### ISSUE TITLE
Document custom registries and gulp.registry API

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1003]
We have a new API in gulp 4.0 (`gulp.registry`) which hasn't been documented in the API.md file. See https://github.com/phated/undertaker#registryregistryinstance for more information.

Also, I think it would be helpful to have a custom-registries.md that reflects the information in https://github.com/phated/undertaker#custom-registries but in a more gulp-specific context.

@dinoboff would you be able to tackle this?

**Comment by phated** [comment]
Looking for help on tackling this docs issue.  Anyone available?

**Comment by SyntaxRules** [comment]
Added some documentation to the API.md file.

I'm struggling to see how to get https://github.com/phated/undertaker#custom-registries into a more gulp-specific context. The example from https://github.com/gulpjs/gulp/issues/986 shows a good example of using this feature. Is splitting out the gulpfile into multiple registries(or files) the only use case for this feature?

**Comment by callumacrae** [comment]
It could be used to build a collection of generic tasks used across a company, from the looks of things. For example, they've got loads of projects where they use Sass, and then they run autoprefixer, RECESS, and a minifier on it—would a registry be useful there to avoid duplication of tasks in many repositories?

**Comment by SyntaxRules** [comment]
Example to test my understanding...

```js
var gulp = require('gulp');

var companyTasks = require('myCompanyTasksRegistry');

gulp.registry(companyTasks);

gulp.task('one', gulp.parallel('someCompanyTask', function(done) {
   console.log('in task one');
   done();
});
```

In this example `myCompanyTasksRegistry` is and npm module that I'm using that has some predefined tasks for me. The benefit of this is that others can leverage npm to get bug fixes, the latest code, etc... without having to copy and paste over files.

the `myCompanyTasksRegistry` file might look like this:

```js
var util = require('util');
var del = require('del');

var DefaultRegistry = require('undertaker-registry');

function myCompanyTasksRegistry(){
  DefaultRegistry.call(this);

this.set('clean', function(cb){
    del([buildDir], cb);
  });
this.set('someCompanyTask', function(done) {
  done()'
});

util.inherits(MyRegistry, DefaultRegistry);

module.exports = myCompanyTasksRegistry;
```

@callumacrae  Does this cover the use case you are talking about?
@phated Does this look like a a good addition to the gulp docs?

**Comment by phated** [comment]
@SyntaxRules yeah, other than a syntax error, that looks good and right along the lines of what @callumacrae was describing.  Sorry I didn't answer the other question sooner.

Custom registries allow 3 main things:
* Sharable collections of tasks (like above)
* Custom behavior for your tasks (like binding metadata to the function for access with `this`)
* Other behavior that needs to hook into the registry lifecycle (see gulp-hub)

**Comment by tunnckoCore** [comment]
looks good, yea.
@phated undertaker is awesome and works awesome, soon I'll commit testing runner on top of it.

[quick look](https://github.com/tunnckoCore/ideas/issues/9) :)

**Comment by callumacrae** [comment]
That perfectly describes my use case :+1:

**Comment by SyntaxRules** [comment]
Ok, added this example to the pull request #1021 (After I made sure syntax was correct and I tested it on my machine). I also added the use cases that @phated suggested, with some modification.

Does this look good? Does anyone have any suggestions or think we need additional documentation we need for this section?

**Comment by phated** [comment]
I'm out for the next week. I will review when I get back.

**Comment by contra** [comment]
Pending review from @callumacrae on #1021

**Comment by phated** [comment]
This has been merged.  The documentation has outlined some issues that need to be tackled in undertaker but the docs look good.  If I make any changes that need to be reflected in the docs, I will update at that time.  Closing this as done.

**Comment by barischrooneyj** [comment]
https://gulpjs.com/docs/en/api/registry

The "Creating Custom Registries" link does not work
