### ISSUE TITLE
Document gulp.tree API

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1004]
We have a new method exposed ([`gulp.tree()`](https://github.com/phated/undertaker#treeoptions--object)) that allows users or outside tools to get the registered tasks.  We need to document this in API.md

**Comment by SyntaxRules** [comment]
I think you want this in two parts:
1. For the cli (in gulp-cli repo)
2. The api tree for other people to get

### For part 1:

Do you want this in the [gulp-cli repo](https://github.com/gulpjs/gulp-cli/blob/4.0/docs/CLI.md) or in the [gulp repo](https://github.com/gulpjs/gulp-cli/blob/4.0/docs/CLI.md)?

It looks like there is a line or two in there. **Is this sufficient?** It could certainly be beefed up with pictures and examples if you think its worth the time. Disclosure: I'd like to get gulp 4 released as soon as possible.
![image](https://cloud.githubusercontent.com/assets/4117657/7053728/32d7f158-ddec-11e4-85ed-da2d7bdf0ce6.png)

#### References:

- https://github.com/gulpjs/gulp-cli/blob/4.0/lib/versioned/%5E4.0.0-alpha.1/index.js#L28
- https://github.com/gulpjs/gulp-cli/blob/4.0/docs/CLI.md
- https://github.com/gulpjs/gulp/blob/4.0/docs/CLI.md

### For part 2:

I'm planning adding a blurb in [API.md](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md). Showing an example with deep and an example without- then [referencing to the undertaker](https://github.com/phated/undertaker#treeoptions--object)

If that sounds good, I'll submit a pull request soon.

#### References:

- https://github.com/phated/undertaker#treeoptions--object
- https://github.com/gulpjs/gulp/blob/4.0/docs/API.md

**Comment by phated** [comment]
Thanks for tackling this issue. All docs can be PRed here, as we are also building out the gulp website with all the docs (cli, gulp, etc). All of your outline sounds good.

**Comment by contra** [comment]
@phated I think we let the docs finalize here then prior to 4.0 release we can auto-import them into the new website

**Comment by phated** [comment]
@contra I agree.  Hence the issues

**Comment by SyntaxRules** [comment]
PR, linked and ready for review. Thanks!

**Comment by phated** [comment]
@SyntaxRules thanks, merged.
