### ISSUE TITLE
Self reloading issue

### ISSUE THREAD

**Issue by mudetroit** [gulpjs/gulp#1009]
I have set up gulp so that it will reload when the gulpfile is modified. That basic process is working, but for some reason it seems the old tasks are not being terminated properly.

```javascript
    var gulp = require('gulp');
    var less = require('gulp-less');
    var spawn = require('child_process').spawn;

    gulp.task('default', function(){
    	var p;

    	if(p)
    		p.kill();

    	p = spawn('gulp', ['watch'], {stdio: 'inherit'});
    });

    gulp.task('watch', ['styles', 'watch-styles', 'watch-gulp']);

    gulp.task('styles', function(){
    	return gulp.src('./***.less')
    	.pipe(less())
    	.pipe(gulp.dest('./'))
    });

    gulp.task('watch-styles', ['styles'], function(){
    	gulp.watch('./**/*.less', ['styles']);
    });

    gulp.task('watch-gulp', ['styles'], function(){
      gulp.watch('./gulpfile.js', ['default']);
    });
```

That is a basic gulpfile that demonstrates the problem. When I tweak that gulpfile to cause it to reload I receive this in the console:

```
    [11:21:02] Starting 'default'...
    [11:21:02] Finished 'default' after 5.25 ms
    [11:21:02] Using gulpfile ~/repo/gulp-reload/gulpfile.js
    [11:21:02] Starting 'styles'...
    [11:21:02] Finished 'styles' after 34 ms
    [11:21:02] Starting 'watch-styles'...
    [11:21:03] Finished 'watch-styles' after 669 ms
    [11:21:03] Starting 'watch-gulp'...
    [11:21:03] Finished 'watch-gulp' after 1.83 ms
    [11:21:03] Starting 'watch'...
    [11:21:03] Finished 'watch' after 2.92 μs
```

Then modifying a less file within the directory gives this output

```
    [11:21:24] Starting 'styles'...
    [11:21:24] Finished 'styles' after 8.95 ms
    [11:21:24] Starting 'styles'...
    [11:21:24] Finished 'styles' after 2.92 ms
```

Each subsequent restart seems to lead to an additional call to styles, as if the old watchers are still there.

This is problem is cross posted at [StackOverflow](http://stackoverflow.com/questions/29519142/duplicate-tasks-on-self-reloading-gulp), and created a [git repo with all the example code](https://github.com/mudetroit/gulp-self-reload-problem).

**Comment by tkellen** [comment]
This probably has something to do with the fact that gulp is a cached global singleton (gross).

**Comment by callumacrae** [comment]
This is what I do, and it works:

https://github.com/Lostmyname/lmn-gulp-tasks/blob/master/tasks/auto-reload.js

Effectively:

```js
var spawn = require('child_process').spawn;

gulp.task('js', function () {
    var process;

    function restart() {
      if (process) {
        process.kill();
      }

      process = spawn('gulp', ['default'], { stdio: 'inherit' });
    }

    gulp.watch('gulpfile.js', restart);
    restart();
});
```

**Comment by phated** [comment]
I wonder if this is a gaze thing. @shama any thoughts?

**Comment by shama** [comment]
I don't think this would be a gaze thing as if you tell the process to die that gaze is watching under, it will happily do so. I think the example @mudetroit posted might not be creating/destroying the processes properly.

FWIW, I don't think you even need to spawn processes to accomplish this though. On grunt-contrib-watch, we just delete the require cache: https://github.com/gruntjs/grunt-contrib-watch/blob/master/tasks/lib/taskrunner.js#L338 and then re-require the file.

**Comment by mudetroit** [comment]
It is entirely possible that I am doing something wrong in there, but not certain where it is going wrong. I am going to try tweaking it a bit towards the implementation @callumacrae posted. Will update later tonight.

**Comment by mudetroit** [comment]
Okay, I made modifications to my build similar to @callumacrae's implementation, and the issue seems to be resolved. My gut feeling, which I will try to test tomorrow evening, is that the underlying problem has something to do with the the task containing gulp-watch was part of the process being killed and restarted.

**Comment by mudetroit** [comment]
The [Stackoverflow question](http://stackoverflow.com/questions/29519142/duplicate-tasks-on-self-reloading-gulp/29533920#29533920) yielded an answer that seems pretty close to accurate, as to the base source of the problem. Basically. the way it was structured I wasn't keeping a good reference to the process so it wasn't killing the old process just spawning a new one each time.

Will go ahead and close this as it appears to be my own mistake and not anything more insidious.
