### ISSUE TITLE
No way to add args to gulp task

### ISSUE THREAD

**Issue by sonewman** [gulpjs/gulp#1014]
Despite reference to the [documentation](https://github.com/gulpjs/gulp/blob/master/docs/CLI.md#task-specific-flags) this feature has appeared to have gone away.

I have tried everything but the CLI seems to pass the args first and assumes all arguments (if not documented flags) are task names.

This results in the following:
```bash
§ gulp mocha:/Users/sam/code/some-spec.js
[00:08:20] Using gulpfile ~/code/gulpfile.js
[00:08:20] Task 'mocha:/Users/sam/code/some-spec.js' is not in your gulpfile
[00:08:20] Please check the documentation for proper gulpfile formatting
```
:disappointed: perhaps it would be possible to add and option for args to be supplied after `--` like `npm` does? Unless there is another obvious way I have missed.

**Comment by tkellen** [comment]
I'm guessing you're coming from Grunt or Rake?

To pass an argument, you'll want `gulp --my_flag taskname`

**Comment by sonewman** [comment]
I have used both in the passed. But not exclusively, however the example above used to work I only just recently noticed it wasn't.

I was using it to specify a particular glob match to run unit test specifically if listed, but what you are suggesting is that I have to use some kind of arg parsing module and actually prefix the option. 

I just wanted to pass the file specific glob after the task name and use `process.argv.slice(3)` to grab the files if any.

I will also likely need to use `minimist` so it is parsed in the same manor as the gulp args in comparison to say `commander`.

**Comment by contra** [comment]
Yep - you should use minimist to parse command line args.
