### ISSUE TITLE
getting random error (Error: Uncaught, unspecified "error" event)

### ISSUE THREAD

**Issue by tugberkugurlu** [gulpjs/gulp#1015]
I am randomly getting the following error and I don't seem to understand why:

> events.js:87
>       throw Error('Uncaught, unspecified "error" event.');
>             ^
> Error: Uncaught, unspecified "error" event.
>     at Error (native)
>     at DestroyableTransform.emit (events.js:87:13)
>     at DestroyableTransform.onerror (C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-gitshasuffix\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:558:12)
>     at DestroyableTransform.emit (events.js:107:17)
>     at onwriteError (C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
>     at onwrite (C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
>     at WritableState.onwrite (C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
>     at afterTransform (C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
>     at TransformState.afterTransform (C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
>     at C:\TeamCity\buildAgent\work\df3412d10f4cb065\src\ConfyConf.Client.Web\node_modules\gulp-minify-css\index.js:113:9

Is this a familiar to any known issues? I don't know what would help to narrow this down as at same state it happens in on run and doesn't happen on the other. Also, the error message is no help.

**Comment by contra** [comment]
The stacktrace singles out two plugins: gulp-minify-css and gulp-gitshasuffix
