### ISSUE TITLE
Any docset for dash/zeal ?

### ISSUE THREAD

**Issue by labo-css** [gulpjs/gulp#1016]
I just want to browse the docs while offline.

**Comment by contra** [comment]
We had manpages at one point not sure what happened to those. You can open `node_modules/gulp/docs` and browse that IIRC

**Comment by labo-css** [comment]
Sorry, i don't understand, i want them to be integrated in my zeal app. http://zealdocs.org/
Grunt is already in there.

**Comment by contra** [comment]
@labo-css I'm open to it I don't see any instructions anywhere on how to put docs in there though

**Comment by labo-css** [comment]
Maybe this can help, i don't know where to start :/
https://kapeli.com/docsets

Zeal use the same docsets than Dash an app for mac users.

**Comment by csyisaiko** [comment]
no more time

**Comment by contra** [comment]
@csyisaiko please stop spamming bullshit across our issues, thanks :wink:

**Comment by Grawl** [comment]
:+1:

**Comment by williamli** [comment]
+1

**Comment by contra** [comment]
PR?

**Comment by rkhayat** [comment]
+1

**Comment by Kapeli** [comment]
Gulp is now available in Dash since version 3.1.0.

**Comment by labo-css** [comment]
Thanx! :)

**Comment by Grawl** [comment]
cool :з

**Comment by vilellaj** [comment]
As a Windows user, I would love this docs on Zeal,
Let's make it happen ?!

**Comment by trollixx** [comment]
Zeal provides all officially supported Dash docsets, and Gulp is among them.

**Comment by vilellaj** [comment]
Thank you :D
