### ISSUE TITLE
Grunt style template strings expanding config data

### ISSUE THREAD

**Issue by inquire** [gulpjs/gulp#1017]
http://gruntjs.com/api/grunt.template

"grunt.template

Template strings can be processed manually using the provided template functions. In addition, the config.get method (used by many tasks) automatically expands <% %> style template strings specified as config data inside the Gruntfile."

Does gulp have support for this? Judging by the source code, i couldn't find anything like that. 

Was this ever considered?

**Comment by tkellen** [comment]
No, but you can use https://github.com/tkellen/js-expander if you want this sort of functionality in your gulpfile.
