### ISSUE TITLE
Gulp stats slow on call. Execute is fast

### ISSUE THREAD

**Issue by Rupertje** [gulpjs/gulp#1018]
What is causing Gulp to need 15 seconds before it starts? Anyone having a fix, or information what causes this?

I'm using Gulp in a Vagrantbox. Calling Gulp from a terminal inside PHPStorm.

**Comment by callumacrae** [comment]
Probably a vagrant problem—I used to run my gulpfile outside of my vagrant box for that reason.

Follow steps here: https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck

If that doesn't work, try running Gulp outside of the vagrant box. If you install node and npm using nvm, it's really easy to remove without leaving any apps or files anywhere.

**Comment by Rupertje** [comment]
> If that doesn't work, try running Gulp outside of the vagrant box. If you install node and npm using nvm, it's really easy to remove without leaving any apps or files anywhere.

@callumacrae I'm bit of a newbie with all of this to be honest. How do I do this?

**Comment by callumacrae** [comment]
https://github.com/creationix/nvm#install-script
