### ISSUE TITLE
bus error

### ISSUE THREAD

**Issue by maxlibin** [gulpjs/gulp#102]
Hi, I am keep getting this error when watching

```
var gulp = require('gulp');
var sass = require('gulp-sass');


gulp.task('dosass',function(){
    gulp.src('./sass/test.scss').pipe(sass()).pipe(gulp.dest('./sass/css'));
})

gulp.task('default', function(){
    // watch task
    gulp.run('dosass');
    gulp.watch('./sass/test.scss', function(){
        gulp.run('dosass');
    });
});
```

output:
[gulp] Running 'default'...
[gulp] Running 'dosass'...
[gulp] Finished 'dosass' in 4.52 ms
[gulp] Finished 'default' in 17 ms
[1]    6897 bus error  gulp

**Comment by thisispete** [comment]
dunno if it helps but I just noticed I get a bus error when I have an endless loop in a recursive scss mixin.. 
this is grossly oversimplifying, mine was nested in a bunch of logic, but this will throw the gulp bus error on the sass compiler:
```
@function myfunc($var) {
  @return myfunc($var)
}
```
