### ISSUE TITLE
after splitting gulpfile.js into multiple files, running command does not return to shell

### ISSUE THREAD

**Issue by todzheng** [gulpjs/gulp#1020]
when I have everything in gulpfile.js, running "gulp clean" correctly delete files and return to shell.

when I split clean task to clean.js in gulp directory, the file looks like:
'use strict';

var del = require('del');
var gulp = require('gulp');
gulp.task('clean', function (cb) {
    return del(['dist/**/*'], cb);
});

after my gulpfile.js looks like:

(function () { 
'use strict'; 
var gulp = require('gulp'); 
require('require-dir')('./gulp'); 
}());

then run "gulp clean", it does not return to shell and I have to use CTRL+C

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)
