### ISSUE TITLE
Nested gulp.src doesn't work in the same directory

### ISSUE THREAD

**Issue by drinchev** [gulpjs/gulp#1022]
I'm not completely sure this is a bug or a side-effect, but anyway I'm having the following issue :

With a directory structure that looks like :

```
    Gulpfile.js
    node_modules/
    scripts/
    scripts/a.js
    scripts/b.coffee
    package.json
```

and content of a.js :

```
    fileA
```

and b.js :

```
    fileB
```

with my Gulpfile.js :

```
var gulp = require('gulp'),
    concat = require('gulp-concat');

gulp.task('scripts', function() {

	gulp.src('scripts/**/*.coffee')
	    .pipe(gulp.src('scripts/**/*.js'))
	    .pipe(concat('all.js'))
	    .pipe(gulp.dest('build'));	

});
```

I have the final file all.js having content :

```
    fileB
```

Initially I tried to convert coffeescript and then concatenate javascripts file to a final build file, but after the things didn't work out, I simplified the code to this demo.

My version of gulp is : 3.8.11 ( as reported by `gulp -v` ) on a OS X

Do you have any ideas why this is happening?

**Comment by contra** [comment]
Piping to gulp.src is broken right now, use gulp-add-src as a workaround. There is a ticket open for this already but I'm on mobile. I think this is fixed in 4.0 already

**Comment by drinchev** [comment]
Thanks for the fast reply.

**Comment by dinoboff** [comment]
confirming it's working in gulp 4.0
