### ISSUE TITLE
Dependencies for a gulp.task(fn) in v4

### ISSUE THREAD

**Issue by mikehaas763** [gulpjs/gulp#1025]
Is the api gulp.task(fn) not supposed to have direct dependencies as opposed to the gulp.task(name, fn) api? I may be trying to use an interface that gulp will not support so any guidance is welcome.

This one does not run the clean task
```javascript
var gulp = require('gulp');
var clean = require('./clean');

module.exports = javascript;

gulp.task(javascript, gulp.series(clean));
function javascript() {
    return gulp.src(['./app/**/*', './appdev/**/*'], { base: '.' })
        .pipe(gulp.dest('./www'));
}
```

This one will run the clean task
```javascript
var gulp = require('gulp');
var clean = require('./clean');

module.exports = javascript;

gulp.task('javascript', gulp.series(clean, javascript));
function javascript() {
    return gulp.src(['./app/**/*', './appdev/**/*'], { base: '.' })
        .pipe(gulp.dest('./www'));
}
```

**Comment by dinoboff** [comment]
In gulp 4, task are just async functions. `gulp.task` is only used to register a task for the CLI and the first optional argument is to provide a name for the task. There's no support for dependencies.

I am guessing your example could be written like:
```js
// clean.js
var gulp = require('gulp');
var del = require('del');

module.exports = function clean(done) {
  del(['./www', done]);
}

// javascript.js
var gulp = require('gulp');

module.exports = function javascript() {
  return gulp.src(['./app/**/*', './appdev/**/*'], { base: '.' })
    .pipe(gulp.dest('./www'));
}

// gulpfile.js
var gulp = require('gulp');
var clean = require('./clean');
var javascript = require('./javascript');

gulp.task('build', gulp.series(clean, javascript));
```
That would create the `clean` and `javascript` tasks and register a third task - the only one accessible from the cli - that combine `clean` and `javascript`.

**Comment by phated** [comment]
Answered very well by @dinoboff - closing

**Comment by mikehaas763** [comment]
Thank you @dinoboff. That was very clear. I think my misunderstanding stems from being a gulp user prior to v4. Some doc updates could probably fix the misunderstanding for others once it's actually released. If I get a few minutes I may submit a PR with suggested updates.

What happened for me was that the examples using gulp.series() and gulp.parallel() look an awful lot like the original dependency arrays. I didn't realize that what they actually do is just return an async function so it's just like defining any other task.
