### ISSUE TITLE
Gulp not working on io.js v.1.6

### ISSUE THREAD

**Issue by diokey** [gulpjs/gulp#1026]
I want to use gulp in my project that uses io.js v.1.6.0 but when i try to run `gulp` i get an error
```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
          ^
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.basename (path.js:560:3)
    at Liftoff.buildEnvironment 
```
I tried re-installing gulp but with no success. Is this a known issue? I saw there was some issues with previous version of io.js https://github.com/gulpjs/gulp/issues/873 but i thought it was fixed.

**Comment by dinoboff** [comment]
gulp 3.8.11 and gulp 4.0 work fine for me with io.js 1.6 or 1.7

**Comment by tunnckoCore** [comment]
> gulp 3.8.11 and gulp 4.0 work fine for me with io.js 1.6 or 1.7

:+1:  same here

**Comment by phated** [comment]
2 people tested successfully - closing.
