### ISSUE TITLE
Using coffee-script for gulpfile will break with the next release of CS

### ISSUE THREAD

**Issue by xixixao** [gulpjs/gulp#103]
With the next release of CS, requiring `coffee-script` won't autoregister `.coffee` extensions. Instead, requiring `coffee-script/register` will be required.

This can be fixed by changing the README when the time comes, but I'd opt for a different solution, that would allow .coffee config without having to specify the registration every time (short of an alias).

See https://github.com/jashkenas/coffee-script/pull/3279

**Comment by bioball** [comment]
Out of box support for CS doesn't seem to work for me without a local installation of CS. Is anybody else seeing this?

**Comment by heikki** [comment]
@bioball AFAIK it is expected behaviour.

**Comment by contra** [comment]
You have to install coffee-script to be able to use it.
