### ISSUE TITLE
Add details of last few patches to changelog

### ISSUE THREAD

**Issue by callumlocke** [gulpjs/gulp#1032]

**Comment by callumacrae** [comment]
Is this actually an issue or just a PR that nobody has written yet?

**Comment by callumlocke** [comment]
An issue. Gulp is at 3.8.11 but the changelog doesn't say what has changed since 3.8.5

**Comment by contra** [comment]
@callumlocke Just dep updates to pull in fixes from other projects AFAIK and maybe some docs, no API changes

**Comment by phated** [comment]
Done
