### ISSUE TITLE
using `--tasks-json` leads to an exponential output growth

### ISSUE THREAD

**Issue by segrey** [gulpjs/gulp#1033]
Extracted from https://github.com/gulpjs/gulp/issues/584#issuecomment-54274928

Listing all dependencies deep inside may lead to exponential growth of output if using `--tasks-json`.

Example:

```javascript
var gulp = require('gulp');
gulp.task('a1', function () {});
gulp.task('a2', gulp.series('a1'));
gulp.task('a3', gulp.series('a1', 'a2'));
gulp.task('a4', gulp.series('a2', 'a3'));
```

```
gulp --tasks-json | wc -l
121
```

---

```javascript
var gulp = require('gulp');
gulp.task('a1', function () {});
gulp.task('a2', gulp.series('a1'));
gulp.task('a3', gulp.series('a1', 'a2'));
gulp.task('a4', gulp.series('a2', 'a3'));
gulp.task('a5', gulp.series('a3', 'a4'));
```

```
gulp --tasks-json | wc -l
230
```

---

```javascript
var gulp = require('gulp');
gulp.task('a1', function () {});
gulp.task('a2', gulp.series('a1'));
gulp.task('a3', gulp.series('a1', 'a2'));
gulp.task('a4', gulp.series('a2', 'a3'));
gulp.task('a5', gulp.series('a3', 'a4'));
gulp.task('a6', gulp.series('a4', 'a5'));
```

```
gulp --tasks-json | wc -l
414
```

A possible fix would be to skip outputting dependencies of the seconds level or higher.

**Comment by phated** [comment]
@segrey what would you think of a `level` option.  This could be handled with `gulp --tasks-json=2`.  I don't want to completely remove the full tree because it can be useful for debugging task combinations.  Thoughts?

**Comment by segrey** [comment]
@phated Having `gulp --tasks-json=2` is fine, but, truth to be told, I don't see why the full tree could be needed. I can be wrong, but looks like all information is provided by the first level (task name, description) and the second level (tasks dependencies). Seems deeper levels give no new information.
Moreover, the second level could be compacted by referencing dependent tasks by name omitting task description.

**Comment by contra** [comment]
@segrey good point

**Comment by phated** [comment]
@segrey in gulp 4, we allow function composition to be infinitely nested.  Take this example:

```js
gulp.task('combined',
  gulp.series(
    clean,
    gulp.parallel(js, css, img),
    gulp.series(
      some,
      other,
      gulp.parallel(thing, stuff)
    )
  )
); 
```

I want to be able to visualize this tree, especially from the standpoint of gulp no longer automatically calculating it for you.

**Comment by segrey** [comment]
@phated Ah indeed, thanks for the example. Then, I guess restricting output by levels is not very correct. How about another fix: when breadth traversing a task tree don't include full JSON for already visited tasks, instead, reference these tasks by their names?

**Comment by phated** [comment]
@segrey we could do something like that, but our implementation is a bit naive; anytime you call `gulp.task`, `gulp.series` or `gulp.parallel`, we save the dependency __name__ into a WeakMap. We don't distinguish tasks by name in gulp 4.0, so you can do something like the following:

```js
// named function to be used in composition
function hello(){}

// anonymous function registered as task, to be referenced at CLI and looked up by the string
gulp.task('hello', function(){});

// references 2 different "tasks" named hello and will log them both as "hello" with --tasks
gulp.task('world', gulp.parallel(hello, 'hello'));
```

**Comment by segrey** [comment]
>We don't distinguish tasks by name in gulp 4.0, so you can do something like the following

@phated Thanks, got it. The problem is that "name" field doesn't identify a task uniquely, because there are tasks with "task" and "function" types. Two questions if you please:
* Are there other task types except "task" and "function"?
* Is it correct that "name" field uniquely identifies a task among all tasks with "task" type? If yes, then the suggested fix could be rephrased like this: when breadth traversing a task tree don't include full JSON for already visited tasks with "task" type, instead, reference these tasks by their names.

**Comment by phated** [comment]
Deferring to gulp-cli 1.2.0

**Comment by phated** [comment]
@segrey It looks like a `depth` option will be added in the next CLI release.  Ref https://github.com/gulpjs/gulp-cli/pull/50

**Comment by segrey** [comment]
Great! Thank you.

**Comment by phated** [comment]
In 1.2.0, we've added a `--depth` flag but it doesn't apply to the `--tasks-json` flag.  I've created an issue at https://github.com/gulpjs/gulp-cli/issues/57

**Comment by sttk** [comment]
@segrey I've applied `--depth` flag to `--tasks-json` tentatively in gulpjs/gulp-cli#57.

However, I think the json data which are cut child tasks of series/parallel tasks by this `--depth` flag would not be useful. So I'll try to add an option value `--depth=nonrecursive` (or another appropriate name) which outputs a tree until first child tasks that are not series/parallel tasks.

Please tell me your needs.

**Comment by segrey** [comment]
@sttk agree, cutting child tasks is not useful, `--depth=nonrecursive` is what I'd like to have. The idea is to fetch whole gulp task structure without losing any information.

**Comment by phated** [comment]
I'd like to move discussion to gulpjs/gulp-cli#57 (and any related PRs that come from it) so I'm closing this.
