### ISSUE TITLE
Pass arguments to task

### ISSUE THREAD

**Issue by pronebird** [gulpjs/gulp#1036]
Is it possible to create a task that accepts arguments from console? E.g. `gulp task --silent`.

**Comment by tunnckoCore** [comment]
Shortly, no. Just build another CLI for your wants, design it as you want and from there extract the name of the task which want to run.

**Comment by tunnckoCore** [comment]
But yea, sound like a good idea. Gulp and Undertaker is just packages and everybody can use them to build another great tool on top of them.

**Comment by contra** [comment]
not sure what he is talking about ^

yes it is absolutely possible, just use the minimist module or any other CLI arg parsing module

**Comment by tunnckoCore** [comment]
> yes it is absolutely possible, just use the minimist module or any other CLI arg parsing module

exactly, just because the are packages like every other package in the ecosystem.

> Shortly, no. 

I answered like that, because this isn't responsibility of these packages, but yea, it not mean it not possible at all.

**Comment by vlizard** [comment]
[This recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/pass-arguments-from-cli.md) looks like the answer.

**Comment by pronebird** [comment]
@vlizard wow exactly what I need. Thanks everyone!
