### ISSUE TITLE
Documentation references unpublished module

### ISSUE THREAD

**Issue by SimenB** [gulpjs/gulp#1041]
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/recommended-modules.md

https://github.com/wearefractal/BetterError is not on npm.

**Comment by contra** [comment]
@SimenB Still working on it...

**Comment by SimenB** [comment]
@contra Sure, just a bit weird saying it's recommended when it's unpublished.

I see you updated the documentation now :smile:
