### ISSUE TITLE
Gulp startup slow?

### ISSUE THREAD

**Issue by fbm-static** [gulpjs/gulp#1044]
Have you guys started to insert some analytics stuff to "analyze" our behavior with the gulp cli. The startup is considerably slow against a simple 'node -v'.

Thanks.

**Comment by sindresorhus** [comment]
Run https://github.com/jaguard/time-require and paste in the output.

**Comment by fbm-static** [comment]
```
Start time: (2015-04-27 23:45:16 UTC) [treshold=1%]

 #  module                                           time  %
 1  vinyl-fs (node_modules...es\vinyl-fs\index.js)   1.1s  ■ 2%
 2  gulp (node_modules\gulp\index.js)                1.2s  ■ 2%
 3  gulp-less (node_modules\gulp-less\index.js)      2.3s  ■■ 3%
 4  gulp-filter (node_modu...gulp-filter\index.js)  954ms  ■ 1%
 5  gulp-postcss (node_mod...ulp-postcss\index.js)   1.1s  ■ 2%
 6  gulp-uglify (node_modu...gulp-uglify\index.js)  706ms  ■ 1%
 7  vinyl-fs (node_modules...es\vinyl-fs\index.js)  749ms  ■ 1%
 8  decompress-tar (node_m...ompress-tar\index.js)  736ms  ■ 1%
 9  decompress-tarbz2 (nod...ress-tarbz2\index.js)  833ms  ■ 1%
10  download (node_modules...es\download\index.js)   3.1s  ■■■ 4%
11  bin-wrapper (node_modu...bin-wrapper\index.js)   4.9s  ■■■■ 7%
12  ./lib (node_modules\gu...ifsicle\lib\index.js)   4.9s  ■■■■ 7%
13  gifsicle (node_modules...es\gifsicle\index.js)     5s  ■■■■ 7%
14  imagemin-gifsicle (nod...in-gifsicle\index.js)     5s  ■■■■ 7%
15  decompress-tarbz2 (nod...ress-tarbz2\index.js)  779ms  ■ 1%
16  download (node_modules...es\download\index.js)   2.8s  ■■ 4%
17  bin-wrapper (node_modu...bin-wrapper\index.js)   4.3s  ■■■ 6%
18  ./lib (node_modules\gu...ran-bin\lib\index.js)   4.3s  ■■■ 6%
19  jpegtran-bin (node_mod...pegtran-bin\index.js)   4.3s  ■■■ 6%
20  imagemin-jpegtran (nod...in-jpegtran\index.js)   4.3s  ■■■ 6%
21  download (node_modules...es\download\index.js)   2.4s  ■■ 3%
22  bin-wrapper (node_modu...bin-wrapper\index.js)   3.8s  ■■■ 5%
23  ./lib (node_modules\gu...png-bin\lib\index.js)   3.8s  ■■■ 5%
24  optipng-bin (node_modu...optipng-bin\index.js)   3.8s  ■■■ 5%
25  imagemin-optipng (node...min-optipng\index.js)   4.1s  ■■■ 6%
26  decompress-targz (node...press-targz\index.js)  752ms  ■ 1%
27  download (node_modules...es\download\index.js)   2.5s  ■■ 4%
28  bin-wrapper (node_modu...bin-wrapper\index.js)   3.6s  ■■■ 5%
29  ./lib (node_modules\gu...ant-bin\lib\index.js)   3.6s  ■■■ 5%
30  pngquant-bin (node_mod...ngquant-bin\index.js)   3.7s  ■■■ 5%
31  imagemin-pngquant (nod...in-pngquant\index.js)   3.7s  ■■■ 5%
32  imagemin-svgo (node_mo...agemin-svgo\index.js)  760ms  ■ 1%
33  imagemin (node_modules...es\imagemin\index.js)    19s  ■■■■■■■■■■■■■ 27%
34  gulp-imagemin (node_mo...lp-imagemin\index.js)  19.9s  ■■■■■■■■■■■■■ 28%
35  autoprefixer-core (nod...\lib\autoprefixer.js)  933ms  ■ 1%
36  ./utils (node_modules\...er-sync\lib\utils.js)   1.6s  ■■ 2%
37  ./async (node_modules\...er-sync\lib\async.js)   1.6s  ■■ 2%
38  ./async-tasks (node_mo...c\lib\async-tasks.js)   1.6s  ■■ 2%
39  ./lib (node_modules\br...cket.io\lib\index.js)   1.5s  ■ 2%
40  socket.io (node_module...s\socket.io\index.js)   1.5s  ■ 2%
41  ./sockets (node_module...-sync\lib\sockets.js)   1.6s  ■■ 2%
42  ./lib/UI (node_modules...er-sync-ui\lib\UI.js)  825ms  ■ 1%
43  browser-sync-ui (node_...ser-sync-ui\index.js)  864ms  ■ 1%
44  ./lib/browser-sync (no...\lib\browser-sync.js)     5s  ■■■■ 7%
45  browser-sync (node_mod...rowser-sync\index.js)     5s  ■■■■ 7%
46  d:\www\wordpress\wp-co...file.js (gulpfile.js)  33.9s  ■■■■■■■■■■■■■■■■■■■■■■ 48%
47  micromatch (node_modul...\micromatch\index.js)  930ms  ■ 1%
48  anymatch (node_modules...es\anymatch\index.js)     1s  ■ 1%
49  ./stream (node_modules...lib\public\stream.js)     1s  ■ 1%
50  ./lib/public/reload (n...lib\public\reload.js)   1.1s  ■ 1%
Total require(): 4760
Total time: 1m 10.4s
```

**Comment by callumacrae** [comment]
imagemin depends on three packages which all have basically the same dependencies, which means that there are a tonne of duplicate requires, and [require is slow](https://kev.inburke.com/kevin/node-require-is-dog-slow/). What happens if you run [npm dedupe](http://4waisenkinder.de/blog/2014/06/09/flatten-your-dependencies-with-npm-dedupe/) and try again?

Also, what is file 46?

**Comment by fbm-static** [comment]
@callumacrae it's the gulpfile.js itself I think. Just a bunch of requires and gulp.task definitions. What's weird is it runs faster on the second run.

**Comment by RnbWd** [comment]
I hypothesize the task manager (orchestrator) is responsible... Using vinyl-fs + meow + <insert favorite task manager> decreased the start time on my machine from > 1s to < 100 ms (just estimated times, no benchmarks). I concur the start time is slow - but I don't know why.

**Comment by callumacrae** [comment]
Is there any delay when you use just orchestrator?

Does it happen if you use Gulp 4, which replaces orchestrator with undertaker?

**Comment by elijahwww** [comment]
I am new to node/gulp. I am getting terrible start times with gulp and completely randomly. Sometimes it kicks off in a few seconds, sometimes a full minute will pass. Here's time-require output. I'm using gulp@3.8.11

What do you think could be causing this? Is it trying to get to git to verify some dependencies?

>Start time: (2015-05-18 16:21:05 UTC) [treshold=0%,sorted]
>  # [order]  module                                                                   time  %
>   1 [5931]  /Users/xxxxxxx/Documents/ddddddddddddddd/gulpfile.js (gulpfile.js)      39.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
>   2 [4088]  /Users/xxxxxxx/Documents/ddddddddd.../images.js (gulp/tasks/images.js)  20.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
>   3 [4085]  gulp-imagemin (node_modules/gulp-imagemin/index.js)                     20.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
>   4 [4084]  imagemin (node_modules/gulp-imagemin/node_modules/imagemin/index.js)    20.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 51%
>   5 [2940]  imagemin-gifsicle (node_modules/gu...dules/imagemin-gifsicle/index.js)   6.1s  ▇▇▇▇▇▇▇▇▇▇▇ 15%
>   6 [2936]  gifsicle (node_modules/gulp-imagem...e/node_modules/gifsicle/index.js)   6.1s  ▇▇▇▇▇▇▇▇▇▇▇ 15%
>   7 [2935]  ./lib (node_modules/gulp-imagemin/...de_modules/gifsicle/lib/index.js)   6.1s  ▇▇▇▇▇▇▇▇▇▇▇ 15%
>   8 [2932]  bin-wrapper (node_modules/gulp-ima...ode_modules/bin-wrapper/index.js)     6s  ▇▇▇▇▇▇▇▇▇▇▇ 15%

**Comment by contra** [comment]
@elijahwww All of those times say `imagemin` in them so go open a ticket there

**Comment by RapurHarishBabu** [comment]
Hi Everyone I'am New to Node / Gulp. This is my :) Default Theme Workflow. Which i has been working on from 2-3 days... I has spend most of the time in Gulpfile.js to make my WOrkflow Awesome :) But unfortunately, My Gulpfile.js is taking up to 99% compare Other files :( is there a way to reduce the time of Gulpfile.js? Thank you...

Start time: (2015-08-28 18:46:32 UTC) [treshold=1%,sorted]
# [order]  module                                             time  %
 1 [3911]  C:\xampp\htdocs\Site\Gulpfile.js (Gulpfile.js)     4.4s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 99%

 2 [2837]  gulp-imagemin (node_mod...ulp-imagemin\index.js)  756ms  ■■■■■■■■■ 17%
 3  [795]  gulp-jade (node_modules\gulp-jade\index.js)       750ms  ■■■■■■■■■ 17%
 4 [2080]  gulp-jade-php (node_mod...ulp-jade-php\index.js)  691ms  ■■■■■■■■ 16%
 5  [692]  jade (node_modules\gulp...les\jade\lib\index.js)  572ms  ■■■■■■■ 13%
 6 [2835]  imagemin (node_modules\...les\imagemin\index.js)  570ms  ■■■■■■■ 13%
 7 [1944]  jade (node_modules\gulp...les\jade\lib\index.js)  536ms  ■■■■■■ 12%
 8 [3910]  gulp-autoprefixer (node...autoprefixer\index.js)  516ms  ■■■■■■ 12%
 9  [668]  ./parser (node_modules\...es\jade\lib\parser.js)  484ms  ■■■■■■ 11%
10 [1920]  ./parser (node_modules\...es\jade\lib\parser.js)  457ms  ■■■■■ 10%
11  [662]  ./filters (node_modules...s\jade\lib\filters.js)  414ms  ■■■■■ 9%
12 [1914]  ./filters (node_modules...s\jade\lib\filters.js)  390ms  ■■■■■ 9%
13  [305]  gulp (node_modules\gulp\index.js)                 331ms  ■■■■ 7%
14 [3908]  autoprefixer-core (node...e\lib\autoprefixer.js)  318ms  ■■■■ 7%
15 [1410]  gulp-watch (node_modules\gulp-watch\index.js)     302ms  ■■■■ 7%
16 [3229]  gulp-minify-css (node_m...p-minify-css\index.js)  301ms  ■■■■ 7%
17 [3423]  gulp-minify-html (node_...-minify-html\index.js)  245ms  ■■■ 6%
18 [2632]  vinyl-fs (node_modules\...les\vinyl-fs\index.js)  221ms  ■■■ 5%
19  [999]  gulp-sass (node_modules\gulp-sass\index.js)       184ms  ■■ 4%
20  [304]  vinyl-fs (node_modules\...les\vinyl-fs\index.js)  167ms  ■■ 4%
21 [1566]  gulp-plumber (node_modu...gulp-plumber\index.js)  162ms  ■■ 4%
22  [793]  gulp-util (node_modules...es\gulp-util\index.js)  155ms  ■■ 3%
23 [2212]  gulp-util (node_modules...es\gulp-util\index.js)  154ms  ■■ 3%
24 [2581]  ./lib/src (node_modules...l-fs\lib\src\index.js)  152ms  ■■ 3%
25 [3383]  gulp-util (node_modules...es\gulp-util\index.js)  150ms  ■■ 3%
26  [148]  gulp-util (node_modules...es\gulp-util\index.js)  149ms  ■■ 3%
27 [3588]  gulp-util (node_modules...es\gulp-util\index.js)  143ms  ■■ 3%
28 [1565]  gulp-util (node_modules...es\gulp-util\index.js)  142ms  ■■ 3%
29  [661]  clean-css (node_modules...es\clean-css\index.js)  142ms  ■■ 3%
30  [660]  ./lib/clean (node_modul...lean-css\lib\clean.js)  140ms  ■■ 3%
31 [3195]  gulp-util (node_modules...es\gulp-util\index.js)  140ms  ■■ 3%
32 [1674]  transformers (node_modu...s\lib\transformers.js)  138ms  ■■ 3%
33 [2076]  gulp-util (node_modules...es\gulp-util\index.js)  133ms  ■■ 3%
34 [1262]  gulp-util (node_modules...es\gulp-util\index.js)  133ms  ■■ 3%
35  [926]  gulp-util (node_modules...es\gulp-util\index.js)  131ms  ■■ 3%
36  [422]  transformers (node_modu...s\lib\transformers.js)  131ms  ■■ 3%
37 [3907]  ../data/prefixes (node_...core\data\prefixes.js)  130ms  ■■ 3%
38  [473]  uglify-js (node_modules...lify-js\tools\node.js)  127ms  ■■ 3%
39 [1130]  gulp-util (node_modules\gulp-util\index.js)       125ms  ■■ 3%
40 [1670]  uglify-js (node_modules...lify-js\tools\node.js)  122ms  ■■ 3%
41 [1725]  uglify-js (node_modules...lify-js\tools\node.js)  120ms  ■■ 3%
42 [1913]  clean-css (node_modules...es\clean-css\index.js)  117ms  ■■ 3%
43 [1912]  ./lib/clean (node_modul...lean-css\lib\clean.js)  114ms  ■■ 3%
44  [418]  uglify-js (node_modules...lify-js\tools\node.js)  113ms  ■■ 3%
45 [3063]  clean-css (node_modules...es\clean-css\index.js)  112ms  ■■ 3%
46 [3062]  ./lib/clean (node_modul...lean-css\lib\clean.js)  111ms  ■■ 3%
47 [2834]  imagemin-svgo (node_mod...magemin-svgo\index.js)  106ms  ■■ 2%
48 [1341]  chokidar (node_modules\...les\chokidar\index.js)  105ms  ■■ 2%
49  [258]  ./lib/src (node_modules...l-fs\lib\src\index.js)  103ms  ■■ 2%
50 [2832]  svgo (node_modules\gulp...ules\svgo\lib\svgo.js)  100ms  ■■ 2%
51 [3739]  postcss (node_modules\g...ostcss\lib\postcss.js)   80ms  ■ 2%
52 [2821]  ./svgo/config (node_mod...go\lib\svgo\config.js)   80ms  ■ 2%
53 [2818]  js-yaml (node_modules\g...ules\js-yaml\index.js)   75ms  ■ 2%
54  [685]  with (node_modules\gulp...modules\with\index.js)   74ms  ■ 2%
55 [2817]  ./lib/js-yaml.js (node_...s-yaml\lib\js-yaml.js)   72ms  ■ 2%
56 [3866]  ./prefixes (node_module...-core\lib\prefixes.js)   70ms  ■ 2%
57 [3731]  ./processor (node_modul...tcss\lib\processor.js)   69ms  ■ 2%
58 [3422]  minimize (node_modules\...imize\lib\minimize.js)   69ms  ■ 2%
59 [1937]  with (node_modules\gulp...modules\with\index.js)   68ms  ■ 2%
60 [2492]  glob-stream (node_modul...\glob-stream\index.js)   68ms  ■ 2%
61 [3729]  ./lazy-result (node_mod...ss\lib\lazy-result.js)   67ms  ■ 2%
62 [2800]  ./js-yaml/loader (node_...lib\js-yaml\loader.js)   64ms  ■ 1%
63 [1308]  anymatch (node_modules\...les\anymatch\index.js)   57ms  ■ 1%
64 [2742]  imagemin-optipng (node_...emin-optipng\index.js)   54ms  ■ 1%
65 [1306]  micromatch (node_module...s\micromatch\index.js)   54ms  ■ 1%
66 [2301]  buffer-to-vinyl (node_m...fer-to-vinyl\index.js)   50ms  ■ 1%
67 [3506]  ./lib/template (node_mo...-util\lib\template.js)   47ms  ■ 1%
Total require(): 3913
Total time: 4.4s

**Comment by callumacrae** [comment]
@RapurHarishBabu 4.4s isn't slow :frowning: 

I'd suggest using watch tasks to run specific tasks when they need running, instead of running the entire gulpfile every time, if that's what you're doing currently.

**Comment by RapurHarishBabu** [comment]
@callumacrae  Thanks for the Idea about watch tasks i will sure use it when my Workflow  Developing has done :+1:

**Comment by fega** [comment]
I somethimes get 20 seconds, but in others...

Start time: (2016-05-12 16:20:42 UTC) [treshold=1%]
 #  module                                                                                      time  %
 1  gulp-util (node_modules\gulp\node_modules\gulp-util\index.js)                               1.7s  ■■ 2%
 2  ./lib/src (node_modules\gulp\node_modules\vinyl-fs\lib\src\index.js)                        1.5s  ■■ 2%
 3  vinyl-fs (node_modules\gulp\node_modules\vinyl-fs\index.js)                                 2.4s  ■■■ 3%
 4  gulp (node_modules\gulp\index.js)                                                           4.4s  ■■■■■ 5%
 5  gulp-util (node_modules\gulp-hb\node_modules\gulp-util\index.js)                            1.3s  ■■ 1%
 6  ../dist/cjs/handlebars (node_modules\gulp-...odules\handlebars\dist\cjs\handlebars.js)      1.4s  ■■ 2%
 7  handlebars (node_modules\gulp-hb\node_modules\handlebars\lib\index.js)                      1.5s  ■■ 2%
 8  gulp-hb (node_modules\gulp-hb\src\gulp-hb.js)                                               3.9s  ■■■■ 4%
 9  csso (node_modules\gulp-csso\node_modules\csso\lib\index.js)                                1.7s  ■■ 2%
10  gulp-util (node_modules\gulp-csso\node_modules\gulp-util\index.js)                          1.4s  ■■ 2%
11  gulp-csso (node_modules\gulp-csso\index.js)                                                 3.4s  ■■■■ 4%
12  gulp-util (node_modules\gulp-concat\node_modules\gulp-util\index.js)                        1.4s  ■■ 1%
13  gulp-concat (node_modules\gulp-concat\index.js)                                               2s  ■■ 2%
14  gulp-util (node_modules\gulp-csslint\node_modules\gulp-util\index.js)                       1.3s  ■■ 1%
15  gulp-csslint (node_modules\gulp-csslint\index.js)                                           2.2s  ■■■ 2%
16  ./utils (node_modules\browser-sync\lib\utils.js)                                              2s  ■■ 2%
17  ./snippet (node_modules\browser-sync\lib\snippet.js)                                        2.5s  ■■■ 3%
18  ./hooks (node_modules\browser-sync\lib\hooks.js)                                            3.2s  ■■■ 3%
19  ./logger (node_modules\browser-sync\lib\logger.js)                                         983ms  ■ 1%
20  ./transports (node_modules\browser-sync\no...odules\engine.io\lib\transports\index.js)        1s  ■ 1%
21  ./server (node_modules\browser-sync\node_m....io\node_modules\engine.io\lib\server.js)      2.1s  ■■ 2%
22  engine.io (node_modules\browser-sync\node_...\node_modules\engine.io\lib\engine.io.js)      2.2s  ■■■ 2%
23  ./transports (node_modules\browser-sync\no...engine.io-client\lib\transports\index.js)      1.2s  ■■ 1%
24  ./socket (node_modules\browser-sync\node_m...e_modules\engine.io-client\lib\socket.js)      1.4s  ■■ 1%
25  ./lib/ (node_modules\browser-sync\node_mod...de_modules\engine.io-client\lib\index.js)      1.4s  ■■ 1%
26  engine.io-client (node_modules\browser-syn...t\node_modules\engine.io-client\index.js)      1.4s  ■■ 2%
27  ./manager (node_modules\browser-sync\node_..._modules\socket.io-client\lib\manager.js)      1.8s  ■■ 2%
28  socket.io-client (node_modules\browser-syn...de_modules\socket.io-client\lib\index.js)      2.3s  ■■■ 2%
29  socket.io (node_modules\browser-sync\node_modules\socket.io\lib\index.js)                   5.1s  ■■■■■ 6%
30  ./sockets (node_modules\browser-sync\lib\sockets.js)                                        5.2s  ■■■■■ 6%
31  browser-sync-ui (node_modules\browser-sync\node_modules\browser-sync-ui\index.js)          992ms  ■ 1%
32  ./lib/browser-sync (node_modules\browser-sync\lib\browser-sync.js)                         10.9s  ■■■■■■■■■■■ 12%
33  browser-sync (node_modules\browser-sync\index.js)                                          11.1s  ■■■■■■■■■■■ 12%
34  uglify-js (node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js)                     1s  ■ 1%
35  ./minifier (node_modules\gulp-uglify\minifier.js)                                           1.4s  ■■ 1%
36  gulp-uglify (node_modules\gulp-uglify\index.js)                                             2.6s  ■■■ 3%
37  gulp-util (node_modules\gulp-jshint\node_modules\gulp-util\index.js)                        1.5s  ■■ 2%
38  ./reporters (node_modules\gulp-jshint\src\reporters\index.js)                                 2s  ■■ 2%
39  ./jshint.js (node_modules\jshint\src\jshint.js)                                            936ms  ■ 1%
40  jshint/src/cli (node_modules\jshint\src\cli.js)                                             2.9s  ■■■ 3%
41  ./extract (node_modules\gulp-jshint\src\extract.js)                                         3.4s  ■■■■ 4%
42  gulp-jshint (node_modules\gulp-jshint\src\index.js)                                         5.5s  ■■■■■■ 6%
43  ./js-yaml/loader (node_modules\gulp-svgmin...de_modules\js-yaml\lib\js-yaml\loader.js)        1s  ■ 1%
44  ./lib/js-yaml.js (node_modules\gulp-svgmin...svgo\node_modules\js-yaml\lib\js-yaml.js)      1.1s  ■■ 1%
45  js-yaml (node_modules\gulp-svgmin\node_modules\svgo\node_modules\js-yaml\index.js)          1.2s  ■■ 1%
46  ./svgo/config.js (node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\config.js)            1.3s  ■■ 1%
47  svgo (node_modules\gulp-svgmin\node_modules\svgo\lib\svgo.js)                               1.9s  ■■ 2%
48  gulp-util (node_modules\gulp-svgmin\node_modules\gulp-util\index.js)                        2.2s  ■■■ 2%
49  gulp-svgmin (node_modules\gulp-svgmin\dist\index.js)                                        4.2s  ■■■■ 4%
50  gulp-util (node_modules\gulp-imagemin\node_modules\gulp-util\index.js)                      3.2s  ■■■ 3%
51  globby (node_modules\gulp-imagemin\node_mo...es\imagemin\node_modules\globby\index.js)      1.1s  ■ 1%
52  imagemin (node_modules\gulp-imagemin\node_modules\imagemin\index.js)                        1.2s  ■■ 1%
53  cross-spawn-async (node_modules\gulp-image...\node_modules\cross-spawn-async\index.js)     932ms  ■ 1%
54  execa (node_modules\gulp-imagemin\node_mod...\exec-buffer\node_modules\execa\index.js)      1.2s  ■■ 1%
55  exec-buffer (node_modules\gulp-imagemin\no...fsicle\node_modules\exec-buffer\index.js)      1.5s  ■■ 2%
56  imagemin-gifsicle (node_modules\gulp-image...\node_modules\imagemin-gifsicle\index.js)      1.9s  ■■ 2%
57  imagemin-optipng (node_modules\gulp-imagemin\node_modules\imagemin-optipng\index.js)        1.1s  ■■ 1%
58  ./js-yaml/loader (node_modules\gulp-imagem...de_modules\js-yaml\lib\js-yaml\loader.js)     942ms  ■ 1%
59  ./lib/js-yaml.js (node_modules\gulp-imagem...svgo\node_modules\js-yaml\lib\js-yaml.js)      1.1s  ■ 1%
60  js-yaml (node_modules\gulp-imagemin\node_m...dules\svgo\node_modules\js-yaml\index.js)      1.1s  ■■ 1%
61  ./svgo/config.js (node_modules\gulp-imagem...vgo\node_modules\svgo\lib\svgo\config.js)      1.2s  ■■ 1%
62  svgo (node_modules\gulp-imagemin\node_modu...gemin-svgo\node_modules\svgo\lib\svgo.js)      1.6s  ■■ 2%
63  imagemin-svgo (node_modules\gulp-imagemin\node_modules\imagemin-svgo\index.js)              1.7s  ■■ 2%
64  gulp-imagemin (node_modules\gulp-imagemin\index.js)                                        10.7s  ■■■■■■■■■■ 12%
65  cache-swap (node_modules\gulp-cache\node_modules\cache-swap\index.js)                         1s  ■ 1%
66  gulp-util (node_modules\gulp-cache\node_modules\gulp-util\index.js)                         2.5s  ■■■ 3%
67  bluebird (node_modules\gulp-cache\node_modules\bluebird\js\release\bluebird.js)             2.2s  ■■■ 2%
68  ./lib/TaskProxy (node_modules\gulp-cache\lib\TaskProxy.js)                                  2.3s  ■■■ 2%
69  gulp-cache (node_modules\gulp-cache\index.js)                                               6.8s  ■■■■■■■ 7%
70  ./lib/clean (node_modules\gulp-htmlmin\nod...fier\node_modules\clean-css\lib\clean.js)      2.7s  ■■■ 3%
71  clean-css (node_modules\gulp-htmlmin\node_...minifier\node_modules\clean-css\index.js)      2.8s  ■■■ 3%
72  uglify-js (node_modules\gulp-htmlmin\node_...ier\node_modules\uglify-js\tools\node.js)      1.1s  ■■ 1%
73  html-minifier (node_modules\gulp-htmlmin\n...odules\html-minifier\src\htmlminifier.js)        5s  ■■■■■ 5%
74  gulp-util (node_modules\gulp-htmlmin\node_modules\gulp-util\index.js)                       2.4s  ■■■ 3%
75  gulp-htmlmin (node_modules\gulp-htmlmin\index.js)                                             8s  ■■■■■■■■ 9%
76  ./js-yaml/loader (node_modules\gulp-front-...de_modules\js-yaml\lib\js-yaml\loader.js)     929ms  ■ 1%
77  ./lib/js-yaml.js (node_modules\gulp-front-...tter\node_modules\js-yaml\lib\js-yaml.js)        1s  ■ 1%
78  js-yaml (node_modules\gulp-front-matter\no...ont-matter\node_modules\js-yaml\index.js)      1.1s  ■ 1%
79  front-matter (node_modules\gulp-front-matter\node_modules\front-matter\index.js)            1.1s  ■■ 1%
80  gulp-util (node_modules\gulp-front-matter\node_modules\gulp-util\index.js)                  2.1s  ■■ 2%
81  gulp-front-matter (node_modules\gulp-front-matter\index.js)                                 4.1s  ■■■■ 4%
82  gulp-util (node_modules\gulp-plumber\node_modules\gulp-util\index.js)                       1.7s  ■■ 2%
83  gulp-plumber (node_modules\gulp-plumber\index.js)                                           2.1s  ■■ 2%
84  gulp-util (node_modules\gulp-notify\node_modules\gulp-util\index.js)                          2s  ■■ 2%
85  node-notifier (node_modules\gulp-notify\node_modules\node-notifier\index.js)                1.4s  ■■ 2%
86  ./lib/extra_api (node_modules\gulp-notify\lib\extra_api.js)                                   4s  ■■■■ 4%
87  gulp-notify (node_modules\gulp-notify\index.js)                                             4.1s  ■■■■ 4%
88  ./lib/git (node_modules\gulp-gh-pages\lib\git.js)                                           1.5s  ■■ 2%
89  gulp-util (node_modules\gulp-gh-pages\node_modules\gulp-util\index.js)                      2.1s  ■■ 2%
90  ./utils (node_modules\gulp-gh-pages\node_m...eam\node_modules\micromatch\lib\utils.js)      1.7s  ■■ 2%
91  ./lib/expand (node_modules\gulp-gh-pages\n...am\node_modules\micromatch\lib\expand.js)      1.8s  ■■ 2%
92  micromatch (node_modules\gulp-gh-pages\nod...-stream\node_modules\micromatch\index.js)      1.9s  ■■ 2%
93  glob-stream (node_modules\gulp-gh-pages\no...nyl-fs\node_modules\glob-stream\index.js)      3.4s  ■■■■ 4%
94  ./lib/src (node_modules\gulp-gh-pages\node_modules\vinyl-fs\lib\src\index.js)                 5s  ■■■■■ 5%
95  vinyl-fs (node_modules\gulp-gh-pages\node_modules\vinyl-fs\index.js)                        5.8s  ■■■■■■ 6%
96  gulp-gh-pages (node_modules\gulp-gh-pages\index.js)                                         9.8s  ■■■■■■■■■■ 11%
97  E:\Users\Usuario\Documents\GitHub\simulapro.github.io\gulpfile.js (gulpfile.js)         1m 25.6s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 92%
Total require(): 4807
Total time: 1m 32.7s

**Comment by tunnckoCore** [comment]
Don't use gulp, lol :D That's the fix. jk..

 Actually, gulp is great as idea, but the core problem is in the way that vinyl-fs is implemented - in first place. But the team aren't so guilty - minimatch and glob are the real and slow problem. :) I can't realize that there's no other globbing module than `node-glob` (there are, but based on it) - it's time, really :)

just my 2c - for last time.

Cheers, Charlike.

**Comment by phated** [comment]
@fega it isn't a good idea to comment on a long dead thread, you'd probably be better off asking these questions on StackOverflow.  You also probably want to look into using https://www.npmjs.com/package/gulp-load-plugins which lazily loads your plugins.

Locking this thread.
