### ISSUE TITLE
Gulp 4 in environment without global gulp

### ISSUE THREAD

**Issue by fineline** [gulpjs/gulp#1050]
To run a build in a cloud environment without gulp installed globally (such as OpenShift node cartridge), with V3 I can add to the gulpfile:

`module.exports = function() {
	gulp.run("build");
};`

And then run this on deploy (using npm prepublish or the host system's action hooks):

`node -e 'require("./gulpfile.js")()'`

Will there be an approach that makes this possible in V4, when gulp.run is gone?

I could make all gulp tasks reference functions outside the task and just call the functions direct, but then I lose all the dependency management between tasks that is defined in gulp.

**Comment by contra** [comment]
make an npm script that calls gulp?

**Comment by fineline** [comment]
Thanks contra. I can confirm that running:

./node_modules/.bin/gulp

 works on my local machine after uninstalling gulp globally, but on openshift it doesn't, the error is:

Error: EACCES, open '/var/lib/openshift/553f118afcf933c1b900009c/.v8flags.3.14.5.10.553f118afcf933c1b900009c.json'

quite similar to that described here

http://stackoverflow.com/questions/25728115/running-a-gulp-build-on-openshift

Whereas the approach I describe above does work. 

So I guess the use of gulp.run() in this case is a workaround for the underlying problem that the gulp bin target doesn't work on openshift due to a permissions issue.

If this workaround is no longer available in V4, hopefully the permission issue can be addressed instead. But I guess that's a separate issue and so I'll close this one.
