### ISSUE TITLE
.config/gulpfile.js

### ISSUE THREAD

**Issue by shannonmoeller** [gulpjs/gulp#1054]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), and already submitted an issue for [`findup-sync`](https://github.com/cowboy/node-findup-sync/issues/17), but I wanted to get visibility here.

**Comment by hobi** [comment]
I like it!

I have problem with this messy stuff too.

**Comment by KapuzenSohn** [comment]
+1

**Comment by contra** [comment]
+1

**Comment by phated** [comment]
I'm :-1: on this

**Comment by callumacrae** [comment]
@phated: Why?

**Comment by tkellen** [comment]
I'm :-1: on this as well. Here are just a few reasons off the top of my head:

* This would break built-in editor support for tools like jshint and jscs.
* It is a nonsensical for tools like jshint and jscs--their configuration is supposed to cascade down to child directories. Would these tools have hardcoded support for `.config` folders? Some new configuration that specifies the folder it should actually take action in? Gross.
* Many of these files commonly appear in multiple locations, `.jshintrc`, for instance, is often present in test folders as well as the root of a project, extending the parent to add support for globals like describe/it/expect etc. Should those also be in `.config` directories?
* Paths in Grunt/Gulp/whatever are relative to the root directory--sure, you can change the working directory when you execute these tools but the ergonomics of doing so seems pretty confusing and error prone to me.

**Comment by tkellen** [comment]
I think a better solution would be to lobby for Github to hide dotfiles and provide some easy method of action to display them if needed.

**Comment by shannonmoeller** [comment]
@tkellen To your points:

- Allowing `.*rc` files to be in a `.config/` folder would be a per-project opt-in feature. As such, there may be a couple bumps as plugins update their dependencies, but this is no different from any other feature release.
- Not if it's a clearly defined pattern. Again, this would be an _optional additional_ location in which to find the configuration, in keeping with a [well defined spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).
- The root of a project could have a `.config/` while deeper directories could still have their own `.*rc` files. Or the option of a `.config/` directory could be completely ignored by a developer and everything is business as usual.
- Correct me if I'm wrong, but Grunt/Gulp/whatever are relative to the location of the `{grunt,gulp,*}file.js`. I don't see a quick check on the name of the parent directory as being that confusing or error prone. If they truly were root-relative, it's been made it quite clear that [package.json isn't going anywhere](https://github.com/npm/npm/issues/8159) anytime soon, so that could be used to find the root.
- The GitHub repo landing page is just one of many places that the list of files shows up. `ls` much?

Some have said that this is purely an aesthetic change. But I argue that it serves the same purpose as any other directory in that it's a grouping of related things. Why else have `lib`, `src`, `test`, `docs` directories? Why not keep them all in the root? Because grouping similar things makes sense and improves the navigability of a project however and wherever it's browsed.

**Comment by shannonmoeller** [comment]
I wish @nzakas would have allowed me the opportunity to leave the above points here as well. https://github.com/eslint/eslint/issues/2426

**Comment by phated** [comment]
I'm in agreement with the points made by both tkellen and the author of eslint. Also, I will not tolerate using our issues to harass maintainers of projects using mentions. Please stop.

**Comment by shannonmoeller** [comment]
@phated It was not my intent to harass. My apologies. Comment deleted.

**Comment by tkellen** [comment]
I appreciate what you're trying to do @shannonmoeller, but I disagree with your solution. I find this change very unintuitive given the method of action for many of these files.

As someone who maintains projects that see millions of downloads a month I don't think you appreciate how easily confused people are, or what it is like to deal with that confusion on a daily basis via issues, twitter, random personal emails, etc. When viewed from that lens (and every maintainer of a high profile project will view it from this lens), your suggested change provides little but the promise of more support requests.

My final thoughts on the matter:

1. In your example, 7 of the 10 files you want to hide lead with a dot. There is wide precedent for these files to not appear in default listings already (e.g. `ls` doesn't show them without `-a`, most (all?) file manager GUIs don't without opting in). I think you should lobby for Github to change their default display. Assuming you convince them, you'll get 70% of what you want without changing a single workflow

2. Fork all of these projects and do the work of implementing your solution. Send PRs and lobby for the community to support them. At the very least, you can use the forks yourself.

**Comment by shannonmoeller** [comment]
Running with the [PR idea](https://www.npmjs.com/package/find-config) in hopes that I can lobby again, without making such a twit of myself.

Thank you for your consideration.

**Comment by contra** [comment]
I'm :+1: on the idea but if it breaks a bunch of shit why would we ever consider this? :-1:

**Comment by zxqfox** [comment]
@tkellen Sooner or later community will get some standard place to hold user configs. And I don't get a clue why you trying to argue against it.

> It is nonsensical for tools like jshint and jscs. Their configuration is supposed to cascade down to child directories.

You should meet the real troubles: https://github.com/jscs-dev/node-jscs/issues/894

**Comment by phated** [comment]
@zxqfox this has already been discussed in detail and everyone seems to understand each other.  Your comments haven't added anything to this discussion and the issue you linked to has nothing to do with this.  I am going to lock this thread, as it has already been concluded.
