### ISSUE TITLE
Plugin naming convention

### ISSUE THREAD

**Issue by callumacrae** [gulpjs/gulp#1058]
There's nothing in the guidelines about naming plugins. I'd suggest the following:

- If the sole purpose of the package is to be a gulp plugin, it should begin "gulp-".
- If it is not a gulp plugin (for example, if it is only gulpfriendly), it should not start "gulp-".
- It should not contain anything other than alphanumeric characters and hyphens.

**Comment by superlukas** [comment]
* If the package wraps another package (and does nothing else), it should inherit the original package's name and prepend "gulp-".

**Comment by callumacrae** [comment]
@superlukas :+1:

**Comment by callumacrae** [comment]
@contra / @phated: Any feedback before I send a PR? A PR would definitely not be a good place to discuss something like this, so I'd prefer to do it in an issue.

**Comment by contra** [comment]
1 and 2 are good, 3 is very eurocentric

**Comment by superlukas** [comment]
@contra @callumacrae The [portable character set][1] defined by POSIX allows accents and tildes. Maybe that would be a better choice. FWIW, both can't handle my last name (and I'm okay with that).

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap06.html

**Comment by superlukas** [comment]
Never mind my last comment; It's late in central Europe...

According to npm, the package name will be part of a URL, a directory name, and something people put in their source code. Therefore, sticking with the portable character set defined by POSIX (or another subset of ASCII) is probably a good idea.

* http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap06.html
* https://www.ietf.org/rfc/rfc1738.txt
* https://docs.npmjs.com/files/package.json#name

**Comment by contra** [comment]
@superlukas Sure, but that is an npm guideline and has nothing to do with gulp. It's useless cruft to re-specify any npm package naming guidelines in our documentation.

**Comment by callumacrae** [comment]
Eh, I was thinking more just to make packages easier to use with gulp-load-plugins. Currently if you have a plugin with a dot in the name you have to either set an alias or load it manually.

I can't think of any reason _not_ to add it to the guidelines.

**Comment by joshuakelly** [comment]
I have to agree here. Strict naming conventions would make things easier when you are using something like gulp-load-plugins. 

+1

**Comment by contra** [comment]
@callumacrae My perspective: If our guidelines are identical to npm, and npm doesn't allow people to upload modules that don't follow their guidelines, then nothing that violates our guidelines exists or will ever exist.

**Comment by superlukas** [comment]
Maybe you guys should just split the difference and point out *why* it matters (for example, programmatic loading of plugins), rather than what matters, and then just leave a link to the npm docs for further reading.

**Comment by phated** [comment]
@contra @callumacrae where does this stand?

**Comment by contra** [comment]
I think we should add the first two items (about prefixing) but exclude everything to do with what characters are allowed because it is already enforced by NPM. Will merge a PR if somebody sends one.

**Comment by stevemao** [comment]
@callumacrae how do you define gulpplugin and gulpfriendly? If a module is using vinyl it's a gulpplugin? If a module is not using vinyl but works with gulp then it's gulpfriendly?
What about
https://github.com/frankwallis/gulp-hub
https://github.com/OverZealous/run-sequence
and
https://github.com/robrich/gulp-match?

**Comment by contra** [comment]
@stevemao If a module returns a stream that takes in vinyl files, outputs vinyl files, and follows the guidelines then it is a plugin. Otherwise it is gulpfriendly.

**Comment by stevemao** [comment]
I see, it makes more sense now after I read [writing-a-plugin](https://github.com/gulpjs/gulp/blob/506bac3f9f243cfda402b56143e2de2bae9418bc/docs/writing-a-plugin/README.md) again. So I guess the three modules I list should be gulpfriendly :)
