### ISSUE TITLE
docs: CLI.md # Compilers

### ISSUE THREAD

**Issue by iamstarkov** [gulpjs/gulp#1063]
> Compilers
>
> You can find a list of supported languages at interpret. If you would like to add support for a new language send pull request/open issues there.

What does [this paragraph][p] explain? Can I use gulp with es6-gulpfile? Yep, I renamed gulpfile from `gulpfile.js` to `gulpfile.babel.js`. But it doesn’t work.

I investigated in [changelog][changelog], [gulp sources][src] and in [js-variants list][js-variants]. But still don’t understand, what I’m doing wrong. Can you help me?

[js-variants]: https://github.com/tkellen/js-interpret#jsvariants
[src]: https://github.com/gulpjs/gulp/blob/2455eb91b83b8274b1b6960c538aaab3ae00c818/bin/gulp.js#L24
[changelog]: https://github.com/gulpjs/gulp/blob/ae98edfbfbe8341f20c7cb5d4d4b8ec339ee44ae/CHANGELOG.md#370

[p]: https://github.com/gulpjs/gulp/blob/master/docs/CLI.md#compilers

**Comment by Whoaa512** [comment]
Do you also have babel included in your project?

**Comment by iamstarkov** [comment]
Yep, here is my terminal log from linked project with testcase branch https://github.com/iamstarkov/iamstarkov.github.io/compare/gulpfile.babel.js

    ➜  iamstarkov.github.io git:(gulpfile.babel.js) ✗ node -v
    v2.0.1
    ➜  iamstarkov.github.io git:(gulpfile.babel.js) ✗ npm -v
    2.9.1
    ➜  iamstarkov.github.io git:(gulpfile.babel.js) ✗ gulp -v
    [00:33:21] CLI version 3.8.11
    [00:33:21] Local version 3.8.11
    ➜  iamstarkov.github.io git:(gulpfile.babel.js) ✗ npm ls babel
    iamstarkov.com@1.1.0 /Users/matmuchrapna/projects/iamstarkov.github.io
    └── babel@5.3.3

    ➜  iamstarkov.github.io git:(gulpfile.babel.js) ✗ ll | grep gulpfile
    -rw-r--r--   1 matmuchrapna  staff   3.6K May 11 01:15 gulpfile.babel.js
    ➜  iamstarkov.github.io git:(gulpfile.babel.js) ✗ gulp
    [00:33:48] No gulpfile found

and it’s working, dunno what to do next =(

**Comment by pho3nixf1re** [comment]
Have you figured this out yet? I'm running into the same thing.

**Comment by pho3nixf1re** [comment]
Turns out the version of `interpret` Gulp uses is way out of date and doesn't have the `.babel.js` extension.

**Comment by pho3nixf1re** [comment]
@sindresorhus This can be fix by releasing a new version to npm. `interpret` was bumped back in February to the correct version.

**Comment by iamstarkov** [comment]
This commit in master f1e6fab92364fb8dfd747479c32c3772bde8f310 by @sindresorhus fixing the problem.

**Comment by phated** [comment]
I've already stated this multiple times.  `interpret` introduced a breaking change before the babel stuff was added so we can't release this as gulp 3.x

**Comment by iamstarkov** [comment]
I don’t get point about interpret clearly. It’s breaking change for interpret consumers (like gulp) – it’s clear. Does bumping interpret inside gulp will lead to breaking changes for gulp users? if so, why?

**Comment by phated** [comment]
@iamstarkov yes, it is related to changing the typescript transpiler.  Since you have to have the transpiler installed next to gulp, this would break people using the old version.  We introduced a `legacyModule` option but `Liftoff` doesn't take it into account.  If someone were to add support for that property in Liftoff, we could introduce this support in gulp 3.x but no one seems interested in tackling that.

**Comment by iamstarkov** [comment]
okay, thank you

**Comment by iamstarkov** [comment]
btw, if commit with bumping interpret is already in master, is it mean that there will be no 3.x releases of gulp?

**Comment by phated** [comment]
@iamstarkov yeah, if something dire comes up, we will rebase it out, but I don't see that happening.
