### ISSUE TITLE
Patch 3.8.11 for Babel support?

### ISSUE THREAD

**Issue by impinball** [gulpjs/gulp#1066]
This would be awesome. The current one out on npm has nothing on Babel or the old 6to5. I know it's already patched for 4.0, but could that be backported (and/or the npm version updated)?

**Comment by phated** [comment]
We aren't publishing this as liftoff has a breaking change down the dependency tree. If someone fixes that to have back compat, then we can upgrade.

**Comment by impinball** [comment]
Oh.

**Comment by phated** [comment]
This should be fixed in the just published v3.9.0

**Comment by AgentME** [comment]
What does gulp babel support look like? Is this for the gulpfile.js? As a gulp and babel user this sounds interesting, but I'm having trouble finding documentation about this.

**Comment by phated** [comment]
Please read the thread, it is all outlined above.  I am going to lock this.

**Comment by phated** [comment]
Please read the thread for this https://github.com/gulpjs/gulp/issues/830 - I'm locking this thread.
