### ISSUE TITLE
Can't use gulpfile.ls with LiveScript 1.4.x

### ISSUE THREAD

**Issue by unclechu** [gulpjs/gulp#1071]
LiveScript started at 1.4.x renamed package name from `LiveScript` to `livescript` and now gulp says this:
```
[22:19:54] Failed to load external module LiveScript
```

**Comment by jmm** [comment]
@unclechu Are you on Windows or OS X? That's probably a node / npm / OS issue that doesn't actually have anything to do with gulp. See for example:

https://github.com/substack/node-browserify/pull/1247#issuecomment-99956642
https://github.com/substack/node-browserify/issues/1251
https://github.com/npm/npm/issues/7195

**Comment by jmm** [comment]
Or perhaps not, but if those issues don't trip things up, I think that would require an update in [tkellen/js-interpret](https://github.com/tkellen/js-interpret), if I'm not mistaken.

**Comment by contra** [comment]
@jmm send a PR to js-interpret

**Comment by jmm** [comment]
@contra You must mean @unclechu.

**Comment by contra** [comment]
Early morning :coffee: :expressionless:

**Comment by jmm** [comment]
Never use the internet while groggy. I'm pretty sure that's in the manual.

**Comment by tkellen** [comment]
Liftoff has to be updated to use "legacy" modules from interpret before
this can land. I have been swamped and haven't had a chance to look at it.
I will try to look this weekend. It's a total hack, but symlinking
node_modules/LiveScript to node_modules/livescript should work in the
interim.

**Comment by unclechu** [comment]
@jmm I'm using GNU/Linux, okay? And NPM is case sensitive, "LiveScript" and "livescript" is different packages, if Windows thinks that it's same and can't see the difference it's Windows users problems.

**Comment by tkellen** [comment]
This will be resolved in an upcoming minor release of Liftoff.

**Comment by phated** [comment]
This should be fixed in the just published v3.9.0
