### ISSUE TITLE
Running tasks either completes successfully or ENOENT randomly.

### ISSUE THREAD

**Issue by canebat** [gulpjs/gulp#1072]
I'm getting ENOENT errors randomly. I thought it was because maybe the clean task was conflicting with the other file copying tasks, but I have added in task ordering and the problem still persists.

My directory structure is:

```
   app/
        gulpfile.js
        server.js

        dist/
        node_modules/
        routes/
        public/
          css/
          js/
          imgs/
          templates/        
          index.html
```

The goal is to copy over all the files + folders in the current directory into `dist/`, except for a few files:

Things not to copy:
(1) Anything in `public/` except for `public/imgs/`.
(2) `./gulpfile.js`
(3) the `dist/` folder (because this is the destination)

I also minify my css and js files, and then copy that over to `dist/`. 

So, I created the following tasks:

```
var gulp = require('gulp');
var usemin = require('gulp-usemin');
var uglify = require('gulp-uglify');
var minifyCss = require('gulp-minify-css');
var del = require('del');

gulp.task('default', ['minify']);

// DELETE everything in dist/
gulp.task('clean', function() {
    var generated = ['dist/*'];
    return del(generated);
});

// Minify all css + js files, copy to dist/
gulp.task('minify', ['copy'], function() {
    gulp.src('public/index.html')
        .pipe(usemin({
            assetsDir: 'public',
            css: [minifyCss(), 'concat'],
            js: [uglify(), 'concat']
        }))
        .pipe(gulp.dest('dist/public'));
});

// copy all application files over to dist/
// except for certain files
gulp.task('copy', ['clean'], function() {
  var filesToMove = ["./**/*", 'public/imgs/**/*', '!public/**/*', '!gulpfile.js', '!dist/**/*']
  gulp.src(filesToMove, { base: './'})
      .pipe(gulp.dest('dist'));
});
```

So you see that the order should be 'clean' -> 'copy' -> 'minify':

[23:41:28] Starting 'clean'...
[23:41:28] Finished 'clean' after 2.91 ms
[23:41:28] Starting 'copy'...
[23:41:28] Finished 'copy' after 7.68 ms
[23:41:28] Starting 'minify'...
[23:41:28] Finished 'minify' after 241 ms
[23:41:28] Starting 'default'...
[23:41:28] Finished 'default' after 6.8 μs

This results either as successfully completed or in a some error, but if an error, every run gives something different. I have seen:

    events.js:72
            throw er; // Unhandled 'error' event

`Error: ENOENT, lstat '/home/ub/test/app/dist/public'`
`Error: ENOENT, lstat '/home/ub/test/app/dist/public/js`
`Error: ENOENT, open '/home/ub/test/app/dist/public/index.html'`

What's wrong with my tasks?

**Comment by phated** [comment]
You don't return your streams so task ordering doesn't work. Please ask support questions on StackOverflow
