### ISSUE TITLE
Question: can gulp watch only for addition/removal of files?

### ISSUE THREAD

**Issue by everdimension** [gulpjs/gulp#1073]
Example usage:

**Task:** Using `gulp-inject` to inject `js/**/*.js` files into `index.html`.

**Problem:** If I watch for changes in the `js/**/*.js` glob, this would mean that I'm running the `inject` task each time any of the `.js` files' content is changed, which is unnecessary, since the paths don't change.

**Question:** How can I create a watcher that would only watch for addition/removal of the files in the glob?

Thanks!

**Comment by phated** [comment]
Support questions should be asked on StackOverflow.

**Comment by everdimension** [comment]
Oh, ok, sorry about that!
