### ISSUE TITLE
concurrency issue with gulp.watch

### ISSUE THREAD

**Issue by gruppjo** [gulpjs/gulp#1074]
Hi,

is it possible that the `gulp.watch` callback is not triggered again when the same file changes with a threshold of a couple of milliseconds?

I'll try to roughly describe the scenario:
```js
gulp.task('watch', function () {
  gulp.watch('index.html', function (event) {
    console.log(event.path + ' was ' + event.type);
    livereload.reload();
  })
});

gulp.task('inject1', ['inject2'], function () {
  return gulp.src('index.html')
    .pipe(inject()) // inject some stuff here
    .pipe(gulp.dest('index.html'));
});

gulp.task('inject2', function () {
  return gulp.src('index.html')
    .pipe(inject()) // inject some other stuff here
    .pipe(gulp.dest('index.html'));
});
```
I have a `watch` task listening for changes in the `index.html` and two other gulp tasks that inject some content into it and depend on each other.
In the watch callback (among other things) a live-reload is triggered, so when the `index.html` changes the page in the browser is refreshed.
When `inject1` is called and thus `inject2` is called, the watch callback is only called once, namely after inject2 has finished and not again when inject1 finishes. That's very inconvenient because the injections from `inject1` are not visible until a new live-reload is triggered.

Is this intended behaviour or am I doing something wrong? I checked out the issue that merged all the gulp.watch issues (https://github.com/gulpjs/gulp/issues/651) but this problem doesn't seem to be among them.

Any help appreciated and keep up the good work :)

**Comment by phated** [comment]
Support questions should be asked on StackOverflow.

**Comment by gruppjo** [comment]
It's not a support question it's rather a question on how and when the gulp watch callback is triggered.
