### ISSUE TITLE
Running tasks with child_process synchronously

### ISSUE THREAD

**Issue by Fiery** [gulpjs/gulp#1075]
Trying to adopt gulp into daily automation tasks handling file IO with calling other executables. The good part about using js is its native async feature that allows simple and native multi-thread processing. This also becomes the issue since all tasks running child_process asynchronously and returns immediately after child_process.exec(). The expectation is to run a series of tasks calling external executables one by one, but looks like currently gulp can't help handle that since all child_process won't wait until process finish. Current walkaround is to use shell to call each task in the expected order but I feel like using gulp all the way down and don't not want bother to use other tools in the hople of minimizing possible training to users.

I take gulp as a great tool for the streaming system and code over configuration concept, and would like to see it becomes a general automation framework with support to all possible automation logics. Hope this would be considered for future releases. I've tried with gulp4.0 alpha but looks like bach isn't able to know when child_process finishes either.

**Comment by contra** [comment]
@Fiery this isn't a gulp problem, it's a node problem. this is how node works - things are async. there are modules that will help you deal with this, go search npm.

**Comment by Fiery** [comment]
Would you mind recommending a module which would help? I totally understand this is not gulp problem that's why I said "The good part about using JS is its native async feature" not "The good part about using  gulp is its native async feature" so there is no point in defending your gulp against my suggestion. I am just wondering if this would be included in the form of a wrapper around the existing solution so that we can have a out-of-box solution from gulp itself, not to find other modules and DIY to make the tool complete.

**Comment by contra** [comment]
@Fiery https://www.npmjs.com/ there are plenty of tools for running async things in series. The module I usually use is called `async`.

gulp is idiomatic node, so we use modules instead of bundling everything in. We have no opinion on control flow so you can use whatever you wish. Enjoy the freedom 🌴
