### ISSUE TITLE
Unable to find gulp task default when requiring a module that defines default gulp task

### ISSUE THREAD

**Issue by ankurp** [gulpjs/gulp#1076]
I am trying to require a gulpfile (someGulpfile.js) in my own gulpfile (gulpfile.js) from where I run the gulp command. When I try to use the tasks defined in someGulpfile it throws an error on console saying `Task 'default' is not in your gulpfile` even though I just did `require('./someGulpfile');` in my gulpfile.js

I found out that this somewhat works but it does not output every task that is run (for example it does not output, Starting sometask, Finished sometask, Starting default, ...) and if there is an error it does not show the error and where it happened but errors out in the gulp library code where it has trouble formatting the error output.

```
//gulpfile.js
var gulp = require('gulp');
gulp.tasks = require('./someGulpfile').tasks;

//someGulpfile.js
var gulp = require('gulp');
gulp.task('sometask', function() {});
gulp.task('default', ['sometask']);
module.exports = gulp;
```

I am using version 3.8.11

**Comment by contra** [comment]
Remove line #2, it isn't needed, modules are singletons in node

**Comment by callumacrae** [comment]
Also check out [gulp-hub](https://github.com/frankwallis/gulp-hub)

**Comment by ankurp** [comment]
@contra I ran into this issue where I have a node_module in my package.json that defines some gulp tasks and it has gulp as its dependency. I then add gulp as a dependency in my own package and for some reason that gulp is not able to find the tasks that I require from the node_module that defines them.

**Comment by jmm** [comment]
@ankurp It sounds like your package and the other package using different instances. I ran into a similar situation recently. Maybe there's a better solution, but what I did was like this:

```js
// gulpfile.js
var gulp = require('gulp');
require('path/to/someGulpfileGuts')(gulp);

// someGulpfile.js
require('./someGulpfileGuts.js')();

//someGulpfileGuts.js
module.exports = function (gulp) {
  gulp = gulp || require('gulp');
  gulp.task('sometask', function() {});
  gulp.task('default', ['sometask']);
};
```

**Comment by DemenageurSite** [comment]
Hi. This work in my case. 
I was facing the "gulp task is not in your gulpfile" error message, when using "gulp-require-tasks"
passing the gulp Instance solve the problem : 

`var gulp            = require('gulp');
var requireTasks    = require('gulp-require-tasks');

requireTasks({
    passGulp: true,
    gulp: gulp
}); `

Many thanks for your post !
