### ISSUE TITLE
get contents of files opened with gulp.src(..., {read: false});

### ISSUE THREAD

**Issue by daprahamian** [gulpjs/gulp#1077]
Hello,

Person new to gulp asking for help. So far I am loving it. I am currently looking to do something a little strange: I would like to open a bunch of files using `gulp.src(..., {read: false})`, and perform various operations on them, some of which include filtering down which files were included. After a number of operations, I would like to then be able to read the comments, as if I had use `gulp.src` without the `read: false` flag. Is there a way to do this?

**Comment by Nirazul** [comment]
Consider posting your questions at [Stackoverflow](https://stackoverflow.com), because Github Issue Tracker is not really a platform for help/learn/support questions.
