### ISSUE TITLE
Error: browserify-shim needs to be passed a proper browserify instance as the first argument.

### ISSUE THREAD

**Issue by mlmarius** [gulpjs/gulp#1078]
Hi. My application loads jquery synchronously from a CDN before loading the app. Now I've added a component that does a require('jquery') and fails. Looking around i gather that i need to shim jQuery so I modified the browserify task like so: 

```javascript
gulp.task('browserify', function() {
    return gulp.src('./src/js/app.js').pipe(browserify({
            transform: ['browserify-shim']
        }))
        //Pass desired output filename to vinyl-source-stream
        //.pipe(source('app.js'))
        .pipe(ngAnnotate())
        //.pipe(streamify(uglify({ mangle: false })))
        // Start piping stream to tasks!
        .pipe(gulp.dest('./dist/js/')).pipe(connect.reload());
});
```

didn't get to the part where I actually configure the shim because this also fails saying that:

```
Error: browserify-shim needs to be passed a proper browserify instance as the first argument.
```

Can someone help fix this ?

**Comment by phated** [comment]
Support questions should be asked on StackOverflow.  Also, gulp-browserify is blacklisted.
