### ISSUE TITLE
Looks like registry.gulpjs.com is down again

### ISSUE THREAD

**Issue by reflexdemon** [gulpjs/gulp#1085]
Not sure if the API has changed or the website name has changed.

[SlushJS](http://slushjs.github.io/generators/#/) generator search is broken and when looking on the network view of the browser found that the site registry.gulpjs.com is down again.

http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,author,modified,homepage,version,license&from=0&q=keywords:slushgenerator&size=15

**Comment by contra** [comment]
@reflexdemon The registry is gone, we switched to using npmsearch.com which also has a registry because I don't want to keep paying 50 dollars a month to host the elasticsearch
