### ISSUE TITLE
Stream kill signal

### ISSUE THREAD

**Issue by okvic77** [gulpjs/gulp#1089]
I need to restart the server from gulp.
I create a gulp task with a server declaration, but when I ``gulp.watch`` the task I can't shutdown the old server. I can recibe a "kill signal" and kill the server service inside gulp? Like the process end signal.

Thanks.

**Comment by tunnckoCore** [comment]
Can you provide some code?

**Comment by okvic77** [comment]
https://github.com/okvic77/gulp-foreman/blob/master/demo.js

**Comment by tunnckoCore** [comment]
Ooo my gash... `gulp-foreman`. The worst thing i've seen recently. It not doing anything with gulp and streams. You are able to what you want in that tasks, that not mean it should be prefixed with `gulp` and it is some gulp-ish magic. gulp is just cli runner of that functions.

Okey, in case. You want on `gulp server:reset` to kill the process (that is started from the `gulp server`) and start it again?

**Comment by okvic77** [comment]
No, when I re-run ``server`` task reset the service.
The stream that ``server`` return never stops, so the task will never end. I need some signal from gulp that let me know when I need to stop the server (and stream returned).

**Comment by tunnckoCore** [comment]
Erm... cant got it, re-explain?

for your last comment I understand that (which dont have logic to me)
```
gulp server # start the server
gulp server # stop and start the server (e.g. reset)
```

or?

this should be the programmatical api of `node-foreman`
```js
'use strict'

var toArg = require('to-arg')
var spawn = require('cross-spawn')

function foreman (opts) {
  opts = typeof opts ? opts : {}

  var args = Object.keys(opts).map(function (key) {
    return toArg(key, opts[key])
  })
  return spawn('nf', args)
}

// then, no matter where, even without gulp

foreman({
  procfile: 'path/to/Procfile'
})
```

**Comment by tunnckoCore** [comment]
and use in gulp task

```js
'use strict'

var gulp = require('gulp')
var foreman = require('../../index.js')

gulp.task('server:start', function (done) {
  foreman('start', {
    start: {
      env: './beta.env'
    },
    stdio: 'inherit'
  }, done)
})
```

**Comment by okvic77** [comment]
This could help to explain.
```javascript
var gulp = require('gulp');
var foreman = require('gulp-foreman');

gulp.task('server', function() {
    return foreman({
        procfile: path.join(__dirname, 'Procfile'),
        port: 2000,
        env: path.join(__dirname, '.env')
    });
});

gulp.task('default', ['server'], function(){
    gulp.watch('**/*.js', ['server']); // I need to reset the server if i edit some js files.
});

```

**Comment by phated** [comment]
Your module doesn't follow any of the guidelines and will end up blacklisted.  There is absolutely no reason to integrate with streams

**Comment by tunnckoCore** [comment]
@phated it's not his, he just forked https://github.com/jshcrowthe/gulp-foreman to show example.

> @okvic77: This could help to explain.

oh yea, really I forgot it. Cant handle the case, I dont know.

It strange cuz only simple `glob-watcher` sample like

```js
var watch = require('glob-watcher')

watch(['./*.js', '!./something.js'], function () {
  console.log('changed')
})
```
throws me error
