### ISSUE TITLE
local gulp install fails installing dependencies -- No compatible version found: vinyl-fs@'>=0.3.0 <0.4.0'

### ISSUE THREAD

**Issue by hux** [gulpjs/gulp#1090]
I have been unable to work around this issue. 
npm install -g gulp works just fine, it is only the local gulp that is giving this error.

Hopefully this is the relevant npm-debug.log information needed - I can provide the full log if necessary. Thank you for anyone's help or ideas on how to resolve this.

473 verbose about to build /var/data/new2/node_modules/gulp
474 verbose unlock done using /var/data/new2/.npm/_locks/gulp-f3d43e7d4fd79c3d.lock for /var/data/new2/node_modules/gulp
475 verbose stack Error: No compatible version found: vinyl-fs@'>=0.3.0 <0.4.0'
475 verbose stack Valid install targets:
475 verbose stack ["0.0.1","0.0.2","0.1.0","1.0.0"]
475 verbose stack
475 verbose stack at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:262:12)
475 verbose stack at next (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:241:17)
475 verbose stack at setData (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:218:5)
475 verbose stack at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
475 verbose stack at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
475 verbose stack at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
475 verbose stack at FSReqWrap.oncomplete (fs.js:101:15)
476 verbose cwd /var/data/new2
477 error Linux 3.14.35-28.38.amzn1.x86_64
478 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp"
479 error node v0.13.0-pre
480 error npm v2.9.1
481 error code ETARGET
482 error notarget No compatible version found: vinyl-fs@'>=0.3.0 <0.4.0'
482 error notarget Valid install targets:
482 error notarget ["0.0.1","0.0.2","0.1.0","1.0.0"]
482 error notarget
482 error notarget This is most likely not a problem with npm itself.
482 error notarget In most cases you or one of your dependencies are requesting
482 error notarget a package version that doesn't exist.
482 error notarget
482 error notarget It was specified as a dependency of 'gulp'
483 verbose exit [ 1, true ]

**Comment by phated** [comment]
This is 99% guaranteed to be related to your version of npm or node installed.
