### ISSUE TITLE
Question: Gulp 4: Using gulp.series() and gulp.parallel() inside function not working?

### ISSUE THREAD

**Issue by geirsagberg** [gulpjs/gulp#1093]
So the recommended usage for gulp 4 is to use functions over task strings (see https://github.com/gulpjs/gulp/issues/1091). 
I would then expect to be able to nest functions using `gulp.parallel()` and `gulp.series()` inside another function, like so:
```
var util = require('gulp-util')
function alpha() {
	util.log('alpha here');
}
function beta() {
	util.log('beta here');
}
function gamma() {
	return gulp.parallel(alpha, beta);
}
gulp.task(gamma);
```
However, when I run `gulp gamma`, the output is only:
```
Starting 'gamma'...
```
As far as I can tell, `alpha` and `beta` have not been run at all. What am I doing wrong?

**Comment by phated** [comment]
No, gulp.series and gulp.parallel return functions,  there is no reason to be putting them inside another function wrapper. gulp 4 helpers are available for function composition and don't result in the immediate execution of the things passed, they are only executed upon calling of the returned function

gamma should just be:
```js
var gamma = gulp.parallel(alpha, beta);
gamma.displayName = 'gamma';
// or if you think that is too verbose
gulp.task('gamma', gulp.parallel(alpha, beta));
```

**Comment by geirsagberg** [comment]
Ok, so this doesn't work:
```
function compileScripts() { ... }
function compileLess() { ... }
function compile() {
    return gulp.parallel(compileScripts, compileLess);
}
gulp.task(compile);
gulp.task('default', compile);
```
Instead I have to do
```
function compileScripts() { ... }
function compileLess() { ... }
gulp.task('compile', gulp.parallel(compileScripts, compileLess));
gulp.task('default', gulp.series('compile'));
```
I guess what I am looking for is an easy way to declare aliases, so the last line can be:
```
gulp.task('default', 'compile');
```
without the need for the `gulp.series()`-wrapping.

**Comment by tkellen** [comment]
```js
function compileScripts() { ... }
function compileLess() { ... }
const compile = gulp.parallel(compileScripts, compileLess);
gulp.task('compile', compile);
gulp.task('default', compile);
```

**Comment by geirsagberg** [comment]
Ok that's not too bad :) thanks @tkellen!

**Comment by tkellen** [comment]
sure thing!

**Comment by adambuczynski** [comment]
The only problem with this, is that you are forced to define the tasks last, because the const/var declaration is only usable after it's been defined, unlike functions definitions which are available in the entire script.

If you could wrap gulp.parallel and gulp.series in a function as well, you would be able to define your main tasks at the top of your file, and leave all handlers and helpers at the bottom, having a top-down overview in your gulpfile instead of a bottom-up, as now is the case.

**Comment by phated** [comment]
@adambuczynski sorry, that is not an API we plan to support.
