### ISSUE TITLE
Having two gulp.on('stop', ...) ignores the first one

### ISSUE THREAD

**Issue by binarykitchen** [gulpjs/gulp#1095]
Looks like having two stop listeners in two gulp tasks makes the first stop listener being left out:

```coffee
gulp.task('selenium', (cb) ->
  selenium.start({spawnOptions: {stdio: 'ignore'}}, (err, seleniumProcess) ->
    if err
      cb(err)
    else
      # Register shutdown callback
      gulp.on('stop', ->
        console.log 'hellloo???'
        seleniumProcess.kill()
        plugins.util.log('Selenium killed.')
      )

      plugins.util.log('Selenium started.')
      cb()
  )
)
```

and 

```coffee
gulp.task('server', ['build', 'backend'] ->

  devServer = new DevServer(watching)
  devServer.launch()

  # Register callback to kill server on task completion
  gulp.on('stop', ->
    devServer.exit()
  )
)
```

Upon gulp stop the dev server exits, but the first stop listener is never called and the selenium process is never killed.

**Comment by jisaacks** [comment]
Gulp gets it's `on` method from [orchestrator](https://github.com/orchestrator/orchestrator), I am not familiar enough with orchestrator to know if that is a feature or a bug.

**Comment by phated** [comment]
There is nothing in orchestrator that would cause this so I'm going to have to say that it's outside of gulp's scope and is either the gulpfile or other userland code.  Also, please try out the 4.0 branch
