### ISSUE TITLE
gulp-cli does not pick up gulpfile.babel.js

### ISSUE THREAD

**Issue by ide** [gulpjs/gulp#1098]
The gulp program that comes with the gulp-cli package (0.2.0) doesn't find gulpfile.babel.js. Uninstalling gulp-cli and globally installing gulp fixed the problem so this isn't urgent, but it seems like gulp-cli should work.

**Comment by jisaacks** [comment]
Would it make more sense to post this as an issue on the [gulp-cli](https://github.com/gulpjs/gulp-cli) repo?

**Comment by ide** [comment]
Good call, will move it.
