### ISSUE TITLE
gulpfile.ts?

### ISSUE THREAD

**Issue by tinganho** [gulpjs/gulp#1099]
Since you supported `gulpfie.babel.js` could you support `gulpfile.ts` too for TypeScript developers?

**Comment by phated** [comment]
This is already supported

**Comment by tinganho** [comment]
Just tried this seems no support?

```
import * as gulp from 'gulp';
^^^^^^
SyntaxError: Unexpected reserved word
```

**Comment by callumacrae** [comment]
Do you have typescript as a dependency of your project?

**Comment by tinganho** [comment]
@callumacrae yes i tried that too. Doesn't work.

**Comment by phated** [comment]
Please read your command line output. It tells you what module you need to install. I believe it currently is typescript-require or typescript-register but I'm not 100% sure

**Comment by tinganho** [comment]
@phated totally missed the message. Thanks.
