### ISSUE TITLE
Traverse and process each file of different types.

### ISSUE THREAD

**Issue by OpenGG** [gulpjs/gulp#1101]
Hey all.

I got this huge folder, legacy of long evolving development. It contains multiple subfolders, html files, js files, image files, css files, and so on.

Now I decide to write a little gulp script to help me minify them all.

My logic will be:

1. Traverse each file and folder.
2. Sub folders get copied recursively.
3. JS/HTML/CSS/Images files get copied and compressed separately.
4. Other types of file get copied to according location.

I know this could work:

    gulp.src('./**/*.js').pipe(minifyJS()).pipe(gulp.dest(outputDir));
    gulp.src('./**/*.css').pipe(minifyCSS()).pipe(gulp.dest(outputDir));
    gulp.src('./**/*.(png|jpg|gif|jpeg)').pipe(compressImage()).pipe(gulp.dest(outputDir));
    gulp.src('./**/*.html').pipe(minifyHTML()).pipe(gulp.dest(outputDir));
    gulp.src('./**/*.!(png|jpg|gif|jpeg|html)').pipe(gulp.dest(outputDir));

But how about this?

    gulp.src('./**/*').pipe(function(){
        var fileName = getFileNameSomehow();
        var type = getFileTypeWithExtensionName(fileName);
        if(type === 'html'){
            return minifyHTML(file);
        }else if(type === 'js'){
            return minifyJS(file);
        }else ...
    }).pipe(gulp.dest(outputDir));

I dont know if the below method could do the job too.

**Comment by phated** [comment]
Use [`gulp-if`](https://www.npmjs.com/package/gulp-if).  Also, support questions should be directed to StackOverflow
