### ISSUE TITLE
Please lock the version of js-v8flags more strictly

### ISSUE THREAD

**Issue by artyfarty** [gulpjs/gulp#1102]
Some [minor change](https://github.com/tkellen/js-v8flags/commit/2bc66ce703b41276010034c7c559cb7e7344a590) (moved cache into `~/.cache/` from `~/` without checking if that directory actually exists) just broke, well, everything.

**Comment by tkellen** [comment]
It *should* be reverting to a global temp folder if this standard cache path isn't present.

**Comment by balihoo-jflitton** [comment]
It doesn't appear to be doing so

**Comment by tkellen** [comment]
I've pushed a patch fix. This won't be re-published until additional tests cover this. Additionally, the outright failure when flags cannot be cached is going to be removed. For CI servers the slight performance hit for re-invocation is meaningless.

**Comment by phated** [comment]
We believe in semver.  Whether or not a regression happens doesn't mean it wasn't fixing another bug (and as someone who follows v8flags, it was).  Great job by @tkellen for finding and fixing the bug quickly.
