### ISSUE TITLE
weird execution of "default" when given other task

### ISSUE THREAD

**Issue by Giszmo** [gulpjs/gulp#1103]
I have a task I'm trying to parametrize, so I defined a `--debug` switch.

Running `gulp myTask --debug` runs my task and correctly detects my `debug` mode.

Running `gulp --debug myTask` runs my task and correctly detects my `debug` mode but also **runs the default task**.

**Comment by jisaacks** [comment]
This is because gulp is using [minimist](https://github.com/substack/minimist#example) and this is how minimist works.

calling `gulp myTask --debug` will result with `myTask` as a token as `debug` set to `true`
calling `gulp --debug myTask` will result with no tokens and `debug` set to `myTask`

**Comment by Giszmo** [comment]
So there is a rational explanation for this issue. Is it a bug? I find it highly unintuitive and therefore a bug. But thanks for showing where it comes from.

**Comment by jisaacks** [comment]
I don't think it is a bug, I think it makes sense considering how command line args work. What if you wanted to set the debug flag to "myTask"? How would it disambiguate what you intend? Do you have any recommendations?

**Comment by Giszmo** [comment]
`--debug=myTask` for a start? At least that's how it often is.

`$ man ls` for example gives me:

    SYNOPSIS
       ls [OPTION]... [FILE]...
    …
      --color[=WHEN]

Same with most commands. Options don't have to go last and if not used as a flag, they work with `=`.

**Comment by jisaacks** [comment]
> --debug=myTask for a start?
> Options don't have to go last and if not used as a flag, they work with =

Right, optimist supports that, but you need to specify the flags to treat as booleans ahead of time in the options you pass to optimist. Then it will not treat tokens after the flag as a value for the flag.

I have gotten that to work locally by manually setting `debug` as a boolean when instantiated optimist within the gulp cli.

I don't think hard coding that would be an option, however a mechanism for defining the options to pass to optimist from within the gulpfile *might* be reasonable. I would need to think about how that might work, if you have any ideas that would be great.

If I come up with a clean solution I will make a PR.

**Comment by jisaacks** [comment]
It looks like it wouldn't make sense for the gulpfile to specify options to pass to minimist. Since the path to the gulpfile can be set as an argument to minimist; minimist must be instantiated before the gulpfile is read.

My next idea would be to specify minimist options via a gulprc file. However, it seems that idea has already been pitched and [rejected](https://github.com/gulpjs/gulp/issues/170#issuecomment-32577467).

As it stands now my gut would be that this is a feature that isn't worth supporting in gulp. However, that is not my call. Maybe a collaborator can give an opinion on the issue.

**Comment by contra** [comment]
I agree, it is confusing. Maybe we should just drop support for `--key <value>` and only support `--key=<value>` for gulp args to prevent this

**Comment by phated** [comment]
I don't think we should support that.  If you are passing non-gulp flags to a gulp process, put them at the end or use `=` but we aren't going to hack around argv parsing libraries to restrict our args to `=`, which doesn't even completely solve the issue.  It is standard unix pattern to collapse `--something blah` into `--something=blah`
