### ISSUE TITLE
Add `-h|--help` flag to gulp CLI?

### ISSUE THREAD

**Issue by al-the-x** [gulpjs/gulp#1104]
Been using and teaching `gulp` for a while, but one thing that's always bugged me is that neither `gulp --help` nor `gulp -h` work like a typical unix command. I'd like to add that functionality, and I'm open to suggestion on the implementation. I imagine them working like this:

```shell
$> gulp --help
usage: gulp [options] <task-name> [ <task-name> [ <task-name> . . . ] ]

    Execute one or more `<task-name>` arguments as defined in `gulpfile.js` using the `gulp.task` 
    API. For more details on defining tasks, see the online documentation at: 

        https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

    OPTIONS:
      -h | --help            This help message
      --tasks                 List available tasks
      -v | --version        Print version of CLI and local library
```

I could use some guidance on where the command line flags are defined... I noticed that the project appears to be using [Liftoff](https://www.npmjs.com/package/liftoff) and [minimist](https://www.npmjs.com/package/minimist) to handle CLI flags. Admittedly, I'm more familiar with [yargs](https://github.com/bcoe/yargs) and [commander](https://github.com/tj/commander.js) but happy to learn and help.

**Comment by callumacrae** [comment]
What's wrong with the current output? Is it unclear?

**Comment by thecotne** [comment]
+1

@callumacrae currently gulp does not have any help command

**Comment by jisaacks** [comment]
> What's wrong with the current output? Is it unclear?

For starters, invoking `gulp --help` will run the default task if it exists, which the user most likely is not expecting to happen.

**Comment by callumacrae** [comment]
I'm confused

![screen shot 2015-06-22 at 10 49 38](https://cloud.githubusercontent.com/assets/472830/8279415/62232a02-18cc-11e5-9b90-9d3a2a2be58e.png)

Is this a Gulp 4 change?

**Comment by al-the-x** [comment]
I have never seen this output before, but it looks great! Would love to have something similar in current 3.x branch, maybe back-ported to 2.x...?

**Comment by al-the-x** [comment]
Happy to do some of that work, even if it's short-term... Having a `--help` flag alone would be super helpful.

**Comment by contra** [comment]
This is in the 4.0 branch, we aren't backporting new features to 3.x - only critical bug fixes. Help us test 4.0 by using it!
