### ISSUE TITLE
Should multiple tasks on the command line be treated as series in gulp4?

### ISSUE THREAD

**Issue by srcspider** [gulpjs/gulp#1106]
**Scenario**

The following command is intended to generate email templates. 
```sh
gulp clean emails
```
My intention is to clean out any current templates and generate a new ones.

**Expected**
```sh
[15:27:56] Starting 'clean'...
[15:27:56] Finished 'clean' after 26 ms
[15:27:56] Starting 'emails'...
 writing user/signup/verify-emailaddress.text.php
 writing user/signup/verify-emailaddress.html.php
[15:27:56] Finished 'emails' after 751 ms
```

**Actual**
```sh
[15:11:44] Starting 'clean'...
[15:11:44] Starting 'emails'...
 writing user/signup/verify-emailaddress.text.php
 writing user/signup/verify-emailaddress.html.php
[15:11:45] Finished 'emails' after 753 ms
[15:11:45] Finished 'clean' after 759 ms
```

Seems command line arguments have parallel behavior. Maybe have a option to force running as a series? Given that dependencies per task are no longer a thing in gulp4 that would make more sense for strings of commands.

*Disclaimer: I'm aware of the of the solution of making yet another task for the purpose of calling the tasks in the right order but that's not very console friendly; specifically for cases where you just want to run X, Y, Z and expect it to just work.*

**Comment by callumacrae** [comment]
`gulp clean && gulp emails`?

**Comment by srcspider** [comment]
Ah right.
