### ISSUE TITLE
Gulp watch only works twice ...

### ISSUE THREAD

**Issue by skarfacegc** [gulpjs/gulp#1109]
Just resaving a file without changes will fire the watcher twice.  My relevant sections from my gulpfile:

    var SOURCE_FILES = ['lib/**/*.js', 'bin/*', 'test/**/*.js'];
    var TESTS = ['test/unit/**/*.js'];

    // Run the test suite, show details 
    gulp.task('test', function(cb) {
        gulp.src(TESTS)
            .pipe(mocha({
                reporter: 'spec'
            }).on('end', cb));
    });

    // Rerun coverage on change
    gulp.task('watch', function() {
        gulp.watch(SOURCE_FILES, ['test']);
    });

OSX 10.10.3 / gulp 3.9.0 / node 12.0.4

**Comment by callumacrae** [comment]
Could that be your editor doing crazy things?

**Comment by skarfacegc** [comment]
Same behavior with touch.

**Comment by skarfacegc** [comment]
Some additional information:

The first file I touch will work twice.  touching that file never works again (unless I restart gulp)
Touching other files work the first time, but not again.  

So touching the first file works twice, then I can touch each other file in the glob, and watch will work once per file.

**Comment by skarfacegc** [comment]
figured it out.  I was using sinon.useFakeTimers and never restored one of them.
