### ISSUE TITLE
gulp babel and isparta

### ISSUE THREAD

**Issue by eddiemoore** [gulpjs/gulp#1110]
For some reason I can't use the normal ES6 imports with isparta in my gulpfile. If I use require it all works correctly, runs all my tests and covers all my code. But when I change over to use import I get:
```shell
$ gulp mocha
[14:54:55] Requiring external module babel/register
[14:54:56] Using gulpfile ~/Work/XXX/gulpfile.babel.js
[14:54:56] Starting 'istanbul'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unable to parse /Users/ed/Work/XXX/src/chat.js

Line 1: Unexpected reserved word
```
##### gulpfile:
```js
import gulp from 'gulp'
import istanbul from 'gulp-istanbul'
// import isparta from 'isparta' // Doesn't work
const isparta = require('isparta') // Works
import mocha from 'gulp-mocha'

gulp.task('istanbul', cb => {
  gulp.src(['./src/**/*.js'])
    .pipe(istanbul({
      instrumenter: isparta.Instrumenter,
      includeUntested: true,
      babel: { stage: 0 }
    }))
    .pipe(istanbul.hookRequire())
    .on('finish', cb)
})

gulp.task('mocha', ['istanbul'], () => {
  return gulp.src('./test/**/*.js')
    .pipe(mocha({
      reporter: 'spec'
    }))
    .pipe(istanbul.writeReports({
      dir: './coverage',
      reportOpts: {dir: './coverage'},
      reporters: ['lcovonly']
    }))
})
```

Now to tell you the truth, I can't tell if this is an issue with gulp, [istanbul](https://www.npmjs.com/package/istanbul), [isparta](https://www.npmjs.com/package/isparta), or babel

**Comment by phated** [comment]
Considering this is solved by just requiring it, I am going to say it is one of your other modules.

**Comment by greim** [comment]
Oh, weird. I'm having this exact same issue. @eddiemoore did you make any progress solving it?

**Comment by greim** [comment]
Maybe this: https://github.com/douglasduteil/isparta/pull/60

**Comment by eddiemoore** [comment]
@greim Yeah that's the bug.
