### ISSUE TITLE
Using strings when registering with gulp.task II

### ISSUE THREAD

**Issue by jmm** [gulpjs/gulp#1111]
The idea has been [floated](https://github.com/gulpjs/gulp/issues/969#issuecomment-84531764) that gulp 4 may eliminate the signature `gulp.task(taskNameString, func)` in favor of just `gulp.task(func)`. What is the status of that idea? If it's still alive:

* What is the motivation for it?
* Why is it necessary or important?

I raised concerns about that approach in https://github.com/gulpjs/gulp/issues/969#issuecomment-84975436 that I would really like to see discussed before a decision is made and gulp 4 is released, but my comments dating back almost 3 months haven't been replied to and the issue has remained closed. I'm not going to re-post everything here (you can read it all starting with the comment I just linked to), but here are the highlights:

The premise is exposing a task to the CLI where the name contains a non-identifier character such as `:`. E.g. `build:clean`.

Clunky:

```js
buildClean.displayName = 'build:clean';
gulp.task(buildClean);
function buildClean () {}
```

Worse still, even that doesn't work (or didn't at the time I posted it anyway).

Even clunkier:

```js
var buildClean = function () {};
buildClean.displayName = 'build:clean';
gulp.task(buildClean);

// or

gulp.task(buildClean());
function buildClean () {
  var f = function () {
    // real function
  };
  f.displayName = 'build:clean';
  return f;
}
```

Another argument against eliminating the `name` argument is a case like this from the [docs](https://github.com/gulpjs/gulp/blob/78751c834e1c7365f60dff7094c1d7e492b11997/docs/API.md#gulpseriestasks) where you just want to expose a series / parallel to the CLI:

```js
gulp.task('default', gulp.series('one', 'two', function(done) {
  // do more stuff
  done();
}));
```

Without `name` you'd have to (at best) do something clunky like:

```js
gulp.task(function () {
  var task = gulp.series('one', 'two', function (done) {
    // do more stuff
    done();
  });
  task.displayName = 'default';
  return task;
}());
```

But of course *that* doesn't even work currently because `gulp.series()` returns a function with a `name` prop.

**Comment by callumacrae** [comment]
It's optional

**Comment by jmm** [comment]
@callumacrae It's going to be optional or deprecated? Deprecation is what was floated previously.

**Comment by phated** [comment]
Optional, not recommended but not deprecated.

**Comment by jmm** [comment]
> not deprecated.

:+1:
