### ISSUE TITLE
Update vinyl-fs to version 1.0.0

### ISSUE THREAD

**Issue by Edifice** [gulpjs/gulp#1117]
vinyl-fs has been updated a while ago and if anyone have some time, please update the dependency. 
Personally I would use the overwrite flag from this PR: https://github.com/wearefractal/vinyl-fs/pull/59

(I'm not in the core team, and I just don't wan't to ruin anything, that's why I don't make a PR)

Thanks!

**Comment by callumacrae** [comment]
It's going to be updated in Gulp 4.0: https://github.com/gulpjs/gulp/blob/4.0/package.json#L28

**Comment by Edifice** [comment]
Are there any known compatibility issues when upgrading from Gulp 3 to 4?
Then I could just update, to solve my problem.

**Comment by callumacrae** [comment]
http://semver.org/

Yes, otherwise it would be Gulp 3.10.0.

**Comment by Edifice** [comment]
Ok thanks, they I'll find a workaround until then.
