### ISSUE TITLE
TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by Student007** [gulpjs/gulp#1122]
Hi,
I have no more idea what is the problem so I think it is a bug.
Running `gulp test-once` cause the error
**TypeError: Cannot read property 'fn' of undefined** 
The error causes at gulpfile.js:29:18
It looks like the task `mocha` isn't defined ?
What I am doing wrong ? (I am a gulp beginner using it with Koa)
```
// gulpfile.js
var gulp = require('gulp');  
var nodemon = require('gulp-nodemon'); // restart app on filechange  
var mocha = require('gulp-mocha-co');  
var exit = require('gulp-exit');

gulp.task('watch', function() {  
  gulp.watch(
    ['*.js', 'test/*.js'], // files to watch
    ['mocha'] // gulp task to run on file change
  );
});
gulp.task('nodemon', function() {  
  nodemon({
    script: 'server.js',
    env: {PORT: 8000}, // preventing conflicts
  }).on('restart');
});

gulp.task('mocha', function() {  
  process.env.PORT = 8001; // default would conflict with superset
  return gulp.src(['test/*.js']) // run all tests
  .pipe(mocha({           // pipe them into mocha
    reporter: 'nyan'      // report by nyan
  }));
});

gulp.task('test-once', function() {  
  gulp.task.mocha.fn().pipe(exit());
});
// default tasks to run if gulp is called without specific task
gulp.task('default', ['nodemon', 'mocha', 'watch']);  
```

**Comment by jisaacks** [comment]
What exactly are you trying to achieve with `gulp.task.mocha.fn().pipe(exit())` ? I am not suggesting that it is wrong, but I have not seen that before and not sure what you are trying to do.

**Comment by Student007** [comment]
Hi JD,
I assumed that this isn't right. I got it from a [tutorial](http://russmatney.com/techsposure/basic-koa-api-gulp-supertest/) to start to get together gulp, koa and testing.
In my opinion it should do the following:
gulp.task is an object is holding all tasks referencing their functions - so the functions can be called by common dot notations. If I run the mocha task, it should RETURN a gulp reference what is piping all test files into mocha to be reported by nyan. After that it should pipe to exit. So long my opinion of what should happen by this code.
What I didn't understand is that the gulp task 'mocha' isn't defined. Is this the wrong way to call it ?
Or is it possible loading the tests needs to long ? So a callback solution would be better ? If so - how to do ? Is it necessary to load the gulp.src outside the gulp.task('mocha', function(){}) and only take the reference to the prepared preloaded object ? Is there a on ready way gulp can use ?
 
Dan

**Comment by heikki** [comment]
Typo?

`gulp.task.mocha.fn().pipe(exit());`-> `gulp.tasks.mocha.fn().pipe(exit());`

**Comment by Student007** [comment]
@heikki YES that was the problem. I didn't know so I couldn't see myself. Thanks a lot :smile:

**Comment by Student007** [comment]
close

**Comment by jisaacks** [comment]
@Student007 if you want to close the issue you should have a `close` button next to the `comment` button.

**Comment by Student007** [comment]
@jisaacks lesson learned :wink:
