### ISSUE TITLE
branch #4 is broken

### ISSUE THREAD

**Issue by martinkr** [gulpjs/gulp#1123]
Hey,

i just did a fresh install of gulp-cli and gulp, bothfrom branch#4 and unfortunately it's broken. The scripts worked before, now i get the following error
```
/usr/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:34
        return gulpInst.get(task).description;
                        ^
TypeError: undefined is not a function
    at /usr/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:34:25
    at /usr/lib/node_modules/gulp-cli/lib/shared/log/tasks.js:37:10
    at Array.forEach (native)
    at logTasks (/usr/lib/node_modules/gulp-cli/lib/shared/log/tasks.js:23:8)
    at /usr/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:33:14
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```
with
```
gulp-cli@0.2.0
gulp@4.0.0-alpha.1
```

Cheers!

**Comment by jmm** [comment]
@martinkr What command do you get that for? Anything? That's similar to the error I was getting, but only for `gulp --tasks`: https://github.com/gulpjs/gulp/issues/1112

**Comment by martinkr** [comment]
gulp --tasks also

**Comment by contra** [comment]
Can you change the line in that file to `gulpInst.task(task).description` and see if that fixes it?

**Comment by contra** [comment]
If so, can you send a PR with that fix?

**Comment by clintwood** [comment]
See https://github.com/gulpjs/gulp-cli/pull/28 and https://github.com/gulpjs/gulp/issues/1112

**Comment by martinkr** [comment]
https://github.com/gulpjs/gulp-cli/pull/28 resolves the problem for me

**Comment by phated** [comment]
Should be fixed as of https://github.com/gulpjs/gulp-cli/commit/dc5409639f1eabb70bb943981afba29024268288
