### ISSUE TITLE
71390 segmentation fault gulp

### ISSUE THREAD

**Issue by welly** [gulpjs/gulp#1124]
Hello,

I've a task which is executing a jekyll build as follows:

```
gulp.task('jekyll', function(done) {

  return cp.spawn('bundle', ['exec', 'jekyll', 'build', '-q', '--source=' + config.src, '--destination=' + config.dest, '--config=' + config.config], { stdio: 'inherit' })
  .on('close', done);

});

```

I'm getting sporadic but regular segmentation faults. Could anyone suggest what might be causing this?

Thanks!

**Comment by contra** [comment]
The segfault is probably happening in jekyll not in gulp, and the logs are getting output through the gulp process (via `stdio: 'inherit'`)

**Comment by welly** [comment]
I was wondering that and I've actually commented out the jekyll call and it's still occurring but on a different (rebuild) task that looks like:

gulp.task('jekyll:rebuild', ['jekyll'], function() {
  browsersync.reload();
});

Same thing: 72419 segmentation fault  gulp

**Comment by welly** [comment]
Ok, I actually think the issue is with browsersync. I'm going to look and see if there's any issues around that.

cheers!

**Comment by phated** [comment]
the segmentation fault error comes from chokidar, which gulp isn't using (yet)

**Comment by phated** [comment]
Browsersync uses chokidar*
