### ISSUE TITLE
Do NOT deprecate or remove `gulp.run()`...

### ISSUE THREAD

**Issue by resistdesign** [gulpjs/gulp#1125]
`gulp.run()` is very handy for use in a cli that incorporates other types of commands as well.

I saw this: `gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.`
And I don't like it :(

**Comment by TrySound** [comment]
@resistdesign Now u do `gulp.run('task');` or `gulp.start('task');`, in 4.0 you will gulp.parallel('task')(); or gulp.series('task')();
That's all

**Comment by resistdesign** [comment]
Ah, ok, also I just found that I can use `gulp` without declaring tasks and that works too, like just:
```node
#!/usr/bin/env node

var gulp = require('gulp');

gulp.src('hello.txt')
  .pipe(gulp.dest('build'));
```

**Comment by TrySound** [comment]
@resistdesign It's just streams.

**Comment by resistdesign** [comment]
You're right, I couldn't get my head out of the task structure to see that :P
