### ISSUE TITLE
babel-core

### ISSUE THREAD

**Issue by thejameskyle** [gulpjs/gulp#1127]
It'd be nice if you could conditionally load `babel-core` instead of `babel` when it exists.

`babel-core` is the lightweight version of babel that plugins like `babelify` use.

This should work just as well:
```js
require('babel-core/register')
```

**Comment by superlukas** [comment]
This issue should be moved to https://github.com/tkellen/js-interpret I guess.

**Comment by thejameskyle** [comment]
Moved
