### ISSUE TITLE
Controlling failing builds

### ISSUE THREAD

**Issue by SBoudrias** [gulpjs/gulp#113]
I think failing a build might be a task Gulp should handle directly. Currently plugins can throw errors, but this is not really clear as it log a full stack trace an error information while most of this really isn't necessary. The plugin just need the build to fail.

Also, be throwing errors, plugins stop the complete process. This may not always be the best behavior as we'll miss all the other relevant information our other build task could provide.

For example, Gulp-JSHint run linting on each task. Once all files have passed through, it log the reports. If any linting fails, it could just notify the Gulp process (`Gulp.failBuild()` or anything).

This way, the process continue and other tasks can be runned; like the unit tests and such.

Once all the streams are done, Gulp either exit 0 with success, or then exit 1 logging all tasks who've failed, e.g.

```
Gulp: Build failed (0/3)
  jshint: Linting errors
  mocha: Tests error
  uglifyjs: Unexpected error
```

Maybe Gulp could even allow two options for plugins. A minor fail (fail the build, but continu process) and a major fail (fail the build, and stop the current stream process).

**Comment by techtonik** [comment]
So, what is the proper 4.0.0 code to markAsFailed on error?

**Comment by phated** [comment]
@techtonik just don't do that part....
