### ISSUE TITLE
Gulp [4] Registry

### ISSUE THREAD

**Issue by iamaaron** [gulpjs/gulp#1133]
If we cannot access different tasks from separate files that are part of the same registry, what is the concept behind the registry? See below for an example.

gulp.js
```javascript
'use strict';

var gulp = require('gulp');
var HubRegistry = require('gulp-hub');

var registry = new HubRegistry(['gulp/tasks/*.js']);

gulp.registry(registry);

gulp.task('default', gulp.series('build', 'debug', 'lint', 'test'));
```

Now if I were to have build, debug, lint, and test, as tasks, defined in all complete separate files, but included in the registry. I get an AssertionError and a a message of 'Task never defined' for those tasks. I may be implementing it wrong, but I have found very little documentation on this feature. May I get an explanation?

**Comment by iamaaron** [comment]
Do we have to include that registry in every file for tasks?

**Comment by phated** [comment]
I believe this is a bug we are trying to fix over at https://github.com/phated/undertaker/issues/25 - As far as I am aware, `gulp-hub` is using an old version of the registry spec.

**Comment by phated** [comment]
I believe this is completely fixed in https://github.com/frankwallis/gulp-hub/pull/26 which was merged to the `registry-init` branch of gulp-hub.
