### ISSUE TITLE
Cascade error display

### ISSUE THREAD

**Issue by let4be** [gulpjs/gulp#1134]
I'm using gulp 4.0
(npm install gulpjs/gulp-cli#4.0 -g)

When one task throws some kind of error the error is being propagated to the root task and I see huge stacktrace for each task, is there any way to get rid of this?

http://hastebin.com/potikeroqa.pl

Expected behavior:
show stack-trace only for the task where error originates from

If I do
`throw new gutil.PluginError('test', 'something broke', {showStack: false})`
it hides stacktrace completely

Thanks!

**Comment by phated** [comment]
I'm not sure if we plan to tackle this.  If a community member wants to submit some code that attempts to solve it, we will review the possibility of adding the feature.

**Comment by phated** [comment]
Ref #1330

**Comment by phated** [comment]
Collapsing into #1330 which now has an impl attached
