### ISSUE TITLE
Dependency headache - race condition

### ISSUE THREAD

**Issue by gavD** [gulpjs/gulp#1138]
I have the following:

```javascript
gulp.task('clean', function(cb) {
  return del(['build/*'], cb);
});

// ...

gulp.task('build', ['clean', 'quality', 'styles', 'scripts'], function() {
  // do stuff
});
```

What I need is for "clean" to COMPLETELY COMPLETE before "quality", "styles" and "scripts" runs. Unfortunately, they all kick off in parallel, and half the time my build fails because it's still in the middle of clearing the build directory when the unit tests start in `quality`. Race condition.

I've pored through the Gulp docs and endless articles and I'm still none the wiser; I know that `build` won't start until `['clean', 'quality', 'styles', 'scripts']` have ALL completed and that's great, but `quality`, `styles` and `scripts` should wait for `clean`.

## Possible solution 1

I make "clean" a dependency on `quality`, `styles` and `scripts`, and that would have the desired effect, but what if I wanted to run, say, `styles` on its own? It would clobber the styles AND scripts in the build directory... Is that something I just have to live with? That I can't run the subtasks in isolation any more if I take this approach?

## Possible solution 2

Each of `styles` and `scripts` would have a dependency - `clean-styles` and `clean-scripts` - this would mean that it only cleaned up its own directory first.

This would work but it feels less elegant than "blow away the entire build directory before we start a full build"

So, is there any way to have a dependency act like "hold the phones! Don't do ANYTHING until `clean` is completed"?

Thanks!

**Comment by alferov** [comment]
@gavD, the exact same case is described in the [documentation](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md).

**Comment by gavD** [comment]
Thanks @alferov - sort of - it is the same as my "Proposed solution 1". It has the downside that it can't run `styles` or `templates` in isolation without wiping out the entire build directory.

I suppose that's a small price to pay, my application is small enough that it doesn't matter much, but I just wondered if there was a way to have the flexibility I want.

**Comment by alferov** [comment]
@gavD, hmm, you could try to play around with the task order using [run-sequence](https://www.npmjs.com/package/run-sequence). They have nice example in the documentation that might work well for you.

**Comment by gavD** [comment]
Thanks @alferov - I've used run-sequence in other projects and it's always worked great, I was just wondering if there was a more conventional way I could do it but I'm happy with that if not :-)

thanks for your help!
