### ISSUE TITLE
npm@3 and peerDependencies

### ISSUE THREAD

**Issue by iarna** [gulpjs/gulp#1140]
You may already be aware, but npm@3 introduces breaking changes to how peerDependencies are handled. Specifically, it no longer installs them for users. INSTEAD, it reports warnings if they're missing or invalid, but otherwise leaves it to the end user to solve.

I did a quick spot check of a handful of gulp plugins and didn't see any peer deps, but I wanted to make sure that you all were aware of this change.

**Comment by tkellen** [comment]
Thanks for the heads up @iarna (and all the great work on npm)! I believe we're all aware, but I'll leave this open for the rest of the crew to respond.

**Comment by contra** [comment]
Yep, peer dependencies are forbidden for plugins by the guidelines. No plugin should ever depend on gulp so they should be fine. Thanks!
