### ISSUE TITLE
Make anonymous task silent

### ISSUE THREAD

**Issue by amio** [gulpjs/gulp#1143]
Usually I use anonymous task for sub-tasks, I want to hide these detail from gulp user,
but the gulp still notify for anonymous task, and seems no way to make it quiet.

![image](https://cloud.githubusercontent.com/assets/215282/8589595/a1453ae6-264a-11e5-8443-8eb001c8c71e.png)

How do I hide these `[14:47:05] Starting '<anonymous>'...` ?
What about dismiss report from anonymous task, or add a property(such as `fn.silent`) to task function?

here's my task definition, FYI:
```
gulp.task('copy', copyBootstrap())

function copyBootstrap(){

	var styl_dir = 'node_modules/bootstrap-styl/bootstrap'
	var js_dir = 'node_modules/bootstrap-styl/js'
	var dist = 'lib'

	return gulp.parallel(
		function(){
			var a = gulp.src(styl_dir + '/**/*')
				.pipe(gulp.dest(dist + '/bs-styl'))
			return a
		},
		function(){
			return gulp.src(js_dir + '/**/*')
				.pipe(gulp.dest(dist + '/bs-js'))
		}
	)

}
```

**Comment by amio** [comment]
For now I make a plugin to do that https://www.npmjs.com/package/gulp-all
but I think maybe anonymous task was meant to be acting like that? for doing some private even dirty works, silently.

Or when should I use anoymous task?

**Comment by phated** [comment]
`gulp.parallel` and `gulp.series` are meant to build task dependency trees.  If you don't want things to show up, just use plain functions and helpers libraries like `async` or `bach`.

**Comment by godban** [comment]
+1 this 'anonymous' messages is annoying
