### ISSUE TITLE
Gulp tasks don't exit if I require my JS file

### ISSUE THREAD

**Issue by osambhus** [gulpjs/gulp#1145]
I have a `gulpfile.js` which has a bunch of tasks.

I noticed that my gulp tasks run, but after finishing they don't exit/terminate. I have to use `control + c` to exit. I went through a thread that talked about a similar problem, but it was using `gulp-mocha` and there was an issue in the plug in.

In my case, I also know what is causing this issue. I have required a js(`edgecaset.js`) file that I've written, into my gulp file (one of the tasks uses a function in that file). It is a simple file with one function that interacts with a rest api. If I don't require that file, everything works great.

I'm exporting just one function from the `edgecast.js` file to be used in the gulp file. It has a call to the `setTimeOut` function (could that be the problem?)

The 'gulpfile.js' requires this file.
```javascript
var edgecast = require('./edgecast.js');
```
And this require statement causes all the problems.

The edgecast.js file has the following libraries imported.
```javascript
var rest = require('restler'),
    JSFtp = require('jsftp'); 
```

Here is the function that I'm exporting from the `edgecast.js` file

```javascript
var main = function () {
    console.log(config.edgecast.username);
    ftp.put(config.ftp.local_path, config.ftp.remote_path, function(hadError) {
        if (!hadError) {
            console.log('File transferred successfully');
            rest.put(config.edgecast.purge_url, purgeOptions).on('complete', function(data, response) {
                if (response.statusCode != 200)
                    console.log('Purge failed');
                else {
                    console.log('Purge request Issued');
                    purgeID = data.Id;
                    setTimeout(function() {
                        rest.get(config.edgecast.get_purge_url + purgeID, purgeOptions).on('complete', function(data) {
                            if (data.CompleteDate) {
                                console.log('Purge completed on ' + data.CompleteDate);
                                rest.put(config.edgecast.load_url, loadOptions).on('complete', function(data, response) {
                                    if (response.statusCode == 200)
                                        console.log('Asset Loaded');
                                    else {
                                        console.log('Load Failed');
                                        console.log(response.statusCode);
                                    }
                                });
                            }
                        });
                    }, 180000);
                }
            });
        } else console.log('File Transfer Failed. ' + hadError);
        ftp.raw.quit(function(err) {
            if (err) return console.error(err);
        });
    });
};
```

**Comment by jmm** [comment]
@osambhus Please mark up code in your posts.

**Comment by osambhus** [comment]
Updated. Sorry about that.

**Comment by jmm** [comment]
@osambhus Awesome, thank you. It's also great to mark up inline snippets like file and method names by wrapping them in a pair of single backticks.

**Comment by osambhus** [comment]
Done :)

**Comment by jmm** [comment]
@osambhus Great! I noticed this week that GitHub styles `<kbd>` elements nicely, e.g. <kbd>Control+C</kbd> (not saying this to nitpick or that you need to edit your post again, just thought you might be interested -- I've always marked that stuff up with backticks until this week).

Does another task depend on the task that calls that function with the `setTimeout()`? Maybe you need to take a callback in your task and pass that to the function that calls `setTimeout()`.

**Comment by osambhus** [comment]
Oh yeah. Thanks for the tip. I didn't go through the mark down instructions properly I guess :).

Nope. There are no dependent tasks. I've tried using a callback as well. It doesn't work. 

Here is the task.

```javascript
gulp.task('deploy', function() {
    edgecast.main();
});
```
That is all it does for now. But it is messing up my other tasks that are in no way related to this one. If it don't require the `egdecast.js` file, everything works great. So I'm guessing it is something in the `edge cast.js` file or one of the libraries it is importing. Not sure.

I've added the code in the `edgecast.js` file in the post.

**Comment by jmm** [comment]
So if you just require `edgecast.js` but don't call the function it hangs?

**Comment by osambhus** [comment]
That is correct.

**Comment by jmm** [comment]
@osambhus Can you post a link to the whole file?

**Comment by jmm** [comment]
@osambhus FWIW I'm skeptical this is going to turn out to be a gulp issue, but not sure what's going on at this point.

**Comment by osambhus** [comment]
```javascript
'use strict';

var rest = require('restler'),
    config = require('./config'),
    JSFtp = require('jsftp');

var ftp = new JSFtp({
    host: config.ftp.host,
    port: 21,
    user: config.edgecast.username,
    pass: config.edgecast.password
});

var httpHeaders = {
    'Authorization': config.edgecast.token,
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Host': 'api.edgecast.com'
};

var purgeRequestBody = {
    'MediaPath': config.edgecast.purge_media_path,
    'MediaType': 8
};

var loadRequestBody = {
    'MediaPath': config.edgecast.load_media_path,
    'MediaType': 8
};

var purgeOptions = {
    data: JSON.stringify(purgeRequestBody),
    headers: httpHeaders
};

var loadOptions = {
    data: JSON.stringify(loadRequestBody),
    headers: httpHeaders
};
var purgeID;

var main = function () {
    console.log(config.edgecast.username);
    ftp.put(config.ftp.local_path, config.ftp.remote_path, function(hadError) {
        if (!hadError) {
            console.log('File transferred successfully');
            rest.put(config.edgecast.purge_url, purgeOptions).on('complete', function(data, response) {
                if (response.statusCode != 200)
                    console.log('Purge failed');
                else {
                    console.log('Purge request Issued');
                    purgeID = data.Id;
                    setTimeout(function() {
                        rest.get(config.edgecast.get_purge_url + purgeID, purgeOptions).on('complete', function(data) {
                            if (data.CompleteDate) {
                                console.log('Purge completed on ' + data.CompleteDate);
                                rest.put(config.edgecast.load_url, loadOptions).on('complete', function(data, response) {
                                    if (response.statusCode == 200)
                                        console.log('Asset Loaded');
                                    else {
                                        console.log('Load Failed');
                                        console.log(response.statusCode);
                                    }
                                });
                            }
                        });
                    }, 180000);
                }
            });
        } else console.log('File Transfer Failed. ' + hadError);
        ftp.raw.quit(function(err) {
            if (err) return console.error(err);
        });
    });
};

module.exports.main = main;
```

Here is the file. It is pretty small as of now and not that complicated so I thought of putting it here itself. Thought this would be easier.

**Comment by contra** [comment]
This issue has nothing to do with gulp but I'll answer it anyways: Your problem is that you are opening a connection and not closing it. In node, when you do asynchronous work it keeps the process from exiting. Open connections qualify as asynchronous work. If you have an open http request, db connection, or in your case FTP connection the process will not end until it is finished (closed).

**Comment by osambhus** [comment]
@contra That makes sense. Thanks a lot for the input. I'll have to handle the FTP connection a little better.
