### ISSUE TITLE
gulp 3.9.0 hanging (Win 7 64-bit, both MSYS Git Bash and CMD)

### ISSUE THREAD

**Issue by mchameddie** [gulpjs/gulp#1147]
Hello,

Have made several attempts to install and run gulp today. Appears to install correctly, but when running gulp or gulp -v, I only see the current time. In Git Bash, gulp -v returns me to a bash prompt; in CMD, it writes out 2 or 3 blank lines and the cursor freezes in the middle of the last. I've attached screen captures of both windows.

I am running Windows 7 64-bit and using MSYS MingW (Git Bash), which at least returns me to a prompt after gulp -v fails. Many thanks in advance for assistance.

Thank you,
Eddie M

![gulp_output_gitbash](https://cloud.githubusercontent.com/assets/12733917/8628470/f4eda966-2718-11e5-8b07-0a8360b75fe0.png)
![gulp_output_cmd](https://cloud.githubusercontent.com/assets/12733917/8628469/f4ec6cae-2718-11e5-8766-bc393ec4d727.png)

**Comment by marvinhagemeister** [comment]
These kind of problems occur when there a task doesn't emit the end event. Can you post the content of your gulpfile.js?

**Comment by mchameddie** [comment]
Thank you, Marvin. I just attempted commenting out everything except a blank default function, then tried adding a console.log("hello"), just to see if it would even get that far. No dice. My root path is quite long, but only 107 characters (counting slashes). So if there is a 265 (or 256?)-character limit, I'm well within.

In the meantime, here's the basic gulpfile.js I tried. As you can see, I'm brand-new to gulp, so I'm just starting out with bare-bones basics.

var gulp = require('gulp');

gulp.task('default', function() {
     // place code for your default task here
     console.log('hello');
});

**Comment by geekflyer** [comment]
which version of node are you using?

Can you please try a clean install of gulp via:
```sh
rm -rf node_modules
npm uninstall -g gulp
npm cache clean
npm install -g gulp
```

Also, can you please run via PowerShell instead and see what happens?

**Comment by mchameddie** [comment]
THANK YOU, GEEKFLYER! Looks like running in PowerShell and/or cleaning the npm cache might've done it.

The rm -rf threw an error msg in PS, so I tried it in my Bash shell. It proceeded to refuse on all node_modules directories, either because the pathnames were too long OR the directories weren't empty. Which is fine with me because I really didn't want to have to re-git clone all those from our main repo.

The remaining steps worked fine in PS, and now I get:

$ gulp -v
[10:56:29] CLI version 3.9.0
[10:56:29] Local version 3.9.0

Also tested gulp -v in my Bash and CMD prompts. Bash worked fine; CMD needed a bit more prompting (pun not intended), but with a bit of assistance from coworker, CMD gulp -v finally came around.

Thanks again so much (to everyone who replied)! I will close this issue. Have a great week, all!  :)
