### ISSUE TITLE
gulp docs in Simplified Chinese

### ISSUE THREAD

**Issue by lisposter** [gulpjs/gulp#1148]
Hi, everyone, since I saw the "Spanish documentation", I began to  translate the docs into Simplified Chinese, and it almost done now.

Like the Spanish docs, I have created a repo [https://github.com/lisposter/gulp-docs-zh-cn](https://github.com/lisposter/gulp-docs-zh-cn) for the docs in zh-cn.

From now, I plan to review all the docs, and keep sync with the English doc.

**Comment by phated** [comment]
Thanks! Please submit a PR adding this to the documentation index.

**Comment by lisposter** [comment]
@phated Sounds cool!  Added it in PR  #1151

**Comment by contra** [comment]
Thanks!
