### ISSUE TITLE
gulp.watch ignore paths does not support !./ syntax.

### ISSUE THREAD

**Issue by sondreb** [gulpjs/gulp#1153]
When working with Gulp it's often that developers use ./ syntax in their configuration and paths to indicate from the current running folder, I presume.

This means variables for some paths might start with "./" and the ignore ! declaration for gulp.src does not work with a ./ prefix to the path.

I guess I could do a string replace of "./" to ensure the path does not contain it, but perhaps this is a scenario that should be supported by Gulp?

**Comment by contra** [comment]
Can you show me a case where this isn't working? AFAIK this should work fine

**Comment by sondreb** [comment]
Here is more details, this is on Windows 10:
```javascript
var filteredPaths = ['app\\**\\*.js', '!./app/app.js', '!app\\shared\\**\\*.js'];

gulp.watch(filteredPaths, function (event) {
    //	'!./app/app.js' triggers when app.js is modified
    //	'!.\\app\\app.js' triggers when app.js is modified
    //	'!/app/app.js does not trigger when app.js is modified

});
```

**Comment by contra** [comment]
Ah that's watch not gulp.src, totally different globbing engine. Is the problem only with watch?

**Comment by gigablox** [comment]
```js
index: {  
    src: dest + "/index.html",
    dest: dest,
    sources:[
      dest+'/css/*.css',
      dest+'/js/jquery.js',
      dest+'/js/!(app.js|bootstrap.js)*.js',
      dest+'/js/app.js',
      dest+'/js/bootstrap.js'
    ],
    options:{
      ignorePath:['/www'],
      addRootSlash:false
    }
  },
```

Out of nowhere globbing patterns stopped working. Have not changed my manifest at all. Was wondering if you are aware of any `gulp` dependencies that changed or if any of your project dependencies are pointing to latest that would cause this behavoir.

**Comment by phated** [comment]
@gigablox please don't hijack threads with your problems. Open a new issue or your stuff will be skipped/lost. Thanks

**Comment by gigablox** [comment]
@phated Calm down chief - this question was related enough to be asked here.

**Comment by phated** [comment]
@sondreb any feedback on @contra's last question?
