### ISSUE TITLE
Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by Manaus** [gulpjs/gulp#1155]
Hello, I'm running `node 0.12.7`, `npm 2.11.3` on Win7, and running this code returns a 'Task default is not in your gulpf file': 

    [11:43:50] Using gulpfile ~\Web\mywebsite\gulpfile.js
    [11:43:50] Task 'default' is not in your gulpfile
    [11:43:50] Please check the documentation for proper gulpfile formatting

This is the code 

    var gulp = require('gulp'),
	watch = require('gulp-watch'),
	jade = require('gulp-jade'),
	less = require('gulp-less');

    // functions ----------------------

    gulp.task('default', ['compile']);

    gulp.task('compile', function() {
	    return gulp.src('./less/*.less')
		.pipe(less())
		.pipe(gulp.dest('./css'));
    })

This are my installed modules: 

    ├── browser-sync@2.7.13
    ├── gulp@3.9.0
    ├── gulp-coffee@2.3.1
    ├── gulp-jade@1.0.1
    ├── gulp-less@3.0.3
    ├── gulp-plumber@1.0.1
    ├── gulp-stylus@2.0.5
    ├── gulp-watch@4.3.3
    ├── lost@6.5.0
    └── require-dir@0.3.0

Thanks

**Comment by ilovezy** [comment]
maybe you should put the 

gulp.task('default', ['compile']);

after the compile task was defined? you can not bind the compile task into default before decare it?

**Comment by Manaus** [comment]
Thanks ilovezy, that fixed the issue.

**Comment by Manaus** [comment]
Am I mistaken if I say this is a workaround? On the mac platform hoisting seems to work fine

**Comment by ilovezy** [comment]
I'm not sure,I'm saving money to buy a mac, it seems a little expensive to me now

**Comment by Manaus** [comment]
I'd reopen this, I don't think the order of the task should be that important.

**Comment by ilovezy** [comment]
It's not the gulp's problem,I think it's beacuse Javascript it self， gulpfile.js is just a js file
like this

console.log(message)
var message = 'hello cc'

you can only get : message is not defined ,
maybe there will be a way to finish this, 
perhaps the default will not be decared if the tasks are not found

**Comment by Romanx** [comment]
This is related to where the tasks are defined prior to their use. JS natively hoists variables as can be found [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var) but i'm not sure if that is different for node/gulp i'd assume not.

This is another good example explaining complications [here.](http://jamesallardice.com/explaining-function-and-variable-hoisting-in-javascript/)

I think this should be closed as theirs nothing gulp can really do. You could use manual hoisting by defining name function variables as opposed to defining them in gulp.task that should cause them to be hoisted.
