### ISSUE TITLE
4.0: `gulp --tasks-simple` doesn't return descriptions

### ISSUE THREAD

**Issue by SyntaxRules** [gulpjs/gulp#1157]
`gulp --tasks-simple` doesn't return descriptions

`gulp -T` does.

I think `gulp --tasks-simple` should return descriptions.

Thoughts?

**Comment by phated** [comment]
`--tasks-simple` can't return descriptions, as it is used by tools that generate lists of build tasks

**Comment by SyntaxRules** [comment]
I guess this would be an enhancement request then.

Would a command like `--tasks-simple-with-descriptions` allow tools to work with the `--tasks-simple` function and still give me the nice display? (A better name/command would be appropriate)

I would really like this addition because it would give others that want to use my gulpfile a nice way to view top level tasks and their descriptions. Determining what tasks are available to me is the first thing I normally do when getting a new gulpfile.

**Comment by phated** [comment]
--tasks and --tasks-json might be getting a optional depth argument, not sure yet
