### ISSUE TITLE
4.0: named functions cannot have a different displayName

### ISSUE THREAD

**Issue by SyntaxRules** [gulpjs/gulp#1158]
An example of this behavior looks like this:
```js
//gulpfile.js

function nameTest(done) {
	done();
}
nameTest.displayName = 'name-test';
nameTest.description = 'this is a description';

var nameTest2 = function (done) {
	done();
};
nameTest2.displayName = 'name-test2';
nameTest2.description = 'this is a description2';

gulp.task('name-test', nameTest);
gulp.task(nameTest);
gulp.task(nameTest2);

//output to gulp --tasks-simple
nameTest
nameTest
name-test2

//output to gulp -T
[14:49:19] ├─┬ nameTest                             this is a description
[14:49:19] │ └── name-test
[14:49:19] ├─┬ nameTest                             this is a description
[14:49:19] │ └── name-test
[14:49:19] └── name-test2                           this is a description2
```

I would like the task `nameTest` to be used as `name-test`.

This is consistent with the documentation:
> gulp.task names the task after the function displayName property if function is anonymous and the optional name parameter of gulp.task is not provided.

But this doesn't make much sense to me, shouldn't the output of `gulp --tasks-simple` and `gulp -T` include `name-test` instead of `nameTest`?

**Comment by phated** [comment]
This has already been submitted and merged in upstream undertaker, not published yet, waiting on a few more fixes.

**Comment by SyntaxRules** [comment]
Thanks!
