### ISSUE TITLE
npm install -g gulp fails with Error: No compatible version found: deprecated@'^0.0.1'

### ISSUE THREAD

**Issue by joelsaxton** [gulpjs/gulp#1160]
I am on a vanilla EC2 instance of Amazon Linux and I am unable to install gulp onto this box.

This is my configuration:

npm --version
2.11.3
node --version
v0.12.7

when I run:

sudo npm install --global gulp

I get a bunch of successful http responses, but then I get hit with this:

npm ERR! Error: No compatible version found: deprecated@'^0.0.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1"]
npm ERR!     at installTargetsError (/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.14.44-32.39.amzn1.x86_64
npm ERR! command "node" "/bin/npm" "install" "-g" "gulp"
npm ERR! cwd /usr/local/lib/node_modules
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm http 304 https://registry.npmjs.org/vinyl-fs
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/archy
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
npm ERR! not ok code 0

**Comment by tunnckoCore** [comment]
which version of `gulp` or `gulp-cli`?

**Comment by joelsaxton** [comment]
Thank you. Not quite sure what you mean. I'm trying to install it. I also tried this:

sudo npm install --global gulp@3.9.0 

but I got the same results. Is there a particular version I should be telling it to install?

**Comment by Nirazul** [comment]
You log file is in contradiction to the versions you provided:

```
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
```

Is it possible that the command is executed in another environment with different versions?

**Comment by joelsaxton** [comment]
Yeah, thanks. I will see if I can figure out what happened.
