### ISSUE TITLE
Gulp logo: missed opportunity?

### ISSUE THREAD

**Issue by nafarlee** [gulpjs/gulp#1161]
I feel like it was a missed opportunity to not have all of the fonting in the "Gulp" logo connected, specifically the "G" connecting to the "ulp." 
Wouldn't that sort of represent the whole "data streaming smoothly through a bunch of varied pieces" philosophy much better?

**Comment by contra** [comment]
Open to a PR, logos are all at https://github.com/gulpjs/artwork
