### ISSUE TITLE
Default debounce for watch

### ISSUE THREAD

**Issue by adambuczynski** [gulpjs/gulp#1162]
Is it possible for Gulp to have a default debounce value for watch tasks?
After doing a find & replace in Atom I get the following:

![ss](https://www.dropbox.com/s/yn11tj6jbuzfro5/Screenshot%202015-07-23%2012.18.27.png?dl=1)

And then:

![ss](https://www.dropbox.com/s/cdyn2hzljf2kh5t/Screenshot%202015-07-23%2012.24.17.png?dl=1)

The task:

```javascript
/**
 * Watch client side code
 */
function watchClientCode() {
  gulp.watch([
    config.assets.client.js.app,
    config.assets.client.html
  ], gulp.series(lintCode, testClientCode, buildAppJs, buildIndex));
}
```

It would be better if Gulp would automatically debounce the watch task for half a second or so before running, so to avoid running 50 times if I make a replacement in 50 files.

This is with Gulp 4.0

**Comment by tkellen** [comment]
`gulp.watch` is just [gaze](/shama/gaze) (via [glob-watcher](/wearefactal/glob-watcher)). The second argument is the options object, which supports `debounceDelay`.

**Comment by tkellen** [comment]
Also documented here:
https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#gulpwatchglob-opts-fn

**Comment by adambuczynski** [comment]
I am aware of the debounceDelay option, but as I mentioned in my issue, I think gulp should set this to a sensible default value, rather than have it default to 0, which I presume the default setting is.

**Comment by tkellen** [comment]
If this were to be implemented, I believe it should happen in gaze, not gulp. Wherever possible we try not to introduce special semantics for the dependencies we use. I'll defer to @phated and @contra on this one though.

**Comment by jmm** [comment]
@adambuczynski Do you have a sensible default in mind? At a glance it [looks like `gaze` defaults to `500`](https://github.com/shama/gaze/blob/3f8823445dec98393c26f5864de81c2512cca322/lib/gaze.js#L47):

```js
opts.debounceDelay = opts.debounceDelay || 500;
```

BTW @tkellen your `glob-watcher` repo link is missing a char.

**Comment by adambuczynski** [comment]
@jmm If Gaze really defaults to 500ms and if Gulp just uses that value, then it seems to be a tad bit too short for the scenario when you're saving multiple files at once.

I've set the debounce value to 1000ms for my projects now, which seems to avoid the issues I've described above.

**Comment by phated** [comment]
Like @tkellen stated, all defaults should go into the dependency where they are the default, not in our abstractions. Gaze 0.5 is no longer supported, I believe, so whatever its default is will continue to be the default. In 4.0, that might be changed when we upgrade/change the watcher. Feel free to use another watcher or set the option in the meantime.

**Comment by adambuczynski** [comment]
@phated Could you explain the reasoning behind that decision, because I fail to see the why having a gulp specific default which is *more* sensible to the actual functionality would be a bad thing.

If Gaze would default to 5 seconds for some reason, surely Gulp would adjust the default?

Just curious what your reasoning is.

**Comment by phated** [comment]
It is bad form for consumers to traverse a whole tree of abstractions to find defaults and overrides. Gulp isn't a watching library and just exposes it through an abstraction, so we have less knowledge and expertise in deciding a sane default. This has not been brought up before (or rarely at best since I can't remember any times) which means gaze picked a sane default. And since we pass the options through (like a good abstraction) you can adjust the options to fit your environment.

**Comment by adambuczynski** [comment]
Thanks!
