### ISSUE TITLE
Have gulp return a value when run from command line

### ISSUE THREAD

**Issue by binarykitchen** [gulpjs/gulp#1166]
I am trying to do something like this in a bash file

```bash
VERSION=gulp bump --importance=$IMPORTANCE
```

whereas `gulp bump` is a gulp task which is supposed to do some modifications and to return a value back to the command line. Have searches in your recipes but found nothing similar. Any clues?

**Comment by phated** [comment]
gulp isn't a tool for building command line tools.  this use case is far outside of anything we support or plan to support. sorry.

**Comment by binarykitchen** [comment]
true, just realised that. will have to parse the output somehow with the `awk` command then.
