### ISSUE TITLE
Support for .gulprc

### ISSUE THREAD

**Issue by stefanr** [gulpjs/gulp#1170]
Since gulp allows setting some options via arguments (e.g. `gulp --gulpfile=build/gulpfile.js`), I think it would be nice if we could specify these options in a separate file, e.g. `.gulprc`.

So if you have a folder structure like this, where everything that's gulp related is in a separate folder, e.g. `build`, you might want to execute gulp tasks from the root directory as well.
```
/{root}
  /build
    /node_modules
      /gulp
      /...
    /gulpfile.js
  /node_modules
    /...
  /src
  /.gulprc
```

The following `.gulprc` file would allow this.

```
{
  "gulpfile": "build/gulpfile.js"
}
```

Which is equal to `gulp --gulpfile={root}/build/gulpfile.js`.

**Comment by tkellen** [comment]
Hugely agreed! I've long desired to support this directly in [Liftoff](/tkellen/js-liftoff) but I haven't had time to tackle an implementation. I'm giving this a close, but feel free to continue this discussion in tkellen/js-liftoff#8 (or make a new issue there if you like).

**Comment by sindrenm** [comment]
Sorry to bump an old post, but it seems like [this was added][1] just a couple of hours after your previous comment here, @tkellen, and released in Liftoff v2.3.0. This was the newest issue I could find on the matter in this repo, so I was just wondering if there was some progress here. :smile: 

[1]: https://github.com/js-cli/js-liftoff/issues/8#issuecomment-235702317

**Comment by phated** [comment]
@sindrenm there's a bunch of open issues related at https://github.com/gulpjs/gulp-cli/issues

**Comment by sindrenm** [comment]
Oh wow, of course there are! `gulp-cli`. Right. :man_facepalming:

Thanks, @phated.
