### ISSUE TITLE
getFlags in v8flags module fails in Electron environment

### ISSUE THREAD

**Issue by s-a** [gulpjs/gulp#1172]
I figured out that v8flags seems to be a dead dependency? Or is it some kind of API gulp is publishing?

ref: https://github.com/tkellen/js-v8flags/issues/25
ref: https://github.com/s-a/iron-node/issues/22

**Comment by tkellen** [comment]
It is not a dead dependency:
https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L12

**Comment by s-a** [comment]
hehe :+1: you are faster than me
