### ISSUE TITLE
gulp.src ignore option does not work

### ISSUE THREAD

**Issue by mprokopowicz** [gulpjs/gulp#1176]
I can't get the ignore option of gulp.src working:

```
'use strict';

var gulp = require('gulp');
var debug = require('gulp-debug');

var config = {
  src: 'app/**/*.js',
  test: 'app/**/*.test.js'
}

gulp.task('default', function() {
  return gulp.
    src(config.src, {ignore: config.test}).
    pipe(debug({title: 'debug'}));
});
```

```
[01:33:38] Using gulpfile ~/Projects/gulp-src/gulpfile.js
[01:33:38] Starting 'default'...
[01:33:38] debug app/src.js
[01:33:38] debug app/src.test.js
[01:33:38] debug 2 items
[01:33:38] Finished 'default' after 19 ms
```

Am I misunderstanding something? I would really like to use ignore option in favour of "!whatever/**" pattern.

I'm using gulp 3.9.0

**Comment by contra** [comment]
gulp.src has no ignore option, I don't know why you think it does. The ignore patterns go in the same array as the rest of your globs, see the README which has an example right at the top that does this

**Comment by mprokopowicz** [comment]
@contra 
Citing [gulp API docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md):

> options
> Type: Object
> Options to pass to node-glob through glob-stream.
> gulp adds some additional options in addition to the options supported by node-glob and glob-stream:

So I understand that any option valid for [node-glob](https://github.com/isaacs/node-glob) should be also valid for ```gulp.src```.

On [node-glob](https://github.com/isaacs/node-glob) I can read:

> ignore Add a pattern or an array of patterns to exclude matches.

Moreover: I've added some console.logs to node-glob sources used by gulp and I can see, that the ignore option is passed to node-glob but has no effect.

If I use node-glob directly, the ignore option is working as expected.

**Comment by contra** [comment]
I'll refer to my original response:

> The ignore patterns go in the same array as the rest of your globs, see the README which has an example right at the top that does this

If you think the documentation isn't clear enough I will merge any PR to correct them
