### ISSUE TITLE
file watches work with relative paths, but I tried using NPM "pre" and it doesn't work with gulp 

### ISSUE THREAD

**Issue by ORESoftware** [gulpjs/gulp#1187]
Because the gulp file watches don't really work out of the box for new or deleted files, I tried doing this instead:

```json
"scripts":{
   "prestart_dev": "gulp default",
    "start_dev": "NODE_ENV=development node ./bin/www"
}
```

I run this:

```npm run start_dev```

the prestart_dev runs, as expected, but it doesn't kick off start_dev, it just sits there. Any idea what I can do to fix it?

**Comment by ORESoftware** [comment]
if you don't want to answer it here, fine I can deal with it, but please answer it on SO, thanks http://stackoverflow.com/questions/31798532/using-npm-pre-scripts

**Comment by contra** [comment]
This seems like an npm bug and nothing to do with gulp... right?

**Comment by ORESoftware** [comment]
well...I am not sure...most likely an NPM thing
