### ISSUE TITLE
Gulp -v argument badly implemented.

### ISSUE THREAD

**Issue by andrevenancio** [gulpjs/gulp#1189]
working with 'yargs' recently I found that any arguments starting with the letter "v" will return the version of 'gulp'. Basically any custom arguments we might want to pass to the gulp file, can't start with a "v".

this should return the version
```
gulp -v 
```

this should not
```
gulp -vasdjhashdkashdjkhakjsdhashkjdhakjshdkjahsjkdhaskjdajskd
```

**Comment by callumacrae** [comment]
`gulp -vasd` is the equivalent of `gulp -v -a -s -d`, they're short flags. This is not a gulp issue and you should take it up with the yargs author if you have an issue with this behaviour.

**Comment by DavidR91** [comment]
Pretty sure this *is* is a gulp issue:

` gulp -IDoBeliveThisIsABug`
`[14:07:59] CLI version 3.9.0`

Omit the v:
`gulp -IDoBelieThisIsABug`
`[14:08:37] Local gulp not found in ~`

:+1:

**Comment by DavidR91** [comment]
(To clarify: I think is a Gulp issue because it seems ridiculous that parsing short flags means you can choose to parse only a single letter from the middle of the input and decide to omit every character before and after it)

**Comment by andrevenancio** [comment]
To be fair @callumacrae it is a gulp issue... It still happens even if I'm not using the yargs package. I shouldn't be able to get the version number if I type gulp -vvvvvvvvvvvvv. 
gulp should check strict flags. -v or -version for example. shortcuts like -vasd shouldnt be the equivalent as -v -a -s -d

So, I'm with @DavidR91 on this one... :)

**Comment by dinoboff** [comment]
Why `-vasd` shouldn't be the equivalent of `-v -a -s -d`? that's what I would expect.

If there's a bug is to not report the unrecognised flags.

**Comment by callumacrae** [comment]
Gulp can't detect the unrecognised flags because it doesn't know what flags you're using in your gulpfile.

**Comment by callumacrae** [comment]
@DavidR91: The first one is outputting the version number, the second one is running gulp normally but with a tonne of unrecognised flags. What's weird about that?

**Comment by phated** [comment]
Short flag collapsing is standard in almost every unix command.  You understand why `git commit -am "message"` works, right?  It is because `-am` gets expanded to `-a -m`.  @callumacrae has address every other point very well. This isn't a bug and won't be changed.

**Comment by contra** [comment]
lol ^
