### ISSUE TITLE
Publish a 3.10 version with updated vinyl module (basename, dirname & extname)

### ISSUE THREAD

**Issue by Delapouite** [gulpjs/gulp#1191]
Hi

In June the PR of @jeremyruppel https://github.com/wearefractal/vinyl/commit/e09817f15e4ddfc28e1b3452bbca5e2ba1fc2f19 adding handy accessors to `basename`, `dirname` and `extname` was published as vinyl@5.0

This update has also been reflected in the vinyl-fs module in https://github.com/wearefractal/vinyl-fs/commit/3a44b5da290c1d0279381a4d13f8816bc2ebb014 upon which gulp depends.

Could a new version of gulp be published on the 3.x branch bumping the vinyl-fs so that we can benefit of these accessors along the pipeline?

**Comment by contra** [comment]
@Delapouite There are breaking changes in vinyl 5 and the new vinyl-fs, hence the major update to the version number.
