### ISSUE TITLE
Gulp is not working due to Expected in: dynamic lookup error.

### ISSUE THREAD

**Issue by lokeshjain2008** [gulpjs/gulp#1193]
I have tried many things updated `npm`. installed and uninstalled `gulp` many times.
Below is the screenShot of my terminal.
![screen shot 2015-08-08 at 1 38 38 am](https://cloud.githubusercontent.com/assets/2353424/9144973/825419f0-3d6e-11e5-8b0e-18e6a9ea715f.png)

Help me to resolve this. I need `gulp` to survive.

**Comment by phated** [comment]
This has nothing to do with gulp.  Notice the error is referencing browser-sync.
