### ISSUE TITLE
Is a loop plugin viable?

### ISSUE THREAD

**Issue by mrzealot** [gulpjs/gulp#1194]
Hi all!

First off, I'm just getting started familiarizing myself with gulp. I'd like to (also) use it as a static site generator and replicate the jekyll behaviour of templating markup files.

My problem is with handling layouts that can have their own layouts (e.g., [here](https://github.com/jekyll/jekyll/blob/master/site/_layouts/docs.html)). This docs template injects its `content` variable into itself (along with some includes) but it is also, in turn, injected as `content` into the default layout.

As far as I can tell, achieving this with gulp would require some kind of looping on the stream level. But it wouldn't have to be "jekyll-specific" as it could be similar to [gulp-if](https://github.com/robrich/gulp-if) and just keep applying its stream parameter until a condition is true (like a while loop, so maybe gulp-while...). One step is relatively easy with something like:

    gulp.src('*.md')
        .pipe(gulpData()) // extract yaml
        .pipe(gulpMarkdown())
        .pipe(gulpConsolidate('engine', function(file){
            return file.data // use gulp-data as local vars in e.g. jade
        }))
        .pipe(gulp.dest(...))

And (I imagine) recursion would look something like:

    gulp.src('*.md')
        .pipe(gulpData()) // extract yaml
        .pipe(gulpMarkdown())
        .pipe(gulpWhile(
            function(file) { // condition fn
                return !!file.data.layout // until the file should be injected somewhere
            }, gulpData() // extract layout yaml, if any
            .pipe(gulpConsolidate(...))
        ))
        .pipe(gulp.dest(...))

Unfortunately I haven't found anything like this yet.

So I guess my main question is: is such a thing viable? I might not be intimate enough with the gulp paradigm yet to realize that this whole situation could be avoided or solved in another way.
So if it:
- *is* viable:
  - Is there something like this already that I missed?
  - If there isn't, should one be written? Should I write it? :)
- *Isn't* viable:
  - Why? How can this be circumvented?

Thanks!

**Comment by phated** [comment]
Streams are already like a while loop, they are called once for every file in your stream until it is exhausted. Gulp-if should work fine for the case you described.

**Comment by mrzealot** [comment]
@phated Firstly: thanks for the quick reply!

Streams *do* loop over files but they, as you yourself said, are called *once* for every file. The "looping" I'm talking about would be a stream being called **multiple times** on a set of files.

It's all well and good that each `.md` would get layouted (in-place, as it would modify the file contents in the stream) but I need them to keep getting layouted until there is a layout property in the yaml front-matter. For this to work, I think the files would need to enter the layouting pipe in a loop.

E.g., there is a "global" site layout in `global.jade`:

    html
        head
        body
            div.content != content

... and a blog post wrapper in `post.jade`:

    ---
    layout: global.jade
    ---
    
    article != content

... and finally the content in `test-post.md` and lot of other `.md` files like it:

    ---
    layout: post.jade
    ---
    ## This is markdown content here...

If I then say `gulp.src('*.md').pipe(trafo())` then each `.md` file would get **one pass** of the trafo and would be layouted with the `post.jade` template, but to chain this intermediate state to get layouted *again* with the `global.jade`, I'd need to write the `.pipe(trafo())` part twice. Which is okay, if I know beforehand that there can only be 2 levels, but what if there can be an arbitrary depth?

I hope I made the issue clearer... If I'm the one that not understanding something, please clarify how you'd solve this scenraio with only gulp-if.
