### ISSUE TITLE
support for params in gulp

### ISSUE THREAD

**Issue by ORESoftware** [gulpjs/gulp#1198]
Is this really the best way to pass params to a gulp task?

https://www.npmjs.com/package/gulp-param

considering the number of downloads it seems to be a quite popular and much-desired feature. I have seen gulp commiters say they don't want this, but...I am really flabbergasted about this. Why isn't this feature in "core'?

**Comment by phated** [comment]
A single gulp task should contain the entire pipeline.  On top of that, your build process is based on a singleton, so global variables aren't any more harmful.  This isn't a feature that we are going to add, as it goes far past the scope of this project.

**Comment by ORESoftware** [comment]
I am looking for a way to do this:

```javascript
var mgp = require('my-gulp-plugin');

gulp.task('do-an-iteration', options, function(cb){
   mgp.doTheWork(options,function(){
         cb();
  });
});

gulp.task('default', function(){
  for(var i = 0; i < 10; i++){  // this is just a placeholder, in reality we'd want to loop over some meaningful array of filepaths or what not
  gulp.run('do-an-iteration', {
      readFilePath:someVariable,
      outputFilePath:someOtherVariable
   });
  }
});
```

how is this way outside the scope of this project? This IS this project? I clearly don't get it. What am I missing? thanks

**Comment by ORESoftware** [comment]
nevermind, I remember reading that you guys wanted/expected people to create the loop inside the task itself - so that basically everything would be declared/initialized/required in the task itself. So I would put the looping construct inside 'do-an-iteration', like so:

```javascript
var mgp = require('my-gulp-plugin');

gulp.task('do-an-iteration', function(cb){
       var array = []; //some array object with useful objects as elements/items
    async.eachSeries(array, function iterator(item, callback) {
       mgp.doTheWork(item,callback);
      }
    }, function done() {
       cb();
    });
});

gulp.task('default', function(){
    gulp.run('do-an-iteration');
});
```

I guess my only question left is I don't understand what the successor is for gulp.run, since gulp.run is deprecated, it's not clear what replaces it or what not.

**Comment by TrySound** [comment]
@ORESoftware You can use something like [minimist](https://github.com/substack/minimist) to pass param independently of gulp.

**Comment by phated** [comment]
@ORESoftware the replacement for gulp.run is to just call functions.  Gulp 4 is all about function composition and reuse.

**Comment by ORESoftware** [comment]
ok cool thanks then

**Comment by ORESoftware** [comment]
thanks @TrySound I will check out minimist, I have heard of that lib but never knew what it was for

**Comment by TrySound** [comment]
@ORESoftware It just parses command opts like `gulp build --min --lint`

**Comment by ORESoftware** [comment]
oh thanks, originally I was asking about arguments to gulp.task in the program not at the command line

I was just confused about what the gulp-param module did and also confused about why params couldn't be sent to gulp.task, turns out the gulp-param module deals with command line args not args in the program itself.
