### ISSUE TITLE
gulp4 install issue on ubuntu 14.04

### ISSUE THREAD

**Issue by CaptainChainsaw** [gulpjs/gulp#1199]
Hi,

I'm having an issue installing gulp4 as it is required by angular-strap.  I ran:

`sudo npm install gulpjs/gulp-cli#4.0 -g` 

This is what I got in the log file.  Anyone got an ideas how to get this installed?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'gulpjs/gulp-cli#4.0',
1 verbose cli   '-g' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'gulpjs/gulp-cli#4.0', null ]
5 verbose cache add name=undefined spec="gulpjs/gulp-cli#4.0" args=["gulpjs/gulp-cli#4.0",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: '#4.0',
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'gulpjs/gulp-cli',
6 verbose parsed url   path: 'gulpjs/gulp-cli',
6 verbose parsed url   href: 'gulpjs/gulp-cli#4.0' }
7 silly lockFile dd154dca-gulpjs-gulp-cli-4-0 gulpjs/gulp-cli#4.0
8 verbose lock gulpjs/gulp-cli#4.0 /home/graeme/.npm/dd154dca-gulpjs-gulp-cli-4-0.lock
9 info maybeGithub Attempting gulpjs/gulp-cli#4.0 from git://github.com/gulpjs/gulp-cli#4.0
10 silly lockFile b7be6e36-t-github-com-gulpjs-gulp-cli-4-0 git://github.com/gulpjs/gulp-cli#4.0
11 verbose lock git://github.com/gulpjs/gulp-cli#4.0 /home/graeme/.npm/b7be6e36-t-github-com-gulpjs-gulp-cli-4-0.lock
12 verbose addRemoteGit [ 'git://github.com/gulpjs/gulp-cli', '4.0' ]
13 silly lockFile fb042cb1-git-github-com-gulpjs-gulp-cli git://github.com/gulpjs/gulp-cli
14 info maybeGithub Attempting gulpjs/gulp-cli#4.0 from git+ssh://git@github.com:gulpjs/gulp-cli#4.0
                                                                                             1,1           Top

**Comment by phated** [comment]
1. Don't install things with sudo, your environment is messed up if you are using sudo
2. Update your node and npm.  Your node is out-of-date, even on the 0.10 branch and your npm is insanely out of date.
3. Installation isn't a gulp issue, it is almost always your environment, and if it isn't your environment then it is an npm issue.
