### ISSUE TITLE
Codependent tasks in Gulp 4

### ISSUE THREAD

**Issue by timkelty** [gulpjs/gulp#1200]
- I have a `build` task that runs `build-rev`.
- I also want the `build-rev` task to run `build` _if_ the `build` task hasn't run.

Is there a good way to achieve this?

```js
gulp.task('build',
  gulp.series(
    'clean',
    gulp.parallel(
      'build:js',
      'build:css',
      'build:img',
      'build:misc'
    ),
    'build:rev',
    'lint'
  )
);
```

```js
var path     = require('path');
var config   = require(path.join(process.cwd(), 'gulpfile.js/config'));
var gulp     = require('gulp');
var rev      = require('gulp-rev');
var jsonDest = path.join(config.paths.destAssets, 'json');

var src = [
  path.resolve(config.paths.destAssets, '**/*.css'),
  path.resolve(config.paths.destAssets, '**/*.js')
];

gulp.task('build:rev', gulp.series(
  'build',
  function() {
    return gulp.src(src, {base: config.paths.dest})
    .pipe(rev())
    .pipe(gulp.dest(config.paths.dest))
    .pipe(rev.manifest())
    .pipe(gulp.dest(jsonDest));
  }
));
```

**Comment by phated** [comment]
You are creating a circular dependency here (even in just the way you are thinking about this).  I highly suggest you revisit the structure of your tasks and probably combine all the build tasks into a single pipeline using gulp-if to conditionally run your transforms.

**Comment by timkelty** [comment]
I figured that was the case, just wanted to make sure I wasn't missing something obvious.
Thanks!
