### ISSUE TITLE
Gulp fails to copy file with more than 1GB with RangeError message

### ISSUE THREAD

**Issue by zepedrorocha** [gulpjs/gulp#1203]
I am trying something very simple: copy a file with more than 1GB, using gulp.src and gulp.dest.
However gulp fails with the following message:
     
    RangeError: File size is greater than possible Buffer: 0x3FFFFFFF bytes
    at evalmachine.<anonymous>:282:19
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)

the code in question is very simple:

      return gulp.src(PACKAGES_PATTERN, {
      cwd: "C:\\my-src-dir",
     })
    .pipe(gulp.dest(repoPath))

This seems to be related to vinylfs, since I get the same message when dong the following:

      return fsv.src('C:\\my-src-dir\\huge-file.bin').pipe(fsv.dest('./output'))

Thx

**Comment by callumacrae** [comment]
Use another tool to do the copy, using vinyl to copy a file that big isn't efficient because vinyl reads the entire file into memory.

This solution looks good: http://stackoverflow.com/a/11295106/902207

**Comment by joaocc** [comment]
Hi,
Can we assume this also implies that gulp cannot be trusted to take care of large files, since it depends on vinyl? Or is there any alternative to get gulp to do it's amazing asynchronous/streamed thing with a different framework/library?
Thx

**Comment by callumacrae** [comment]
It means don't load large files into memory in node: https://nodejs.org/api/smalloc.html#smalloc_smalloc_kmaxlength

You can also set the `read` option to false and it won't read the contents of the file, but that's not appropriate in this scenario.

**Comment by phated** [comment]
This is unsupported by the gulp API. However, a gulpfile is just JavaScript, so require in a module that can do this and just use that.

**Comment by phated** [comment]
I just realized that you can copy large files with vinyl-fs by turning streaming mode on.

```js
gulp.src(glob, { stream: true })
```

**Comment by contra** [comment]
Yep, this is exactly why the streaming mode was created :+1:

**Comment by joaocc** [comment]
Great! Thanks!

**Comment by callumacrae** [comment]
TIL. It's not in the docs, shall I send a PR? https://github.com/gulpjs/gulp/blob/master/docs/API.md#options

**Comment by contra** [comment]
@callumacrae Sure, the docs could be clearer on that

**Comment by callumacrae** [comment]
My bad, it is in the docs! I missed it twice, somehow.
