### ISSUE TITLE
gulp not running tasks in windows 8.1 fresh install

### ISSUE THREAD

**Issue by lijith** [gulpjs/gulp#1204]
Did a fresh install of windows 8.1, node and gulp due to hdd crash.
checked the install by checking versions of them using -v flag. shows no problems there.
and npm is working.

I made a dummy project to test gulp with gulp-sass. when i ran gulp for first time windows asked which software to open files with. so i checked sublime text and the gulp.js file got opened in sublime text.
now when i run gulp in cmd the gulp.js file opens in sublime text instead of gulp running the task in gulp.js

no errors and nothing shows in cmd. Any idea why and how to solve this?

**Comment by contra** [comment]
you told windows to open executables in sublime. dont do that. go revert that in your system preferences.

**Comment by xt0rted** [comment]
Just ran into this myself. The issue was because I mistakenly called the gulp file `gulp.js` instead of `gulpfile.js`. Looks like that was the same issue reported here since they mention `gulp.js` as their file name.
