### ISSUE TITLE
Nobody working on Gulp 4 since June, Why?

### ISSUE THREAD

**Issue by robertbaker** [gulpjs/gulp#1205]

**Comment by callumacrae** [comment]
Gulp is built by volunteers. If you want to speed up the release, check these issues: https://github.com/gulpjs/gulp/issues?q=is%3Aopen+is%3Aissue+label%3Agulp4

Check out a few of the previous issues opened for more info:

https://github.com/gulpjs/gulp/issues/1068
https://github.com/gulpjs/gulp/issues/968
https://github.com/gulpjs/gulp/issues/865
