### ISSUE TITLE
update vinyl-fs to 1.0.0

### ISSUE THREAD

**Issue by evilebottnawi** [gulpjs/gulp#1206]
gulp.src have passthrough is an excellent option, it is extremely necessary

**Comment by phated** [comment]
There are breaking changes in vinyl, we can't update until 4.0. You can switch to using the 4.0 branch or just require vinyl-fs directly in your gulpfile and add it to your dependencies.

**Comment by evilebottnawi** [comment]
@phated When can we expect stable release gulp4?

**Comment by phated** [comment]
It is currently stable. No ETA on release.

Gulp is built by volunteers. If you want to speed up the release, see if you can help with any of these issues: https://github.com/gulpjs/gulp/issues?q=is%3Aopen+is%3Aissue+label%3Agulp4

Check out a few of the previous issues opened for more info:

#1068
#968
#865

**Comment by evilebottnawi** [comment]
@phated thanks
