### ISSUE TITLE
Idea: case-insensitive task names (at least for CLI)

### ISSUE THREAD

**Issue by sholladay** [gulpjs/gulp#1207]
Just food for thought here: when have you ever needed to distinguish between task `someThing` vs `something` and have different behavior for each? I propose that this is bad practice - hopefully not too controversial.

Given that, consider that in Gulp 4 the recommended approach is to have named functions all over the place. What I have been finding is that, I naturally follow the conventional camel case rules and when it comes time to register these task functions, suddenly all of my tasks have very specific casing that must be considered at the command line. It is becoming more common for me to say out loud "woops ... it's `gulp startServer` ... with a capital S".

Yes, you can still provide a string literal to explicitly name a task, but the path of least resistance is now in favor of causing confusion. I foresee a lot of `gulp --tasks`ing and fist shaking from people who are not necessarily familiar with these paradigms.

Assuming that I've made a decent case here, solving it would ideally (in my opinion) involve the task system being case insensitive. However, I recognize that would probably involve some undesirable overhead in the machinery. I wonder if there would be a cheap trick like taking care of this only in the CLI. The disconnect has more to do with the CLI user and the gulpfile than anything internal to the gulpfile itself. But that might just be confusing, too, if the insensitivity didn't hold true when referencing tasks internally.

**Comment by callumacrae** [comment]
I'm not sure how I feel about this, but I don't see any reason why this _wouldn't_ be a good idea. It would stop people from having two tasks called "something" and "Something", but that sounds like a horrible antipattern anyway.

**Comment by sholladay** [comment]
A user-land module could reduce the severity of the problem by accepting a list of tasks to automatically register along with some aliases of each.

So that would look like:

````javascript
var gulp = require('gulp'),
    tasks = require('gulp-alias');  // hypothetical module, does not yet exist

function doFoo() {
    // ... some task code ...
}

tasks(
    [
        doFoo
    ]
);
````

My lack of thought for the API name aside, it would be roughly equivalent to this.

````javascript
var gulp = require('gulp');

function doFoo() {
    // ... some task code ...
}

grunt.task(doFoo);
grunt.task('dofoo', doFoo);
// maybe also...
grunt.task('do-foo', doFoo);
````

But personally, I would end up using this module in every single gulpfile I create. And it smells bad to me, because it is not really achieving what it _wants_ to. The hope is for a programmer's knowledge and habits and the user's habits to not conflict with each other by default.

**Comment by phated** [comment]
This is probably not something we will support in the core of gulp, as it goes against standard JS.  However, this can be implemented as a custom registry in gulp 4.

**Comment by contra** [comment]
not going to do this in core
