### ISSUE TITLE
Allow using gulpfile.babel.js with either babel-core OR babel

### ISSUE THREAD

**Issue by callumlocke** [gulpjs/gulp#1212]
[Since v0.6.3](https://github.com/tkellen/js-interpret/blob/master/CHANGELOG), interpret's `.babel.js` loader is specified as an array containing both `babel-core/register` and `babel/register` – i.e. if importing `babel-core/register` fails, try `babel/register`. This should make everyone happy.

**Comment by phated** [comment]
The semver rand for interpret in gulp will allow this version to be picked up.  What is the suggestion here?

**Comment by callumlocke** [comment]
I think you also need to write some code to make use of the new interpret
feature, ie to try each loader in the array until one of them imports
without error

**Comment by phated** [comment]
@callumlocke liftoff does that for us. People just need to make sure they have a fully updated gulp and all its deps

**Comment by tkellen** [comment]
That happens already here:
https://github.com/tkellen/js-rechoir/blob/master/index.js#L30-L46

via
https://github.com/tkellen/js-liftoff/blob/master/index.js#L124-L127
