### ISSUE TITLE
Receiving Error during npm install on Window 7 64-bit

### ISSUE THREAD

**Issue by joecue** [gulpjs/gulp#1214]
I'm unable to install gulp from the command line.  I've enabled the command window to run as administrator, and still cannot get it to install.

Below are the errors I'm seeing in the command window.

C:\inetpub\wwwroot-gulp>npm install -g gulp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\jquerin\\AppData\\Roaming\\npm\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! node v0.12.2
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\inetpub\wwwroot-gulp\npm-debug.log

The npm-debug.log isn't much help either, at least to me.

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\jquerin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@2.12.0
3 info using node@v0.12.2
4 verbose install initial load of C:\Users\jquerin\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\jquerin\AppData\Roaming\npm\package.json
6 silly cache add args [ 'gulp', null ]
7 verbose cache add spec gulp
8 silly cache add parsed spec { raw: 'gulp',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed gulp@*
10 verbose addNamed "*" is a valid semver range for gulp
11 silly addNameRange { name: 'gulp', range: '*', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:37:40 PM
20 verbose request id 8cc2de3c76c44fcb
21 http request GET https://registry.npmjs.org/gulp
22 http 200 https://registry.npmjs.org/gulp
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"4PCS86L8FMW4OCT2JMRAH9W47"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '105642',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Wed, 26 Aug 2015 19:37:40 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '36',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-atl6231-ATL',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '4',
23 silly get     'x-timer': 'S1440617860.776157,VS0,VE0',
23 silly get     vary: 'Accept' } ]
24 verbose get saving gulp to C:\Users\jquerin\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
25 verbose stack TypeError: undefined is not a function
25 verbose stack     at calculateOwner (C:\Users\jquerin\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
25 verbose stack     at C:\Users\jquerin\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
25 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
26 verbose cwd C:\Users\jquerin
27 error Windows_NT 6.1.7601
28 error argv "node" "C:\\Users\\jquerin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
29 error node v0.12.2
30 error npm  v2.12.0
31 error undefined is not a function
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

I would like to give this a try and see if it fits my workflow better than grunt, but I just can't seem to get it to install.

I'm running the following.
node v0.12.2
npm  v2.12.0

Please advise.

**Comment by contra** [comment]
Your npm install is broken. Update npm.

**Comment by joecue** [comment]
Running "npm cache clean" then trying to install gulp globally seemed to have worked.  At least on one workstation.
