### ISSUE TITLE
New event for 'end but don't run dependent tasks'

### ISSUE THREAD

**Issue by derekdreery** [gulpjs/gulp#1215]
I have the following situation

  1. task runs jshint
  2. task runs browserify

Task 2 depends on task 1. If task 1 emits an error, I want to be able to catch the error (`on('error'...` and emit the "tell gulp to stop this pass" event. The `end` event unfortunately carries on with the next task in the chain, so it would need to be a new event.

**Comment by TrySound** [comment]
Show your code

**Comment by phated** [comment]
Just don't catch the error, the pipeline will be torn down and the task will exit.

**Comment by derekdreery** [comment]
If I don't catch the error - then they whole process will crash and I will lose my watches. Even if it fails I want it to wait for a change then try again.

I'll make a toy example to demonstrate.
