### ISSUE TITLE
Release a preview of gulp 4 to npm

### ISSUE THREAD

**Issue by mikehaas763** [gulpjs/gulp#1216]
For technical infrastructural reasons that are of course different for every organization I was wondering if we could start releasing a preview/alpha/etc version of gulp 4 to npm?

**Comment by contra** [comment]
We really want to but are waiting for npm to fix some bugs before we can put the next version of gulp on npm. Without these bugs fixed, updating gulp will explode your current install (since we broke the CLI out into another module)

**Comment by contra** [comment]
AFAIK the next version of npm was just released with the fixes we requested so it might be fixed already. @phated?

**Comment by phated** [comment]
@contra just read through my twitter and I don't see an announcement.  There are a couple of breaking changes that need to be completed before we can publish a version.  pre-release tags with npm are absolutely horrible and we are going to follow the npm release cycle by posting 4.0 but tagging next, so we need to actually have the breaking changes complete before anything can be published.
