### ISSUE TITLE
semver .js:281 throw new TypeError('Invalid Version: ' + version)

### ISSUE THREAD

**Issue by fuonge** [gulpjs/gulp#1219]
I keep getting this typeerror when running gulp play or creating a new project with pluralsight tutorial 

Z:\coding\pluralsight-gulp>gulp hello-world
AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver
.js:281 throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: undefined
    at new SemVer AppData\Roaming\npm\node_modules\gulp\node_mo
dules\semver\semver.js:281:11)
    at SemVer.compare AppData\Roaming\npm\node_modules\gulp\nod
e_modules\semver\semver.js:348:13)
    at compare AppData\Roaming\npm\node_modules\gulp\node_modul
es\semver\semver.js:571:31)
    at Function.gt AppData\Roaming\npm\node_modules\gulp\node_m
odules\semver\semver.js:600:10)
    at Liftoff.handleArguments AppData\Roaming\npm\node_modules
\gulp\bin\gulp.js:99:14)
    at Liftoff.<anonymous> AppData\Roaming\npm\node_modules\gul
p\node_modules\liftoff\index.js:192:16)
    at module.exports AppData\Roaming\npm\node_modules\gulp\nod
e_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> AppData\Roaming\npm\node_modules\gul
p\node_modules\liftoff\index.js:185:9)
    at AppData\Roaming\npm\node_modules\gulp\node_modules\liftof
f\index.js:159:9
    at AppData\Roaming\npm\node_modules\gulp\node_modules\v8flag
s\index.js:99:14

Z:\coding\pluralsight-gulp>npm install
|
> Pluralsight-Gulp@0.1.0 install Z:\coding\pluralsight-gulp
> bower install

'bower' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! Pluralsight-Gulp@0.1.0 install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Pluralsight-Gulp@0.1.0 install script 'bower install'.
npm ERR! This is most likely a problem with the Pluralsight-Gulp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Pluralsight-Gulp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Z:\coding\pluralsight-gulp\npm-debug.log

Z:\coding\pluralsight-gulp>
npm ERR! Please include the following file with any support request:
npm ERR!     Z:\coding\pluralsight-gulp\npm-debug.log

Z:\coding\pluralsight-gulp>

Please let me know what I am doing wrong. I even installed gulp locally with
npm install gulp --dev-save 
i also rand gulp -v before gulp hello-world

**Comment by phated** [comment]
You don't have bower installed so your install is failing.  Also, the command to install gulp locally is `npm install --save-dev gulp` (not dev-save).  These are all problems with the tutorial, please report it to pluralsight or the pluralsight-gulp project.

**Comment by fuonge** [comment]
That did not work:

Z:\coding\ng2do>bower install
bower ENOENT        No bower.json present

Z:\coding\ng2do>npm install
npm WARN package.json ng2do@0.0.1 license should be a valid SPDX license express
ion

Z:\coding\ng2do>npm install --save-dev gulp
npm WARN package.json ng2do@0.0.1 license should be a valid SPDX license express
ion
gulp@3.9.0 node_modules\gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (supports-color@2.0.0, escape-string-regexp@1.0.3, ansi-styles@2
.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.
1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1
.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.
0, lodash._reevaluate@3.0.0, object-assign@3.0.0, beeper@1.1.0, lodash._reinterp
olate@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0
.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0
.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

Z:\coding\ng2do>gulp play
C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver
.js:281
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: undefined
    at new SemVer (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_mo
dules\semver\semver.js:281:11)
    at SemVer.compare (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\nod
e_modules\semver\semver.js:348:13)
    at compare (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modul
es\semver\semver.js:571:31)
    at Function.gt (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_m
odules\semver\semver.js:600:10)
    at Liftoff.handleArguments (C:\Users\137124\AppData\Roaming\npm\node_modules
\gulp\bin\gulp.js:99:14)
    at Liftoff.<anonymous> (C:\Users\137124\AppData\Roaming\npm\node_modules\gul
p\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\nod
e_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\137124\AppData\Roaming\npm\node_modules\gul
p\node_modules\liftoff\index.js:185:9)
    at C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modules\liftof
f\index.js:159:9
    at C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flag
s\index.js:99:14

Z:\coding\ng2do>gulp
C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver
.js:281
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: undefined
    at new SemVer (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_mo
dules\semver\semver.js:281:11)
    at SemVer.compare (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\nod
e_modules\semver\semver.js:348:13)
    at compare (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modul
es\semver\semver.js:571:31)
    at Function.gt (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_m
odules\semver\semver.js:600:10)
    at Liftoff.handleArguments (C:\Users\137124\AppData\Roaming\npm\node_modules
\gulp\bin\gulp.js:99:14)
    at Liftoff.<anonymous> (C:\Users\137124\AppData\Roaming\npm\node_modules\gul
p\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\nod
e_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\137124\AppData\Roaming\npm\node_modules\gul
p\node_modules\liftoff\index.js:185:9)
    at C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modules\liftof
f\index.js:159:9
    at C:\Users\137124\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flag
s\index.js:99:14

Z:\coding\ng2do>
