### ISSUE TITLE
[feature] custom gulpfile name/path

### ISSUE THREAD

**Issue by stryju** [gulpjs/gulp#122]
it would be nice to enable a way to provide a custom gulpfile name/path, like:
`gulp --gulpfile my/custom/file.js`

affected code:
https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L117

grunt handles that nicely

thoughts?

**Comment by sheryarshirazi** [comment]
I change my gulp file path from root to my public folder by using
gulp --gulpfile public/gulpfile.js
it works fine first time but when i run gulp again. it still not found the new path

**Comment by eneserdogan** [comment]
Although current file work towards problem is solved. But I would recommend for a more organized code structure to be in the main directory.

**Comment by bluebaroncanada** [comment]
How the heck do you even get a listing of commands you can run with the gulp client.  Everything I tried just runs gulp against the main gulp file.
`gulp --help` would be pretty nice.  Took me forever to find this.
