### ISSUE TITLE
fast-browserify-builds-with-watchify.md

### ISSUE THREAD

**Issue by vdclouis** [gulpjs/gulp#1230]
This recipe states that you can run the `js` task to build the file. When I try this, the task never finishes but keeps watching... Is there something I'm missing?

**Comment by callumacrae** [comment]
Watchify watches the files for changes, and so doesn't finish until it is cancelled. Read the text at the top of the recipe :)

**Comment by vdclouis** [comment]
@callumacrae myeah, this comment is rather confusing then.
```js
gulp.task('js', bundle); // so you can run `gulp js` to build the file
```

**Comment by phated** [comment]
@vdclouis please send a PR with the improvements so we can review.  Thanks.

**Comment by joeMalmsten** [comment]
@phated I tend to agree with @vdclouis. Excuse me if I'm interpreting this incorrectly but

gulp.task('js', bundle); // so you can run `gulp js` to build the file
If we run this task it never exits even when finished, so there is a watch or something hanging it up.

b.on('update', bundle); // on any dep update, runs the bundler
If the above task never finished and this starts a new task every time something has changes wouldn't we be generating a large amount of tasks sitting there watching... something? If none of those tasks exit after finishing it seems like you could have a large amount of tasks sitting there doing nothing until you close the parent task (ionic serve in my case).

the bundle task itself doesn't rebuild on a change so why is it hanging after finishing?
