### ISSUE TITLE
Gulp cannot be installed in node v4.0.0 rc1

### ISSUE THREAD

**Issue by AntouanK** [gulpjs/gulp#1233]
Something seems to be failing with `vinyl-fs`

<img width="765" alt="screen shot 2015-09-06 at 09 05 04" src="https://cloud.githubusercontent.com/assets/4569111/9703286/873250ee-5476-11e5-9d05-00f894aa0a9f.png">

**Comment by phated** [comment]
This is standard behavior of npm with prerelease versions of node.

**Comment by AntouanK** [comment]
@phated What do you mean exactly? Other packages are installed just fine...

**Comment by contra** [comment]
We could remove the engineStrict from our package.json to fix this
