### ISSUE TITLE
Controll bamboo builds

### ISSUE THREAD

**Issue by s2zaman** [gulpjs/gulp#1235]
Hi everyone,

I am using `sencha app build production` command as a task in my Bamboo Build Plan.
Issue:
 When the SENCHA BUILD fails, the Bamboo Build still goes as successful.

So i want to trigger the Bamboo Build to declare itself as FAILED, only if `sencha build` fails. I have used the following snippet as powershell script
_____________________
```
$buildLog = sencha app build production

$result = $buildLog.Contains("[ERR] BUILD FAILED")
if($result -eq 'true')
{
    echo 'Sencha Build Failed !'
    trigger to make Bamboo Build FAILED.
}
```
____________________

My Question:
I want to trigger the Bamboo Build to declare as FAILED, how can i do it  ?

**Comment by contra** [comment]
What is bamboo and what does it have to do with gulp? I don't see anything related to gulp in the code sample either

**Comment by s2zaman** [comment]
Oh sorry to post it here !
Bamboo means Atlassian Bamboo is a Continuous Integration & Build Server from Atlassian.
