### ISSUE TITLE
[HELP] Creating a plugin

### ISSUE THREAD

**Issue by oleynikd** [gulpjs/gulp#1237]
Fist of all - thank you all guys for such a great job!

I need a little help with fundamental understandings about gulp (or just node) plugin creation.
I want to create a plugin that modifies (or creates new) file based on data found in package.json.

For now what I did can be used like this ([repo](https://github.com/oleynikd/gulp-wp-file-header)):

```
var wp = require('gulp-wp-file-header')('./package.json');
return gulp.src('./style.css')
        .pipe(wp.patch())
        .pipe(gulp.dest('./'));
```

But if there's no `'./style.css'`there is no way for me to create one because pipe won't reach my plugin.

As I understand I need to skip `gulp.src()` and make my plugin responsible for reading/creating this file, right? 
I read [that guide](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md#streaming-file-objects) where it is said that plugin should always return stream that "Takes in vinyl File objects" and "Outputs vinyl File objects". But I'm not sure I understood this...

Will something like this fit into gulp's logic?:
```
var wp = require('gulp-wp-file-header')('./package.json');
return wp.patch('./style.css')
         .pipe(gulp.dest('./'));
```
Or i don't even need the `gulp.dst()` part? What about piping then...

Please help me to understand required logic.
Thanks!

**Comment by contra** [comment]
Yeah, if your plugin needs to have logic for file reading then it should replace gulp.src and be at the head of the stream (like your second example).

**Comment by phated** [comment]
You actually don't need src or dest. I recommend you just do the reading and writing yourself and don't make your interface a stream. You can just take a callback to call after everything is done. If you are pulling data from package.json that you are using in your module, there's really no reason to be a gulp plugin.

**Comment by oleynikd** [comment]
Understood. Thank you a lot for such a fast response!!!
