### ISSUE TITLE
gulp.watch seems to be very slow in comparison to browser-sync --files option

### ISSUE THREAD

**Issue by jacobg** [gulpjs/gulp#1238]
The following command sets up a listening port within a second:
```
browser-sync start --files 'src/**/*.js' --server 'src'
```

But this command takes a couple minutes before the port is set up:
```
var gulp = require('gulp');
var browserSync = require('browser-sync');

// this task utilizes the browsersync plugin
// to create a dev server instance
// at http://localhost:9000
gulp.task('serve', function() {
  browserSync({
    open: false,
    port: 9000,
    server: {
      baseDir: ['src'],
      middleware: function (req, res, next) {
        res.setHeader('Access-Control-Allow-Origin', '*');
        next();
      }
    }
  });

  gulp.watch('src/**/*.js').on('change', browserSync.reload);
});
```
The src directory tree contains 18243 js files, as it's a jspm application.

If change the gulp.watch call to ignore jspm_packages tree, then it works quickly:
```
gulp.watch(['src/**/*.html', 'src/*.js', 'src/!(jspm_packages)/**/*.js', 'src/**/*.css']).on('change', browserSync.reload);
```

But I don't have to do that for the direct call to browser-sync.

What's happening here?

**Comment by contra** [comment]
@jacobg browser-sync is probably ignoring dependency folders by default

**Comment by jacobg** [comment]
@contra Yeah it seems you're right. browser-sync is dealing with a narrower use-case than gulp.

**Comment by phated** [comment]
Closing as a non-issue.  The globs are probably too broad.
