### ISSUE TITLE
Segmentation fault with Node.js v4.0.0 and io.js v3.3.0

### ISSUE THREAD

**Issue by vidakovic** [gulpjs/gulp#1240]
Gulp crashes with the latest stable release of Node.js (v4.0.0) and with the previous io.js release (v3.3.0)

**Comment by contra** [comment]
Any more info?

**Comment by travm** [comment]
I ran into this as well, try wiping your node_modules folder and also reinstalling gulp globally. Should do the trick!

**Comment by vidakovic** [comment]
@travm 
Your suggestion works for me... thanks a ton!

@contra 
My environment: Ubuntu 14.04 LTS, io.js installed via nvm. First I thought that copying the global modules from an older installation (nvm reinstall-packages etc.) was the problem, but even a fresh install (both io.js and the global modules) didn't help. @travm 's trick with removing the project's node_modules folder fixed this.
