### ISSUE TITLE
Watch method to proxy to chokidar

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1247]
We need to update the `watch` method for gulp 4 to just use chokidar directly since vinyl-fs is removing the watch syntax in 2.0 (as per https://github.com/wearefractal/vinyl-fs/issues/92)

I know @es128 has mentioned he be able to help with this task.

**Comment by es128** [comment]
Yup I owe you a PR for this

**Comment by ddprrt** [comment]
I had a look into it. How should it behave with the different API. e.g. chokikdar's `.close` would equal `.end`. Chokidar does not feature an event object, but returns file stats. Adapt tests and feature a new API, or move to the new API and update all the docs?

**Comment by phated** [comment]
@ddprrt the watch API is going to be a tiny facade over chokidar's watch.  We don't plan to have backward-compat with gulp 3.9's watch

**Comment by phated** [comment]
The chokidar switch has been made!!!!  Closing!
