### ISSUE TITLE
semver error locating local gulp due to glob error

### ISSUE THREAD

**Issue by jsheely** [gulpjs/gulp#1251]
The long and short of it is. glob updated to fix an error in file path checking on the network. Gulp simply needs to update it's dependencies on glob

liftoff > findup-sync > glob

This currently effects build deployments on Microsoft Azure
https://github.com/projectkudu/kudu/issues/1573

See also:
https://github.com/isaacs/node-glob/issues/205

**Comment by phated** [comment]
@jsheely what were the breaking changes that caused 4.x -> 5.x, need to make sure that they don't effect dependents.

**Comment by jsheely** [comment]
I linked the breaking check issue on node-glob. 

I'm not sure if there were any breaking changes to warrant a bump in the major version from 4 to 5. From the commit history it looks like he simply felt like upgrading it.

@isaacs would have to confirm

**Comment by isaacs** [comment]
Glob bumped the major version because comments and negation are deprecated (ie, default to being disabled rather than enabled, and warn when used): isaacs/node-glob@3cf348667b64cb204347d82689734bbb0f99166a

If you were relying on those features, then that's definitely a breaking change.

**Comment by isaacs** [comment]
That is, me feeling like upgrading it had no bearing on the decision to bump the major version.  It was a breaking change.  I could have put off that breaking change, or back-ported features into 4.x, but doing so would have been more work.

**Comment by phated** [comment]
thanks for the info @isaacs 

@contra are you using the negate stuff from node-glob or some other abstraction on top?

**Comment by contra** [comment]
@phated We are doing our own negation so we are not affected by that

**Comment by isaacs** [comment]
It's very unlikely that upgrading to glob 5 will cause problems.  Very few people were using in-pattern negation and commenting.  The `exclude` option is a better approach.

**Comment by phated** [comment]
I've just bumped liftoff to 2.2.0 that switches to findup-sync version 0.3.0 which bumped semver to 5.x

Removing your gulp install and clearing cache should get the newest version.

**Comment by albertjan** [comment]
@phated when will this be pushed to npm?
