### ISSUE TITLE
Gulp not working on Node.js 4.0.x

### ISSUE THREAD

**Issue by idooo** [gulpjs/gulp#1252]
I'm getting this error when trying to run gulp (Mac OS X 10.10.5, Node.js v4.0.0)
```
'gulp' terminated by signal SIGSEGV (Address boundary error)
```

Can be related with https://github.com/nodejs/node/issues/2798

**Comment by phated** [comment]
Uninstall all versions of gulp and reinstall.  Native addons don't work cross node version

**Comment by sporto** [comment]
I did:

```
npm uninstall gulp-cli -g
npm uninstall gulp -g
rm -rf node_modules/gulp

npm install gulp-cli -g
npm install gulp --save-dev
```

Still getting `terminated by signal SIGSEGV (Address boundary error)`

Node 4.0

```
gulp -v
CLI version 0.3.0
Local version 3.9.0
```

**Comment by callumacrae** [comment]
just trash your entire node_modules directory and reinstall. it's probably something like node-sass causing the error

**Comment by sporto** [comment]
this worked :)

**Comment by chris-jarvis1** [comment]
this also worked for me, thanks!
