### ISSUE TITLE
Allow to overwrite in dest()

### ISSUE THREAD

**Issue by elyran** [gulpjs/gulp#1258]
Such a simple request yet so complicated!

Why hold it until the next major release of gulp?

Otherwise, please suggest a viable way to accomplish the same functionality.
My script:
```
gulp.task("uglify js", function () {
	gulp.src([
		"../software/**/*.js",
		"!../software/**/*.min.js",
		"!../software/**/*-min.js"
		])
		.pipe(uglify ())
		.pipe(gulp.dest("../tmp/deploy"));
});
```

**Comment by contra** [comment]
This is in the next release. Don't want to wait? Just install the latest version of vinyl-fs and use that instead.

**Comment by elyran** [comment]
What do you mean by "install the latest version of vinyl-fs" ? Install it where? Should we remove the one in gulp's "node_modules" dir? Thanks

**Comment by contra** [comment]
```
npm install vinyl-fs
```

```js
var vfs = require('vinyl-fs');

// use vfs.src, vfs.dest, whatever
```
