### ISSUE TITLE
Spanish documentation link leads to wrong repo

### ISSUE THREAD

**Issue by cassidoo** [gulpjs/gulp#1260]
This link here: https://github.com/bucaran/gulp-docs-es
Leads to this: https://github.com/bucaran/wregex

**Comment by callumacrae** [comment]
https://github.com/bucaran/wregex/issues/5

@bucaran can you fix this?

**Comment by bucaran** [comment]
Whoa, that was weird. Done.

**Comment by cassidoo** [comment]
Awesome. :+1:
