### ISSUE TITLE
how to add description to series/parallel task in gulp4?

### ISSUE THREAD

**Issue by chmontgomery** [gulpjs/gulp#1261]
I want to add a description to my generic build task, however there doesn't seem to be a way to return `gulp.series` or `gulp.parallel` from inside a task function. e.g., given the following:

```js
gulp.task('build', build);

function build() {
  return gulp.series(
    clean,
    gulp.parallel(sass, gulp.series(coffee, uglify))
  );
}
build.description = "this builds all the things";
```

This is obviously invalid (`gulp.tree` in unable to parse the build fn). Is there a different way to do this?

**Comment by chmontgomery** [comment]
sorry, nvm, just figured it out. Not the most intuitive thing but it works:

```js
gulp.task('build', build());

function build() {
  var fn = gulp.series(
    clean,
    gulp.parallel(sass, gulp.series(coffee, uglify))
  );
  fn.description = "this builds all the things";
  return fn;
}
```

**Comment by contra** [comment]
Leaving this open because I think this should work

```js
gulp.task(stuff);

function stuff(){}
stuff.description = 'yo';
```

**Comment by phated** [comment]
@contra that does work.  That's not what the original issue was talking about.  I have no idea why gulp.series/parallel is being called inside a function instead of just being used directly.  They return functions that you can augment with a description...

**Comment by chmontgomery** [comment]
@contra your example totally works. My problem was with using a description on a `gulp.series` or `gulp.parallel`. However as @phated said, I just decorated the fn returned by the above methods.
