### ISSUE TITLE
Cannot install gulp

### ISSUE THREAD

**Issue by HLRLookup** [gulpjs/gulp#1263]
It seems that gulp requires an older version of vinyl-fs.

I cannot install an older version of vinyl-fs (like `npm install vinyl-fs@0.3.9`) because older versions of vinyl-fs are not compatible with the latest version of node/npm (`npm ERR! notsup Not compatible with your version of node/npm: vinyl-fs@0.3.9` )

So I am stuck unable to install  gulp because gulp requires specific older versions of vinyl-fs which are not compatible with newer version of node/npm.

Anyone have a solution for this so I can install gulp?

Thanks,

David

**Comment by phated** [comment]
We do not officially support prerelease versions of node.  However, the issue (and needed fix) related to the messages you are seeing is at https://github.com/wearefractal/vinyl-fs/issues/91#issuecomment-139069750
