### ISSUE TITLE
FSEvents error on Gulp watch

### ISSUE THREAD

**Issue by smlombardi** [gulpjs/gulp#1271]
I've got Gulp watch running and browsersync.  Every now and then  the browser will not respond when clicking navigation.  I look at the Terminal and see

`2015-09-21 10:35 gulp[49951] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'`

Gulp keeps running and eventually responds.

Specs:
CLI version 3.8.11
Local version 3.9.0
Node v0.12.7
OS 10.11 GM (15A282b)
MBP Retina 15, Thunderbolt display

**Comment by phated** [comment]
I believe that FSEvents is just a chokidar thing and that would mean this issue is related to browsersync.  Gulp's watch currently uses gaze which I don't think uses FSEvents

**Comment by jstty** [comment]
The issue goes a bit deeper than gaze or chokidar. 
https://github.com/nodejs/node/issues/854
