### ISSUE TITLE
pull in external docs

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#1281]
right now all of the docs are scattered amongst sub-repos, and our main repo just links to them. this is really really shitty and makes it difficult to know where to file issues and difficult to find documentation.

repos that need to be pulled in:
- [x] vinyl-fs (for .src, .dest, and .symlink)
  - [x] vinyl (for what files coming out of .src and .dest look like)
  - [x] glob-stream (for .src)
- [x] chokidar (for .watch)
- [x] undertaker

**Comment by es128** [comment]
Ok. Let me see if I can help with the chokidar stuff tonight.

**Comment by phated** [comment]
Looking for some more people to contribute on the remaining items in this list.

**Comment by troch** [comment]
I thought I had commented on this, must have forgotten to click "Comment"... Looking at API.md on 4.0 branch, undertaker is referenced and its methods (task, lastRun, series, parallel) seem to have up-to-date documentation, but they are scattered. Should those API functions be grouped together, API.md split into smaller files, have a main file describing Gulp's main dependencies making its API...?

**Comment by Romanx** [comment]
I'll take a look at those that aren't pulled in and make a PR

**Comment by phated** [comment]
Ref #1446

**Comment by phated** [comment]
The projects listed (and even more) have been incorporated into our API Docs rewrite so I'm going to close this.

Note: We brought them all in by hand so they'll have to be kept up-to-date manually.  That being said, most are controlled by us or don't change very often.
