### ISSUE TITLE
Gulp should have a --help argument

### ISSUE THREAD

**Issue by ghostsquad** [gulpjs/gulp#1288]
[This page](https://github.com/gulpjs/gulp/blob/master/docs/CLI.md) lists what you can do with gulp, why not have that displayed with
`gulp --help`
or
`gulp -h`?

**Comment by phated** [comment]
Already solved in gulp-cli

**Comment by ghostsquad** [comment]
Is gulp-cli not released?? 

```
$ gulp --help
[13:12:48] Using gulpfile C:\dev\test\gulpfile.js
[13:12:48] Starting 'watch'...
```

**Comment by phated** [comment]
Current released version of gulp-cli is just the code from this repo (master branch) but 1.0 will be out soon that supports 3.x/4.0 and will have the option.
