### ISSUE TITLE
Translate documentation for portuguese (PT-BR)

### ISSUE THREAD

**Issue by YanMagale** [gulpjs/gulp#1290]
Hello everyone.

I saw the tweet on translations of official Gulp Documentation.  I would make the translation into Portuguese (PT-BR).

I can participate in the work of translating the documentation?

As soon as I finish the translation, I send the PR.

**Comment by contra** [comment]
Yep, go for it!

**Comment by phated** [comment]
Closing this.  Send a PR when you have something.  Thanks.
