### ISSUE TITLE
How to suppress "task did not complete" messages?

### ISSUE THREAD

**Issue by fongandrew** [gulpjs/gulp#1293]
I occasionally run some long-running tasks that are, in fact, expected to take longer than 10 seconds (e.g. minimizing and zipping a project for production). In Gulp v4, this results in the warning message: "Task did not complete after 10s. Did you forget to signal async completion?"

Is there any option to suppress this message or extend the "did not complete" time from 10s to something longer?

**Comment by phated** [comment]
Please look at other issues before opening a new one.  This is especially frustrating because we are having a discussion about this over at #1268
