### ISSUE TITLE
[notice] semver abuse incoming

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1297]
I wanted to post a notice where the most people would see it, so I guess it will be here.

We are going to be bumping gulp-util's patch version to add support for the new gulplog functionality that was introduced in https://github.com/gulpjs/gulp-util/commit/65c210a35e1bf3557672b59862ac5a8cfc4eca54

This should allow for easier transition to gulp-cli 1.0 when it is released.

In the near future, we will also be releasing a patch version of gulp-util that adds deprecation warnings with upgrade suggestions to all APIs in gulp-util, as the whole package is going to be deprecated.

**Comment by phated** [comment]
gulp-util 3.0.7 was just publish which uses gulplog if available in the currently running environment (basically, if you are using the new CLI).

**Comment by ilanbiala** [comment]
@phated any update on this?

**Comment by phated** [comment]
gulp-util has been deprecated using traditional methods (`npm deprecate` command) - see https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 for more information

Ecosystem migration is being tracked in https://github.com/gulpjs/gulp-util/issues/143
