### ISSUE TITLE
vynil-fs 2.0 breaks gulp.dest

### ISSUE THREAD

**Issue by massa84** [gulpjs/gulp#1300]
The following code stopped working after vynil-fs has been updated to version 2.0 in the commit f3447dc91d9d6167f4b3aa10c1d45dc224f7f37a
the commit before this one is working as expected.

The issue is that not ALL the files are copied to the destination directories but only some of them.

The idea behind the following task is to copy a folder contents to the destination directory only if it doesn't exist in the destination or if source is newer than the existing one.
``` javascript
var gulp = require('gulp'),
    es   = require('event-stream'),
    path = require('path'),
    newer = require('gulp-newer'),
    gulpPrint = require('gulp-print'),
   settings = {
        source: {
            modules: 'node_modules/*'
        },
        destination: {
            modules: 'dest/node_modules'
        }
    };
function syncModules() {
    return gulp.src(settings.source.modules)
        .pipe(newer(settings.destination.modules))
        .pipe(gulpPrint(function(filepath) {
            return 'Module updated: ' + filepath;
        }))
        .pipe(copyFolderContents);
}

var copyFolderContents = es.map(function(data, cb) {
    if (data.isDirectory()) {
        var filepath = path.relative(process.cwd(), data.path);
        var pathToPass = filepath + '/**/*';
        var module = '/' + filepath.split('/')[1];
        gulp.src(pathToPass)
            .pipe(gulp.dest(settings.destination.modules + module));
    }
    cb(null, data);
});
gulp.task('default', syncModules);
```

**Comment by phated** [comment]
I can't debug this because you are using streams wrong.  You shouldn't be constructing a separate pipeline inside another pipeline, streams really only work when there is a single pipeline.   My gut feeling is that because there is no references to your nested pipeline, it is being garbage collected before your pipeline finishes.  Please update your usage of streams and see if that works.
