### ISSUE TITLE
gulp 4 release hold up?

### ISSUE THREAD

**Issue by nmccready** [gulpjs/gulp#1302]
Gulp 4 is amazing! It is way easier to reason about then the previous version of gulp! Our team has been using it consistently at least since March or April. Everything about it has been stable. 

So with that all said what is the main hold up for getting a release out? What bugs are the major outliers in the milestone? Can anything be pushed off for a patch? This would make many many user happy that have begged for a pre-release.

**Comment by phated** [comment]
Thanks for your interest and feedback.  We are very close to finishing up, especially now that the chokidar switch has been made.  We've actually made a lot of changes in the past few weeks and are waiting to get feedback on a few outstanding items and there are few important issues to get completed.

Outstanding issues:
1. Empty arrays - https://github.com/gulpjs/gulp/issues/1298
2. Deprecating gulp-util - https://github.com/gulpjs/gulp/issues/1297
3. Fix alias support - https://github.com/gulpjs/gulp/issues/1159
4. Migration guide - https://github.com/gulpjs/gulp/issues/861
5. Remaining documentation (not required in entirety) - https://github.com/gulpjs/gulp/labels/documentation

Hopefully you have some bandwidth to help us knock out the remaining few things.

**Comment by yairEO** [comment]
when will gulp v4 finally be released? weeks? months? 
are people on it 24/7 or is it maintained as a side-project?
I'm really curious, thanks!
