### ISSUE TITLE
invalid or emplty plural glob

### ISSUE THREAD

**Issue by salarmehr** [gulpjs/gulp#1306]
I think gulp should show a **warning** when there is no corresponding file for a plural pattern. It's rare that the developer specify a pattern without any corresponding files. A warning had no deleterious effect but can save huge debugging time. 

Also, currently gulp does not return **error** for invalid plural paths. 

~~~~~
var gulp = require('gulp');

gulp.task('test', function() {
	return gulp.src(['fakeDirectoy/*'])
		.pipe(gulp.dest('path'));
});

**Comment by phated** [comment]
@salarmehr there is a very in-depth conversation being had over this behavior in issue #1298 - could you please take a read through that thread and outline your thoughts on it?  I am trying to gather all use cases before we firm up the API.  Thanks.

Going to close this in favor of #1298
