### ISSUE TITLE
Gulp watch not picking up/compiling scss

### ISSUE THREAD

**Issue by govinder-rayt** [gulpjs/gulp#1307]
Hi guys,

I recently updated my Mac to El Capitan, however since doing so 'gulp watch' runs but doesn't pick-up/compile the changes I make to any .scss file?

Is there something I need to update to fix this?

Any help would be appreciated.

Cheers,

Gov

**Comment by contra** [comment]
Run `npm rebuild` and see if that corrects it

**Comment by phated** [comment]
Most likely a native addon problem. @contra's suggestion should work.
