### ISSUE TITLE
is gulp support cluster      let it more faster (gulp 怎么能支持多进程)

### ISSUE THREAD

**Issue by zhoujianlin8** [gulpjs/gulp#1308]
one process source is limit  （异步并发在单进程中受资源的限制同样比较慢）

**Comment by phated** [comment]
You can use the cluster module in your gulpfile, as it is just JavaScript.  There are no plans for core to fork the process.

**Comment by contra** [comment]
duplicate of https://github.com/gulpjs/gulp/issues/317
