### ISSUE TITLE
Gulp always runs the "default" task

### ISSUE THREAD

**Issue by fadilmamedov** [gulpjs/gulp#1310]
If we have ```gulpfile.js``` file with the next content:

    var gulp = require("gulp");
    gulp.task("test", []);

and run ```gulp test``` command, it shows ```Task default is not in your gulpfile``` error in console.

Lets try to add the "default" task to our ```gulpfile.js``` file:

    var gulp = require("gulp");
    gulp.task("test", []);
    gulp.task("default", []);

Then ```gulp test``` command runs the "default" task, although it must run the "test" task.

node version: v0.10.33
npm version: 1.4.28

**Comment by phated** [comment]
Unable to replicate on node 0.10.36 with gulp 3.9 installed

**Comment by fadilmamedov** [comment]
Sorry, the problem was in windows command line. It doesn't see additional command line arguments, which I passed to the gulp. The issue resolved. Thanks.
