### ISSUE TITLE
async vs sync tasks documentation is confusing

### ISSUE THREAD

**Issue by ghostsquad** [gulpjs/gulp#1320]
Async vs sync tasks is very confusing in documentation. 

first, it says:
> Async task support
> Tasks can be made asynchronous if its fn does one of the following: accepts callback, returns a stream, or returns a promise

Then is goes on to say:
> Note: By default, tasks run with maximum concurrency -- e.g. it launches all the tasks at once and waits for nothing. If you want to create a series where tasks run in a particular order, you need to do two things:
> 
> give it a hint to tell it when the task is done,
> and give it a hint that a task depends on completion of another.

Async support is default *IF* requirements are met? That's not really "default" if you have to meet some requirements.

Then, to run synchronously, you need to make the task "accept a callback hint", wait, isn't that how you make it Async?

```
// takes in a callback so the engine knows when it'll be done
gulp.task('one', function(cb) {
    // do stuff -- async or otherwise
    cb(err); // if err is not null and not undefined, the run will stop, and note that it failed
});
```

Wow, I'm confused....

**Comment by TrySound** [comment]
@ghostsquad If you add callback argument, gulp will waint until this callback will be called. Else it just ends task after calling. But recommend to use only async, caz in gulp4 sync behaviour removed.

**Comment by TrySound** [comment]
@ghostsquad Returning streams or promises is alternative for callback.

**Comment by phated** [comment]
If you would like to make changes to the documentation, please submit a PR.

**Comment by ghostsquad** [comment]
@phated - I'd love to submit a PR, but I don't know what I'd be changing, as I don't know what the correct behavior/instructions actually are.

@TrySound - sync removed in gulp4??! A dependency try is very useful for things like running unit tests (fast) and failing before integration tests are run. This is exactly what I'm doing in fact. How does one implement that in gulp4?

**Comment by TrySound** [comment]
@ghostsquad The only different is that you need to call `cb` after your sync operations.

**Comment by TrySound** [comment]
@ghostsquad Just say gulp when task should be finished.
