### ISSUE TITLE
Can't install it and why so so so many dependencies

### ISSUE THREAD

**Issue by pulkitnandan** [gulpjs/gulp#1326]
I'm trying to npm install gulp locally in project and this must be fetching something by making above 80,000 get requests. Why? and finally it fails. I was using gulp to build my project but gulp seems to build itself first so slowly that I just can't progress.

├─┬ bower@1.5.3
│ ├─┬ bower-registry-client@0.3.0
│ │ └─┬ request@2.51.0
│ │   └─┬ bl@0.9.4
│ │     └── readable-stream@1.0.33 
│ └─┬ request@2.53.0
│   └─┬ bl@0.9.4
│     └── readable-stream@1.0.33 
├─┬ gulp-clean@0.3.1
│ ├─┬ gulp-util@2.2.20
│ │ └─┬ through2@0.5.1
│ │   └── readable-stream@1.0.33 
│ └─┬ through2@0.4.2
│   └── readable-stream@1.0.33 
├─┬ gulp-concat-sourcemap@1.3.1
│ └─┬ gulp-util@2.2.20
│   └─┬ through2@0.5.1
│     └── readable-stream@1.0.33 
├─┬ gulp-filter@2.0.2
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-minify-html@1.0.4
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-notify@2.2.0
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-rev@3.0.1
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-rev-replace@0.4.2
│ ├─┬ gulp-util@2.2.20
│ │ └─┬ through2@0.5.1
│ │   └── readable-stream@1.0.33 
│ └─┬ through2@0.4.2
│   └── readable-stream@1.0.33 
├─┬ gulp-sass@2.0.4
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-tsd@0.0.4
│ ├─┬ gulp-jshint@1.6.4
│ │ └─┬ gulp-util@2.2.20
│ │   └─┬ through2@0.5.1
│ │     └── readable-stream@1.0.33 
│ ├─┬ through2@0.6.5 
│ │ └── readable-stream@1.0.33 
│ └─┬ tsd@0.6.5
│   └─┬ bl@0.9.4
│     └── readable-stream@1.0.33 
├─┬ gulp-typescript@2.6.0
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-uglify@1.0.2
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ gulp-usemin@0.3.14
│ └─┬ through2@0.5.1
│   └── readable-stream@1.0.33 
├─┬ gulp-useref@1.3.0
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.33 
├─┬ karma@0.13.10
│ ├─┬ chokidar@1.2.0
│ │ └─┬ fsevents@1.0.2
│ │   └─┬ node-pre-gyp@0.6.12
│ │     └─┬ tar-pack@2.0.0
│ │       └── readable-stream@1.0.33 
│ └─┬ log4js@0.6.27
│   └── readable-stream@1.0.33 
└─┬ karma-phantomjs-launcher@0.1.4
  └─┬ phantomjs@1.9.18
    └─┬ request@2.42.0
      └─┬ bl@0.9.4
        └── readable-stream@1.0.33 

npm WARN EPACKAGEJSON find-doctors-locations@1.0.0 No repository field.
npm verb stack Error: ENOENT: no such file or directory, chmod '/home/pulkitnandan/doctors-locations/node_modules/vinyl-fs/node_modules/strip-bom/cli.js'
npm verb stack     at Error (native)
npm verb cwd /home/pulkitnandan/doctors-locations
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp" "--save-dev" "--allow-root" "--verbose"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.4
npm ERR! path /home/pulkitnandan/doctors-locations/node_modules/vinyl-fs/node_modules/strip-bom/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pulkitnandan/doctors-locations/node_modules/vinyl-fs/node_modules/strip-bom/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm verb exit [ -2, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pulkitnandan/doctors-locations/npm-debug.log

**Comment by contra** [comment]
npm 3 has problems, use npm 2
