### ISSUE TITLE
Gulp exits zero if a promise is rejected with no value

### ISSUE THREAD

**Issue by ariporad** [gulpjs/gulp#1327]
Hi,

First, versions:

```bash
$ gulp -v
[21:05:26] CLI version 0.3.0
[21:05:26] Local version 3.9.0
```

After a bit of debugging, I've discovered that this code causes gulp to exit 1 (as it should):

```javascript
var gulp = require('gulp');

gulp.task('myTask', function () {
    return Promise.reject('Everything\'s Broken!');
});
```

Where as this causes it to exit 0, when it should exit 1:
```javascript
var gulp = require('gulp');

gulp.task('myTask', function () {
    return Promise.reject(); // No rejection value
});
```

I hope I'm not submitting a duplicate, I couldn't find one. Thanks!

**Comment by phated** [comment]
Can you test this with gulp 4.0 and see if it still happens?

**Comment by ariporad** [comment]
@phated: nope, it's fixed: [I just spent *_waaaaay_* too much time proving it](https://github.com/ariporad/gulp-test-exit-1-on-empty-rejected-promise).

Is there documentation on gulp 4, and how to upgrade to it?

**Comment by phated** [comment]
@ariporad all the documentation in the 4.0 branch should be updated.  We don't have a migration guide yet, as we are looking to the community to help out with that.  See: https://github.com/gulpjs/gulp/issues/861

I don't think we will be able to backport that change into the 3.x branch. Sorry.

**Comment by roymiloh** [comment]
I spend wayyyy much time accidentally "solving" it (passing an arbitrary string to reject method), then came here to see if anybody else encountered this bug, and found this issue - @phated, it could be _really_ helpful documenting it somewhere (as you said, it won't work in 3.x, ever).
