### ISSUE TITLE
Gulp 4: gulp.series repeats error log

### ISSUE THREAD

**Issue by aparajita** [gulpjs/gulp#1330]
When a task within `gulp.series` generates an error, the error is logged twice: once by the task that generated the error, and once by `gulp.series`. Is there some way to suppress this by default?

**Comment by phated** [comment]
Nope.  This is an artifact of us having to propagate any error that happens in the execution of the series but also logging the error when they occur (incase someone is using the `--continue` flag)

**Comment by aparajita** [comment]
In the current architecture, is it possible to turn off propagation when we know there is no need to?

**Comment by phated** [comment]
No

**Comment by adambuczynski** [comment]
This is actually quite bothersome. I have several nested tasks, in series and parallel, and some errors that I get are propagated and logged up to 4 or 5 times.

**Comment by aparajita** [comment]
@adambuczynski I agree. It's kind of useless to see the same error multiple times. There is no need for the series/parallel task to report an error, because by definition the actual task noticed the error and (hopefully) reported it.

**Comment by sttk** [comment]
The error object is taken over by upper tasks. 
So following example codes can suppress too much error logs, though I don't check over that there is no bad effect.

```js
(undertaker/lib/helpers/createExtensions.js)
function createExtensions(ee) {
  ...
  error: function(error, storage) {
    ...
    error.logged = true;
  }
};

(gulp-cli/lib/versioned/^4.0.0-alpha.1/log/events.js)
function logEvents(gulpInst) {
  ...
  gulpInst.on('error', function(e) {
    if (e.error.logged) { return; }
    ...
  });
}
```

**Comment by phated** [comment]
Implementation in latest referenced PR.

**Comment by aparajita** [comment]
@phated and @sttk  Wonderful, thank you! I knew it couldn't be that difficult.

**Comment by phated** [comment]
@aparajita yep, just need to take time to think through the correct and best implementation so we don't ship technical debt

**Comment by sttk** [comment]
@phated Yes, I don't like the solution in my post above, too.
If there is another better way, I hope to be adopted it.

However, in now-and-later (next and handler functions in map.js and mapSeries.js), all extension's error processes of upper tasks are called when an error caused.

And the error object is the only object which is shared among tasks.
If this issue need to be solved, the error object have to be used somehow.

**Comment by phated** [comment]
@sttk I've already committed a change better than the example you provided.  The only place this matters is in the CLI and the underlying libraries should not be changed in their behavior.

**Comment by sttk** [comment]
@phated OK. I didn't conceive any more solutions and I also think your implementation is better.
I agree with you.

**Comment by aparajita** [comment]
Shouldn't this be closed?

**Comment by phated** [comment]
@aparajita I'm still working on releasing gulp-cli version 1.1 - it will be closed after release.

**Comment by phated** [comment]
gulp-cli v1.1.0 has been published with this change.  You need to have the latest undertaker installed as a dependency of gulp to have everything working.
