### ISSUE TITLE
Gulp watch problem

### ISSUE THREAD

**Issue by TeodorKolev** [gulpjs/gulp#1333]
Gulp watch did not work for new added files. Can you give me just one reasonable reason why it don't? Just one

**Comment by TrySound** [comment]
@TeodorKolev It's gaze problem. New watcher in gulp4 works fine.

**Comment by TeodorKolev** [comment]
What is gaze and how can I fix that?

**Comment by TrySound** [comment]
@TeodorKolev Use can use [chokidar](https://github.com/paulmillr/chokidar) which is used by gulp4

**Comment by contra** [comment]
@TeodorKolev 

1. Please stop opening duplicate issues
    - Use the search bar at the top of the repository to find if a question has already been asked
2. Please don't be aggressive and pick fights - this is the THIRD issue you have opened where you are hostile in the initial post and every comment afterwards.

To answer your initial question: Upgrade to gulp 4.x - the watcher that 3.x used (http://npm.im/gaze) had a lot of problems: missing new files, excess CPU consumption, events not firing, etc.

@TrySound Thanks for helping out on the issues! Appreciate it 🌴

**Comment by TeodorKolev** [comment]
ok, can you tell me update command for gulp from 3 to 4. Thanks

**Comment by contra** [comment]
@TeodorKolev `npm install gulpjs/gulp#4.0` - make sure you read the new docs on the 4.0 branch, the task system API has changed substantially

**Comment by TeodorKolev** [comment]
Where can I find it? because I don't see it in website neither in here(github)

**Comment by contra** [comment]
@TeodorKolev There is a button at the top of the repo that says "master" - you can click that to switch repositories. Use the github documentation if you have any other questions about git.

**Comment by TeodorKolev** [comment]
I have found it 10x a lot for everithing
