### ISSUE TITLE
semver.js:281:TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by watership** [gulpjs/gulp#1334]
Node 4.1.2
gulp  3.9.0
Linux CentOS

/usr/lib/node_modules/gulp/node_modules/semver/semver.js:281
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer (/usr/lib/node_modules/gulp/node_modules/semver/semver.js:281:11)

![qq 20151019110218](https://cloud.githubusercontent.com/assets/2470422/10568908/ea972cd0-7650-11e5-92cf-74ef40ce4ab1.png)

**Comment by phated** [comment]
Your output is missing the result of the local gulp. This problem is always related to you not having a version of gulp installed locally.  Also, this is a duplicate issue with long threads explaining such. Please search before reporting.
