### ISSUE TITLE
npm install hang

### ISSUE THREAD

**Issue by petecarapetyan** [gulpjs/gulp#1340]
I am getting a hang on 'npm install gulp' last couple days. I have tried multiple linuxes, multiple versions of npm, with and without --no-dim-links. Google search is full of npm hang search results, but I can get other npm installs to work fine, so I am guessing (only guessing) that it might or might not be something about gulp npm registry entry??? Since I am a js newbie and thus don't know what I am talking about please feel free to flame me here, otherwise I am dead in the water as polymer won't run without an initial gulp install.

**Comment by phated** [comment]
Email the npm support team.
