### ISSUE TITLE
Timeout per task

### ISSUE THREAD

**Issue by leebenson** [gulpjs/gulp#1343]
Don't hate me @phated :-) I know this has been asked before, but I didn't see a resolution.

I'm getting a zillion warnings about `Task did not complete after 10s. Did you forget to signal async completion?` after a string of tasks. I think this should be settable per-task, something like mocha's `this.timeout(0)` option per test (if it's already available, I couldn't find anything in the docs)

My build flow does a lot of heavy lifting. Several tasks last several minutes.

`--timeout 0` is useful, but then it cancels timing for _all_ tasks. There are plenty of tasks I expect to finish in 10s, and also plenty I don't care about the timing. It'd be nice not to have to blanket-bomb the warning, but rather "unset" it per task.

I know you're hesitant of increasing the API surface area, but it's too opinionated to assume a task is gonna complete in 10s. All those `chalk.red` warnings in my logs scream 'error'.

**Comment by Romanx** [comment]
This has been changed recently so timeout does not exist. Please see issue #1268 for the details but update your gulp instance to the newest

**Comment by leebenson** [comment]
Thanks @Romanx 

I read #1268 but I don't a resolution. What's the official advice for a task that takes > 10s? Just put up with the warning?

**Comment by leebenson** [comment]
got the latest version and the warning is gone. thx @Romanx.

**Comment by phated** [comment]
Just to follow up. The newest version uses an event that node emits when it is exiting so we will only show the warnings if something is actually awry vs us just thinking it might be. I also changed the message to  no longer mention a duration so that's how you can tell it's an old version.

**Comment by leebenson** [comment]
Works brilliantly @phated. Good result.
