### ISSUE TITLE
Any way to run pre-task work?

### ISSUE THREAD

**Issue by atrauzzi** [gulpjs/gulp#1344]
I'm putting together a collection of gulp scripts that will contain tasks for triggering various scaffolding and build scripts (in both node and non-node languages).

One thing that I would like to do is have the script check to make sure that it is being run in a directory with a configuration file before executing any other tasks.

I've pulled inquirer so that I can do prompting in the event that the configuration file is missing, but unfortunately it seems like gulp terminates the current invocation before inquirer has any chance of capturing input.  Is this an issue, or am I doing something wrong in terms of how I'm structuring things?

**Comment by callumacrae** [comment]
Just put it in your gulpfile.js outside of a task. Would that work, or am I misunderstanding the question?

**Comment by atrauzzi** [comment]
@callumacrae The issue is that when I call inquirer, it is asynchronous, so gulp immediately goes to attempting to run a task.  It's almost like I need to block before gulp gets going on things.

**Comment by callumacrae** [comment]
```js
var gulp = require('gulp');

if (true) {
  process.exit(0);
}

gulp.task('default', function () {
  // This won't run
});
```

**Comment by atrauzzi** [comment]
The structure you're implying there isn't quite right.  It's more like:

    var gulp = require('gulp');
    var inquirer = require('inquirer');
    
    var callback1 = function () {
        // This never gets run because the task has terminated before input is captured.
    }

    var callback2 = function() {
        // This ends up getting run.
    }

    inquirer.prompt(..., callback1);

    gulp.task('default', callback2);

**Comment by atrauzzi** [comment]
Aha!  So looking into the internals, it appears as though I can poke at the guts of orchestrator to get what I'm after without hurting things:

    gulp.on('start', (e) => {
    	if(!project && gulp.seq.indexOf('initialize') < 0) {
    		gulp.seq = ['initialize'];
    	}
    });

And of course, I'm aware that in this approach I've overwritten `gulp.seq` and should probably store it somewhere in case I want to resume the originally requested task.  But even this is good enough to get started with for my use case! :)

**Comment by phated** [comment]
@atrauzzi glad you found a workaround but be aware that this will break in gulp 4

**Comment by atrauzzi** [comment]
@phated - I'd be interested in coming up with a similar solution and trying out Gulp 4.  Any suggestions on where I'd look?
