### ISSUE TITLE
About the future

### ISSUE THREAD

**Issue by kuraga** [gulpjs/gulp#1346]
Good day!

First, is v4 release coming?

Second, the main change of v4 is "replaced 3.x task system (orchestrator) with new task system (bach)". But are there some plans about the real future (maybe for v5)? ECMAScript 7, async/await, generators, etc?

Thanks! :smile:

**Comment by contra** [comment]
@kuraga FYI we already support all of that stuff - anything that works in node works just fine in gulp, and you can use babel for anything that node core hasn't implemented yet

**Comment by kuraga** [comment]
@contra I'm talking about using these features in gulp (or bach, maybe) mechanisms...
Question is influenced by https://medium.com/swlh/you-might-not-need-gulp-js-89a0220487dd

**Comment by kuraga** [comment]
So, Gulp is callback-oriented now. Might it be promises/generators/async-await/etc. oriented?

**Comment by callumacrae** [comment]
It also works with promises and streams, not just callbacks

**Comment by phated** [comment]
The async types we support for task completion:
* node-style streams 
* callbacks
* promises
* node's child processes
* Observables (rxjs, etc) 

I thought a lot about adding generators but the iteration case didn't seem like a good fit and it would have added a huge amount of code. That being said, you can still use that stuff in your gulpfile, we just don't use it to watch for task completion.

**Comment by kuraga** [comment]
Thanks!
