### ISSUE TITLE
Ignoring OS specific files, i.e. files like .DS_Store

### ISSUE THREAD

**Issue by Nejat** [gulpjs/gulp#1352]
when using the `{ dot : true; }` with `gulp.src` it would be great to have an easy way to ignore os specific hidden files such as mac's `.DS_Store` files

currently I achieve this with the following negation `'!**/.DS_Store'`, but it's less than ideal as it adds platform specific definitions to packages otherwise used on different operating systems

**Comment by phated** [comment]
We hand globs directly off to the node-glob library.  I doubt they plan to support something like this.
