### ISSUE TITLE
Remove gulp-shell from blacklist

### ISSUE THREAD

**Issue by sbussard** [gulpjs/gulp#1353]
Please remove `gulp-shell` from the blacklist. 

from blacklist.json
```
"gulp-shell": "duplicate of gulp-exec",
```

The reason stated is not true, as `gulp-exec` lacks feature parity with `gulp-shell`.
There are more forks and stars for `gulp-shell` on github vs. those numbers for `gulp-exec`.
To me, `gulp-shell` is also much more intuitive than `gulp-exec`.

**Comment by callumacrae** [comment]
From the gulp-shell docs:

> ```
gulp.task('shorthand', shell.task([
  'echo hello',
  'echo world'
]))
```

vs this from the gulp-exec docs:

> Note: If you just want to run a command, just run the command, don't use this plugin:

That alone seems reason to prefer gulp-exec to gulp-shell: gulp-shell are promoting a massive anti-pattern.

The entire reason gulp-shell was created is so it could be used in a way that shouldn't be in a gulp plugin: https://github.com/sun-zheng-an/gulp-shell/issues/1#issuecomment-35830848

**Comment by contra** [comment]
Yeah, gulp-shell is promoting huge anti-patterns. I've opened an issue about this and it was closed with no resolution.

**Comment by callumacrae** [comment]
The issue, for reference: https://github.com/sun-zheng-an/gulp-shell/issues/55

**Comment by phated** [comment]
Yeah, @callumacrae. Let's get that in a different PR

**Comment by Sayvai** [comment]
I'm using gulp-shell because no matter how hard i try, I am was unable to **finish** a gulp task (i.e. return  out stream) when successfully executing a shell command through `child_process.spawn`.

Below is sample code I am referring to above:

```
var spawn = require('child_process').spawn;

gulp.task('test', function (cb) {
    var ls = spawn('karma', ['start', 'karma.conf.js'], {stdio: 'inherit'});

    ls.on('close', function (code) {
        console.log('child process exited with code ' + code);
    });
});
```

**Would you know how i could finish the above task?** It would be great, just so that i do not have to rely on gulp-shell?.

**Comment by TrySound** [comment]
@Sayvai Call `cb` on close

**Comment by Sayvai** [comment]
@TrySound - Your solution above worked. Genius! Thank you.
