### ISSUE TITLE
gulp 4 src/dest not emitting `end` event when number of files >16

### ISSUE THREAD

**Issue by MadLittleMods** [gulpjs/gulp#1356]
Using latest from repo: `gulpjs/gulp#4.0`

If I try to move more than 16 files using `gulp.src` and `gulp.dest` it seems to never emit the `end` event. It works just fine with less files and turning off the the through pipe(for debugging) has no effect.

You can download a copy of the [test case here](https://files.gitter.im/gulpjs/gulp/6TvJ/gulp4-src-dest-never-end-test1.zip).

Note: There are 20 files in the `src/stuff` and everything gets moved just fine to `dist/stuff`.

```js
gulp.task('task-test1', function() {
	var stream = gulp.src(['./src/stuff/**/*'])
		.pipe(gulp.dest('./dist/stuff'))
		/* */
		.pipe(through.obj(function(chunk, enc, cb) {
			// noop
			console.log(chunk.path);
			cb(null, chunk);
		}, function(cb) {
			console.log('test1 stream flush');
			// "call callback when the flush operation is complete."
			cb();
		}));
		/* */


	stream.on('end', function() {
		console.log('stream ended');
	});
	stream.on('close', function() {
		console.log('stream closed');
	});
	stream.on('drain', function() {
		console.log('stream drained');
	});


	return new Promise(function(resolve, reject) {
			setTimeout(function() {
				resolve();
			}, 10000)
		});
});
```

The output from that script is (note there are 20 files in the `src/stuff` directory). Only 16 are shown in the console output:

```
gulp4-src-dest-never-end-test1/dist/stuff/dummy1
gulp4-src-dest-never-end-test1/dist/stuff/dummy10
gulp4-src-dest-never-end-test1/dist/stuff/dummy11
gulp4-src-dest-never-end-test1/dist/stuff/dummy12
gulp4-src-dest-never-end-test1/dist/stuff/dummy13
gulp4-src-dest-never-end-test1/dist/stuff/dummy14
gulp4-src-dest-never-end-test1/dist/stuff/dummy15
gulp4-src-dest-never-end-test1/dist/stuff/dummy16
gulp4-src-dest-never-end-test1/dist/stuff/dummy17
gulp4-src-dest-never-end-test1/dist/stuff/dummy18
gulp4-src-dest-never-end-test1/dist/stuff/dummy19
gulp4-src-dest-never-end-test1/dist/stuff/dummy2
gulp4-src-dest-never-end-test1/dist/stuff/dummy20
gulp4-src-dest-never-end-test1/dist/stuff/dummy3
gulp4-src-dest-never-end-test1/dist/stuff/dummy4
gulp4-src-dest-never-end-test1/dist/stuff/dummy5
```

---

Increasing the timeout on the 10sec return promise has no effect.

If you return the `stream` to use it as the async end signal, the task does finish and the console is as expected: listed 20 files, shows `'test1 stream flush` and `'stream ended'`

I thought the 16 number may correspond with CPU cores but I have an i7 with 4 cores (8 logical cores)

**Comment by phated** [comment]
You aren't draining the stream and hitting the highWatermark. Return your stream instead of a promise.

**Comment by MadLittleMods** [comment]
@phated This is just a simple example but my actual use case is looping over and creating multiple src/dest streams, turning them into a promise(listen to `end`), and return a `Promisify.all(streams)`.

How should this be achieved instead?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow. You don't need promises to handle your use case, just need to do some more research on working with streams.

**Comment by MadLittleMods** [comment]
I would like to use promises over something like [`require('event-stream').merge`](https://www.npmjs.com/package/event-stream#merge-stream1-streamn-or-merge-streamarray).

Using [`stream-exhaust`](https://www.npmjs.com/package/stream-exhaust) as you [recommended here](https://github.com/gulpjs/gulp/issues/707#issuecomment-63425331) seems to be working great.

Sorry for asking what seems to be a fundamental part of streams with the `highWatermark`, back pressure, and draining. It has been a totally transparent part to me up until now even though I have done non-returning streams before, I probably never hit the `highWatermark`.
