### ISSUE TITLE
Does gulp.series() wait for all its inner called events to finish to log the end of the task?

### ISSUE THREAD

**Issue by marcofugaro** [gulpjs/gulp#1357]
One problem I encountered using [run-sequence](https://github.com/OverZealous/run-sequence), the gulp 3 alternative of gulp.series, is that it was a hell dealing with subtasks and tasks that are required to run in sequence.

The solution I found was not to use subtasks at all. For example I had to use
 
    gulp.task('browsersync', function() { runSequence('clean', ['styles:dev', 'scripts:dev', 'fonts'], 'watch', 'browsersyncinit'); }); 

instead of 

    gulp.task('browsersync', function() { runSequence('dev', 'browsersyncinit'); }); 

or simply

    gulp.task('browsersync', ['dev'], function() { 
        ...
    });

to keep my code DRY.

The problem is due to the subtask, in this case `'dev'`, to starting all of its inner tasks and finishing before the inner tasks are completed, triggering the next task in sequence, in this case  `'browsersync'`, which basically starts watching some files, and after that the tast  `'clean'` is executed, and errors occour.

This is what I want it to do:

![Console Image](http://i.imgur.com/8nw8dXg.png)

and this is what I would for my code to look like in gulp 4.0
```
gulp.task('browsersync', gulp.series('dev', function() {
    ...
}));

gulp.task('build', gulp.series('clean', gulp.parallel('styles', 'scripts', 'fonts'))); 
gulp.task('build:dev', gulp.series('clean', gulp.parallel('styles:dev', 'scripts:dev', 'fonts'))); 
gulp.task('dev', gulp.series('build:dev', 'watch')); 
gulp.task('default', ['build']);
```

Will this work? I basically need all the subtasks and subsubtasks of `'dev'` to be completed before `'browsersync'` is called.
Do you have any suggestions?

**Comment by phated** [comment]
Yes that will work except the default task isn't specified correctly (array syntax is completely removed).  Also, support questions should be directed to StackOverflow.  Thank you.
