### ISSUE TITLE
Copy single directory and contents

### ISSUE THREAD

**Issue by webchaz** [gulpjs/gulp#1358]
I'm trying to copy one directories contents and then another directory with its contents, for example:

```
gulp.src(['src/**/*', 'node_modules/**/*']).pipe(gulp.dest('dist'));
```

This copies all of the `node_modules` to the dist directory, but not within the `node_modules` directory.  How can I have it include the directory as well?

**Comment by lancedikson** [comment]
@webchaz, try to use this one:

```
gulp.src(['src/**/*', 'node_modules/**/*'], {base: '.'}).pipe(gulp.dest('dist'));
```

**Comment by webchaz** [comment]
So this one copies node_modules correctly, but it also copies the 'src' folder.  For 'src', I just want to copy the contents, not the folder.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  However, you just want to change your node_modules glob to `node_modules/**` so it doesn't glob files.

**Comment by Supportic** [comment]
Just in case someone revisits such a problem. It worked for me to put an asterisks infront of the folder you want to keep instead of using the `base` attribute.
```js
// will copy the assets folder and its sub directories + files to the destination
dir.src.path + 'assets*/**/*'
// will only copy the sub directories + files of the assets folder to the destination
dir.src.path + 'assets/**/*'
```
