### ISSUE TITLE
Browserify sourcemaps contains only the sourcemap of the bundle and not the browserified files

### ISSUE THREAD

**Issue by inf3rno** [gulpjs/gulp#1362]
By the recipe: https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md the sourcemap contains the bundle and not the source files, so it is harder to debug. In firebug the line and col was not translated to the bundle.  In firefox console the sourcemaps are not working as far as I can tell.

**Comment by phated** [comment]
If you get this to work, please submit a PR with the changes needed.

**Comment by callumacrae** [comment]
That approach works for me.

**Comment by inf3rno** [comment]
@callumacrae Can you copy the code here? I have something like this:
```js
var browserify = require("browserify"),
    source = require("vinyl-source-stream"),
    buffer = require("vinyl-buffer"),
    uglify = require("gulp-uglify"),
    gulp = require("gulp"),
    globby = require("globby"),
    sourcemaps = require("gulp-sourcemaps");

module.exports = function () {
    return browserify({
        entries: globby.sync(["index.js", "src/**/*.js"])
    })
        .bundle()
        .pipe(source("bundle.js"))
        .pipe(buffer())
        .pipe(sourcemaps.init({
            loadMaps: true
        }))
        .pipe(uglify())
        .pipe(sourcemaps.write("./"))
        .pipe(gulp.dest("dist"));
};
```
I want to debug the files in the src/*, but I got only the browserify bundle (before uglify) in firebug and I got the line number of the uglified version, so always line 1. It does not work in the console of firefox and chrome. It's a surprise, but in the msie console it works better, it shows the actual line of the browserify bundle, but still not the src files. In opera it works the same way.

**Comment by callumacrae** [comment]
set `debug: true` in your browserify options, that enabled sourcemaps
