### ISSUE TITLE
Gulp uses vinyl-fs version 0.3.14?

### ISSUE THREAD

**Issue by partap** [gulpjs/gulp#1363]
I was looking for a way to use the current file basename string in a concatenation...

I found gulp-concat-util, which executes a template with `file` as a local.  Looks like a vinyl file object...so far so good.  I can access `file.path`, but I want to use the filename as an object index...so I looked up the docs and found `file.stem`.  Perfect. Just need to do something like:
```
concat = require('gulp-concat-util')
...
gulp.task('templates', function() {
  gulp.src('assets/javascripts/templates/*.js')
    .pipe(concat.header("templates['<%= file.stem %>'] = "))
    .pipe(concat('templates.js'))
    .pipe(gulp.dest('public/javascripts'))
});
```

Except it doesn't work...inspecting the object I see `file.base` and `file.path`, but no `file.basename`, `file.extname` or `file.stem`.  So now I'm wondering if the documentation matches the version I'm using.
Looked at the package.json and see that gulp has dep for vinyl-fs version `^0.3.0`, and it loads 0.3.14, but `npm info vinyl-fs` shows that the latest version is 2.2.1...

Is there a reason for gulp staying at the pre-1.0 version of vinyl?  

It was a quick fix to patch the file object using gulp-tap in this case, but annoying that I had to spend the time to figure out that I needed to.

ps.  Just started with gulp today...loving it so far!  Converting a project from mimosa, and this is the first problem that I've run into.  Mimosa does a weird thing with jade templates...compiles them all into a single js file, and a lot of code already depends on this behavior.

**Comment by phated** [comment]
Sorry about that. Vinyl has tons of breaking changes so we can't update in the 3.x branch. Once 4.0 is finished, it will ship with the latest version.
