### ISSUE TITLE
Common error interface

### ISSUE THREAD

**Issue by sergeybekrin** [gulpjs/gulp#1365]
For now, most of plugins throws custom error object with completely different properties, which makes error normalization kinda hard.

Can we implement some basic error type (like GulpError, wich extends Error), so all plugins could implement it for better visual and semantic output?

**Comment by contra** [comment]
We already have this with https://github.com/gulpjs/gulp-util#new-pluginerrorpluginname-message-options. If you find a plugin that isn't using the PluginError class (or BetterError) then open a ticket and ask them to do so.
