### ISSUE TITLE
Babel 6.0 and gulpfile.babel.js

### ISSUE THREAD

**Issue by prabinv** [gulpjs/gulp#1366]
Upgrading to Babel 6.0 seems not to recognize the ES 2015 syntax written in the `gulpfile.babel.js`. I'm running node 0.12. Do I need to `npm install` any package? Or will it work only on node > 4.0?

**Comment by KapuzenSohn** [comment]
Maybe issue #1364 will help you

**Comment by prabinv** [comment]
Great.. I'll try that out. Thanks @KapuzenSohn
