### ISSUE TITLE
gulp.watch() for exported file stream

### ISSUE THREAD

**Issue by daviestar** [gulpjs/gulp#1367]
Hello,

I am working with an external program (http://esotericsoftware.com) which exports JSON.  Using `gulp.watch()`, I am using Gulp to manipulate the exported JSON.  However, the external program writes the file as a stream, causing `gulp.watch()` to be called too early and fail.

From the developer of Spine: "Spine streams to the file. It creates/recreates it and writes data to the file multiple times, then closes it."

My question on SO: http://stackoverflow.com/questions/33398558/gulp-task-failing-only-with-gulp-watch

Is there a way to deal with this type of file modification?

**Comment by phated** [comment]
Thanks for opening your support question on StackOverflow.  You might need to debounce your watch function.
