### ISSUE TITLE
Setting file stat per stream in gulp.dest

### ISSUE THREAD

**Issue by jedd-ahyoung** [gulpjs/gulp#1368]
I have tasks that sometimes take files that are marked read-only (TFS checkout policies) and produce output to a destination folder.

If the source files are readonly, the dest files will be read-only as well.

I know that `gulp.dest` takes a second option argument with a "mode" parameter. However, in the API docs, this seems to only affect the directory itself as it is created. vinyl-fs seems to do something different, though.

Does `gulp.dest` use vinyl-fs under the hood? How might I set destination file permissions through gulp.dest?

**Comment by contra** [comment]
@jedd-ahyoung This ticket is interesting and might be better if opened on the vinyl-fs repo - I think we need a more generic set of options in dest for setting stuff on stat

**Comment by phated** [comment]
If the vinyl object has stat set, we just use what is there.  I think this sort of stuff needs to continue to be deferred to a transform stream that you put before your `dest` stream.
