### ISSUE TITLE
conditionally run a task before others...

### ISSUE THREAD

**Issue by tracker1** [gulpjs/gulp#1369]
Okay, this may seem like a relatively silly thing, but lets say I have the following tasks...

* `js`
* `css`
* `clean` - deletes the `dist/` oath
* `build` - should depend on `clean` then run `js` and `css`

My actual use case is a bit more complicated, but needless to say, when running `build`, `clean` should finish before `js` and `css` start.  `clean` throws an error because the other two start putting output in the `dist/` path before `clean` has finished running.  I do not want, and should not have to configure `js` and `css` to depend on `clean`.

**Comment by contra** [comment]
In gulp 4:

`gulp.task('do-stuff', gulp.series('clean', gulp.parallel('js', 'css')))`

**Comment by tracker1** [comment]
@contra thanks
