### ISSUE TITLE
Adding stream to existing stream

### ISSUE THREAD

**Issue by btrepp** [gulpjs/gulp#1371]
Hi there,

I'm trying to use use grunt-rev to fingerprint my assets. I'm trying to use lazy pipe too to create a more re-usable stream function.

```
gulp.task('build', function(){
    return gulp.src('app/**/*.js')
               .pipe(processJavascript())
               .pipe(gulp.dest('wwwroot'));
});

processJavascript = (function(){
    var pipeline = lazypipe()
        .pipe(concat,'app.js')
        .pipe(rev)
//TODO deal with this 
//        .pipe(es.merge, rev.manifest({merge:true}));

    return lazypipe()
        .pipe(function(){return gulpif("**/*.js",pipeline())});
})();
```

What I'm after here is concating all my javascript into one file, applying a fingerprint, then adding the grunt-rev manifest to the output stream. So I would expect the output of the stream to write app.js.56748546 and rev-manifest.json out the the wwwroot folder.

I plan to use the manifest to do replacements on files at the end. I'd prefer to keep the whole thing as a 'stream'. It appears heaps of gulp plugins just punt on the stream thing, as the examples I see have people writing out the manifest in a seperate gulp.dest line.

Is there any way to add the manifest into the pipeline?. Or is there a better fingerprinting plugin that would allow me to deal with things in a more stream-y way?.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  You may want to look at pumpify or https://www.npmjs.com/package/mississippi for stream utilities that may help you achieve this.
