### ISSUE TITLE
Gulp 4 doesn't update mtime causing gulp-changed and gulp-newer to fail

### ISSUE THREAD

**Issue by noderat** [gulpjs/gulp#1373]
I've discovered that mtime is not correctly updated while testing the imagemin-mozjpeg module in the gulp 4.0 branch, gulp 3.9 works correctly.

[Example repo which fails to skip the image only when gulp is upgraded to 4.0](https://github.com/noderat/imagemin-mozjpeg-mtime)

Related issue from imagemin-mozjpeg repo: imagemin/imagemin-mozjpeg#6

I suspect this may occur with more than just imagemin-mozjpeg, however.

**Comment by phated** [comment]
This seems to be related to https://github.com/gulpjs/vinyl-fs/issues/124 which we have fixed in the master branch but not released yet (still some more problems to sort out).  Could you try using the master branch of vinyl-fs in your dependency tree to see if your problem is solved?

**Comment by noderat** [comment]
Awesome, that resolved the issue completely!
