### ISSUE TITLE
gulpfile.babel.js will not opt in for any es6 features with babel 6.x

### ISSUE THREAD

**Issue by montemishkin** [gulpjs/gulp#1375]
In babel 6.x the default behavior is now such that babel does nothing.  In other words, you must opt in to any es6 features you want to use.  See [here](https://babeljs.io/docs/plugins/).

Since gulp allows for es6 features to be used in a gulpfile by requiring gulpfiles named `gulpfile.babel.js` through the `babel-core/register`, and the register now defaults to not having any features enabled, this means that a project using babel 6.x is unable to take advantage of es6 features in its gulpfile through the usual trick of renaming it `gulpfile.babel.js`.

**Comment by phated** [comment]
Babel (and every other transpiler) has always been deferred to userland.  All we do is intelligently look up the transpiler registration methods based on filenames.  If you are going to use babel 6, just make a babelrc file and put your plugins in there.  This was a strange decision made by the babel team and there's nothing we can do.
