### ISSUE TITLE
Error when writing a file.

### ISSUE THREAD

**Issue by ounos** [gulpjs/gulp#1376]
gulp gives me a hard time.
I get error: Error: EPERM, utime.

I am not the owner of the file, but i am in the same group. File permissions 777.
sudo will do the trick, but I can't use it. 

gulp version: 4.0
(I had a similar chmod error using gulp 3.x)

**Comment by phated** [comment]
It seems that the utimes call requires you to be an owner (as per http://man7.org/linux/man-pages/man2/utimes.2.html) but I thought that gulp.dest always creates the file with the current user as the owner.  I'm going to close this here and open it on the vinyl-fs repo.

**Comment by phated** [comment]
Issue created at https://github.com/gulpjs/vinyl-fs/issues/127

**Comment by phated** [comment]
This has finally been fixed by gulpjs/vinyl-fs#151 and published as 2.3.2 - Please update to the latest version for the fixes.

As per the new [`.dest()` documentation](https://github.com/gulpjs/vinyl-fs#destfolder-options):

> Once the file is written to disk, an attempt is made to determine if the stat.mode, stat.mtime and stat.atime of the vinyl File object differ from the file on the filesystem. If they differ and the running process owns the file, the corresponding filesystem metadata is updated. If they don't differ or the process doesn't own the file, the attempt is skipped silently. This functionality is disabled on Windows operating systems or any other OS that doesn't support process.getuid or process.geteuid in node. This is due to Windows having very unexpected results through usage of fs.fchmod and fs.futimes.
