### ISSUE TITLE
Gulp 4: invoke task on gulp context

### ISSUE THREAD

**Issue by amobiz** [gulpjs/gulp#1377]
I can do this in Gulp 3.X:
```
'use strict';
module.exports = function () {
   var gulp = this;
   // do gulp things...
};
```
This is convenient to modularize tasks.

But not in Gulp 4.0:
```
'use strict';
module.exports = function () {
   var gulp = this;  // undefined
};
```
Wouldn't it be nice if tasks be invoked on gulp context for backward compatibility reason?

**Comment by phated** [comment]
No, we won't be doing this in core.  That was a terrible implementation detail from the orchestrator library.  If you want to do something like that, it can be done in a Custom Registry similar to https://github.com/gulpjs/undertaker-task-metadata

**Comment by amobiz** [comment]
OK, I see. Thanks for quick response.

**Comment by amobiz** [comment]
FYI. Just in case anyone looking for this.

[bind all functions on the gulp instance to allow destructuring](https://github.com/gulpjs/gulp/commit/73eced0969af4d1e87cea1d7172f90b557b8f7b5)
