### ISSUE TITLE
An error when installing gulp!

### ISSUE THREAD

**Issue by NikSays** [gulpjs/gulp#1378]
admin@niksays-A780L-M2L:/media/admin/Files/Tea$ sudo npm install --save-dev gulp
npm ERR! Error: EPERM, symlink '../user-home/cli.js'
npm ERR!  { [Error: EPERM, symlink '../user-home/cli.js'] errno: 50, code: 'EPERM', path: '../user-home/cli.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.2.0-17-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "gulp"
npm ERR! cwd /media/admin/Files/Tea
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path ../user-home/cli.js
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, symlink '../user-home/cli.js'
npm ERR! tar.unpack untar error /home/admin/.npm/semver/4.3.6/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/media/admin/Files/Tea/node_modules/gulp/node_modules/vinyl-fs/node_modules/mkdirp/node_modules/minimist'
npm ERR! error rolling back  vinyl-fs@0.3.14 { [Error: ENOTEMPTY, rmdir '/media/admin/Files/Tea/node_modules/gulp/node_modules/vinyl-fs/node_modules/mkdirp/node_modules/minimist']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/media/admin/Files/Tea/node_modules/gulp/node_modules/vinyl-fs/node_modules/mkdirp/node_modules/minimist' }
npm ERR! tar.unpack untar error /home/admin/.npm/readable-stream/1.0.33/package.tgz
npm ERR! tar.unpack untar error /home/admin/.npm/glob/4.5.3/package.tgz
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! tar.unpack untar error /home/admin/.npm/minimatch/2.0.10/package.tgz
npm ERR! tar.unpack untar error /home/admin/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /media/admin/Files/Tea/npm-debug.log
npm ERR! not ok code 0

**Comment by robrich** [comment]
Try sudo. If that doesn't work, `npm cache clear` then try it again.

**Comment by NikSays** [comment]
Result isn't changes. 
*google translate*

**Comment by phated** [comment]
This isn't the npm issue tracker. Post there.
