### ISSUE TITLE
Use gulpfile.babel.js without global gulp install

### ISSUE THREAD

**Issue by eatonphil** [gulpjs/gulp#1379]
Is it possible to use a babel gulpfile without a global gulp? I was not able to do so on FreeBSD 10.2. I got an "import" syntax error both when I ran "./node_modules/.bin/gulp" and "./node_modules/.bin/babel-node ./node_modules/.bin/gulp". I then installed gulp globally, removed the local node_modules, reinstalled the dependencies, and "gulp" ran correctly. What do I have to do to avoid having this global gulp installation?

**Comment by phated** [comment]
Yes, we do this all the time.  By naming you file `gulpfile.babel.js`, the CLI (whether running locally or globally) knows to look for `babel-core/register` or `babel/register` in your local node_modules directory and attempt to require it before running the gulpfile.  If you are using babel 6, you need to research the breaking changes that cause you to create a .babelrc file also.
