### ISSUE TITLE
you dependency example only has 1 dependent task

### ISSUE THREAD

**Issue by chovy** [gulpjs/gulp#1383]
How do I ensure more than one task depends on a task to finish before starting?

for example:

```
gulp.task('build', ['clean', 'validate', 'js', 'css'], function(){
});
```

This does not work. `clean` needs to run before the other 3. In actuality it creates a race condition where the files are trying to build into `./dist` before they are done being cleaned.

**Comment by phated** [comment]
you put clean as the dependency of every other task.  Gulp 4 solves this with a `.series` method.
