### ISSUE TITLE
 sass自动生成css，为什么只有保存app.scss主文件才能生成css, 保存其它sass文件就不能自动生成css

### ISSUE THREAD

**Issue by huangtubiao** [gulpjs/gulp#1384]
var styles = lazypipe()
    .pipe($.sass, {
        outputStyle: 'expanded',
        precision: 10
    })
    .pipe($.autoprefixer, 'last 1 version')
    .pipe(gulp.dest, '.tmp/styles');

///////////
// Tasks //
///////////

gulp.task('styles', function() {
    return gulp.src(paths.styles)
        .pipe(styles());
});

**Comment by callumacrae** [comment]
?
