### ISSUE TITLE
Gulp 4: What needs to happen for 4.0.0?

### ISSUE THREAD

**Issue by ide** [gulpjs/gulp#1386]
Gulp 4 seems to generally have been received well by early adopters and I like it a lot more than Gulp 3 after having converted a half dozen gulpfiles without much trouble.

My thinking is that publishing Gulp 4.0.0 would let the core team and contributors focus on 4.x (see https://github.com/gulpjs/gulp/pull/1262 which went into master and might need to be cherry picked over to 4.x). If gulp-cli now can support Gulp 3 and 4, people who want to stay on Gulp 3 could get the new CLI and explicitly install gulp@3 in their package.json files.

So I mostly want to know what pending work is blocking Gulp 4 and can't be deferred by the gulp@3 escape hatch. If there were clear tasks that people could work on it might be enough to push Gulp forward enough to get 4.0.0 out. There are over 17k stars after all...

**Comment by phated** [comment]
We've recently had some problems with vinyl-fs so we need to wrap that up.  The 1.0 release of gulp-cli should be happening this week.  There's always work to do and we have thoroughly labelled issues that you can attempt to tackle.

**Comment by ide** [comment]
The issue tracker is clean but I'm wondering which issues are blocking Gulp 4.0.0 specifically. Are all the issues labeled gulp-4 (https://github.com/gulpjs/gulp/milestones/gulp%204) blockers or a subset of them? Telling people: "we can publish Gulp 4 after these specific issues are closed" helps clarifies priorities in particular.

**Comment by phated** [comment]
The very top of the list has 4 issues that people using 4.0 have encountered.  They weren't added to the milestone (they are now) but those are obvious problems that will need to be decided on and solved before a 4.0 release, as their resolution could cause breaking changes.  Again, the vinyl-fs repo has other outstanding issues, as well as the undertaker repo.

**Comment by ide** [comment]
Thanks for the clarifications =)

**Comment by atilkan** [comment]
2 more years have passed.
