### ISSUE TITLE
The file has changed after gulp compiled, but i didn't edit it before gulp compiled. why ???

### ISSUE THREAD

**Issue by MeicaiRose** [gulpjs/gulp#1389]
the built file has changed with:
![screenshot from 2015-11-13 16 42 44](https://cloud.githubusercontent.com/assets/7079384/11142063/a63d17fa-8a25-11e5-81f7-8913ac48a83f.png)
![screenshot from 2015-11-13 16 43 50](https://cloud.githubusercontent.com/assets/7079384/11142074/bea1d43e-8a25-11e5-9c0e-8e4295f098c3.png)

after that,there is something wrong in chrome browser with:
![screenshot from 2015-11-13 16 46 37](https://cloud.githubusercontent.com/assets/7079384/11142141/23329960-8a26-11e5-9e25-bee6a23d9fb8.png)

i get so confused.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  This has nothing to do with gulp and has something to do with your pipeline (userland plugins).

**Comment by MeicaiRose** [comment]
ok, i got it. maybe the wrong is made by react js.
