### ISSUE TITLE
Documenting gulp.task arguments

### ISSUE THREAD

**Issue by jacopotarantino** [gulpjs/gulp#1396]
Could someone please explain the callback fed to `gulp.task`? I'm not sure if it's supposed to take arguments, what it's supposed to do, or if gulp depends on my plugin/function listening for this callback function to invoke a/sync responses. I was looking at stackoverflow as well as https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulptaskname-deps-fn and couldn't find a sufficient explanation of this information.

**Comment by kevdez** [comment]
The callback can be whatever you want it to be, whether you want to accept arguments or not. Usually the callback consists of what you want that gulp task to do, after it's done with the array of dependency tasks (if any).

I noticed that the documentation for gulp.task() is a little off from the rest of the API documentation. I'll fix that.

**Comment by jacopotarantino** [comment]
@kevdez thanks! Undocumented function arguments can be really confusing.

**Comment by phated** [comment]
Closed by #1429
