### ISSUE TITLE
gulp.watch writing variable number asterisk(*) signs instead of code changes

### ISSUE THREAD

**Issue by dejan7** [gulpjs/gulp#1400]
I'm running a gulp task that concatenates few JS files. It works great when i run it once. But the issue is when i include gulp.watch: Whenever i save a watched file It writes a variable number of asteriks in my output file in places where changes were supposed to be and i get JS "ILLEGAL TOKEN" error. If i manually delete the output file and then create it again (either by re-running the gulp task or by simply saving a watched file) the result is generated properly. 

I'm running gulp in laravel's homestead (virtual machine). 
Gulp version is 3.9.0

This is my gulpfile.js

    var gulp  = require('gulp'),
        gutil = require('gulp-util'),
        concat = require('gulp-concat'),
        uglify = require('gulp-uglify');
    
    
    gulp.task('mix-jquery', function() {
        return gulp.src([ 'jquery_deps/*.js']).pipe(concat('frontend.js')).pipe(gulp.dest('./public/'));
    });
    
    gulp.task('mix-angular', function() {
        return gulp.src([
            'bower_components/angular/angular.min.js',
            'bower_components/angular-ui-router/release/angular-ui-router.min.js',
            'bower_components/ng-dialog/js/ngDialog.min.js',
            'main.js',
            'controllers/*.js'
        ]).pipe(concat('app.js')).pipe(gulp.dest('./public/'));
    });
    
    gulp.task('default', ['mix-jquery', 'mix-angular'], function() {
        return gutil.log('all done!')
    });
    
    var watcher = gulp.watch(['main.js', 'controllers/*.js'], ['default']);
    
    watcher.on('change', function(event) {
        console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');
    });

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
