### ISSUE TITLE
How to use gulpfile.babel.js is undocumented

### ISSUE THREAD

**Issue by shadowmint** [gulpjs/gulp#1401]
I realize this isn't a commonly used feature, but this functionality seems to have no documentation for it *anywhere* outside of this issue tracker.

Upgrading packages just resulted in complete breakage of my gulp workflow due to https://github.com/gulpjs/gulp/issues/1364

Please consider adding an article to https://github.com/gulpjs/gulp/tree/master/docs/recipes that documents that need for a `.babelrc` file, and broadly speaking, how to use es6 gulpfiles in general.

**Comment by callumacrae** [comment]
It's documented here: https://github.com/gulpjs/gulp/blob/master/docs/CLI.md#compilers

But yeah, that could be clearer. I'll look to add a recipe (or if you want to contribute one, feel free!).

It's worth noting that there's not much a documentation improvement with gulp could have done about the Babel 6 update.


I've also written an article about it on my website: http://macr.ae/article/gulp-and-babel.html

**Comment by phated** [comment]
It's not our responsibility to document other libraries you might be including in your project.

**Comment by shadowmint** [comment]
@phated This is a core feature of gulp. Either don't support it, or document it.
