### ISSUE TITLE
[Question] invoke a task programatically and watch completion

### ISSUE THREAD

**Issue by rolandjitsu** [gulpjs/gulp#1402]
I have some tasks like the following:
```js
gulp.task('build', gulp.parallel(
	'deps',
	'serve/static',
	'build/js',
	'serve/html',
	'build/css'
));

gulp.task('build:!ilbsr', function build () {
	return new Promise((resolve) => {
		WebSocketServer.isRunning(BUILD_SERVER_ADDRESS).then(() => resolve(), () => {
			console.log();
			gulp.task('build')();
		});
	});
});
```
And it seems ok, the only issue is that I do not know when the task is actually done, because the `gulp.task('build')();` returns nothing. Is there actually a way of invoking a task within another task and somehow check when it is completed?

**Comment by phated** [comment]
Pass a function to your invocation.  We do something similar at https://github.com/gulpjs/gulp-cli/blob/master/lib/versioned/%5E4.0.0/index.js#L66-L70

**Comment by rolandjitsu** [comment]
@phated thanks.
