### ISSUE TITLE
[Feature Request] Automatically run self contained tasks

### ISSUE THREAD

**Issue by oleersoy** [gulpjs/gulp#1404]
Hi,

I have built a 'self contained' [superfly-css-task-build](https://github.com/superfly-css/superfly-css-task-build) gulp task.

All that is needed to run it in the `gulpfile.js` is:

``` js
require('superfly-css-task-build');
```
It would be great if, upon typing `gulp build:css`, gulp could detect the task in `node_modules` and just run it without me having to create the `gulpfile.js` file.  Not sure if gulp should support this...but I figured I'd float the idea.

Cheers,
Ole

**Comment by phated** [comment]
This is something that can and should be done in userland.
