### ISSUE TITLE
Reporting task times out to an external system?

### ISSUE THREAD

**Issue by beenanner** [gulpjs/gulp#1405]
Is there a way to grab the times reported at the end of a task in gulp4 and use them in another command. For instance run a series/parallel task and grab the time it took for each part and send them to some reporting DB for analysis?

My crazy idea would be something like this :-)

var combinedTask = gulp.parallel(task1,task2);

combinedTask.on('end', function(tasksTimes) {
     //access to some json object of times for task1, task2, total time of combinedTask. 
});

**Comment by phated** [comment]
You can listen to internal events for this but we aren't going to document them because they might change.  You can see usage of this at https://github.com/gulpjs/gulp-cli/blob/master/lib/versioned/%5E4.0.0/log/events.js

**Comment by beenanner** [comment]
Thanks @phated exactly what I was looking for. :-)
