### ISSUE TITLE
watching multiple files

### ISSUE THREAD

**Issue by httpNick** [gulpjs/gulp#1407]
I was using this gist for my gulpfile: https://gist.github.com/httpNick/708219f5002b6a9dc578

It works great for ES6 babelfiy-ing, but I would like to watch all files within my ./public/js folder and output the built versions to a build folder. Is there a way to modify this gulpfile to watch all js files within the folder?

Thanks ahead of time, I appreciate the gulp community I have seen so far.

**Comment by phated** [comment]
Please direct support questions to StackOverflow.
