### ISSUE TITLE
The last modified date is from source, not build time

### ISSUE THREAD

**Issue by sprynm** [gulpjs/gulp#1414]
My compiled files have a last modified date of the source file (.less) instead of the last time they were built. This makes it hard to see what files have updated recently since the main build files rarely change compared to the imports.

Is this typical and where might I look into control this?

Basics of the build:

             return gulp.src(src)
                .pipe($.chmod(755))
                .pipe($.if( flatten, $.flatten() ) )
                .pipe($.less(LESSConfig) )
                .pipe($.injectString.append('\n /* Created: ' + datestamp + ' */ '))
                .pipe(gulp.dest(dest))
                .pipe($.if( deploy, gulp.dest( path.join( paths.deploy, dest ) ) ) )
                .pipe($.debug( {title: msg}))

    Env{
      Windows: 10,
      Node: 5.1,
      npm: 3.4.1,
      Gulp : 4.0.0-alpha.2,
      devDependencies: {
        dateformat: ^1.0.12,
        gulp: gulpjs/gulp#4.0,
        gulp-chmod: ^1.3.0,
        gulp-cleancss: ^0.2.2,
        gulp-debug: ^2.1.2,
        gulp-flatten: ^0.2.0,
        gulp-if: ^2.0.0,
        gulp-inject-string: ^1.0.0,
        gulp-less: ^3.0.5,
        gulp-less-watcher: ^0.5.0,
        gulp-load-plugins: ^1.1.0,
        gulp-mq-remove: 0.0.2,
        gulp-notify: ^2.2.0,
        gulp-plumber: 1.0.1,
        gulp-rename: ^1.2.2,
        less-plugin-autoprefix: ^1.5.1,
        less-plugin-clean-css: ^1.5.1,
        less-plugin-group-css-media-queries: ^1.0.1,
        yargs: ^3.29.0
      }
    }

**Comment by phated** [comment]
This is a known bug we are working to fix.  It is being fully discussed at https://github.com/gulpjs/vinyl-fs/pull/128
