### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by Adedeji92** [gulpjs/gulp#1415]
Please Help me with the correction of this problem
![capture](https://cloud.githubusercontent.com/assets/8332170/11437379/8e365496-94ed-11e5-8f8e-e54dd159987c.PNG)

**Comment by TrySound** [comment]
@Adedeji92 Show your code. We can't know what it the problem with nothing.

**Comment by TrySound** [comment]
Also try to remove node_modules folder and run `npm install`

**Comment by phated** [comment]
Support questions should be directed to StackOverflow
