### ISSUE TITLE
Production flag breaks application

### ISSUE THREAD

**Issue by taviroquai** [gulpjs/gulp#1416]
Hi,

I'm new to gulp.

I'm trying to moving my project to use bower + gulp. My project is based on Laravel and AngularJS.

The following is my gulpfile.js

var elixir = require('laravel-elixir');

elixir(function(mix) {
    mix.scripts([
        '../bower/jquery/dist/jquery.js',
        '../../../public/assets/js/bootstrap.min.js',
        '../../../public/assets/js/proj4.js',
        '../../../public/assets/js/ol.js',
        '../../../public/assets/js/angular.min.js',
        '../../../public/assets/js/ngMap.js',
        '../../../public/assets/js/ngIdiom.js',
        '../../../public/assets/js/ngFeatureInfo.js',
        '../../../public/assets/js/ngLayerSwitcher.js',
        '../../../public/assets/js/ngSearchResults.js',
        '../../../public/assets/js/ngNavigationToolbar.js'
    ], 'public/assets/js/app.js');
});

You can look at the code at
https://github.com/taviroquai/mapigniter2/tree/master/public/assets/js

Now, if I run just gulp, everything works fine.

If I run gulp with production flag, it breaks my application with angularjs error:
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=ngMap&p1=Error%3A%2…%2F%2Flocalhost%2Fmapigniter2%2Fpublic%2Fassets%2Fjs%2Fapp.js%3A22%3A17333)

It seems that the compression somehow breaks the code.

I'm new to javascript builds so please explain slowly. Thanks :)

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
