### ISSUE TITLE
Feature Request Of Doom: A Task Interface for Object literals?

### ISSUE THREAD

**Issue by objectkit** [gulpjs/gulp#1417]
Its great that the #task method in Gulp 4 uses [Function#name or #displayName](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#name) to infer the
name of tasks passed by function

````
function doSomething () {}

gulp.task(doSomething)
gulp.task("default", gulp.series("doSomething"))

````

I'd like to also request the introduction of a Task interface so that objects passed
to gulp#task can also be supplied to the method. This is inspired by the oft forgotten [W3C EventListener interface](https://developer.mozilla.org/en-US/docs/Web/API/EventListener) in the context of DOM (I know- not Gulp!) that I rarely see used, but I do find useful. 

A Task could possibly look like this:

````
// Pseudo IDL - I know - this is not a WIDL context!
interface Task
    readonly attribute String? taskName;
    readonly attribute String? description:
    Object execute (in Object callback, in String name);
````
If an object is supplied to gulp#task that implements the Task#execute method, the task name could be inferred possibly by choosing between the following:

- The Task constructors Function#name
- The Task constructors Function#displayName (to support current implementation?)
- The task instances #taskName

A possible impl for a task called Clean could be
````
function Clean () {}
Clean.prototype.execute = function (callback, taskName) {
    return del["path", callback]
}

task(new Clean())
gulp.task("default", gulp.series("Clean")) // yep - this example has an uppercase name for better or worse
````
Or another could be
````
var someTask = {
        taskName: "clean",
        description: "cleaning...",
        execute: function (callback, taskName) {
            return del["path", callback]
        }
    }
task.add(someTask) // taskName is "clean"
gulp.task("default", gulp.series("clean"))
````
In terms of DOM, entirely different case I know, _but for example_, this is generally absolutely
fine:
````
// via function
dispatcher.addEventListener("qwerty", function (event){
    // whatever - but execution context is the dispatcher
})
// via object literal implementing EventListener's #handleEvent
var listener = {
    events: []
    recordEvent: (event) {
        this.events.push(event)
    }
    handleEvent: (event) {
        // whatever - but execution context is the object!
        this.recordEvent(event)
    }
dispatcher.addEventListener("qwerty", listener);
````
The reason I used that example above is that I think perhaps an object context for a task that maintains the execution context of that task object, could have its uses? I don't think this is in the vein of gulp at the moment, but I think it could be useful subject to some refinement... Just putting that out there!

update: Added omitted [#description](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#fndescription) property

**Comment by callumacrae** [comment]
But why?

**Comment by objectkit** [comment]
Well, to forward the case _against_ why a Task object is a bad idea, to my eyes, Gulp is implemented in a reliably modern edition of ECMAScript, and makes use of the capabilities of that edition, which is very useful considering the complicated history of the language. The fact that it strongly supports the Functional Programming paradigm is also great as that will support so many use cases, with complexity deferred to plugin authors, and simplicity to Gulpfile writers. I pick my plugins, do minimal integration work, and use Gulp to do the hem work, creating a seamless simple manageable output is a real deal for me. And for short scripts, this is absolutely fine.

Outside of that, I can guess three scenarios, all falsifiable, as to why a partial supplementary OOP approach that would use an object to define a task to be valuable. I can use JavaScript fine, but I chose CoffeeScript here as just found it easier to write the examples with, and I;m currently working on transpilation and compression tasks. ES6 could possibly work here too...

The first regards use case of *transpiled Gulpfiles*. Personally, for my crimes against brackets, I have recently taken to using CoffeeScript to write Gulpfile scripts which I do find to be useful for brevities sake, but as a long time ECMAScript user, sometimes a pain to be frank. Unfortunately, CoffeeScript does not export named functions, so the present convenience of named functions as task descriptor names is lost. This may also be true in the case of using transpiled Gulpfiles for other variants produced by TypeScript or Babel (but I'm not sure, and even if I was, if anyone would use them to define a Gulpfile), but as tasks can be still be defined ``gulp.task("name", func)``, there is no loss. I would however find it convenient to write a Task object that works independently of ``Function#name`` or ``Function#displayName`` similar to the proposal above.

The second scenario regards *complexity management* of potential Gulpfile complexity. For large scripts, or scripts with possibly complexity, I imagine there are cases where a partial switch from the FP paradigm to the OOP paradigm, or a variation thereof, would make sense. In a hurry, I may have three or four attempts of trying to simplify a task, perhaps using different plugins to drive the goal I'm writing the tasks for.  Using a single point of entry via the proposed ``execute`` method would present the opportunity for me to temporarily manage this with one object, rather than various functions scattered in the global scope. A daft overly formal redundant example of a different case could possibly be:

````
# require here
class ProjectBuild # somehow extends a mysterious TaskContext

    # note this does not use the taskName attribute
    # @see the #init method for how task names could possibly be managed

    input: null
    output:
    coffeeOptions:
        bare: no

    uglifyOptions:
        mangle: yes

    constructor: (@input, output = "./build/") ->

    init: (gulp) ->
        gulp.task "transpile", @
        gulp.task "compress", @
        # antipattern, but for example
        gulp.task "default", gulp.serial "transpile", "compress"

    execute: (callback, taskName) ->
        switch taskName
            case "transpile" then @executeTranspile callback
            case "compress" then @executeCompress callback
            else throw new ReferenceError # or more tasks here

    executeTranspile: (callback) ->
        gulp.src @srcDirectory
            .pipe coffee @coffeeOptions
            .pipe gulp.dest @output

    executeCompress: (callback) ->
        gulp.src @srcDirectory
            .pipe uglify @uglifyOptions
                .on "error", (thrown) =>
                    @handleUgligyError thrown
            .pipe gulp.dest @output

    handleUgligyError: (thrown) ->
        # console, grunt, whomever, perhaps nothing? who knows

# at bottom of script
build = new ProjectBuild "./src/coffee/main/**/*.coffee",
build.init gulp
````
While that _example is entirely redundant for already available alternatives_, it is supposed to show potential starting points for a Gulpfile that could really grow in complexity. For example, one could have a task objective managed by a single object, compression, but potentially implement delegate methods within execute so that different strategies could be explored e.g. with different options, variables, run orders etc. One could either keep each task with its own variables defined in an object context that could be useful.

The last scenario I can think of is to _reduce the need for global variable management_. Using the FP paradigm with a lot of plugins referencing global variables in tasks (or within closures to manage that if there was a need) can add a lot of noise to a script. If one _could_ reference tasks defined in external files, and those tasks would have their own requires and variables, Gulpfile could require them, and gulp wiring could and setup alone could take place in the Gulpfile. Each task could have its own object level variables, thereby reducing the need for sprawling global variable lists in the Gulpfile.

````
# many requires later, then local tasks
CompressionTask = require "./gulp/CompresstionTask"
TranspilationTask = require "./gulp/TranspilationTask"

gulp.task new CompressionTask # taskName property would be read by gulp
gulp.task new TranspilationTask # same as above
gulp.task "default", gulp.serial CompressionTask::taskName, TranspilationTask::taskName
````

Adding in a few more language build tools and processors, and this could scale up well (or become a disaster of its own making), yet Gulpfile would all be about Gulp - a single point of reference (if done correctly by the writer) that does not become a God File as it references external objects created (or borrowed) by the writer, each of which can have its own versioning independently of Gulpfile.

Sometimes OOP kills simplicity and FP pronounces it, and sometimes vice versa. IMO Gulp should remain FP geared, but not prevent partial OOP with a Task object. I just thought a potential route for OOP (formal or informal) could possibly be useful.

Well, thats the best playground I could come up with quickly. I'm sure there are many better ones, and less complex use cases too.

If the means to provide this is for the Gulp implementation to support task objects in the API informally, but not have to take responsiblity for any adventures or misadventures with them... why not? I'm undecided myself, but I am obviously leaning towards thinking it could be a good idea, or a safely indifferent idea...

**Comment by contra** [comment]
I actually did this as an experiment, can't remember if I ever finished it: https://github.com/contra/gasp

**Comment by contra** [comment]
Feel free to contribute, but this will be a layer on top of gulp and not a part of core so this issue should probably be elsewhere ✌

**Comment by objectkit** [comment]
@contra Happy out to see that a non-invasive decorative layer is totally possible on top of Gulp while keeping Gulp core FP - proper order - no blocker - closed is good with me :)
