### ISSUE TITLE
Should try babel-core/register first, then babel/register

### ISSUE THREAD

**Issue by silvenon** [gulpjs/gulp#1419]
From [Setting up Babel 6](http://babeljs.io/blog/2015/10/31/setting-up-babel-6/):

> The `babel` package is no more. Previously, it was the entire compiler and all the transforms plus a bunch of CLI tools, but this lead to unnecessarily large downloads and was a bit confusing. Now we’ve split it up into two separate packages: `babel-cli` and `babel-core`.

**Comment by callumacrae** [comment]
Where is it recommended to use babel?

**Comment by phated** [comment]
We do that already. Update your installation.

**Comment by silvenon** [comment]
Both local and global versions are latest.

```
[11:43:24] Failed to load external module babel-register
[11:43:24] Requiring external module babel-core/register
[11:43:24] CLI version 1.0.0
[11:43:24] Local version 3.9.0
```

But now that I look at it, I see that you're first loading babel-register (not babel/register), I have no idea what that is, so I'll shut up.

**Comment by callumacrae** [comment]
It's babel-core/register: https://github.com/babel/babel/blob/master/packages/babel-core/register.js

**Comment by teohhanhui** [comment]
`babel-register` should be supported once #1456 has been released.

**Comment by duereg** [comment]
babel-core/register is already out of date. Babel is recommending you use `babel-register` package moving forward.

**Comment by callumacrae** [comment]
@duereg: Read the PR linked in the comment above yours and check out interpret: https://github.com/js-cli/js-interpret
