### ISSUE TITLE
package dependency problem when install Gulp globally

### ISSUE THREAD

**Issue by Tibicenas** [gulpjs/gulp#1420]
Got this message, what i have to do ?
```
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
````

**Comment by phated** [comment]
Nothing, it will install fine. That is just a warning.

**Comment by Tibicenas** [comment]
It's up to them update that dependency then ?

**Comment by mlms13** [comment]
Just a heads up for anyone else looking for this issue, it seems to be coming from `node-globule`, which gulp indirectly depends on. It [has been reported to them](https://github.com/cowboy/node-globule/issues/21).
