### ISSUE TITLE
Allow promise containing stream

### ISSUE THREAD

**Issue by OliverJAsh** [gulpjs/gulp#1421]
`gulp.task` allows you to pass in a function returning a promise or a stream.

Could it allow a promise containing a stream? The task should wait until the stream inside of the promise has completed.

**Comment by phated** [comment]
Nope. We don't look at results of anything.

**Comment by OliverJAsh** [comment]
The problem I'm trying to solve is I need to perform some async action before I can define my gulp tasks, which is why my stream is currently inside of a promise.

Can you think of a way of doing this?

``` js
promise().then(x => (
  gulp.task('foo', gulp.src(x))
));
```

**Comment by OliverJAsh** [comment]
I'm currently doing something like this as a workaround:

``` js
gulp.task('build', () => {
    const promise = x;

    promise.then(fileName => {
        return new Promise(resolve => {
            gulp.src(fileName)
                .pipe(rev())
                .pipe(gulp.dest('./public'))
                .on('end', resolve);
        });
    });
});
```

**Comment by zxqfox** [comment]
I believe we should reopen this since async functions comes to our lives:
```js
gulp.task('build', () => async function() {
  var config = await readConfig();
  return gulp.src(config.somePath).pipe(...); // will return a stream
}); // ... but wrapped to promise because of async
```
... so we must rewrite it to:
```js
var toArray = require('stream-to-array');
gulp.task('build', () => async function() {
  var config = await readConfig();
  return toArray(gulp.src(config.somePath).pipe(...)); // ... and it's weird
});
```

Even with simple Promises it's quitely strange to force users resolve streams manually.

Also would be nice to have support for generators to reduce syntactic noise, since they are supported out of the box in Node4.x+:
```js
gulp.task('build', () => co(function*() {
  yield toArray( // Need it to convert stream to promise because co returns a promise with a stream
    gulp.src('./from/*').pipe(gulp.dest('./to'))
  );
}));
```

**Comment by phated** [comment]
@zxqfox this is out of scope

**Comment by zxqfox** [comment]
@phated That's sad because it means you forcing users to write their own helpers (their own gulp-pieces) to wait streams inside promises, whlie gulp were made for it. Thanks for an answer.

**Comment by tadatuta** [comment]
@zxqfox :+1:

**Comment by SwinX** [comment]
@zxqfox :+1:

**Comment by blond** [comment]
@zxqfox 👍

**Comment by phated** [comment]
Hey everyone, github added reactions so your +1s are just noise. I'm locking this.
