### ISSUE TITLE
Gulp 3.9.0 gulp.watch does not detect when new file is added

### ISSUE THREAD

**Issue by dragonflypl** [gulpjs/gulp#1422]
I have an gulp client side build set up. Some steps are css/js/html minification/concatenation and etc. Standard stuff. I'm using gulp 3.9.0. The issue I'm struggling with is that ```gulp.watch``` does not pick up new files (changed/deleted events are triggering my callback, but added is not raised):

<pre><code>watchThis(
            "./src/main/client/app/agent/accounts/**/*.html",
            "app",
            "-markup");

        function watchThis(paths, key, suffix) {
            gulpUtil.log('Watching ' + gulpUtil.colors.cyan(paths + " as " + key + suffix));

            gulp.watch(paths, function(event) {
                gulpUtil.log("File event: " + gulpUtil.colors.cyan(path.basename(event.path) + ' ' + event.type));
                gulp.start(key + suffix);
            }).on('error', function(error) {
                gulpUtil.log(error);
            });
        }
</code>
</pre>

I don't want to use ```gulp-watch``` plugin as I just dropped it - I had some other issues with it including it was too slow on large projects + it sometimes was hunging. ```gulp.watch``` it lightning fast and robust so far, but the only issue is that it does not detect when files are added.

How can I fix it?

**Comment by TrySound** [comment]
@dragonflypl No way. It's gaze. gulp-watch uses chokidar which is used by gulp4. The problem is only on windows. U can decide it with usePolling option. [See more here](https://github.com/paulmillr/chokidar)

**Comment by dragonflypl** [comment]
Ok, so basically i should use wire up second pooling watch with chokidar's usePooling to detect new files?

**Comment by contra** [comment]
Yeah, gulp.watch in 3.9 was a pile of burning trash and had a ton of issues. We fixed this in 4.x by switching from gaze -> chokidar which solves this case. `npm install gulpjs/gulp#4.0` will solve this

**Comment by dragonflypl** [comment]
What is the status of gulp 4 ? Is it in beta / stable enough to use in projects?
