### ISSUE TITLE
Gulp 4: when not returning a promise, tasks get halted immediately and no warning or error is shown

### ISSUE THREAD

**Issue by adambuczynski** [gulpjs/gulp#1423]
Today I was struggling to figure out what was going on with my tasks. I had a couple of functions that were being run in series, but after I added another task I noticed some of them were no longer being executed and gulp was just quitting without any error or warning. It was not even showing a "finished series" message.

After some digging, I realized my new task was missing a `return` statement. So since this task had no return value, Gulp just decided to quit the whole flow.

I think the handling of cases like this should be improved a little, and Gulp should probably throw a warning of some sort to let the user know what's happening. Just quitting without a message and without running subsequent tasks is rather confusing.

**Comment by phated** [comment]
With an updated CLI, you will receive a "Tasks not completed" warning.

**Comment by adambuczynski** [comment]
Excellent, update gulp-cli and tested, works very well.
