### ISSUE TITLE
[gulp 4] globs symlinks incorrectly

### ISSUE THREAD

**Issue by meowlab** [gulpjs/gulp#1427]
You can download sample OSX apps here, after download, decompress it:
https://github.com/atom/electron/releases/download/v0.35.2/electron-v0.35.2-darwin-x64.zip

Here is the test case:
```javascript
var gulp = require('gulp')

gulp.task('test', () => {
	gulp.src('electron-v0.35.2-darwin-x64/**/*')
		.pipe(gulp.dest('electron-2/'))
})
```
Copy anything from `electron-v0.35.2-darwin-x64` to `electron-2` is excepted.

But when running, you will see error like this:
```javascript
[19:56:46] Starting 'test'...
[19:56:46] Finished 'test' after 7.32 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

I believe this is caused by some empty folders in Electron.app/, is this a bug or gulp definitely not support it?  Thanks!

**Comment by contra** [comment]
Which version of gulp?

**Comment by meowlab** [comment]
```shell
> gulp -v
[14:19:51] CLI version 3.9.0
[14:19:51] Local version 3.9.0
```

**Comment by contra** [comment]
Can you try this with 4.0 and see if it still happens?

**Comment by meowlab** [comment]
Nope... It still damage the OS X app I mentioned above, and console says:

```shell
> gulp test
[18:34:08] Using gulpfile ~/test/gulpfile.js
[18:34:08] Starting 'test'...
[18:34:08] The following tasks did not complete: test
[18:34:08] Did you forget to signal async completion?
```

I didn't change anything in my gulpfile.js, I believe it is 4.0 compatible.

Anything I missed? Thanks

**Comment by Romanx** [comment]
Hey,

If your task is still:
```js
var gulp = require('gulp')

gulp.task('test', () => {
    gulp.src('electron-v0.35.2-darwin-x64/**/*')
        .pipe(gulp.dest('electron-2/'))
})
```

change it to:
```js
var gulp = require('gulp')

gulp.task('test', () => {
    return gulp.src('electron-v0.35.2-darwin-x64/**/*')
        .pipe(gulp.dest('electron-2/'))
})
```

Returning a pipe, promise or using the callback signals the async completion of the task

**Comment by meowlab** [comment]
@Romanx Thanks for the tip, the console stop complain but the OSX app copied still damaged
Any ideas?

**Comment by Romanx** [comment]
Unfortunately not, glad i fixed your task error but maybe @contra could be more help now it's working.

**Comment by meowlab** [comment]
@contra Upgrade to 4.0 cause more issue than 3.9
There are 4 files under `electron-v0.35.2-darwin-x64`(source folder) and in gulp 3.9, after copy, destination folder has 4 files, it is correct.
In gulp 4.0, after copy, there are 13 items in destination folder, some of them should be in `Electron.app`, could you reproduce this?

**Comment by phated** [comment]
Just looked into this and it seems to be a problem with symlinks.  Setting `{ followSymlinks: false }` gets us a bit closer but we seem have a problem with symlinked directories containing files.  I'll need to look into that more later.

```
gulp.task('test', function(){
    return gulp.src('electron-v0.35.2-darwin-x64/**/*', { followSymlinks: false })
        .pipe(gulp.dest('electron-2/'))
})
```

**Comment by phated** [comment]
It seems we have a partial fix in a PR over at the vinyl-fs repo (linked above).  It doesn't generate symlinks but would generate all the files; would that work for your use case or are the symlinks a must?

**Comment by phated** [comment]
I just published vinyl-fs version 2.4.3 so this should be fixed in gulp 4 with fully updated dependencies.  Closing.

**Comment by konstantinblaesi** [comment]
I just tested this and gulp  4.0.0 indeed doesn't have this issue anymore. However I noticed that `npm install gulp` or `npm install gulp@latest` will still install 3.9.1. You need to explicitly `npm install gulp@4.0.0` ...

**Comment by phated** [comment]
@konstantinblaesi Nice. You can find the reasoning for 3.9.1 by default at https://medium.com/gulpjs/gulp4-interview-with-blaine-bublitz-d94bfaa7dc78
