### ISSUE TITLE
Rev up vinyl-fs

### ISSUE THREAD

**Issue by sparty02** [gulpjs/gulp#1428]
Currently the ```vinyl-fs``` dep is really outdated at ```"vinyl-fs": "^0.3.0"```, while the current release version is ```vinyl-fs@2.2.1```.  Any concerns with updating?

**Comment by TrySound** [comment]
@sparty02 https://github.com/gulpjs/gulp/issues/1363#issuecomment-152702047

**Comment by contra** [comment]
3.x is locked except for major bug fixes, use 4.0

**Comment by sparty02** [comment]
Thanks @TrySound , I didn't see that other issue because it was closed!
