### ISSUE TITLE
gulp.watch emitting 'deleted' event only once (first time)

### ISSUE THREAD

**Issue by designabyss** [gulpjs/gulp#1430]
**Gulp Version 3.9.0**

Here's the watch call
```javascript
var watcher = gulp.watch(base.app+'**/*', ['default'])
```
and on change
```javascript
    watcher.on('change', function(evt){
        console.log(path.relative('./',evt.path) + ' | type: '+evt.type)

        if(evt.type==='deleted'){
            del(path.relative('./', evt.path)
                .replace(base.app.replace('./',''),base.dist.replace('./',''))
                .replace('src','assets'))
        }
    })
```

and default task
``` javascript
gulp.task('default', ['sass', 'html', 'images']
```

I am testing it by renaming an image in 'app' directory and it does get detected by watch *the first time* but not afterwards. However event of type *changed* does emit regardless (by actions such as editing an html file).

I need the images to be exactly in sync.

**Comment by contra** [comment]
Use 4.0 - the watcher in 3.x has a myriad of issues so we switched to a different library
