### ISSUE TITLE
Documentation for browserify regarding entries isn't clear

### ISSUE THREAD

**Issue by KingScooty** [gulpjs/gulp#1434]
Referring to the documentation here: https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md

I'm finding the lack of comments regarding entries and source confusing. What's the relationship between - `entries: './entry.js',` and `.pipe(source('app.js'))`?

I've written the task below, but my scripts are outputting to `./.temp/assets/js/app/assets/_js/main.js`. 
How do i collapse that path to just the root of the `gulp.dest`? The desired output is `./.temp/assets/js/main.js`

```javascript
gulp.task('js-development', function() {
  var b = browserify({
    entries: './app/assets/_js/main.js',
    debug: true
  });

  return b.bundle()
    .pipe(source('./app/assets/_js/main.js'))
    .pipe(buffer())
    .pipe(plugins.sourcemaps.init({loadMaps: true}))
      .on('error', plugins.util.log)
    .pipe(plugins.sourcemaps.write('./'))
    .pipe(gulp.dest('.temp/development/assets/js/'));
});
```

**Comment by contra** [comment]
`entries` is an option you give to browserify that tells it what file to read, the argument to source is what you want to name the files after it comes out of browserify.

The argument to source should be the name of the file (so in your case just `main.js`)

This is all in the documentation for browserify and the documentation for the source plugin.
