### ISSUE TITLE
Gulp Installation Creates Many Node_Modules - Why?

### ISSUE THREAD

**Issue by Amakaruk** [gulpjs/gulp#1436]
Why are so many sub-directories created when I install gulp using the following command:

    npm install --save-dev gulp

This is the result (files created in my node_modules folder):

12/09/2015  08:33 PM    <DIR>          .
12/09/2015  08:33 PM    <DIR>          ..
12/09/2015  08:33 PM    <DIR>          .bin
12/09/2015  08:32 PM    <DIR>          ansi-regex
12/09/2015  08:32 PM    <DIR>          ansi-styles
12/09/2015  08:33 PM    <DIR>          archy
12/09/2015  08:32 PM    <DIR>          array-differ
12/09/2015  08:32 PM    <DIR>          array-uniq
12/09/2015  08:33 PM    <DIR>          balanced-match
12/09/2015  08:32 PM    <DIR>          beeper
12/09/2015  08:32 PM    <DIR>          brace-expansion
12/09/2015  08:33 PM    <DIR>          builtin-modules
12/09/2015  08:32 PM    <DIR>          camelcase
12/09/2015  08:32 PM    <DIR>          camelcase-keys
12/09/2015  08:32 PM    <DIR>          chalk
12/09/2015  08:33 PM    <DIR>          clone
12/09/2015  08:32 PM    <DIR>          clone-stats
12/09/2015  08:33 PM    <DIR>          concat-map
12/09/2015  08:33 PM    <DIR>          core-util-is
12/09/2015  08:33 PM    <DIR>          dateformat
12/09/2015  08:33 PM    <DIR>          defaults
12/09/2015  08:33 PM    <DIR>          deprecated
12/09/2015  08:33 PM    <DIR>          duplexer2
12/09/2015  08:32 PM    <DIR>          end-of-stream
12/09/2015  08:32 PM    <DIR>          error-ex
12/09/2015  08:32 PM    <DIR>          escape-string-regexp
12/09/2015  08:33 PM    <DIR>          extend
12/09/2015  08:32 PM    <DIR>          fancy-log
12/09/2015  08:32 PM    <DIR>          find-index
12/09/2015  08:32 PM    <DIR>          find-up
12/09/2015  08:32 PM    <DIR>          findup-sync
12/09/2015  08:32 PM    <DIR>          first-chunk-stream
12/09/2015  08:33 PM    <DIR>          flagged-respawn
12/09/2015  08:32 PM    <DIR>          gaze
12/09/2015  08:32 PM    <DIR>          get-stdin
12/09/2015  08:33 PM    <DIR>          glob
12/09/2015  08:33 PM    <DIR>          glob-stream
12/09/2015  08:33 PM    <DIR>          glob-watcher
12/09/2015  08:32 PM    <DIR>          glob2base
12/09/2015  08:33 PM    <DIR>          globule
12/09/2015  08:32 PM    <DIR>          glogg
12/09/2015  08:33 PM    <DIR>          graceful-fs
12/09/2015  08:33 PM    <DIR>          gulp
12/09/2015  08:33 PM    <DIR>          gulp-util
12/09/2015  08:32 PM    <DIR>          gulplog
12/09/2015  08:32 PM    <DIR>          has-ansi
12/09/2015  08:32 PM    <DIR>          has-gulplog
12/09/2015  08:33 PM    <DIR>          hosted-git-info
12/09/2015  08:32 PM    <DIR>          indent-string
12/09/2015  08:33 PM    <DIR>          inflight
12/09/2015  08:33 PM    <DIR>          inherits
12/09/2015  08:32 PM    <DIR>          interpret
12/09/2015  08:33 PM    <DIR>          is-arrayish
12/09/2015  08:32 PM    <DIR>          is-builtin-module
12/09/2015  08:32 PM    <DIR>          is-finite
12/09/2015  08:33 PM    <DIR>          is-utf8
12/09/2015  08:32 PM    <DIR>          isarray
12/09/2015  08:33 PM    <DIR>          liftoff
12/09/2015  08:32 PM    <DIR>          load-json-file
12/09/2015  08:33 PM    <DIR>          lodash
12/09/2015  08:32 PM    <DIR>          lodash.escape
12/09/2015  08:32 PM    <DIR>          lodash.isarguments
12/09/2015  08:32 PM    <DIR>          lodash.isarray
12/09/2015  08:32 PM    <DIR>          lodash.keys
12/09/2015  08:32 PM    <DIR>          lodash.restparam
12/09/2015  08:32 PM    <DIR>          lodash.template
12/09/2015  08:32 PM    <DIR>          lodash.templatesettings
12/09/2015  08:32 PM    <DIR>          lodash._basecopy
12/09/2015  08:32 PM    <DIR>          lodash._basetostring
12/09/2015  08:32 PM    <DIR>          lodash._basevalues
12/09/2015  08:32 PM    <DIR>          lodash._getnative
12/09/2015  08:32 PM    <DIR>          lodash._isiterateecall
12/09/2015  08:32 PM    <DIR>          lodash._reescape
12/09/2015  08:32 PM    <DIR>          lodash._reevaluate
12/09/2015  08:32 PM    <DIR>          lodash._reinterpolate
12/09/2015  08:33 PM    <DIR>          loud-rejection
12/09/2015  08:33 PM    <DIR>          lru-cache
12/09/2015  08:32 PM    <DIR>          map-obj
12/09/2015  08:33 PM    <DIR>          meow
12/09/2015  08:32 PM    <DIR>          minimatch
12/09/2015  08:33 PM    <DIR>          minimist
12/09/2015  08:33 PM    <DIR>          mkdirp
12/09/2015  08:33 PM    <DIR>          multipipe
12/09/2015  08:33 PM    <DIR>          normalize-package-data
12/09/2015  08:32 PM    <DIR>          number-is-nan
12/09/2015  08:32 PM    <DIR>          object-assign
12/09/2015  08:32 PM    <DIR>          once
12/09/2015  08:33 PM    <DIR>          orchestrator
12/09/2015  08:33 PM    <DIR>          ordered-read-streams
12/09/2015  08:32 PM    <DIR>          os-homedir
12/09/2015  08:33 PM    <DIR>          parse-json
12/09/2015  08:32 PM    <DIR>          path-exists
12/09/2015  08:32 PM    <DIR>          path-is-absolute
12/09/2015  08:32 PM    <DIR>          path-type
12/09/2015  08:32 PM    <DIR>          pify
12/09/2015  08:32 PM    <DIR>          pinkie
12/09/2015  08:32 PM    <DIR>          pinkie-promise
12/09/2015  08:33 PM    <DIR>          pretty-hrtime
12/09/2015  08:33 PM    <DIR>          process-nextick-args
12/09/2015  08:32 PM    <DIR>          read-pkg
12/09/2015  08:32 PM    <DIR>          read-pkg-up
12/09/2015  08:33 PM    <DIR>          readable-stream
12/09/2015  08:33 PM    <DIR>          rechoir
12/09/2015  08:32 PM    <DIR>          redent
12/09/2015  08:32 PM    <DIR>          repeating
12/09/2015  08:33 PM    <DIR>          replace-ext
12/09/2015  08:33 PM    <DIR>          resolve
12/09/2015  08:33 PM    <DIR>          semver
12/09/2015  08:33 PM    <DIR>          sequencify
12/09/2015  08:33 PM    <DIR>          sigmund
12/09/2015  08:33 PM    <DIR>          signal-exit
12/09/2015  08:32 PM    <DIR>          sparkles
12/09/2015  08:32 PM    <DIR>          spdx-correct
12/09/2015  08:32 PM    <DIR>          spdx-exceptions
12/09/2015  08:33 PM    <DIR>          spdx-expression-parse
12/09/2015  08:32 PM    <DIR>          spdx-license-ids
12/09/2015  08:32 PM    <DIR>          stream-consume
12/09/2015  08:32 PM    <DIR>          string_decoder
12/09/2015  08:32 PM    <DIR>          strip-ansi
12/09/2015  08:32 PM    <DIR>          strip-bom
12/09/2015  08:33 PM    <DIR>          strip-indent
12/09/2015  08:32 PM    <DIR>          supports-color
12/09/2015  08:33 PM    <DIR>          through2
12/09/2015  08:32 PM    <DIR>          tildify
12/09/2015  08:32 PM    <DIR>          trim-newlines
12/09/2015  08:33 PM    <DIR>          unique-stream
12/09/2015  08:33 PM    <DIR>          user-home
12/09/2015  08:33 PM    <DIR>          util-deprecate
12/09/2015  08:32 PM    <DIR>          v8flags
12/09/2015  08:32 PM    <DIR>          validate-npm-package-license
12/09/2015  08:33 PM    <DIR>          vinyl
12/09/2015  08:33 PM    <DIR>          vinyl-fs
12/09/2015  08:33 PM    <DIR>          wrappy
12/09/2015  08:33 PM    <DIR>          xtend
               0 File(s)              0 bytes
             134 Dir(s)  511,612,510,208 bytes free

**Comment by phated** [comment]
This is by design, gulp is composed of many small modules (the node pattern)
