### ISSUE TITLE
Windows Installation is *not* global

### ISSUE THREAD

**Issue by thaddeusd** [gulpjs/gulp#1437]
npm install -g gulp on a Windows server uses %appdata% to install gulp. Any code compiled requires the path to %appdata% to be hard wired in the project. Is there a way to install that does not need %appdata%?

**Comment by TrySound** [comment]
@thaddeusd It's npm issue.

**Comment by phated** [comment]
This is how npm does things.  If you would like to ask them about it, you can open an issue at https://github.com/npm/npm
