### ISSUE TITLE
Gulp 4: Specify which events should trigger task (gulp.watch)

### ISSUE THREAD

**Issue by glen-84** [gulpjs/gulp#1438]
I need to run a task when files or folders are added or changed, but not deleted. I can't find a way to do this.

Would it make sense to add an "events" option, like this:

```js
let watcher = gulp.watch("**/*.js", {events: ["add", "change", "addDir"]}, myTask);

watcher.on("all", (event, eventPath) => {
    if (event === "unlink" || event === "unlinkDir") {
        // Handle deletions separately.
    }
});
```

I apologize if I'm missing something.

**Comment by mattidupre** [comment]
Came here for a similar issue. Right now I'm having to create a noop function `done => done()` just to instantiate a watcher.

```javascript:
gulp.watch('foo/**/*.bar', done => done())
  .on('unlink', ...)
;
```

Is there any way to just add a property proxying chokidar directly?

**Comment by phated** [comment]
We've fixed not having `opts` or a `callback` as of #1501 - if you need to listen to specific events, use the returned file watcher like:

```js
var watcher = gulp.watch('foo/**/*.bar');
watcher.on('unlink', fn);
watcher.on('unlinkDir', fn);
```

**Comment by mattidupre** [comment]
Outstanding, much appreciated!

**Comment by glen-84** [comment]
Thanks Blaine. =)

**Comment by webcaetano** [comment]
Feedback: 
Had same problem. 
I figure out that gulp 4 uses gulp-watcher with uses https://github.com/paulmillr/chokidar
So for now the docs for watch events are there.

**Comment by webcaetano** [comment]
Here an example:
https://github.com/webcaetano/boilerplate-gulp-webapp/blob/a8a099a3956b8194d764c257603d998a0d0ca20f/gulp/watch.js#L22-L34
