### ISSUE TITLE
git problem

### ISSUE THREAD

**Issue by YoniLug** [gulpjs/gulp#1440]
I tried running my  gulp with gulp built command  and i get the   
gulp built
the following error output:

![untitled1](https://cloud.githubusercontent.com/assets/11645613/11842312/8e7e562e-a40b-11e5-8c1c-b4539d99aa72.png)

how ican solve this issue?

**Comment by phated** [comment]
This isn't a gulp problem, it is happening inside your jspm dependency.  Support questions should be directed to StackOverflow.
