### ISSUE TITLE
Gulp unstable and slow after switching to Babel 6.

### ISSUE THREAD

**Issue by frankwaalkens** [gulpjs/gulp#1442]
After we switched to Babel 6 and split babel up to use babel-preset-react, babel-preset-es2015 etc. my gulp task has become increasingly slower. 

Another side-effect is the fact that i can run a maximum of 4 builds, after this, gulp will not compile anything and i will have to manually quit and reset the current watch-task.

any clues how to improve my task?

Kind regards,

Frank

**Comment by contra** [comment]
Can you include the relevant code?

**Comment by frankwaalkens** [comment]
Im sorry, I can´t do that. I was hoping there was a know issue with Babel6 in combination with existing gulp tasks.

Kind regards,

**Comment by callumacrae** [comment]
Babel does slow down the startup time of Gulp because it transpiles the code before executing it, but that's expected. It shouldn't slow it down much, though.

Could be an issue. We can't know unless we can replicate it. Good luck!

**Comment by PrimeLens** [comment]
this worked for me

https://www.reddit.com/r/javascript/comments/3u7gob/babels_poor_performance_what_im_doing_wrong/cz2z0or
