### ISSUE TITLE
Directory name set to lowercase when copied

### ISSUE THREAD

**Issue by j-bailey** [gulpjs/gulp#1444]
Hello,

When I copy file with `gulp.src('assets/**/*').pipe(gulp.dest('build/assets'));`, the directory names all come out lowercase.  However, file names are in their original format.  Is there a way to fix this?

**Comment by contra** [comment]
@j-bailey Which operating system?

**Comment by j-bailey** [comment]
OSX El Capitan

**Comment by phated** [comment]
OSX uses a case insensitive file system by default so that is most likely your problem.
