### ISSUE TITLE
Document exports as task

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1445]
We should add some documentation for this.  Not sure if it should be here, or gulp-cli.  Maybe it would be a good recipe.

Ref https://github.com/gulpjs/gulp/issues/1305

cc @thejameskyle

**Comment by thejameskyle** [comment]
Side question: Should this be the recommended way of writing tasks within an ES2015 context?

**Comment by kevdez** [comment]
Does this only benefit gulp-cli with the auto-completion? If so, I agree that it's a better fitting in gulp-cli. It seems like a specific use case, correct me if I'm wrong btw.

**Comment by phated** [comment]
@kevdez it allows you to use es2015 module syntax in conjunction with babel to avoid using gulp.task

**Comment by phated** [comment]
@thejameskyle Probably for 4.0 but 3.x still has the terrible dependency syntax you have to use. Would you be willing to contribute a recipe for 3.x (submitted to master) and then adapt it for 4.0 and submit to the 4.0 branch?

**Comment by marcinant** [comment]
Is this code valid for 4.0 only?
On 3.9.1 I get:
```
Task 'default is not in your gulpfile
Please check the documentation for proper gulpfile formatting
```

**Comment by phated** [comment]
@marcinant you must be using the latest published version of `gulp-cli`, not the CLI that comes with gulp 3.x

**Comment by marcinant** [comment]
Could you please mention this somewhere in comments?

**Comment by phated** [comment]
Feel free to submit a PR
