### ISSUE TITLE
Setting base path in src path

### ISSUE THREAD

**Issue by deni35** [gulpjs/gulp#1450]
Now to use a several different base paths I'm forced to call the several gulp.src and use the merge:
```javascript
var s1 = gulp.src([
        './bower_components/bootstrap/dist/css/*.css',
        './bower_components/bootstrap/dist/js/*.js',
        './bower_components/bootstrap/dist/fonts/*',
        '!**/*.min.*',
        '!**/npm.js'
    ], {
        base: './bower_components/bootstrap/dist'
    })
    .pipe(gulp.dest('./dist/'));

var s2 = gulp.src('./bower_components/jquery/dist/jquery.js')
    .pipe(gulp.dest('./dist/'));

return merge(s1, s2);
```

It would be great to have a special character to separate base path. For example (here I use " : " char):
```
'./bower_components/bootstrap/dist:/css/*.css'
```
Now I can do it the following way:
```
'./bower_components/bootstrap/dist/*fonts/*'
```
This will allow us to separate paths into config file.

Also I'd like be able to set rename options in path. For example: 
```
'./bower_components/jquery/dist/jquery.js   {prefix: "/js/"}'
```

**Comment by Austin503** [comment]
'./bower_components/jquery/dist/jquery.js   {prefix: "/js/"}

**Comment by phated** [comment]
I could see us supporting a function for that option like we do for many options on `dest`.  I'll open an issue on vinyl-fs

**Comment by phated** [comment]
Linked
