### ISSUE TITLE
Should we suggest gulp-cli for 3.x?

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1451]
Currently, gulp ships with the CLI built in, but we split it out to allow for different versions of gulp to be handled.  It is going to be suggested in 4.x to install gulp-cli globally instead of gulp.  However, should we update the docs in master (for 3.x) to suggest that also?

**Comment by phated** [comment]
@contra ^

**Comment by contra** [comment]
@phated Yeah, I think so
