### ISSUE TITLE
gulp and gulp-cli both define bin/gulp.js

### ISSUE THREAD

**Issue by yurivict** [gulpjs/gulp#1452]
Shouldn't you delete one of them? They are overlapping.

**Comment by contra** [comment]
It's on purpose - you can install gulp or gulp-cli globally and it will work the same

**Comment by yurivict** [comment]
It doesn't matter which one I install? But they have random diffs here and there.

**Comment by contra** [comment]
Yes, this is exactly what we do.

**Comment by yurivict** [comment]
No, both gulp and gulp-cli install gulp executable. Only gulp-cli should install an executable.
Also both have shell completions. Only one should have completions.

**Comment by contra** [comment]
@yurivict I think I know my code better than you, so let me definitively tell you: All of the CLI logic is in the gulp-cli module. I don't understand why you opened this issue or why you are arguing with me other than to piss me off.

Proof:
- https://github.com/gulpjs/gulp/blob/4.0/package.json#L27
- https://github.com/gulpjs/gulp/blob/4.0/bin/gulp.js
