### ISSUE TITLE
Gulp truncates file time

### ISSUE THREAD

**Issue by jcmoore0** [gulpjs/gulp#1455]
Issue:  Gulp.Dest truncates file modified time (down to the second)

version: 4.0.0-alpha.2    
[21:19:57] 1450153068177  - src stat.mtime.getTime()
[21:19:57] 1450153068000 -  dest stat.mtime.getTime()
  
var newer = require('gulp-newer');
var debug = require('gulp-debug');
var gutil = require('gulp-util');
gulp.task('test', () => {
     gutil.log('testing');
     return gulp.src('app/assets/img/**')
       .pipe(newer('tmp'))
       .pipe(debug())
       .pipe(gulp.dest('tmp'));
 });

**Comment by contra** [comment]
Which version of gulp is this? 4.0 or 3.x?

**Comment by jcmoore0** [comment]
4.0.0-alpha.2   
Thanks

**Comment by phated** [comment]
Thanks for finding and reporting.  This was actually reported and fixed by https://github.com/gulpjs/vinyl-fs/pull/125 which we should be releasing soon but we have a bigger bug that needs to be fixed in the same release.
