### ISSUE TITLE
standalone + stream or separate gulp plugin

### ISSUE THREAD

**Issue by strarsis** [gulpjs/gulp#1457]
When considering to write a gulp plugin, what approach is best?

1. standalone module with some vinylfs stream compatible access + out streaming

2. separate gulp plugin wrapped around the module

I observe some tools going the first approach, deprecating their gulp-plugins 
and offering this functionality directly from the wrapped/underlying module instead.

Thank you and
with best regards

**Comment by gakimball** [comment]
I'm interested to know about this as well, as I've written a few libraries specifically designed for Gulp anyway, and as the maintainer it's simpler if I can keep the functionality in one codebase.

In some cases you can infer the user's intent with the plugin options. For example, if a plugin has a `src` option to take in files, if the developer omits that option, you can assume the files are coming in through a stream.

**Comment by callumacrae** [comment]
I'd say either approach is valid: what we _don't_ want is a module that can only be accessed using gulp, and that's not what you're asking about. I've written [plugins which wrap modules](https://github.com/callumacrae/gulp-w3cjs), and [plugins inside the modules](https://github.com/callumacrae/rev-del), and both have worked fine.

**Comment by gakimball** [comment]
@callumacrae If a module's API only works with Gulp (as in, only within a Vinyl stream), is the recommendation then to prefix the module name with `gulp-` so you're being up-front about it?

**Comment by callumacrae** [comment]
Yep! Check out point 8 of the plugin guidelines: https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

> Name your plugin appropriately: it should begin with "gulp-" if it is a gulp plugin

**Comment by strarsis** [comment]
So using a separate gulp plugin is always best practice.
However, the actual functionality can still come from the underlying module,
like favicons does by exposing stream property.

With best regards

**Comment by callumacrae** [comment]
Going to close this now, let me know if you have any more questions.
