### ISSUE TITLE
Update vinyl-fs dependency

### ISSUE THREAD

**Issue by SimenB** [gulpjs/gulp#1458]
Current version transitively pulls in `lodash@1`, which spits out a deprecation-warning during installation of Gulp.

![image](https://cloud.githubusercontent.com/assets/1404810/12010084/14521c16-ac97-11e5-9d93-c3bdd201b1a5.png)

![image](https://cloud.githubusercontent.com/assets/1404810/12010085/18b6b910-ac97-11e5-8c43-d217d15bd0b5.png)

**Comment by TrySound** [comment]
@SimenB Dup of https://github.com/gulpjs/gulp/pull/1295 and many others. Please use search before asking.

**Comment by SimenB** [comment]
Sorry abut that
