### ISSUE TITLE
using child_process detached=true does not work for some reason

### ISSUE THREAD

**Issue by ORESoftware** [gulpjs/gulp#1464]
Hi all, this is a question about using child_processes with Gulp - I have these two tasks in my Gulpfile which each kick off a C.P.:

```js
var testRunner = require('./index').Runner;

gulp.task('run_tests', ['suman'], function (cb) {

    testRunner({
        $node_env: process.env.NODE_ENV,
        fileOrDir: './test/build-tests',
        configPath: './suman.conf.js'
    }).on('message', function (msg) {
        console.log('msg from suman runner', msg);
        cb();
    });

});


gulp.task('suman', [], function (cb) {

    var proc = require('./index').Server();
    proc.on('message', function (msg) {
        console.log('msg from suman server', msg);
        cb();
    });

});
```

so as you can see above, I have two Gulp tasks, each of which are kicking of child_process using cp.fork() like so:

```js
makeSuman.Runner = function (obj) {

    var $NODE_ENV = obj.$node_env;
    var fileOrDir = obj.fileOrDir;
    var configPath = obj.configPath;

    var n = cp.fork('./lib/runner', ['--pth', fileOrDir, '--cfg', configPath], {
        detached: true,
        env: {
            NODE_ENV: $NODE_ENV || process.env.NODE_ENV
        }
    });

    return n;
}


makeSuman.Server = function (obj) {

    obj = obj || {};
    var $NODE_ENV = obj.$node_env;

    var n = cp.fork('./bin/www', [], {
        detached: true,
        env: {
            NODE_ENV: $NODE_ENV || process.env.NODE_ENV
        }
    });

    return n;
}
```

A little more info before the question - when I use detached:true as an option for child_process for the node Express Server that I am trying to start, the Gulp process just seems to die immediately. So for now I have been forced to use detached:false. But using the false option then seems to prevent my other child_process from doing its thing right. 

So, my question is, why does using the detached:true option cause my 'suman' Gulp task to just bomb? 

All I get is this:

```
$ gulp run_tests
[17:16:14] Using gulpfile ~\WebstormProjects\suman\gulpfile.js
[17:16:14] Starting 'suman'...
(then it dies)
$
```

but when I set detached to false, it works sort of fine - any ideas? thanks!

**Comment by contra** [comment]
@ORESoftware the way the node event loop works is the process dies if nothing is keeping it open.

https://nodejs.org/api/child_process.html#child_process_options_detached

Simple explanation: If you type `node -e 'console.log(1)'` it will print and die, but if you do `node -e 'process.on('stdin', function(){ console.log(1); })'` it will stay open, because you added stuff to the event loop. When you detach the process you are telling node you don't want the child process to keep the parent open.

Simple solution: Don't detach it, and if you have to then make something keep the node event loop going

**Comment by ORESoftware** [comment]
ok thanks - I might use what you suggested to keep Gulp alive - but is it possible that Gulp is overreaching in killing the child_processes spawned by it even if those child_processes are detached? What I am experiencing is that if I set detached=true for any CP spawned by Gulp, they seem to get killed when the main Gulp process dies. Any more insights appreciated, thanks

**Comment by contra** [comment]
@ORESoftware gulp doesn't touch anything you are doing or have anything to do with keeping the process alive - if you ran the exact same code in a `test.js` file with `node test.js` you should experience the same result.

**Comment by ORESoftware** [comment]
I know what you mean, but my experimentation seems to show there are some differences, not sure due to what.  It makes no sense that if I set detached to true that when the Gulp process ends, that the child_processes should be killed; from what I remember, when I run it as node test.js, the same thing doesn't happen. Let me double check and if I see anything weird I might report back.

**Comment by contra** [comment]
@ORESoftware If you find a difference can you make a sample repo that reproduces the problem?

**Comment by ORESoftware** [comment]
will do, haven't fully looked into it yet - one thing that might help me on my way - if I use Gulp to start a server - which is what I have been trying to do - ideally what would happen is when I fork a child_process a new terminal window would pop up and stdout/stderr would be directed to that terminal and that process would be separate and detached from Gulp. Any idea how to open a separate terminal window with a child_process/Gulp?

**Comment by contra** [comment]
@ORESoftware Again, gulp doesn't really do anything to the code you run inside of it. That's all standard node.js stuff - if you want to open a new terminal from your javascript you will probably have luck by googling something like "nodejs how to open a terminal" or searching npm for a module.

**Comment by ORESoftware** [comment]
alright np will get back to you asap on if I find something weird, pls keep ticket open for a couple more days thanks
