### ISSUE TITLE
Installing via npm results in over 100 modules being installed.

### ISSUE THREAD

**Issue by qodesmith** [gulpjs/gulp#1466]
`npm install --save-dev gulp`

The above is now resulting in over *100* modules being install in my npm_modules folder. I've used gulp on a number of other projects but have never seen this before. Entering `gulp --v` in the console returns "CLI version 3.9.0".

**Comment by tunnckoCore** [comment]
And? Maybe you're switched to npm3? It uses flat resolution, so it's normal.

But yea, hance, 100 modules, huh. I :heart: gulp, lol.

Cheers,
Charlike! :100:

**Comment by qodesmith** [comment]
::facepalm:: That was it: npm3. Closing this issue. Thanks!
