### ISSUE TITLE
devdocs.io

### ISSUE THREAD

**Issue by thigrand** [gulpjs/gulp#1467]
Hello,
Will you add offline docs on devdocs.io? 
Please;)

**Comment by ginfuru** [comment]
:+1:

**Comment by phated** [comment]
I couldn't find any documentation on contributing docs to them.  I think this is either up to that project to include our docs or the community to contribute them.  I read something about a scraper, so I would assume they just scrape our docs but I'm not sure.

**Comment by kubawolanin** [comment]
Author of DevDocs wrote on [its Trello board](https://trello.com/c/gj3ojCAh/349-scrapy#comment-57f4f5c8548aec73fc026c4e) that it's possible for anyone to  contribute to the project. I think it's a matter of submitting a pull request.
