### ISSUE TITLE
release 4.0.0 with beta tag on npm

### ISSUE THREAD

**Issue by nmn** [gulpjs/gulp#1469]
Can we please have gulp v4 on NPM with a flag? beta/alpha/next

I've been playing with gulp4 by installing from github and it seems to work well and is much simpler than before. So having it on NPM would be nice to keep playing and getting more feedback as well.

**Comment by phated** [comment]
There are still breaking changes to be made.

**Comment by phated** [comment]
To be clear, this was locked because it is a duplicate of #865 which has already detailed how we will handle the release process when we can actually bump the version. Please refrain from opening duplicate issues as it spreads discussion and makes it harder for people to find things.
