### ISSUE TITLE
Lodash deprecated warning

### ISSUE THREAD

**Issue by votemike** [gulpjs/gulp#1472]
I am getting the error `lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0`

I believe this is because gulp is using an old version of **vinyl-fs** which depends on an old version of **glob-watcher** which depends on an old version of **gaze** which depends on an old version of **globule** which uses the deprecated version of **lodash**.

So I believe this could be solved by upgrading the version of **vinyl-fs** that gulp uses.

**Comment by TrySound** [comment]
Dup of https://github.com/gulpjs/gulp/issues/1458

**Comment by votemike** [comment]
So it is, I don't know why my search didn't pick up on that. However that issue is closed as it is a dup. And the ticket it dups has been closed without a proper resolution. Is this issue not going to be fixed?

**Comment by TrySound** [comment]
Read chain
> Breaking version, you can use vinyl-fs directly in your gulpfile. Just replace gulp.src with vfs.src, etc

**Comment by TrySound** [comment]
These deprecations nothing break. Need just wait gulp4 release.

**Comment by votemike** [comment]
Fair enough if it's going to be resolved in G4.
