### ISSUE TITLE
Gulp.watch dosen't work when I use intellij idea to develop.

### ISSUE THREAD

**Issue by wubobuaa** [gulpjs/gulp#1473]
When I use sublime text to edit files and save,Gulp.watch works well,but Gulp.watch will not keep watching files if I use intellij idea to develop.Just because intellij idea can save files automatically?

**Comment by callumacrae** [comment]
Works for me, I just have to press cmd+s to manually save the file. Not sure why. Not a gulp issue, take it up with JetBrains if you want the behaviour changing :)

**Comment by nkanand4** [comment]
Although this is closed, I wanted to add this information for anyone landing here.

You need to turn off "Safe write" in
File -> Settings -> System Settings -> Use "safe write" (save changes to a temporary file first)

http://stackoverflow.com/questions/34614229/gulp-watch-dosent-work-when-i-use-intellij-idea-to-develop
