### ISSUE TITLE
gulp.unwatch

### ISSUE THREAD

**Issue by LPGhatguy** [gulpjs/gulp#1475]
With long-running watch tasks in Gulp, I sometimes want to stop and restart a watch task (usually to find new globbed files on systems that don't handle them well).

To do this, a `gulp.unwatch` method would be useful to undo the operation of `gulp.watch`.

**Comment by contra** [comment]
@LPGhatguy In gulp 3.x, gulp.watch returns an object that you can dispose of with `.end()`

More info here: https://github.com/gulpjs/glob-watcher
