### ISSUE TITLE
gulp.src base not working as expected

### ISSUE THREAD

**Issue by fourbytes** [gulpjs/gulp#1476]
I'm trying to have my processed css output to the same dir as the source scss using this:

```
gulp.task('sass_modules', function() {
  return gulp.src('Application/modules/**/*.scss')
  .pipe(sassInheritance({dir: 'Application/modules/'}))
  .pipe(sourcemaps.init())
  .pipe(sass().on('error', sass.logError))
  .pipe(sourcemaps.write('./maps'))
  .pipe(gulp.dest('Application/modules/'));
});
```

However this just results in all files being written to Application/modules/, not the source dir (e.g. Application/modules/landing/static/landing/css).

I've also tried using the base option as per below but this results in all output files being output to the application root directory/the current working dir.

```
gulp.task('sass_modules', function() {
  return gulp.src('Application/modules/**/*.scss', {base: './'})
  .pipe(sassInheritance({dir: 'Application/modules/'}))
  .pipe(sourcemaps.init())
  .pipe(sass().on('error', sass.logError))
  .pipe(sourcemaps.write('./maps'))
  .pipe(gulp.dest('./'));
});
```

Which as per the documentation [here](https://github.com/gulpjs/gulp/blob/master/docs/API.md), seems like they should both work. Am I missing something here?

```
$ gulp -v
[11:36:39] CLI version 3.9.0
[11:36:39] Local version 3.9.0
```

**Comment by phated** [comment]
Please supply a repo that reproduces this and link it here.  It is very hard for gulp contributors to set up everything as you have it set up and it becomes much easier to look into if they can just clone a repo down and test it.

**Comment by alexnewmannn** [comment]
@fourbytes Could you not do a mixture of the two? Set the base to `{base: 'Application' }` which means the file name outputted would be anything after `Application`. Then set the destination to Application -  `gulp.dest('./Application')`

Which means if you pass in 
```
gulp.task('sass_modules', function() {
  return gulp.src('Application/modules/**/*.scss', {base: 'Application'}) //Aplication/Modules/Helpers/_variables.scss
  .pipe(sassInheritance({dir: 'Application/modules/'}))
  .pipe(sourcemaps.init())
  .pipe(sass().on('error', sass.logError))
  .pipe(sourcemaps.write('./maps'))
  .pipe(gulp.dest('./Application')); // Application/Modules/Helpers/_variables.css
});
```
`Application/Modules/Helpers/_variables.scss` should be the outputted file.

Sorry if this my interpretation of your question is wrong, if you give code or an example source path and where you want it to be saved I could be of more help.

**Comment by fourbytes** [comment]
@alexnewmannn, tried that setup exactly (copy paste), and it results in the same problem, the files get output to the destination (./Application/_variables.css and ./Application/maps/_variables.css.map) instead of the source directory, seeming to ignore the base option completely.

@phated I'll set up a small example repo when I get some time today.

**Comment by phated** [comment]
In my extremely sort time debugging this, it seems that the gulp-sass-inheritance plugin is to blame.  I removed it from the pipeline and the `.css` files are output to the correct directories.  I tried reading the source of gulp-sass-inheritance but it seems terrible.
