### ISSUE TITLE
did you forget to signal async completion

### ISSUE THREAD

**Issue by rolandjitsu** [gulpjs/gulp#1483]
If I have a task that should run for a long time, when I stop it using `CTRL + C` I get:
```shell
[18:42:01] The following tasks did not complete: serve
[18:42:01] Did you forget to signal async completion?
```
Is there any way to fix this or to make the task not throw that?

**Comment by glen-84** [comment]
What does the task look like?

**Comment by rolandjitsu** [comment]
It looks something like:
```js
gulp.task(function serve(done) {
	WebSocketServer.isRunning(BUILD_SERVER_ADDRESS).then(
		() => {
			log(colors.red('A build server instance has already been started in another process, cannot start another one'));
			done();
			process.exit(1);
		},
		() => {
			gulp.task('build')(() => {
				createJsBuildServer();
				createBuildServer();
				log(colors.green('File watch processes for HTML, CSS & static assets are started'));
				gulp.watch(PATHS.src.static, gulp.series('serve/static'));
				gulp.watch(PATHS.src.html, gulp.series('serve/html'));
				gulp.watch(PATHS.src.scss, gulp.series('build/css'));
				// For more BS options,
				// check http://www.browsersync.io/docs/options/
				bs.init({
					server: PATHS.dist.public,
					port: WEB_SERVER_PORT
				});
				// When process exits kill browser-sync server
				process.on('exit', () => {
					bs.exit();
				});
			});
		}
	);
});
```

**Comment by callumacrae** [comment]
Caused by https://github.com/gulpjs/gulp/issues/1268. I'm not sure if this is a bug: the task hasn't completed, after all.

Might be a good idea to check the status code in the exit event listener, and only throw the warning on 0. Would help avoid confusion like this.

**Comment by rolandjitsu** [comment]
I realize that semantically it has not completed, as it is running until stopped by the user, but once stopped it should catch up on that and not throw. Otherwise, is there a way to signal completion when the exit event listener is triggered (I used `done` but then I get the message after the process is killed)?

**Comment by glen-84** [comment]
There is a 2nd argument to `bs.init`. Does it help if you do:

```js
bs.init({
    server: PATHS.dist.public,
    port: WEB_SERVER_PORT
}, done);
```

?

See https://www.browsersync.io/docs/api/#api-init

**Comment by rolandjitsu** [comment]
It does actually. Thanks :+1:
