### ISSUE TITLE
Unable to export an Object from Gulp task to another Javascript file

### ISSUE THREAD

**Issue by SimitTomar** [gulpjs/gulp#1484]
I have a simple Gulp Task in which I am merging few Yaml files and updating some variables which I want to share with another Javascript file. This is how my gulpfile.js looks:

var mergedYaml;
var initialVariable = 'Test1';
var updatedVariable;

gulp.task('ShareVariable', function(cb){
        //Load all the Yaml files available inside pom folder
        return glob("tests/acceptance/wdio/utilities/pom/*.yml", function (er, files) {
            //console.log(files);
            mergedYaml = yamlMerge.mergeFiles(files);
            initialVariable = 'Test2';
            updatedVariable = initialVariable;
            console.log(updatedVariable);
            cb();
        })
})

module.exports = {
    myFunc1: function() {
        return updatedVariable;
    }
};

Now, when I use the value of ‘updatedVariable’ in another gulp task, it’s value is correct i.e., Test2.

But on exporting the value of this variable, the value is returned as undefined, This is how I am importing this in my Test.js

var myFile = require('../../../../gulpfile.js');
console.log(myFile.myFunc1());

I think this is happening because when the function is getting called in Test.js, The context of 'updatedVariable' is lost as it's not getting transferred from gulp task to the exported function.

Is there any way I can export a variable which has been updated in the Gulp Task to another javascript file ? My ultimate goal is to use the ‘mergedYaml’ object but to start with I am trying to export simple variables.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
