### ISSUE TITLE
gulp 4 bails out on task before it's finished

### ISSUE THREAD

**Issue by laurelnaiad** [gulpjs/gulp#1490]
I just upgraded to 4 in hopes of solving this.... but what I got was actually just a more verbose bail out...

"The following tasks did not complete: watch
[13:40:40] Did you forget to signal async completion?

Is there a way to trick gulp into not assuming that I've forgotten to do something?

I have a very complicated task. I'm trying to hide the complications from gulp, but whether I return a promise or attempt a callback, I get this message.

**Comment by laurelnaiad** [comment]
(Ok, so for future reference gulp 4 still seems to require a phantom event handler.
Tacking `stream.on('data', (file) => { });` onto the end of the stream I'm using (inside the promise) seems to work around it.

**Comment by phated** [comment]
Pretty sure something is being done very wrong if that is your solution.

**Comment by laurelnaiad** [comment]
I guess it's fine if you think that, but nonetheless my streaming process just gets interrupted by gulp unless I tack that onto the end.

**Comment by glen-84** [comment]
I have the same issue, and it seems related to #552 because it fails after 16 files.

According to [this](https://github.com/gulpjs/gulp/issues/552#issuecomment-139933016) comment, you have to `sink the stream by returning it or piping it into anything that consumes it`, which is what @laurelnaiad was doing above with the `.on("data", ...` – is there a more elegant way of doing this?

My task looks something like this:

```ts
// Build images.
export default async (gulp, defKey: string, config) => {
    const buildManager = new BuildManager(config, "img", defKey);

    // Determine last run.
    let lastRun = gulp.lastRun(`build:img:${defKey}`);
    if (lastRun === undefined) {
        lastRun = await buildManager.loadLastRun();
    }

    // Determine whether or not to stream changes using Browsersync.
    let sync;
    if (nestedProp.get(config, "operations.browserSyncStream.enabled")) {
        sync = browserSync.has("bs-server");
    } else {
        sync = false;
    }

    return new Promise((resolve, reject) => {
        gulp.src(nestedProp.get(config, "paths.src"), {since: lastRun})
            .pipe(print((filePath) => `Building '${filePath}'`))
            .pipe(ifElse(
                nestedProp.get(config, "operations.minification.enabled"),
                imagemin.bind(null, nestedProp.get(config, "operations.minification.options"))
            ))
            .pipe(gulp.dest(nestedProp.get(config, "paths.dest")))
            .pipe(ifElse(
                sync,
                () => browserSync.get("bs-server").stream(
                    nestedProp.get(config, "operations.browserSyncStream.options")
                )
            ))
            .on("finish", () => {
                buildManager.saveLastRun();
                resolve();
            });
    });
}
```

I tried returning `gulp.src`, but that didn't seem to help.

**Comment by phated** [comment]
@glen-84 I don't see why you need to use the `async` keyword and return a promise, if this is just a gulp task, you can just return the stream and not use async.  Streams must end with a writeable stream or they don't get drained and the transform streams buffer to 16 and the process exits.  We've done work to make `gulp.dest` act like a writeable stream but you're ending on the `ifElse` transform stream instead.  if you return the stream (not a promise) to `gulp.task`, we drain it for you so "bad" patterns like this don't cause problems.

**Comment by glen-84** [comment]
@phated,

Thanks for your reply.

I just confirmed that the issue is indeed caused by the if/else Browsersync part of the code. My code seems similar to the way it's done in the [docs](https://www.browsersync.io/docs/api/#api-stream):

```js
// Compile SASS & auto-inject into browsers
gulp.task('sass', function () {
    return gulp.src('scss/styles.scss')
        .pipe(sass({includePaths: ['scss']}))
        .pipe(gulp.dest('css'))
        .pipe(bs.stream());
});
```

What would you suggest as an alternative?

**Comment by phated** [comment]
@glen-84 your code is nothing like that example because you wrap it in a promise and flag your function with `async`.  My suggest is "don't do that".

**Comment by glen-84** [comment]
I'm using `async` to await the method call (`await buildManager.loadLastRun()`) ... is there no way to support an async method? It's gonna be a bit messy nesting everything in a `then`.

**Comment by phated** [comment]
@glen-84 all gulp tasks are treated as async, I don't understand why you think you need to build something custom on top of it.  All of this is documented at https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#async-support (gulp 4) and https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support (gulp 3)

**Comment by glen-84** [comment]
I'm not trying to "build something custom on top of it", I just wanted to call a function using async/await because it's much cleaner than using promises directly.

The function just returns a last run time from a file, nothing fancy. I'm familiar with the various ways of signalling async completion using Gulp.

If the task itself cannot work when marked as `async`, then I'll have to just use `then`.

Thanks for your help.

**Comment by phated** [comment]
@glen-84 alright, with the context you have given, it seems like you are adding complexity for complexity's sake.  In the future, please direct support questions to StackOverflow.  Thanks!
