### ISSUE TITLE
A single task in gulp.watch() using gulp.task() incorrectly logs as <anonymous>

### ISSUE THREAD

**Issue by jaydenseric** [gulpjs/gulp#1492]
As [discussed](https://github.com/gulpjs/gulp/issues/1411#issuecomment-173383849) earlier.

Using the latest version of Gulp 4:

```js
var gulp = require('gulp');

gulp.task('css', function () {
  return gulp.src('test.css');
});

gulp.task('watch', function () {
  gulp.watch('test.css', gulp.task('css'))
})
```

Results in:

```
[09:45:21] Starting 'watch'...
[09:45:24] Starting '<anonymous>'...
[09:45:24] Finished '<anonymous>' after 15 ms
```

Whereas replacing the watch task with:

```js
gulp.task('watch', function () {
  gulp.watch('test.css', gulp.registry().get('css'))
})
```

Results in:

```
[09:52:17] Starting 'watch'...
[09:52:20] Starting 'css'...
[09:52:20] Finished 'css' after 16 ms
```

**Comment by axvm** [comment]
`gulp.task()` returns function which in fact anonymous (`function() { }`). 

gulp.task:
```js
function task(name, fn) {
  if (typeof name === 'function') {
    fn = name;
    name = fn.displayName || fn.name;
  }
  
  if (!fn) {
    return this._getTask(name);
  }

  this._setTask(name, fn);
}
```

_getTask:
```js
function get(name) {
  var wrapper = this._registry.get(name);

  if (!wrapper) {
    return;
  }

  var meta = metadata.get(wrapper);

  if (meta) {
    return meta.orig; // Here is our anonymous function, Watson!
  }

  return wrapper;
}
```

The problem can be resolved by overriding _getTask method in `gulp/index.js` like this:
```js
  var metadata = require('undertaker/lib/helpers/metadata');
  
  function Gulp() {
    // ... 
    this._getTask = function get(name) {
      var wrapper = this._registry.get(name);

      if (!wrapper) {
        return;
      }

      var meta = metadata.get(wrapper);

      if (meta) {
        let orig = meta.orig;
        orig.displayName = meta.name;

        return orig;
      }

      return wrapper;
    };
  }
```
Yea, this is private method but another way to fix the problem - override `gulp.task`

**Comment by phated** [comment]
@avxm it just needs to be fixed in undertaker.

**Comment by axvm** [comment]
@phated I can send PR. But which way preferred? Set function display name in public `task` method or in private `_getTask` method?

**Comment by phated** [comment]
Neither, gulp shouldn't modify a user's function. I'm not sure of the complete solution for this. It might need to be done with the watch debounce changes.

**Comment by axvm** [comment]
@phated I don't understand why we can't set `displayName` if it undefined?

```js
 fn.displayName = fn.displayName || 'foo'
```

We do not modify value if it defined. Also i'm not sure with decision to fix it in undertaker. This is project-specific problem so it needs to be fixed here, isn't?

**Comment by axvm** [comment]
Ok. Now I understand why it needs to be fixed in undertaker and why we shouldn't modify user's functions. Anyways the problem in return value of `task` method. Any cons why it must to return unwrapped function?

**Comment by phated** [comment]
I had some time to look into this and I couldn't come up with a good reason why I wanted to return the unwrapped function.  Instead, `gulp.task('taskName')` will return the wrapped function with an `unwrap()` method if you need to get the original function.  I have the code, just need to finish it up and push it.

**Comment by phated** [comment]
@jaydenseric @axvm this should be fixed by my update of undertaker in https://github.com/gulpjs/gulp/commit/d8f5c90a0622d19ef1943a2a3d02dc50e3c853e7
