### ISSUE TITLE
gulp.watch - Error: watch null EMFILE

### ISSUE THREAD

**Issue by qodesmith** [gulpjs/gulp#1499]
`gulp.watch` is giving an error in the simplest use-case that I've set up. I've been using gulp.watch in a few projects and this error is "all-of-a-sudden". Perhaps I'm overlooking something? Are my glasses on my face but I can't find them?

Here is my gulpfile.js contents:
```javascript
var gulp = require('gulp');
var less = require('gulp-less');

gulp.task('default', function() {
  gulp.watch('styles.less', ['styles']);
});

gulp.task('styles', function() {
  return gulp.src('styles.less')
  .pipe(less())
  .pipe(gulp.dest(''));
});
```
As you can see, this is a simple scenario where watching a less file change will result in compiling that file to css. Here's what I see in the console when I run 'gulp':
```
[19:19:30] Using gulpfile ~/Projects/Sandbox/fred/gulpfile.js
[19:19:30] Starting 'default'...
2016-01-23 19:19 gulp[41595] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[19:19:30] Finished 'default' after 7.91 ms
events.js:141
  throw er; // Unhandled 'error' event
  ^

Error: watch null EMFILE
  at exports._errnoException (util.js:856:11)
  at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)
```

I also tried replacing the contents of the 'styles' task to just contain a console.log statement. Same results. Any thoughts on this?

**Comment by qodesmith** [comment]
I forgot to add the versions of everything I'm using:
* npm: 3.5.3
* node: 5.4.1
* gulp:
  * CLI version: 3.9.0
  * Local version: 3.9.0
* gulp-less: 3.0.5

**Comment by phated** [comment]
That error is a node error for too many files open.  Guessing something is wrong with your OS.  I suggest googling around for `EMFILE`

**Comment by qodesmith** [comment]
I only have Sublime, the terminal, and Chrome open at the same time (nothing novel here). What I did notice is that if I *close* sublime and *then* run gulp, the process runs with no error. So damn weird. And to add to the weirdness, this error is *not* consistent. My life.

**Comment by phated** [comment]
Sublime probably is accessing a bunch of files (maybe a plugin or their indexing process, etc).  Good luck tracking down the problem.

**Comment by qodesmith** [comment]
@phated I appreciate the insight. Googling `emfile` now. Hope this helps someone else who may land here via google or something.

**Comment by lichenbuliren** [comment]
I have the same problem with you . finally i found that the actually problem is that if you open you project directory with command sublime . under terminal,and then run the gulp, that the gulp will cause the error.

so, you can open sublime application first, and then load you project directory, and finally start gulp in the terminal. everything will be ok！

hope the will help you

**Comment by orangeyyy** [comment]
I have got the same problem now, if I close the Sublime, it works well, could somebody tell me why? is   it a problem of Sublime?

**Comment by mapleshawxiao** [comment]
@lichenbuliren It's working now!!!  thanks a lot!!!

**Comment by jasperrooduijn** [comment]
@lichenbuliren I had the same problem and your solution works! Thats great. I just can not understand what the real issue is here... Could you tell me why this happens?
