### ISSUE TITLE
add option to NOT run fs.chmod() on destination files

### ISSUE THREAD

**Issue by cr1st1p** [gulpjs/gulp#1502]
I'm in the situation of having all the permission setup with 'setfacl' (for lxc containers) and I can NOT work at ALL with this setup because gulp's code always tries to run chmod, which fails miserably.

Can you please add an option where there is no chmod() call involved?
Gulp version 3.9.0

**Comment by phated** [comment]
3.9 won't be receiving this change; we could probably do it for gulp 4.

**Comment by kcivey** [comment]
It looks like the chmod problem was fixed in 9 months ago (#1012) but still not in a released version. It's been driving me crazy too.

**Comment by callumacrae** [comment]
@kcivey from the issue you linked to:

>  feel free to use the 4.0 stuff it's stable

`npm install --save-dev gulpjs/gulp#4.0`

**Comment by cr1st1p** [comment]
For who's interested in an ugly hack, I did this, in gulpfile.js:
var fs = require('fs');
if (1) fs.chmod = function (a, b, cb) {
	cb(0);
}

I haven't tested gulp v4.0 but I do wonder if it won't *still* crash, since I also am having default 'setfacl' settings for directories.

**Comment by phated** [comment]
Lots of fixes have either landed in vinyl-fs or are about to land in vinyl-fs (avoiding the chmod if the process uid is not the same as the file owner).  If you don't want to upgrade to gulp 4, you can pull in vinyl-fs as the standalone module to have the fixes.  node's module resolution might even pick it up for your gulp install if they are side-by-side.

**Comment by cr1st1p** [comment]
Well, I just tried using 4.0, but I get several unmet dependencies warnings. 
And when I try to run it, I get all kind of missing module errors.
Can you create an actual release version of 4.0 instead of having it as a branch, and publish it on npm?

**Comment by phated** [comment]
No, it isn't complete yet.

**Comment by phated** [comment]
Expanding upon that ^ - there are *many* people using it already so your system is messed up, not gulp 4.

**Comment by cr1st1p** [comment]
I started again from an empty package.json and added one by one the required dependencies. Still got some warnings about dependencies, but I ignored them.
It would have helped me if you would have left me a notice about an important change re: gulp 4 (gulp.series|parallel).

After doing the required changes in my gulpfile.js, guess what? I ended now with 
[10:10:24] Error: EPERM: operation not permitted, futime
    at Error (native)

The file is there, user can write/append into it. So, I got the same bad behaviour I was complaining, if using setfacl.

Then, I commented the call in ./node_modules/gulp/node_modules/vinyl-fs/lib/dest/writeContents/writeBuffer.js
Things worked kind of ok until I got a different message, which I guess is because of my possibly incomplete migration of gulpfile.js to gulp#4.0

Vinyl-fs version: 2.3.1

**Comment by phated** [comment]
As stated in my original post the change/fix for not attempting chmod if the process.uid doesn't match the file uid is still in progress and hasn't landed yet.  I am going to lock this thread because it is causing additional noise to something that already is being worked on over in the vinyl-fs repo.
