### ISSUE TITLE
Gulp 4: Unsupported dependency

### ISSUE THREAD

**Issue by pascalberger** [gulpjs/gulp#1503]
While trying to install gulp 4 using the following command:

    npm install -g git+https://git@github.com/gulpjs/gulp.git#4.0

I get the following warning:

    npm WARN install Couldn't install optional dependency: Unsupported

Node version is 5.5.0 and npm 3.3.12.

**Comment by marvinhagemeister** [comment]
Relevant npm issue: https://github.com/npm/npm/issues/9204#issuecomment-174223597

**Comment by TrySound** [comment]
@pascalberger It's chokidar mac specific thing. Nothing bad with it. Just skip it.
