### ISSUE TITLE
Trying to import compass mixins

### ISSUE THREAD

**Issue by Ziiweb** [gulpjs/gulp#1504]
I have just followed [this][1] tutorial without problems, to start using SASS. As you can see it includes a part where it is using **compass mixins**. I have compiled `.scss` files including `@import compass/css3/box-sizing` without problems.

Now I want to compile my `.scss` files, but using Gulp. So I have followed [this][2] tutorial. So now I have these files:

    //src/DefaultBundle/Resources/public/assets/css/main.scss
    form {
      span {
        color: red;
      }
    }

    var gulp = require('gulp');
    var sass = require('gulp-sass');
    gulp.task('default', function() {
        gulp.src('src/DefaultBundle/Resources/public/assets/css/main.scss')
            .pipe(sass())
            .pipe(gulp.dest('web/css'));
    });

So when I run `$ gulp` as the latter tutorial says, I get the `.css` file.

**The problem**: if I add **`@import compass/css/box-sizing`** at the top of my `.scss file`, I get this error when running `$ gulp`:

    [13:12:01] Working directory changed to /var/www/my_project
    [13:12:01] Using gulpfile /var/www/my_project/gulpfile.js
    [13:12:01] Starting 'default'...
    [13:12:01] Finished 'default' after 5.37 ms
    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: src/DefaultBundle/Resources/public/assets/css/main.scss
    Error: File to import not found or unreadable: compass/css3/box-sizing
           Parent style sheet: stdin
            on line 2 of stdin
    >> @import "compass/css3/box-sizing";
       ^
    
        at options.error (/var/www/my_project/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:277:32)

Im on Ubuntu 15.

  [1]: http://www.zingdesign.com/the-sass-and-compass-tutorial-for-absolute-beginners/
  [2]: http://knpuniversity.com/screencast/gulp/sass

**Comment by TrySound** [comment]
@Ziiweb It's support issue. Please address it on [stackoverflow](http://stackoverflow.com/)
