### ISSUE TITLE
Proposal: gulp.dest() should return Promise so multiple operations can be resolved in task

### ISSUE THREAD

**Issue by SetTrend** [gulpjs/gulp#1507]
When working with transpilers (e.g. `TSC`), it regularly occurs in a task that multiple stream branches are getting created.

In addition, other operations may be involved in a task which need to finish before completion and don't deal with streams at all (e.g. `del`)

`gulp.dest()` is not expected to return streams. So I'd like to suggest to have `gulp.dest()` return a `Promise` object instead.

This way we could wait for `gulp.dest()` to finish from within `gulp.task()`. And we also could have `gulp.task()` return a `Promise` object, too, for synchronization:

```js
gulp.task( "buildProject"
         , function ()
           { var ts = tsc(...);

             return Promise.all( ts.ts.pipe(gulp.dest("lib"))
                               , ts.dts.pipe(gulp.dest("headers"))
                               , new Promise((resolveCB) => { del("obj"); resolveCB(); });
                               );
           }
         );
```

**Comment by TrySound** [comment]
@SetTrend Tasks should be atomic. API follow this convention. This API let you split compicated operation in a few small. What you ask is bad practice which won't be encouraged. Also I don't think that in typescript you can't use regular api.

**Comment by contra** [comment]
If you are using gulp 4, you basically just reinvented gulp's task system within a single task. If you break each step into it's own task (which can be just a function) and run them in `gulp.parallel` you effectively solve your problem.


Example with your code:

```js
var ts = tsc(...);

function lib() {
  return ts.ts.pipe(gulp.dest("lib"));
}

function headers() {
  return ts.dts.pipe(gulp.dest("headers"));
}

function clean() {
  del("obj");
}

gulp.task("buildProject", gulp.parallel(lib, headers, clean));
```

or if tsc needs to be dynamically constructed:

```js
function lib(ts) {
  return ts.ts.pipe(gulp.dest("lib"));
}

function headers(ts) {
  return ts.dts.pipe(gulp.dest("headers"));
}

function clean() {
  del("obj");
}

gulp.task("buildProject", function(cb) {
  var ts = tsc(...);
  return gulp.parallel(lib(ts), headers(ts), clean)(cb)
});
```

**Comment by SetTrend** [comment]
@contra : Excellent suggestion! What if `del()`/`clean()` both return `void`? Does `gulp.parallel()` accept `Promise` objects? So, may `clean()` return a `Promise` object?

**Comment by contra** [comment]
@SetTrend All functions support returning streams, returning promises, or calling a callback argument.

https://github.com/gulpjs/gulp/blob/4.0/docs/API.md

**Comment by SetTrend** [comment]
@contra : Thanks for trying to help.

My particular question is, though: Will `gulp.parallel()` accept promises in the *prerequisites* array? Or will it only accept strings of task names?

I cannot find this information in the documentation.
