### ISSUE TITLE
Gulp + Browserify + Uglify + SourceMaps

### ISSUE THREAD

**Issue by mdcanham** [gulpjs/gulp#1509]
I am using the recipe provided at [gulp/docs/recipes/browserify-uglify-sourcemap.md](url) however I can not get sourcemaps working with Browserify.

The sourcemaps that are generated do work however they take me from the uglified JS to the browserified JS. I want my source maps to take me to individual source files not my single browserified file.

I am not sure if this is how the recipe is meant to work. However from the description I got the impression that I'd be able to map from my minified JS to individual source files...

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
