### ISSUE TITLE
Move to ESLint external config "eslint-config-xo-space" ?

### ISSUE THREAD

**Issue by zckrs** [gulpjs/gulp#1511]
What do you think about use https://github.com/sindresorhus/eslint-config-xo-space  who extends [eslint-config-xo](https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js) with two spaces indentation ?

**Comment by phated** [comment]
I believe we discussed this early on in the switch to ESLint and XO wasn't going to work for us.  I forget the exact reasons but you can probably track down the comments.
