### ISSUE TITLE
Gulp watch fire task only on added or deleted

### ISSUE THREAD

**Issue by synthecypher** [gulpjs/gulp#1512]
Is there a way to only trigger a task upon a particular set of event types. e.g. `added` or `deleted`?

```javascript
gulp.watch(`/path/to/new/files**/*`, (event) => {
  if (event.type === 'added' || event.type === 'deleted') {
    // fire some gulp task
  }
});
```

**Comment by phated** [comment]
What version of gulp?  3.x or 4.0?

**Comment by synthecypher** [comment]
3.9.0

**Comment by contra** [comment]
Is this fixed with the 4.0 branch?

**Comment by yasinkocak** [comment]
On Gulp 3.8 and 3.9 is only triggering 'changed' and 'deleted' files.
Gulp 4.0 not tested.

Use Mac OSX El Capitan

`
var gulp = require('gulp');

gulp.task('default', function () {
  gulp.watch('templates/**/*.html', function (event) {
    console.log(event);
  });
});
`

**Comment by phated** [comment]
Chalking this up to #651 for 3.9 - However, I think you can use the returned watcher to listen on events, I'm not sure how accurate they are due to all the other problems.  In gulp 4, you can use the returned watcher to listen for all events that chokidar emits.
