### ISSUE TITLE
[Question] am I misinterpreting the use case for .on('stop')?

### ISSUE THREAD

**Issue by justinhelmer** [gulpjs/gulp#1515]
Hello, @contra and `gulp` contributors - thanks for the amazing tool.

I am trying to take advantage of the benefits of `gulp` programmatically, as a part of a larger build process. This issue may be better suited for [gulp-sass](https://github.com/dlmanning/gulp-sass) so I apologize if that is the case, but from my perspective it relates to my understanding of `gulp.dest` and the [Orchestrator](https://github.com/robrich/orchestrator) events.

Here is an illustration:

```js
// Store the working directory before running anything
var CWD = process.cwd();

var gulp = require('gulp');
require('some/other/location/gulpfile');

// fired when all tasks complete??
gulp.on('stop', function() {
  process.chdir(CWD); // restore cwd to what it was before calling gulp.start
  resolve(); // some promise
});

gulp.start('build');
```

```js
// gulpfile.js

// Set up the build path relative to the working directory
var buildPath = path.resolve('build');

// Change working directory to the location of the gulpfile, else gulp will not work
process.chdir(path.resolve(__dirname));

gulp.task('build', ['copyCSS']);
gulp.task('copyCSS', copyCSS);

function copyCSS() {
  var files = ['node_modules/normalize.css/normalize.css'];
  gulp.src(files).pipe(gulp.dest(buildPath + '/css'));
}
```

The issue is, the `gulp.on('stop')` callback appears to be fired before the files are actually written to disk. All output indicates success, but the physical files were not copied.

A small adjustment works around this observation:

```js
gulp.on('stop', function() {
  setTimeout(function() {
    process.chdir(CWD); 
    resolve();
  }, 20); // have to tinker with this number, its not an event loop thing
});
```

However, as it appears to be a timing issue, it is more likely related to my flawed understanding of the toolset.

Please advise.

**Comment by phated** [comment]
You aren't returning your stream, so the task management system doesn't know when the streaming is complete.  However, I don't recommend using the events or `gulp.start` because neither are gulp-documented functionality and will be completely removed/changed in gulp 4.

**Comment by justinhelmer** [comment]
oh man. haha thanks. sorry to waste your time.
