### ISSUE TITLE
How to build gulp.parallel dynamically?

### ISSUE THREAD

**Issue by AndreKR** [gulpjs/gulp#1517]
I think I am running into the same problem as in #1093, but I can't wrap my head around how to rewrite it:
```
var bundles = { 'a.js': [ 'source_a1.js', 'source_a2.js' ], 'b.js': [ 'source_b.js' ] };

gulp.task('dev', function () {

  var subtasks = Object.keys(bundles).map((destination) => {
    var bundler = browserify();
    bundles[destination].forEach((el) => {
      bundler.add(el);
    });
    return bundler.bundle().pipe(vinyl_source_stream(destination)).pipe(gulp.dest('output'));
  });

  return gulp.series(
    gulp.parallel.apply(null, subtasks),
    finalize()
  );

});
```

Immediately running the function doesn't work either:
```
gulp.task('dev', (function () {
  ...
})());
```
Result: `The following tasks did not complete: dev, <parallel>, <anonymous>, <anonymous> Did you forget to signal async completion?`

**Comment by contra** [comment]
You don't return a gulp.series or gulp.parellel - these are simply async functions. gulp.task only supports returning for streams and promises, for async functions use the callback:

```js
gulp.task('dev', function (cb) {
  // ... your other stuff

  var task = gulp.series(
    gulp.parallel.apply(gulp, subtasks),
    finalize
  );

  task(cb);
});
```

See the documentation for gulp.series and gulp.parallel if you have any other questions.

**Comment by contra** [comment]
Also, try using ES6 for `gulp.parallel(...subtasks)`

**Comment by AndreKR** [comment]
Ah, no sync tasks anymore, found it, thanks.
Yeah, I had the spread operator there but then I found out that it's only enabled in Node.js 5 which [isn't going to come](http://packages.ubuntu.com/xenial/nodejs) to Ubuntu for a long time. :(
