### ISSUE TITLE
3.9.0 package tarball is missing man pages

### ISSUE THREAD

**Issue by jasonkarns** [gulpjs/gulp#1518]
package.json lists gulp.1 as man pages, but said file is absent from the tarball

**Comment by jasonkarns** [comment]
same with 3.8.10, 3.8.11, and 4.0.0.alpha1

**Comment by phated** [comment]
Looks like https://github.com/gulpjs/gulp/commit/d2010000ec849c4ace0cfb7a691bba6a242faa20 added the `files` property but forgot to add the manpages.  Please start using the `gulp-cli` package for the CLI, it ships with the manpages now.

**Comment by phated** [comment]
Fixed and published in 3.9.1
