### ISSUE TITLE
What is the stream type returned by gulp.src()

### ISSUE THREAD

**Issue by unional** [gulpjs/gulp#1519]
Hi,

I wrote https://github.com/typings/typed-gulp to be used by https://github.com/typings/typings to provide typed support for gulp.

I wonder what is the return stream type of `gulp.src()`. Is it a `Duplex` stream?

**Comment by unional** [comment]
Referencing https://github.com/typings/typed-gulp/issues/1

**Comment by contra** [comment]
@unional gulp.src is a readable stream unless the [passthrough option](https://github.com/gulpjs/vinyl-fs#optionspassthrough) is passed to it, in which case it is a duplex

**Comment by contra** [comment]
FYI There are some major API changes in 4.0, you may want to type that branch from scratch

**Comment by unional** [comment]
Thanks!
