### ISSUE TITLE
No Changelog for gulp 3.9.1

### ISSUE THREAD

**Issue by code-chris** [gulpjs/gulp#1521]
There is no changelog for the new patch release 3.9.1, so nobody knows which was changed. Can someone add this info, please?

**Comment by artem-malko** [comment]
It seems, that there is no any changes?

**Comment by TrySound** [comment]
@code-chris You can always read commits :) Here's issue
https://github.com/gulpjs/gulp/issues/1518

**Comment by code-chris** [comment]
@TrySound There are many changes between 3.9 and 3.9.1.. So which changes are important?

**Comment by TrySound** [comment]
@code-chris That was only docs changes. Nothing important. 3.9.1 was happened only because previously man pages was accidentally dropped.

**Comment by code-chris** [comment]
@TrySound For me its ok, but its an official release, so there should be an entry in the changelog, or not?

**Comment by phated** [comment]
All the gulp team works on this in their free time.  Something was broken and we got a change out yesterday when we had some time.  The community is welcome and encouraged to submit PRs for anything, especially documentation things like this.
