### ISSUE TITLE
How to tell when Gulp is finished executing

### ISSUE THREAD

**Issue by evilgeniuscreative** [gulpjs/gulp#1522]
Is there a way to tell when Gulp is finished with all tasks it's running? I can't find anything in the docs. 

Or when all watches are finished?

If not, it'd be great to have that as part of the API. Gulp.isFinished or something.

**Comment by phated** [comment]
There are events you can listen to but they are purposefully undocumented because we don't intend to support them.

**Comment by evilgeniuscreative** [comment]
So... can you share with me these Great Secrets? Or are there other options to see when things are done? Thanks.

**Comment by phated** [comment]
`process.on('exit')`?  It is just a node API

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by evilgeniuscreative** [comment]
Thanks
