### ISSUE TITLE
gulp.src not including files correctly

### ISSUE THREAD

**Issue by Joshua-F** [gulpjs/gulp#1525]
After testing the example on the [API](https://github.com/gulpjs/gulp/blob/master/docs/API.md#globs) I noticed that all it is using as a source is just `a.js`.

The main reason I was looking into this was because I was trying to include all `server/**/*.ts` files but exclude all files in `server/typings/**` but include `server/typings/main.d.ts` but `server/typings/main.d.ts` isn't being included.

CLI version 3.9.1
Local version 3.9.1

Directory structure for test:

- server
  - a.js
  - bad.js
  - bob.js

```javascript
var gulp = require('gulp');
var debug = require('gulp-debug');

gulp.task('testing', function() {
    return gulp.src(['server/*.js', '!server/b*.js', 'server/bad.js'])
        .pipe(debug({title: 'test:'}))
});
```

> [06:30:36] Starting 'testing'...
> [06:30:36] test: server\a.js
> [06:30:36] test: 1 item
> [06:30:36] Finished 'testing' after 27 ms

Edit: After looking briefly at the code should this be moved to [gulpjs/vinyl-fs](https://github.com/gulpjs/vinyl-fs)?

**Comment by TrySound** [comment]
@Joshua-F Try to move negative glob in the end of array.

**Comment by TrySound** [comment]
First you found all in server, then you removed all b*, then in all leaved you are trying to find bad, but there is not one bad, caz all b* already removed. Everything is correct.

I'm not sure, but try
`['server/*.js', '!server/b^(ad)*.js']`

**Comment by Joshua-F** [comment]
If everything is correct then the docs are wrong, which I hope is not the case. I tried what you said and it included all 3 files.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow. If there is a problem with the docs, please submit a PR with the changes.

**Comment by Joshua-F** [comment]
@phated I'm not sure if you actually read the issue, the docs show that this is suppose to work, but it doesn't. Is this intended to work or not? If not then the docs are wrong, if yes then there is a bug here.
