### ISSUE TITLE
[Question] Any input or insight on `vinyl-tasks`?

### ISSUE THREAD

**Issue by justinhelmer** [gulpjs/gulp#1527]
If there is any interest in doing so, I would love to hear input from `Gulp` folks: [vinyl-tasks](https://github.com/justinhelmer/vinyl-tasks)

If there are questions, I can explain further. But the documentation and codebase should speak for themselves. This is intended to be a complete solution.

**Comment by justinhelmer** [comment]
If you think this is a good idea, can you help me get it into the hands of the right people?

Cheers.

**Comment by TrySound** [comment]
@justinhelmer gulp4 uses https://github.com/gulpjs/undertaker

**Comment by contra** [comment]
@justinhelmer FYI (in response to the README) Gulp 4 only breaks the task syntax, all of the plugins will continue to work exactly the same in 4.0.

**Comment by justinhelmer** [comment]
@TrySound @contra -

Both of those things are really good feedback. I will update the `README` and swap `orchestrator` for `undertaker`.

Be honest; is this a fruitful endeavor?

In terms of _who_ this would be useful for, any suggestions on how to reach those people?

I appreciate the quick responses and for getting involved.

**Comment by phated** [comment]
The limitations seem completely wrong. Gulp doesn't expect to be installed globally. I exclusively use it as part of npm scripts. Option parsing can be done using plain `process.argv` and you are more than welcome to run a gulpfile using the `node` command or even require it in any other script.

**Comment by justinhelmer** [comment]
@phated -

"Completely wrong" is a bit of a misnomer.

The `gulp` tool is documented as a command-line tool only. I have specifically seen callouts that running `gulp` tasks programmatically (i.e. via a `node` interface, i.e. using `.start()` directly) is unsupported. Are you suggesting otherwise? 

Or are you suggesting that there is not value in having a `Node JS` wrapper for running `Gulp` tasks, both individually and part of larger automation pipelines?

In my experience, and with the people I have worked with, they would rather not use `Gulp` via the `CLI`. This tool makes it possible for people to feel comfortable using `Gulp` in their scripts, and wraps it up in a pretty bow with `bluebird` promises, global error handling, and the like.

So I'm unclear exactly what your callouts are. My goal is to understand how you think these things are addressed by `Gulp` directly, or if you are saying that there is no value.

Ideally, this would be a project that you and your team support.

**Comment by phated** [comment]
Feel free to keep working on your project but I don't think this is something we are going to help push or take on maintenance responsibility for.  I'm going to close this issue.

**Comment by justinhelmer** [comment]
@phated fair enough. Bummer :-(

Cheers.
