### ISSUE TITLE
Task tree logging should be the same as gulp-cli

### ISSUE THREAD

**Issue by louisremi** [gulpjs/gulp#1528]
When gulp-cli is available globally, running `gulp --tasks` prints a pretty tree of tasks with colors and task description.
Gulp can also be used without a global gulp-cli, by running it from npm scripts:
```
"scripts": {
  "help": "gulp --tasks"
  "gulp": "gulp"
}
```
Now running `npm run help` will also print the list of gulp tasks. But _when using Gulp 3_, the list will be very basic, with no description available.

Would it be conceivable to instead have both modules share the same code and display the same task tree

**Comment by callumacrae** [comment]
They do use the same code https://github.com/gulpjs/gulp/blob/4.0/bin/gulp.js#L3

What versions of local and global gulp are you using?

**Comment by louisremi** [comment]
Absolutely right, I forgot to mention this difference was only present in Gulp 3.

**Comment by callumacrae** [comment]
It's a thing added in gulp 4. I'd recommend just updating to 4.0 at this point, if you want the output to be the same.

**Comment by louisremi** [comment]
The very large majority of users are still using Gulp 3. Gulp 4 isn't yet the current version of Gulp,  and there is no estimated release date of Gulp 4. I believe there are enough reasons, and the solution is simple enough, to justify patching Gulp 3.
I am ready to do most of the work if you reconsider the validity of this issue (I can't create the module where the shared code will be, though).

**Comment by callumacrae** [comment]
The large majority of users aren't using gulp-cli! :stuck_out_tongue: 

I believe gulp 3 is now feature frozen, so I doubt the maintainers would accept a patch adding this functionality. The resources would be best spent getting gulp 4 out of the door—if you're willing to help, that would be super useful!

Check out the outstanding issues here: https://github.com/gulpjs/gulp/issues?q=is%3Aissue+is%3Aopen+label%3Agulp4
