### ISSUE TITLE
Install on MacBook Pro

### ISSUE THREAD

**Issue by gofundamental** [gulpjs/gulp#1531]
I have tried installing on Mac and had this error. It looks like there is a possible workaround on PC, but perhaps someone knows how to fix on mac?
Thank you.

Gulp.js
WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by TrySound** [comment]
@gofundamental Nothing bad in this deprecation. Use can still use it.

**Comment by gofundamental** [comment]
Ok. Thank you. I'll try again. :)
