### ISSUE TITLE
Gulp pattern matching using double negation

### ISSUE THREAD

**Issue by anjali-chawla** [gulpjs/gulp#1532]
I have a folder structure as:

> app/
> ----- shared/  
> ---------- sidebar/
> --------------- sidebarDirective.js
> --------------- sidebarView.html
> ---------- article/
> --------------- articleDirective.js
> --------------- articleView.html
> ----- components/
> ---------- home/
> --------------- homeController.js
> --------------- homeService.js
> --------------- homeView.html

I want to write a gulp file match that includes all files, excludes all HTMLs except that of components/home folder

For it, I have written the following pattern
```
path = "app";
gulp.src([
     path  + '/**/*',
      '!' + path + '/**/*.html',
      '{!' + path + '/**,'+path+'/components/home}/*.html'
    ])
```
But this does not seem to work. Any inputs?

**Comment by tunnckoCore** [comment]
Okey, but why is the second pattern? Why you negate html files with it when you want them?

I believe that should work

```js
gulp.src([
  'app/**/*.html',
  '!app/components/home/*.html'
])
```

**Comment by anjali-chawla** [comment]
That is because I want to select all files except HTMLs. But I want the HTML files in /components/home folder. 
The pattern you suggested will give me all HTML files except that in /components/home.

**Comment by doowb** [comment]
@anjali-chawla in gulp 4 (which uses the latest `vinyl-fs` you can add another include pattern after the negation pattern:

```js
path = "app";
gulp.src([
     path  + '/**/*',
      '!' + path + '/**/*.html',
      path + '/components/home/*.html'
    ])
```

You can also use the `passthrough` option and use 2 `.src` calls:

```js
gulp.src([path + '/**/*', '!' + path + '/**/*.html'])
  .pipe(gulp.src([path + '/components/home/*.html'], {passthrough: true}))
```

**Comment by anjali-chawla** [comment]
Thanks for the response @doowb . But I'm currently using Gulp version 3.3.9 and I cannot change it. Is there anyway to achieve the same in 3.3.9 version?

**Comment by doowb** [comment]
You can use `vinyl-fs` directly in your gulp file and it will achieve the same results as using it through `gulp`:

```js
var vfs = require('vinyl-fs');

vfs.src(...)
  .pipe(vfs.dest(...));
```

**Comment by phated** [comment]
Closing this, as the recommendation to use vinyl-fs directly is the best recommendation.  I believe https://github.com/urish/gulp-add-src should work with old versions of gulp, also.
