### ISSUE TITLE
gulp.watch() stops watching after a minute.... is it because of old graceful-fs?

### ISSUE THREAD

**Issue by dman777** [gulpjs/gulp#1533]
I am using gulp 3.9.0. When I run gulp locally, `gulp.watch()` will watch files and ` watcher.on('change', function(event) {})` as it should. But it will only do it for about a minute, then it will stop detecting any changes. 

Using the same gulp task on my cloud server and same gulp version, I do not have this issue. 

There are no errors with `watcher.on('error', function(err) {}`. 

I noticed I get this message with npm:
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

```
localhost learning-threejs # npm list graceful-fs
app@0.0.1 /home/one/github/learning-threejs
├─┬ gulp@3.9.0
│ ├─┬ gulp-util@3.0.7
│ │ └─┬ dateformat@1.0.12
│ │   └─┬ meow@3.7.0
│ │     └─┬ read-pkg-up@1.0.1
│ │       └─┬ read-pkg@1.1.0
│ │         ├─┬ load-json-file@1.1.0
│ │         │ └── graceful-fs@4.1.3 
│ │         └─┬ path-type@1.1.0
│ │           └── graceful-fs@4.1.3 
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3 
│   └── graceful-fs@3.0.8 
├─┬ gulp-livereload@3.8.1
│ └─┬ gulp-util@3.0.7
│   └─┬ dateformat@1.0.12
│     └─┬ meow@3.7.0
│       └─┬ read-pkg-up@1.0.1
│         └─┬ read-pkg@1.1.0
│           ├─┬ load-json-file@1.1.0
│           │ └── graceful-fs@4.1.3 
│           └─┬ path-type@1.1.0
│             └── graceful-fs@4.1.3 
└─┬ wiredep@3.0.0
  └─┬ bower-config@0.5.2
    └── graceful-fs@2.0.3 
```

Would this be why? Would like to find out what is wrong.

**Comment by david-owens-akqa** [comment]
I'm pretty sure it's not graceful-fs that is causing your error. I get the same message, but gulp.watch() still works fine for me

**Comment by phated** [comment]
This is not a graceful-fs problem and the deprecation is just annoying, not harmful.  Going to chalk this up to #651 and I recommend you upgrade to gulp 4 to benefit from the new file watcher.
