### ISSUE TITLE
npm WARN deprecated graceful-fs@3.0.8

### ISSUE THREAD

**Issue by namel** [gulpjs/gulp#1537]
performing the basic `npm install gulp` results in warnings:

```
npm WARN deprecated graceful-fs@3.0.8
npm WARN deprecated lodash@1.0.2
npm WARN deprecated graceful-fs@1.2.3
```

Can these warnings be taken care of?  True - they are just warnings but it's gotten to be annoying ...

according to npm list, at least one of the culprits is:
```
 ├─┬ gulp@3.9.1
 │ └─┬ vinyl-fs@0.3.14
 │   ├─┬ glob-watcher@0.0.6
 │   │ └─┬ gaze@0.5.2
 │   │   └─┬ globule@0.1.0
 │   │     ├─┬ glob@3.1.21
 │   │     │ ├── graceful-fs@1.2.3
```

**Comment by callumacrae** [comment]
Updating those dependencies would be a breaking change and so can't be done in gulp 3. They're not harmful, but if they're really annoying you, just update to gulp 3!

https://github.com/gulpjs/gulp/issues/1485

**Comment by namel** [comment]
@callumacrae - I'm not sure I follow.  You're suggesting that I update to gulp 3, but I'm in gulp@3.9.1
am I missing something?  I guess you meant gulp 4?

**Comment by callumacrae** [comment]
Yeah, I meant gulp 4. sorry :)
