### ISSUE TITLE
Gulp task works manually, but doesn't use latest file changes in gulp watch.

### ISSUE THREAD

**Issue by zackhall** [gulpjs/gulp#1540]
I have a task that builds my index file: 

```
gulp.task('index', function() {
  gulp.src('src/index.html')
    .pipe(data(config))
    .pipe(gulpSwig(config))
    .pipe(gulp.dest('dist'));
});
```

When I run this manually, it takes `src/index.html` runs it through a swig template and outputs it to `dist/index.html` no problem.

However, I've got a watch task setup to watch this, and rerun the task: 

```
gulp.task('serve', ['index'], function() {
  gulp.watch('src/index.html', ['index']);
});
```

The first run of this runs just fine. When I update `src/index.html`, gulp catches it and runs the `index` task again and generates an `dist/index.html` file, but it somehow uses a cached version of `src/index.html`. No matter how many changes I make to the file, and how many times the `dist/index.html` is generated, it always generates it with the original content.

Can anyone tell me what's going on here?

**Comment by zackhall** [comment]
I can even delete the `dist\index.html` file to make sure it's generated again, but it uses the cached content.

**Comment by doowb** [comment]
I think `swig` caches templates by file path by default. You might want to see if `gulp-swig` passes the `config` through to the `swig` engine and see if there is a `cache` option.

**Comment by zackhall** [comment]
@doowb: You are currect. Good call! 

This fixed it: 
```
.pipe(swig({defaults: { cache: false }}))
```
