### ISSUE TITLE
Gulp 4 - Task with same name as function results in a "task did not complete" error

### ISSUE THREAD

**Issue by marcospgp** [gulpjs/gulp#1541]
I just spent a few hours trying to find out why my sass task was not completing. When I tried changing the name of the function to sassCpl (with the task in turn becoming `gulp.task('sass', sassCpl)`) it stopped returning an error and functioned normally.

 Maybe this should be mentioned somewhere? Or maybe fixed? I understand the redundancy of it given that in this case `gulp.task('sass')` should be enough, but users should be aware that `gulp.task('sass', sass)` doesn't work.

**Comment by phated** [comment]
Please supply a gulpfile.  Also, if your function is named "sass" why are you using string names and not just passing the function (as is the gulp 4 suggestion)?

**Comment by marcospgp** [comment]
You mean `gulp.task(sass)`? As you can see from my post, I did mention that but thought it was `gulp.task('sass')`. And as you can see from what I said, I am following the suggestion now that I found the cause of the problem, but it should still be important to alert users about the impossibility of having tasks and functions with the same name.

 Here's a gulpfile:

```
var gulp = require('gulp'),
	sass = require('gulp-sass');

function sass () {
	return gulp.src('./src/sass/**/*.scss')
		.pipe(sass().on('error', sass.logError))
		.pipe(gulp.dest('./src/styles'));
}

function watch () {
	gulp.watch('./src/sass/**/*.scss', sass);
}

gulp.task('watch', watch);

gulp.task('sass', sass);

gulp.task('serve', gulp.series(
	/*gulp.parallel(sass, compileTs),
	gulp.parallel(watch, connectPhp)*/
	sass
));

```

**Comment by phated** [comment]
So the problem here is your own JS.  You have named a variable **and** a function `sass` so the names collide and it uses the assignment of the `require('gulp-sass`)` because named functions are essentially hoisted upon parse.  This isn't a gulp problem.
