### ISSUE TITLE
gulp doing nothing

### ISSUE THREAD

**Issue by cawoodm** [gulpjs/gulp#1543]
The following gulp.js is supposed to concatenate all my .js files into one but it does nothing and shows no error message:

```javascript
var gulp = require('gulp');
require('gulp-concat');

gulp.task('default', function() {
	gulp.src('./*.js')
	.pipe(concat('modules.js'))
	.pipe(gulp.dest('dist'));
}
);
```

PS: I run it with `node gulp.js` as just running `gulp` on my machine (Win7) simply opens gulp.js in my editor (notepad++).

**Comment by TrySound** [comment]
@cawoodm First of all you don't have any global or local `concat` variables. Running gulp.js will define tasks. But nothing will execute it. Also gulp use `gulpfile.js` config by default, not `gulp.js`. I think you problem will be fixed with renaming.

**Comment by cawoodm** [comment]
Cool thanks! I knew this was a noob issue.

**Comment by ashishpatel1992** [comment]
Hi,
I am using following command to run my file
node gulpfile.js
**Code:**
```
var gulp = require('gulp');
var wpPot = require('gulp-wp-pot');
console.log(`Gulp Running`);
var s= gulp.task('compile',() => {
  console.log(`GUlt`);
  return gulp.src('truemag/**/*.php')
        .pipe(wpPot({
          domain:'cactusthemes',
          package:'Example Project',
          destFile: 'myfile.pot'
        }))
        .pipe(gulp.dest('./file.pot'));
})
//console.log(s);
gulp.task('log', function() {
  console.log('== My Log Task ==')
});

```

But nothing happens just a console output Gulp Running. But In real gulp doesnt do anything.

**Comment by TrySound** [comment]
@ashishpatel1992 Use `gulp-cli` to run tasks. gulpfile just adds your tasks to registry, but do not run 'em.

**Comment by ashishpatel1992** [comment]
@TrySound  Thanks! Its working now!
