### ISSUE TITLE
gulp4 - How should I run a task from inside a node script?

### ISSUE THREAD

**Issue by orpx** [gulpjs/gulp#1547]
Before gulp4 I could use gulp.start, is there an alternative or a best practice for gulp4 within gulp package?

I can always use https://github.com/shelljs/shelljs in order to execute shell commands from node.

**Comment by TrySound** [comment]
@orpx `gulp.series('default')();` or `gulp.parallel('default')();`

**Comment by orpx** [comment]
Thanks! I wasn't familiar with this usage.
