### ISSUE TITLE
gulp4 pass parameters when invoking a task from a script

### ISSUE THREAD

**Issue by orpx** [gulpjs/gulp#1548]
Following https://github.com/gulpjs/gulp/issues/1547, Is there a way getting the parameters passed in the following example:

gulp.series('default')('p1','p2');

I am already familiar with using yargs but if I want to call the task from a script it is not really possible (unless I use a library like shelljs).

**Comment by hoodsy** [comment]
:+1:

**Comment by phated** [comment]
avoid string names whenever possible and partial the function.
