### ISSUE TITLE
add es6 example to gulp 4.0 readme

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#1549]
Need a really clean, minimalist gulpfile on the readme using es6. The README should feature the ES6 example first, then have the ES5 example second (want to make it clear we support everything).

Help wanted, good first time contribution!

**Comment by nkpfstr** [comment]
I assume you want this in the root README and not `docs/README.md`?

**Comment by jeremenichelli** [comment]
I can take care of it

**Comment by contra** [comment]
Also, if you want to create a better example than what's currently in the README - go right ahead 🌴

**Comment by jeremenichelli** [comment]
One question @contra, is it necessary to install **Babel** as a `devDependency` to make ES2015 modules work? I don't remember exactly that.

**Comment by contra** [comment]
@jeremenichelli Depends how much of ES6 you use - node supports a lot of it without any flags now, some stuff still needs babel installed however.

**Comment by jeremenichelli** [comment]
It would be good to add that as a note below the **es6** example.

**Comment by phated** [comment]
Merged @jeremenichelli's PR and did some cleanup and tested as actual gulpfiles.  Everything is working now in the 4.0 branch's readme

**Comment by jesperronn** [comment]
Just if people are looking, the PR from @jeremenichelli  is #1550
