### ISSUE TITLE
Illegal space before opening round brace in the function calls

### ISSUE THREAD

**Issue by hansiemithun** [gulpjs/gulp#1551]
After the upgradation of gulp from 3 to 4. I am facing this error:  The declaration` function (test)` with space is no longer working where as `function(test)` does work from` gulp lint `command. Also i find some weird error as follows:` Line must be at most 120 characters at C:filepath\app.config.js `. Quick fix of help w.r.to `gulp `or `jshintrc` rules will be much appreciated. To more details of this error i have posted an similar question in [Stackoverflow](http://stackoverflow.com/questions/35766128/how-to-supress-the-error-illegal-space-before-opening-round-brace-at-from-jsrc)

**Comment by TrySound** [comment]
@hansiemithun gulp is not linter. It's just task manager. Seems like you upgraded also linter. So it's not gulp issue.

**Comment by TrySound** [comment]
Ask in stackoverflow.

**Comment by hansiemithun** [comment]
Thanks for your quick response, which version of linter fits for this cause, can i have a better clarity w.r.to this.

**Comment by TrySound** [comment]
gulp issue is for bugs. It's support question. Keep discussing on stackoverflow and close this issue please.
