### ISSUE TITLE
Errors when deleting files and directory on Mac

### ISSUE THREAD

**Issue by dtrinh50** [gulpjs/gulp#1553]
I am using a Mac with OS X Yosemite and am currently getting errors every now and then when I try to run gulp.

My code for the clean task looks like this:
```

gulp.task('clean', function(cb) {
  del(bases.dist, cb);
});
```
I have tried two ways of using this clean task.

1. Pass it as a callback to a task. The issue with this is it deletes the files and stops there.

2. Call the clean task when I initiate Gulp. This works about 50% of the time. Every now and then, I get errors such as: 

`Error: ENOENT, stat '/Users/username/Desktop/project/dist/vendor/js/lib.min.js`

or
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/username/Desktop/project/dist/fonts/OpenSans-Bold.ttf'
    at Error (native)
```
I am almost certain the cause is with the clean task, but I am not 100% certain. Is there a way to solve this issue?

**Comment by phated** [comment]
The del module no longer takes a callback, it returns a promise. This isn't a gulp problem.
