### ISSUE TITLE
gulp.src UTF-8 without BOM

### ISSUE THREAD

**Issue by tolgaonbay** [gulpjs/gulp#1557]
Hi,

gulp.src removes BOM character from UTF-8 encoded files on MS Windows 7/Server 2012. I tried running the same task on cygwin and it worked. Is there any way to bypass this problem on Windows machines?

```
gulp.task('move', function() {
    return gulp.src(srcFolder + '/**/*')
            .pipe(gulp.dest(destFolder));
});
```

```
gulp --version
[10:03:33] CLI version 3.9.1
[10:03:33] Local version 3.9.1
```

```
node --version
v4.1.2
```

**Comment by phated** [comment]
Unfortunately, this isn't able to be disabled in gulp 3.x.  Please update to gulp 4 (`npm install gulpjs/gulp#4.0`) or use vinyl-fs ^2.0 directly.
