### ISSUE TITLE
Relative path of assets in bower_compontents packages

### ISSUE THREAD

**Issue by artinnok** [gulpjs/gulp#1560]
Hello!

For example, in project we have an [fotorama](http://fotorama.io/) or [semantic ui](http://semantic-ui.com/). CSS files of this packages have some rules:

**fotorama.css**
`.fotorama__video-play{background:url(fotorama@2x.png)`
**semantic.css**
`@font-face {
  src: url("themes/default/assets/fonts/icons.eot");
}`

I want to get at output of gulp:
**fotorama.css**
`.fotorama__video-play{background:url('/static/src/img/fotorama@2x.png')`
**semantic.css**
`@font-face {
  src: url("/static/src/fonts/icons.eot");
}`

Of course, we can use [gulp-replace](https://www.npmjs.com/package/gulp-replace) for creating some rules of replacement, but it is headache and bad decision - what if i have an dozens of CSS-dependencies in bower_components? I must write hundreds of rules?

**Comment by emaildano** [comment]
@artinnok gulp-replace does support [regex](https://www.npmjs.com/package/gulp-replace#regex).

With regex, you can write a pattern to match `url(` and `url("` and add your relative path. So you don't need to specify each one.

https://regex101.com/r/sC3hI5/1

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
