### ISSUE TITLE
gulp 3.9: failed to run gulp test

### ISSUE THREAD

**Issue by hodbauer** [gulpjs/gulp#1561]
I'm trying to run my app tests.
No matter what i've done the 'gulp test' is failed with the next error:
_Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')_

I have angular 1.5.1 app with ES6 syntax and i'm trying to test it.
I'm using karma with Jasmine to test it. i created a test:
```javascript
describe('controllers', () => {
  let vm;
  beforeEach(angular.mock.module('myApp'));
  // failed when adding this code (no matter what it include)
  beforeEach(inject(() => {
  }));
  // till here
  it('should be true', function(){
    expect(true).toBeTruthy();
  })
});
```
when i'm removing the inject section all is ok, but i cannot test my app without inject my controllers...

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
