### ISSUE TITLE
Not recongnizeing glob arguments when using merge-stream

### ISSUE THREAD

**Issue by kmcaloon** [gulpjs/gulp#1562]
So when I run a task using the standard method all of my globbing works fine. Here is the script along with the variables:

```
// Relevant variables
var devDir 			    = 'assets/';
var jsDir			    = 'scripts/';
var jsDev			 	= devDir + jsDir;
var mainJS              = 'main.js';
var mainScript 			= jsDev + mainJS;
var includedScripts	    = jsDev + '_*.js';

// The task
gulp.task('admin-js', function () {

 	return gulp.src([includedScripts, mainScript])
		.pipe(sourcemaps.init())
		.pipe(processScripts())
		.pipe(sourcemaps.write())
		.pipe(gulp.dest(jsDist))
		.pipe(browserSync.stream());
});
```

However, I would like to merge this with another stream within a single task. When I try to do this, it breaks:
```
gulp.task('admin-js', function () {

	var mainScript = gulp.src([includedScripts, mainScript])
		.pipe(sourcemaps.init())
		.pipe(processScripts())
		.pipe(sourcemaps.write())
		.pipe(gulp.dest(jsDist))
		.pipe(browserSync.stream());

	var otherScripts = gulp.src(otherScripts)
		.pipe(sourcemaps.init())
		.pipe(uglify)
		.pipe(sourcemaps.write())
		.pipe(gulp.dest(jsDist))

 	return merge(mainScript, otherScripts)

});
```
It is now telling me Error: Invalid glob argument: assets/scripts/_*.js, however this glob argument was working fine in the 1st example. 

Here is a recipe using the same method: https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md

**Comment by phated** [comment]
I bet there is something wrong with browser-sync's stream interface.  Please direct support questions to StackOverflow.
