### ISSUE TITLE
Gulp do not support node version 4.4 and above.

### ISSUE THREAD

**Issue by madhurangaonbit** [gulpjs/gulp#1563]
When trying to run gulp I get the following error:
Bus error (core dumped)

Then I found it is because of the node-sass issue.
So I ran `npm rebuild` and I came up with the following error.

/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Bus error (core dumped)

npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "rebuild"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

However I had nodejs 4.4 and I have downgraded to 0.12.12 .
Then it is working without any issue.

**Comment by callumacrae** [comment]
This isn't an issue with gulp. It is either an issue with npm, or node-sass.

**Comment by phated** [comment]
To be specific, it is a native module compilation problem with node-sass

**Comment by madhurangaonbit** [comment]
However, When I downgraded to Node 0.12.12, everything worked properly.

**Comment by Romanx** [comment]
I'm running 4.4 with node-sass and it's not an issue so it must likely be something with your environment @madhurangaonbit
