### ISSUE TITLE
3752 Segmentation fault      node "$basedir/node_modules/gulp/bin/gulp.js" "$@"

### ISSUE THREAD

**Issue by shahidbasheer** [gulpjs/gulp#1565]
Hi,
my gulp setup is working fine for months but all of sudden i am getting this error.
my directory structure is below and it working in my other project whereas gulpfile.js and project settting is same.
+projects
 |-- project_1
 |-- project_2
+node_module

here is the output of "npm ls chokidar"

$ npm ls chokidar
gulp_html_workflow@1.0.0 E:\Google Drive
└── (empty)

npm ERR! code 1

**Comment by shahidbasheer** [comment]
Hi, 
I checked it further error is with sass there are some variable in my sass partial file like i mention below when i comment them this error do not appear instead variable not found error which is ok. 
Now I switched to compass which is working fine. 


$orange: #ec7d00;
.orange {
	color: $orange;
}

 
 $blue : #3e81de;
.blue {
	color: $blue;
}

**Comment by phated** [comment]
Looks solved. Closing.

**Comment by hualinIT** [comment]
How to solve this problem?

**Comment by shahidbasheer** [comment]
@hualinIT compile sass file with compass to check if the error is in your sass file this is how i solved. Some time gulp-sass dont give correct error.
