### ISSUE TITLE
graceful-fs dependency update

### ISSUE THREAD

**Issue by ivishwas-s** [gulpjs/gulp#1568]
npm throws a warning that graceful-fs has an update.

`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

Please look into this.

**Comment by phated** [comment]
It's not throwing. It is just a log. Please look at other issues created about this before opening another one.
