### ISSUE TITLE
[Notice] graceful-fs deprecation warning

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1571]
We are aware of the graceful-fs deprecation warning upon install of gulp 3.x.

This is due to:
1. A transitive graceful-fs devDependency

We are unable to upgrade due to API breaking changes.

There is nothing wrong with the dependency, especially since it is only used in development. We will be updating or removing it in gulp 4 and the message will go away.

**Please do not open issues about this topic.
Thank you,
-The gulp team**

**Comment by phated** [comment]
This should be no longer an issue due to the amazing work by @thealphanerd at https://github.com/isaacs/node-graceful-fs/commit/07701dc98bc088e1a71f18a8f59a970e3354646f

I'll leave this open until I have a chance to verify.  Unlocking incase anyone has a chance to test it out.

**Comment by piotr-cz** [comment]
how to test?

**Comment by phated** [comment]
Looks like there was a follow up at https://github.com/isaacs/node-graceful-fs/commit/07701dc98bc088e1a71f18a8f59a970e3354646f#commitcomment-18659275

Locking again with the same conclusion.  Sorry everyone.

**Comment by phated** [comment]
As per https://github.com/gulpjs/gulp/pull/1760#issuecomment-242213701 - It looks like I can close this now that graceful-fs 3.0.10 has been released.

**Comment by phated** [comment]
Looks like I need to reopen this 😦

**Comment by phated** [comment]
gulp 4 has been published under the `next` tag (`npm install gulp@next`) so I'm going to close this.
