### ISSUE TITLE
.gitingore template for gulp

### ISSUE THREAD

**Issue by joeblau** [gulpjs/gulp#1573]
I maintain https://www.gitignore.io and I'm trying to create some Stack templates. As Gulp is part of Yeoman, I want to have a Yeoman template and include the 3 projects that make up Yeoman.  I already have templates for Bower and and Grunt, but none for Gulp yet.

**Comment by ebuildy** [comment]
Grunt, gulp etc... are toolkit / framework that do nothing themself, so I don't get the approach here.

Yeoman use Grunt or Gulp, with plugins and configuration to produce files, here I get the point, but for gulp alone nop

**Comment by joeblau** [comment]
Alright cool, that makes sense then for gulp being a no-op.  I didn't know if gulp created temporary files or imported dependences that should be ignored by git.  Thanks for your answer on this! :+1:
