### ISSUE TITLE
Sugestion: make it easier to add description to a task

### ISSUE THREAD

**Issue by fredyang** [gulpjs/gulp#1575]
In gulp v4, gulp.task does not support 3 parameter any more. So it is
gulp.task(taskName, function () {});

To add a description, I have to
var fn = function () { };
fn.description = 'a great task';
gulp.task(taskName, fn)

I would like to have gulp.task to support description like

gulp.task(taskName, fn, description);

description is an optional.

**Comment by phated** [comment]
Sorry, we've already discussed this and aren't going to implement it.  You can implement this with your own function wrapper or whatever.
