### ISSUE TITLE
gulpfile.babel.js, gulp-mocha, and line numbers

### ISSUE THREAD

**Issue by shellscape** [gulpjs/gulp#1577]
When using ES6 support through the `gulpfile.babel.js` convention, line numbers in stack traces are seriously jacked up - there doesn't seem to be any pattern that I can manually map the lines myself. I haven't yet been able to come up with a source map solution to produce the actual line numbers in the ES6 files that I'm `gulp.src`ing and passing to gulp-mocha.

Is this a fundamental problem with gulp doing the transpiling, or just something simple I'm missing that isn't documented?

**Comment by phated** [comment]
turn on sourcemap support in your babelrc

**Comment by phated** [comment]
Btw, support questions should be directed to StackOverflow

**Comment by shellscape** [comment]
@phated the SO thing is something you might say to rookies, and that definitely doesn't apply. On the surface this seemed like a breakdown in gulp's handling of babel internally, especially since literally nothing in the closed issues or much on google in the way of posts addressing the issue. *Please* don't be so quick to pull that trigger.

**Comment by shellscape** [comment]
And fwiw, for anyone else happening across this: gulp doesn't seem to play nice with `"sourceMaps": "inline"` and gulp-mocha. here's the configuration that belongs in the .babelrc file:

```json
  "env": {
    "development": {
      "sourceMaps": true
    }
  }
```

**Comment by phated** [comment]
@shellscape No, that is what we say to everyone that has a support question.  I'm locking this thread as you've already solved your own support question.
