### ISSUE TITLE
Tasks can't be generated with a loop

### ISSUE THREAD

**Issue by Dan503** [gulpjs/gulp#1581]
I have a series of tasks that are most easily created using a for loop:
```````````````````js
var task_array = ['one', 'two', 'three'];

//This doesn't work:
for (var i = 0; i < task_array.length; i++) {
	gulp.task(task_array[i], function() {
		return gulp.src('path/to/files')//etc
	});
};
```````````````````
When watching the console, it says that all the tasks fire when I use task_array as the dependency array on another task like so.
```````````````````js
gulp.task('another-task', task_array, function() {
	return gulp.src('path/to/files')//etc
});
```````````````````
However, only the last task actually runs.
```````````````````js
//loop is equivelent to this.
//"one" and "two" are visibly called in the console but do not take effect
gulp.task('three', function() {
	return gulp.src('path/to/files')//etc
});
``````````````````` 
If I separate the tasks out like this, it does work... it's really ugly though and less maintainable.
```````````````````js
function task_function(index){
    return gulp.src('path/to/files')//etc
}
gulp.task(task_array[0], function() {
	return task_function(0);
});
gulp.task(task_array[1], function() {
	return task_function(1);
});
gulp.task(task_array[2], function() {
	return task_function(2);
});
```````````````````

**Comment by ebuildy** [comment]
Looks like a closure issue, read about closure here: http://www.w3schools.com/js/js_function_closures.asp

**Comment by sholladay** [comment]
Yeah, the fundamental problem here is that any variable _references_ (as opposed to literal values) within that function you are passing to `gulp.task()` are going to end up in the state you would expect for the last iteration of the loop. If that is not the behavior you want, then the technical lingo for what you desire is a _new closure for each loop iteration_. You can use something like `task_array.forEach()` to achieve that. Or you can make a wrapper function that you call every time within the loop that carries out the desired logic.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  Looks like some people already helped out though.
