### ISSUE TITLE
Best way to check if stream is a vinyl stream

### ISSUE THREAD

**Issue by ORESoftware** [gulpjs/gulp#1582]
Here's a quick and dirty check to see if a stream is Node.js readable stream

```js
 isReadableStream: function isReadableStream(obj) {
        return obj instanceof stream.Stream && typeof obj._read === 'function' && typeof obj._readableState === 'object';
    }
```

are there a set of functions that Gulp uses internally to check if streams are vinyl streams and which type of vinyl streams? Need these checks for a lib I am writing, thanks

**Comment by phated** [comment]
Nope, a vinyl stream can be any type of node stream in object mode since we just pass vinyl objects through the streams. They aren't a custom type.
