### ISSUE TITLE
Gulp watch issue Error: watch null EPERM

### ISSUE THREAD

**Issue by jdnichollsc** [gulpjs/gulp#1583]
Hi guys,

Exist an issue with the **watch** method. See my gulpfile please: https://github.com/jdnichollsc/Ionic-Starter-Template/blob/master/gulpfile.js

The steps to reproduce the issue on Windows platform:
- Download the project
- Execute gulp watch in CLI
- Remove any empty folder in **./app/templates** or **./app/img**

- You can see the following error: ![Gulp issue](http://content.screencast.com/users/jdnichollsc/folders/Jing/media/a897208a-1aa1-45de-b902-c572ce0531c7/2016-03-27_1506.png)

Regards, Nicholls

**Comment by phated** [comment]
Duplicate of #651

**Comment by jdnichollsc** [comment]
But the issue #651 is closed, what is the solution? =)

**Comment by contra** [comment]
@jdnichollsc Solution is use the gulp 4 which has a different file watcher and suffers none of these issues

**Comment by jdnichollsc** [comment]
Thanks guys :+1:

**Comment by jdnichollsc** [comment]
any example with Gulp 4? :)

**Comment by s100** [comment]
But the latest version of Gulp is 3.9.1...?
