### ISSUE TITLE
gulp.dest failed sometimes

### ISSUE THREAD

**Issue by jecuendet** [gulpjs/gulp#1586]
In my gulpfile, I copy resources (font awesome) explicitely from bower_components/ to dist/
It works most of the time, but suddenly, it fails with the error message below. I'm pretty sure it's a timing issue, it arise more often on non-SSD disks. If I run it again directly, it works 99% of the time.

Error message:
> [08:35:58] Using gulpfile /home/git/cyber/prestations/template/front/gulpfile.js
> [08:35:58] Starting 'clean'...
> [08:35:58] Finished 'clean' after 2.95 ms
> [08:35:58] Starting 'default'...
> [08:35:58] Starting 'scripts'...
> [08:35:58] Starting 'partials'...
> [08:35:58] Starting 'copy-fa-fonts'...
> [08:35:58] Starting 'copy-kendo-img'...
> [08:35:58] Finished 'default' after 169 ms
> [08:35:58] fa-files1 bower_components/font-awesome/fonts/FontAwesome.otf
> [08:35:58] kendo-files1 bower_components/kendo/img/editor.png
> [08:35:58] fa-files1 bower_components/font-awesome/fonts/fontawesome-webfont.eot
> [08:35:58] kendo-files1 bower_components/kendo/img/imagebrowser.png
> [08:35:58] kendo-files2 dist/img/editor.png
> stream.js:74
>       throw er; // Unhandled stream error in pipe.
>       ^
> 
> Error: ENOENT: no such file or directory, stat
> '/home/git/cyber/prestations/template/front/dist/img/editor.png'
>     at Error (native)

gulpfile:
```javascript
//font-awesome
gulp.task('copy-fa-fonts', function () {
    return gulp.src(conf.wiredep.directory + '/font-awesome/fonts/*.{otf,eot,svg,ttf,woff,woff2}')
        .pipe(debug({title: 'fa-files1'}))
        .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')))
        .pipe(debug({title: 'fa-files2'}));
});

// Only applies for fonts from bower dependencies
// Custom fonts are handled by the "other" task
//gulp.task('fonts', ['copy-fa-fonts'], function () {
gulp.task('fonts', ['copy-fa-fonts'], function () {
    return gulp.src($.mainBowerFiles())
        .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
        .pipe($.flatten())
        .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});



//kendo-ui img
gulp.task('copy-kendo-img', function () {
    return gulp.src(conf.wiredep.directory + '/kendo/img/*')
        .pipe(debug({title: 'kendo-files1'}))
        .pipe(gulp.dest(path.join(conf.paths.dist, '/img/')))
        .pipe(debug({title: 'kendo-files2'}));;
});

gulp.task('other', ['copy-kendo-img'], function () {
    var fileFilter = $.filter(function (file) {
        return file.stat.isFile();
    });

    return gulp.src([
            path.join(conf.paths.src, '/**/*'),
            path.join('!' + conf.paths.src, '/**/*.{html,css,js}')
        ])
        .pipe(fileFilter)
        .pipe(gulp.dest(path.join(conf.paths.dist, '/')));
});

gulp.task('clean', function () {
    del([path.join(conf.paths.dist, '/'), path.join(conf.paths.tmp, '/')]);
});

gulp.task('build', ['html', 'fonts', 'other']);

```

Running with : gulp build

**Comment by phated** [comment]
Your clean task isn't signaling completion.  Support questions should be directed to StackOverflow.

**Comment by jecuendet** [comment]
Thanks a lot!
