### ISSUE TITLE
Gulpfile stopped working altogether

### ISSUE THREAD

**Issue by coljung** [gulpjs/gulp#1589]
A few weeks ago I created a local branch on a project to test Gulp. It was working fine back then, but now that I tried working on this again, I keep getting the following error:

[14:56:19] Using gulpfile ~/Documents/vagrant/HQ-Module/source/module-buyers/resources/hq-module-core/gulpfile.js
[14:56:19] Task 'default' is not in your gulpfile
[14:56:19] Please check the documentation for proper gulpfile formatting

Problem is that 'default' exists, i've trimmed down my file to this:

`var gulp = require('gulp');

gulp.task('default', function () { console.log('Hello Gulp!') });
`

And still it wont work. I'm baffled as to what is causing this behaviour, any ideas ?

**Comment by phated** [comment]
This is not enough information....  What is your global version, local version, did you remove node_modules, npm cache clean, reinstall, etc.

**Comment by coljung** [comment]
local version: gulp@3.9.1
global version: gulp@3.9.1
node_modules was completely removed
npm cache clean ran
i removed and reinstalled package a couple of times as well. 

Still, problem persists.

**Comment by coljung** [comment]
One thing though, if i run npm -v gulp, i get 2.14.7, but if i run npm list i get gulp@3.9.1.

So im a bit confused about this.

**Comment by coljung** [comment]
I basically reinstalled my whole project and now it works. Something somewhere i assume messed up gulp.
