### ISSUE TITLE
Gulp watch + tasks

### ISSUE THREAD

**Issue by ORESoftware** [gulpjs/gulp#1590]
Been struggling with this since The Beginning of using Gulp

I have a watcher, and when the event happens the callback is fired

```js
gulp.task('callback', function (cb) {
    watch('css/**/*.css', function () {
        gulp.src('css/**/*.css')
            .pipe(watch('css/**/*.css'))
            .on('end', cb);
    });
});
```

but really, I want to be able to run a Gulp task, before the watch callback is fired, something like this:

```js
gulp.task('callback', function (cb) {
    watch('css/**/*.css', ['some-gulp-task'],  function () {
        gulp.src('css/**/*.css')
            .pipe(watch('css/**/*.css'))
            .on('end', cb);
    });
});
```

is this possibly in the works for Gulp 4 ? It would make things much more convenient for us users. Thanks!

**Comment by phated** [comment]
This should already be fully supported in gulp 4 by using the gulp.series helper. I'm currently on my phone so can't give an example.

**Comment by phated** [comment]
Back at a computer.  It should look something like (although I'm not sure what your `watch` stream is):

```js
gulp.task('callback', function () {
    gulp.watch('css/**/*.css', gulp.series('some-gulp-task', function () {
        return gulp.src('css/**/*.css')
            .pipe(watch('css/**/*.css'))
    });
});
```

**Comment by ORESoftware** [comment]
Oh sweet that should help a lot
