### ISSUE TITLE
issue with gulp src not exist 

### ISSUE THREAD

**Issue by seeliang** [gulpjs/gulp#1596]
i am not sure i did it right, but if lintName point to a none exist folder,
it's not showing error 
```javascript 
 gulp.src([
      './node_modules/' + lintName + '/.scss-lint.yml',
      './node_modules/' + lintName + '/.eslintrc'
    ])
    .pipe( gulp.dest('./') );
```

**Comment by phated** [comment]
In gulp 4, this will throw an error.  In gulp 3, it will just succeed immediately because no files are passed through the stream.  Support questions should be directed to StackOverflow.

**Comment by seeliang** [comment]
thanks @phated
