### ISSUE TITLE
copyright's email's domain expired

### ISSUE THREAD

**Issue by cgcgbcbc** [gulpjs/gulp#1598]
the copyright in the license file is `Copyright (c) 2013-2016 Fractal <contact@wearefractal.com>
`
but godaddy states that `This domain name expired on 3/7/2016 and is pending renewal or deletion.`
<img width="778" alt="screen shot 2016-04-08 at 19 32 28" src="https://cloud.githubusercontent.com/assets/3320660/14382480/b49b9d6c-fdc0-11e5-8df6-776731b581c9.png">

**Comment by contra** [comment]
Not supposed to happen, working on it - thanks for the heads up
