### ISSUE TITLE
gulp.src is not processing globs properly

### ISSUE THREAD

**Issue by gmahomarf** [gulpjs/gulp#1600]
**EDIT 3: SEE NEXT COMMENT**

Given the glob ```build/*/``` and the following directory structure:

```
- gulpfile.js
- build/
  - dir1/
  - dir2/
  - dir3/
  - dir4/
  - 1.txt
  - 2.txt
  - 3.txt
  - 4.txt
```

I'm using ```gulp.src("build/*/")```, which should resolve to only the directories under ```build```, but gulp-debug shows it's actually resolving the glob to both directories and files under ```build```.

I tested with ```node-glob``` and ```glob-stream``` separately, and they both work properly. I have issues only when running with ```gulp```.

I've created a repo containing my test cases here: https://github.com/gmahomarf/gulp-blob-test

Here's the output for my test cases, which you can verify with the repo above:

```
 $ gulp
[09:21:19] Using gulpfile ~/Code/gulp-test/gulpfile.js
[09:21:19] Starting 'default'...
[09:21:19] gulp-debug: build/1.txt
[09:21:19] gulp-debug: build/2.txt
[09:21:19] gulp-debug: build/3.txt
[09:21:19] gulp-debug: build/4.txt
[09:21:19] gulp-debug: build/dir1
[09:21:19] gulp-debug: build/dir2
[09:21:19] gulp-debug: build/dir3
[09:21:19] gulp-debug: build/dir4
[09:21:19] gulp-debug: 8 items
[09:21:19] Finished 'default' after 58 ms

 $ node gulp
[09:21:26] gulp-debug: build/1.txt
[09:21:26] gulp-debug: build/2.txt
[09:21:26] gulp-debug: build/3.txt
[09:21:26] gulp-debug: build/4.txt
[09:21:26] gulp-debug: build/dir1
[09:21:26] gulp-debug: build/dir2
[09:21:26] gulp-debug: build/dir3
[09:21:26] gulp-debug: build/dir4
[09:21:26] gulp-debug: 8 items

 $ node glob
[ 'build/dir1/', 'build/dir2/', 'build/dir3/', 'build/dir4/' ]

 $ node stream
{ cwd: '/home/gazy/Code/gulp-test',
  base: '/home/gazy/Code/gulp-test/build/',
  path: '/home/gazy/Code/gulp-test/build/dir1/' }
{ cwd: '/home/gazy/Code/gulp-test',
  base: '/home/gazy/Code/gulp-test/build/',
  path: '/home/gazy/Code/gulp-test/build/dir2/' }
{ cwd: '/home/gazy/Code/gulp-test',
  base: '/home/gazy/Code/gulp-test/build/',
  path: '/home/gazy/Code/gulp-test/build/dir3/' }
{ cwd: '/home/gazy/Code/gulp-test',
  base: '/home/gazy/Code/gulp-test/build/',
  path: '/home/gazy/Code/gulp-test/build/dir4/' }
```
**EDIT:** I tried changing the arguments for ```gulp.src``` to ```['build/*/', '!build/{,*}.*']``` to explicitly ignore all files, but unfortunately that also ignores a couple of folders in my project that have dots in their name

**EDIT 2:** Added ```vinyl-fs``` to the list of tests, also working properly. Also added two extra dirs with dots in their name
```
 $ node vinyl
[10:22:38] gulp-debug: build/dir.1
[10:22:38] gulp-debug: build/dir.2
[10:22:38] gulp-debug: build/dir1
[10:22:38] gulp-debug: build/dir2
[10:22:38] gulp-debug: build/dir3
[10:22:38] gulp-debug: build/dir4
[10:22:38] gulp-debug: 6 items
```

**Comment by gmahomarf** [comment]
I finally traced the issue. It's an issue with the older versions of ```glob-stream```, which ```gulp``` uses via an old version of ```vinyl-fs```. The problem is this line https://github.com/gulpjs/glob-stream/blob/v3.1.18/index.js#L113

```.js
path.resolve('/some/path', 'build/*/') // results in "/some/path/build/*"
```

Is there any chance you can update the dependencies?

**Comment by waynebloss** [comment]
This has been addressed in issue  #1571

**Comment by gmahomarf** [comment]
@waynebloss how about you actually read my comment and leave the answering to the repo collaborators?

**Comment by waynebloss** [comment]
I did not read the whole entire thing. I see now where you mentioned #1571. Good luck to you.

**Comment by waynebloss** [comment]
I'm guessing #1486 would be relevant here too.

**Comment by phated** [comment]
Sorry, vinyl-fs has had many breaking changes and we can't update the dependency until gulp 4 to avoid breaking semver.  However, you can use vinyl-fs directly in your gulpfile by replacing `gulp.src` and `gulp.dest` with `vinylfs.src` and `vinylfs.dest` respectively, which would allow you to use the newer versions or you can upgrade to gulp 4.

**Comment by gmahomarf** [comment]
@phated Thanks, I endend up using ```vinyl.src```. Purely academic curiosity here: considering the error is in ```glob-stream``` and not in ```vinyl-fs```, would updating the ```glob-stream``` version only result in breaking changes?

**Comment by phated** [comment]
@gmahomarf we've done very small changes in vinyl 0.3.x in the past but it has lead to very messy PRs when other people submit them so we typically reserve it for extreme cases.
