### ISSUE TITLE
gulp multiple Watch task bundle into single task

### ISSUE THREAD

**Issue by ramitgarg** [gulpjs/gulp#1605]
Hello,

I am having a single gulpfile.js in which I have written build task. And I am having small-2 modules basis gulp file which generate module specific build. Now I have written gulp-watch statement in every module specific gulp task. 
Is it possible to call all watch command from main gulp file (gulpfile.js)?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by carmat** [comment]
A link to the SO question here would be helpful
