### ISSUE TITLE
gulp 4 cannot find gulp.parallel | gulp.series

### ISSUE THREAD

**Issue by zyf0330** [gulpjs/gulp#1606]
I use gulp 4, and there is an error showing "gulp.parallel is not a function".

I am here. @mikestreety 
`gulp -v` show
```
CLI version 1.2.1
Local version 3.9.1
```
This is my gulpfile, I delete some code and these code will cause the same result.
```
var fs = require('fs');
var _path = require('path');
var gulp = require('gulp')
var newer = require('gulp-newer');
var modify = require('gulp-modify');
var uglify = require('gulp-uglify')
var cleanCSS = require('gulp-clean-css');
var htmlmin = require('gulp-htmlmin');
var imagemin  = require('gulp-imagemin');

gulp.task('default', gulp.parallel(function () {
	console.log('finish')
}))
```

**Comment by Nirazul** [comment]
What makes you think that your version is gulp 4, when `Local version` says `3.9.1`?
Try updating local gulp to v4.

**Comment by zyf0330** [comment]
@Nirazul Because I done everything according to documentation.

**Comment by mikestreety** [comment]
@zyf0330 I've just re-followed my instructions here:  https://www.liquidlight.co.uk/blog/article/how-do-i-update-to-gulp-4/ (as per original issue raised)

And got the following:

```
[11:39:21] CLI version 1.2.1
[11:39:21] Local version 4.0.0-alpha.2
```

**Comment by zyf0330** [comment]
I just do as [getting started](https://github.com/gulpjs/gulp/blob/4.0/docs/getting-started.md)

**Comment by Nirazul** [comment]
`$ npm install --save-dev gulp` 
...will get you 3.9.1

`$ npm install gulpjs/gulp.git#4.0  --save-dev`
...did not work for me (zsh: no matches found), I had to write it in quotes:

`$ npm install 'gulpjs/gulp.git#4.0'  --save-dev`

**Comment by zyf0330** [comment]
Thanks. I know now, just misunderstood.

Nirazul <notifications@github.com>于2016年4月18日周一 下午7:08写道：

> $ npm install --save-dev gulp
> ...will get you 3.9.1
>
> $ npm install gulpjs/gulp.git#4.0 --save-dev
> ...did not work for me (zsh: no matches found), I had to write it in
> quotes:
>
> $ npm install 'gulpjs/gulp.git#4.0' --save-dev
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gulpjs/gulp/issues/1606#issuecomment-211330924>
>
-- 

追随

**Comment by mikestreety** [comment]
@Nirazul That's interesting. Thanks for pointing that out!

**Comment by zyf0330** [comment]
I use windows, and `npm install gulpjs/gulp.git#4.0 --save-dev` is useful.

Mike Street <notifications@github.com>于2016年4月18日周一 下午7:11写道：

> @Nirazul <https://github.com/Nirazul> That's interesting. Thanks for
> pointing that out!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gulpjs/gulp/issues/1606#issuecomment-211332820>
>
-- 

追随

**Comment by phated** [comment]
Support questions should be directed to StackOverflow

**Comment by xcatliu** [comment]
Why don't publish a 4.0-alpha version in npm?

**Comment by phated** [comment]
@xcatliu it looks like you missed https://github.com/gulpjs/gulp/issues/1486
