### ISSUE TITLE
Uninstall and install issues

### ISSUE THREAD

**Issue by jkinley** [gulpjs/gulp#1610]
I was updating gulp and followed the new instructions for removing the global gulp install and then installing gulp-cli. I did so and now I am getting errors during install and don't know what is going on. Attached is the log. Can someone please help? Thanks, Jeff
[npm-debug.txt](https://github.com/gulpjs/gulp/files/225076/npm-debug.txt)

**Comment by tmcgee123** [comment]
This actually happened to me when I was flipping between Gulp 3 and 4 multiple times. That directory gets locked up after npm install sometimes. You'll have to:

1. `rm -rf /usr/local/share/man/man1/gulp.1`
2. `npm rm --global gulp`
3. `npm install --global https://github.com/gulpjs/gulp.git#4.0`
4. This is non-standard I think, but I've found this works better for me than using the `npm install --global gulp-cli`, I'm not sure if this is correct as per @phated's docs but it's what I've had to do to run Gulp 4, so try this instead: `npm install --global https://github.com/gulpjs/gulp-cli.git#4.0`

That should get you what you need. After that, run `gulp -v` to see what versions you are on, mine is this:
[09:32:43] CLI version 0.4.0
[09:32:43] Local version 4.0.0-alpha.2

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  Plus, this is an npm issue.

@tmcgee123 the 4.0 branch on the gulp-cli repo is super out of date, please use the published version, which supports both gulp 3 and 4 and has many features and fixes since that branch was merged.  I am going to be removing it soon (next couple of days probably).

**Comment by tmcgee123** [comment]
Thanks @phated for the heads up. 👍

**Comment by moehammoud** [comment]
Cheers, @tmcgee123. Worked a treat.
