### ISSUE TITLE
is there a way to set root path?

### ISSUE THREAD

**Issue by zyf0330** [gulpjs/gulp#1611]
I want to set a root path for `gulp.src` and I just thought `options.base` can do this, but I am wrong.
And I don't find another way. Is it exists?

**Comment by tmcgee123** [comment]
If you look at [the node-glob documentation](https://github.com/isaacs/node-glob#options) you can see where to set root. 

Also, this is not an *issue*, you should probably try to ask questions like this on Gitter.

**Comment by zyf0330** [comment]
Thank you. I found it. And, I just didn't see something about what else
kind of object gulp.src can receive.

On Fri, Apr 22, 2016, 22:25 Tom M <notifications@github.com> wrote:

> If you look at the node-glob documentation
> <https://github.com/isaacs/node-glob#options> you can see where to set
> root.
>
> Also, this is not an *issue*, you should probably try to ask questions
> like this on Gitter.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gulpjs/gulp/issues/1611#issuecomment-213447634>
>
-- 

追随

**Comment by zyf0330** [comment]
I didn't know those about glob truly. I thought param of string or array just means the same systax with glob.

**Comment by tmcgee123** [comment]
Glad to help!

**Comment by stljeff1** [comment]
Next time, please state your solution for everyone else

**Comment by kungfooman** [comment]
Neither `--root` nor something like `gulp.src('src/test.js', { sourcemaps: true, root: '../..' })` seemed to work for me, so I just just moved my gulpfile into the root and moving on with more important issues :sweat_smile:
