### ISSUE TITLE
G4 - Did you forget to signal async completion?

### ISSUE THREAD

**Issue by joe-watkins** [gulpjs/gulp#1613]
Hello, in the process of transitioning from G3 to G4 and I've ran into a snag with one of my tasks. I've tried a standard function and `gulp.series()` with no luck. Both tasks bark out:

```
The following tasks did not complete: svg-2-png
[09:17:32] Did you forget to signal async completion?
```

Tasks:
``` javascript
function svg2png(done){
	return gulp.src(appDefaults.imagesDir+"/*.svg")
		.pipe(svg2png())
		.pipe(gulp.dest(appDefaults.imagesDir+'/fallbacks'));
		done();
}
```

``` javascript
gulp.task('svg2png', gulp.series(function(done){
	gulp.src(appDefaults.imagesDir+"/*.svg")
		.pipe(svg2png())
		.pipe(gulp.dest(appDefaults.imagesDir+'/fallbacks'));
		done();
}));
```

`gulp.task('svg-2-png',svg2png);`

I think this is going to be something documentation could help for folks like me moving from 3 to 4. I read blog posts about this but don't see any reference to done(); in readme ;)

**Comment by contra** [comment]
Just return the stream, you don't need to call the callback at all.

```js
function svg2png(){
    return gulp.src(appDefaults.imagesDir+"/*.svg")
        .pipe(svg2png())
        .pipe(gulp.dest(appDefaults.imagesDir+'/fallbacks'));
}
```

If you were doing something that didn't have a stream, you can use the callback to signal done instead of returning a stream. You never do more than one.

**Comment by joe-watkins** [comment]
@contra Thanks very much for the help but the same results occurred:

``` javascript
    function svg2png(){
      return gulp.src(appDefaults.imagesDir+"/*.svg")
        .pipe(svg2png())
        .pipe(gulp.dest(appDefaults.imagesDir+'/fallbacks'));
    }
```

```
[09:48:41] The following tasks did not complete: svg-2-png
[09:48:41] Did you forget to signal async completion?
```

**Comment by contra** [comment]
@joe-watkins Your stream isn't ending for some reason... strange

**Comment by doowb** [comment]
You're reusing the function inside itself:

![image](https://cloud.githubusercontent.com/assets/995160/14684733/56b311f6-06ff-11e6-801f-ce2f45ef639d.png)

**Comment by phated** [comment]
Please fix your JS as @doowb pointed out.

**Comment by jackesdavid** [comment]
Friends, this is workaround this issue:

We need to call the callback functions(Task and Anonimous

```
function electronTask(callbackA)
{
    return gulp.series(myFirstTask, mySeccondTask, (callbackB) =>
    {
        callbackA();
        callbackB();
    })();

}
```

**Comment by phated** [comment]
@jackesdavid that is not the appropriate fix.  Even if you improperly use those methods inside functions, you need to pass the `callbackA` to the invocation.
