### ISSUE TITLE
Feature Request: automatically guess matching task from shortest-unique-name-part

### ISSUE THREAD

**Issue by marc-portier** [gulpjs/gulp#1619]
Would be nice if I can make my tasks nicely descriptive, but still know that calling it can be shortened to the shortest leading string that uniquely matches one task.

So assuming these tasks:
- 'abc'
- 'afd'
- 'xyz'

one could
- gulp ab --> to lanuch 'abc'
- gulp af --> 'afd'
- gulp x --> 'xyz'
- gulp a --> error: ambiguous short version of task

Implementation could be based on something like the following
Assuming basic internal structure is TASKS = {name: task_function,...}

We could concvert the passed 'cmd' to the correct matching key with something like
function findTask(cmd) {
    if (TASKS.hasOwnProperty(cmd)) {return cmd;}
    //else
    var matches = Object.keys(TASKS).filter(function (key) { return key.indexOf(cmd) === 0});
    if (matches.length === 1) { return matches[0]};
    // else
    throw new Error(matches.length === 0 ? "no matching task" : "ambiguous tasks matching: " + matches.join('|'));
}

Haven't looked into the actual gulp code yet, but if this feature is considered useful I could be motivated to make a proper pull request - pointing me somewhat into the correct general direction is appreciated.

**Comment by phated** [comment]
We already support autocompletion and hitting tab isn't prohibitive so we aren't going to add this.
