### ISSUE TITLE
del module doesn't seem to work with unc server paths

### ISSUE THREAD

**Issue by kbli** [gulpjs/gulp#1620]
The following works with the drive letter of the a mapped network drive specified:

```
gulp.task('clean', function() {
  return del([
    "S:/path/to/files/css/*.css",
    "S:/path/to/files/js/*.js",
  ], {force: true});
});
```

But the //servername/ server paths fail. There are no errors, but the files do not get deleted.

```
gulp.task('clean', function() {
  return del([
    "//servername/path/to/files/css/*.css",
    "//servername/path/to/files/js/*.js",
  ], {force: true});
});
```

**Comment by mcacek** [comment]
This sounds like an issue with del rather than with gulp. https://github.com/sindresorhus/del/issues/35

**Comment by contra** [comment]
That ^
