### ISSUE TITLE
[PROPOSAL] New plugin creation method

### ISSUE THREAD

**Issue by zozzz** [gulpjs/gulp#1621]
Hi!

I have an idea if you're deprecate the ``gulp-util`` module. This idea will help solve a couple of problems I've read here, such as logging. The point is that of ``gulp`` providing a uniform API that allows more information is available, when the logging occurs and maintain the backward compatibility.

So the proposal is the following:

#### New plugin creation method

before:

```javascript
module.exports = function concat(options) {
	// don't available any contextual information
	require("gulp-util").log("...");
};
```

after:

```javascript
module.exports = gulp.plugin(function concat() {
	// this is produce something like in top level logger
	// log("error", "Missing xy parameter..", {pluginName:"concat", taskName:"..."})
	this.log.error("Missing xy parameter..")

	// maybe rename this.throught -> this.transform
	// and provide additional methods like this.filter etc...
	var stream = this.through(function() {
		// log("error", "Can't read file: ...", {pluginName:"concat", taskName:"..."})
		this.log.error("Can't read file: ...")

		// log("error", "Can't read file: {file}", {
		// 	pluginName:"concat",
		// 	taskName:"...",
		// 	file: "..."
		// })
		this.log.error("Can't read file: {file}", {file:"..."});

		// log("error", "Syntax error", {
		// 	pluginName: "contact",
		// 	taskName: "someTask",
		// 	details: [...]
		// })
		this.log.error("Syntax error", {
			details: [/*...*/]
		});
	});

	// maybe do something with stream...

	return stream;
});
```

> Maybe you notice the ``this.through`` code snippet. This is not mandatory,
  but i think this is a good ide, because the 90% of the gulp plugins is using this
  module to transform the stream... [see](https://www.npmjs.com/browse/depended/through2)

backward compatibility issues:

``gulp-util`` module exports a log method that mimics the old behavior. This method
is not so clever to provide contextual information, but this is the best ide until
rewrite the plugin.

#### Task registering & executing

```javascript
// so this is uncahnged, but behinde the scenes:
//
// when task function is called prepare for the right task
// context and make a local reference in the concat plugin
// so concat plugin currently knows which task is called
gulp.task(function someTask() {
	return gulp.src("...")
		.pipe(concat());
});
```

> This is maybe bereak some undertaker CustomRegistry example

#### Create new contextual plugin

```javascript
gulp.contextPlugin(function log(ctxClass) {
	// factory function
	return function(ctx) {
		return new Logger({
			taskName: ctx.taskName,
			pluginName: ctx.pluginName
		});
	}
});

// or give more options, but i think this is too complicated
// maybe anough a factory function like above example.
gulp.contextPlugin(function(ctxClass) {
	var symbol = Symbol("log");
	Object.defineProperty(ctxClass.prototype, "log", {
		get: function() {
			if (!this[symbol]) {
				this[symbol] = new Logger({
					taskName: this.taskName,
					pluginName: this.pluginName
				});
			}
			return this[symbol];
		}
	});

	return {
		init: function(newCtxClass) {
			newCtxClass.prototype[symbol] = null;
		}
	};
});
```

Here is an example that basically implement the above idea:
[proposal](https://gist.github.com/zozzz/5fcb0a6824d02cc70e149b435866cbc1)

**Comment by phated** [comment]
The benefit of gulp plugins is that they are just node streams and don't actually have context related to gulp and that is __by design__.  The deprecation of `gulp-util` doesn't mean that utility modules won't be available (see [gulplog](https://www.npmjs.com/package/gulplog)) but that we don't want people to use a massive grab-bag of modules when they only need 1 method (like PluginError)
