### ISSUE TITLE
install error in nodejs 6.0

### ISSUE THREAD

**Issue by yreenchan** [gulpjs/gulp#1622]
After I upgrade node to 6.0, I got error when install gulp
![err](https://cloud.githubusercontent.com/assets/3251726/14878284/2b64c5ba-0d55-11e6-9a0b-d5131c7ea3b7.jpg)

**Comment by phated** [comment]
Not a gulp problem, it's an npm problem.

**Comment by yreenchan** [comment]
so how can I solved it?

**Comment by callumacrae** [comment]
> If you need help, you may report this error at:
> <https://github.com/npm/npm/issues>
