### ISSUE TITLE
v4 watch now runs one time and no more in some cases

### ISSUE THREAD

**Issue by rosskevin** [gulpjs/gulp#1624]
Commit: https://github.com/gulpjs/gulp/commit/6c03475e1a39d18c139b4d56baa1c14a587f9f4a

I apologize in advance for this terrible issue report, I've been chasing this for hours and I'm afraid I have little to share, but I hope in the end someone can point me in the general direction of my error.

I had no problems until I pulled the latest, I generally stay up to date.  Both gulp and gulp-cli are the lates.

I note from the ^^^commit a few others have seen the same change break their code.  It is likely to be improper use, but I'm not spotting it in my code.

I created a test case and have been unable to reproduce:
https://github.com/alienfast/gulp-pipeline/tree/master/test/watch-repeated

This test case works fine, both in the `simple` form and with the gulp-pipeline `recipe` form.

The case where it doesn't work is in when using an [`Aggregate`](https://github.com/alienfast/gulp-pipeline/blob/master/src/aggregate.js#L94), which does some task generation and surely this is the most likely place for my error.

What I can say, definitively, is that the file watcher is triggering [and I receive those events](https://github.com/alienfast/gulp-pipeline/blob/master/src/aggregate.js#L142), but inside `glob-watcher` [`#runComplete`](https://github.com/gulpjs/glob-watcher/blob/master/index.js#L32) is never run again (after the first run).

Since `#runComplete` is never run, what error would that indicate in my use?  Missing passing through the `done`?

**Comment by phated** [comment]
Aggregate is really complex, but I'm guessing the problem is that you don't return the `this.taskFn` result at https://github.com/alienfast/gulp-pipeline/blob/master/src/aggregate.js#L123 which means returning a stream doesn't actually get passed to gulp.  I highly recommend you simplify.

**Comment by phated** [comment]
This is essentially the same problem and solution as https://github.com/gulpjs/gulp/issues/1623#issuecomment-215847959

The behavior was inconsistent between `gulp.task` and `gulp.watch` and by normalizing it, it has highlighted that many people were actually writing code that wasn't working correctly.

**Comment by rosskevin** [comment]
Thanks @phated, I had tried the return there but not in a deliberate manner so I pulled it.  I just re-checked it (and committed it), same behavior.

But I get what you are saying, I'll look to see if there is an opportunity to make it simpler.  My other thought was a coding error in my [parallel](https://github.com/alienfast/gulp-pipeline/blob/master/src/util/parallel.js) and [series](https://github.com/alienfast/gulp-pipeline/blob/master/src/util/series.js) helpers, which are essential parts to using the Aggregate.

Thanks again for looking.

**Comment by rosskevin** [comment]
@phated - would it be possible to implement a paranoid check in the code so that these types of user errors are obvious?  I'm a fan of the break early and often, perhaps we could check return values and blow up if it isn't a stream, promise, etc?

**Comment by phated** [comment]
We have a warning message when you run a task without watch but I don't know how to adapt it for watch. Afk right now, sorry I can't link the cli code

**Comment by rosskevin** [comment]
I may have found the issue: 
adding watches: https://github.com/alienfast/gulp-pipeline/blob/master/src/aggregate.js#L81
single task i.e. `css:watch` https://github.com/alienfast/gulp-pipeline/blob/master/src/aggregate.js#L91

The thing is, an Aggregate has `n` tasks, and the great thing about it is it registers watches for all of the tasks, and if any change, it runs the aggregate (whatever set of series or parallel).

You can see I don't return a value from `watchFn`, because I'm actually registering say 4 watches and don't know which to return.

Any thoughts on that?

**Comment by phated** [comment]
Your watch function isn't async. Everything must be async in gulp 4. This is the behavior that wasn't normalized until now.

**Comment by rosskevin** [comment]
I tried running multiple watches in a few ways within the task, no success.  Ultimately I aggregated the globs for a single call to `gulp.watch`.  While that isn't foolproof, it is _much_ simpler.

Thank you

**Comment by phated** [comment]
@rosskevin glad you got something working.  To be clear, it is not a problem with multiple watches, but instead a problem with you not having an async watch task that proxied to your other tasks.  When you wrap functions you should always call them with the same arguments as the wrapper and return the result from the wrapper.

**Comment by rosskevin** [comment]
Agreed. I tried but failed miserably.  I just bumped into another case where I want to do something similar.

How could you run 3 watches from a single registered task and have it return properly?  The readme has a sample but I see it doesn't return either, does it?

```javascript
function watch() {
  gulp.watch(paths.scripts.src, scripts);
  gulp.watch(paths.styles.src, styles);
}
```

**Comment by phated** [comment]
You should just be able to receive and call the `done` callback. All the examples haven't been updated yet.
