### ISSUE TITLE
Is gulp 4 ever going to be released?

### ISSUE THREAD

**Issue by sleaze** [gulpjs/gulp#1629]
I wanted to reply to https://github.com/gulpjs/gulp/issues/96 but it is locked!

The current tip and 4 branch seem to have diverged quite a bit with regard to commits..

Is there a plan to actually get series 4 out into the real world at a specific point in time?

Thanks,

MR. SLEAZE

**Comment by phated** [comment]
Please stop opening issues about this. It will be released when completed.
