### ISSUE TITLE
Error while installing gulp 3.9.1

### ISSUE THREAD

**Issue by cbmadhu** [gulpjs/gulp#1630]
Hi
I am facing below error while installing gulp@3.9.1. Please let me know how to resolve this

Node version is : V4.4.2
npm Version is : 2.15.0

Madhus-MacBook-Pro:Gulp_Workspace root# npm install –g gulp@3.9.1
npm WARN package.json Gulp_Workspace@1.0.0 No description
npm WARN package.json Gulp_Workspace@1.0.0 No repository field.
npm WARN package.json Gulp_Workspace@1.0.0 No README data
npm ERR! addLocal Could not install /Users/MadhuSangee/Documents/workspace/Gulp_Workspace/–g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "–g" "gulp@3.9.1"
npm ERR! node v4.4.2
npm ERR! npm v2.15.0
npm ERR! The header content contains invalid characters
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

**Comment by phated** [comment]
npm problem, not a gulp problem.
