### ISSUE TITLE
I want to see an error message for gulp.src if I don't satisfy the conventions

### ISSUE THREAD

**Issue by BirgitPohl** [gulpjs/gulp#1633]
I was trying out gulp and I was trying to make compiling coffee to js work for two days. This was my initial code for that purpose.
```coffee
gulp.src "#{sourcePath}*.coffee"
    .pipe coffee bare: true
    .pipe concat "test.js"
    .pipe gulp.dest "#{targetPath}"
    .on 'error', gutil.log, 'change', browserSync.stream, 'end', gutil.log successColor ['watch']
  gutil.log successColor "Successfully updated a file here: " + detailsColor "#{targetPath}"
```
But I realized that when I add a watcher or even a browser sync that the task never ends - meaning it can only be triggered once.

Why so? Because the on method and also the gutil.log function seem to break it without triggering an error.
It can only look like this:

``` coffee
gulp.task 'write-coffee', ->
  gulp.src(sources.coffee)
  .pipe(coffee({bare: true}).on('error', gutil.log, 'end', gutil.log logColor.success "Successfully updated a file here: " + logColor.detail "#{targets.js}"))
  .pipe(concat('app.js'))
  .pipe(gulp.dest(targets.js))
  #If gutil.log or console.log comes after this, the function never finished. It will trigger once, but not many times.
```
Figuring it out took a long time, so I request an error message so that I can avoid this issue.
Issues like: "Gulp is doing nothing" or "Task is triggered only once" which I found on the internet will be prevented. ;-)

**Comment by phated** [comment]
What are you doing with the event handlers.  This is just completely incorrect node code.

**Comment by BirgitPohl** [comment]
The second one is incorrect as well?

Well, that is not the point.
The point is, that the method .src doesn't even show it that this is wrong.

**Comment by phated** [comment]
No, that is the point.  You aren't writing proper node code, so how are we supposed to error correctly?  We have a long history of errors being propagated correctly so fix your code and it will work.  Further support questions should be directed to StackOverflow.
