### ISSUE TITLE
No defered resolution of named tasks

### ISSUE THREAD

**Issue by mathflair** [gulpjs/gulp#1635]
In the prior version of Gulp, I could have a named task as a dependency even though the file that declared the task hadn't yet been required. Now, I get an error as soon as task.parallel or task.serial is called, even though the named task will be defined later.

This is especially annoying as it forces me to enforced ordered requiring of my task files, instead of just being able to require the directory.

**Comment by phated** [comment]
This was a design decision to get people to use named function instead of magic strings.  If you are unwilling to update your code, you can use https://github.com/gulpjs/undertaker-forward-reference
