### ISSUE TITLE
on("end", fn ()) does not appear to be working correctly

### ISSUE THREAD

**Issue by jbblanchet** [gulpjs/gulp#1637]
Someone raised an issue in gulp-jasmine (sindresorhus/gulp-jasmine#69) about the end event, and it seems to be caused by gulp:

```javascript
gulp.task("default", function (callback) {
    gulp.src("test.spec.js")
        .on("end", function () {
            console.log("We're done!");
            callback();
        });
});
```

works with gulp@3.7 but stopped working with gulp@3.8.

Returning the pipe:

```javascript
gulp.task("default", function () {
    return gulp.src("test.spec.js")
        .on("end", function () {
            console.log("We're done!");
        });
});
```

works as expected. Not sure if I'm missing something (I rarely use callbacks).

**Comment by phated** [comment]
This is how streams work.  How does it end if you aren't piping it somewhere?  The reason it works when you return it is because the underlying library (orchestrator) attaches an `on('data')` handler which causes the stream to flow.

**Comment by jbblanchet** [comment]
Thanks for the quick answer.

Maybe I simplified my example too much (but there was still a difference in behaviour between 3.7 and 3.8). How about this example:

```javascript
var gulp = require("gulp");
var through = require("through2");

var foo = through.obj(function (file, enc, cb) {
    console.log(file);
    cb(null, file);
});

gulp.task("default", function (cb) {
    gulp.src("test.spec.js")
        .pipe(foo)
        .on("end", function () {
            console.log("We're done!");
            cb();
        });
});
```

**Comment by phated** [comment]
Technically a stream that ends with a transform stream (through2) won't end either.  You have to end on a Writable stream.  I'm also wondering why you aren't using 3.9.1

**Comment by jbblanchet** [comment]
I am using 3.9.1, I'm trying to understand why code that worked in 3.7 doesn't work anymore, and 3.8 is the version where it stopped working.

My understanding from what you're saying is that the end event is only emitted by the drain (i.e. gulp.dest), so I'll have to force and emit.end() in the flush callback to simulate that, since gulp-jasmine is never really writing anything.

**Comment by phated** [comment]
You can return your stream or attach a noop `on('data')` handler.

**Comment by jbblanchet** [comment]
I pretty much always return my streams, but I need a generic solution for gulp-jasmine. Emitting the 'end' event in the flush function did the trick. Thanks for taking the time to help me.

**Comment by phated** [comment]
@jbblanchet that's a really bad way to solve the problem.  I think you want to change your transform stream into a writable, otherwise you have to do a ton of hackery like we had to do in vinyl-fs
