### ISSUE TITLE
gulp.watch only calls associated function on first change to files watched, does not call on subsequent changes.

### ISSUE THREAD

**Issue by joshuarussell76** [gulpjs/gulp#1638]
It appears that the 6c03475e1a39d18c139b4d56baa1c14a587f9f4a commit has broken gulp.watch such that a function associated with a watch is only called on the first change to the watched files. Subsequent changes to the watched files do not result in the function being called.
We did create a sample project to reduce complexity and isolated the issue to this commit.

**Comment by phated** [comment]
Please search the issue tracker before opening an issue. This has already been opened 3 times.

**Comment by alexisdiel** [comment]
For new users that found this thread by google...

Add the **done** as parameter at the last task and callback at the end.

> gulp.task("reload", (done) => { browserSync.reload(); done(); });
> gulp.task("js:watch", () => gulp.watch("lib/**/*.js", gulp.series("js", "reload")));
