### ISSUE TITLE
Gulp 4.0 gulp.src no cwd options

### ISSUE THREAD

**Issue by xiaoyu2er** [gulpjs/gulp#1639]
why gulp 4.0 remove the cwd options in gulp.src? It's pretty convenient.

**Comment by phated** [comment]
This option is still available, though it might have been omitted from the 4.0 docs during updates.  The docs need a major overhaul.  Please see https://github.com/gulpjs/vinyl-fs#options for full documentation in the meantime.

**Comment by xiaoyu2er** [comment]
@phated Thanks a lot !
