### ISSUE TITLE
Intermittent watching based on relative vs absolute path.

### ISSUE THREAD

**Issue by Panguino** [gulpjs/gulp#1641]
When using a path that starts at C:\folder\folder etc to watch a file, instead of a relative path the watch.gulp will Intermittently not detect file updates.  The only difference between the 2 ways I have tried to reproduce this issue on my project is relative vs absolute path.  Any thoughts to why this is happening or a workaround?  I will need to be able to use absolute paths.

Cheers,

**Comment by smalllong** [comment]
The gulp.dest is also not work when using absolute path. Any idea why?
