### ISSUE TITLE
Gulp 4 symlinked gulpfile.js

### ISSUE THREAD

**Issue by supernovus** [gulpjs/gulp#1646]
I've been using gulp 4 for a while, and I love it. Up until now I've had no problems using a common gulpfile for a bunch of different projects, it's simple symlinked into each project that uses it from a 'common' project that has a bunch of shared resources in it. 

I updated all of my node_modules today after a node.js upgrade, and now when I try to use gulp against the symlinked gulpfile.js I get an error:

[10:40:09] Using gulpfile /system/docs/dev/common/gulpfile.js
[10:40:09] Task never defined: default
[10:40:09] To list available tasks, try running: gulp --tasks

If I go into the 'common' project where the gulpfile is not a symlink, it works fine, so there's nothing wrong with the gulpfile itself. It would appear something has changed in how gulp handles symlinks.

What's going on, and how can this be fixed or worked around without making an individual copy of the gulpfile into each project (which is a terrible option, but one that I will use if I have to.)

**Comment by phated** [comment]
You have not provided enough information, need versions of everything, etc.

**Comment by supernovus** [comment]
Sorry about that, the newest versions as of today.

$ gulp -v
[10:55:21] CLI version 0.4.0
[10:55:21] Local version 4.0.0-alpha.2
$ node -v
v6.0.0

As it only started exhibiting this behavior after the updates today, I figured it had to have been a relatively recent change.

**Comment by phated** [comment]
You are using a super old version of gulp-cli.  Please upgrade to the published version of https://www.npmjs.com/package/gulp-cli

**Comment by supernovus** [comment]
Oh, the instructions I found for how to install gulp 4.0 said to use the version specifically tagged, so I've been using "npm install -g "gulpjs/gulp-cli#4.0" to install it. I'll switch back to the gulp-cli package I had before which I was using with gulp 3.x

**Comment by supernovus** [comment]
I'm now using:
$ gulp -v
[11:06:02] CLI version 1.2.1
[11:06:02] Local version 4.0.0-alpha.2

And it's acting the same way. If I use a gulpfile.js that is a "real file", it works perfectly. As soon as I use one that is a symbolic link, it shows no tasks registered.

Here's the output of gulp --tasks from the 'common' folder:

$ gulp --tasks
[11:08:23] Tasks for /system/docs/dev/common/gulpfile.js
[11:08:23] ├─┬ build
[11:08:23] │ └─┬ <series>
[11:08:23] │   ├── build-js
[11:08:23] │   └── build-css
[11:08:23] ├── build-css
[11:08:23] ├── build-js
[11:08:23] ├─┬ clean
[11:08:23] │ └─┬ <parallel>
[11:08:23] │   ├── clean-js
[11:08:23] │   └── clean-css
[11:08:23] ├── clean-css
[11:08:23] ├── clean-js
[11:08:23] ├─┬ default
[11:08:23] │ └─┬ <series>
[11:08:23] │   └─┬ build
[11:08:23] │     └─┬ <series>
[11:08:23] │       ├── build-js
[11:08:23] │       └── build-css
[11:08:23] ├─┬ rebuild
[11:08:23] │ └─┬ <series>
[11:08:23] │   ├─┬ clean
[11:08:23] │   │ └─┬ <parallel>
[11:08:23] │   │   ├── clean-js
[11:08:23] │   │   └── clean-css
[11:08:23] │   └─┬ build
[11:08:23] │     └─┬ <series>
[11:08:23] │       ├── build-js
[11:08:23] │       └── build-css
[11:08:23] ├─┬ watch
[11:08:23] │ └─┬ <parallel>
[11:08:23] │   ├── watch-js
[11:08:23] │   └── watch-css
[11:08:23] ├── watch-css
[11:08:23] └── watch-js

And here's the output of the same command from one of the project folders (with the symlink)

$ gulp --tasks
[11:07:46] Tasks for /system/docs/dev/common/gulpfile.js

I'm going to run an strace on both and see if I can see what's going on.

**Comment by phated** [comment]
Instead of using a symlink, why don't you use the `--gulpfile` flag?

**Comment by phated** [comment]
Symlinks are still supported in Liftoff (see https://github.com/js-cli/js-liftoff/blob/master/index.js#L81-L84) unless node 6 changed something...

**Comment by supernovus** [comment]
The automated system which updates the various packages from git checks for the presence of certain files, such as 'gulpfile.js' , 'Gruntfile.js', 'Makefile', etc. to determine if that particular project uses a particular build system, and then runs 'gulp', 'grunt', or 'make' depending on the presence of the file.

Actually, the server which uses the automated system is a different OS than my machine, and is using node 'v5.11.0' but the same versions of 'gulp' and 'gulp-cli' and it does not appear to be experiencing this problem, so I'm wondering if it's specific to node 6.0 or one of the node_modules that I had to rebuild on my local machine today after upgrading node.

If I use "gulp --gulpfile ../common/gulpfile.js" on my local machine, it works properly. I'll want to set up an alias, as that's a bit of a handful to be typing every time.

**Comment by phated** [comment]
Definitely seems like a platform thing.  Going to close this but feel free to drop any followup information here; I'll keep an eye out.

**Comment by supernovus** [comment]
I am continuing to try to figure this out, as there is another problem I've found with using the --gulpfile flag. If I use --gulpfile, it doesn't actually operate in my current working directory, but changes to the directory where the gulpfile is, which completely defeats the purpose entirely (as it's not working on the source files in the project folder, but on the source files in the common folder.) I as of now, have no way to recompile on my local machine without hard copying the files into the folder, which is going to be a pain that I'll have to work around. I am going to attempt upgrading everything again to see if that helps.

**Comment by frontyard** [comment]
Is there a recommended way to use single gulpfile.js across several modules/directories? I've tried symlinks, I've tried setting --gulpfile. I've even tried explicitly setting --cwd. None of these make any difference, gulp uses makes directory where gulpfile is it's working directory, which makes it impossible to put gulpfile.js anywhere other then directory that needs to be built.
