### ISSUE TITLE
Error: Cannot find module 'orchestrator' when node_modules is a symlink

### ISSUE THREAD

**Issue by COLABORATI** [gulpjs/gulp#1648]
I would like to put ```node_modules``` in a tmp directory and symlink to it from the actual working directory, to save lots of disk space wasted by gazillion of little files when working with many projects that need the same set of modules. But when I do this I get 
```Error: Cannot find module 'orchestrator'```
This only happens when symlinking to the node_modules directory, not when this directory is a real one.
This looks like some module loading code does not like symlinks (on linux). 
It would be great if that could be resolved, thanks for your attention!

**Comment by phated** [comment]
This is a node issue.

**Comment by COLABORATI** [comment]
Are you sure? Would you please link me to any document that gives some more information about this issue, especially I would be very interested in how to _solve_ this problem.

Thank you very much for your attention!

**Comment by COLABORATI** [comment]
For my special situation https://github.com/npm/npm/issues/10013#issuecomment-189176273 was the solution!

**Comment by COLABORATI** [comment]
However, this is not a solution - file system features of the underlying operating system should not be a problem for an application like gulp. Please re-open this issue until the problem is solved, thanks.

**Comment by callumacrae** [comment]
What do you propose we do to fix it, and why do you think it should be part of gulp itself?

**Comment by williansmartins** [comment]
Guys, I'm late, but This happen with me, and I after I read a lot of thing that not help me, I re-install the gulp... just this, and it is ok
