### ISSUE TITLE
Can't exclude directories using src glob

### ISSUE THREAD

**Issue by aaronbushnell** [gulpjs/gulp#165]
I can't exclude a directory from being copied over when using a src glob. Here's my task:

``` js
gulp.task('copy', function() {
    return gulp.src(['app/**', '!app/_tmp/**'])
        .pipe(gulp.dest('dist'));
});
```

Gulp copies over `app/**`, but `app/_tmp/` is still being copied.

Expected:

``` sh
+ app/
  + tmp/
      file1
      file2
  + css/
      styles.css
  + js/
      app.js
+ dist/
  + css/
      styles.css
  + js/
      app.js
```

Gulp output:

``` sh
+ app/
  + tmp/
      file1
      file2
  + css/
      styles.css
  + js/
      app.js
+ dist/
  + tmp/
  + css/
      styles.css
  + js/
      app.js
```

**Update**: Clarified that the `dist/_tmp/` directory does not contain any files

**Comment by ktstowell** [comment]
`['!node_modules', '!node_modules/**', './**']` Worked for me, though I do like @aaronbushnell 's proposition in https://github.com/isaacs/minimatch/issues/25

**Comment by alexpi** [comment]
I want to match everything except bower_components and anything inside. 
So, I used the following code as suggested, but this still matches any folder that has .html files inside, together with those files.
``` javascript
return gulp.src([
        'src/*',
        '!src/bower_components{,/**}'
    ]
```

Any suggestions?

**Comment by stryju** [comment]
@alexpi this pattern will include the folders containing the html files, but should exclude the html files themselves - is that the case?

**Comment by alexpi** [comment]
@stryju This pattern keeps .html files and the bower_components subfolders that contain them, which is not what I need.
I want to match .html files that reside in src/, but exclude the bower_components folder, its subfolders, and anything inside them, including .html files.

**Comment by alexpi** [comment]
Sorry! There was no issue after all, another Gulp task was the culprit. The code works as expected.

**Comment by hermeslm** [comment]
Thanks to gfloyd, that solution works.

**Comment by zeshanshani** [comment]
Thank you, @ktstowell, your solution worked really well. I'm working with Gulp Zip. It was really cumbersome to exclude a few folders/files and keep everything else including the project tree as it is. 

Here's my code:

``` JS
var gulp             = require( 'gulp' ),
    zip              = require( 'gulp-zip' );

gulp.task( 'zip', function() {

  return gulp.src( [
    '!{.gitignore,sftp-config.json}',
    '!node_modules', '!node_modules/**',
    '!dist', '!dist/**',
    '!assets/bower_components', '!assets/bower_components/**',
    './**',
  ] )
    .pipe( zip('archive.zip') )
    .pipe( gulp.dest( 'dist' ) );

});

**Comment by acauamontiel** [comment]
This works well for me:
```javascript
gulp.src(['app/**', '!app/_tmp{,/**/*}'])
```

**Comment by vmasto** [comment]
Just as a note, I used to use:

```
gulp.src([
  '!node_modules{,/**}',
  '!dist{,/**}'
])
```

But then converting it to:

```
gulp.src([
  '!node_modules',
  '!node_modules/**',
  '!dist',
  '!dist/**'
])
```

Shaved off at least *3 whole seconds* from my task. 
Just a heads up, you might want to test your task if you care about performance; it would appear the `dir{**}` notation is really slow.

**Comment by npineda** [comment]
I was calling a folder above and copying all it's content expect from the folder I was currently inside(called "deploy"). This worked for me - gulp.src(['../**/*','!../deploy','!../deploy/**']).

**Comment by kennygfunk** [comment]
Read through this thread and tried a bunch of things but still directories are copying over. I want to exclude ALL of /src but src/images/sub-directory ends up getting copied albeit empty.

```
gulp.src([
    'dev/wordpress/**/*',
    'dev/wordpress/**/.*',
    '!dev/wordpress/wp-content/themes/lucidworks/src{,/**/*}',
  ])
    .pipe(gulp.dest(myDest));
```


I end up with:
```
src/images/sub-directory/(empty)
src/fonts/(empty)
```
Using gulp babel. Any ideas?

**Comment by Triloworld** [comment]
There is one line solution. It is great when glob need to be apply relative:

> @import "../../!(web)/**/*.scss";

It import: 

- ../../name/x.scss
- ../../name/name/x.scss
- ../../name/web/x.scss
- ../../name/web/web/x.scss

Don't import:

- ../../web/x.scss
- ../../web/name/x.scss

So it basically work as one level directory exclude.
It can be even something like this:

- ../../!(web)/!(web)/**/.scss

Important: It won't work if added AFTER '**'. Like this one: ../../**/!(web)/*.scss (how to choose on what level directory exclude when multilevel are included?)
