### ISSUE TITLE
Requiring external module babel-register

### ISSUE THREAD

**Issue by frapweb** [gulpjs/gulp#1650]
hi there,

everything i tried i run in the same problem.
first i started with node4lts, uninstalled my local and global gulp 3x updated npm even a reboot and reinstalled with gulp4. this was the beginning when i got module babel-register many hours ago. i now even uninstalled my whole node system, deleted the /usr/local/lib/node_module folder, installed latest nodejs 6 with latest gulp4 - nothing same problem. is there any solution known to get gulp 4 running ?

  aweseome-gulp-starter git:(master) ✗ gulp -v
[01:26:24] Requiring external module babel-register
[01:26:24] CLI version 1.2.1
[01:26:24] Local version 4.0.0-alpha.2

  aweseome-gulp-starter git:(master) ✗ node -v
v6.1.0
...
{
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-register": "^6.8.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-babel": "^6.1.2",
    "gulp-eslint": "^2.0.0",
    "require-dir": "^0.3.0"
  },
}

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
