### ISSUE TITLE
gulp.series only do the first task

### ISSUE THREAD

**Issue by jeodiong** [gulpjs/gulp#1651]
```
function clean(){
  return console.log('1');
}

function build(){
  return console.log('2');
}

gulp.task(clean);
gulp.task(build);
gulp.task('clean-build', gulp.series(clean, build));
```
➜  myPro git:(master) ✗ gulp clean-build
[23:20:08] Failed to load external module coffee-script/register
[23:20:12] Using gulpfile ~/Documents/html/myPro/gulpfile.js
[23:20:12] Starting 'clean-build'...
[23:20:12] Starting 'clean'...
1
[23:20:12] The following tasks did not complete: clean-build, clean
[23:20:12] Did you forget to signal async completion?

**Comment by webdesserts** [comment]
Notice the last line `Did you forget to signal async completion?`. Gulp 4.0 now requires all tasks to be async. This means you either need to return a Promise, a Stream, or call a callback when your done. In your example you would do the following:

```
function clean(done){
  console.log('1');
  done();
}

function build(done){
  console.log('2');
  done();
}

```

**Comment by phated** [comment]
Excellent breakdown of this @webdesserts - I think this has sufficiently been answered.

**Comment by jeodiong** [comment]
@webdesserts thanks

**Comment by webdesserts** [comment]
@jeodiong just realized that I never included the link to that thread I was talking about 🙃 [here you go](https://github.com/robrich/orchestrator/issues/29)
