### ISSUE TITLE
gulp.watch not logging correctly when using imported functions

### ISSUE THREAD

**Issue by alexandernanberg** [gulpjs/gulp#1656]
So my setup is a bit special so it could be a problem from my part and not the gulp core. The problem I'm having is that the gulp.watch isn't logging when running tasks or finishing them. Although the tasks are  transpiling/compiling correctly. I suspect that there is some problem with the assigning of `this.name = 'taskname'` inside the task functions?

I'm using gulp-cli 1.2.1 and gulp 4.0.0-alpha.2.

**gulpfile.js**
```
const gulp = require('gulp');
const tasks = require('../gulp-tasks')();

gulp.task('default', gulp.series(
  tasks.clean,
  gulp.parallel(
    tasks.styles,
    tasks.scripts,
  ),
  tasks.watch
));
```

**Gulp-tasks index.js** 
```
module.exports = function() {

  return {
    clean: require('./tasks/clean.js'),
    styles: require('./tasks/styles.js'),
    scripts: require('./tasks/scripts.js'),
    watch: require('./tasks/watch.js')
  };

};
```

**styles.js**
```
...

function styles() {
  this.name = 'styles';

  return gulp.src(src)
    .pipe(plumber({
      errorHandler: utils.errorHandler
    }))
    .pipe(sass({
      outputStyle: 'compressed',
      includePaths: [path.join(config.dist, 'lib')]
    }))
    .pipe(gulp.dest(dest));
}

module.exports = styles;

```

**watch.js**
```
function watch() {
  this.name = 'watch';

  gulp.watch('path to styles', require('./styles.js'));
  gulp.watch('path to scripts', require('./scripts.js'));
}

module.exports = watch;
```

**Comment by phated** [comment]
@alexandernanberg we made a change to the way watch functions work to align with the task API.  Everything is async (you should actually be calling a the `done` function inside watch) and must signal async completion (your watch tasks need to return a stream/promise or call the `done` callback).
