### ISSUE TITLE
Files emitted by gulp.src() do not test positive as Vinyl files

### ISSUE THREAD

**Issue by JPGygax68** [gulpjs/gulp#1662]
The doc says that `gulp.src()` emit a stream of Vinyl files, yet `isVinyl()` returns false for those files:
```javascript
var File = require('vinyl');

gulp.src('./articles/**/*.md')
    .pipe( through.obj(function(file, enc, cb) {
        console.log('isVinyl:', File.isVinyl(file)); // => false
        cb();
    });
```
(Running Node 6.1 under Windows 10 64bit.)

Am I missing something ?

**Comment by phated** [comment]
That's not how you call `isVinyl()`.... the `isVinyl()` method is on the file instance, e.g. `file.isVinyl()`

Support questions should be directed to StackOverflow.

**Comment by JPGygax68** [comment]
I'm sorr, but that is not correct. The [Vinyl docs](https://github.com/gulpjs/vinyl) clearly state that `File.isVinyl(file)` is how this function must be called. Trying to call it as an instance method yields the error message `TypeError: file.isVinyl is not a function`.

**Comment by phated** [comment]
My mistake.  That method was added in 0.5.3 which is a new version that gulp currently ships with so it won't correctly return the results in anything before gulp 4.

**Comment by JPGygax68** [comment]
So this is going to work when gulp 4 is released - good to know. Thanks!
