### ISSUE TITLE
race condition in test suite

### ISSUE THREAD

**Issue by ORESoftware** [gulpjs/gulp#1664]
hey all - minor issue hear - but it appears you have a race condition in your test suite. You are using Mocha, which runs everything serially, so the race condition does not happen there (unless test cleanup fails to happen).

The race condition happens because both `test/watch.js` and` test/dest.js` both read/write to the same path `var outpath = join(__dirname, './out-fixtures');`

My suggestion is that since these are two separate tests that they should write to different filepaths or the test files should block each other - one should not start until the other has finished. Once you move to a concurrent test runner, the two different test files could potentially read/write to the same path concurrently which will cause race conditions.

Just something to be aware of if you are writing tests with something different than Mocha for Gulp 4.

**Comment by phated** [comment]
Thanks for letting us know.  The 3.x branch won't be getting any more changes and the 4.0 branch needs a completely rewritten test suite due to the API changes but it will still use Mocha.  The test suite in gulp is really just a smoke test because all the libraries that compose it are extremely well tested.

**Comment by ORESoftware** [comment]
Np, the reason I saw that is because I am developing a test runner called Suman (borrows some features from AVA, but closer to the Mocha API) and it runs tests in parallel (separate processes). I got your tests to run 100% with Suman; running them concurrently is marginally faster, but the big benefits are test isolation. I might recommend using a concurrent test runner instead of Mocha (serial) for Gulp 4, it's just better all around, no doubt about it.

If you're curious, I put the tests here:

https://github.com/ORESoftware/gulp-suman

clone, install and run

`$ node ./node_modules/suman/index test-dest`

it should run under 2 seconds and runs each of the Gulp test files in a separate proc

I create test-dest by running a converter routine against the test directory,

so the original tests are in the test dir, and the transpile tests (from Mocha => Suman) are in the test-dest dir, enjoy 

if you want to play with Suman, you can install it globally

and then the above command simply becomes

`$ suman test-dest`
