### ISSUE TITLE
gulp-4 chainning task registration failure.

### ISSUE THREAD

**Issue by SalathielGenese** [gulpjs/gulp#1668]
With gulp-3, I used to chain tasks...
```javascript
gulp
    .task('a', ...)
    .task('b', ...);
```
Not impossible with gulp-4 as `gulp.task` returns `undeifined`.

**Comment by phated** [comment]
This is by design.  The gulp 4 API exposes `task` for getting and setting tasks so it only makes sense to return undefined when setting tasks since a get can return undefined or a function.

**Comment by SalathielGenese** [comment]
Ok! Thanks...
