### ISSUE TITLE
Reading tasks from a different folder is not working

### ISSUE THREAD

**Issue by Sweterings** [gulpjs/gulp#1669]
I have a gulpfile.js which simply points to a folder on my filesystem which contains about 15 different .js files, all of them describing gulp tasks. When the folder was still next to the gulpfile.js, there were no problems. However, no I have moved the folder (for reasons), so that the path in the gulpfile now reads "../../gulp" instead of just "./gulp". (I moved the folder up two directories). Yet, when I now try to run any task, gulp won't find any of the tasks in the now replaced folder. It can still find tasks in the old position (if I return them there), but the new folder seems to be completely empty. 

Is there some setting I missed? Some parameter I didn't initialized properly?

My gulp file simply looks like this: 

```
'use' strict';
var gulp = require('gulp');
//require('require-dir')('./gulp'); //"old" location
require('require-dir')('../../gulp'); //"new" location
```

and my filesystem looks like this:
```
gulp ("new" location)
  ├tasks.js
  └moretasks.js
node_modules
  └subfolder
    ├gulp ("old" location)
    └gulpfile.js (can't find tasks)
random
  └subfolder
    └gulpfile.js (CAN find tasks)
```

When I tried to switch locations around (the gulpfile.js on the root, and the gulp folder in the subfolder), it didn't work either.

Any help will be much appreciated.

EDIT: So, the folder that the gulpfile.js is in, is the node_modules folder, as shown in the now updated tree above. I have found that if I place the file in a different folder, named "random", it works perfectly.

**Comment by phated** [comment]
`node_modules` has special meaning in node.js, don't place files in that directory.
