### ISSUE TITLE
Support Symbol() type in specifying gulp.task

### ISSUE THREAD

**Issue by yanneves** [gulpjs/gulp#1671]
Perhaps it's a design decision, however, `gulp.task` should support `Symbol` type alongside `String`, especially since a popular pattern to organise gulp tasks in a separate directory (e.g. `gulp/`) creates a dependency injection anti-pattern.

`gulpfile.js`
```javascript
import lint from './gulp/lint'

gulp.task('default', [lint])
```

`gulp/lint.js`
```javascript
const lint = Symbol()

gulp.task(lint, () => {
  ...
})

export default lint
```

Presently, this results in a validation error.
```bash
> Error: Task requires a name that is a string
```

**Comment by phated** [comment]
This is a neat idea but gulp 4 decided to solve this problem with named functions (no more need to pass strings at all).  Would there be benefits of a symbol over a named function?

**Comment by yanneves** [comment]
Aha, indeed, I should have noticed this difference in Gulp v4.

Symbol would be a good incremental change for Gulp <v4 but support for passing in (named) functions solves this far better. Thanks for entertaining the idea anyway - I'll close this issue here.
