### ISSUE TITLE
gulp.start() & async, any idea?

### ISSUE THREAD

**Issue by bestplay9384** [gulpjs/gulp#1673]
Hey there,
I have many tasks, each one depends on another one - this is how i make all of them run synchronously one after another in correct order (order is important!).

My gulpfile works on many files from one directory.
I was trying to make it work the same, but on many directories - tried using gulp.start and async plugin.
It does not work ;/

Is there any possibility to run it wanted way?

example:
directory1
   task1 on file1 (from directory1)
   task2 on file2 (...)
   task3 on file3 (...)
directory2
  task1 on file1 (from directory2)
  task2 on file2 (...)
  task3 on file3 (...)

end.

Any idea?

**Comment by puranjayjain** [comment]
@bestplay9384 this can be achieved with a bunch of gulp plugins (in v3+) and with gulp's own modules in v4+.
Please refer to https://github.com/osscafe/gulp-cheatsheet it is a really great curated list of gulp tasks like the ones you are trying to achieve
Please refer to http://gulpjs.org/recipes/ for more information

**Comment by phated** [comment]
Use the `run-sequence` module with gulp 3.x and use `gulp.series`/`gulp.parallel` in gulp 4.  Support questions should be directed to StackOverflow.
