### ISSUE TITLE
Errors related to v8 flags

### ISSUE THREAD

**Issue by puranjayjain** [gulpjs/gulp#1674]
There are bunch of v8 flag errors thrown in node v6+. Node 6 has it's own set of apis to achieve that and the original module js-v8flags. I already opened an issue there https://github.com/js-cli/js-v8flags/issues/32. Is there a possibility of removing dependency to that module (from v4) if not what else can be done?

**Comment by phated** [comment]
Ref https://github.com/js-cli/js-v8flags/issues/32#issuecomment-221869544
