### ISSUE TITLE
gulp compass error

### ISSUE THREAD

**Issue by hh747hh** [gulpjs/gulp#1676]
Hello,

I am having a issue with executing 'gulp compass'. 

I have npm installed the 'compass' as well as the gem file but it said can't fine compass.

Any idea?

Thank you for your help!

![screen shot 2016-05-26 at 11 58 50 am](https://cloud.githubusercontent.com/assets/16959988/15581742/af221e4c-233b-11e6-99e1-4ff0276aa325.png)

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
