### ISSUE TITLE
Difference in return statement

### ISSUE THREAD

**Issue by ntanitime** [gulpjs/gulp#1683]
Hi, 
I don't understand the difference between this two gulp tasks:

```
gulp.task('stylesA', () => {
    gulp.src(paths.client.mainStyle).pipe(styles()).pipe(gulp.dest('.tmp/app'));
});
```

and 

```
gulp.task('stylesB', () => {
    return gulp.src(paths.client.mainStyle).pipe(styles()).pipe(gulp.dest('.tmp/app'));
});
```

How can be useful to return the stream inside a gulp task?
Can someone make a concrete example where without "return" the algorithm does not work.

**Comment by heikki** [comment]
http://stackoverflow.com/questions/28526354/what-are-gulp-task-async-run-hints

**Comment by phated** [comment]
Correct answer linked above. If you want to improve the docs in any way, please send a PR for us to review.
