### ISSUE TITLE
Slowness when using globals on cwd option of src

### ISSUE THREAD

**Issue by loicberthou** [gulpjs/gulp#1685]
Hi,

I notice that my script is getting extremely slow when I use the cwd option for src. It might be because I don't use the right way to do what I want but couldn't find any better solution.

I am trying to move assets from located under a folder 'node_modules' to an output folder 'css' and keep the folder hierarchy.
For example:
copy the file 'node_module/bootstrap/dist/css/bootstrap.min.css'
to the folder 'www/css/bootstrap/dist/css/bootstrap.min.css'

My complete code is the following:

```javascript
var config = {
  sourceDir: './app/',
  buildDir: './www/',

  styles: {
    src: 'app/css/**/*.scss',
    dest: 'www/css'
  },

  libs: {
    styles: [
      'bootstrap/dist/css/bootstrap.min.css',
      'bootstrap/dist/css/bootstrap.min.css.map',
      'jquery-ui/themes/flick/jquery-ui.min.css',
      'jquery-ui/themes/flick/images/ui-bg_flat_75_ffffff_40x100.png',
      'tag-it/css/jquery.tagit.css',
      'fullcalendar/dist/fullcalendar.css',
      'bootstrap-daterangepicker/daterangepicker-bs3.css',
      'bootstrap/dist/fonts/glyphicons-halflings-regular.woff2',
      'bootstrap/dist/fonts/glyphicons-halflings-regular.woff',
      'bootstrap/dist/fonts/glyphicons-halflings-regular.ttf',
      'select2/select2.css',
      'select2/select2.png',
      'select2/select2-spinner.gif',
      'ng-img-crop/compile/minified/ng-img-crop.css',
      'angular-toggle-switch/style/bootstrap3/angular-toggle-switch-bootstrap-3.css',
      'textangular/dist/textAngular.css',
      'css-progress-wizard/css/progress-wizard.min.css',
      'angular-ui-tree/dist/angular-ui-tree.min.css',
      'theme-application/dist/toolkit.min.css',
      'theme-application/docs/assets/css/application.css',
      'theme-application/dist/toolkit.min.css.map',
      'theme-application/fonts/toolkit-entypo.woff2',
      'theme-application/fonts/toolkit-entypo.woff',
      'theme-application/fonts/toolkit-entypo.ttf',
      'less-space/dist/less-space.min.css',
      'videogular/app/styles/themes/default/videogular.css'
    ]
}

gulp.task('lib_styles', function() {
  return gulp.src(config.libs.styles, {cwd: 'node_modules/**'})
    .pipe(gulp.dest(config.styles.dest));
});
```

When I replace the line:
```javascript
  return gulp.src(config.libs.styles, {cwd: 'node_modules/**'})
```
with the line:
```javascript
  return gulp.src(config.libs.styles, {cwd: 'node_modules/'})
```

It takes 36ms instead of 22s but I loose all the hierarchy.
Any idea what I am doing wrong?
Thanks!

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  However, it sounds like you are looking for the `base` option, not `cwd` - https://github.com/gulpjs/vinyl-fs#optionsbase

**Comment by loicberthou** [comment]
Thanks for the quick feedback. Will post on StackOverflow, I tried base without success. I read base only works with files that have globals in their path, but I don't.

**Comment by phated** [comment]
`base` is automatically determine if you use globs.  If you aren't using globs, you use the `base` options to manually set it.  I notice that none of your "styles" paths have "node_modules" appended to them, which is why `base` wouldn't be working and why you needed `cwd` before.  I hope StackOverflow can help you sort everything out.

**Comment by loicberthou** [comment]
Thanks a lot mate, this is the one combination I hadn't tried! Solved it.
