### ISSUE TITLE
Unmet Dependency!!!!

### ISSUE THREAD

**Issue by JonthueM** [gulpjs/gulp#1687]
I have tried 
`I tried to 
rm -rf $HOME/.npm
rpm cache clean
sudo npm install -g gulp`
And ` -r node_modules and then re-install npm`
https://github.com/vigetlabs/gulp-starter/issues/62

`npm WARN unmet dependency /lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
`

**Comment by JonthueM** [comment]
Fixed!!!! For solution comment!

**Comment by jacobfogg** [comment]
I would love the solution... I'm having the same issue!

**Comment by ahetland** [comment]
[alexander@localhost ~]$ sudo npm cache clean
[alexander@localhost ~]$ sudo npm update -g npm
[alexander@localhost ~]$ npm -v

worked for me ...
