### ISSUE TITLE
fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

### ISSUE THREAD

**Issue by NikosEfthias** [gulpjs/gulp#1691]
when i run i get the following warning 
![](http://i.imgur.com/U2CAPhJ.png)

**Comment by phated** [comment]
Duplicate issue. Not upgrading.

**Comment by NikosEfthias** [comment]
@phated what is the original issue can you merge this with that so i can end up with some solution

**Comment by callumacrae** [comment]
@NikosEfthias https://github.com/gulpjs/gulp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+graceful-fs
