### ISSUE TITLE
Gulp auto install many package in node_module of root folder.

### ISSUE THREAD

**Issue by kenzouno1** [gulpjs/gulp#1693]
Former i'm run command ` npm -i gulp --save-dev` only gulp folder generator but to day I'm update npm to v3.95 and install gulp but i see 137 folder in my node_module folder.

here is folder generated after run ` npm -i gulp --save-dev`
http://prntscr.com/bgyigd

**Comment by phated** [comment]
Not an issue.

**Comment by Nirazul** [comment]
http://stackoverflow.com/questions/33154836/npm-install-installs-all-dependencies-in-node-modules-directory-instead-of-ha
