### ISSUE TITLE
Crash after run

### ISSUE THREAD

**Issue by dslpp056193** [gulpjs/gulp#1694]
After install gulp 4 for local and gulp 3.9.1 for global, i tried run `gulp`, but got next error

![image](https://cloud.githubusercontent.com/assets/11080873/16233376/cb7f8c0a-37d6-11e6-819e-5f3490dc4823.png)

**Comment by heikki** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md#1-install-gulp-globally

**Comment by dslpp056193** [comment]
Thanks!
