### ISSUE TITLE
Search for gulpfile recently became case sensitive.

### ISSUE THREAD

**Issue by cgc** [gulpjs/gulp#1697]
My projects with gulpfiles called `Gulpfile.js` (note capitalization) that successfully built on linux a few hours ago are no longer building. The issue: running a gulp task terminates with `No gulpfile found`. renaming the file from `Gulpfile.js` to `gulpfile.js` successfully fixed the issue. As my builds were working recently, I suspect that sometime in the last few hours some upstream dependency of gulp must have changed the algorithm for finding the gulpfile. It seems like [liftoff](https://github.com/js-cli/js-liftoff) has recently updated, I wonder if that is related to this?

**Comment by phated** [comment]
Yes, that's the issue but it's a problem in a deep dependency.  I've contacted the project maintainer.

**Comment by jonschlinkert** [comment]
It was a bug in micromatch, I just published a patch from @idobh2 (thanks!) that should fix it. see https://github.com/jonschlinkert/micromatch/pull/67#issuecomment-227562640. 

if someone could reinstall and verify that the issue is fixed that would be great

**Comment by phated** [comment]
Rolled back the findup-sync upgrade.  Published liftoff as 2.2.4
