### ISSUE TITLE
gulp no longer recognizing capital-G Gulpfile.js

### ISSUE THREAD

**Issue by Praisebetoscience** [gulpjs/gulp#1698]
OS: CentOS 6.8 (Final)
node version: 4.4.5 
npm version: 3.9.6
gulp version: 3.9.1 (cli and local)

About 7 days ago I was able to `gulp build` successfully on v3.9.1.  Today I'm testing my deployment procedure and `gulp build` generates and error: `No gulpfile found`.   When I say testing my deployment procedure I mean I created a new centOS 6.8 VM and installed all the necessary packages including gulp following my instructions line by line.  

If I symlink `gulpfile.js` to `Gulpfile.js` it works.  The developers I'm working with I believe have an IDE which creates a capital-G `Gulpfile.js`.  

I also took the deploy VM I created a few days ago, and verified it still worked (it did).  I ran `sudo npm install -g gulp` and it looks like in installed a few more dependencies, and it stopped recognizing the capital-G gulp file.   I'm guessing there's a new problem somewhere down the dep chain?  

[deps.txt](https://github.com/gulpjs/gulp/files/326727/deps.txt)
[npm output.txt](https://github.com/gulpjs/gulp/files/326729/npm.output.txt)

**Comment by phated** [comment]
We reverted the changes in a dependency. Clean your npm cache and reinstall

**Comment by Praisebetoscience** [comment]
great!  thanks for the quick response.
