### ISSUE TITLE
gulp/npm

### ISSUE THREAD

**Issue by ErikaMartinez** [gulpjs/gulp#1701]
I ran the following command on the console but it appears the following error
npm install --no-bin-links

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Erika\package.json'
npm WARN Erika No description
npm WARN Erika No repository field.
npm WARN Erika No README data
npm WARN Erika No license field.

**Comment by phated** [comment]
This isn't a gulp problem. You have an invalid package.json file as per npm's requirements.
