### ISSUE TITLE
can not regenerate dest files

### ISSUE THREAD

**Issue by Luncher** [gulpjs/gulp#1707]
the test example: 

var del = require('del');
var gulp = require('gulp');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');

gulp.task('clean', function() {
    //return del(['dist']);
});

gulp.task('default', ['clean'], function() {
    return gulp.src(['src/js/*.js'], {base: 'src'})
    .pipe(uglify())
    .pipe(gulp.dest('dist')); 
});

when i delete the `clean` task, and then run `gulp`, can not generate result files. why?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
