### ISSUE TITLE
How to work around "Gulp version mismatch:"?

### ISSUE THREAD

**Issue by Bartvds** [gulpjs/gulp#171]
I installed `gulp` today, works nicely with a new project.

But I forked an existing plugin to fix some stuff, but I cannot run the gulpfile:

```
[gulp] Gulp version mismatch:
[gulp] Running gulp is 3.3.4
[gulp] Local gulp (installed in gulpfile dir) is 3.2.5
```

Not sure why this is... do all my local projects need to sync their gulp version? :confused:

**Comment by thiagoprazeres** [comment]
npm update gulp -g 
Update the local: cd /your/folder/ 
npm update gulp

**Comment by saeid1** [comment]
tanks thiagoprazeres
it is working.

**Comment by mnpenner** [comment]
Why can't the global gulp determine that there's a local gulp then kill itself and run that one instead of always warning? It's a pain to keep all my gulps across all my projects, across all my machines, across all my co-workers' machines in sync.

**Comment by phated** [comment]
@mnpenner just install it locally and alias an npm script to gulp, I never use the global install.
