### ISSUE TITLE
issue with graceful-fs module in node 6.2.2

### ISSUE THREAD

**Issue by oszkarjona-tradedoubler** [gulpjs/gulp#1710]
I started to use node 6.2.2. Build gives this error:

> (node:37956) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

`npm ls graceful-fs`

>  ┬ gulp@3.9.1
>    ├─┬ gulp-util@3.0.7
>   │ └─┬ dateformat@1.0.12
>   │   └─┬ meow@3.7.0
>   │     └─┬ read-pkg-up@1.0.1
>   │       └─┬ read-pkg@1.1.0
>   │         └─┬ load-json-file@1.1.0
>   │           └── graceful-fs@4.1.4 
>   └─┬ vinyl-fs@0.3.14
>     ├─┬ glob-watcher@0.0.6
>     │ └─┬ gaze@0.5.2
>     │   └─┬ globule@0.1.0
>     │     └─┬ glob@3.1.21
>     │       └── graceful-fs@1.2.3 
>     └── graceful-fs@3.0.8 
>

**Comment by contra** [comment]
https://github.com/gulpjs/gulp/issues/1571
