### ISSUE TITLE
Allow --silent programmatically

### ISSUE THREAD

**Issue by keleko34** [gulpjs/gulp#1713]
Allow the --silent argv functionality to be done programmatically as well:
Ex.
gulp.logs.silent();

**Comment by phated** [comment]
This is going to be solved with gulprc files which area currently in progress.

**Comment by bjg2** [comment]
Can't seem to get silent working with gulprc (not sure I get gulprc correct though, since I don't see any examples online).

My `.gulprc` file:
```
{
    "silent": true
}
```
I expect that `gulp command` should work as `gulp command --silent`

**Comment by phated** [comment]
@bjg2 you need to name the file `.gulp.json` and that's a flag, you need to set it like:
```json
{
    "flags": {
       "silent": true
    }
}
```

The full docs are at https://github.com/gulpjs/gulp-cli#configuration
