### ISSUE TITLE
Wrapper function around a gulp.series cant be called in another gulp.series 

### ISSUE THREAD

**Issue by stefan-kern** [gulpjs/gulp#1714]
Using gulp 4. 
Suppose theres a working gulp function (either of those, both produce the sam results):

```js
function files () {
  return gulp.src('/images')
    .pipe(gulp.dest('/dist/images'))
}

/* OR */

function files () {
  return del('/images')
}
```
If this function gets called like so, all works fine:
```js
gulp.task('init', gulp.series(files))

gulp.task('wrapper', gulp.series('init'))
```

however, registering it as a task via a string makes no sense to me if theres no need to register them globally. storing them in objects seems much cleaner.
theres the option of running functions inside gulp tasks like so

```js
gulp.task('wrapper', gulp.series(files))
```
this works if the called function ```files``` returns a gulp.src (the del package works aswell).

but if the function thats called from ```gulp.series``` returns a ```gulp.series``` itself like so:

```js
function init () {
  return gulp.series(files)
}

gulp.task('wrapper', gulp.series(init))
```
It gives the error message: ```Did you forget to signal async completion?```

-----

is it possible for ```gulp.series``` / ```gulp.parallel``` to have the same kind of behaviour as ```gulp.src``` or ```del```?

**Comment by doowb** [comment]
`gulp.series` and `gulp.parallel` return a function that takes a callback so that they can be used as functions passed into `.task` like your first examples:

```js
gulp.task('init', gulp.series(files));
```

If you want to use `gulp.series` instead of another task you need to execute the returned function passing it a callback:

```js
function init (cb) {
  gulp.series(files)(cb);
}

gulp.task('wrapper', gulp.series(init));
```

Hope that helps.

**Comment by stefan-kern** [comment]
Thank you, that achieves the behaviour i wanted!
But shouldn't it be default behaviour?
My point is that ```gulp.src``` doesnt need the callback either:

```js
function files () {
  return gulp.src('/images')
   .pipe(gulp.dest('/dist/images'))
}
```

I don't know the internal magic of gulp too well to see if this is a design choice or an inconsistency.

**Comment by doowb** [comment]
Take a look at [these gulp 4 docs](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#fn). They should explain it a little better.

**Comment by phated** [comment]
They return a function to execute. In your original example, you weren't calling the function. It's not recommended to wrap the methods though because composition is so powerful.
