### ISSUE TITLE
Is is possible to do Multiple Theme + CSS Files with Gulp Task?

### ISSUE THREAD

**Issue by chanakairugal** [gulpjs/gulp#1718]
Guys, I need to know how to create task that execute multiple theme and component css files when certain file change...

This is how my file structure looks like

_**App Root**_
**Widgets**
-- search-widget
---- search-widget.html
---- search-widget.css
---- search-widget.scss

-- sorting-widget
---- sorting-widget.html
---- sorting-widget.css
---- sorting-widget.scss

**Themes**
-- base-theme
---- base-theme.html
---- base-theme.css
---- base-theme.scss

-- Neon-theme
---- neon-theme.html
---- neon-theme.css
---- neon-theme.scss

Is this possible to do ?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by chanakairugal** [comment]
http://stackoverflow.com/questions/38283094/is-is-possible-to-do-multiple-theme-css-files-with-gulp-task
