### ISSUE TITLE
where to find the doc of gulp.start() & gulp.run() with v3.9.1?

### ISSUE THREAD

**Issue by bi-kai** [gulpjs/gulp#1721]
I'm using `gulp 3.9.1`, i wonder what are the differences between `gulp.start() & gulp.run()`, where can i find the doc?

if they aren't recommended, what should i use instead? 
code like this:
```
gulp.task('browser-sync', function () {
    Browsersync.init({
          ...
    });
    gulp.start(['watch']);
});
```
**i am confused, please help!**

**Comment by phated** [comment]
Those are internal methods you shouldn't use. Support questions should be directed to StackOverflow.

**Comment by bi-kai** [comment]
@phated  hi, if i can't use these two methods, only `gulp.watch()` fits;
**i just wonder how to run a task in another**, do you have any examples?

**Comment by alexeyraspopov** [comment]
@bi-kai, in Gulp 3.x you have to play with tasks dependencies:

```javascript
gulp.task('A', ['B', 'C'], function() {

});
```

But still, can use `gulp.start` at your own risk.

In Gulp 4 you will have `gulp.series` and `gulp.parallel` to run tasks in the particular order or concurrently.
