### ISSUE TITLE
Giving an empty parameter to a gulp task prevent it to start

### ISSUE THREAD

**Issue by blue112** [gulpjs/gulp#1722]
I have a gulp lint command that takes a files arguments, like so:

    gulp lint -f "file1" "file2"

If I use it that way, it works perfectly.

If I pass an empty argument, like that:

    gulp lint -f ""

The task isn't even started, and gulp exits with the "1" exit code. What is happening ?

**Comment by phated** [comment]
Gulp doesn't have a -f flag so you are doing something with that in your gulpfile. Support questions should be directed to StackOverflow.

**Comment by AurelieV** [comment]
@phated : hey. This is not dependent of the task, or the "-f" parameters. 
If you run any gulp task with an empty param, gulp will crash and never start the task.
```gulp foo ""``` with an existing gulp task `foo` will never work.
