### ISSUE TITLE
NPM Refusing to install gulp as a dependency of itself

### ISSUE THREAD

**Issue by bigbeno37** [gulpjs/gulp#1723]
_Using Node 2.15.8 and NodeJS 4.4.7, as well as Git Bash (Using MINGW64) that came with Git 2.9.0 on a Windows 10 64-bit system_

I installed NodeJS earlier on today and decided to give Gulp a shot. [I followed these exact instructions](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) until I got to Step 3, where after typing in `npm install --save-dev gulp`, the console displays the following message:

`npm WARN install Refusing to install gulp as a dependency of itself`

I've tried reinstalling NodeJS a few times now, and I'm at a loss at what's wrong here.

**Comment by bigbeno37** [comment]
It turns out that when I was going through the `npm init` stage I was making my project called 'gulp', which seemed to clash with installing Gulp. All is working fine now.

**Comment by amitsharma14393** [comment]
I faced the same issue, my project folder name was same i.e 'gulp' and renaming it to 'gulper', problem is resolved.

**Comment by percivaljunior** [comment]
Não é o nome da pasta que confita e sim o nome do projeto no arquivo package.json. Basta trocar "name": "gulp" para "name": "projeto-gulp" por exemplo.

**Comment by chaitanyaGitHub1** [comment]
Thanx amit and percival
