### ISSUE TITLE
Running gulp watch in task runner explorer by setting bindings 'after build' in Visual studio 2015

### ISSUE THREAD

**Issue by vijender1256** [gulpjs/gulp#1724]
I am trying to run gulp watch by setting bindings property of watch to 'After Build' in Task runner explorer. I tried to run application, during build it triggerd my watch task from gulp and its still running. But my application is not running in the browser, it just hangs on visual studio screen.

After I stopped the watch task my project runs and I could see my app in browser. I noticed that when you run project watch is triggered by one thread and until it is closed it not allowing my appliction to run and open in browser.

How do i fix it. any help appreicated.

```
gulp.task('watch', ['compile', 'resources'], function () {
   gulp.watch(["src/**/*", "!**/*.ts"], ['resources']);
   gulp.watch("src/**/*.ts", ['compile']);
});
```
Above is my gulp watch and I set it to run after build in task runner explorer.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by vijender1256** [comment]
I am having hard time people responding in there. do you have any solution just in case on top of your head, thank you @phated

**Comment by GusBeare** [comment]
In my experience if you close the task runner explorer then gulp watch carries on and you get back full control of VS. This is with VS 2019 preview.
