### ISSUE TITLE
How to setup path for dev / production build

### ISSUE THREAD

**Issue by djKooks** [gulpjs/gulp#1726]
This is just a question. Hope someone has good answer.
I'm almost new on gulp, and setting up on my AngularJS project.

The question is, how does other people setup the directories in front-end html/js scripts?
Because after I setup my dir paths on minified files, I couldn't debug with logs on javascript because their line number are all 1.

I have found out some ways like using ng-config or else, but I'm not sure this is the good way.
Are there some good example or guide for divide settings for development and production build?

Thanks.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
