### ISSUE TITLE
About install gulp problem

### ISSUE THREAD

**Issue by longboy** [gulpjs/gulp#1727]
npm install --save-dev gulp
the node_modules folder has 300 folders，but I don't need so many modules，Is this normal？

node version 6.3
gulp version 3.9.1

![0202](https://cloud.githubusercontent.com/assets/6941888/16981131/c6d2bdd6-4e9b-11e6-91e6-9bd375b5335e.png)

**Comment by DavidRouyer** [comment]
This is completely normal!
You are using node 6 with npm 3. Gulp has dependencies to other modules, and these dependencies have other dependencies and so on...
npm 3 flattens that tree as much as possible in node_modules, this is why you see so much modules!
