### ISSUE TITLE
why my images disappear？

### ISSUE THREAD

**Issue by longboy** [gulpjs/gulp#1728]
gulp v 3.9.1
node v 6.3.0

gulpfile.js:
![04](https://cloud.githubusercontent.com/assets/6941888/16987915/0e71844a-4ec1-11e6-8085-b4fd462c56c6.png)

when i run gulp，the images can't  find in the dist/images，but the css appear， why ? Has error?

![01](https://cloud.githubusercontent.com/assets/6941888/16987790/9bf75dc2-4ec0-11e6-8463-895434514d3c.png)
![02](https://cloud.githubusercontent.com/assets/6941888/16987806/ae8c7ab2-4ec0-11e6-91d4-22d1dd05ce16.png)
![03](https://cloud.githubusercontent.com/assets/6941888/16987847/c87e4c48-4ec0-11e6-919b-25d70163733b.png)

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  This question has been asked there a lot so you'll be able to find the reason.
