### ISSUE TITLE
local version not found

### ISSUE THREAD

**Issue by DUBANGARCIA** [gulpjs/gulp#1729]
In the console I get this message

![consola](https://cloud.githubusercontent.com/assets/17387158/16991925/f0e6c02e-4e62-11e6-961d-50779b0856c5.png)

but gulp I have it installed locally

![image](https://cloud.githubusercontent.com/assets/17387158/16991979/270345ec-4e63-11e6-87da-5a461c8451c9.png)

**Comment by phated** [comment]
Your paths are set incorrectly.  Support questions should be directed to StackOverflow.
