### ISSUE TITLE
src exclude not working as expected

### ISSUE THREAD

**Issue by ramseyfeng** [gulpjs/gulp#1730]
I have two files 'ui-bootstrap.js' and 'ui-bootstrap-tpls.js' under directory 'xxx/vendor/angular-bootstrap/'. 
I want to copy 'xxx/vendor/**/*.js' to the build directory.  and I want to exclude 'ui-bootstrap.js' from copying to the dest.

It seems not working by using below code:

    paths.vendor.src = './vendor/**/*';
    ...
    gulp.src([paths.vendor.src, '!./vendor/angular-bootstrap/ui-bootstrap.js'], {base: './'});

I'm using gulp 3.9.0, is this a bug?

**Comment by phated** [comment]
There might have been a node-glob or minimatch bug that caused this not to work.  Try removing the `./` before `vendor` in both paths.

**Comment by ramseyfeng** [comment]
Still not working, copy all the files to the dest...

**Comment by ramseyfeng** [comment]
Sorry, actually i did some wrong config, it shouldn't be a issue. Thanks anyway!
