### ISSUE TITLE
Please document gulp.src() (vinyl-fs#src) `followSymlinks` option for gulp@4

### ISSUE THREAD

**Issue by jmm** [gulpjs/gulp#1731]
In actuality `gulp.src` is `require("vinyl-fs").src` and there's documentation of some of its options duplicated / excluded, respectively. I mention it in case that can be the public API and it makes more sense to eliminate most of the duplication, link to the `vinyl-fs` docs, and just include notes that are relevant in the context of `gulp` if applicable. Like:

> **Note:** Plugins might not implement support for streams.

But please document at least `followSymlinks` one way or the other.

Related:

  * https://github.com/gulpjs/gulp/issues/1427
  * https://github.com/gulpjs/gulp/issues/1273
  * https://github.com/gulpjs/vinyl-fs/pull/85

**Comment by phated** [comment]
Lots of stuff is missing from the 4.0 docs but that is already covered by #1281 and #1446 so I'm closing this.
