### ISSUE TITLE
Specify gulp process exit code

### ISSUE THREAD

**Issue by mildmojo** [gulpjs/gulp#1736]
Is there a way to specify the gulp process exit code? It doesn't seem possible within gulp. I'm hooking the process exit with a global var to do it right now, which is kind of ugly. 

I'm trying to echo a subprocess's exit code to gulp's caller, roughly like:

```js
// gulpfile.js
var gulp = require('gulp');
var spawn = require('child_process').spawn;

var gulpExitCode = 0;

process.on('exit', function() {
  process.exit(gulpExitCode);
});

gulp.task('test', function(done) {
  var proc = spawn('ls', [], { stdio: 'inherit' });
  proc.on('error', function(err) {
    done(err);
  });
  proc.on('close', function(code) {
    gulpExitCode = gulpExitCode || code;
    done();
  });
});
```

**Comment by phated** [comment]
There's no good way to override this.  We only exit with 1 upon error or 0 upon success.

@contra yes, undertaker accounts for child_process event emitters.

**Comment by contra** [comment]
@phated Where is this done currently?
