### ISSUE TITLE
Gulp source ordering

### ISSUE THREAD

**Issue by Bitneko** [gulpjs/gulp#1737]
Given the following gulp.src setup
```
gulp.src([
        baseDir + '/plugins/**/*.js',
        baseDir + '/modules/**/*.js',
         baseDir + '/modules/fallbackAnimation.js'
   ])
     .pipe(plugins.concat(pkg.name + '.js', {newLine: ';'}))
     .pipe(gulp.dest(dest + '/assets/' +  pkg.name +'/js'));
```

I would expect `fallbackAnimation.js` to be included after all the Javascript files in `/modules`. At least that's how it work in grunt. However the file are concatenated in alphabetical order.

**Comment by phated** [comment]
Duplicate of #300. This is expected, as everything is async (unlike grunt where everything is sync and thus slow)
