### ISSUE TITLE
Gulp Project on External Drive Fails

### ISSUE THREAD

**Issue by ethanbeyer** [gulpjs/gulp#1738]
I'm not sure if I need to include my External Harddrive in my BASH Profile or something, but if I build a Foundation Project on my desktop or in any folder on my Computer, gulp works fine. As soon as I run gulp from a folder on an external drive, it fails.

If there's some piece of documentation I'm missing, I would appreciate any pointers.

Thanks.

**Comment by phated** [comment]
What version of gulp?

**Comment by ethanbeyer** [comment]
So this seemed to boil down to an npm dependency that I didn't have installed globally. It was available in the project's `package.json` file, but for some reason it needed to exist globally. Pending further errors, I believe this is actually user error, not a bug with Gulp.
