### ISSUE TITLE
Synchronous tasks don't finish with split files recipe

### ISSUE THREAD

**Issue by miguel-leon** [gulpjs/gulp#1743]
One of the solutions proposed in the recipes for splitting files into multiple files [gulp-require-tasks](https://github.com/betsol/gulp-require-tasks) has a conflict and tasks won't finish.
More information in this [issue](https://github.com/betsol/gulp-require-tasks/issues/9).

I know the recipe states that the method is deprecated and it might run into troubles with future updates. But I just figured this report might save some time to those using this recipe.

**Comment by slavafomin** [comment]
Hello @miguel-leon , [I've responded](https://github.com/betsol/gulp-require-tasks/issues/9#issuecomment-237108003) to your issue.

Right now, I can't reproduce the described error in practice with the latest version of Gulp and I'm not seeing any reasons for why it shouldn't work either.

If you will be able to create a reproducible demo, it would be helpful to resolve your issue.

Thanks.

**Comment by slavafomin** [comment]
Hello @miguel-leon!

Thank you for your report, I've [responded to your issue](https://github.com/betsol/gulp-require-tasks/issues/9#issuecomment-237113032).

I can confirm this problem. However, it applies only to **synchronous** task functions, which are pretty **rare** in Gulp ecosystem, where all plugins return proper stream objects. Also, the Node itself is asynchronous in nature, so most of the modules also return Promises or call a callback.

I will look into it and will either find a way to fix it or will add a warning message to the README.

Cheers!
