### ISSUE TITLE
Is it available to handle gulp crashes?

### ISSUE THREAD

**Issue by littleguga** [gulpjs/gulp#1746]
I have last installed gulp from npm.
Win7 64x

In gulp i have a task watching for files in directory.
But if i move 1 or more files from this directory - gulp crashes.
I tried this, but it didn't help:
```
try{
    ...
    gulp.watch(src_jade, ['reloadJade']);
    gulp.watch(src_stylus, ['reloadStylus']);
    ...
}catch(err){
     console.log('err happened');
}
```

I want gulp just to ignore this error and don't crashes.

crash error:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch null EPERM
    at exports._errnoException (util.js:890:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)
```

Anything i can do with it?

**Comment by phated** [comment]
You can listen for error events on the returned watcher instance. Support questions should be directed to StackOverflow.
