### ISSUE TITLE
Add ability to subscribe on task failure 

### ISSUE THREAD

**Issue by vladkens** [gulpjs/gulp#1747]
Hello, its necessary to return 1 as process code if some task was failure and i don't have possibility to do this now.

I think it's good idea to add ability to listen status of all gulp tasks like:

`gulp.on('complete', e => console.log(e.task_name, e.task_status));`

**Comment by nicolaiskogheim** [comment]
I know this probably isn't what you're asking for, but have you heard of [gulp-plumber](https://www.npmjs.com/package/gulp-plumber)?

I wanted to handle errors my self, and plumber can take over whenever anything fails.

Here's a usage example, notice the `pipe` to `plumber` in the third line:

```js
gulp.task('styles', function () {
    return gulp.src(paths.styles, {cwd: paths.src})
        .pipe($.plumber(function (err) {
            logPrettyDebugInfo('sass', err, this);
        }))
        .pipe($.rubySass({
            style: 'expanded',
            precision: 10
        }))
        .pipe($.autoprefixer('last 1 version'))
        .pipe(gulp.dest(path.join(paths.tmp,'styles')))
        .pipe($.size());
});
```
And here's the `logPrettyDebugInfo` from above:

```js
function logPrettyDebugInfo(taskName, err, that){
  var stack, task, header, output, pluginMsg;
  
  //Some of my builds is slow, so I trigger a beep on failure
  beepOnce();

  if(err.stack){
    stack = '\nStacktrace ⇩\n'.blue;
    stack+= err.stack.grey;
    stack+= '\nStacktrace ⇧\n'.blue;
  }else{
    stack = 'No stacktrace\n';
  }

  task = '['+taskName+']';
  header = task.bold.cyan + ' There was an issue with '.bold.red;
  header+= err.plugin.yellow.underline + '\n';

  pluginMsg = err.message + '\n';

  output = [stack, header, pluginMsg];
  console.log.apply(console, output);
  that.emit('end');
}

var didBeep = false;
function beepOnce(){
  !didBeep && beepbeep();
}
```

**Comment by nicolaiskogheim** [comment]
You should be able to exit `gulp` and return an error code in the callback you give to plumber, if that's all you want.

**Comment by phated** [comment]
If you use the gulp-cli package, an errored task already exits with a code of 1.
