### ISSUE TITLE
gulp.src | gulp.dest (static file copy) incorrectly copies symlink permissions

### ISSUE THREAD

**Issue by cdhowie** [gulpjs/gulp#1750]
If I have a file that is copied from one directory to another using the `gulp.src(...).pipe(gulp.dest(...))` idiom, and one of the source files is a symlink, the destination file's permissions are set to be those of the symlink itself, and not its target.  This usually results in the destination file having the permissions 777 instead of 644 or something reasonable.

**Comment by phated** [comment]
What version of gulp? Permissions weren't handled correctly until a recent version of the 4.0 branch.

**Comment by cdhowie** [comment]
Latest in npm (3.9.1).

**Comment by contra** [comment]
@cdhowie Can you upgrade to 4.0 (`npm install gulpjs/gulp#4.0`) and see if that fixes the problem?

**Comment by phated** [comment]
Using the 4.0 branch or using the latest vinyl-fs directly will solve this.
