### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by jamiehutber** [gulpjs/gulp#1751]
I am on ubuntu 16.06 and have just done a fresh install of node v6 with nvm. I have then installed gulp globally: `npm i gulp -g`

Now when I try to run a simple gulp script I get the following error:

```javascirpt
/home/hutber/.nvm/versions/node/v6.0.0/lib/node_modules/gulp/bin/gulp.js:131
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /home/hutber/.nvm/versions/node/v6.0.0/lib/node_modules/gulp/bin/gulp.js:131:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
`````

Maybe this is something I am doing wrong, I have had a look at gulpInst.start.apply(gulpInst, toRun); and gulpInst.start is undefined.

**Comment by yairEO** [comment]
how did you solve it?

**Comment by jamiehutber** [comment]
I believe but can't remember 100% that gulp is the wrong package, you want `gulp-cli` for using gulp in terminal/cmd

**Comment by momocow** [comment]
I have also met with this error.

From the error log of OP, we can find that the error is generated from your global `gulp` executable.
```
TypeError: Cannot read property 'apply' of undefined
    at /home/hutber/.nvm/versions/node/v6.0.0/lib/node_modules/gulp/bin/gulp.js:131:19
    ...
```

Check you global `gulp` version if it is greater than or equal to the one on which your package depends (which is installed locally).

**Comment by reachdevelopers** [comment]
I have the same issue

`TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`


I have those install and still can't figure this out.
`[11:59:52] Requiring external module babel-register
[11:59:52] CLI version 3.9.1
[11:59:52] Local version 4.0.0
`

**Comment by benoittgt** [comment]
This helped me: https://medium.com/gulpjs/gulp-sips-command-line-interface-e53411d4467

**Comment by thefpsninja** [comment]
/usr/lib/nodejs/gulp/bin/gulp.js:132
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at process._tickCallback (internal/process/next_tick.js:61:11)

This is the error i had. I just did a SUDO by "sudo gulp" and boom i bypassed that xD
