### ISSUE TITLE
it takes too long before gulp.watch() returns when there are more than 4 glob descriptors

### ISSUE THREAD

**Issue by michael8090** [gulpjs/gulp#1752]
codes like below take 20s before the log comes out...
```
gulp.watch(["!build/**","!node_modules/**","**/*.js"], () => {});
console.log('watching');
```

There are about 1000 files matching the glob above.

I have to switch to `gulp-watch` package, and it works fine (which takes less than 1s).

I'm using the latest gulp, `3.9.1`
My env is Win10, i7 cpu and 250GB SSD.

It's frustrating that the embeded API `gulp.watch` is so slow that we accutally created another widely used NPM package (gulp-watch) just because of the poor performance......

**Comment by phated** [comment]
This is the watcher we are stuck with until gulp 4 is released.

**Comment by michael8090** [comment]
As gulp@3 is the default version of gulp and the one of the four APIs is slow by default, why don't we just merge `chokidar` to gulp@3 as we do in gulp@4 and make gulp@3 more usable?

If there is a good reason for the "sticking with old watcher" strategy, could you give me a hint?

Otherwise I'm happy to send a pull request.

**Comment by phated** [comment]
That completely breaks semver. We won't be doing that.
