### ISSUE TITLE
Pipe synchronicity

### ISSUE THREAD

**Issue by lukasradek** [gulpjs/gulp#1753]
I have a question involving pipe processing succesion with following code: 
```
.pipe(sassInheritance({dir: path.dev + 'scss/'}))
    .pipe(tap(function(file, t){
        return sass(file.path).on('error', sass.logError)
            .pipe(gulp.dest(path.test + 'css'))
            .pipe(debug({title:'dest'}));
             }
         )
     )
     .pipe(debug({title:'tap'}))
     .pipe(browserSync.stream());  
```

Problem is, that in CMD I get log as follows:
debug 'tap'
browserSync (telling me that file has changed)
debug 'dest'

Shouldn't pipes be processed one after another? Am I missing something?

**Comment by MasterOfZozo** [comment]
Try follow official guides. You have one pipe in another. Restructure your code. I think there is no reason to use it this way. Example from [gulp-sass-inheritance](https://www.npmjs.com/package/gulp-sass-inheritance) is looking good.

For running one task after another. You could use [run-sequence](https://www.npmjs.com/package/run-sequence)
Sequential run of task will be natively implemented in gulp v4

**Comment by lukasradek** [comment]
Thanks @MasterOfZozo. sass-inheritance is bound to gulp-sass, which uses libsas, which is good enough reason for me.

I got this workaround which is OK from my point of view.

Can you please enlighten me about the nesting pipes and affect on synchronicity? I haven't been able to find that.

**Comment by MasterOfZozo** [comment]
This is first time I saw it. But problem of gulp is currently there is no way how to run thinks synchronously.
Pipes running consecutively but in nested pipes no. You can do really only on level of gulp tasks.

And, I'm sorry if I do not understand - you are using ruby gem instead of libsass?

**Comment by lukasradek** [comment]
Well it can be a problem with gulp-tap as well. Don't know the inner workings unfortunatelly. And yes, I am using gulp-ruby-sass :-)

**Comment by MasterOfZozo** [comment]
Každopádně jsem rád pomohl, Lukáši :'D A na ruby se vykašli, pozastavili vývoj, dokud libsass nebude fungovat stejně a toho už dosáhli. S libsass máš asi osminásobně rychlou kompilaci, jiný rozdíl není.

**Comment by lukasradek** [comment]
Chudáci nečeští přispěvatelé :-).  Teď jsem trošku mimo, ale všude se dočítám, že libsass je stále pozadu (cituji: "nemá nejnovější fce ruby-sassu), tak proto jsem šel cestou toho.

**Comment by MasterOfZozo** [comment]
Nejspíš staré články, opravdu umí to samé. Narazil jsem jenom jednou z projektem interního cachování nalezeném na sitepoint.com (Hugo Giraudel). Ale je to špatný nápad a ani vážně nadšený vývojář to při dobrém systému nevyužije.
A pokud nechceš pokecat jako vývojář někde jinde (můžeš zkusit [facebook](https://www.facebook.com/GetOutOfMyProfileThereIsNothingWhatYouNeedToKnow) ), tak bych tu českou část smazal

**Comment by lukasradek** [comment]
Tak pokud to tak je, tak je to fajn, že to libsass dohnal :-). Svoje mažu.

**Comment by phated** [comment]
Stream pipelines can't be nested. Support questions should be directed to StackOverflow.
