### ISSUE TITLE
Why not host the documentation on `Read the Docs`

### ISSUE THREAD

**Issue by qqbuby** [gulpjs/gulp#1754]
When I click the `Docs` button on our web http://gulpjs.com/, it takes me to the github repos. I think we could use the `Read the Docs` to host our docs.

RE: https://readthedocs.org/

RE: http://www.mkdocs.org/

**Comment by contra** [comment]
Already using readme.io (kind of) http://gulp.readme.io

**Comment by qqbuby** [comment]
@contra Ok, however the `Docs` nav button on the http://gulpjs.com should be updated to http://gulp.readme.io
