### ISSUE TITLE
WARN deprecated minimatch@2.0.10

### ISSUE THREAD

**Issue by felipefreitas** [gulpjs/gulp#1757]
Hello!
**Problem:**
I can't install GulpJs without this WARN described below.

**Situation:**
I've been found this issue below when I downloaded the Gulp Js from npm console. Someone can help to solve this? I didn't found another thread with this issue.

![image](https://cloud.githubusercontent.com/assets/7951137/17742403/449f3d4e-6476-11e6-9f64-e9daa1d8650e.png)

**My sugestion**
I think an update for this package could solve the problem.

Thanks!

**Comment by contra** [comment]
Use gulp 4.0 which has this updated - will be released to npm soon.

**Comment by phated** [comment]
The minimatch deprecation means nothing.  A gulpfile is not susceptible to a DoS attack 😖

**Comment by felipefreitas** [comment]
Yes @phated! But my problem isn't this, I don't worry about DoS in gulpfile. The problem is the warning as I meationed above.
