### ISSUE TITLE
gulp 4: ENOENT when running as npm script

### ISSUE THREAD

**Issue by JosephClay** [gulpjs/gulp#1758]
Using gulp 4, I can build via the command line, but running the same as an npm script fails. e.g.

```sh
# succeeds
$ gulp

# this script simply runs "gulp", but fails with
# "env: node\r: No such file or directory"
$ npm run build
```

Other npm commands work, such as `npm start` which runs `node index`.

Any ideas on how to get a better error message to track this down?

---
gulp 4
OS X 10.11.6
node 6.2.0
npm 3.8.9

**Comment by eddiemonge** [comment]
What is the scripts block in your package.json?

**Comment by JosephClay** [comment]
I've [created a repo](https://github.com/JosephClay/gulp-1758) that demonstrates the issue (at least on my system). I've checked in the `npm-debug.log` in case it's of any help.

```js
"scripts": {
    "build": "gulp"
  }
```

**Comment by phated** [comment]
This is an npm issue (most likely an issue with your environment configuration).

**Comment by JosephClay** [comment]
@phated Seems to be gulp 4 specific. 

I've updated my repo with a grunt test and it works. I've also [tried to reproduce with gulp 3 in a branch](https://github.com/JosephClay/gulp-1758/tree/gulp-3) and it works fine.

I've also verified both node and npm are in `/usr/local/bin/` and that `/usr/local/bin` is in `$PATH`.

**Comment by phated** [comment]
You should __not__ be installing gulp and gulp-cli in your dependencies.  Many npm versions don't have deterministic installation and that breaks stuff.  gulp 4 ships with gulp-cli as a dependency.

**Comment by JosephClay** [comment]
> gulp 4 ships with gulp-cli as a dependency

I did not know this! I've updated the test cases to not install gulp-cli.

[Uninstalled and reinstalled node.](http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x) Then [reinstalled gulp 4](https://demisx.github.io/gulp4/2015/01/15/install-gulp4.html). Running `gulp -v` in the command line now returns the same error as running the npm script:

`env: node\r: No such file or directory`

Again, gulp 3 works if I uninstall gulp-cli globally and reinstall gulp 3.

**Comment by phated** [comment]
the reason I think this is an npm problem is `env: node\r` looks like a key a JSON argument (possibly the npm environment object they generatre.  Echoing path doesn't really do anything because npm modifies it as part of `npm run ...`

**Comment by stramel** [comment]
AH LINE ENDINGS! Re-installed my entire dev environment :sweat_smile:

**Comment by GoodLuckBamboo** [comment]
I have the same issuse, I install the gulp4 form http://registry.npmjs.org/gulp4
I fixed the problem by change the end of line of the node_modules/.bin/gulp4  by vim

`:set ff=unix`

then i  run `npm run XXX`

and the bug is missing, my CentOS has the same issue too. And I resolve it with the same method.

**Comment by phated** [comment]
Don't use that package...
