### ISSUE TITLE
Cannot install gulp-cli on the latest Nodejs 6.4.0

### ISSUE THREAD

**Issue by Son-Lam** [gulpjs/gulp#1761]
I was working on nodejs 6.3.0 with gulp without any problem. Today I tried to update to nodejs 6.4.0 and when I run "gulp -v" it return "gulp unknown". I tried re-install without success.

I downgraded back to nodejs 6.3.0 and everything start working again.

Could you test and see what the problem.

Best Regards,

**Comment by phated** [comment]
Usually when you upgrade node, you have to rebuild/reinstall your modules due to native module weirdness.
