### ISSUE TITLE
gulp-webpack + gulp-sass

### ISSUE THREAD

**Issue by mathishuettl** [gulpjs/gulp#1764]
Hello,

how can i run gulp-webpack to build my js and gulp-sass to build my css files in one task?
I want something when i run gulp watch that when i change something in main.js is should build the javascript-file and when i change something in the sass files it should build the css file.

```
gulp.task("default", function() {
	return gulp.src("main.js")
		.pipe(webpack({
			output: {
				filename: "app.js"
			},
			watch: true
		}))
		.pipe(gulp.dest("./dist"));
});

gulp.task("sass", function() {
	return gulp.src('./sass/main.scss')
		.pipe(sourcemaps.init())
		.pipe(sass().on("error", sass.logError))
		.pipe(sourcemaps.write())
		.pipe(gulp.dest('./dist'));
});


gulp.task('watch', function () {
	gulp.watch('./sass/**/**/*.scss', ['sass']);
});

```

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
