### ISSUE TITLE
Need to update gulp package.json?

### ISSUE THREAD

**Issue by rivimey** [gulpjs/gulp#1765]
I'm new to gulp, but while trying to install the current (3.9.1) I saw these messages:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

It seems most of these can be traced back to the gulp package.json specifying relatively old versions of packages; for example glob-watcher is is specifed as 0.0.6 but the current version is 3.0.0. Similarly, vinyl-fs is specified as 0.3.14 but the current version is 2.4.3.

**Comment by phated** [comment]
Duplicate. Please search for other issues before opening yet another.

**Comment by rivimey** [comment]
I did!! No matches for 'package.json' or 'please update to minimatch'.

Please specify which this is a dup of or even better fix the issue!

**Comment by phated** [comment]
😖  https://github.com/gulpjs/gulp/search?q=minimatch&type=Issues&utf8=%E2%9C%93
