### ISSUE TITLE
How to change gulp's default color output?

### ISSUE THREAD

**Issue by maotora** [gulpjs/gulp#1766]
Hi, I've been using gulp for quite sometime and love it.

But i usually have this problem where gulp's default color output doesn't allow me to see the timestamp with my terminal black colorscheme.

When i searched I saw a similar problem [here](http://stackoverflow.com/questions/31748610/gulp-output-on-windows-cmd-is-unreadable).

I'm using gulp#4.0 and this problem has always been there, I'm asking about this now because i need to see almost everything gulp outputs now.

Here is a screenshot how sad it looks..

![windowed_2016-08-20_17h50s50](https://cloud.githubusercontent.com/assets/5174884/17831883/b122efc6-66fe-11e6-99f6-e900b5611158.png)

**Comment by phated** [comment]
You can change your terminal's color theme/scheme to align with https://www.npmjs.com/package/chalk

Eventually, you will be able to change colors in a `.gulp.js` file as per https://github.com/gulpjs/gulp-cli/issues/63
