### ISSUE TITLE
Minor error in fast-browserify-builds-with-watchify recipe

### ISSUE THREAD

**Issue by ericgrosse** [gulpjs/gulp#1771]
In [this recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md), you find the following:

```
function bundle() {
  return b.bundle()
    // log errors if they happen
    .on('error', gutil.log.bind(gutil, 'Browserify Error'))
    .pipe(source('bundle.js'))
    // optional, remove if you don't need to buffer file contents
    .pipe(buffer())
    // optional, remove if you dont want sourcemaps
    .pipe(sourcemaps.init({loadMaps: true})) // loads map from browserify file
       // Add transformation tasks to the pipeline here.
    .pipe(sourcemaps.write('./')) // writes .map file
    .pipe(gulp.dest('./dist'));
}
```

Specifically:

```
// optional, remove if you don't need to buffer file contents
 .pipe(buffer())
```

I tried this exact setup without the `buffer()` step and got the following error:

```
Error: gulp-sourcemap-init: Streaming not supported
```

Once I added `buffer()`, everything worked again correctly.

All to say, the comment claiming that buffering file contents is optional should be removed since it's in fact mandatory.

**Comment by phated** [comment]
Sourcemaps are also flagged as optional so this comment remains true.
