### ISSUE TITLE
[question] How to run a notifier on the invoked task only?

### ISSUE THREAD

**Issue by thasmo** [gulpjs/gulp#1773]
So I've been using `gulp-notifier` to display notifications for each Gulp task. Unfortunately I wasn't able to configure it in a way that it would only run on the invoked task and not on all sub-tasks, because I'd like to have popup notififytions only on the initially invoked task.

What I tried now is to wrap the actual Gulp task function to add code which triggers a notification when needed. The wrapper looks like this and seems to work for my tasks:

```js
var gulp = require('gulp');
var notifier = require('node-notifier');
var task = require('./task.js');

gulp.task(task.displayName, function(callback) {
	var notify = function() {
		notifier.notify('DONE.');
	};

	var result = task(function() {
		notify();
		callback();
	});

	if(result) {
		if (result.constructor.name == 'DestroyableTransform') {
			result.on('end', notify);
		} else if (result.constructor.name == 'Promise') {
			result.then(notify);
		}
	}

	return result;
});
```

This wraps the actual Gulp task which is loaded via `require` and tries to run the notifier on the end of the task. (At the moment it runs for every task.)

Is this the right way to go? Is there an easier and/or more compatible way to achieve this?

I'd like to **not** use a Gulp plugin for this, because I don't want people to actually know how to add the notifier within a task. Notifications should just work "out of the box" without adding logic within a task function.

Thanks!

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by thasmo** [comment]
Indeed, [done](http://stackoverflow.com/questions/39173603/how-to-run-a-notifier-on-the-invoked-gulp-task-only) that now; I wasn't sure if this was the right place, although there were issues tagged with `question`, so I tried. ;) Thanks!

**Comment by phated** [comment]
Sorry, questions are usually flagged when I'm not sure if an issue exists that needs to be fixed. Usually they are paired with "needs further investigation".

**Comment by thasmo** [comment]
I see. :)
