### ISSUE TITLE
gulp.watch ignore/exclude specific folder (node_modules)

### ISSUE THREAD

**Issue by Bram-Zijp** [gulpjs/gulp#1774]
Hi,

I am using gulp.watch and i would like to ignore a folder (node_modules for instance). I would like to use:
  `gulp.watch(['../**/*.php', '!./node_modules/**'], reload)`;

My gulp file is based on Web Starter Kit from Google and this is my serve task with the bloated manual gulp.watch:
```
// Watch files for changes & reload
gulp.task('serve', ['scripts', 'styles'], () => {
  browserSync.init({
    notify: false,
    // Customize the Browsersync console logging prefix
    logPrefix: 'WSK',
    scrollElementMapping: ['#page'],
    proxy: project,
    port: 3000
  });

  gulp.watch(['../inc/**/*.php', '../*.php', '../layouts/**/*.php', '../plugins/**/*.php', '../template-parts/**/*.php'], reload);
  gulp.watch(['styles/**/*.{scss,css}'], ['styles', reload]);
  gulp.watch(['scripts/**/*.js'], ['scripts', reload]);
  gulp.watch(['images/**/*'], ['images', reload]);
});
```

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by shnam7** [comment]
Hi, there
I'm experiencing the same problem that gulp.watch() is not handling 'excludes'.
In my example below,

```javascript
const watched = ['docs/**/*', '!docs/gulpfile.js' ];

gulp.src(watched).pipe(require('gulp-debug')());

gulp.watch(watched, (done)=>{
  console.log('watch triggered'); done();
});
```

gulp.src() show correct list which is not including 'docs/gulpfile.js', but gulp.watch() triggers when I make changes on 'docs/gulpfile.js'

I spent many hours on this, and it seems to be a kind of bug. Please advise if I missed anything.
Thanks,
