### ISSUE TITLE
issues with gulp install

### ISSUE THREAD

**Issue by rm2k** [gulpjs/gulp#1779]
I ran the following command on my windows 8 command prompt:

`npm install -g gulp`

and I get the following:
![gulp-instal](https://cloud.githubusercontent.com/assets/1936364/18096247/d8391c24-6ed9-11e6-9142-895f49d35511.PNG)

**Comment by callumacrae** [comment]
That's not an error, nothing to worry about :)

https://github.com/gulpjs/gulp/issues/1485

**Comment by invernizzie** [comment]
It will be when node hits v7. I bet there's a good reason why gulp@3 is stuck with vinyl@0.3?
