### ISSUE TITLE
Couldn't bundle the code in gulp which is in system.config

### ISSUE THREAD

**Issue by kodali2446** [gulpjs/gulp#1780]
Hi,
I am working on minifying and bundling the code using gulp. This is to reduce the number of http requests.This is my main index.html page.
I minified and bundled all the files that are inside head tag. But my source files are in the body tag . I wrote  System.config ad gave the system .import statements inside the body to load and take the source files.  Can i replace it by a single bundled file so that whenever the file is requested by the browser the bundled one will be called and thereby reduce the number of http requests.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
