### ISSUE TITLE
Should or can I use gulp on server side?

### ISSUE THREAD

**Issue by MurWhite** [gulpjs/gulp#1781]
We use gulp to build our FE project faster.

> Automate and enhance your workflow

But can I or should I use it on the server side to do some operation such as batch amending file name....
In other words, I'm writing something like a node-package and use gulp to do something like  batch amending file name.
```javascript
gulp.src()
    .pipe(rename())
     ......
    .pipe(gulp.dest())
```
But one of my seniors told me,"You should do it use native node code instead of gulp".I am wondering if I am doing something incorrectly.Or you can tell me the risk when I use gulp in a node-package's `dependencies`.
You can convince me not to use gulp here,or help me to convince my senior that I have no problem with using gulp here.

英文表达如果不太清楚，我希望用中文再讲述一遍：
我现在书写一个类似于node package的东西，提供给其他开发者使用，其中有些代码我用了gulp的命令，见上面代码。但是我的一个前辈告诉我说，这样写不好，“没有人会这样用gulp”。但是这个理由并不能说服我，我也不能说服他。因此我前来询问，这样使用gulp究竟是否可行。

**Comment by arturparkhisenko** [comment]
@MurWhite Maybe he meant `fs.rename`? I don't think if there is a big sense of using gulp for only renaming a file.

**Comment by MurWhite** [comment]
@arturparkhisenko It's just a sample.I can't write each code I coded in my project.I just wanna know if it's reasonable to use gulp on a server side or node-package.

**Comment by phated** [comment]
@MurWhite It's not wrong to use it server side but you might want to use lower-level modules like vinyl-fs (which gulp uses internally for the streaming interfaces).  You also need to determine what features you are using and see if it makes sense overall.

Support questions should be directed to StackOverflow.
