### ISSUE TITLE
Is gulp dead?

### ISSUE THREAD

**Issue by nikolay** [gulpjs/gulp#1782]
Last commit on the [v4](https://github.com/gulpjs/gulp/tree/4.0) branch is more than 2 months old.

**Comment by phated** [comment]
No. Gulp is made up of many small modules. If you look at our github org, much work is being done in other repo.  Issues like this are very demoralizing for the people working on the project, please don't open them.

**Comment by contra** [comment]
@nikolay Yeah, shit is happening in a bunch of other projects. gulp is a very thin layer on top of all of these other projects, there's really no reason for us to commit to this project often.

Your contributor graph shows you haven't committed anything in over two weeks, doesn't mean you're dead.

**Comment by nikolay** [comment]
I understand it all but I honestly asked as at this pace, it's not gonna be released anytime soon and issues like https://github.com/gulpjs/gulp/issues/1604 will be v4.

**Comment by jonschlinkert** [comment]
If I ever write a list of the top 10 most irritating issue titles, this will rank near the top. I would block this user.

**Comment by nikolay** [comment]
@jonschlinkert Well, you can block me, whatever, but you should better take care of your easy and unsubstantiated irritability first, which could be devastating, and which is near the top of world's evils.

https://snyk.io/test/npm/gulp

**Comment by phated** [comment]
@nikolay that warning means nothing.  You aren't passing user input directly to gulp (or else you __really__ shouldn't be).  This thread has gone long enough.  I'm locking it.
