### ISSUE TITLE
gulp.watch stops watching files

### ISSUE THREAD

**Issue by dman777** [gulpjs/gulp#1783]
I am having a issue where `gulp.watch` successfully detects file changes, but only for a while. After a few file changes and saves to my `index.html`, it stops detecting file changes. There are no errors...it just silently stops detecting the file saves/changes. 

from the gulpfile.js of fountain-webapp:

```javascript
 
function watch(done) {
  gulp.watch([
    conf.path.src('index.html'),
    'bower.json'
  ], gulp.parallel('inject'));
```

```
one@development ~/github/drop $ gulp -v
[15:11:54] CLI version 1.2.2
[15:11:54] Local version 4.0.0-alpha.2
```

```
one@development ~/github/drop $ npm -g list generator-fountain-webapp
/home/one/.nvm/versions/node/v4.2.2/lib
└── generator-fountain-webapp@0.7.2 
```

```
one@development ~/github $ node --version
v4.2.2
one@development ~/github $ npm --version
2.14.7
```

**Comment by phated** [comment]
Your task most likely isn't signaling async completion. Support questions should be directed to StackOverflow.

**Comment by dman777** [comment]
Here is a bare bones version, I don't see a async issue. Please let me know if I am missing. `gulp.watch` will detect a change to `index.html` one time, after that it won't detect any changes:

```javascript
gulp.task('serve', gulp.series('watch'));

function reloadBrowserSync(cb) {
  console.log('sssssssssssssssss');
  cb();
}

function watch(done) {
  gulp.watch(['/home/one/github/one-drop/src/index.html',
             '/home/one/github/one-drop/src/app/**/*.html'], reloadBrowserSync);
  done();
}
```

Here is what it looks like when it will detect the first change.... after that is silently detects no future file changes to index.html:

```
[18:07:19] Finished 'serve' after 17 ms
[18:07:31] Starting 'reloadBrowserSync'...
sssssssssssssssss
[18:07:31] Finished 'reloadBrowserSync' after 676 Î¼s
```
