### ISSUE TITLE
Gulp TFS Checkout for only modified files in dest folder when src folder files are changed

### ISSUE THREAD

**Issue by vijender1256** [gulpjs/gulp#1785]
I am trying to checkout Files from dest folder when I change files in the src folder. currently when i use tfs-gulp-checkout plugin it is checkout all the files, but I am trying to checkout only modified files in src folder to that of dest folder :

```
const tfs = require('gulp-tfs-checkout');
    gulp.task('build-less', ['checkout'], () => {
        return gulp.src('Content/**/*.less')
            .pipe(less())
            .pipe(gulp.dest('dest'));
    });

    gulp.task('checkout', function () {
        return gulp.src('dest/**/*.css')
                         .pipe(tfs());
    });
```
Can anyone provide solution for checking out only modified files in dest folder

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.

**Comment by vijender1256** [comment]
@phated I dont know if this is a support question does gulp has capability to checkout only specified files in dest folder ?

**Comment by heikki** [comment]
http://stackoverflow.com/questions/39274625/gulp-tfs-checkout-for-only-modified-files-in-dest-folder-when-src-folder-files-a

**Comment by heikki** [comment]
@vijender1256 I know you asked that question. I linked it here for future generations.

**Comment by vijender1256** [comment]
@heikki Thanks, I did not get any help from stackoverflow, let me know if someone from gulp community can help to figure this out, here is solution i found but couldn't figure out how to use this with gulp task:
https://gist.github.com/loktar00/345d071d5086fec957ab
