### ISSUE TITLE
gulp can't compile .js with babel when gulpfile in node_modules dir

### ISSUE THREAD

**Issue by smilce** [gulpjs/gulp#1787]
gulp can't compile .js with babel when gulpfile in node_modules dir.

when I put gulpfile in a normal dir , it is ok , for instance, 
` gulp --gulpfile client/gulpfile.babel.js`

but when I put gulpfile in node_modules, it can't compile
`gulp --gulpfile node_modules/gac-build-tool/gulpfile.babel.js `
it show error
```
[15:13:20] Working directory changed to ~/Work/guoren/project/ksbx-manage/node_modules/gac-build-tool
/Users/liubingli/Work/guoren/project/ksbx-manage/node_modules/gac-build-tool/gulpfile.babel.js:3
import gulp from 'gulp';
^^^^^^
```

**Comment by phated** [comment]
Babel ignores node_modules for transpilation. Also, devDeps don't get installed for transitive dependencies. This has nothing to do with gulp.
