### ISSUE TITLE
Why is there no 3.9.2 milestone?

### ISSUE THREAD

**Issue by ssteinerx** [gulpjs/gulp#1788]
Seems like the vinyl-fs dependency issue is almost solved, would it be possible to create a 3.9.2 milestone with just that updated dependency as the release blocker issue?

If #1604 were the only issue to be resolved to get the vinyl-fs dependency updated, and a 3.9.2 out the door, I would be willing to work on it.

The 4.0 milestone just seems way too far away...

ssteinerX

**Comment by phated** [comment]
That's not how semver works.

**Comment by ssteinerx** [comment]
@phated I understand how semver works, I don't understand how not releasing an incremental update to resolve an ancient dependency works.

Is it not possible to release a 3.9.2 version, accommodating the changes to lodash, in a semver compliant way?

**Comment by phated** [comment]
Correct, there are already issues that have mentioned that.
