### ISSUE TITLE
How should I organize sub tasks in gulp 4?

### ISSUE THREAD

**Issue by wheeljs** [gulpjs/gulp#1790]
I have a problem with subtasks when I using gulp 4. 
In gulp 3, I have splitted tasks into some files and use [gulp-load-subtasks](https://github.com/skorlir/gulp-load-subtasks) to load and execute them. When I using gulp 4, I got a problem when I try to load tasks. eg: I can't load task *a* (which depends on task *b*) before task *b* loaded. When I try to do this, I got an error `AssertionError: Task never defined: b`.

This is my folder:

```
gulpflie.babel.js
workflow/
    common.js
    task/
        a.js
        b.js
```

How should I organize sub tasks in gulp 4?

**Comment by heikki** [comment]
https://github.com/gulpjs/gulp/blob/4.0/docs/recipes/split-tasks-across-multiple-files.md

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
