### ISSUE TITLE
Watch tasks sometimes run without changes being made.

### ISSUE THREAD

**Issue by hoodweb** [gulpjs/gulp#1792]
I have the following gulpJS

```
gulp.task('watch', function(){
	gulp.watch('./sass/**/*.sass', function(){
		console.log('SASS');
	});
	gulp.watch('./js/**/*.js', function(){
		console.log('JS');
	});
});

gulp.task('default', ['watch']);
```

Sometimes when I make changes to a .js file inside the JS directory, the console will print "SASS", and vice versa.

Only consistency is the fact that the task will always print "SASS" when .sass files are changed, and print "JS" when .js is changed.

**Comment by phated** [comment]
The gulp 3.x file watcher had many problems.  See #651 

You can either upgrade to gulp 4, use gulp-watch package or use the chokidar package directly.

**Comment by hoodweb** [comment]
Fair, just attempted to upgrade to gulp 4. And it doesn't look like I can get the gulp-sass compiler to work with gulp 4. So I'll just live with these conditions. Maybe when its not in Alpha :-) Thanks for the reply
