### ISSUE TITLE
in windows 7 it's ok,but in linux(including mac), report some errors.

### ISSUE THREAD

**Issue by priscillapan** [gulpjs/gulp#1794]

**Comment by Arial7** [comment]
Do you have write permissions to the destination directory?

**Comment by priscillapan** [comment]
in Mac, sudo gulp document-output, the same error occured. i'v checked the directory it's trying to write, it has w/r right


internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at /home/project/node_modules/gulp-jsdoc3/dist/gulp-jsdoc.js:112:121
    at /home/project/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:82:15)
