### ISSUE TITLE
gulp vs gulp-cli reasoning unclear in getting started guide

### ISSUE THREAD

**Issue by abraham** [gulpjs/gulp#1795]
In the getting started guide there is this text.

> If you have previously installed a version of gulp globally, please run npm rm --global gulp to make sure your old version doesn't collide with gulp-cli.

It would be more useful if there was an explanation of what the difference between them is and why I should rm the `gulp` that a different (apparently now outdated) guide told me to install 10 minutes ago.

https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

**Comment by phated** [comment]
I believe all our provided docs and guides are updated to suggest `gulp-cli`.  We have no control over external posts, etc.

If you find some of our documentation recommending that `gulp` be installed globally, please submit a PR.

The reason for removing `gulp` globally is a really nuanced (and frustrating) reason that doesn't really belong in a "Getting Started" guide.  If you want to submit a PR that says something like "For more information, see [github thread link]", I'd be willing to consider it.  I think the thread rabbit hole is pretty deep (gulp issues, npm issue, etc) but it should be easy enough to find something with github search.
