### ISSUE TITLE
gulp.lastRun is not a function [2]

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [gulpjs/gulp#1799]
```javascript
var time = gulp.lastRun('build-coffee');
```

ERROR: gulp.lastRun is not a function﻿

How to know last run time?
How to work this code:

```coffeescript
gulp.task 'build-coffee', =>
	gulp.src './modules/**/*.coffee', since: gulp.lastRun('build-coffee')
	.pipe coffee()
	.pipe gulp.dest './build/'

```

questions
==========
- How to know last run time?
- How to work this code?
- Which version I should use?

**Comment by phated** [comment]
Install 4.0

Support questions should be directed to StackOverflow.

**Comment by uMaxmaxmaximus** [comment]
> Support questions should be directed to StackOverflow.

i dont know, thks
