### ISSUE TITLE
How to know task last run time?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [gulpjs/gulp#1800]
```javascript
gulp.lastRun('taskName') // Error: gulp.lastRun is not a function
```

My gulp vercion is 3.10.3. Which version it needs?

P.S. @phated get out from here! If you do not know the answer, just shut your mouth and let others respond. Do not spoil the impression of the community.

**Comment by heikki** [comment]
https://github.com/gulpjs/gulp/issues/1798
https://github.com/gulpjs/gulp/issues/1799

**Comment by uMaxmaxmaximus** [comment]
@heikki this tickets are closed! AND contain no response!!!

#1798
#1799

**Comment by heikki** [comment]
<img width="410" alt="screen shot 2016-09-12 at 11 29 29" src="https://cloud.githubusercontent.com/assets/82735/18429483/3c33fada-78dc-11e6-8a70-44820682bdc1.png">

**Comment by uMaxmaxmaximus** [comment]
@heikki 

![image](https://cloud.githubusercontent.com/assets/19378179/18429671/66526a44-78dd-11e6-9c61-5f03c2b1ad69.png)

**Comment by alidd** [comment]
uMaxmaxmaximus (Иван Вольнов):
> get out from here! ... just shut your mouth

I like pUTINs Russians!
Georgia -> Ukraine -> Syria -> Github?

**Comment by Arial7** [comment]
If you would read the other issues, you would know that 4.0 does exist. Stop being rude!

**Comment by contra** [comment]
`npm install gulpjs/gulp#4.0`
