### ISSUE TITLE
multiple gulp dest not working

### ISSUE THREAD

**Issue by mmclau14** [gulpjs/gulp#1801]
hi all below is a snippet of code from one of my gulp tasks.  as you can see, i am doing some really basic stuff like setting up plumber with it's default settings, concatenating some scripts together, replacing some constants, etc. The only thing that does not currently work is everything after the first .dest method. just wondering how i can write one stream, then do some more modifications, then write the stream again as I am trying to do here. I am literally just trying to have a non minified and minified version with different names. did not think it would be so hard.

```javascript
        gulp.src(paths.jsMain) // source the files
        .pipe(plumber()) // set up plumber for error reporting
        .pipe(concat(paths.jsMainDist)) // concatenate the scripts together
        .pipe(replace('__VERSION__', settings.build.__VERSION__)) //
        .pipe(replace('__BUILD_TIME__', settings.build.__BUILD_TIME__)) //
        .pipe(gulp.dest(paths.jsDist)) // write to dist
        .pipe(uglify()) // minify the scripts
        .pipe(rename(minName(paths.jsMainDist))) // rename the script
        .pipe(gulp.dest(paths.jsDist)); // write to dist
```

**Comment by phated** [comment]
This should be fine, vinyl-fs had a feature specifically written to support this.  Not sure if there is something wrong with one of your plugins or something.  Those questions should be directed to StackOverflow or their respective repositories.

Out of curiosity, what version of gulp are you using?

**Comment by mmclau14** [comment]
[15:47:34] CLI version 3.9.0
[15:47:34] Local version 3.9.1

**Comment by phated** [comment]
I'd recommend using https://www.npmjs.com/package/gulp-debug immediately after the first `.dest` call to see if files are being passed through.  It'll help narrow where your problem is.

**Comment by mmclau14** [comment]
thanks for the recommendation. i used it and found that the following was being logged out: 
```
[16:01:07] unicorn: dist/build/business.min.js
[16:01:07] unicorn: 1 item
```

**Comment by phated** [comment]
Everything is working with the stream pipeline.  It's most likely a problem with your uglify or renaming.  Those support questions should be directed to StackOverflow.

**Comment by mmclau14** [comment]
and it looks like you guys use the vinyl-fs dest directly so that repo must have the problem, right?

**Comment by phated** [comment]
It's not a vinyl-fs related issue.  It's likely your renaming is incorrect and is being output to a different spot on the filesystem.  You've already noted that the files are flowing through the stream successfully, thus this is not an issue and is instead a support problem.  I suggest you debug further and/or create a post on StackOverflow.
