### ISSUE TITLE
Is there any limitation about the file number passing via gulp.src?

### ISSUE THREAD

**Issue by ganlanyuan** [gulpjs/gulp#1803]
Hey, 
I have about 88 scss files need to compile to css. When I do
```javascript
gulp.src(config.sass.src)  
  .pipe(sourcemaps.init())
  .pipe(sass(config.sass.libsass_options).on('error', sass.logError))  
  .pipe(sourcemaps.write(config.map_dest))
  .pipe(gulp.dest(config.sass.dest))
```
Total 51 files are compiled.    
I try to not generating soursemaps with
```javascript
gulp.src(config.sass.src)  
  // .pipe(sourcemaps.init())
  .pipe(sass(config.sass.libsass_options).on('error', sass.logError))  
  // .pipe(sourcemaps.write(config.map_dest))
  .pipe(gulp.dest(config.sass.dest))
```
Total 82 files are compiles, still 6 files left not been compiled.
There is no any error in the process.

Is there any limitation about how many files I can pass?
How can I make sure all files are compiled correctly?
Thanks

**Comment by phated** [comment]
There's no limit in gulp.  You might be hitting platform limits or using streams wrong.  Those support questions should be directed to StackOverflow.

**Comment by ganlanyuan** [comment]
I see, thanks

**Comment by ganlanyuan** [comment]
Adding `return` fixed my issue.
``` javascript
return gulp.src(config.sass.src)  
  .pipe(sourcemaps.init())
  .pipe(sass(config.sass.libsass_options).on('error', sass.logError))  
  .pipe(sourcemaps.write(config.map_dest))
  .pipe(gulp.dest(config.sass.dest))
```
