### ISSUE TITLE
Very high cpu usage on OS X - gulp.watch()

### ISSUE THREAD

**Issue by edhemphill** [gulpjs/gulp#1805]
I am trying to figure out the status of the high CPU usage issues when using the .watch() stuff. On OS X it looks like one thread is essentially running at 100%. gulp 3.9.1, node 4.2.1, 10.11.5

https://github.com/gulpjs/gulp/issues/651

Every thread which was discussing this seems to be locked.

Is it best to simply move to another build system / file watching project, is this fixed in gulp 4, or where best to proceed?  Does gulp 4 not poll the fs?

If I use 4.0, should I use the 4.0 branch or master?   

Thanks.

**Comment by phated** [comment]
You can fix your globs, use the gulp-watch module, use chokidar directly or use the 4.0 branch of gulp. Support questions should be directed to StackOverflow.
