### ISSUE TITLE
bug  about gulp html2jade during watch

### ISSUE THREAD

**Issue by lolliuym** [gulpjs/gulp#1817]
I have my Gulpfile that I install with YeoMan. I add gulp-html2jade and setup to watch. 
I am writing in both Jade and html. I know that ({ pretty: true }) affect to amend.

#
`gulp.task('html2jade', function() {
  var options = {nspaces:2};

  gulp.src('app/*.html')
    .pipe($.gulp.html2jade(options))
    .pipe(gulp.dest('app/jade'))
});

gulp.task('html', ['jade', 'styles', 'scripts'], () => {
  return gulp.src('app/*.html')
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.cssnano({safe: true, autoprefixer: false})))
    .pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))
    .pipe(gulp.dest('dist'));
});

gulp.task('serve', ['styles', 'scripts', 'fonts'], () => {
  browserSync({
    notify: false,
    port: 9000,
    server: {
      baseDir: ['.tmp', 'app'],
      routes: {
        '/bower_components': 'bower_components'
      }
    }
  });

  gulp.watch([
    'app/*.html',
    'app/images/**/*',
    '.tmp/fonts/**/*'
  ]).on('change', reload);

  gulp.watch('app/**/*.jade', ['jade']);
  gulp.watch('app/*.html', ['html2jade']);
  gulp.watch('app/styles/**/*.scss', ['styles']);
  gulp.watch('app/scripts/**/*.js', ['scripts']);
  gulp.watch('app/fonts/**/*', ['fonts']);
  gulp.watch('bower.json', ['wiredep', 'fonts']);
});
`
 
It give me negative resultat:
 #`
body
    //
      if lt IE 10
      p.browserupgrade
      | You are using an
      strong outdated
      |  browser. Please
      a(href='http://browsehappy.com/') upgrade your browser
      |  to improve your experience.
    .ui.segment
      p
      |       
      |       
      .ui.active.dimmer
        .ui.loader
    |     
    |     
    .container
      .header
        ul.nav.nav-pills.pull-right
          li.active
            a(href='#') Home12
          |           
          |           
          li
            a(href='#') About
          |           
          |           
          li
            a(href='#') Contact
        |         
        |         
        h3.text-muted 3 7
      |       
      |       
      .container
        h2 Vertical (basic) Form
        |         
        |         
        form
          .form-group
            label(for='email') Email:
            |             
            |             
            input#email.form-control(type='email', placeholder='Enter email')
          |           
          |           
          .form-group
            label(for='pwd') Password:
            |             
            |             
            input#pwd.form-control(type='password', placeholder='Enter password')
          |           
          |           
          .checkbox
            label
              input(type='checkbox')
              |  Remember me
          |           
          |           
          button.btn.btn-default(type='submit') Submit
      |       
      |       
`

**Comment by phated** [comment]
You missed the part in out issue template that says "Support questions should be directed to StackOverflow".
