### ISSUE TITLE
Gulp don't watch new file when glob start with "./"

### ISSUE THREAD

**Issue by KiT106** [gulpjs/gulp#1821]
```js
gulp.watch("./src/**/*.js", doSomeJob);  // don't watched for new files
```
Trigger don't fire when I add a new file, but every work fine when I remove "./" in glob prefix.
```js
gulp.watch("src/**/*.js", doSomeJob);  // now it work.
```
* Environment
  * node.js 6.7.0 (npm 3.10.3)
  * OS: both Windows 10 and Ubuntu 16.04
  * Gulp 3.9.1

**Comment by eness** [comment]
you answered your own question dude, just don't use ./ as you've mentioned :)

**Comment by callumacrae** [comment]
@KiT106: What version of gulp are you using? If you're on gulp 3, I'd probably just recommend updating to gulp 4, which uses a different (better) watcher.

@eness: Nah, this is a bug report, not a support request.

**Comment by KiT106** [comment]
@callumacrae Gulp 3.9.1

**Comment by phated** [comment]
The gulp 3.x file watcher has many problems. You can upgrade to the gulp 4 branch, use the gulp-watch module or use chokidar directly.
