### ISSUE TITLE
Question: are there any good ways to run gulp in cluster mode for a web server?

### ISSUE THREAD

**Issue by jxcheng008** [gulpjs/gulp#1825]
are there any good ways to run gulp in cluster mode for a web server? I saw some solutions but not understand it..

**Comment by phated** [comment]
It seems you missed the part of our issue template that states "Support questions should be directed to StackOverflow".  It is not recommended to use gulp inside a web server; instead use the modules that make up gulp in the proper combinations.  Not only does that make it easier to stay up-to-date on the modules, web server workflows don't require all the parts gulp brings together.
