### ISSUE TITLE
how to get changed files in gulp.watch() callback with gulp 4?

### ISSUE THREAD

**Issue by dawanraoming** [gulpjs/gulp#1830]
how to get changed files in gulp.watch() callback with gulp 4?
in chokidar, this can be get
```javascript
var chokidar = require('chokidar');
chokidar.watch('/path/**/*.js').on('add', path=> {
  //in here, changed file path is the first argument to the callback
});
```

but in gulp 4, i don't know how to get changed files path in `gulp.watch()` callback
```javascript
var gulp = require('gulp');
gulp.watch('/path/**/*.js', function(){
//in here, how to get changed files?
});
```
-----------
Sorry, my english is not good.

**Comment by heikki** [comment]
https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#fn-1

**Comment by alxhghs** [comment]
@heikki the link above is now dead
