### ISSUE TITLE
Gulp watch not working on Node 4.6.0 version

### ISSUE THREAD

**Issue by IrvingArmenta** [gulpjs/gulp#1831]
Hello, I just had an issue with the updated 4.6.0 version of Node installed on my Windows PC.

I will (try to) explain my set up:

System: Windows 7 64x
Gulp version: 3.9.1
Node version: 4.6.0

I was working just fine before the update, i didn't change anything on my file, it gave me the indication to use "npm rebuild node-sass" i did, and it "worked" , however, the "watch" task doesn't work at all, and the scss files don't get compiled, only the "jsScripts" task is working, but "watch" finishes after 20ms, I'm using js lint and concatenation for JS, and gulp-sass for a very simple site, here is how my gulp file looks like, as it worked before:

```
var gulp = require('gulp');
   sass = require('gulp-sass');
   notify = require("gulp-notify");
   jshint = require('gulp-jshint'),
   uglify = require('gulp-uglify'),
   rename = require('gulp-rename'),
   concat = require('gulp-concat'),
   cssmin = require('gulp-cssmin'),

gulp.task('styles', function() {
    gulp.src('scss/**/*.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(cssmin())
        .pipe(rename({suffix: '.min'}))
        .pipe(gulp.dest('./stylesheets/'))
        .pipe(notify({ message: 'scss file compiled!' }));
});

gulp.task('jsScripts', function() {
  return gulp.src('./js/*.js')
    .pipe(jshint('.jshintrc'))
    .pipe(jshint.reporter('default'))
    .pipe(concat('web-app.js'))
    .pipe(gulp.dest('./js/output'))
    .pipe(rename({suffix: '.min'}))
    .pipe(uglify())
    .pipe(gulp.dest('./js/output'))
    .pipe(notify({ message: 'JS Scripts done!' }));
});

gulp.task('watch',function() {
    gulp.watch('scss/**/*.scss',['styles']);
    gulp.watch('./js/*.js', ['jsScripts']);
});

gulp.task('default', ['jsScripts', 'styles', 'watch']);

```
As I already said, it worked perfectly before Node 4.6.0, I'm not sure what the issue is.

**Comment by phated** [comment]
Anytime you upgrade node, you have to rebuild all native plugins.  This isn't a gulp issue.
