### ISSUE TITLE
Changes to parent dir before checking for gulpfile.coffee

### ISSUE THREAD

**Issue by ripexz** [gulpjs/gulp#1832]
```
project/
├─ gulpfile.js
└─ subdir/
  └─ gulpfile.coffee
```

**What were you expecting to happen?**
Running `gulp` in `/subdir`, I'd expect it to use `gulpfile.coffee`
Yes, I have `coffee-script` installed locally and it did work on a previous gulp version (I think I had 3.8.8 before, but possibly newer)

**What actually happened?**
```
~/project/subdir$ gulp
[13:34:15] Working directory changed to ~/project
[13:34:17] Using gulpfile ~/project/gulpfile.js
```

**What version of gulp are you using?**
CLI version 3.9.1
Local version 3.9.1

**What versions of npm and node are you using?**
node v6.3.0
npm v3.10.3

**Comment by callumacrae** [comment]
@ripexz: This was actually just fixed: is your dependency tree up to date?

https://github.com/gulpjs/gulp/issues/1823#issuecomment-253349513

**Comment by ripexz** [comment]
@callumacrae ah, I updated all deps and it works with `findup-sync@0.4.3`, thanks! 😄
