### ISSUE TITLE
Add an --assume-task-ran CLI option

### ISSUE THREAD

**Issue by hach-que** [gulpjs/gulp#1834]
I wasn't quite sure where to post feature requests; the issue text say this tracker is for bugs only, but the contribution guide recommends submitting them here?

Anyway, say you have a list of tasks like this:

- build
- test (depends on build)
- docker build (depends on test)
- docker push (depends on docker build)
- deploy (depends on docker push)

To gain visibility on these steps when running under Jenkins, you might think of doing something like this in a Jenkinsfile:

```
stage('Build'} { sh 'gulp build' }
stage('Test'} { sh 'gulp test' }
// ...
```

It's even more important for things like Docker, where accidentally running `docker build` in parallel increases build times (https://github.com/docker/docker/issues/9656), so you want to use Jenkins locks to prevent multiple docker steps running in parallel on the same node:

 ```
// ...
stage('Docker Build') {
  lock('docker') { sh 'gulp docker-build' }
}
// ...
```

The problem is that Gulp doesn't have an easy way of saying "this task has already run", and this means that running "docker-build" will cause "build" and "test" to run again, unless you add some sort of variant like `gulp docker-build-ignore-deps` (and then you need to do this for *every* task in your Gulpfile).  And while you want to skip these dependencies on a build server (where you know the previous steps have run), it's still very important that developers only have to do `gulp docker-build` to have everything work right.

So this is a feature request to be able to do something like:

```
gulp --assume-ran=test docker-build
```

which would effectively be the same as replacing the task declaration for test with:

```
gulp.task('test', []);
```

that is to say, not only does `test` no longer have any behaviour for this run, but all of the dependencies that it would in-turn bring in are removed from that particular task.  That doesn't stop those other dependencies from being brought in if say, another step was also required for `docker-build` that brought them in though.

I'm not quite sure where I would go about adding this to Gulp to submit a PR, since I'm not familiar with Gulp internals at all.

**Comment by phated** [comment]
You can implement this yourself with some helper functions. In gulp 4, this custom logic would become reusable with custom registries.
