### ISSUE TITLE
Mystery function in documentation for creating a plugin

### ISSUE THREAD

**Issue by keesey** [gulpjs/gulp#1835]
One the "Writing a plugin" page, under ["Modifying file content"](https://github.com/gulpjs/gulp/tree/master/docs/writing-a-plugin#modifying-file-content), the first code sample uses a function, `splitFile()`, which is neither defined nor referenced anywhere else.

**Comment by phated** [comment]
Treat that documentation as pseudo-code.

**Comment by keesey** [comment]
Oh, I see now. Could at least put a dummy like this to make clearer:

```
function splitFile(file) {
  // Create and return an array of vinyl file objects, based on the input file.
}
```

**Comment by phated** [comment]
Sure, feel free to submit a PR.
