### ISSUE TITLE
[Gulp 4]gulp.watch,a conflic between the file name & folder name.

### ISSUE THREAD

**Issue by uihoh0** [gulpjs/gulp#1837]
I'm using Gulp 4 to do some pre-compile in my project&use gulp.watch for auto compiling my \*.jade files to \*.html.Recently,I want to do some diffferent job between 'jade/\*.jade' and 'jade/\*\*/\*.jade' when they're edited.Then i add a new watch to do this.
```js
gulp.watch(['jade/*.jade'],function(){
      console.log('a')
})
```
**When i edit jade/course.jade,log 'a',right.**
**But when i edit jade/course/sth.jade,still log 'a',wrong.**
I've tried different globs but still can't solve the problem.
Finally i find out the problem.
**When i edit jade/only/one.jade nothing logged,right.**
**then i add a new file jade/only.jade,**
**re-edit jade/only/one.jade,logged 'a',wrong**
I'm quite sure it's a conflic between the  file name & folder name.

**What version of gulp are you using?**
Gulp 4
**What versions of npm and node are you using?**
node 6.9.0
npm 2.15.10

**Comment by phated** [comment]
You aren't signaling async completion in your watch task.

**Comment by uihoh0** [comment]
@phated Sorry,my bad.But the async completion just to help Gulp detect if the task done,so that it can move on to the next task,right?And now I did the signaling ,this issue is still.
```js
gulp.task('wt',function(){
    gulp.watch(['jade/*.jade'],function(done){
      console.log('hi12');
      done();
    })
});
```

**Comment by uihoh0** [comment]
I noticed that gulp.watch was base on chokidar.And tried to find some solutions on chokidar's repo.
And there were many similar Issues in chokidar.Now I'm sure this should be **a bug deeper than gulp and chokidar**.
I found a solution in this page [isssue#296](https://github.com/paulmillr/chokidar/issues/296).
By setting the option usePolling: true can just fix.More details about usePolling, check [chokidar's repo#performance](https://github.com/paulmillr/chokidar#performance).
```js
gulp.task('wt', {
    usePolling:true
  },function(){
    gulp.watch(['jade/*.jade'],function(done){
      console.log('hi12');
      done();
    })
});
```
@phated Thx 4 help.
