### ISSUE TITLE
A bug for gulp.dest

### ISSUE THREAD

**Issue by ImHype** [gulpjs/gulp#1842]
```javascript
var gulp = require('gulp');
gulp.task('default',  function() {
  return gulp.src('./src/mcss/**/*.mcss')
    .pipe(gulp.dest('./src/css'));
});
```
I just test this code. but the target files isn`t in *./src/css* directory.Please have a try and you will know~ 

My device is windows

**Comment by RIAstar** [comment]
Are your target files in `./src/css/src/mcss` ?

In that case I had the same issue last Friday on a fresh install on Windows.
I tracked it down to `vinyl-fs` > `glob-stream` > `glob-parent`

`glob-stream` published a patch update that contains a major update of `glob-parent`.
And just like that, all our builds are down.

Still need figure out whether it's a bug or a "feature" of `glob-parent`, but it sure smells like a bug.
The `base` path of the files on the stream are wrong:
for your example they went from `/path/to/src/mcss` to `/path/to` overnight.

**Comment by phated** [comment]
@RIAstar I'm pretty sure you were relying on some broken behavior because the changes you are referring to solved https://github.com/jonschlinkert/is-glob/issues/4 and https://github.com/jonschlinkert/is-glob/issues/5 

You are likely using Windows path separators which aren't valid glob paths.

**Comment by RIAstar** [comment]
Hah! I'm not using Windows path separators, but I'm using `path.join` to build some globs, which on Windows converts my forward slashes to backslashes.

Thanks for the tip, @phated .

**Comment by thauk-copperleaf** [comment]
@RIAstar Thanks for that, the update to vinyl 2.0.0 seems to be the source of the issue. The build tooling for my project was updated to gulp 4 without my knowledge and this bug has also broken the asset pipeline build for me on Windows.

@phated Not sure what is exactly the broken behaviour you are suggesting exists. That glob pattern looks reasonable to me. What ends up happening locally is that all the files are correctly matched, but they are not copied like loose files into the destination; rather, they are copied with a matching nested directory structure into dest. This is surprising behaviour.

**Comment by phated** [comment]
The slashes windows uses for separators are escape characters in a valid glob string so they can't be used as separators. We weren't properly supporting escape characters and now we are. You were relying on broken behavior.

**Comment by thauk-copperleaf** [comment]
@phated If the example relies on "broken behaviour", it might be instructive to explain (with an example) how to correctly create a gulp task to copy files using a glob, that works on Windows

**Comment by phated** [comment]
The gulp team has limited resources. Feel free to submit a PR correcting any mistakes in examples/samples/recipes or docs. Thanks!

**Comment by thauk-copperleaf** [comment]
@phated I understand how OSS projects have limited resources! I contribute to a few myself. And I'd love to submit a PR if I could. But how can I a submit a PR to correct a mistake, if I don't know what the mistake is, because when you tell me the example is broken, you won't tell me how it's broken?

More straightforwardly: if you say there's broken behaviour, please educate me on what you mean... please don't close the issue.

**Comment by phated** [comment]
You can do further reading at https://github.com/isaacs/node-glob/blob/master/README.md#windows

You keep saying that example is wrong, so please submit a PR fixing it. Thanks! 

The original issue was a support question which should be directed to StackOverflow. The follow up questions were tangentially related and answered so this belongs closed. Thanks for following up.
