### ISSUE TITLE
node 7 support / graceful-fs / gulp 4

### ISSUE THREAD

**Issue by thojansen** [gulpjs/gulp#1843]
Node7 is now officially released. Any plans to release gulp4 soon? Right now gulp fails due to the `graceful-fs` dependency.

```
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/xxx/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:32:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

**Comment by piotr-cz** [comment]
same here.
I've tried reinstalling nodejs v7.0.0, different npm versions before realizing it's related to gulp.

Node 7 has been released yesterday

**Comment by contra** [comment]
For now: `npm install gulpjs/gulp#4.0`

**Comment by neilsoult** [comment]
@contra tried that, but now getting:
```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Task function must be specified
```

**Comment by contra** [comment]
@neilsoult 4.0 has a bunch of new changes, check out the docs: https://github.com/gulpjs/gulp/tree/4.0

As for 3.x supporting Node 7, it's really up to the dependency being used (graceful-fs) to make this work. We can't update the dependency on the 3.x branch because it introduced breaking changes, so graceful-fs would have to backport a fix.

**Comment by neilsoult** [comment]
@contra ok thanks, looks like the path of least resistance for now is to use node v6.9.1

**Comment by phated** [comment]
Yeah, there's nothing we can do about this which is why I re-opened https://github.com/gulpjs/gulp/issues/1571

gulp 3.x used gaze which had a graceful-fs 1.x dependency.  We've worked with graceful-fs to solve the problems in 2+ but the fix wasn't able to be backported to 1.x.

**Comment by toby1991** [comment]
yarn will help u

**Comment by dodge107** [comment]
Just got this working with Gulp@3.9.1 and node 7 - it loaded graceful-fs@3.0.11.

**Comment by piotr-cz** [comment]
@dodge107 
Did you install graceful-fs separately?

**Comment by dodge107** [comment]
no - just edited my package.json  file as follows:

`"gulp": "^3.9.1",`

and ran npm install - small waring but worked.

**Comment by Martinspire** [comment]
So i'm guessing one of the submodules has been updated to work with graceful properly?

**Comment by chicoxyzzy** [comment]
Confirmed. It works.

**Comment by trevorhreed** [comment]
Followed @dodge107 instructions. I also had to delete my `/node_modules/` folder before running `npm install`, and then it finally worked.

**Comment by paulthealien** [comment]
Removing the dir `node_modules/` and running `npm i` solves the issue. Thanks @trevorhreed

**Comment by tkarls** [comment]
Confirmed. Removing node_modules and "npm -install" works.
In my case it resolved to gulp@3.9.1 with graceful-fs@3.0.11

Strange that a npm upgrade did NOT work. Didn't investigate more than this but I thought that npm upgrade would give the same result as a clean npm install. But perhaps not.

**Comment by app-sparkler** [comment]
+1 @dodge107

**Comment by feizhang365** [comment]
saved my day
Followed @dodge107
1.edited package.json file as follows:
"gulp": "^3.9.1",
2.Removing the dir node_modules/
3.npm install
It works
