### ISSUE TITLE
gulp.watch does not emit deletion events for directories or their files on directory deletion

### ISSUE THREAD

**Issue by birjolaxew** [gulpjs/gulp#1844]
Tested in gulp 4.0 and gulp 3.9.1.
When a watched directory is deleted, no events are fired for directories or their files.

With the following initial folder structure:

```
test
├── dir
│   └── foo
└── test
```

These actions are executed manually:

1. Create folder `test/dir2` (should emit `addDir - test/dir2`)
2. Create file `test/dir2/foo` (should emit `add - test/dir2/foo`)
3. Create file `test/dir2/bar` (should emit `add - test/dir2/bar`)
4. Delete file `test/dir2/bar` (should emit `unlink - test/dir2/bar`)
5. Delete folder `test/dir2` (should emit `unlinkDir - test/dir2` and/or `unlink test/dir2/foo`)
6. Delete folder `test/dir` (should emit `unlinkDir - test/dir` and/or `unlink test/dir/foo`)
7. Delete file `test/test` (should emit `unlink - test/test`)

As can be seen below, the watch listener is never informed of the deletion of `test/dir2` or `test/dir`, nor that of the `foo` file in either of them.

----

**gulpfile.js (gulp 4.0):**

```javascript
var gulp = require("gulp");
gulp.task("test", function(){
  return gulp.watch("test/**/*")
    .on("all", function(event, path) {
      console.log(event+" - "+path);
    });
});
```

**Expected output:**

```
addDir - test/dir2
add - test/dir2/foo
add - test/dir2/bar
unlink - test/dir2/bar
unlinkDir - test/dir2    (and/or unlink test/dir2/foo)
unlinkDir - test/dir     (and/or unlink test/dir/foo)
unlink - test/test
```

**Observed output:**
```
addDir - test/dir2
add - test/dir2/foo
add - test/dir2/bar
unlink - test/dir2/bar
unlink - test/test
```

**Comment by phated** [comment]
I believe delete events are really hard to listen to.  This would be something for you to research in relation to gaze and chokidar.
