### ISSUE TITLE
gulp.watch - wrong event handler argumet

### ISSUE THREAD

**Issue by retan** [gulpjs/gulp#1845]
The even handler on gulp.watch change event doesn't get an event object but a filepath.
When I tried a simplified code from the docs:
```js
    var watcher = gulp.watch('app/assets/**/*');
    watcher.on('change', function(event) { // <-- never fires
      console.log('File ' + event.path + ' was ' + event.type);
    });
```
what the console displayed was:
```
File undefined was undefined
```

A changed version of this code
```js
   var watcher = gulp.watch('app/assets/**/*');
    watcher.on('change', function(event) { // <-- never fires
      console.log('event = ' + event + ', typeof event = ' + typeof event);
    });
```
outputs:
```
event = app\assets\img\fb.svg, typeof event = string
```
What I expect is to get event as an object with path and type properties.
I need this to implement the procedure explained here: https://github.com/gulpjs/gulp/blob/master/docs/recipes/incremental-builds-with-concatenate.md

npm -v: 3.10.8
node -v: v6.9.1
CLI version 1.2.2
Local version 4.0.0-alpha.2

**Comment by phated** [comment]
I believe chokidar only gives you that object when you listen to the "all" event.

Be aware that most of our 4.0 docs are out of date so be careful taking them verbatim.
