### ISSUE TITLE
Error: Requiring external module coffee-script/register

### ISSUE THREAD

**Issue by artelse** [gulpjs/gulp#1846]
When gulp starts up, it brings up this error: `Requiring external module coffee-script/register`. I looked around to solve this error, but have not been able to. I made sure `coffee-script` is local in `node_modules` and have tried different versions of `node` to see if that would nail it down.
So this happens before a `Gulpfile.coffee` is even loaded.
`gulp 3.9.1 and npm 2.14.20`

**Comment by citycide** [comment]
Someone can correct me if I'm wrong but I'm pretty sure this is not an error. Gulp is just telling you it's using `coffee-script/register` to pre-compile your build scripts.

[See here.](https://github.com/gulpjs/gulp/blob/de1acf66a6253302c856971f8c00f65ea6c63882/bin/gulp.js#L52-L58) No `throw` or error-related terms in sight, it's just logging it. ( unless of course it actually fails to load the module )

**Comment by contra** [comment]
Yeah, not an error.

**Comment by artelse** [comment]
Thanks for the clarification this is not an error but a statement. Perhaps the logging text could be changed to be less ambiguous?

**Comment by contra** [comment]
@tkellen ^

**Comment by phated** [comment]
@contra this is in gulp CLI, not liftoff.  Also, it is red when it says "failed" but I think that is proper.  The message from the original issue is a success and it is colored the same as the rest of the output.  I see nothing to change here.

**Comment by artelse** [comment]
@phated @contra But what if it just said `Loaded required module..` than there is no doubt about its meaning. For gulp newbies and non-natives like myself, it'll be very helpful.

**Comment by tkellen** [comment]
How about:
```js
`External module ${chalk.magenta(name)} loaded.`
chalk.red(`External module ${name} not found.`)
```

**Comment by artelse** [comment]
And in non-error messages no color with red in it, green?
