### ISSUE TITLE
Alternative to gulp.task and gulp.run

### ISSUE THREAD

**Issue by alanrivetta** [gulpjs/gulp#1848]
Hello everyone.

I need to do this

````javascript
taskWatch = function () {
  diffs = getDiffFromFiles('file1','file2');

  diffs.forEach(function(task){
      task = "..." //...
      gulp.task(task) //gulp.run(task)
    })
}
````
But Gulp 4 gulp.task was removed and gulp.run

an alternative?

Thank you very much

**Comment by phated** [comment]
Just call the function.  You can even chain plain functions with `gulp.series(fn1, fn2, ...)`
