### ISSUE TITLE
gulp.src can't match file like .gitignore or .babelrc

### ISSUE THREAD

**Issue by Krispomoho** [gulpjs/gulp#1849]
I have met a problem ,when I want to use gulp to move files from one directory to another directory, gulp will miss the file like `.gitignore` or `.babelrc`.

├─┬ source
│ ├── hello.txt
│ ├── .gitignore
│ ├── .babelrc

Here is my code, I put it in a javascript file, and run it with node.
`vargulp = require('gulp');`
 `gulp.src('source/**/*').pipe(gulp.dest('./dest'))`

after run this file, only hello.txt has been moved normally.
├─┬ dest
│ ├── hello.txt

**Comment by doowb** [comment]
Use `{dot: true}` in `gulp.src` to enable finding `dotfiles`:

```js
gulp.src('source/**/*', {dot: true}).pipe(gulp.dest('./dest'));
```

**Comment by callumacrae** [comment]
Thanks, @doowb 😄
