### ISSUE TITLE
Broken links in guidelines

### ISSUE THREAD

**Issue by MattMS** [gulpjs/gulp#1851]
The [gulp-header](https://github.com/godaddy/gulp-header) and [gulp-footer](https://github.com/godaddy/gulp-footer) links on the [guidelines page](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) result in a 404.

Should these be updated to the NPM package pages for [header](https://www.npmjs.com/package/gulp-header) and [footer](https://www.npmjs.com/package/gulp-footer) instead?

I got those NPM links from a quick Google search, and have not used them before, so I am not sure if they are correct.

**Comment by phated** [comment]
Please submit a PR.  Thanks!

**Comment by benhalverson** [comment]
@phated I can make a quick PR for this. Should the [gulp-concat](https://github.com/contra/gulp-concat) link also point to the [npm link](https://www.npmjs.com/package/gulp-concat)?
