### ISSUE TITLE
Publish Gulp 4 as Beta

### ISSUE THREAD

**Issue by ChadKillingsworth** [gulpjs/gulp#1853]
I've been watching the development and progress of Gulp 4 for some time (I'm aware of the milestones). Is it possible however to publish Gulp-4 as-is to npm with a beta tag (not latest)? This would allow more projects to start using it.

**Comment by phated** [comment]
Unfortunately pre-release versions on npm are very finicky (npm doesn't even use them for their betas).  We have a release process documented at https://github.com/gulpjs/gulp/issues/1486

gulp 4 still has a few milestones to hit in the dependencies before it can be released with the `next` tag.  Once published, everything becomes mostly locked to follow proper semver, so those milestones must be reached before being published.
