### ISSUE TITLE
npm install gulp ERROR

### ISSUE THREAD

**Issue by cmb97** [gulpjs/gulp#1855]
Can anyone there please help me with this error? 
**I can't install gulp through npm**
I'm getting the following error:

C:\node\demo>npm install gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
demo@1.0.0 C:\node\demo
+-- archy@1.0.0  extraneous
+-- chalk@1.1.3  extraneous
+-- deprecated@0.0.1  extraneous
+-- interpret@1.0.1  extraneous
+-- liftoff@2.3.0  extraneous
+-- minimist@1.2.0  extraneous
+-- orchestrator@0.3.8  extraneous
+-- pretty-hrtime@1.0.3  extraneous
+-- semver@4.3.6  extraneous
+-- tildify@1.2.0  extraneous
+-- v8flags@2.0.11  extraneous
`-- vinyl-fs@0.3.14  extraneous

npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! path C:\node\demo\node_modules\.staging\spdx-correct-0af5c0e3\package.json.4066678607
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\node\demo\node_modules\.staging\spdx-correct-0af5c0e3\package.json.4066678607' -> 'C:\node\demo\node_modules\.staging\spdx-correct-0af5c0e3\package.json'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\node\demo\node_modules\.staging\spdx-correct-0af5c0e3\package.json.4066678607' -> 'C:\node\demo\node_modules\.staging\spdx-correct-0af5c0e3\package.json'
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\node\\demo\\node_modules\\.staging\\spdx-correct-0af5c0e3\\package.json.4066678607',
npm ERR!   dest: 'C:\\node\\demo\\node_modules\\.staging\\spdx-correct-0af5c0e3\\package.json',
npm ERR!   parent: 'demo' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node\demo\npm-debug.log

**Comment by bananaappletw** [comment]
@cmb97 
It seem like you don't have right privilege to install it.
Try to install `nvm`?
Then you don't need root privilege.

**Comment by contra** [comment]
NPM issue, nothing to do with gulp. Closing this. If you still have issues open a ticket on the npm tracker (https://github.com/npms/npm)
