### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

### ISSUE THREAD

**Issue by JonDotsoy** [gulpjs/gulp#1856]
With `gulp.dest` in Node v7 show this Warning.

```bash
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```

That is deprecated and replaced on Node V7.

<https://nodejs.org/api/buffer.html#buffer_new_buffer_buffer>

**Comment by terinjokes** [comment]
Since we target back to 0.10, were going to need to use a shim for the newer methods.

**Comment by phated** [comment]
Thanks, this will be looked into for gulp 4.
