### ISSUE TITLE
Files run through gulp have repeated characters at end

### ISSUE THREAD

**Issue by ericnewton76** [gulpjs/gulp#1857]
gulp dest randomly repeating lines at end of file(s).

this happens a lot, but randomly.  guessing there's an unflushed buffer somewhere.

EDIT: actually, it more looks like a double flushed buffer somehow... 

![image](https://cloud.githubusercontent.com/assets/2211788/20292251/21eedeaa-aaba-11e6-8c4c-0202961587d8.png)

**Comment by ericnewton76** [comment]
>npm list gulp
arbor-memorial-shared-memories@0.0.1 C:\Projects\ArborMemorial\sharing-memories
`-- gulp@3.9.1

package.json:
{
  "name": "arbor-memorial-shared-memories",
  "version": "0.0.1",
  "description": "Arbor Memorial Shared Memories Site",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "ssh://git@bitbucket.org/lightmakerusa/arbor-memorial-shared-memories.git"
  },
  "author": "Efrain Lugo and Kurt Johnson and Eric Newton",
  "license": "BSD-2-Clause",
  "devDependencies": {
    "bem-jade": "^0.1.2",
    "coffee-script": "^1.10.0",
    "connect-livereload": "~0.5.3",
    "express": "~4.13.3",
    "gulp": "^3.9.0",
    "gulp-bless": "~3.0.1",
    "gulp-changed": "~1.3.0",
    "gulp-coffee": "~2.3.1",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "~2.4.0",
    "gulp-if": "^1.2.5",
    "gulp-jade": "~1.1.0",
    "gulp-jslint": "^0.2.2",
    "gulp-minify-css": "^1.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-notify": "~2.2.0",
    "gulp-prettify": "~0.3.0",
    "gulp-sass": "~2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-svg-sprite": "^1.2.10",
    "gulp-svg2png": "^0.3.0",
    "gulp-svgmin": "^1.2.0",
    "gulp-uglify": "^1.4.1",
    "gulp-util": "^3.0.7",
    "imagemin-pngcrush": "~4.1.0",
    "jade": "^1.9.2",
    "node-bourbon": "^4.2.3",
    "serve-favicon": "~2.3.0",
    "tiny-lr": "0.2.1",
    "vinyl": "^1.1.0",
    "gulp-sourcemaps": "^1.6.0"
  }
}

**Comment by callumacrae** [comment]
Does it only happen with one task or does it happen with all? Could you post your gulpfile?

**Comment by ericnewton76** [comment]
![image](https://cloud.githubusercontent.com/assets/2211788/20310968/e905b958-ab1b-11e6-86a7-e72df2feb8df.png)

here's another run, different file affected (that I noticed)

**Comment by ericnewton76** [comment]
Attaching the gulpfile here:
[gulpfile.js.txt](https://github.com/gulpjs/gulp/files/592358/gulpfile.js.txt)

**Comment by ericnewton76** [comment]
Stand by, I'm doing massive updates to our gulpfile for this project, it doesn't meet our standards atm.

Updates will probably mask away this problem unfortunately.

**Comment by callumacrae** [comment]
It's happening on more than one machine? That's very strange 😦 

Is it just happening with one task (looks like the build-coffee or build-js tasks), or all of them?

**Comment by mayorovp** [comment]
In attached gulpfile one file writen to one dest file via two different pipelines.

Here is minimal example to reproduce the bug:

    var gulp = require('gulp');
    var stream = require('stream');
    var File = require('vinyl');
    
    var cc = [1, 2].map(i => {
        const file = new stream.Readable();
        file._read = function () { }
    
        gulp.task("t" + i, function () {
    
            var dst = gulp.dest('dst')
            dst.write(new File({
                base: 'src',
                path: 'src/foo.txt',
                contents: file,
            }))
            dst.end()
    
        })
    
        return file;
    })
    
    gulp.task('default', ['t1', 't2']);
    
    setTimeout(() => {
        for (var i = 0; i < 5; i++) {
            cc[0].push("00")
            cc[1].push("1")
        }
        cc[0].push(null)
        cc[1].push(null)
    }, 100)

This example copies to `dst/foo.txt` file two source files, with '0000000000' and '11111' content. I used virtual source files to simulate async pipeline processing.

Expected behavior:

- 'dst/foo.txt' content is '0000000000';
- **or** 'dst/foo.txt' content is '11111';
- **or** an error.

Actual behavior:

- 'dst/foo.txt' content is '1111100000';

**Comment by phated** [comment]
I believe that is the expected behavior of node, since both streams are being created synchronously (thus both truncating at the same time) and then both have access to the file descriptor and write to it.

This is an extremely bad pattern to be using but isn't actually a bug.

**Comment by phated** [comment]
@mayorovp thanks for making a minimal reproduction so I could verify.
