### ISSUE TITLE
Global install of CLI installs under User profile instead of true "Global"

### ISSUE THREAD

**Issue by pjc2007** [gulpjs/gulp#1858]
npm version 3.10.8 on Windows 10

Running **npm install --global gulp-cli**, the installation ends up under my current user app *data* location.
e.g 

C:\Users\<myusername>\AppData\Roaming\npm\gulp
C:\Users\<myusername>\AppData\Roaming\npm\gulp.cmd

On our build machine we log in as a different user to what the build system runs, so this location is no good to us.

Would be good if all global installs could go to the Program Files (or Program Files (x86) as node itself does.

**Comment by callumacrae** [comment]
Use `npm config get prefix` and `npm config set prefix` to change where it installs.

Alternatively, use the local install of gulp by running `gulp` from a npm script, or running `./node_modules/.bin/gulp`.

This isn't a gulp issue (it's npm), so I'm going to close this - you'd probably get a quicker answer on stackoverflow.
