### ISSUE TITLE
Version is not clear in the docs

### ISSUE THREAD

**Issue by twifty** [gulpjs/gulp#1865]
Google searches for most things gulp related tend to bring up the docs at https://gulp.readme.io/docs

For which version are they exactly?

The top banner on the page states v1.0, the current release of gulp is v3.9.1, but the methods and options on that page look more like v4. It is very confusing, so much so that another search is required.

Perhaps that page could feature a drop down box for quickly toggling between v3 and v4, much like Symfony (php) does with their docs.

**Comment by phated** [comment]
That was an experiment with readme.io for gulp 4 docs.  I believe we decided to move away from that service.  I'll look into deleting it from readme.io
