### ISSUE TITLE
Gulp doesn't work with ES6 import syntax

### ISSUE THREAD

**Issue by alayek** [gulpjs/gulp#1867]
I tried to import Gulp in my Gulp file as follows:

```js
import { src, dest, task } from 'gulp';
```

And I am using it like this

```js
task('html', () => (
  src('app/**/*.html)
  .pipe(htmlMin())
  .pipe(dest('dist/'));
))
```

This fails with an error message that `undefined has no array called tasks`

I did a workaround for the time being

```js
import gulp from 'gulp';
const src = gulp.src.bind(gulp);
const task = gulp.task.bind(gulp);
const dest = gulp.task.bind(gulp);
```

After the above `bind` statements, this worked as expected.

I was hoping Gulp would support this out of the box; without me having to bind `this`. Is this on Gulp 4 milestone?

Node Version: `v6.9.1`
Gulp Version: 
```bash
$ gulp -v
[1:37:07] CLI version 1.2.2
[1:37:07] Local version 3.9.1
```

**Comment by CodeTheory** [comment]
I think you have to use Gulp 4 and babel for this. I use it here: https://github.com/wulkano/kap/blob/master/gulpfile.babel.js#L1

**Comment by alayek** [comment]
@CodeTheory Thanks for the help. I will try it out with Gulp 4, but I hope you understand my question.

I _am_ using babel, to parse the Gulpfile; **not** to compile other ES6 code in my repo.

---

I noticed that you are `export`ing the tasks. Maybe that's making a difference, which is why you are not facing the `bind(this)` issue?

**Comment by callumacrae** [comment]
Yep, support for this was added in Gulp 4.
