### ISSUE TITLE
WARN deprecated graceful-fs

### ISSUE THREAD

**Issue by marti1125** [gulpjs/gulp#1870]
> Gulp uses "graceful-fs": "^3.0.0"

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Can I send a PR with this fix?

**Comment by demurgos** [comment]
Looks like there is already [an open issue](https://github.com/gulpjs/gulp/issues/1571) about the warning.

As for the problem with node 7, `gulp@3.9.1` and above seems to work.

**Comment by marti1125** [comment]
@demurgos ups =/
