### ISSUE TITLE
Is it possible to get a v3.9.2 of Gulp while we wait for v4?

### ISSUE THREAD

**Issue by valera-rozuvan** [gulpjs/gulp#1877]
The main reason is that Gulp v3.9.1 uses:

```
"vinyl-fs": "^0.3.0"
```

which in turns pulls down old version of **graceful-fs** (pre v4). If at all possible, can we get a Gulp v3.9.2 release with **vinyl-fs 2.4.4**? I am willing to create a PR :)

**Comment by beufordy3k** [comment]
I would be interested in this as well.

**Comment by phated** [comment]
Nope. Those are breaking changes.
