### ISSUE TITLE
Global Gulp install - question

### ISSUE THREAD

**Issue by Vengefull** [gulpjs/gulp#1885]
Why we are not able to use Global Gulp install. 
Isn't it a bit odd to "force" people to install dev/build tool per project + adding it to the project itself since it's main usage (at least for me) is for development.

**Comment by callumacrae** [comment]
You don't have to install it globally, you can run the local version:

```
./node_modules/.bin/gulp build
```

Or you can add it to your npm scripts, and it'll run the local version:

```
  "build": "gulp build"
```

Unfortunately, it isn't possible to use just the global install because of how npm works.
