### ISSUE TITLE
Gulp Plugin Error

### ISSUE THREAD

**Issue by kingsae1** [gulpjs/gulp#1887]
Gulp Plugin site error

http://gulpjs.com/plugins/
error : angular is not defined

**Comment by JPeer264** [comment]
In my case there is no such error. Where do you get this exactly and what did you do?

**Comment by kingsae1** [comment]
In my case, i use chrome browser. and when i click plugins on the button, the site return timeout

GET http://gulpjs.com/plugins/js/vendor.js net::ERR_CONNECTION_RESET
app.js:1 Uncaught ReferenceError: angular is not defined

I thought it cannot load vendor.js file. Please check the file and whether correct module or not

vendor.js	(failed)	script	(index):49	8.3 KB	2.1 min

**Comment by callumacrae** [comment]
I'm unable to replicate this. Is it still happening for you?

Also, where are you trying to access the site from? (country)

**Comment by JPeer264** [comment]
Maybe it is also possible that you cached an older `vendor.js`. Try to open it on another browser, incognito mode or delete your cache.

**Comment by kingsae1** [comment]
Now I didn't delete cache in my browser but it's done. I don't know why it is unable to open this site before. 
Thanks for your comment ^^

**Comment by JPeer264** [comment]
@kingsae1 Glad to hear that. Please close this issue, as it is solved.
