### ISSUE TITLE
Docs v4: Example folder instead of examples in readme

### ISSUE THREAD

**Issue by JPeer264** [gulpjs/gulp#1890]
I would suggest a small improvement for the docs in Gulp v4. Isn't it better to have an example folder `./examples` and put everything what is in `#sample-gulpfilejs` into an own file (`./examples/gulpfile.js`) ? Including `#use-last-javascript-version-in-your-gulpfile` into (`./examples/gulpfile.babel.js`).

I can do a PR if you think it is better.

**Comment by phated** [comment]
@JPeer264 the new docs are going to be generated with Gitbook so I don't think putting JS files for the examples will work.
