### ISSUE TITLE
Gulp/Ruby Error! Gem cmd is not installed

### ISSUE THREAD

**Issue by MetaVisual** [gulpjs/gulp#1893]
I have poured at least 8 hours into troubleshooting with no avail to get Gulp/Ruby to work properly. I am taking a course on sass fundamentals and have downloaded its repository from github. I am running Windows 7 64-bit.

I also installed git bash, as well as, ruby, sass, and gulp from the git bash cmd line. I am able to run everything properly until running the 'gulp' command.

All the research I have seen on stackoverflow has not produced any answers unfortunately. I have attached images that show my errors, versions of all in git, and my environmental variables paths in Windows 7.

****When running gulp, I get error: 
" [22:32:30] Finished 'webserver' after 15 ms
Error! Gem cmd is not installed."**
errorInBashGulp**

When doing a search it stated that my path in environmental variables needs to be directed to the ruby folder, which it is.

****Also, when I save the .scss file in Atom, I get the other error:
" 'node-sass' is not recognized as an internal or external command,
operable program or batch file."**
errorInAtomOnSave
![errorinbashgulp](https://cloud.githubusercontent.com/assets/17764585/22377345/85780bfa-e47f-11e6-90e9-27bafa2e214f.jpg)
![versions](https://cloud.githubusercontent.com/assets/17764585/22377351/8a582c9a-e47f-11e6-8d84-b3cc248e45af.jpg)
![errorinatomonsave](https://cloud.githubusercontent.com/assets/17764585/22377354/8e4ad488-e47f-11e6-96e1-ad817f5c42bc.jpg)
![rubyfolder](https://cloud.githubusercontent.com/assets/17764585/22377356/91e6be40-e47f-11e6-90a1-7a2fc3200bbe.jpg)
![environmentalvariables](https://cloud.githubusercontent.com/assets/17764585/22377359/938d7dba-e47f-11e6-97b1-3d485795d198.jpg)

**

I have uninstalled/reinstalled ruby 3 times and get the same error. Not sure what to do or what the problem actually is... Any help would be great. Thanks so much!

Chris Davis

**Comment by mike3run** [comment]
i don't think this has something to do with gulp but more with sass, node-sass or gulp-sass 😄

**Comment by phated** [comment]
Sorry but this is not a support forum. Please direct your support questions to StackOverflow.
