### ISSUE TITLE
Nunjucks content partially escaped when passing through gulp cheerio

### ISSUE THREAD

**Issue by oleersoy** [gulpjs/gulp#1896]
Hi,

I'm using [Gulp Cheerio (Issue Link)](https://github.com/knpwrs/gulp-cheerio/issues/17) to process some content that is first rendered with Nunjucks.  In short I end up with the Nunjucks rendered content partially escaped and I have detailed out what happens further on [SO here](http://stackoverflow.com/questions/41819997/gulp-cheerio-is-partially-escaping-html-elements).

I'm not quite sure whether it is a Gulp, Gulp-Cheerio, or Cheerio is causing the issue.  Was wondering if anyone might be able to help shed some light on it?

The repository containing the [superfly-css-gulp-task is here](https://github.com/superfly-css/superfly-css-task-test).

To reproduce the results described in the [SO post](http://stackoverflow.com/questions/41819997/gulp-cheerio-is-partially-escaping-html-elements) and [Gulp Cheerio Issue Link](https://github.com/knpwrs/gulp-cheerio/issues/17) first:
1) Clone the repository`git clone https://github.com/superfly-css/superfly-css-task-test`
2) Run `cd cd superfly-css-task-test && npm install`
3) Run `gulp test:css`

To see the tests results `cat target/test/html/index.html`.  The test source is contained in `src/test/html/index.html`.

TIA for any help with this.
Ole

**Comment by phated** [comment]
Likely nothing to do with gulp and we don't track plugin issues.
