### ISSUE TITLE
gulp.watch in windows

### ISSUE THREAD

**Issue by reskwer** [gulpjs/gulp#1903]
I apologize for my English, translated google translate.

Gulp.wathc in windows 10
`gulp.watch('./app/style/**/*.styl', gulp.series('style'));`

Problem: each time you re-save the file, time executable Tasks progressive increases.
Re-save the file: 18 races in a row `app/stylus/helpers/my-mixin.styl`

![image](https://cloud.githubusercontent.com/assets/8849299/22609426/3ad4b47e-ea72-11e6-8ac3-9b62195949b5.png)
![image](https://cloud.githubusercontent.com/assets/8849299/22609559/b39d3d0e-ea72-11e6-91be-33b8a89348f1.png)

35 re-save

![image](https://cloud.githubusercontent.com/assets/8849299/22609785/96533aae-ea73-11e6-9ced-cbd7ce4f9857.png)

But, if you re-save files in the root folder `app/style` while the execution of the Task does not exceed 300ms, for the test now will in turn re-save 2 files

`app/style/style.styl`
`app/style/helpers/my-mixin.styl`

![image](https://cloud.githubusercontent.com/assets/8849299/22610058/ae6f9aaa-ea74-11e6-89ea-b0c7f9591ad7.png)

Conclusion if in a gulp.watch to specify the path to all subfolders and files, then these files are re-stored for a very long time.
But if you re-save the file which is not beyond casinoi folder - then all works quickly and well. 

PS. Stylus nothing to do with this behavior occurs on all files, js, css, stylus, sass. This bug was in Gulp 3 and now is in Gulp 4, and is not dependent on the computer capacity. 

Please help with a solution to this problem, forces are not present more to work with.

this my gulp4 project  - https://github.com/reskwer/blank

**Comment by phated** [comment]
This is a duplicate issue. Please use search.
