### ISSUE TITLE
npm install gulpjs/gulp#4.0 not working

### ISSUE THREAD

**Issue by ilyapashkov** [gulpjs/gulp#1907]
Hi boys, i use 'npm install gulpjs/gulp#4.0' on windows 10 with Node JS 6.9.5, its not working

**Comment by callumacrae** [comment]
What error are you getting? Is it a gulp issue or an npm issue?

**Comment by OliverMarcetic** [comment]
Same here...
![screenshot](https://cloud.githubusercontent.com/assets/10829721/22711687/66f1ddda-ed82-11e6-944a-cea6b61dc786.png)

**Comment by contra** [comment]
NPM issue - try clearing your cache + making sure you have git installed + making sure your network is okay. If not, open an issue at the npm project.

**Comment by decoded4620** [comment]
Hey all, I ran into a similar issue and I can assure you it has little to do with `NPM` . Its windows `CMD` that causes the pain. I solved the problem on Windows by simply opening Git Shell (Downloaded with GitHub Desktop). When I run the command in Git Shell, the install works as expected. I suspect that the `PATH` or other `ENV` Variables might be different when Git is running from Git Shell.

**Comment by georgemeehan** [comment]
I too, am having the same issue and I am using git bash. I've tried clearing the cache as suggested above but still received the following error message.
```
npm WARN using --force I sure hope you know what you are doing.

George@DESKTOP-76RAALH MINGW64 ~/Desktop/projects/gulpstart
$ npm install gulpjs/gulp-cli#4.0 -g
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\mingw64\bin\git.EXE checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
npm ERR!
```

**Comment by demurgos** [comment]
@georgemeehan You are confusing `gulp` and `gulp-cli`. 

To install the CLI, just do `npm install -g gulp-cli`, it is compatible with any local Gulp 3 and Gulp 4 version.

**Comment by georgemeehan** [comment]
@demurgos I was following a set of instructions that said to install gulp 4 globally that way.

**Comment by demurgos** [comment]
@georgemeehan 
Not sure which kind of tutorial you were following but it means that they have an error. Use the official documentation.

```
# Globally
npm install -g gulp-cli
# Inside your project
# For Gulp 4:
npm install gulp@next
# For Gulp 3:
npm install gulp
```
