### ISSUE TITLE
zsh: command not found: gulp

### ISSUE THREAD

**Issue by uistudio-de** [gulpjs/gulp#191]
Hi Guys ... 
can someone please help me? I installed gulp (global) (npm install -g gulp) as described in the Getting Started section. then I created the file gulpfile.js. When I type in the terminal gulp I just get zsh: command not found: gulp. 

when I type in terminal echo $path I get: 
/ Usr / bin / bin / usr / sbin / sbin / usr / local / bin / Users / leonardo / .rvm / bin 

everything else works except Gulp. 
My system is OSX.10.9 mavericks.

thanks for any help

**Comment by jhsveli** [comment]
I came here googling for solutions to a similar issue on Ubuntu 14.04, with zsh. I had switched npms global prefix to ~/npm and added this to path "~/npm/bin". This gave me command not gound: gulp. 

Solution was adding: "$HOME/npm/bin" instead

Probably blatantly obvious to most, but thought I'd mention it here on the #1 hit in my search

**Comment by ryandeussing** [comment]
Also, after adding `$HOME/npm/bin` to your path, you probably need to re-install with `npm install -g gulp`

**Comment by iparr** [comment]
I had to use `$HOME/.npm-global/bin` instead. I presume it has changed because of reasons 🤷‍♂️

**Comment by phated** [comment]
You should always use `npm prefix -g` to find where npm is installing your packages globally, in case they update the location.
