### ISSUE TITLE
Gulp is not running tasks in parallel

### ISSUE THREAD

**Issue by pnayyar** [gulpjs/gulp#1911]
Hello,

I'm new to this gulp and have searched enough here for the problem I am looking at.

Problem:
I have a gulp task that I want run for different regions (against an array). 
I created a function to create stream and do the job. I created a gulp task which calls this function in a loop against the array elements.
Some of the tests in the task (stream) takes lot of time, so I want to run it in parallel.

The idea is, while I want my gulp task to run in parallel, I also want to generate a report later and consolidate all the results in a table.

While i searched for answers on this forum I see people want to run it in sequence, and I have a contract that gulp is not running in parallel for me.

Here is how my gulpfile.js looks like:-
```
//function to create stream of task
function regionalSuite (awsRegion, done) {
      global.awsRegion = awsRegion;  
      console.log("\n\n Tests running for Region :: ", awsRegion);
      var stream = gulp.src(['test/apis/**/*_spec.js'])
               .pipe(plugins.mocha({
              reporter: 'mochawesome',
              reporterOptions: {
                reportDir: './coverageReport/allRegionsSuite/mochawesome/'+ awsRegion
              },
              require: ['./tps-common/index.js'],
              timeout: 100000000
          }));

       stream.on("end", function(){
         done();
       });
};

//gulp task to run all tests in all aws Regions
gulp.task('test:allRegionsSuite', ['pre-test'], function (done) {
    let i = 0;
    let total = allRegions.awsRegionList.length;

    function _done() {
        if (i < total) {
            regionalSuite(allRegions.awsRegionList[i], _done);
            i++;
        } else {
            done();
        }
    };
    _done();
});

//gulp task to call 'test:allRegionsSuite' task and then generate consolidated report later.
gulp.task('testAllRegionWithReport', ['test:allRegionsSuite'], function (done){

    var mytable = new Table({
        head: ['Region','Duration', 'Passed', 'Failed', 'Pending', 'Total' ]
        , colWidths: [20, 10, 10, 10, 10, 10 ]
        });

     generateReport(mytable);

  });
```
Expected:
I want each of the gulp task for each awsRegion to run in parallel but currently its running in parallel.
is my loop making it slow?

Using
gulp version : 3.9.1
npm version : 3.8.3

**Comment by phated** [comment]
This is not a support forum. Please direct support questions to StackOverflow.
