### ISSUE TITLE
yarn add gulpjs/gulp#4.0 ~ ERROR

### ISSUE THREAD

**Issue by TOP-Chao** [gulpjs/gulp#1918]
`error An unexpected error occurred: "https://raw.githubusercontent.com/gulpjs/gulp/3f5aba28718dc19e4bf600fb88f128158ff2ff83/package.json: connect ETIMEDOUT 151.101.100.133:443"`

WTF?

npm install gulpjs/gulp#4.0 not error~

**Comment by phated** [comment]
Not a gulp problem
