### ISSUE TITLE
`gulp -T` doesn't show task descriptions

### ISSUE THREAD

**Issue by zenopopovici** [gulpjs/gulp#1919]
**What were you expecting to happen?**
`gulp -T` should display task description.

**What actually happened?**
`gulp -T` doesn't show task description

```js
function buildApp (done) {
  done();
};
```
**Sample gulpfile**
```js
buildApp.displayName = 'build';
buildApp.description = 'Build entire project.';
buildApp.flags = {
  '--development': 'Compliles project and enters Watch mode. No optimisations or minification takes place.',
  '--staging': 'Compliles project, in the same way as development, without entering Watch mode.',
  '--production': 'Builds in production mode (minification, image optimisation, cleanup).'
};
gulp.task(buildApp);
gulp.task('default', buildApp);
```

**What version of gulp are you using?**
CLI version 1.2.2
Local version 4.0.0-alpha.2

**What versions of npm and node are you using?**
node: v7.6.0
npm: 4.4.0

**Comment by phated** [comment]
I'm guessing you have an old version of your local gulp.  That 1.2.2 version of gulp-cli had [this fix](https://github.com/gulpjs/gulp-cli/commit/0cd8050e1415b5bab05b4cc5d7e9b8af24f21463) which made things work with breaking undertaker changes in 1.0.  Check your dependency tree or blow away node_modules and reinstall.

**Comment by zenopopovici** [comment]
I just nuked everything deleted my yarn.lock file and rebuilt ... same issue.

**Comment by phated** [comment]
@zenopopovici please provide a reproduction case

@sttk any thoughts?

**Comment by zenopopovici** [comment]
@phated I think it's an issue with https://github.com/frankwallis/gulp-hub I keep my tasks in different files...

**Comment by zenopopovici** [comment]
https://github.com/frankwallis/gulp-hub/issues/38
