### ISSUE TITLE
Bug on parsing JSX

### ISSUE THREAD

**Issue by reenan** [gulpjs/gulp#1920]
Hello,

I noticed that gulp suddenly stoped building my main.js but was not reporting any error, everything as just fine, no syntax errors nor anything. After an exhausting investigation I found out that the problem was here:

`<Title width={(this.props.contentWidth * 0.7)} title={this.props.title} />`

When I removed this line, everything worked as expected. Put this back on and it stopped again.
So, I changed it to

`<Title width={this.props.contentWidth * 0.7} title={this.props.title} />`

*notice that I did remove the () inside width prop*

and everything worked as well. I do believe this is a bug because the () there isnot a syntax problem nor something that should stop gulp from building my main, even more without displaying any errors when validating my JSX files.

Here is the task for building:

```
.task('sites-main', function() {
    var bundler = browserify({
        entries: ['./path/to/file/Page.jsx'],
        transform: [reactify], // We want to convert JSX to normal javascript
        debug: dev,
        cache: {},
        extensions: ['.jsx'],
        packageCache: {},
        fullPaths: !prod
    });

    var watcher = watchify(bundler);

    return watcher.on('update', function () {
        var updateStart = Date.now();
        console.log('Updating!');

        watcher.bundle() // Create new bundle that uses the cache for high performance
            .pipe(source('main.js'))
            .pipe(prod ? buffer() : gutil.noop())
            .pipe(prod ? uglify() : gutil.noop())
            .pipe(gulp.dest('./path/to/dist/js/'));

        console.log('Updated!', (Date.now() - updateStart) + 'ms');
    })
    .bundle()
    .pipe(source('main.js'))
    .pipe(prod ? buffer() : gutil.noop())
    .pipe(prod ? uglify() : gutil.noop())
    .pipe(gulp.dest('./path/to/dist/js/'));
})
```

And here is the task for validing JSX

```
.task('validate-jsx', function() {
  return gulp.src(['./path/to/jsx/**/*.jsx'])
    .pipe(plumber())
    .pipe(react())
    .on('error', function(e) {
      console.error(e.message + '\n  in ' + e.fileName);
      // process.exit(1);
    })
})
```

**Comment by contra** [comment]
Sounds like a bug with one of your plugins, not gulp itself. Probably the JSX compiler not reporting errors or something, you should investigate which plugin is responsible and open the issue there.

Post a link to the issue you create in here so it links the two threads.
