### ISSUE TITLE
Gulp build failure for semantic-ui, beacause of node_modules syslink

### ISSUE THREAD

**Issue by oslivan** [gulpjs/gulp#1924]
When I use node_modules syslink, `gulp build` won't create dist  under semantic path, and won't raise any exception, so I don't know what's reason? gulp or semantic? Please reference to [build ouput](https://github.com/Semantic-Org/Semantic-UI/issues/5141), thanks for help.

**Comment by phated** [comment]
This isn't a gulp problem.  This has something to do with your system or setup.  Please direct support questions to StackOverflow.
