### ISSUE TITLE
Minimatch 3.0.2

### ISSUE THREAD

**Issue by trextroy** [gulpjs/gulp#1925]
Is there any way we can fix the Minimatch version issue. can we update to 3.0.2 /?

**Comment by phated** [comment]
No, we can't easily change this and follow semver properly. Also, it's not an issue, just a warning.

**Comment by trextroy** [comment]
Installation is getting stuck for me because of that so thought to raise the same.

**Comment by phated** [comment]
That is not the reason installation is getting stuck.  You have something else going on and should look into your system.

**Comment by trextroy** [comment]
Ok thanks for your help.
