### ISSUE TITLE
Running gulp from global

### ISSUE THREAD

**Issue by nareshurs** [gulpjs/gulp#1928]
I am trying to run gulp with Jenkins build using our CI/CD pipe line. This is a maven project. Evey jenkins build is a new workspace folder and when it tries to run gulp (for minification of js code), it doesnt take global installation.

I know most of the threads are closed saying usage of npm scripts/ npm link but I am not in a situation to use like that. I could see this https://github.com/gulpjs/gulp/pull/314/commits/5790e27f7f7a979c281e21af494e313b5957e851
 but seems these changes are not integrated.

Is still there any way like the usage of GULP_HOME possible?  Such a good build system not considered by many projects because of this single issue. Why doesnt gulp provide a way for this?

**Comment by phated** [comment]
Just run in from the node_modules/.bin directory. Support questions should be directed to StackOverflow
