### ISSUE TITLE
Gulp 4: High CPU usage.

### ISSUE THREAD

**Issue by Triloworld** [gulpjs/gulp#1929]
I found small bug which take 100% CPU usage.
If i declare variable:

const TEMPLATE_PATH = './app',

and somewhere in code there will be:

gulp.task('code', function (done) {
    browserSync.reload();
    done();
});

gulp.task('watch:code', function () {
    gulp.watch([TEMPLATE_PATH + '/**/*.html'],
        gulp.series('code')
    );
});

and of course 'app' directory don't exist it will eat all cpu usage. What i don't see is error informing me that this watcher cannot work. 

**If I change watcher to work on existing directory then everything will be ok.**

Versions:
Patryk:cme patrykpadus$ npm -v
4.1.2
Patryk:cme patrykpadus$ node -v
v7.7.2
Patryk:cme patrykpadus$ gulp -v
[22:11:59] CLI version 1.2.2
[22:11:59] Local version 4.0.0-alpha.2
Patryk:cme patrykpadus$ 

Found bug, what trigger it. It is important because it take full cpu usage without stop with error.

**Comment by contra** [comment]
Seems like an issue with the base glob watcher - based on looking over the glob-watcher module code, going to assume it's a level down in chokidar.

@es128 Seen this one before?

**Comment by es128** [comment]
No, haven't seen a situation like this cause a CPU spike, not sure what that's about.

An error is not expected out of chokidar because it allows you to watch paths that do not exist and get events when they are created.

**Comment by phated** [comment]
Likely a problem in browsersync (why are you calling reload without starting browsersync?)

**Comment by contra** [comment]
Yeah, if this doesn't cause high CPU on its own then its your browsersync:

```js
gulp.task('watch:code', function () {
  gulp.watch([TEMPLATE_PATH + '/**/*.html'], function(){});
});
```
