### ISSUE TITLE
Gulp.dest copy corrupts some image files on Windows

### ISSUE THREAD

**Issue by jon-lester** [gulpjs/gulp#1933]
**What were you expecting to happen?**

We're expecting image files to be directly binary-copied to the output directory, but instead *some* are being corrupted during the copy, resulting in images that won't load into the page.

This happens on Windows 7 and Windows 10, but not on MacOS with the same build script and software versions.

The problem seems inconsistent in which images it corrupts for any given build, however it tends to corrupt those which appear closer to the start of the standard sort-order.

We haven't noticed any issues with text files.

**What actually happened?**

It appears as though some of the image files are perhaps being parsed as UTF8. What makes us think this is that, for example, the hex value 0xA2 in the source file is being replaced with 0xEF 0xBF 0xBD at the destination (the UTF8 replacement character).

Please see the attachment, containing copies of one of the image files before and after the copy:

[corruptimage.zip](https://github.com/gulpjs/gulp/files/867506/corruptimage.zip)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task( "copy-image", function () {
	// Copy images from "/[source]/assets/images" to "/[build]/assets/images"
	gulp.src([
		"./" + config.dir.source + "/assets/images/**/*"
	]).pipe( gulp.dest("./" + config.dir.build + "/assets/images") );
});
```

**What versions are you using?**

Gulp version: 3.9.1 (and the 3.x versions that we've used previously)
Npm version: 3.10.3
Node version: 6.6
Windows version: 7 / 10

**Comment by contra** [comment]
Does this happen on 4.0 as well?

**Comment by phated** [comment]
Use the read: false option. That's what it is there for.

**Comment by contra** [comment]
Yep - use the streaming mode. This should be better documented IMO.

**Comment by jon-lester** [comment]
Thanks all - will look into this option.

**Comment by phated** [comment]
(correction) I believe the option is `buffer: false`

**Comment by JosephTurner** [comment]
For me, disabling `removeBOM` fixed it. Weirdly the BOM stripped PNG files ended up nearly double the size.
