### ISSUE TITLE
how do I test a gulp plugin used througn2 with long time async callback?

### ISSUE THREAD

**Issue by lovetingyuan** [gulpjs/gulp#1935]
I write a gulp plugin, I have a problem when I write test for it, https://github.com/lovetingyuan/gulp-polyfit
I use `this.push(file)` in an async way, like this:
```javascript
// some code...
return through.obj(transFunc, function(callback) {
    // some code...
    var self = this;
    Promise.all([4000, 2000, 3000].map(function(time) {
       return new Promise(function(resolve, reject) {
         setTimeout(function() {
           self.push(new Vinyl({
             contents: new Buffer(time)
           }))
           resolve()
         }, time)
       })
     })).then(function() {
       callback()
     }).catch(callback)
});
```
The plugin works well, but when I test it, the `data` event of the stream only be emmitted once or do not emmit when the time is long enough, I don't know why.

**Comment by phated** [comment]
Don't use promises inside a stream.  I was just working with a library that does it and it was an absolute nightmare.  Streams are already async (notice the callback), no need to add another async abstraction on top of it.

**Comment by lovetingyuan** [comment]
I have to push new file which only could be fetched in a async way, how can I handle this?

**Comment by callumacrae** [comment]
using streams
