### ISSUE TITLE
gulp.series not working and also displayName not working

### ISSUE THREAD

**Issue by roytz** [gulpjs/gulp#1937]
**What were you expecting to happen?**
1. Gulp tasks to run one after the other (and not parallel).
2. Display the functions name I use (and not <anonymous>).

**What actually happened?**
1. Seems like the tasks ran in parallel
2. Functions display as <anonymous>.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
![image](https://cloud.githubusercontent.com/assets/16700423/24782175/97b4002a-1b12-11e7-8094-5a1ffc5f1797.png)
The functions are simple exec functions such as-
```js
gulp.task('setup-dependencies', callback => exec("yarn", { cwd: '/somePlace' }));
```
and some gulp tasks call functions which I set an attribute of 'displayName' for.

**What version of gulp are you using?**
gulpjs/gulp#4.0

**What versions of npm and node are you using?**
node 7.8.0
npm 4.2.0
yarn 0.21.3

**Comment by roytz** [comment]
my mistake. sorry. closing

**Comment by yawlhead91** [comment]
What was you solution
