### ISSUE TITLE
Suggested alternative to gulp.series and gulp.parallel

### ISSUE THREAD

**Issue by TwitchBronBron** [gulpjs/gulp#1938]
I think that the following syntax would be much cleaner and much more intuitive way of running tasks in series or in parallel. It makes the composition of tasks much more fluid, without a lot less boilerplate
```
gulp.task('default',
    ['parallel1', 'parallel2'],
    'series1',
    'series2',
    ['parallel3', 'parallel4'],
    function () {
        //do some work here after all dependencies have been run
    }
);
```

Here is how it would process: 

1. run parallel1 and parallel2 in parallel
2. Run series1
3. Run series2
4. Run parallel3 and parallel4 in parallel. 
5. run the function now that all required tasks have been run.

**Comment by phated** [comment]
No, we aren't building a DSL into our API. You can build this short of stuff on top.

**Comment by contra** [comment]
Also, I don't think this is clear at all - this is what our current system looks like and people hate it.

**Comment by TwitchBronBron** [comment]
@contra, I can't argue with that; the new (series/parallel) system is indeed more readable. I just don't know how much that really matters. I would like to think that you could tell gulpfile authors "The gulp task executes dependencies from left to right in series, and when it encounters an array, those are run in parallel" and most people wouldn't have a problem understanding that.

What if gulp were to support my proposed model in addition to the new series/parallel system? All of the people who "hate" it could continue to use the series/parallel approach.

**Supporting both approaches would make gulp 4 more backwards compatible with gulp 3** to support the traditional `gulp.task('name', ['parallel1','parallel2'], function(){...})` syntax.

Internally, gulp could transform the gulp.task parameter array into a set of gulp.series or gulp.parallel objects. Inside the gulp.task method, you would do something like this: 

```
gulp.task = function () {
    var taskName = arguments[0];
    var seriesTasks = [];
    for (var i = 1; i < arguments.length; i++) {
        if (Array.isArray(arguments[i])) {
            seriesTasks.push(gulp.parallel(arguments[i]));
        }else{
            seriesTasks.push(arguments[i]);
        }
    }
    var series = gulp.series.apply(whateverThisShouldBe, seriesTasks);
    
    //the rest of gulp.task...
}
```

This would transform a task like this: 

```
gulp.task('default',
    ['parallel1', 'parallel2'],
    'series1',
    'series2',
    ['parallel3', 'parallel4'],
    function () {
        //do some work here after all dependencies have been run
    }
);
```

Into this:
```
gulp.task('default',
    gulp.series(
        gulp.parallel(['parallel1', 'parallel2']),
        'series1',
        'series2',
        gulp.parallel(['parallel3', 'parallel4']),
        function () {
            //do some work here after all dependencies have been run
        }
    )
);
```

**Comment by phated** [comment]
Again, no. This goes into userland.

**Comment by contra** [comment]
Yeah, you could do this yourself with a 1 line module

```js
const sugar = (...a) =>
  gulp.series(...a.map((i) => Array.isArray(i) ? gulp.parallel(...i) : i)

gulp.task('default', sugar(
    ['parallel1', 'parallel2'],
    'series1',
    'series2',
    ['parallel3', 'parallel4'],
    function () {
        //do some work here after all dependencies have been run
    }
));
```
