### ISSUE TITLE
bash completion doesn't deal with spaces in task names

### ISSUE THREAD

**Issue by coreyfarrell** [gulpjs/gulp#1940]
**What were you expecting to happen?**
Unless bash-completion can properly handle spaces in task names they should just be filtered out.  This could be a sensible way to support tasks mainly intended for internal use.  Although `gulp 'apple orange'` can be run it wouldn't be published by bash-completion.

**What actually happened?**
bash completion shows apple and orange as separate tasks due to the space, typing gulp and pressing tab produces the following output:
`apple   build   orange`

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
'use strict';

const gulp = require('gulp');

gulp.task('build', function () {});
gulp.task('apple orange', function () {});
```

**What version of gulp are you using?**
Global and local: 3.9.1

**What versions of npm and node are you using?**
npm v3.10.10
node v6.10.0

**Comment by phated** [comment]
@coreyfarrell I think this might be a limitation of the `compgen` command in bash because we just pass the result of `--tasks-simple` to that command.  If you can find a better solution than using `compgen`, please submit a PR to https://github.com/gulpjs/gulp-cli
