### ISSUE TITLE
gulp failing with an issue in v8flags

### ISSUE THREAD

**Issue by chriskinsman** [gulpjs/gulp#1941]
**What were you expecting to happen?**
gulp to complete successfully.

**What actually happened?**
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.9.2/lib/node_modules/gulp/node_modules/v8flags/index.js:14:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**What version of gulp are you using?**
3.9.1

**What versions of npm and node are you using?**
3.10.9
6.9.2

This is when attempting to do a build in a docker container using shippable.  We suspect issue #34 in the v8flags repo.  They just release v2.1.0 which appears to break things.  v2.0.12 it all appears to work correctly.

Gulp uses a semver of ^2.0.2 so it installs the broken v8flags.

Would it be possible to change to "2.0.12" until they fix things downstream?

**Comment by phated** [comment]
Already working on it.  Do you realize you've been caching v8flags config as `version-{undefined}.json`?  That's probably not good.  You should look into your environment.

**Comment by phated** [comment]
Published as 2.1.1 - do a fresh, clean install and you should be good.

**Comment by chriskinsman** [comment]
Didn't realize that.  I don't use v8flags directly at all.  It is just a dependency of gulp that I was unaware of until it broke...

**Comment by phated** [comment]
All good.  I'm now defaulting to a empty user (which might cause problems in very rare edge cases).

**Comment by zombie-guru** [comment]
Where / how was this fix published at? Running into the same issue as well.

**Comment by phated** [comment]
You need to cache clean. You are getting the old version of v8flags
