### ISSUE TITLE
Gulp 3.9.1 minimatch and graceful-fs is depricated

### ISSUE THREAD

**Issue by dobromirpeev** [gulpjs/gulp#1942]
- [ ] Gulp 3.9.1 => glob-stream@3.1.18 => minimatch@2.0.10 is **depricated**
- [ ] Gulp 3.9.1 => glob-watcher@0.0.6 => gaze@0.5.2 => globule@0.1.0 => minimatch@0.2.14 is **depricated**
- [ ] Gulp 3.9.1 => vinyl-fs@0.3.14 => glob-watcher@0.0.6 => gaze@0.5.2 => globule@0.1.0 => glob@3.1.21 => graceful-fs@1.2.3 is **depricated**

**Comment by Romanx** [comment]
Already documented here #1485
