### ISSUE TITLE
Gulp 4 seems to not finish task in gulp.series

### ISSUE THREAD

**Issue by lukasoppermann** [gulpjs/gulp#1944]
Hey,

first let me say that I really love what you are doing with gulp and also gulp 4. While I sadly don't know enough about low level js to help with the release, I figured I switch a project over to gulp 4 to at least do some testing. However I ran into a problem, I am not sure if this is something with gulp or an issue on my side (probably). I did not find any solution to this issue in any other ticket, so maybe you can help me.

This is my code:

```js
gulp.task('build-js', function (done) {

  Object.keys(filesJS).forEach(function (key) {

    gulp.src(filesJS[key])
        .pipe(sourcemaps.init())
        .pipe(babel({
          presets: [ [ 'es2015', { modules: false } ] ],
          plugins: ['transform-custom-element-classes']
        }))
        .on('error', swallowError)
        .pipe(concat(key + '.js'))

        .pipe(uglify())
        .pipe(sourcemaps.write('/'))
        .pipe(gulp.dest('public/js'))
        .on('end', function () {
          reportSavings(sizes, 'JS (' + key + '):')
        })
    })
    done()
})

gulp.task('js', gulp.series(
    'clean-js',
    function moveJsFiles () {
      return gulp.src(moveFilesJS).pipe(gulp.dest('public/js'))
    },
    'build-js',
    'rev-js',
      // do more stuff
      done();
    }
  )
)
```

The error I get is the following: 

> Error: File not found with singular glob: /Users/lukasoppermann/Code/veare/public/js/common.js

`common.js` is created within `build-js`.

When I run the tasks separately via the cli it works fine. It also works fine if I move `build-js` above the `moveJsFiles` function in the series.

I do not understand what I am doing wrong and why it only works this way. Please let me know how I can fix this. 

Thank you.

**Comment by phated** [comment]
You are actually using `done` incorrectly.  The `done` callback is used to signal completion if you aren't return a stream or a promise (among other async completion types).  I'm not sure why you have `done()` at the end of your `gulp.series` chain because it isn't defined (and your `{ }` are wrong).  You typically don't want to use `done` unless you are integrating callback-style libraries, and should instead opt for returning a **single** stream or promise, etc.

Typically, it's bad form to generate streams in a loop, like you are doing in `build-js`.  You should probably do something like this instead:

```js
gulp.task('build-js', function () {

    var files = Object.keys(filesJS).map(function (filepath) {
        return filepath;
    });

    return gulp.src(files)
        .pipe(sourcemaps.init())
        .pipe(babel({
          presets: [ [ 'es2015', { modules: false } ] ],
          plugins: ['transform-custom-element-classes']
        }))
        .on('error', swallowError)
        .pipe(concat(key + '.js'))

        .pipe(uglify())
        .pipe(sourcemaps.write('/'))
        .pipe(gulp.dest('public/js'))
        .on('end', function () {
          reportSavings(sizes, 'JS (' + key + '):')
        });
});

gulp.task('js', gulp.series(
    'clean-js',
    function moveJsFiles () {
      return gulp.src(moveFilesJS).pipe(gulp.dest('public/js'))
    },
    'build-js',
    'rev-js',
    // do more stuff
  )
);
```

Please direct future support questions to StackOverflow.

**Comment by lukasoppermann** [comment]
Thank you, I did not find anything related on StackOverflow, however the problem seems to have been the loop (it worked fine in gulp 3 though).

I needed it because I was building bundles from multiple files, so your solution does not work. I guess I will just have to create different tasks or so for each bundle.

**Comment by phated** [comment]
@lukasoppermann you can create the pipelines in the same task and then merge them together with something like https://www.npmjs.com/package/merge-stream 

There are probably some other patterns to solve your problem without creating multiple streams but I can't come up with them off the top of my head.

An aside: Even if you can't find an answer on StackOverflow, creating the post over there would allow other people to find the answer in the future.

**Comment by lukasoppermann** [comment]
Hey, @phated thanks.

I figured I could also just use a function which creates the stream and does all the work and call it 4 times. The function would take the 2 arguments (output filename and array of files to merge).

Sadly it seems to not be working the way I expect it to. I did create a stackOverflow ticket for this: http://stackoverflow.com/questions/43583541/gulp4-use-function-with-argument-as-task hope someone helps there.

**Comment by phated** [comment]
@lukasoppermann you basically are reinventing partial application but doing it incorrectly.  You probably want to read http://benalman.com/news/2012/09/partial-application-in-javascript/

**Comment by lukasoppermann** [comment]
Thanks, I solved it now by currying and using the merge stream, so that I can actually use the loop.

**Comment by phated** [comment]
Oh, it looks like you deleted the SO question instead of posting a response/answer so people can find that in the future? 😞

**Comment by lukasoppermann** [comment]
Hey @phated I did indeed, my solution did not answer the stackOverflow question at all, and I think the answer is, that you will always have the wrapper function show up. So I see no sense in answering it with an answer that does not actually answer it. 😉 

I solved it by keeping the `Object.keys(filesJS).forEach(function (key) {` but merging the streams to a variable define outside the forEach, which I can than return. Basically what you suggested above. So thanks.

**Comment by ViieeS** [comment]
@lukasoppermann you can also do it using underscore's `_.after`:

```js
const appJs = (cb) => {
const done = _.after(_.size(bundles), cb);

_.each(config.bundles, (paths, bundle) => {

    gulp.src(paths.css)
        // ... pipes ...
       .pipe(gulp.dest(destPath))
       .on('end', done);
});

};

```
