### ISSUE TITLE
Gulp Not Running Task with Nested Dependencies

### ISSUE THREAD

**Issue by aeolingamenfel** [gulpjs/gulp#1946]
**What were you expecting to happen?**
Gulp would run the `fn` attached to the task after the dependencies finished running (see below, the `fn` in question is marked with a comment).

**What actually happened?**
Gulp did not even enter/execute the `fn`. 

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task("build-css", ["build-child-css", "build-parent-css"]);
gulp.task("build-js", ["build-child-js", "build-parent-js"]);

gulp.task("deploy", ["build-css", "build-js"], function() {
    // this function never gets called. However, if I change the deps for 
    // this function to the lower-down build-child-css/build-parent-css/etc. 
    // then it works fine
});

// assume that the build-(child|parent)-(css|js) tasks are just very basic
// SASS/uglification tasks
```

**What version of gulp are you using?**

```
[08:50:59] CLI version 3.9.1
[08:50:59] Local version 3.9.1
```

**What versions of npm and node are you using?**

NPM: `4.1.2`
Node: `v7.7.1`

**Comment by ericmdantas** [comment]
Are you returning all the tasks?

**Comment by aeolingamenfel** [comment]
@ericmdantas what do you mean? My tasks are basically:

```
gulp.task("build-child-css", function() {
    return gulp.src(["sass/*.scss", "sass/**/*.scss"])
        .pipe(sass())
        .pipe(gulp.dest("dist/css/"));
});
```

**Comment by ericmdantas** [comment]
I mean returning the stream, which apparently you do.

Have you checked possible errors emitted by such tasks? In your cause, it'd be something like:

```js
gulp.task("build-child-css", function() {
    return gulp.src(["sass/*.scss", "sass/**/*.scss"])
        .pipe(sass().on('error', sass.logError)) // here
        .pipe(gulp.dest("dist/css/"));
});
```

**Comment by aeolingamenfel** [comment]
@ericmdantas I have; there's no errors being outputted (and the CSS files are being built).

**Comment by phated** [comment]
1. There's not enough information on this issue.
2. No one else has encountered this, so it's likely a problem with your gulpfile.  In that case, this is a support question and should be directed to StackOverflow.
