### ISSUE TITLE
gulp.watch doesn't work if watching directory has a repetitive shortcarts

### ISSUE THREAD

**Issue by saurovh** [gulpjs/gulp#1956]
i have a directory for js like
  app
       - app*    // this is a shortcart to upper app
when i do `gulp.watch('app/**/*.js')` it watch does not works properly
if i remove the shorcarts it works.
i am using gulp -v3.9.1
and node -v5.12.0
and npm -v3.8.6

**Comment by phated** [comment]
Please use the search functionality.
