### ISSUE TITLE
Gulp CLI drops first argument after last valid option

### ISSUE THREAD

**Issue by apeschel** [gulpjs/gulp#1957]
There appears to be an off-by-one error of some kind when parsing the command line arguments.

The Gulp CLI drops the first argument after the last option:

* `gulp --silent task` will not run `task`, but will run the default task
* `gulp --silent task1 task2` will only run `task2`

It doesn't matter if the options are valid:

* `gulp --silent --foo task1 task2` only runs `task2`

It also doesn't matter if the first argument is a valid task:

* `gulp --foo notatask1 notatask2 task1 task 2` will return `Task 'notatask2' is not in your gulpfile`

The CLI works fine when no options are used:

* `gulp task1 task2` executes `task1` and `task2`

**What version of gulp are you using?**

3.9.1

**What versions of npm and node are you using?**

NPM: 3.10.10
Node: v6.10.1

**Comment by phated** [comment]
Switch to using the `gulp-cli` package for your CLI.  This problem shouldn't be present there.  If it is, please re-open this on that repository.
