### ISSUE TITLE
gulp plugins

### ISSUE THREAD

**Issue by amitsingh17051** [gulpjs/gulp#1958]
Hi
im ahveng a problem with my gulp setup
im using a window 7 desktop pc
there is some gulp plug in are working in mu system and some are not like (gulp-imagemim, gulp-sass)
and im having a error like this like 

$ npm install sass
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\AMITSI~1\AppData\Local\Temp\npm-10692-b6333d17\registry.npmjs.org\sass\-\sass-0.5.0.tgz.52019304' -> 'C:\Users\AMITSI~1\AppData\Local\Temp\npm-10692-b6333d17\registry.npmjs.org\sass\-\sass-0.5.0.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sass"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kt3k** [comment]
This is a problem of npm, not of gulp. Please see and try solutions in comments in https://github.com/npm/npm/issues/13461
