### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by Sibiraj-Codes** [gulpjs/gulp#1959]
while installing gulp. the following warnings are produced

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

**Comment by crobinson42** [comment]
Why was this closed @phated - if this is being tracked somewhere else, can you link to it here?

![](https://files.slack.com/files-tmb/T039R6A9M-F6C5L7RAT-86aa654c20/screenshot_2017-07-19_15.06.01_1024.png)

**Comment by phated** [comment]
It's right on the main page...  Duplicate of #1571

Please stop commenting on out-of-date issues and use the search features built into github (like search, tags, etc).
