### ISSUE TITLE
Watch: Pass changed files to task function

### ISSUE THREAD

**Issue by backflip** [gulpjs/gulp#1960]
Is the following approach a reasonable one if I want to pass the changed files to my task function?

```js
gulp.task('watch', function () {
  let events = []

  const watcher = gulp.watch('*.hbs', function handlebarsTask () {
    // Run task function with queued events as parameter
    return myHandlebarsTask(events, function () {
      // Reset events
      events = []
    })
  })

  // Keep track of events
  watcher.on('all', function (event, path) {
    events.push({
      event,
      path
    })
  })
})
```

Or is there a better way? The [docs](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#fn-1) don't seem to describe this use case.

**Comment by phated** [comment]
Watchers don't do this (I believe some have it documented why) so you have to roll-your-own, like you've done here.

Please direct future support questions to StackOverflow.

**Comment by backflip** [comment]
@phated, thanks a lot for clarifying!
