### ISSUE TITLE
Gulp fails to run on NodeJS 8, having NPM 5.0

### ISSUE THREAD

**Issue by creage** [gulpjs/gulp#1963]
```javascript
if (!require.extensions.hasOwnProperty(ext)) {
                                    ^
TypeError: require.extensions.hasOwnProperty is not a function
```
I believe it is connected to https://github.com/aseemk/requireDir/issues/45

Windows 7, Gulp 3.9.1, NodeJS 8.0.0, NPM 5.0

**Comment by akehir** [comment]
I had the same issue. It's not connected to npm 5 (I was installing with npm 4.2).

**Comment by ericmdantas** [comment]
This has nothing to do with `gulp` it was a bug with `require-dir`, which was fixed in `0.3.2` (released yesterday).

**Comment by simonua** [comment]
For reference: [https://github.com/aseemk/requireDir/issues/45](https://github.com/aseemk/requireDir/issues/45)

**Comment by contra** [comment]
^ That. Thanks @ericmdantas, closing.
