### ISSUE TITLE
Gulp just exits without notice when using detached child_process and child.unref()

### ISSUE THREAD

**Issue by chmanie** [gulpjs/gulp#1964]
When I spawn a child_process inside a gulp task in detached mode (see below) and use `child.unref()` on this child the gulp tasks just exits without completion (but just if it's an async task, meaning using promises, callbacks or async/await).

**What were you expecting to happen?**

Gulp completing the (example) task after 5 seconds.

**What actually happened?**

The task just exits without further notice (gulp 3.9.1): 

```sh
Starting 'task1'... # It shows just this and returns to the shell
```

It produces the following message (gulp v4 alpha 2):

```sh
Starting 'task1'...
The following tasks did not complete: task1
Did you forget to signal async completion?
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

This is a minimal example to reproduce the issue. As you can see I'm using the ES6 using the `gulpfile.babel.js` naming.

```js
// gulp v3.9.1
import cp from 'child_process';
import gulp from 'gulp';

gulp.task('task1', done => {
  const child = cp.spawn('sleep', ['5'], {
    detached: true,
    stdio: 'ignore',
  });
  child.unref();
  child.on('exit', done);
});

// gulp v4
import cp from 'child_process';
import gulp from 'gulp';

export const task1 = done => {
  const child = cp.spawn('sleep', ['5'], {
    detached: true,
    stdio: 'ignore',
  });
  child.unref();
  child.on('exit', done);
};
```

**What version of gulp are you using?**

This error occurs in v3 (3.9.1) as well as in v4 (gulp@4.0.0-alpha.2)

**What versions of npm and node are you using?**

Node version 4.8.3, npm version 2.15.11

**Comment by phated** [comment]
That's what `unref()` does. See https://nodejs.org/api/child_process.html#child_process_options_detached
