### ISSUE TITLE
Error Code 128 trying to install gulp#4.0

### ISSUE THREAD

**Issue by nachtfunke** [gulpjs/gulp#1965]
Hello,

I am running npm 5.0.1 and node 8.0.0. When I try to install gulp 4.0 with `npm install gulpjs/gulp#4.0`, it results in this error message:

```bash
npm ERR! exited with error code: 128
```

Is there any workaround?

**Comment by IGx89** [comment]
I believe this is caused by https://github.com/npm/npm/issues/16726. Downgrading to npm 4 or waiting a day or two for npm 5.0.2 is the solution.

**Comment by IGx89** [comment]
This works with npm 5.0.1 I just discovered: `github:gulpjs/gulp#38246c3`. Using the commit SHA instead of the branch name was the key.

**Comment by phated** [comment]
I don't suggest using the SHA, as 4.0 gets rebased at random intervals.
