### ISSUE TITLE
gulp.series not a function 

### ISSUE THREAD

**Issue by Shamonshamonsha** [gulpjs/gulp#1966]
gulp series task

```
gulp.task('default',function () {
    gulp.watch('lib/*.js', function() {
        gulp.series('first','second');
    });
})
```

I got the error  gulp.series is not a function

gulp version :3.9.1
node 6.10.0
npm 4.3.0

**Comment by drazik** [comment]
`gulp.series` is a new function introduced in gulp 4. If you want to run `first` before `second` using gulp 3.9.*, you should use the following syntax : 

```js
gulp.watch('lib/*.js', ['first', 'second']);
```

If you want to give gulp 4 a try, you can install it by typing `npm install "github:gulpjs/gulp#4.0"` in your terminal.

Hope it helps.

**Comment by phated** [comment]
@drazik is partially correct.  `.series` and `.parallel` methods being introduced in gulp 4.  However, the syntax he provides for serial execution is incorrect, as they are run in parallel.  You probably want to do further research on task dependencies and the `run-sequence` module.

Future support questions should be directed to StackOverflow.

**Comment by ayyash** [comment]
The documentation of 3.9.1 should remove reference to gulp series

**Comment by phated** [comment]
@ayyash the master branch is now 4.0 since it is published.  I'm guessing you want https://github.com/gulpjs/gulp/tree/v3.9.1/docs as outlined in our https://github.com/gulpjs/gulp#documentation section of the readme.

Also, please refrain from commenting on months closed issues - it just increases noise.
