### ISSUE TITLE
gulp browserSync.reload

### ISSUE THREAD

**Issue by ccrayton** [gulpjs/gulp#1969]
So my question is, is there a way that when I run gulp watch through my terminal my browser doesn't load on a new page but instead reloads on the present page?

![screen shot 2017-06-07 at 2 39 14 am](https://user-images.githubusercontent.com/19902713/26912935-66b3413a-4bcc-11e7-8b40-0cc9260fb23d.png)

**Comment by callumacrae** [comment]
This is more a browser-sync question than a gulp question so would be best directed over there, but no, I don't think there is.
