### ISSUE TITLE
Is there a way to limit CPU usage for gulp tasks

### ISSUE THREAD

**Issue by adamreisnz** [gulpjs/gulp#1970]
I would like to limit CPU usage for specific gulp tasks (or the whole process), because every time a build kicks off my CPU usage spikes to 80-100% which is causing my whole machine to slow down. I would like to limit this to say 25-50%, so that the task may take a bit longer, but at least won't slow my other work down.

Any way to achieve this in Gulp 4?

Note that I am not referring to the watch task.

**Comment by phated** [comment]
Nope. Node doesn't allow this.

**Comment by dolohow** [comment]
Run gulp in cgroup.
