### ISSUE TITLE
Persistent error: [ERROR] Gulpfile not found: .\gulpfile.js

### ISSUE THREAD

**Issue by brunoheringer** [gulpjs/gulp#1980]
This tracker is for bug reports only.

**What were you expecting to happen?**
I only get this:
[ERROR] Gulpfile not found: .\gulpfile.js
        You can set the gulpFile attribute in ionic.config.json for custom Gulpfile locations, otherwise the default
        Ionic Gulpfile can be downloaded from https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.js

        Or, if you no longer use gulp, you can remove the CLI Gulp Plugin:

        npm uninstall --save-dev --save-exact @ionic/cli-plugin-gulp@latest

but, i already tried many solutions, and I don't get run my app with ionic cordova. 

Can Anybody help me please?

**Comment by callumacrae** [comment]
--> https://forum.ionicframework.com/ <--

This doesn't look like a gulp issue to me :)
