### ISSUE TITLE
Gulp stopped working and says 'paths is not defined'

### ISSUE THREAD

**Issue by frontenddevguy** [gulpjs/gulp#1983]
I am fairly new to gulp but had it working nicely.
Came back to it after a couple of days and it's showing errors.
I also now have to sudo npm install where I didnt need to before

Here is the error:

ReferenceError: paths is not defined
    at Object.<anonymous> (/Applications/AMPPS/www/project/wp-content/themes/project/gulpfile.js:34:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

Gulpfile

`var gulp 			= require('gulp')
var bower 			= require('gulp-bower')
var mainBowerFiles 	= require('main-bower-files')
// var path = require('path')

var sass 			= require('gulp-sass')
var autoprefixer 	= require('gulp-autoprefixer')
var cssmin 			= require('gulp-cssmin')
// var minifycss    = require('gulp-uglifycss') // Minifies CSS files

var sass         	= require('gulp-sass'); // Gulp pluign for Sass compilation
var autoprefixer 	= require('gulp-autoprefixer'); // Autoprefixing magic

// JS related plugins.
var concat       	= require('gulp-concat'); // Concatenates JS files
var uglify       	= require('gulp-uglify'); // Minifies JS files

// Utility related plugins.
var rename       	= require('gulp-rename'); // Renames files E.g. style.css -> style.min.css
var sourcemaps   	= require('gulp-sourcemaps'); // Maps code in a compressed file (E.g. style.css) back to it’s original position in a source file (E.g. structure.scss, which was later combined with other css files to generate style.css)
var notify       	= require('gulp-notify'); // Sends message notification to you
var pump 		 	= require('pump');
var plumber 	 	= require('gulp-plumber');

// Tasks

gulp.task('bower', function() {
    return gulp.src(mainBowerFiles('**/*.min.js'), { base: 'bower_components' })
        .pipe(gulp.dest('library/js/libs'))
});

var buildVendors = gulp.src(mainBowerFiles('**/*.min.js')).pipe(gulp.dest(paths.buildBower));
     return gulp.src(paths.index)
     .pipe(inject(buildBowerFiles,{
        relative: true,
        name: 'bowerInject'
     }));

var config = {
   srcCss : 'library/scss/**/*.scss',
   buildCss: 'library/css',
   buildJs: 'library/js',
}

gulp.task('build-css', function(cb) {
   gulp.src(config.srcCss)

      // output non-minified CSS file
      .pipe(sass({
         outputStyle : 'expanded'
      }).on('error', sass.logError))
      .pipe(autoprefixer())
      .pipe(gulp.dest(config.buildCss))

      // output the minified version
      .pipe(cssmin())
      .pipe(rename({suffix: '.min'}))
      .pipe(gulp.dest('library/css'));

   cb()
})

gulp.task('build-js', function () {
  gulp.src('library/js/scripts.js')
    .pipe(uglify())
    .pipe(rename({ suffix: '.min' }))
    .pipe(gulp.dest('library/js'))
})

gulp.task('watch', function(cb) {
   gulp.watch(config.srcCss, ['build-css']) 
   gulp.watch(config.buildJs, ['build-js']);
})

gulp.task('default', ['build-css', 'build-js', 'watch'])

`

**What version of gulp are you using?**

[22:10:02] CLI version 3.9.1
[22:10:02] Local version 3.9.1

**What versions of npm and node are you using?**
npm 2.12.0
node v0.12.0

**Comment by phated** [comment]
Please direct support questions to StackOverflow.
