### ISSUE TITLE
gulp task fails to exit

### ISSUE THREAD

**Issue by erikvold** [gulpjs/gulp#1986]
I have a gulp task `gulp.task("test-mocha", () => runMocha());` and `runMocha` just returns a promise.

I seem to have somehow written a test that passes, and running `mocha test/file.js` is working fine, but when I run `gulp test-mocha` that fails to exit even though the tests all pass and `Finished 'test-mocha' after X s` is printed in the console, which means gulp much know that the task has ended but yet it still fails to exit the process, and so that task just hangs there for a long time and I have to force exit the process.

**What were you expecting to happen?**

The task should exit normally

**What actually happened?**

The task does not exit, and instead it reports the tests passing, reports the task is done, and then hangs.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task("test-mocha", () => runMocha());
```

**What version of gulp are you using?**

3.9.0

**What versions of npm and node are you using?**

8.1.3

**Comment by erikvold** [comment]
what should normally cause a gulp task to exit?  I can't seem to find the code any `process.exit()` call that would be called at the end of a task.

**Comment by phated** [comment]
Usually that means the library you are using is poorly written and keeps something alive. Nothing you've presented is related to gulp so I'm going to close this.

**Comment by erikvold** [comment]
@phated what do you mean by something is alive?  like an unresolved promise?

**Comment by phated** [comment]
Something is keeping your event loop active. For something like this, it's likely a child process or a socket. I've seen similar behavior from a poorly written karma test runner in the past.

**Comment by phated** [comment]
You probably want https://www.npmjs.com/package/why-is-node-running

**Comment by erikvold** [comment]
@phated Also is there some reason why gulp should not force exit if it knows the task that is running is done?

**Comment by phated** [comment]
Yes, because that is semantically incorrect behavior and breaks workflows.
