### ISSUE TITLE
 Use of const in strict mode

### ISSUE THREAD

**Issue by mavlesreennap** [gulpjs/gulp#1988]
While doing the build using the frontend-maven-plugin version 1.4 along with Gulp build, getting the error " SyntaxError: Use of const in strict mode."

run-sequence version used --> "run-sequence": "~1.1"

Below is the error stack:

[INFO] --- frontend-maven-plugin:1.4:gulp (gulp build) @ proj ---
[INFO] Running 'gulp ' in /Users/ps/Documents/gitlab/proj/
[ERROR]
[ERROR] /Users/ps/Documents/gitlab/proj/node_modules/run-sequence/node_modules/chalk/index.js:2
[ERROR] const escapeStringRegexp = require('escape-string-regexp');
[ERROR] ^^^^^
[ERROR] SyntaxError: Use of const in strict mode.
[ERROR] at Module._compile (module.js:439:25)
[ERROR] at Object.Module._extensions..js (module.js:474:10)
[ERROR] at Module.load (module.js:356:32)
[ERROR] at Function.Module._load (module.js:312:12)
[ERROR] at Module.require (module.js:364:17)
[ERROR] at require (module.js:380:17)
[ERROR] at Object. (/Users/ps/Documents/gitlab/proj/node_modules/run-sequence/index.js:5:14)
[ERROR] at Module._compile (module.js:456:26)
[ERROR] at Object.Module._extensions..js (module.js:474:10)
[ERROR] at Module.load (module.js:356:32)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Please help to resolve this issue.

**Comment by doowb** [comment]
This isn't a gulp issue. The error is coming from chalk:

> [ERROR] /Users/ps/Documents/gitlab/proj/node_modules/run-sequence/node_modules/chalk/index.js:2

**Comment by contra** [comment]
That ^

Chalks issue, or if they already fixed it then the issue is with `run-sequence` for running an old chalk.

**Comment by phated** [comment]
This is likely you are running node with the --use_strict flag. Don't use that, it's really, really bad.
