### ISSUE TITLE
snyk reports a vulnerability via vinyl-fs@0.3.14

### ISSUE THREAD

**Issue by erikvold** [gulpjs/gulp#1992]
https://snyk.io/test/npm/gulp
https://snyk.io/vuln/npm:minimatch:20160620

vinyl-fs@0.3.14 uses minimatch@2.0.10 and minimatch@0.2.14 thru various dependencies, which are vulnerable to a regular exp DoS https://snyk.io/vuln/npm:minimatch:20160620

probably not a big deal, but I wonder why is it that the package.json for gulp depends on such old versions of `vinyl-fs` ?  vinyl-fs is at version 2.4.3 now.

**Comment by Romanx** [comment]
[#1719 (comment)](https://github.com/gulpjs/gulp/issues/1719#issuecomment-231514385)
