### ISSUE TITLE
gulp taskname --version 1.2.3 prints out gulp's version and exits (MAC Only)

### ISSUE THREAD

**Issue by jbgraug** [gulpjs/gulp#1993]
**What were you expecting to happen?**

This bug has been detected only on MAC OS
The --version parameter is used as a gulp task parameter in my gulp file. 
Gulp should not to print gulp's version if --version is used after a task name.  
On linux and windows this works as expected.

**What actually happened?**

Gulp prints out gulp's version and exits on MAC OS. ie:
[10:45:47] CLI version 1.2.2
[10:45:47] Local version 3.9.1

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
var gulp = require('gulp');
gulp.task('version',()=>{
    let i = process.argv.indexOf('--version')
    if (i>-1){
        console.log('--version argument value:', process.argv[i+1]);
    } else {
        console.log('no --version');
    }
});
```

**What version of gulp are you using?**
3.9.1
**What versions of npm and node are you using?**
3.10.10
6.10.1

**Comment by phated** [comment]
We don't support collision with our arguments (we try to keep them limited so this doesn't happen often).

**Comment by jbgraug** [comment]
I understand you that you don't support arguments collision. My point is that gulp behaves differently depending on the OS. That's why i still think it is a bug.

**Comment by phated** [comment]
@jbgraug that's something you'd have to bring up with yargs, the option parser we use.
