### ISSUE TITLE
Tasks don't run the way the dependency specify them

### ISSUE THREAD

**Issue by abhisheksoni27** [gulpjs/gulp#1996]
Here's a toned down version of our `gulpfile.js`:

```js
gulp.task('babelify', function () {
	gulp.src(['./src/**'])
		.pipe(babel())
		.pipe(gulp.dest('dist'));
});
	
gulp.task('build', ['babelify'], function() {
	browserify('./dist/index.js')
	.bundle()
	.pipe(source('gpu.js'))
	.pipe(buffer())
	.pipe(stripComments())
		.pipe(header(fs.readFileSync('./dist/wrapper/header.js', 'utf8'), { pkg : pkg }))
		.pipe(gulp.dest('bin'));
});
```

Technically, `babelify` should run first (it does), complete (it doesn't) then and only should the `build` task be executed. However, `build` starts asynchronously, and hence the script hits an error because the files are not present in `dist` and it aborts and throws an error.

**Comment by abhisheksoni27** [comment]
Apparently, if you don't use `return` gulp assumes it's ended and runs the next one. Or maybe assumes they are mutually exclusive tasks and runs them asynchronously.

```js
gulp.task('babelify', function () {
	return gulp.src(['./src/**'])
		.pipe(babel())
		.pipe(gulp.dest('dist'));
});
```

Fixed.

**Comment by phated** [comment]
If you don't return a stream, it's treated as a synchronous task.  We've fixed this footgun in gulp 4 by removing sync task support.

**Comment by abhisheksoni27** [comment]
@phated 
> "If you don't return a stream, it's treated as a synchronous task." 

Wow. In our case, the opposite was happening. We weren't returning a stream, and hence the second task started simultaneously.

**Comment by phated** [comment]
Not simultaneously, they still start in order but nothing blocks the execution of the first because you have async stuff inside a sync function.

**Comment by abhisheksoni27** [comment]
Right!
The first task might not have completed. Thanks. Can I ask a quick question?

**Comment by phated** [comment]
Sure. I'll probably clean up these comments after.

**Comment by abhisheksoni27** [comment]
Awesome!

Here's the actual `build` task, and `build` has dependents too. So, How can I add a return statement to this?

```js

	browserify('./dist/index.js')
	.bundle()
	.pipe(source('gpu.js'))
	.pipe(buffer())
	.pipe(stripComments())
		.pipe(header(fs.readFileSync('./dist/wrapper/header.js', 'utf8'), { pkg : pkg }))
		.pipe(gulp.dest('bin'))

	browserify('./dist/index-core.js')
	.bundle()
	.pipe(source('gpu-core.js'))
	.pipe(buffer())
	.pipe(stripComments())
		.pipe(header(fs.readFileSync('./dist/wrapper/header.js', 'utf8'), { pkg : pkg }))
		.pipe(gulp.dest('bin'))
});
```

I can separate the two tasks and that would work fine, but just out of curiosity, can a return statement be added to this?

**Comment by phated** [comment]
You can use something like https://www.npmjs.com/package/merge-stream as outlined in https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md

**Comment by abhisheksoni27** [comment]
Brilliant! Thanks a lot, Sir.

**Comment by phated** [comment]
No problem. For the sake of consistency, I must give our standard disclaimer that future support questions should be directed to StackOverflow 😸

**Comment by abhisheksoni27** [comment]
Definitely. Thanks for the support at a non-support forum. :laughing:
