### ISSUE TITLE
How can I execute gulp through another js file?

### ISSUE THREAD

**Issue by NextSeason** [gulpjs/gulp#2000]
I want to reuse my `build` in several different projects, so I want to invoke the `build` dir as a submodule of git module.

There is a `gulpfile.js` in the build dir, and how can I use it with `gulp` command out side the `build` dir?

I don't want to copy the `gulpfile.js` to the project dir, cuz I don't want to solve the dependencies of `build` scripts in every project.

**Comment by phated** [comment]
This is not a support forum. Please direct your support questions to StackOverflow.
