### ISSUE TITLE
gulp server works well, but gulp build to get static html and js files, when it runs, it shows it is not loaded Angular components.

### ISSUE THREAD

**Issue by langlangFan** [gulpjs/gulp#2002]
`gulp server` works well, I tested all.
run `gulp build` to get static html and js files. 
when I deploy it and run, it shows it is not loaded Angular components.
I am a little confused with this issue.
Any suggestion is appreciated.
Thanks,
Lang

**Comment by phated** [comment]
This is not a support forum. Please direct support questions to StackOverflow.
