### ISSUE TITLE
gulp --tasks does not display full dependency graph.

### ISSUE THREAD

**Issue by Noderino** [gulpjs/gulp#2003]
**What were you expecting to happen?**
I was expecting `gulp --tasks` to display full dependency graph.

**What actually happened?**
gulp-cli displays full dependency graph but gulp only displays dependencies of top level tasks.  gulp-cli already requires local gulp to be installed. I don't understand why each package has it's own logic to display tasks. Also if you install gulp from command line it overwrites the gulp-cli files in .bin folder and you can not get nested tasks even if you have gulp-cli.

![Screenshot](http://i.imgur.com/S6VzAvs.png)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
let gulp = require('gulp');
gulp.task('task1', function () {});
gulp.task('task2', ['deep1']);
  gulp.task('deep1', ['deep2'], function () {});
    gulp.task('deep2', ['deep3'], function () {});
      gulp.task('deep3', function () {});
```

**What version of gulp are you using?**
gulp-cli: 1.4.0
gulp: 3.9.1

**What versions of npm and node are you using?**
npm: 5.3.0
node: v6.11.1

**Comment by phated** [comment]
This can't be changed in 3.x without a major bump and it's already done in 4.0.

**Comment by Noderino** [comment]
I understand but Gulp 4 can not list tasks in Gulp 3 projects. I am building a task explorer extension for VS Code. I need all dependencies for older versions too. Do you plan to change this behavior in the future  or should i use a workaround?
