### ISSUE TITLE
Cannot find module after upgrade

### ISSUE THREAD

**Issue by Christo44** [gulpjs/gulp#2008]
I'm having trouble getting gulp to read my modules.

Initially I had a working system.

I then upgraded to with NVM (I removed everything installed with Brew first)
Here's what I have now:
```
"node: v6.11.2"
"npm: 3.10.10"
"nvm"
```
and I have a gulpfile which used to work, but I also upgraded my modules, and I have installed locally in my project:
```
"gulp": "^3.9.1",
"gulp-pug": "^3.3.0",
"gulp-sass": "^3.1.0"
```
globally for this version of node I do have:
```
gulp-cli@1.4.0
jshint@2.9.5
npm@3.10.10
```

in a simple gulpfile running: gulp would work successfully, but introducing other modules is where I started getting issues.

In my gulpfile I have for example: 

```
var gulp = require('gulp');

var sass = require(' gulp-sass'),
prefixer = require('gulp-autoprefixer'),
minifycss = require('gulp-clean-css'),
sourcemaps = require('gulp-sourcemaps'),
rename = require("gulp-rename");

gulp.task('sass', function () {
    return gulp.src(src.sass)
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(prefixer())
        .pipe(gulp.dest(src.css))
        .pipe(minifycss())
        .pipe(rename({suffix: '.min'}))
        .pipe(sourcemaps.write('/maps'))
        .pipe(gulp.dest(src.css))
        .pipe(connect.reload());
});
```

 locally running any command like `gulp sass` would produce:

```
Error: Cannot find module ' gulp-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myusername/sites/projectname/gulpfile.js:25:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I've removed the node_modules, removed the dependancies in package.json, reinstalled each local module

**Comment by phated** [comment]
This is not a support forum. Please direct support questions to StackOverflow. Also, you have a space in that string...
