### ISSUE TITLE
Gulp silently shuts down on task returning empty stream

### ISSUE THREAD

**Issue by cronfy** [gulpjs/gulp#2010]
**What were you expecting to happen?**

Running `gulp all` I expect to see:

```
[15:27:25] Using gulpfile /var/www/project/gulpfile.js
[15:27:25] Starting 'streams'...
[15:27:25] Finished 'streams' after 1.66 ms
[15:27:25] Starting 'dep'...
dep
[15:27:25] Finished 'dep' after 140 μs
[15:27:25] Starting 'all'...
all
[15:27:25] Finished 'all' after 84 μs
```

**What actually happened?**

After starting `streams` task gulp silently exits with code 0:

```
$ gulp all
[15:28:30] Using gulpfile /var/www/project/gulpfile.js
[15:28:30] Starting 'streams'...
[15:28:30] Starting 'dep'...
dep
[15:28:30] Finished 'dep' after 177 μs
$ echo $?
0
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task('dep', function () {
    console.log('dep')
})
gulp.task('streams', function () {
    const streams = require('merge2')()

    return streams
})
gulp.task('all', ['streams', 'dep'], function () {
    console.log('all')
})
```

**What version of gulp are you using?**
**What versions of npm and node are you using?**

```
$ gulp --version
[15:23:48] CLI version 3.9.1
[15:23:48] Local version 3.9.1
$ npm -v
5.2.0
$ node -v
v7.8.0
```

**Comment by phated** [comment]
Don't do that.  I'm not even sure node has a defined behavior for an empty passthrough stream.  It might be something merge2 needs to look into.

**Comment by terinjokes** [comment]
With no work happening (no timers, no I/O, no callbacks being added) eventually the Node.js event loop will run out of events. This is documented to cause Node.js to exit.[[1]]

> The 'exit' event is emitted when the Node.js process is about to exit as a result of either:
> * The process.exit() method being called explicitly;
> * The Node.js event loop no longer having any additional work to perform.

[1]: https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_event_exit

**Comment by phated** [comment]
@terinjokes brought up a good point.  We already handle this if you are using the separate `gulp-cli` module.  Check out https://medium.com/gulpjs/gulp-sips-command-line-interface-e53411d4467 for more details.

**Comment by pattyjung** [comment]
Can you take me off your list of responses as I have been recieving email
about your code for over a week.

Patricia Jung

**Comment by phated** [comment]
@pattyjung you subscribed to the thread and must unsubscribe yourself, none of us can do that for you...
