### ISSUE TITLE
gulp.task without function is not allowed

### ISSUE THREAD

**Issue by jabaa** [gulpjs/gulp#2013]
**What were you expecting to happen?**
I want to add a task consisting of a task name and a dependency list without TaskFunction.

**What actually happened?**
I got an error message that the dependency list must be a TaskFunction.
```
gulpfile.ts (6,22): Argument of type 'string[]' is not assignable to parameter of type 'TaskFunction'
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
import * as gulp from 'gulp';

gulp.task('watch', function() {
});

gulp.task('default', ['watch']);
```

**What version of gulp are you using?**
gulp: 3.9.1
types/gulp: 4.0.4

**What versions of npm and node are you using?**
node: 8.0.0
npm: 5.3.0
typescript: 2.4.2

**Comment by phated** [comment]
Discuss this with the people that write the typings for gulp. We do not write them.

**Comment by jabaa** [comment]
I think the problem is that types/gulp: 4.0.4 supports gulp 4 and in gulp 4 a dependency list is not allowed in that way.

**Comment by contra** [comment]
@jabaa Yeah, the API changed between 3.0 and 4.0 - the typings are correct, you can't use an array dependency list anymore.
