### ISSUE TITLE
Task using `base` option doesn't work from a directory junction

### ISSUE THREAD

**Issue by gene-pavlovsky** [gulpjs/gulp#2014]
I have a copy task using the `base` option. The project directory I working in is a directory junction (NTFS) to another location on the same drive.
The copy task doesn't actually copy any files.
If I run the same task in a directory that the junctions points to, it works.

So, in my case `C:\project` is a junction to `C:\work\project`,
when I'm in `C:\project\MyProject` and I execute the task, it doesn't copy anything.
If I do it in `C:\work\project\MyProject`, the files are copied correctly. If I remove the `base` option from my task, the files are then copied in both cases.

Here's the task itself:
```
var gulp = require('gulp');

module.exports = function(config) {
	return function() {
		return gulp
			.src(config.src, { base: '../node_modules'})
			.pipe(gulp.dest(config.dest));
	};
};
```

Here's how I'm using the task:
```
	'copy-external-scss-bin': {
		task: 'copy-external-scss',
		config: {
			src: path.join(__dirname, '../node_modules/perfect-scrollbar/**/*.scss'),
			dest: path.join(__dirname, '../bin/resource/scss/external')
		}
	}
```

gulp@3.9.0
node v6.9.4
npm 3.10.10

I have a suspicion that somewhere along the way, gulp actually resolves the directory junction, and compares the resulting paths with non-resolved paths, if you get my point. From my point of view, directory junctions should in almost every realistic usage behave very much like file hard links - that is, be virtually indistinguishable from the directory they point to (unlike symlinks, which many tools would treat differently from regular files). Therefore, I think this might be a bug.

**Comment by phated** [comment]
Thanks for the detailed report. However, junctions were never considering for the gulp 3.x line. We're just now getting them supported in vinyl-fs (and it's not quite done yet).
