### ISSUE TITLE
ECONNRESET error (Windows)

### ISSUE THREAD

**Issue by TheChilliPL** [gulpjs/gulp#2018]
**What were you expecting to happen?**
I was installing gulp by
`npm install -g gulp`

**What actually happened?**
```npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to http://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.11.tgz failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chilli\AppData\Roaming\npm-cache\_logs\2017-09-16T16_22_15_832Z-debug.log
```
**What versions of npm and node are you using?**
Node v8.5.0
npm v5.3.0

**I already tried these**
`npm cache clean --force`
`npm config rm proxy` and `https-proxy`
`npm config set registry http://registry.npmjs.org/`

**Comment by TheChilliPL** [comment]
Log file:
[2017-09-16T16_22_15_832Z-debug.log.txt](https://github.com/gulpjs/gulp/files/1308457/2017-09-16T16_22_15_832Z-debug.log.txt)

**Comment by TheChilliPL** [comment]
It crashes after `extract:resolve: sill extract isarray@0.0.1`

**Comment by phated** [comment]
We don't debug your npm problems, sorry.

**Comment by TheChilliPL** [comment]
Every other package is installing well...
