### ISSUE TITLE
Regular Expression Denial of Service from vinyl deps

### ISSUE THREAD

**Issue by wbotelhos** [gulpjs/gulp#2021]
Hi,

First, thanks for the great lib. (:

I'm using the service nodesecurity.io e it is blaming about some dependencies vulnerability:

```
118 - Regular Expression Denial of Service

Vulnerable: <=3.0.1 - Patched: >=3.0.2 - Path: gulp@3.9.1 > vinyl-fs@0.3.14 > glob-stream@3.1.18 > minimatch@2.0.10

How to fix
Updated to version 3.0.2 or greater
```

```
Vulnerable: <=3.0.1 - Patched: >=3.0.2 - Path: gulp@3.9.1 > vinyl-fs@0.3.14 > glob-watcher@0.0.6 > gaze@0.5.2 > globule@0.1.0 > minimatch@0.2.14

How to fix
Updated to version 3.0.2 or greater
```

The lib `vinyl` here is using the version `0.3.14` and checking, the actual version is `2.4.3` (https://github.com/gulpjs/vinyl-fs/blob/master/package.json) which updates `glob-stream` to `6.1.0` and maybe fix this issue, since the actual version a little bit old.

Any plan to update `vinyl`?

Thank you for the great work, again. (:

**Comment by callumacrae** [comment]
https://github.com/gulpjs/gulp/issues/1719#issuecomment-231514385
