### ISSUE TITLE
can not dail with multiple directory via multiple gulp instance?

### ISSUE THREAD

**Issue by sinbargit** [gulpjs/gulp#2025]
There are some directories in same level.Each of them is a sub-project.I want do that: the developer can choose which sub-projects they want to packaging by them self,and the packaging logic are same in each of them. The command is like:gulp --gulpfile ./package/gulpfile.js --root home+common. The home and common is sub-project's name.The script code at below. But that's not work,what should I do?

```
/*roots is home+common*/
roots = arr[1].split("+");
const gulpClone = function () {
};
gulpClone.prototype = gulp;
gulpClone.prototype.constructor = gulpClone;
roots.forEach((root)=>{
    let temp = root.trim();
    temp&&doTask(temp,new gulpClone());
})

function doTask(root,gulp) {
let resourceUrl = path.join(appRootDir,"/resource/",root);

gulp.task('default',["clean","head","other","resource"],function () {});
gulp.task("resource",["compressCss","compressJs"],function () {});
gulp.task('compressCss',["cleanResource"],() => {
...
}
```

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
