### ISSUE TITLE
Unable to download Gulp 4 via npm

### ISSUE THREAD

**Issue by ivtpz** [gulpjs/gulp#2031]
I am unable to download gulp 4.0 through npm. I get a read timeout error when I try to pull the repository.

**What were you expecting to happen?**
`npm i --save-dev gulpjs/gulp#4.0` should install gulp 4.0

**What actually happened?**
Error:
```
npm ERR! git fetch -a origin (git://github.com/gulpjs/gulp.git) fatal: read error: Operation timed out
```

**What version of gulp are you using?**
4.0

**What versions of npm and node are you using?**
npm v3.10.3
node v6.3.1

**Comment by callumacrae** [comment]
This is an npm issue, not a gulp issue
