### ISSUE TITLE
Gulp 3: non-anonymous function as gulp.task()'s 2nd argument always runs

### ISSUE THREAD

**Issue by brendanfalkowski** [gulpjs/gulp#2039]
Not sure if Gulp 3 bugs are being accepted, but posting anyway to document the workaround if anyone else gets stuck on this.

**Versions**

* Gulp 3.9.1
* Node 8.9.1
* NPM 5.5.1

**What were you expecting to happen?**

Using a named function for the 2nd argument of `gulp.task()` should work.

**What actually happened?**

It does work, but when any task is run — then all the tasks using a named function also run.

**Example Code — Has Problem**

I created a global function `createJsModule()` because each of these tasks does the exact same thing with different config.

```js
var createJsModule = function (task) {
    pump([
        gulp.src(task.src),
        uglify(task.uglifyOptions),
        gulp.dest(task.dest)
    ], reportError);
};

gulp.task('a', createJsModule(config.tasks.a));
gulp.task('b', createJsModule(config.tasks.b));
gulp.task('c', createJsModule(config.tasks.c));

gulp.task('x', function () {
    console.log('X gon give it to ya');
});
```

Problem: if you run `gulp x` then Gulp also runs A + B + C tasks.

**Workaround**

If you move the named functions inside an anonymous function it doesn't do that. Example:

```js
gulp.task('a', function () { createJsModule(config.tasks.a); });
gulp.task('b', function () { createJsModule(config.tasks.b); });
gulp.task('c', function () { createJsModule(config.tasks.c); });
```

No idea if that's a Node or Gulp thing, but it seems wrong.

**Comment by Igloczek** [comment]
It's general JS thing. Task method expects to get `function` type param, but you already invoked it and the param is undefined, b/c your function doesn't return anything.
Check this code sample - https://codepen.io/Igloczek/pen/YEVGMm?editors=1012

**Comment by phated** [comment]
^

**Comment by brendanfalkowski** [comment]
@Igloczek — Thanks! I didn't realize that's how functions returning functions were used for optimization. This article helped:

https://davidwalsh.name/javascript-functions

My rewritten Gulp tasks look like this now, which is a little cleaner:

```javascript
/**
 * @param {object} - Task config object. Example: `config.task.jsModuleAppPre`
 * @return {function} - See: https://github.com/gulpjs/gulp/issues/2039
 */
var createJsModule = function (task) {
    return function () {
        pump([
            gulp.src(task.src),
            uglify(task.uglifyOptions),
            gulp.dest(task.dest)
        ], reportError);
    };
};

gulp.task('a', createJsModule(config.tasks.a));
gulp.task('b', createJsModule(config.tasks.b));
gulp.task('c', createJsModule(config.tasks.c));
```
