### ISSUE TITLE
gulp task ends with an unresolved/unrejected promise

### ISSUE THREAD

**Issue by michael8090** [gulpjs/gulp#2041]
----

**What were you expecting to happen?**
gulp should not end the task if the returned promise is not resolved/rejected;

**What actually happened?**
it exits anyway

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task('test', () => new Promise(resolve => null));
```

**What version of gulp are you using?**
3.9.1

**What versions of npm and node are you using?**
node: v6.11.2
npm: 3.10.10

**Comment by phated** [comment]
The promise implementation in 3.x is pretty terrible. 4.0 will solve this.

**Comment by michael8090** [comment]
Last year you said the same, but it's still 3.9.1 now....https://github.com/gulpjs/gulp/issues/1752

**Comment by GongT** [comment]
I just run into this at 2018.12 💩
