### ISSUE TITLE
Completion suggesting items from console.log()

### ISSUE THREAD

**Issue by TheColorRed** [gulpjs/gulp#2044]
In my `~/.bashrc` file, I have the following:

```
eval "$(gulp --completion=bash)"
```

When I try to use the autocomplete feature (tab twice) I get a list of tasks, and a list of words from `console.log()`

----

**What were you expecting to happen?**

I was just expecting these two:

```
dev              prod
```

**What actually happened?**

Autocomplete suggested:

```
dev              file             found.           prod             settings.json    The              was
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
let settings = {};
try {
  settings = require(path.join(__dirname, '/settings.json'))
  console.log('The "settings.json" file was found.')
} catch (e) {
  console.log('Could not find or load "settings.json".')
}

gulp.task('dev', () => {
  // do stuff
})

gulp.task('prod', () => {
  // do stuff
})
```

**What version of gulp are you using?**
3.9.1

**What versions of npm and node are you using?**
npm: 5.5.1
node: 8.0.0

**Comment by phated** [comment]
Use gulp-cli instead of gulp globally - I believe we silence console.log in the new versions.

**Comment by contra** [comment]
`npm rm gulp gulp-cli -g && npm install gulp-cli -g` btw
