### ISSUE TITLE
Callback argument in gulp.watch() does not work as expected

### ISSUE THREAD

**Issue by marcofugaro** [gulpjs/gulp#2045]
Hey, I was trying out gulp 4, it was all nice and wonderful, until I came across this issue which I don't know if it's an issue with the documentation or just with gulp.

**What were you expecting to happen?**
I need the callback function passed as a third argument to `gulp.watch()` to be called when there is a `change`, `add` or `unlink` event. [Like the docs say](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#fn-1).

**What actually happened?**
The callback function never gets called.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
function watch() {
  const socket = io.listen(WEBSOCKET_PORT)
  const triggerFileChange = () => {
    console.log('Callback called')
    socket.emit('file changed')
  }

  gulp.watch('src/**/*.js', scripts, triggerFileChange)
  gulp.watch('src/**/*.scss', styles, triggerFileChange)
  gulp.watch(paths.manifest, manifest, triggerFileChange)
  gulp.watch(paths.images, images, triggerFileChange)
  gulp.watch(paths.markup, markup, triggerFileChange)
}
```
[Here is the full gulpfile](https://github.com/marcofugaro/npm-to-github/blob/3b007f79d5c6c7447f935bbd5cefb59091cb77bd/gulpfile.js)

**What version of gulp are you using?**
4.0.0-alpha.2

**What versions of npm and node are you using?**
node v8.9.1 
npm v5.5.1

**EDIT**:
[This is the relative line](https://github.com/gulpjs/gulp/blob/6d71a658c61edb3090221579d8f97dbe086ba2ed/index.js#L42) in the gulp source code, the line gets executed correctly.

Also if I use only one argument, like this
```js
gulp.watch('src/**/*.js', gulp.parallel(scripts, triggerFileChange))
```
it works fine

**EDIT2**:
Actually something else is happening, the task in the gulp.watch gets called only the first time a file changes, each gulp.watch acts like this. I have no idea why.

**Comment by phated** [comment]
The docs are out of date.  You should follow the docs at https://github.com/gulpjs/glob-watcher which fully describe how to use the watch functionality (and why your task isn't being executed a 2nd time. hint: you aren't signaling completion)

**Comment by marcofugaro** [comment]
Ok! I read the glob-watcher documentation and it's all clear now, I know about async completion.

I think the original problem is with me believing from the docs that you could use the third parameter as a callback being called after the task in the second argument is done, like this
`gulp.watch('filename.js', task, callback)`
so it wouldn't need async completition.

I guess I'll do it like this:
```js
const triggerFileChange = (done) => {
  socket.emit('file changed')
  done()
}

gulp.watch('src/**/*.js', gulp.series(scripts, triggerFileChange))
```

Do you know how can I use in any way `async-done` in this situation?

**Comment by phated** [comment]
@marcofugaro your usage of `gulp.series` to compose your 2 functions is correct.  I'm not sure why you thought watch would take 3 arguments, none of the gulp4 APIs behave that way and all rely on function composition with `series` and `parallel`
