### ISSUE TITLE
Gulp hangs when tasks are required from external file

### ISSUE THREAD

**Issue by niftylettuce** [gulpjs/gulp#2048]
> gulpfile.js

```js
const gulp = require('gulp');
const tasks = require('./tasks');
tasks(gulp);
```

> tasks.js

```js
function tasks(gulp) {
  gulp.task('hello', done => done());
}
module.exports = tasks;
```

> If you run `gulp <task>` will indefinitely hang:

```sh
gulp hello
```

**Comment by niftylettuce** [comment]
I've also tried this without arrow functions, and with normal gulp pipeline tasks, like CSS/JS/uglify etc.  Tried it with callbacks and without callbacks, and also with returning, e.g. `return gulp.doSomething`.

**Comment by phated** [comment]
You didn't follow the issue template.  I can't replicate your issue.
