### ISSUE TITLE
Gulp hangs when tasks are required from external file

### ISSUE THREAD

**Issue by niftylettuce** [gulpjs/gulp#2051]
**What were you expecting to happen?**

Process should exit

**What actually happened?**

Process did not exit

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

> gulpfile.js

```js
const gulp = require('gulp');
const tasks = require('./tasks');
tasks(gulp);
```

> tasks.js

```js
function tasks(gulp) {
  gulp.task('hello', done => done());
}
module.exports = tasks;
```

> If you run `gulp <task>` will indefinitely hang:

```sh
gulp hello
```

**What version of gulp are you using?**

gulp version 3.9.1
gulp cli version 1.4.0

**What versions of npm and node are you using?**

node --version
v8.9.0

npm --version
5.5.1

**Comment by niftylettuce** [comment]
Related to https://github.com/gulpjs/gulp/issues/2048

**Comment by phated** [comment]
Still missing CLI version, etc.

Furthermore, I don't believe your simplified example is actually causing you problems.  An "infinite hang" is often caused by another library you are using holding the event loop open (commonly, karma runner does this).

**Comment by niftylettuce** [comment]
I just updated the note above since I forgot to put versions.  Refresh and it should be visible there.

**Comment by niftylettuce** [comment]
I'm not using any other libraries, the example I mentioned above does in fact hang without any other dependencies than gulp version 3.9.x.

**Comment by niftylettuce** [comment]
gulp cli version is 1.4.0 (latest from npm)
