### ISSUE TITLE
Can you upgrade gulp/vinyl-fs to latest version?

### ISSUE THREAD

**Issue by Chalin-Shi** [gulpjs/gulp#2052]
`npm ls graceful-fs`
Then:
```shell
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3 
│   └── graceful-fs@3.0.11 
```
When node version >= 7.8, the `graceful-fs` version must great than 4.0.0
But i find the latest version of `vinyl-fs` is 2.4.4, Why don't upgrade it?

**Comment by phated** [comment]
Do you not understand how semver works?

**Comment by jybleau** [comment]
@Chalin-Shi #1571
