### ISSUE TITLE
Gulp 4 \ Gulp-Pug: included files (only) increases compile time on each save.

### ISSUE THREAD

**Issue by hettcher** [gulpjs/gulp#2054]
Hey, lads!
Found a lot of issues with the same point, but unfortunately that solutions doesn't helped me.

dependencies:
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-pug": "^3.3.0",
    "gulp-sass": "^3.1.0"

Gulp: 
 CLI version: 1.4.0
 Local version:  Local version 4.0.0-alpha.2

NPM: 5.5.1
Node: 8.9.1
Windows: 7 (x64)

Gulpfile:
![e__front-end_developing_gulp_gulpfile js gulp portfolio - sublime text unregistered 2017-12-01 03 04 33](https://user-images.githubusercontent.com/26379246/33463134-690cc0e8-d644-11e7-8b6f-0d45e0dfe4d5.jpg)

Problem:
1. Proof: (everything's when i save index.pug)
![mingw64__e_front-end_developing_gulp 2017-12-01 03 11 38](https://user-images.githubusercontent.com/26379246/33463320-9b7157f0-d645-11e7-9a61-f708f57ce988.jpg)

2. Proof: (first 5 saves - index.pug, then switched on included files and start saving it, and what we have)
![mingw64__e_front-end_developing_gulp 2017-12-01 03 18 11](https://user-images.githubusercontent.com/26379246/33463421-54cb7924-d646-11e7-9afe-d79756fdbfbb.jpg)

3. Proof: (when i start save first included .pug files)
![mingw64__e_front-end_developing_gulp 2017-12-01 03 08 03](https://user-images.githubusercontent.com/26379246/33463231-f11d4bd8-d644-11e7-99e7-15453467105b.jpg)

The only problem is when i'm using gulp 4 with gulp-pug (with gulp-sass everything's okey)
Gulp 3.9.1 - works fine, even when i save included files.

Important!
This problem is observed on my PC ( before gulp 4 i had gulp 3.9.1, but i followed to your instructions how to update gulp to 4 version), also clean npm cache / delete cache (manually), uninstall Node / switch version from 5.5.1 to 8.9.1, uninstall gulp globally - nothing helped me

On my laptop (where gulp 4 was installed first, as Node (begin from 8.9.1 version) everything's okay. Laptop has the same characteristics as PC.

**Comment by anwerso** [comment]
Looks like a same [old chokidar issue](https://github.com/paulmillr/chokidar/issues/328). `usePolling: true` in watch options will help for now. Not an ideal solution, but I don't know a better one.

**Comment by phated** [comment]
Going to chalk this up to the chokidar issue.  If you do any deeper debugging, please update here or the chokidar issue (depending on where the results show problems belonging).

**Comment by hettcher** [comment]
Sorry for long answer.
Chocidar issue: i have another problem, it doesn't matter if i use global
path or not. The problem is in gulp 4, cuz gulp 3.9.1 works fine.
Look:
gulp 4.0 alpa + gulp-pug 3.3.0 - bug, increase saving time
gulp 3.9.1 + gulp-pug 3.3.0 - work's fine

gulp tasks the same for each variation.

i'm interesting: why i have problem on my PC, but on my laptop everything
works fine? ( OS the same ). What i'm i do? - reinstall windows and it
didn't help. =(

on this weekend i'll try how it will work with chocidar (cuz now i made a
pullback on old gulp version 3.9.1)

2017-12-05 22:22 GMT+02:00 Blaine Bublitz <notifications@github.com>:

**Comment by hettcher** [comment]
Sorry for long answer.
Yeap, @anwerso was right, usePolling: true, it helped me. Thx.
Anyway. i'm wondering why i have the same OS ( PC & Laptop ), the same gulp settings (package) and problem only on the PC. I suppose that problem in the hard drive (PC has old&slower hard drive).
if I have the opportunity to check it, i'll let you know.
