### ISSUE TITLE
Using "pump" with/without return

### ISSUE THREAD

**Issue by brendanfalkowski** [gulpjs/gulp#2058]
The docs suggests "using pump" for error handling:
https://github.com/gulpjs/gulp/blob/master/docs/why-use-pump/README.md

The example (unlike most Gulp tasks) does not `return pump`, but this works great and cleaned up my error reporting. The pump example:

```js
gulp.task('compress', function (cb) {
  pump([
      gulp.src('lib/*.js'),
      uglify(),
      gulp.dest('dist')
    ],
    cb
  );
});
```

Not returning pump fails for `gulp-imagemin` though:
https://github.com/sindresorhus/gulp-imagemin/issues/285

The author patiently replied that the pump example is incorrect, and Gulp tasks should always `return`.

That seems to be true, but the developer experience is worse when returning pump because the console fills with junk (the reason I like pump is not having that happen):
https://github.com/sindresorhus/gulp-imagemin/issues/285#issuecomment-350189618

Are "correct" and "good" at odds here? Seems like an area to improve in Gulp or module integration.

**Comment by phated** [comment]
pump doesn't return anything and you are using it correctly.  That module is broken, sorry.

**Comment by phated** [comment]
@brendanfalkowski I noticed you have `reportErrors` as the callback in the linked code.  You need to actually pass the task's `cb` as that argument or call it within `reportErrors` (but that isn't within the closure).

**Comment by phated** [comment]
I'd take everything sindre says with a grain of salt.  Pretty sure he hasn't looked at gulp for the past 5 years...

**Comment by brendanfalkowski** [comment]
@phated — Thanks for the tips, much appreciated.

I think I'm missing your point on callbacks. My `errorHandler()` function is imported and assigned as a global var. This seems to work fine:

### gulpfile.js

```js
var errorHandler = require('./gulp/error-handler.js');

gulp.task('css', function () {
    var task = config.task.css;

    pump([
        gulp.src(task.src),
        sass(task.sassOptions),
        gulp.dest(task.dest
    ], errorHandler);
});
```

### error-handler.js

```js
module.exports = function (error) {
    // Read `error` properties
    // Log something useful
};
```

### Logged message (my function)

<img width="1050" alt="screen shot 2017-12-12 at 10 19 13 pm" src="https://user-images.githubusercontent.com/214924/33924373-a96ada5e-df8a-11e7-8144-932268922616.png">

— — — — — — — — — — 

### Modified with callback

```js
var errorHandler = require('./gulp/error-handler.js');

gulp.task('css', function (errorHandler) {
    var task = config.task.css;

    pump([
        gulp.src(task.src),
        sass(task.sassOptions),
        gulp.dest(task.dest
    ], errorHandler);
});
```

### Logged message (not my function)

<img width="1053" alt="screen shot 2017-12-12 at 10 18 14 pm" src="https://user-images.githubusercontent.com/214924/33924410-d3059836-df8a-11e7-81f6-d09427b594a1.png">

— — — — — — — — — — 

I'm not sure if there's a sync/async benefit from reading here:
https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulptaskname--deps--fn

Otherwise using the callback seems to output the whole error object instead of using the function.

I'm sure I'm not doing that right, but what's the benefit of the callback?

**Comment by terinjokes** [comment]
When using pump you need to call the callback given to your task by gulp,
usually by passing it as the second argument to pump.

In your first example you're never calling it (and, in fact, never even
giving it a name) so gulp doesn't know your task is finished. (You're also
not returning anything, so gulp has no idea what your task is trying to do)

**Comment by phated** [comment]
@brendanfalkowski It seems like you are missing some JS fundamentals but hopefully @terinjokes' response helps you.

However, we are not a support forum and I feel like we've outlined your issue enough so I'm going to have to lock this.  If you need further help, I'd suggest opening this on StackOverflow.
