### ISSUE TITLE
Etiquetas Video Html

### ISSUE THREAD

**Issue by 8bitcodeblue** [gulpjs/gulp#2060]
//-->Etiquetas Video  utilizando Html --//

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Tag Video</title>
</head>
<body>
	

   <video width="720" height="1270" controls="controls" autoplay="autoplay" loop="loop" preload="none" poster="img.jpg" > 

    

    <source src="video.mp4" type="video/mp4" />
    <source src="video.ogg" type="video/ogg" />

   </video>

</body>
</html>

**Comment by callumacrae** [comment]
http://stackoverflow.com/
