### ISSUE TITLE
Publish @next 4.x version

### ISSUE THREAD

**Issue by kikar** [gulpjs/gulp#2063]
I'm trying to use docker to build my code, but I can't get `gulp 4.x` without installing git.
Could you publish a `gulp@next` version so we won't need to download it directly from git?

**Comment by phated** [comment]
No, it's not ready to be published yet. You can point npm at an http address and it will work without Git.

**Comment by kikar** [comment]
Thanks for the reply @phated , do you know which URL shall I use?
Because according to npm docs:

> Install the package at https://github.com/githubname/githubrepo by attempting to clone it using git.

So it should still try to use git.

There is another possibility having a link to a tarball:

> npm install \<tarball url\>:
> Fetch the tarball url, and then install it. In order to distinguish between this and other options, the argument must start with "http://" or "https://"

Any ideas?

**Comment by phated** [comment]
Github exposes zips and tars...
Zips: https://github.com/gulpjs/gulp/archive/4.0.zip
Tars: https://github.com/gulpjs/gulp/archive/4.0.tar.gz
