### ISSUE TITLE
gulp@4.0.0-alpha.3 breaks gulp scripts with vinyl issue "file.isSymbolic is not a function"

### ISSUE THREAD

**Issue by dozer75** [gulpjs/gulp#2065]
It seems that during this night the alpha.3 package was released of gulp. But when running typescript compiling using this, i get a stacktrace that states `TypeError: file.isSymbolic is not a function`

The complete stacktrace for this is:
```

    at DestroyableTransform.normalize [as _transform] (C:\Temp\Project\node_modules\vinyl-fs\lib\dest\prepare.js:31:15)
    at DestroyableTransform.Transform._read (C:\Temp\Project\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Temp\Project\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Temp\Project\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Temp\Project\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Temp\Project\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (C:\Temp\Project\node_modules\duplexify\index.js:201:22)
    at doWrite (C:\Temp\Project\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Temp\Project\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Pumpify.Writable.write (C:\Temp\Project\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at DestroyableTransform.ondata (C:\Temp\Project\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (C:\Temp\Project\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Temp\Project\node_modules\readable-stream\lib\_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (C:\Temp\Project\node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (C:\Temp\Project\node_modules\readable-stream\lib\_stream_transform.js:146:32)
```

I install gulp using npm with the following configuration in package.json:

`"gulp": "github:gulpjs/gulp#4.0"`

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
var gulp = require("gulp");
var typescript = require("gulp-typescript");
var sourcemaps = require("gulp-sourcemaps");


var typescriptCompile = function (file, done) {
    const tsProject = typescript.createProject("tsconfig.json");

    if (file === null) {
        file = srcPaths.typescript + "**/*.ts";
    } else {
        console.log(`Compiling ${ file }`);
    }

    gulp.src(file)
        .pipe(sourcemaps.init())
        .pipe(tsProject())
        .js
        .pipe(sourcemaps.write(".", {
            includeContent: true, mapSources: function (sourcePath) {
                while (sourcePath.startsWith("../")) {
                    sourcePath = sourcePath.replace("../", "");
                }

                return `/${sourcePath}`;
            } }))
        .pipe(gulp.dest(destPaths.app))
        .on("end", done);
};

gulp.task("compile.typescript", function (done) {
    typescriptCompile(null, done);
});
```

**What version of gulp are you using?**
Gulp 4.0 alpha 3

**What versions of npm and node are you using?**
npm version 3.10.10
node version v6.10.2

**Comment by phated** [comment]
Your plugins need to be updated to use a newer vinyl. The one they are using to create file objects is really old.

**Comment by dmoosocool** [comment]
i got same error.  how can i use alpha 2?

**Comment by dozer75** [comment]
@phated Which plugins? I don't have any references to vinyl myself. The only one is via gulp.

@dmoosocool You can reference the previous commit id instead of the branch name after the `#`. The last one is `6d71a65`

**Comment by 417673259** [comment]
my plugins  is  the latest version 2.1 ，but  get this error   "file.isSymbolic is not a function"

**Comment by eugenegodun** [comment]
@417673259 the latest version of vinyl-fs is 3.0.0 - but it doesn't help me :)

**Comment by 417673259** [comment]
@eugenegodun  You can reference the previous commit id instead of the branch name after the #. The last one is 6d71a65     
solved the problem

**Comment by ba55ie** [comment]
Or you can install [this alternative gulp4](https://www.npmjs.com/package/gulp4) package:
`npm i -D gulp4@4.0.2`

**Comment by SilverJan** [comment]
For the lazy ones to copy & paste: 

 "devDependencies": {
    "gulp": "github:gulpjs/gulp#6d71a65"
  }

or

npm install gulpjs/gulp#6d71a65

**Comment by GregorSondermeier-FD** [comment]
I am experiencing the same problem. Using `gulpjs/gulp#6d71a65` instead of `gulpjs/gulp#4.0` temporarily fixed it for me so I can enjoy the holidays.

As I understand it, the upgrade from `"gulp-cli": "^1.0.0"` to `"gulp-cli": "^2.0.0"` causes the error.

**Comment by tknerr** [comment]
woah... super confusing that `gulpjs/gulp#4.0` points to a branch, not a tag... 

why are there no tags for the 4.0 alpha versions anyway so that we can pin to them?

**Comment by simonua** [comment]
@tknerr, yep, you're exactly right. =(

![image](https://user-images.githubusercontent.com/8005145/34302612-abc8cac8-e6ff-11e7-9a0f-be550e9937b6.png)

@phated, Do you think it would be sensible to tag [6d71a65](https://github.com/gulpjs/gulp/commit/6d71a658c61edb3090221579d8f97dbe086ba2ed) with an appropriate tag that would make it less cryptic in a _package.json_ than referencing the commit itself? Having a tag such as `4.0.0-alpha.X-pre-vinyl-fs-3.0.0` would reveal more information to a reader (and myself in two weeks when I will have forgotten all this) than a commit. Damn you, Doug Crockford, for not having a comment format in JSON. =P

**Comment by phated** [comment]
This thread is getting out of hand so I'm going to consolidate stuff and clean up this thread.

If you are encountering this error:
1. Have your plugins update the version of `vinyl` they are using to ^2 - preferably ^2.1
2. If they are using gulp-util - get them to STOP and use specific modules directly. The gulp-util grabbag is a gigantic mess.
3. (If you can't or **won't** do the above) Downgrade to alpha.2 with `npm install -S gulpjs/gulp#6d71a65`

**Comment by phated** [comment]
With the release of vinyl-fs 3.0.1, we've added a temporary fix that converts old Vinyl objects to new ones required by vinyl-fs.  If you are having this problem, please ensure you have the very latest vinyl-fs dependency.

**Comment by phated** [comment]
gulp 4 has been published under the `next` tag (`npm install gulp@next`) and it has the temporary workaround for this problem so I'm going to close this.

We're also making a lot of progress on the ecosystem migration thanks to @demurgos
