### ISSUE TITLE
gulp.watch runs by itself periodically (roughly twice a second)

### ISSUE THREAD

**Issue by sryze** [gulpjs/gulp#2069]
I'm in the process of integrating gulp into an existing project. I want to minify only some JS files, so I use this code:

```js
const srcRoot = path.join(__dirname, 'WebContent');
const webRoot = path.join(__dirname, 'WebContent');

const jsFilesToMinify = [
    'js/file1.js',
    'js/file2.js'
];

gulp.task('minify-js', () => {
    return gulp.src(jsFilesToMinify.map(file => path.join(srcRoot, file)))
        .pipe(sourcemaps.init())
        .pipe(uglify())
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(file => {
            const destRelativePath = path.relative(srcRoot, path.dirname(file.path));
            return path.join(webRoot, destRelativePath);
        }));
});

gulp.task('watch', ['default'], () => {
    for (let file of jsFilesToMinify.map(file => path.join(srcRoot, file))) {
        gulp.watch(file, ['minify-js']);
    }
});
```

For some odd reason when I run `gulp watch` it runs `default` tasks fine but then it begins to run `minify-js` once every half a second for no reason - file doesn't change (I closed the editor to be sure).

I also tried doing it like this:

```js
gulp.watch(jsFilesToMinify.map(file => path.join(srcRoot, file)), ['minify-js']);
```

^ Same problem.

**What version of gulp are you using?**
CLI version 1.3.0
Local version 3.9.1

**What versions of npm and node are you using?**
npm: 5.3.0
node: v8.4.0

OS: Windows 10

**Comment by phated** [comment]
@sryze glad you figured it out.

**Comment by sryze** [comment]
I had to use `{cwd: srcRoot}` instead of simply prefiing file paths with `srcRoot` . I don't know why, but it worked.

**Comment by phated** [comment]
Cool.  Using `path.join` on Windows soon won't work so I'm glad you moved away from that.
