### ISSUE TITLE
Gulp : Getting error on unit test case failures

### ISSUE THREAD

**Issue by reachmohit247** [gulpjs/gulp#2075]
I want to fail my webapps build if any unit test case fails. So, I have written below code.

`gulp.task('test', function (done) {
new Server({
    configFile: path.join(__dirname, 'unit-test-conf.js'),
    singleRun: true
}, function (code) 
{
    if(code==1){
        console.log('Unit Test failures, exiting process');
       done('Unit Test Failures');
    }else{
        console.log('Unit Tests passed');
        done();
    }
}).start();
});`

I am getting below error while running my Gulp tasks :

![capture](https://user-images.githubusercontent.com/24808682/34431011-ed71204c-ec90-11e7-91e3-52b26c33cd82.PNG)

Please suggest.

**Comment by phated** [comment]
This is from the weird module `Server` you are using - whatever pattern you are using is not a recommended pattern and we don't handle support questions.  Please direct support questions to StackOverflow.
