### ISSUE TITLE
Build failing due to vinyl-fs major dependency bump

### ISSUE THREAD

**Issue by carlosvillademor** [gulpjs/gulp#2083]
**What were you expecting to happen?**
My gulpfile to work regardless of the version of vinyl used by other plugins

**What actually happened?**
I think that because of the issue described on https://github.com/gulpjs/vinyl-fs/issues/288, the gulpfile I'm working on does not work, as there are other versions of vinyl in the dependencies tree.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

**What version of gulp are you using?**
4

**What versions of npm and node are you using?**
Node 8.9.3 with NPM 5.6.0

Is there a chance that you publish in the NPM registry the version 4.0.0-alpha.2 that works, because it doesn't contain the dependency bump of vinyl-fs?

**Comment by carlosvillademor** [comment]
I've read now @phated comment on 2nd January in https://github.com/gulpjs/gulp/issues/2078 and @erikkemperman has replied to my question in https://github.com/gulpjs/vinyl-fs/issues/288. That clarifies the issue I was having, so I'm closing this.

Sorry for the hassle.

Thanks

**Comment by ldusoswa** [comment]
I also have this issue.

CLI version 1.3.0
Local version 4.0.0
npm 3.10.10
node v6.10.0

throwing in a breaking change like this really sucks.
