### ISSUE TITLE
Reverting to v4.0.0-alpha.2

### ISSUE THREAD

**Issue by montik** [gulpjs/gulp#2084]
I have a package that seems to work only with gulp4-alpha.2 (since I upgraded to alpha.3 it fails)

I tried to revert to the alpha.2 version
  
```
"devDependencies": {
    "gulp": "gulpjs/gulp#v4.0.0-alpha.2",
}
```
... but npm install fails

```
  $ npm install 
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
```

it looks like  gulp4-alpha.2 has  _gulp-cli#4.0_ as dependency, which is no longer available.

Is there any workaround?

**What versions of npm and node are you using?**
```
$ npm --version
5.6.0
$ node --version 
v9.3.0
```

**Comment by ldusoswa** [comment]
Also interested in the workaround

**Comment by phated** [comment]
Please read the thread at https://github.com/gulpjs/gulp/issues/2078#issuecomment-354690031
