### ISSUE TITLE
Problems with src and path since alpha3/v4 

### ISSUE THREAD

**Issue by rejas** [gulpjs/gulp#2085]
Hi, 
since the releases of v4 we have some inconsistencies inb our build process, had to revert to v4alpha2, so maybe its a dependency update that is repsonsible:

Trying to copy some file:

```
return gulp
        .src(path.join('src/server', 'index.js'))
        .pipe(gulp.dest('dist'));

```
This worked fine with alpha2 and copied the file "src/server/index.js" to "dist/index.js" (as expected)

With alpha3/v4 the file gets copied into

"dist/src/server/index.js"

What do I miss here? Do I use path.join wrong? 

os: windows 10
node 6.12.3 (but also with v8)
npm 3.10.10 (but also with the one from node v8)

**Comment by doowb** [comment]
`gulp.src` takes a glob pattern or an array of glob patterns as the first argument. Since `path.join` on windows will change `/` to `\\`, this creates an invalid glob pattern.

To achieve what you expect, the correct way is to use the `cwd` option to specify the "parent" filepath for the glob patterns to use:

```js
return gulp
  .src('index.js', {cwd: 'src/server'})
  .pipe(gulp.dest('dist'));
```

**Comment by rejas** [comment]
Thanks for the hint, will try to fix it in my code. Any idea why it worked with < alpha2 though ?

**Comment by doowb** [comment]
In short, there was a bug that was fixed, so when it worked it was actually not working. 😀 

Internally, [glob-parent](https://github.com/es128/glob-parent) is used to calculate the "parent" path by searching for the last segment of the pattern (between '/') that has globbing characters in it. I'm not sure how it was finding `src/server` as the parent before if you were using a full file path (e.g. no globs) but it seems that the behavior is correct now... e.g. if you pass in `src('src/server/index.js')` the glob parent will be `'.'`, which causes the `file` properties to look like this:

```js
// assuming the project is in '~/projects/example'
file.base: '~/projects/example'
file.cwd: '~/projects/example'
file.path: '~/projects/example/src/server/index.js'
// relative is from `file.base` to `file.path`
file.relative: './src/server/index.js'
```
Then using `file.relative` to calculate the `dest` path results in `~/projects/example/dist/src/server/index.js`.

By using `gulp.src('index.js', {cwd: 'src/server'})` the `file` properties look like this:

```js
// assuming the project is in '~/projects/example/'
file.base: '~/projects/example/src/server'
file.cwd: '~/projects/example/src/server'
file.path: '~/projects/example/src/server/index.js'
// relative is from `file.base` to `file.path`
file.relative: './index.js'
```

Then using `file.relative` to calculate the `dest` path results in `~/projects/example/dist/index.js`

Hope this helps, I put this together from what I remember, but I'm pretty sure this is correct.

**Comment by phated** [comment]
Thanks @doowb!  `cwd` is definitely the recommended way for setting a common base for your globs and they definitely should not be built with `path.join` - however, I think that just removing `path.join` and using `'src/server/index.js'` should also work.

> Thanks for the hint, will try to fix it in my code. Any idea why it worked with < alpha2 though ?

Alpha versions are not release candidates and you should have expected breaking changes.  We've been working on a series of breaking changes for months.  You can find a more thorough answer at https://github.com/gulpjs/gulp/issues/2078#issuecomment-354690031

> In short, there was a bug that was fixed, so when it worked it was actually not working. 

More to this point, you were relying on an edge case that has been fixed.

**Comment by rejas** [comment]
Of course I expected breaking changes once I saw what version of gulp the developer who started the project used :-) Only a matter of time until Murphys Law comes into play :-) 
But switching back to gulp3 wasnt feasible either but migrating to v4 will get some budget here so once again:
Thanks for the hints and tips and of course for the v4 :-)
