### ISSUE TITLE
gulp-util is deprecated

### ISSUE THREAD

**Issue by thiemeljiri** [gulpjs/gulp#2092]
When installing last version of gulp 3.9.1 I get an warning about `gulp-util` being deprecated.

    npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

The link https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 says what is necessary to do.

**Comment by phated** [comment]
Yep.

**Comment by thiemeljiri** [comment]
But gulp itself has this dependency!

**Comment by phated** [comment]
Fixed in gulp 4.

**Comment by Fen1kz** [comment]
@phated however last version in npm is 3.9.1

**Comment by demurgos** [comment]
Please see the readme: use `npm install gulp@next` (or `gulp@4`) to install Gulp 4.
