### ISSUE TITLE
gulp.watch not working in Gulp 4.0.0

### ISSUE THREAD

**Issue by Dan503** [gulpjs/gulp#2094]
**What were you expecting to happen?**

I have this simple gulp file

`````````js
gulp.task('watch', () => {
  gulp.watch('path/to/file.scss')
    .on('change', gulp.series('sass'));
})
`````````

I run `gulp watch` then save `file.scss` and It should run the `'sass'` task.

**What actually happened?**

I save `file.scss` and nothing happens

**What version of gulp are you using?**

Gulp 4.0.0

**What versions of npm and node are you using?**
npm: 5.5.1
node: 6.12.0

**Comment by Dan503** [comment]
Watch seems to be working as expected when used in a reduced test environement. it must be something wrong with my gulp set up.

(I edited this set up to test it on https://github.com/doowb/gulp-issue-2093)

https://github.com/gulpjs/gulp/issues/2093

**Comment by Dan503** [comment]
I created a pull request in your mini gulp set up that is able to successfully replicate the issue
https://github.com/doowb/gulp-issue-2093/pull/1

**Comment by doowb** [comment]
Same as #2093. You shouldn't use the `path` methods on glob patterns.

**Comment by Paresh1205** [comment]
Thanks For the Post.. It worked..

**Comment by rjptechsolutions** [comment]
Still, my side gulp watch is not running it shows command not found
