### ISSUE TITLE
Add task's logs for JS API

### ISSUE THREAD

**Issue by GProst** [gulpjs/gulp#2104]
When we start gulp task via CLI there are logs:
```
Starting 'MyTaskName'...
Finished 'MyTaskName' after 3.71 ms
```
But when we start gulp task via JS API (`gulp.task('MyTask')(cb)`) there are no such logs, but I think it would be very useful if they were. Especially, when there are multiple tasks running one by one or in parallel.

Can it be implemented?

**Gulp**: 4.0.0
**Node**: 8.9.1
**npm**: 5.6.0

**Comment by phated** [comment]
This won't be implemented.

**Comment by GProst** [comment]
Fair enough! Thanks for reply😅
