### ISSUE TITLE
Gulp series does not update things unless the last task is run

### ISSUE THREAD

**Issue by wdanilo** [gulpjs/gulp#2107]
Hi! I do not know if it is a bug, however I cannot find any information bout this behavior in the docs and it might be a bug, namely, I've got such gulp tasks:

```
gulp.task 'incVersionDev', (done) ->
  gulp.src './package.json'
    .pipe transform 'utf8', incVersionDev
    .pipe gulp.dest('.')
  done()

gulp.task 'publish' , gulp.series 'build', 'incVersionDev', 'copy_package_config', (done) ->
  # execSync 'cat ./package.json', {stdio:'inherit'}
  execSync 'cd lib && npm publish', {stdio:'inherit'}
  done()
```

when I run `gulp publish` I got `npm` error that I cannot publish the same version twice. What happens is that `incVersionDev` runs but it do not writes `package.json` unless are series tasks are run. If I uncomment echo of `package.json` I can clearly see it was not changed. However if I comment the line `execSync 'cd lib && npm publish', {stdio:'inherit'}`, everything works - the version is incremented. 

It seems like gulp is not making changes to files when running series until series is finished - if that is the case, is it the behavior we want? If so, is there any way to accomplish what I want to do here?

gulp version: next
npm version: 5.5.1

**Comment by phated** [comment]
This is not correct stream usage. Please fix your usage.

**Comment by wdanilo** [comment]
@phated I would love to fix my usage, however first I need to understand what is wrong here. I've been reading docs, but they cover only basics and there are no examples of "correct stream usage" as far as I know. I've been searching other topics and I've seen people using it in similar way. What's wrong here?

**Comment by wdanilo** [comment]
Ok, I think I know what you were referring to - namely I should not use the `done` function. It is not clearly described in docs - in fact it's usage is still not clear to me. However, I've got progress with this issue and see some strange results. If I change the code to:

```gulp.task 'incVersionDev', ->
  gulp.src './package.json'
    .pipe transform 'utf8', incVersionDev
    .pipe gulp.dest('.')
  done()

gulp.task 'publish' , gulp.series 'build', 'incVersionDev', 'copy_package_config', ->
  execSync 'cd lib && npm publish', {stdio:'inherit'}
  done()```

It works (does exactly waht I want), but after execution it throws an error: 
```
[04:35:38] No gulpfile found
```
It's strange because the error is thrown after everything is done successfully. Here is a full log of it: 
```
npm run publish

> basegl@0.1.12 publish /home/wdanilo/dev/libs/basegl
> npx gulp --gulpfile build/gulpfile.coffee publish

[04:35:32] Requiring external module coffeescript/register
[04:35:32] Working directory changed to ~/dev/libs/basegl/build
[04:35:32] Using gulpfile ~/dev/libs/basegl/build/gulpfile.coffee
[04:35:32] Starting 'publish'...
[04:35:32] Starting 'build'...
[04:35:32] Starting 'copy_package_config'...
[04:35:32] Finished 'copy_package_config' after 37 ms
[04:35:32] Starting 'transpile_coffee'...
[04:35:33] Finished 'transpile_coffee' after 985 ms
[04:35:33] Starting 'transpile_glsl'...
[04:35:33] Finished 'transpile_glsl' after 14 ms
[04:35:33] Finished 'build' after 1.04 s
[04:35:33] Starting 'incVersionDev'...
[04:35:33] Finished 'incVersionDev' after 3.46 ms
[04:35:33] Starting 'copy_package_config'...
[04:35:33] Finished 'copy_package_config' after 3.77 ms
[04:35:33] Starting '<anonymous>'...

> basegl@0.1.13 publish .
> npx gulp --gulpfile build/gulpfile.coffee publish

[04:35:38] No gulpfile found
```
Note, that when the error occurs, everything is done already. Here is the npm log: https://pastebin.com/raw/ddDFmqfT

**Comment by phated** [comment]
@wdanilo you've fixed your stream issue (of course, you're relying on implicit returns).  For your other issue: this is not a support forum.  Support questions should be directed to StackOverflow, but you might want to look into your usage of `npx` inside the `publish` script.

**Comment by wdanilo** [comment]
Thank you!
