### ISSUE TITLE
Global installation with Yarn returns CLI version number for Gulp 4

### ISSUE THREAD

**Issue by TimvdLippe** [gulpjs/gulp#2112]
Maybe this is simply working as intended, but I found it confusing at first. Today I tried out `gulp` 4 from my commandline. To do so, I ran `yarn global add gulp`, which installed `gulp` 3. I discovered this, as I ran `gulp --version` which returned the following output:

```
[15:07:21] CLI version 3.9.1
```

Quickly I fixed my error per the documentation (great documentation btw, props for that :+1: ). I ran `yarn global add gulp@next` and `yarn` reported the following:

```
success Installed "gulp@4.0.0" with binaries:
      - gulp
```

Now I ran `gulp --version` again to double check that I got the correct version. However, to my surprise it suddenly returned version 2.0.1. I realize that this is because it is using `gulp-cli` which has this version number, but I would have expected to see the `gulp` version number here, which should be 4.0.0 as I installed that package.

Could you update this command flag to return `4.0.0` instead of the version of the `gulp-cli`? Or maybe even both numbers for improved debugging for issues.

**What were you expecting to happen?**
`gulp --version` returns 4.0.0
**What actually happened?**
```
[15:08:11] CLI version 2.0.1
```

**What version of gulp are you using?**
`yarn global add gulp@next` which right now is `gulp@4.0.0`

**What versions of npm and node are you using?**
Node 8.9.4
Npm 5.6.0
Yarn 1.3.2

**Comment by doowb** [comment]
@TimvdLippe `gulp-cli` is intended to be installed globally and `gulp` is intended to be installed locally in your project. `gulp-cli` provides the `gulp` command so when running `gulp --version` it should show the global CLI version and the local `gulp` version.

[The getting started](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) docs provide more information.

I'm going to close this here, but if you feel that `gulp-cli` should show the global version of `gulp` too, then feel free to [open an issue there](https://github.com/gulpjs/gulp-cli/issues).
