### ISSUE TITLE
Gulp.Watch doesn't work on files inside a symlink folder

### ISSUE THREAD

**Issue by sherpaco** [gulpjs/gulp#2114]
**What were you expecting to happen?**

File changes inside a symlink folder to trigger Gulp.Watch

**What actually happened?**

Nothing.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task('watch',function() {
  return gulp.watch('wp-content/themes/pm/less/*.less',gulp.series('less'));
});
```

If I change "pm" to "twentyseventeen" everything works fine.

Similarly, if I remove the symlink folder "pm" and replace it with a real "pm" folder, gulp.watch also works fine. 

Other tasks work, as well. For example, compiling LESS to CSS functions normally. It just seems to be gulp.watch that's the issue.

**Folders**

wp-content
  -themes
    --twentyseventeen
      ---less
    --pm (symlink)
      ---less

**What version of gulp are you using?**

4.0.0-alpha.2

**What versions of npm and node are you using?**

npm: 4.2
node: 6.10.0

**Comment by phated** [comment]
1. Stop using alpha 2
2. This is a thoroughly discussed problem with chokidar. I forget the solution off the top of my head. You can search on their issue tracker.

**Comment by sherpaco** [comment]
I did do a search, and found several workarounds here: https://github.com/paulmillr/chokidar/issues/293

However, they don't work. I tried to glob the entire themes folder, and while that worked properly for the twentyseventeen folder (as expected), the "PM" symlink folder still did not trigger gulp.watch.

**Comment by sherpaco** [comment]
While I haven't been able to get gulp.watch to work, I did switch to [Gaze](https://www.npmjs.com/package/gaze), which worked straight out of the box.

**Comment by phated** [comment]
Glad you found something that worked because we weren't switching back after removing gaze.
