### ISSUE TITLE
Task 'Watch' is not in your gulpfile

### ISSUE THREAD

**Issue by Priyankapuri87** [gulpjs/gulp#2119]
Hi ,I am new to gulp . This file runs but did'nt do changing in the css file. Please help
var themename = 'template';

var gulp = require('gulp'),
    // Prepare and optimize code etc
    autoprefixer = require('autoprefixer'),
    browserSync = require('browser-sync').create(),
    image = require('gulp-image'),
    jshint = require('gulp-jshint'),
    postcss = require('gulp-postcss'),
    sass = require('gulp-sass'),
    sourcemaps = require('gulp-sourcemaps'),

    // Only work with new or updated files
    newer = require('gulp-newer'),

    // Name of working theme folder
    root = '../' + themename + '/',
    scss = root + 'sass/',
    js = root + 'js/',
    img = root + 'images/',
    languages = root + 'languages/';

// CSS via Sass and Autoprefixer
gulp.task('css', function() {
    return gulp.src(scss + '{style.scss,rtl.scss}')
        .pipe(sourcemaps.init())
        .pipe(sass({
            outputStyle: 'expanded',
            indentType: 'tab',
            indentWidth: '1'
        }).on('error', sass.logError))
        .pipe(postcss([
            autoprefixer('last 2 versions', '> 1%')
        ]))
        .pipe(sourcemaps.write(scss + 'maps'))
        .pipe(gulp.dest(root));
});

// Optimize images through gulp-image
gulp.task('images', function() {
    return gulp.src(img + 'RAW/**/*.{jpg,JPG,png}')
        .pipe(newer(img))
        .pipe(image())
        .pipe(gulp.dest(img));
});

// JavaScript
gulp.task('javascript', function() {
    return gulp.src([js + '*.js'])
        .pipe(jshint())
        .pipe(jshint.reporter('default'))
        .pipe(gulp.dest(js));
});

// Watch everything
gulp.task('watch', function(){
    gulp.watch('./sass/**/*.scss',['sass']);
});

// Default task (runs at initiation: gulp --verbose)
gulp.task('default', ['watch']);

**What version of gulp are you using?**
Local and CLI 3.9.1
**What versions of npm and node are you using?**
npm-5.6.0 and node - v8.9.4

**Comment by phated** [comment]
Hey @Priyankapuri87 - this is not a support forum.  Support questions should be directed to StackOverflow.
