### ISSUE TITLE
Gulp Tasks not working after updating my npm to 5.6.0.

### ISSUE THREAD

**Issue by Anuj-logiciel** [gulpjs/gulp#2123]
Earlier it was working with NPM v2.11.3 . But now with NPM v5.6.0 , All tasks are running If I type *gulp watch* from terminal but without this not anything working (Gulp watch not running on any changes in files).

**Comment by ParallelUniv3rse** [comment]
Could you please provide an error log and the version of your node and gulp as well? We can't help you much without this info, thanks :)

**Comment by phated** [comment]
This is not a support forum and we have nothing to do with Iconic.
