### ISSUE TITLE
Reusing gulpfile.js across serveral directories/modules?

### ISSUE THREAD

**Issue by frontyard** [gulpjs/gulp#2125]
I'm trying to split out large project into modules. I still want to use single gulpfile.js as an entry point into the build as there is a lot of reuse across modules.

I've tried symlinking, I've tried passing --gulpfile, both of these end up with Gulp using directory of the gulpfile.js as it's working directory.

Setting --cwd explicitly doesn't help either.

Is there a way to tell Gulp to use current directory as a working directory or to pass one explicitly?

CLI version 2.0.1
Gulp version 3.9.1
macOS High Sierra 10.13.2
nodejs version 6.10.2
npm version 4.6.1

**Comment by frontyard** [comment]
Another thing that DOES NOT work is extracting gulp tasks into common directory and using requireDir to include those tasks into local gulpfile.js. All those tasks using the common directory as their working directory not the directory of the gulpfile.js

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
