### ISSUE TITLE
Gulp Dest behaves differently for output destination path on windows and Linux

### ISSUE THREAD

**Issue by geekman-rohit** [gulpjs/gulp#2132]
**What were you expecting to happen?**
I have the following code copying a set of files from node_nodules to a vendor directory, surprisingly it copies do different sub directories, replicating the entire structure of file path in windows and simply copying the file to the directory in linux

**What actually happened?**
In windows irrespective of the blob containing any special characters, the entire path including node_modules is replicated, so the structure looks something like this
```
vendor
    node_modules
        jquery
            dist
                jquery.min.js
```
On Linux the file is simply copies inside vendor directory to 
```
vendor
    jquery.min.js
```
    
**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task('copy-node', function(){
  const rawdata = fs.readFileSync('vendor.json');
  const assets = JSON.parse(rawdata);
  var copytask = assets["files"];
  var prefix = "node_modules";
  var files = copytask.map(function(x){return path.join(prefix, x)});
  return gulp.src(files)
  .pipe(gulp.dest('dist/vendor/'))

});
```
Contents of vendor.json
```json
{
  "files": [
    "jquery/dist/jquery.min.js",
    "bootstrap/dist/js/bootstrap.min.js",
    "popper.js/dist/umd/popper.min.js"
  ]

}
```

**What version of gulp are you using?**
4,0.0

**What versions of npm and node are you using?**
NPM 5.6.0,  Node 8.9.4

**Comment by doowb** [comment]
Instead of these 2 lines:

```js
  var files = copytask.map(function(x){return path.join(prefix, x)});
  return gulp.src(files)
```

use the `cwd` option:

```js
return gulp.src(copytask, {cwd: prefix})
```

The reason for this is that `path.join` will use `\` on windows which is an escape character in a glob pattern.

**Comment by phated** [comment]
^ thanks @doowb!
