### ISSUE TITLE
gulp.watch not working properly on node v9.6.1

### ISSUE THREAD

**Issue by lessu** [gulpjs/gulp#2133]
**What were you expecting to happen?**
Watch should always be triggered when file changes.

**What actually happened?**
Watch triggers only twice when file changes.

**My procedure**
1.Run `gulp watch`

2.edit build/js/index.js
3.check console message,
4.✅watch is triggered properly

5.edit build/js/index.js
6.check console message,
7.✅watch is triggered properly

8.edit build/js/index.js
9.check console message,
10.❌nothing happened

Any further editing for index.js will never trigger watch event again.
However,Editing on another file works,for example index2.js ,but after repeating 2 times, index2.js will not be able to trigger either.

**What did I do**
This only happens on node v9.6.1 in my case (just update today).
Then I tried switch to node/8.4.0 and nothing goes wrong any more,it works like a charm.

I also have tried plugin `gulp-watch`,same phenomenon was found.

**My Code**
```js
gulp.task('watch', function() {
    gulp.watch(["src/**/*.css"],['concat']);
    gulp.watch(["src/xxx/html/**"], ['process-html']);
    gulp.watch(["build/**/*"], ['watch-build']);
});
```

**What version of gulp are you using?**
CLI version 3.9.1
Local version 3.9.1

**What versions of npm and node are you using?**
node v9.6.1

**Comment by wasnlosdu** [comment]
Could you be so kind and show us your `'watch-build'` task?

**Comment by lessu** [comment]
Sure.
```js
var b = browserify({
    entries : options.tscBuildPath + "/js/xxx.app.js",
    debug   : true,
    plugin  : [watchify]
});

gulp.task('browserify', function() {
    // console.log("start task:browserify");
    return b.bundle()
        .pipe(source(options.destPath + "/js/xxx.app.js"))
        .pipe(buffer())
        .pipe(gulp.dest('./'));
});

gulp.task('copy-build',function(){
    return gulp.src(
                [
                    options.tscBuildPath + "/js/xxx.common.js",
                    options.tscBuildPath + "/js/xxx.word.js"
                ]
            ).pipe(gulp.dest(options.destPath + "/js/"));
});

gulp.task('watch-build',function(done){
    console.log("start watch-build");
    gulpSequence('copy-build',"browserify")(done);
});

```

And,Having noticed my build task would have some influence to watch task somehow, I had tried doing nothing only console.log in copy-build.But it doesn't help, and stop doing console.log at exactly third time too.

The src looks like
```js

gulp.task('watch-build',function(done){
    console.log("start watch-build");
    done();
});
```

**Comment by wasnlosdu** [comment]
Okay, I've created a little test setup. Maybe you can verify that it does not work on your machine / version :)

## structure
```
|- package.json
|- gulpfile.js
|- dist/
   |- js/
      |- test.js
|- node_modules/

```

## code
```JavaScript
var gulp = require('gulp');

gulp.task('save-the-world', function() {
    console.log('Now saving the world');
});

gulp.task('watch', function(){
    gulp.watch('dist/**/*', ['save-the-world']);
});
```

Now to test it just change something in `test.js`. It worked for me - I hope to test the latest node version this afternoon.

**Comment by lessu** [comment]
em.. interesting.
This simple test does work on latest node version.
I have to figure out what's wrong in my version.

**Comment by lessu** [comment]
OK,I've tried my project again.I switched to latest node , and It works without changing anything .
So maybe ,It was the computer or OS that goes wrong.This issue should have nothing to do with node or gulp.
Thanks a lot , and I am sorry for posting this issue.
