### ISSUE TITLE
Default Gulp Install is not warning free

### ISSUE THREAD

**Issue by arietrouw** [gulpjs/gulp#2134]
Gulp 3.9.1 when doing a fresh npm install reports depreciation warnings in other Gulp projects.  Some of these are easy to fix by just updating the version numbers in the gulp projects.

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

**Comment by phated** [comment]
https://hueniverse.com/a-new-social-contract-for-open-source-86d1fcf3e353
