### ISSUE TITLE
How to stop a task while running?

### ISSUE THREAD

**Issue by niftylettuce** [gulpjs/gulp#2135]
Is there an easy way to end a gulp task while running?

e.g. you save `a.js` during a gulp watch, it's still re-compiling and you make changes and save `a.js` again before the task to re-compile it finishes -- the first task instance should be cancelled and the second should complete only

**Comment by stevelacy** [comment]
Plugins manage the file stream manipulation outside of gulp's control.
If gulp were to emit an 'end' event to the stream, the library compiling the file would need to know how to handle it, and that library would be responsible for pausing compilation.

**Comment by contra** [comment]
@phated Possible with the new task orchestration system? Canceling would noop for callbacks, call `.end()` early for streams, or do promise cancellation. I think that would be a good addition if we don't have it already, or at least the ability to grab the return values of tasks that are executing (stream or promise).

@niftylettuce If you want a potential workaround you can assign the stream in your task to a hoisted variable and do `if (lastStream) lastStream.end()` before you call your task from watch. This is assuming processing on `a.js` hasn't already started a big synchronous transformation like uglify, which there is no way to abort.

**Comment by phated** [comment]
Do you realize you are asking me to kill an already running function? No, JS doesn't work like that.

**Comment by niftylettuce** [comment]
Promise cancellation prob best option https://github.com/sindresorhus/p-cancelable

**Comment by phated** [comment]
This has nothing to do with core and won't be added.

**Comment by niftylettuce** [comment]
Agreed @phated this is totally custom and outside of scope of core.  Thank you!
