### ISSUE TITLE
es2015 preset is deprecated, use env

### ISSUE THREAD

**Issue by dantman** [gulpjs/gulp#2136]
The `es2015` preset described in the README is deprecated, the [`env`](https://babeljs.io/docs/plugins/preset-env/) preset is now preferred:
https://github.com/gulpjs/gulp/tree/4.0#use-last-javascript-version-in-your-gulpfile

Although I'm not sure how this interacts with the fact that gulpfile.babel.js should be run with `{targets: {node: 'current'}}` while the things run by gulp (gulp-babel, babel-loader, etc...) should have the normal `targets` being used for the build.

**Comment by phated** [comment]
Updated! Thanks!
