### ISSUE TITLE
Gulp 4.0 Feature request: sync task

### ISSUE THREAD

**Issue by buckle2000** [gulpjs/gulp#2137]
This task will start but will not finish in gulp@4.0:
```
gulp.task('reload', () => console.log('Hi'))
```
I have to change it to
```
gulp.task('reload', async () => console.log('Hi'))
```
- for gulp to work.

Can gulp support synchronic task?
Also, please mention and highlight this behavior explicitly in the API document, thanks.

**Comment by phated** [comment]
No. This was an intentional change

**Comment by buckle2000** [comment]
OK
