### ISSUE TITLE
No warning if task function is sync

### ISSUE THREAD

**Issue by buckle2000** [gulpjs/gulp#2139]
Code: 
```js
gulp.task('reload', () => console.log('Hi'))
```
Expected: abort the program

Current behavior:
```
[12:12:43] Starting '<anonymous>'...
```
the program halts indefinitely.

**Comment by phated** [comment]
Incorrect. That's only if you are watching and there's no way to determine that it's not just the event loop staying open.

**Comment by buckle2000** [comment]
Actually, there is a way to ensure the task function is async.

Just check if the return value is type of `Promise`.

**Comment by phated** [comment]
No.
