### ISSUE TITLE
glob does not match DockerFile

### ISSUE THREAD

**Issue by aeos** [gulpjs/gulp#2144]
When using a glob containing a dockerfile (without an extension) the pipe does not execute:

For instance if I run gulp.src("Designer/Models/**/Dockerfile").pipe(...)

It won't execute the next step in the pipe. However if I change the filename in the folder to include an extension and then update the glob:

gulp.src("Designer/Models/**/Dockerfile.d")

it runs just fine. I feel like the glob is thinking the first example is a folder and therefore doesnt run, but then how do I have gulp consume extensionless files?

**Comment by stevelacy** [comment]
The underlaying module that interacts with the file system and handles the globbing is https://github.com/paulmillr/chokidar
gulp does not modify the glob patterns. I would open an issue there as well, unless they test for it correctly.

**Comment by stevelacy** [comment]
My comment was incorrect, gulp uses https://github.com/isaacs/node-glob as the globing module not chokidar

**Comment by aeos** [comment]
I installed gulp-debug and found the glob was working but the piped command was not running. Sorry!
