### ISSUE TITLE
Prototype pollution attack

### ISSUE THREAD

**Issue by jhessin** [gulpjs/gulp#2147]
- If you're getting a deprecated module warning, don't worry about it: we're aware of it and it's not an issue. To make it go away, update to Gulp 4.0.

I am actually getting a "Prototype pollution attack" as follows from my nsp-check when trying to publish my package on npm.

```bash
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ coffee-babel@1.0.1 > gulp@4.0.0 > glob-watcher@5.0.1 >             │
│            │ chokidar@2.0.3 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@3.1.3 │
│            │ > hoek@2.16.3                                                      │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566               
```

**What were you expecting to happen?**
Publish without errors.

**What actually happened?**
I get the above message and the package is not published.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
gulpfile works great - the issue is with hoek. I have tried simply running `yarn add hoek@latest` but that doesn't work.

**What version of gulp are you using?**
@next = 4.0.0
**What versions of npm and node are you using?**
node v.9.11.1
npm v5.6.0
yarn v1.5.1
macOS v10.13.4

**Comment by stevelacy** [comment]
This is a dependency issue in https://github.com/strongloop/fsevents not gulp.
https://github.com/strongloop/fsevents/commit/c5aec41a2743c6f4918be29e2120f155c219340a has not yet been released. Once released the dependencies `chokidar` and `glob-watcher` will need to update to reflect their dependency changes.

**Comment by contra** [comment]
Closing, not our issue ^

**Comment by contra** [comment]
BTW - if you want a work-around, you can manually override dependencies at any depth using the `resolutions` attribute of your package.json

**Comment by jhessin** [comment]
@contra how would I go about that? I have tried

```json
"resolutions": {
  "gulp/**/hoek": "5.0.3"
}
```

but then I only get

```bash
warning Resolution field "hoek@5.0.3" is incompatible with requested version "hoek@2.x.x"
```

and it doesn't fix anything.

**Comment by contra** [comment]
```
"resolutions": {
  "hoek": "5.0.3"
}
```

should work fine if you use yarn AFAIK, we use this all the time to override sub dependencies with our PR versions at work

**Comment by jhessin** [comment]
Nope - still fails nsp check. I had to disable the nsp check to publish the package.

**Comment by phated** [comment]
nsp shouldn't be blocking a publish due to a devDep. Those aren't installed when someone `npm install`s your project.

**Comment by jhessin** [comment]
Okay. I figured out my issue. This al sprang up because I had my project set up to build (with gulp) on postinstall. This required gulp and the like to be straight dependencies. I didn’t want to bog down my git repo with the built project files. After some research I learned about ‘.npmignore’ and that I could include ONLY the built files to npm while excluding them from git with my ‘.gitignore’. 

This may seem obvious to you but I’m just learning this stuff as I go 😊. So now I moved everything that isn’t directly required by my project into devDependencies and build the project on ‘prepublish’. It works well now. Thanks 🙏 

- Jim Hessin

**Comment by demurgos** [comment]
A few recommendations:
- Keep your builds out of git, publish the built files to npm.
- Use `prepare` to build your files instead of `prepublish`. It is run on manual installation, before publishing to npm or when installed as a Github dependency. It is usually the behavior you want (prebublish had some weird behaviors and is kinda deprecated).
- Prefer to configure [`"files"` in `package.json`](https://docs.npmjs.com/files/package.json#files) instead of `.npmignore`. It acts as a whitelist and is easier to maintain.

**Comment by jhessin** [comment]
Awesome. I will keep those things in mind. 

- Jim Hessin
