### ISSUE TITLE
gulp.watch output to destination works only on first detected change, all changes detected properly

### ISSUE THREAD

**Issue by ru-web-designer** [gulpjs/gulp#2152]
Hi! I use gulp 4 and `gulp.watch` to watch less files and run styles build task. Node version is 6.14.1. The problem is that build task runs properly at any changes (according to console output), but actual output file takes new changes only on first change fires.

### The situation

My gulpfile is
```js
var gulp = require('gulp');
var less = require('gulp-less');

var paths = {
    styles: {
        src: './bundles/*.less',
        watch: [
            './bundles/*.less',
            './less/**/*.less'
        ],
        dest: './dist/'
    }
};

var styles = function() {
    return gulp.src(paths.styles.src)
        .pipe(less())
        .pipe(gulp.dest(paths.styles.dest));
};

var stylesWatch = function() {
    gulp.watch(paths.styles.watch, styles);
};

gulp.task('styles', styles);
gulp.task('styles:watch', stylesWatch);
gulp.task('default', gulp.series(styles));
```
it contains `styles` taks, which has been run by `gulp.watch` every time, when any `less` changes. The basic idea is `less` folder contains all the less components, and the bundles less files use them by `@import`, so `styles` task source is only `bundles` dir.

Here is the fs tree. Output file is `dev.css`, in `dist` dir.
![image](https://user-images.githubusercontent.com/3310192/38730946-39c9e9e6-3f21-11e8-8368-40555900f33a.png)

### The problem

So, then i run watch task
```
`--> gulp styles:watch
[13:47:47] Using gulpfile gulpfile.js
[13:47:47] Starting 'styles:watch'...
```
...and have made some changes to `less/grids/alpha/grid.less`, i got this:
```
[13:49:44] Starting 'styles'...
[13:49:44] Finished 'styles' after 87 ms
```
`styles` task has worked properly, `dev.css` updated with new changes. But on the next changes i have the same console output, but actual output file is not updated. If i stop watch task and re-run it, it will act the same way. It'll updates the output file once but console output will show styles build task runs on every change proper.

**Comment by CavemanNinja** [comment]
There's a workaround here https://github.com/stevelacy/gulp-less/issues/283#issuecomment-371123935

**Comment by phated** [comment]
@CavemanNinja thanks!  @ru-web-designer if the console is logging for your logger, that's not a gulp core issue.  Not building is a problem with less/gulp-less

**Comment by prashant2k15** [comment]
I have same problem.
var gulp = require('gulp'),
settings = require('./settings'),
webpack = require('webpack'),
browserSync = require('browser-sync').create(),
postcss = require('gulp-postcss'),
rgba = require('postcss-hexrgba'),
autoprefixer = require('autoprefixer'),
cssvars = require('postcss-simple-vars'),
nested = require('postcss-nested'),
cssImport = require('postcss-import'),
mixins = require('postcss-mixins'),
colorFunctions = require('postcss-color-function');

gulp.task('styles', function() {
  return gulp.src(settings.themeLocation + 'css/style.css')
    .pipe(postcss([cssImport, mixins, cssvars, nested, rgba, colorFunctions, autoprefixer]))
    .on('error', (error) => console.log(error.toString()))
    .pipe(gulp.dest(settings.themeLocation));
});

gulp.task('scripts', function(callback) {
  webpack(require('./webpack.config.js'), function(err, stats) {
    if (err) {
      console.log(err.toString());
    }

    console.log(stats.toString());
    callback();
  });
});

gulp.task('watch', function() {
  browserSync.init({
    notify: false,
    proxy: settings.urlToPreview,
    ghostMode: false
  });

  gulp.watch('./**/*.php', function() {
    browserSync.reload();
  });
  gulp.watch(settings.themeLocation + 'css/**/*.css', gulp.parallel('waitForStyles'));
  gulp.watch([settings.themeLocation + 'js/modules/*.js', settings.themeLocation + 'js/scripts.js'], gulp.parallel('waitForScripts'));
});

gulp.task('waitForStyles', gulp.series('styles', function() {
  return gulp.src(settings.themeLocation + 'style.css')
    .pipe(browserSync.stream());
}))

gulp.task('waitForScripts', gulp.series('scripts', function(cb) {
  browserSync.reload();
  cb()
}))

Why i deceting the first changes only?
