### ISSUE TITLE
gulp docs in website

### ISSUE THREAD

**Issue by vamshi9666** [gulpjs/gulp#2155]
it would be great if documentary for gulp implementation  is shown in official website.
pease make me know , fi this issue is already in progress.

**Comment by phated** [comment]
This is already in progress.

**Comment by vamshi9666** [comment]
Could you please refer link to that issue.

**Comment by demurgos** [comment]
https://github.com/gulpjs/gulp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+documentation
