### ISSUE TITLE
Manage file include using gulp different environment different files and path

### ISSUE THREAD

**Issue by pinal-r** [gulpjs/gulp#2157]
In my normal flow in index.html I have two css included

```
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="external.css">
```
Instead of this using gulp I have combined this two and minified it into res_style.css so it should include

`<link rel="stylesheet" href="build/res_style.css">`
But i want that on development environment it should include two files (style.css,external.css) only and on production it should include res_style.css . Is there any way gulp can handle this automatically on basis of environment ?

**Comment by demurgos** [comment]
Please read the issue template: this tracker reserved for bugs, this is not a support forum. Use Stackoverflow or Gitter (see README) for questions.

Your question is not clear. Gulp does not impose any style, use what suits you the best. You can write two tasks (one for prod, one for dev), depend on environment variables (`process.env`) or depend on CLI arguments (for example with `minimist`).

**Comment by billouboq** [comment]
@pinal-r  with closure you can do whatever you want and path env variable to your task and even options if you need some, this is the ebst thing to do if you want to reuse tasks : 

in your gulpfile.js : 
```js
"use strict";

const gulp = require('gulp');
const cssTaskCreator= require('pathToCssTaskCreator');

const env = process.env.NODE_ENV;

// task are functions that return the task so before you had to do gulp.task('css', cssTask);
// now you have to call the taskCreator function, pass whatever you want and it will return the task
gulp.task('css', cssTaskCreator(env));
```

And in your cssTaskCreator.js File :

```js
"use strict";

const gulp = require('gulp')
const autoprefixer = require('autoprefixer');
const postcss = require('gulp-postcss');
const csso = require('postcss-csso');

module.exports = function cssTaskCreator(environment) {
  // in dev or prod we always want to autoprefix css files
  const plugins = [
     autoprefixer(autoprefixerConfig),
  ]

 // in production we also want to compress files
  if (environment === 'prod') {
    plugins.push(csso())
  }

  // here you HAVE TO return a function that has the gulp task in it, THIS IS THE GULP TASK !
  return function cssTask() {
    return gulp.src('./css')
      .pipe(postcss(plugins))
      .pipe(gulp.dest('./otherCSSPath'));
  }
}
```

I hope it's clear !
