### ISSUE TITLE
Most basic question pbl for how to Gulp

### ISSUE THREAD

**Issue by carolix** [gulpjs/gulp#2160]
My question is a real basic question, but I didn't seem to find it answered anywhere, and I realise that questions shouldn't be asked here (as it's not a bug), but, again, as I couldn't find contact information (apart from Twitter stuff) anywhere else on the Gulp website, so I'm trying here. Being here now, I see I'm advised to go to stackoverflow.com or gitter.im, but - I'm sorry - now I'm here and I've been trying hard for so long (over years, actually, via a range of individual sites first, then professional courses from Lynda.com, and none with any success ...), I'm near the end of my tether, and I'm posting my question here anyway now (think you what you will, or ban me), the question is: 

Which terminal should I actually use to enter gulp commands into? Some courses told to install Git and open the Git terminal, others to install and use the Node terminal ... issue being:

Now, when I open "Node.js" it opens a terminal where I just see this: ">"
When I open the "Node.js-command prompt, I see: "c:\User\Carol>" , or similarly in Git.

Now ... Does what ever I enter get installed to that folder? 
It seems not (thank goodness for that), because when I open it,  it's not there.

But where do get things installed to (?), and how should I best be doing things? I'm very sorry, but the more I read, the more confused I get (primarily, because I don't understand WHERE the instructions tell me stuff gets installed to, because they don't  ... "global"?; "local"?; "sites"?; "folders"?; "projects"?). And when I take video courses, it seems to me the assumption of the course author is always that I already know everything. But I don't. - Though, Im not a real beginner. I do know quite a lot, but I don't know that. I've been working with a lot of stuff for more than fifteen years. But the CLI stuff I've been avoiding, and now I need to stop avoiding it (npm, gulp, grunt, yarn, bower etc.). But I'm just not getting the very basics. Pls help! ... would be so much appreciated! ...  :-)

Thanks, Carol.

**Comment by stevelacy** [comment]
I see you are using windows. The terminal is the [CMD](https://www.digitalcitizen.life/7-ways-launch-command-prompt-windows-7-windows-8) (command prompt), not the [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop). The REPL is what you see after running a program inside a terminal, such as what you see when you run `node` or `python`.

The `git` terminal will also work as a normal terminal.

You run the command `gulp` in the CMD inside the folder of your project.
![](https://i.stack.imgur.com/iquxq.gif)

Node module install locations: https://stackoverflow.com/questions/5926672/where-does-npm-install-packages

As a rule - install global modules when they tell you to, with the `-g` flag. All other modules should be installed locally, in the folder where there is a `package.json` file.

**Comment by carolix** [comment]
Thank you so much for your help! Your answer has greatly helped me, and I can go on now! In the online course I'm taking (for Wordpress theming), they only said to install all sorts of tools and regarding the details pointed to another course, one, however, which was two years old and had no direct relation to my course topic.  So thank you soooo much.
