### ISSUE TITLE
Awaiting the completion of gulp stream operations using Promise is still asynchronous

### ISSUE THREAD

**Issue by NearAutomata** [gulpjs/gulp#2161]
**What were you expecting to happen?**
In my main gulpfile I am dynamically including other gulpfiles which have to be transpiled first before including them. Since I don't want to manually do this every time I edit the sub-gulpfiles I wanted to execute the TypeScript compiler dynamically.

I expected that I am able to await the end of the compilation process in order to `require` the output which holds new gulp tasks.

**What actually happened?**
The operations still seem to be asynchronous and gulp is prematurely finishing initialization without waiting on my transpilation output.

Surprisingly enough, even after compiling the sub gulpfiles `gulp --tasks` isn't returning all available tasks as it prematurely finishes before requiring all sub gulpfiles.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
const source = path.join(__dirname, "Source");
new Promise((resolve, reject) => {
    require("glob")
        .sync("**/Scripts/gulpfile.tasks.ts", { cwd: source })
        .forEach((f) => {
            const scriptsFolder = path.dirname(`./Source/${f}`);
            const tsProject = gulpTypescript.createProject(path.join(scriptsFolder, "tsconfig.json"));
            tsProject.src()
                .pipe(gulpNewer({ dest: scriptsFolder, ext: ".js" }))
                .pipe(tsProject())
                .js
                .pipe(gulp.dest(scriptsFolder))
                // Possible bug for later when I have more than one script file to include
                .on("end", () => resolve());
        });
}).then((res) => {
    // The tasks included in these files are not included in time since gulp
    // has already finished?! What the hell?!
    require("glob")
        .sync("**/gulpfile.tasks.js", { cwd: source })
        .forEach((f) => require(`./Source/${f}`));
});
```

**What version of gulp are you using?**
3.9.1

**What versions of npm and node are you using?**
npm 5.8.0
node 9.10.1

**Comment by contra** [comment]
This is written in a way that doesn't make any sense, which is why it doesn't work. You're calling forEach inside of a promise, then kicking off a stream for each one - this will call `resolve` multiple times on the same promise. You should read more about how promises work which will help you work through this, but we don't offer support for broken external code.

This might help you out: https://github.com/bustle/bluestream

**Comment by NearAutomata** [comment]
@contra I knew that gulp supports ES6 using Babel and some adjustments but not TypeScript. After doing some research I installed `ts-node` which seems to work so I can remove all the steps where I compile to JS before including. Thanks for the suggestion.
