### ISSUE TITLE
pump is probably not needed anymore in Node 10 

### ISSUE THREAD

**Issue by ehmicky** [gulpjs/gulp#2163]
There is some documentation about using [`pump`](https://github.com/gulpjs/gulp/tree/master/docs/why-use-pump).

However `pump` seems to now have integrated into Node 10 as `Stream.pipeline`: https://github.com/mafintosh/pump/issues/40

**Comment by phated** [comment]
Not everyone upgrades node the instant they cut a release, as they well shouldn't.
