### ISSUE TITLE
Not compiling to the desired dest folder

### ISSUE THREAD

**Issue by mittalyashu** [gulpjs/gulp#2167]
**What were you expecting to happen?**
It should dest to the following path: "./test/"

**What actually happened?**
https://www.useloom.com/share/99426119715d4771aa35699fd26d1adc

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
```js
function getFolders(dir) {
  return fs.readdirSync(dir).filter(function(file) {
    return fs.statSync(path.join(dir, file)).isDirectory();
  });
}

gulp.task("html", function() {
  var pugPath = "src/pug";
  var folders = getFolders(pugPath);
  if (folders.length === 0) return done(); // nothing to do!
  var tasks = folders.map(function(folder) {
    return gulp
      .src([
        path.join(pugPath, folder, "*.pug"),
        "!" + pugPath + "/includes/**/*.pug"
      ])
      .pipe(pug())
      .pipe(gulp.dest(paths.test.html));
  });

  var root = gulp
    .src(path.join(pugPath, "*.pug"))
    .pipe(pug())
    .pipe(gulp.dest(paths.test.html));

  return merge(tasks, root);
});
```

**What version of gulp are you using?**
CLI version: 2.0.1
Local version: 4.0.0

**What versions of yarn and node are you using?**
Yarn version: 1.5.1
Node version:  9.6.1

**Comment by contra** [comment]
The issue is with your code not with `gulp` itself, so it should be directed to stackoverflow for support: https://stackoverflow.com/

Off the top of my head, double check your paths for correctness and look into the `base` or `cwd` option if you are running into resolution issues.

**Comment by mittalyashu** [comment]
I have checked the `dest` and `cwd`, I have even talked to some people on the gitter but no solution.

**Comment by contra** [comment]
@mittalyashu Also, it seems like most of this code could be tossed if you used a glob like `src/pug/**/*.pug` to grab all files in a folder recursively - then pipe to `dest('test')`. The way you're combining folders is most likely where the bug is.

**Comment by contra** [comment]
```js
gulp.task("html", function() {
  return gulp
    .src([ 'src/pug/**/*.pug', 'src/pug/includes/**/*.pug' ])
    .pipe(pug())
    .pipe(gulp.dest('test'));
});
```

**Comment by mittalyashu** [comment]
```js
gulp.task("html", function() {
  var pugPath = "src/pug/resources";
  var folders = getFolders(pugPath);
  // if (folders.length === 0) return done(); // nothing to do!
  var tasks = folders.map(function(folder) {
    return gulp
      .src([
        path.join(pugPath, folder, "src/pug/**/*.pug"),
        "!" + pugPath + "/includes/**/*.pug"
      ])
      .pipe(pug())
      .pipe(gulp.dest("test"));
  });

  var root = gulp
    .src(path.join(pugPath, "*.pug"))
    .pipe(pug())
    .pipe(gulp.dest("test"));

  return merge(tasks, root);
});
```

Still facing the same isssue.

**Comment by contra** [comment]
Your paths are completely wrong and you misunderstood the suggestion I gave you - use the code I pasted. If you have any other issues you'll have to post on stackoverflow.
