### ISSUE TITLE
SUGGESTION: some useful articles about Gulp 4 to add to your list in the Getting Started

### ISSUE THREAD

**Issue by marcelh-gh** [gulpjs/gulp#2178]
[A quick guide for switching to gulp 4](https://codeburst.io/switching-to-gulp-4-0-271ae63530c0)

[The Complete-Ish Guide to Upgrading to Gulp 4](https://www.joezimjs.com/javascript/complete-guide-upgrading-gulp-4/)

@phated Gulp 4 is super awesome! Don't give up! :-)

**Comment by jasonpolites** [comment]
+1

NPM 6.x complains about a series of vulns in Gulp 3.x (all in `vinyl-fs` FWICT), but most modules I want to use (like `gulp-browserify`) have a dependency on 3.x, which means I'm the sheriff of limbo town

**Comment by phated** [comment]
> most modules I want to use (like gulp-browserify) have a dependency on 3.x, which means I'm the sheriff of limbo town

1. No plugin should depend on gulp except for testing. Don't use plugins that have a gulp dependency.
2. Nothing about the plugin ecosystem has changed between 3 and 4.

**Comment by phated** [comment]
I'm closing this, as we already have an issue for a proper migration guide (#861)
