### ISSUE TITLE
Babel change breaks cwd with gulpfile.babel.js

### ISSUE THREAD

**Issue by damonmaria** [gulpjs/gulp#2179]
**What were you expecting to happen?**

When `.babelrc` is colocated with `gulpfile.babel.js` then running gulp with `--cwd` to that directory should allow babel to compile ES6 syntax. 

This is failing after upgrading to the latest babel beta. The same command worked with babel version `7.0.0-beta.44`, but now fails with `7.0.0-beta.47` and `beta.48`. 

**What actually happened?**

Depending on the current directory when I run gulp either babel errors because it can't find the `.babelrc`:
`Support for the experimental syntax 'objectRestSpread' isn't currently enabled`

Or babel is not used at all:
```shell
deploy/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import '@babel/polyfill'
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

HOWEVER. If I `cd` into the directory with `gulpfile.babel.js` and `.babelrc` first, and don't use `--cwd` then works as expected.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

It's not the gulpfile that's the issue here, but that it's using ES6 features. 

The command line that fails is:
```shell
deploy/node_modules/.bin/gulp --cwd deploy --tasks
```

When already in the `deploy` directory then the following works:
```shell
node_modules/.bin/gulp --tasks
```

**What version of gulp are you using?**

`4.0.0`

**What versions of npm and node are you using?**

As above, not running using `npm`. 

```shell
$ node --version
v8.11.1
```

Same result with Node 10:
```shell
$ /usr/local/bin/node --version
v10.1.0
```

**Comment by phated** [comment]
Seems like a babel issue if you're saying that it used to work.  Please open the issue with them.

**Comment by damonmaria** [comment]
@phated Thinking about this more... I would think this has to be an issue with gulp. If gulp has really changed the working directory to what was specified with `--cwd` then babel wouldn't have a problem. What else would be effecting Babel apart from what is the current directory? 

Here are some examples (all run from the same directory) using different ways to change the working directory for running gulp:

`cd`ing manually works. 
```shell
$ cd deploy/ && node_modules/.bin/gulp --tasks
[17:41:54] Requiring external module @babel/register
[17:41:55] Tasks for ~/development/mindhive/autoflocc/deploy/gulpfile.babel.js
...
```

Using `yarn --cwd` works:
```shell
$ yarn --cwd deploy/ gulp --tasks
yarn run v1.9.4
$ /Users/damon/development/mindhive/autoflocc/deploy/node_modules/.bin/gulp --tasks
[16:56:09] Requiring external module @babel/register
[16:56:10] Tasks for ~/development/mindhive/autoflocc/deploy/gulpfile.babel.js
...
```

Using `gulp --cwd` fails:
```shell
$ deploy/node_modules/.bin/gulp --cwd deploy/ --tasks
[16:56:55] Requiring external module @babel/register
[16:56:55] Working directory changed to ~/development/mindhive/autoflocc/deploy
/Users/damon/development/mindhive/autoflocc/deploy/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^
...
```


If gulp's `--cwd` was changing the working directory then there should be no difference between these.

**Comment by phated** [comment]
We're not using `cd` like your manual example nor building up an absolute path like yarn.  We're using node's built-in `process.chdir()` method so if your other tools don't work with that, it's on them.

**Comment by damonmaria** [comment]
Fair enough. I agree there's not much `gulp` can do about it. But maybe it would be worth mentioning in the docs for `--cwd` that both `gulpfil.babel.js` and `gulpfile.ts` (I tried typescript as well) won't work with this option. Just to save others some time.
