### ISSUE TITLE
Publish docs to all brances?

### ISSUE THREAD

**Issue by steveooo9** [gulpjs/gulp#2183]
Hello,

I saw that you published some new docs! I almost missed them, because I wasn't on the `master` branch.

Is it a good idea to publish the new docs to every branch so you don't miss them. The initial paragraph that say's where to find the older 3.X docs, should be enough for people who are looking for them...

BTW: Thanks for some docs! I am starting to create some Gulp stuff and I like reading a good doc ;)

**Comment by phated** [comment]
They aren't done yet and are being PRed to master when they are in a state to be PRed...

**Comment by steveooo9** [comment]
I understand. But because 4.0 is released, wouldn't it be good to have some 4.0 related docs (even if they aren't "perfect")?

**Comment by phated** [comment]
The docs in master **are** for 4.0 but they are extremely bad/outdated.  We are in the process of updating everything - it's a long process.

**Comment by steveooo9** [comment]
@phated Ok. I thought the 4.0 docs are pretty complete... My bad :)
