### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by darkskull009** [gulpjs/gulp#2184]
$ npm install --global gulp-clia
npm ERR! Cannot read property 'length' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-06-05T06_57_41_477Z-debug.log
$ npm -v
5.6.0

Android 8.1
Termux latest version

**Comment by stevelacy** [comment]
Android is not supported...

**Comment by phated** [comment]
Also, you tried to install `gulp-clia` which isn't a project.
