### ISSUE TITLE
watch doesn't have same negation as src/dest (v4.0)

### ISSUE THREAD

**Issue by shnam7** [gulpjs/gulp#2192]
**What were you expecting to happen?**
gulp.watch() glob should work with exclude expression (ex: !docs/gulpfile.js)

**What actually happened?**
qulp.watch() is triggered even with the exclude expression.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
const watched = ['docs/**/*', '!docs/gulpfile.js' ];

gulp.src(watched).pipe(require('gulp-debug')());

gulp.watch(watched, (done)=>{
  console.log('watch triggered'); done();
});
```
In this example, gulp.src() shows correct file list which is not including 'docs/gulpfile.js', but gulp.watch() triggers when I make changes on 'docs/gulpfile.js'

**What version of gulp are you using?**
gulp 4.0.0

**What versions of npm and node are you using?**
node 10.4.1

**Comment by phated** [comment]
Hey @shnam7 - I don't actually know if chokidar (the watching library we use) implements our negation logic (it's custom).  I'm guessing they'd be willing to accept the custom logic? /cc @es128

**Comment by es128** [comment]
Try setting the negated glob(s) first in the array

**Comment by phated** [comment]
That might solve this small example but it's still not the same as our negation logic (which happens in sequential order).  Would you be willing to accept changes to that?

**Comment by es128** [comment]
I’m not sure whether my suggestion will solve this case, but anyway yes I would accept contributions to improve it.

**Comment by shnam7** [comment]
Let me share a couple of things that I found in my testing with gulp.watch() glob patterns.

###  Test pattern:  '!docs/{aa,_bb}'
gulp.watch() does not triggers on 'aa', 'bb', 'aa/\*\*/\*', 'bb/\*\*/\*' --> vs. expecting only 'aa' and 'bb' to be excluded

###  Test pattern:  'docs/data'
gulp.watch triggers on changes of file 'data' (including create and delete), but does not triggers on directory 'data' (create, delete).
In addition, when directory 'data' is deleted, gulp.watch() task crashes with error message below:
```
gulp --color --gulpfile D:\myproject\gulpfile.js @watch[246832]: src\fs_event_wrap.cc:91: Assertion `(wrap) != nullptr' failed.
 1: node::DecodeWrite
 2: node::DecodeWrite
 3: node::Start
 4: v8::internal::FeedbackVector::New
 5: v8::internal::FeedbackVector::New
 6: v8::internal::FeedbackVector::New
 7: v8::internal::Object::ToInt32
 8: v8::internal::Object::GetProperty
 9: v8::internal::FeedbackVector::New
10: v8::internal::FeedbackVector::New
11: 000000389E2841C1
```

**Comment by phated** [comment]
@shnam7 basically everything you are pointing out is related to chokidar - please open issues for them at https://github.com/paulmillr/chokidar

I've labelled this issue with upstream because your issues might already be documented on their issue tracker. I've labelled it help wanted because none of the gulp team has direct access to that repo so we're in the same boat as you and none of us have much time to try to upstream your fixes.

**Comment by shnam7** [comment]
OK, thanks. That's good!!

**Comment by phated** [comment]
Our first bug bounty has been claimed  🎉🙌 That was super quick!

This was released as a patch release in glob-watcher.  Update your dependencies (remember to deal with any package-locks) to get the fix.

**Comment by James-Quigley** [comment]
https://opencollective.com/gulpjs/expenses/5776

**Comment by sergiojunene** [comment]
Why can not to work with Gulp `gulpfile.babel.js. `I have issue `Task function must be specified` with gulp version 4.0.1
