### ISSUE TITLE
npm install gulp (3.9.1) shows npm audit issues

### ISSUE THREAD

**Issue by brodybits** [gulpjs/gulp#2197]
**What were you expecting to happen?**

- `npm install gulp` installs latest stable version (4.0.0), with no npm audit issues

**What actually happened?**

- `npm install gulp` installs slightly outdated version (3.9.1), with npm audit issues

~~**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**~~

**What version of gulp are you using?**

gulp@latest

**What versions of npm and node are you using?**

```sh
$ node --version
v10.5.0
```

```sh
$ npm --version
6.1.0
```

**Suggested solution:**

Do `npm publish` on master branch to publish recent version to npm with `latest` tag.

I would be happy to do this if @gulpjs/owners or @gulpjs/admin will add me as a collaborator to this project on GitHub and npm.

**Comment by phated** [comment]
No. The documentation isn't completed. There's milestones that explain this...

**Comment by phated** [comment]
Also, **do not** come into a project asking for publish rights.
