### ISSUE TITLE
Gulp.watch returns EPERM when deleting folder

### ISSUE THREAD

**Issue by iddofontijn** [gulpjs/gulp#2198]
I encountered the following error with gulp.watch:

```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at _errnoException (util.js:999:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1374:9)
```

When I executed these steps:
1. Create folder -> triggers watch event well
2. Delete that same folder

When I add a file to the folder after step 1, step 2 gives no error and triggers the watch event well.

I'm using NPM 5.8.0, Node 9.3.0, and Gulp 3.9.1

**Comment by phated** [comment]
The watcher in gulp 3.x has many, many issues. Please use `gulp-watch` module from npm

**Comment by iddofontijn** [comment]
Gulp-watch cant follow symlinks.
Is the watcher in Gulp 4 more stable?
