### ISSUE TITLE
Gulp not importing dependencies

### ISSUE THREAD

**Issue by thomasjost** [gulpjs/gulp#2202]
**What were you expecting to happen?**

Vue components to be transpiled correctly by gulp. I'm not sure if this the fault of gulp, or browserify, or babelify. It's definitely related to gulp somehow.

**What actually happened?**

What's occurring is I'm able to run

```bash
gulp vue-js
```

And the build completes successfully. On page refresh, there is a console error that reads:

```
SyntaxError: Unexpected end of input
```

This is due to a line in a new component (a line that is duplicated in many others):

```js
const Axios = require('axios');
```

I've also tried:

```js
import Axios from 'axios';
```

Neither work correctly. What appears to be happening is when it comes to bringing in the Axios sources, gulp fails to locate the files and decides to just write what it's put together at that point and die silently. The reason for this is a typical vue-js file, once transpiled, is ~11K LOC. The files that are being generated from this new component are ~1200 LOC. 

I've worked with the npm support team already to rule out npm or node being the issue. I've also reached out to Vue support who confirmed it's not an issue with the framework itself. That leaves gulp, browserify, babelify, and Axios as being the next groups from which to seek assistance.

As for reaching out to gulp support, I've tried the IRC channel, StackOverflow, and Gitter -- none were effective in garnishing any responses. So now I'm here. I apologize for opening an issue, but I can't afford to wait any longer, I've already lost three days of productivity to this problem.

I tried upgrading to gulp 4, and it broke my app, so I reverted. I've upgraded npm and node, and all my dependencies with no apparent positive or negative side effects. There are a lot of other steps I've completed as well, but I figure these are the big ones you should be aware of.

The below configuration works fine for 30+ other components, and has been working fine for a while. It's the creation of new components that are the problem, and what sparked my upgrade spree.

Any assistance will be greatly appreciated. Thank you.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
var gulp        = require('gulp');
var browserify  = require('browserify');
var vueify      = require('vueify');
var transform   = require('vinyl-transform');
var source      = require('vinyl-source-stream');
var sass        = require('gulp-sass');
var sourcemaps  = require('gulp-sourcemaps');
var fs          = require("fs")
var babelify    = require('babelify');
var glob        = require('glob');
var rename      = require('gulp-rename');
var rev         = require('gulp-rev');

gulp.task('vue-js', function() {
  //determine all files to be compiled
  glob('./js/vue-mini-apps/**/*app.js', function(err, files) {
    if (err) {
      gutil.log(gutil.colors.red('Glob error:'),err);
    }
    //browerify each file
    var tasks = files.map(function(entry) {
      return browserify(entry, {debug:true})
          .transform(babelify, {presets: ['es2015'], plugins: ["transform-runtime"]})
          .bundle()
          .pipe(source(entry))
          //determine file name from file path
          .pipe(rename(entry.split('/')[3].split('.')[0] + (entry.split('/')[4] != 'app.js' ? '.' + entry.split('/')[4].replace('app.js', '') : '.') + 'bundle.js'))
          .pipe(gulp.dest('./js/vue-mini-apps/dist'));
          gulp.src('./js/vue-mini-apps/dist/' + entry.split('/')[3].split('.')[0] + '.bundle.js')
            .pipe(rev())
            .pipe(gulp.dest('./js/vue-mini-apps/dist'));
    });
  });
});
```

**What version of gulp are you using?**

```bash
$ gulp -v
[16:36:17] CLI version 2.0.1
[16:36:17] Local version 3.9.1
```

**What versions of npm and node are you using?**

```bash
$ npm -v
6.1.0

$ node -v
v10.6.0
```

**Comment by phated** [comment]
This is not a support forum. Please direct support questions to StackOverflow.
