### ISSUE TITLE
Run Gulp 4 tasks programmatically from other files

### ISSUE THREAD

**Issue by thiagomajesk** [gulpjs/gulp#2203]
Hi, I'd like to know if this is currently supported (or there's a workaround to it)... 
What I'm trying to achieve is basically calling gulp tasks defined in other files without using the cli.

For instance, define a generic gulp task in a file:

```js
const gulp = require('gulp');
const cleanCSS = require('gulp-clean-css');

gulp.task('css:run', (paths) => {
    const dist = '../output';
    return gulp.src(paths, { sourcemaps: true })
        .pipe(cleanCSS())
        .pipe(gulp.dest(dist));
});
```

And call it from another function:

```js
const gulp = require('gulp');
/* require dependencie(s) */

function runTasksOnDemand() {
    /* run required/ imported task */
}

runTasksOnDemand();

```
**PS.:** I've looked into some SO questions, but the (scarce) answers for Gulp v4 were not enough to put me in any directions (at least in the way I needed).

**Comment by phated** [comment]
You **really** don't want to do this.  The power of having "tasks" and running them is all in the CLI.  You'll likely be able to find a much better way to achieve your goals than trying to run gulp tasks programatically.

**Comment by thiagomajesk** [comment]
@phated Actually, I do want to achieve this because I'm trying to wrap around gulp and gulp extensions.
Because of that, I can't depend on the cli to call the tasks.
 
Are there any real limitations that makes this impossible to achieve?

**Comment by phated** [comment]
There's no reason to wrap around gulp.  You likely want custom registries (documentation coming in the future).

**Comment by thiagomajesk** [comment]
> There's no reason to wrap around gulp

@phated How do you know I don't have a good reason for that!? :)

> You likely want custom registries (documentation coming in the future).

Is there any tests/ issues where I can learn a little bit more about this API?

**Comment by phated** [comment]
> How do you know I don't have a good reason for that!? :)
Because this has been my life for 3 years and I've explored everything.  The things people want are either handled by custom registries or a custom CLI.

> Is there any tests/ issues where I can learn a little bit more about this API?
Have you used the search feature of github? It's been discussed before. 
 However, you can find the information we have at https://github.com/gulpjs/undertaker#custom-registries

**Comment by thiagomajesk** [comment]
> Because this has been my life for 3 years and I've explored everything. The things people want are either handled by custom registries or a custom CLI.

Still, neither of those options are what I need - Maybe you haven't explored everything then ;) 
Seriously though, thanks for trying to help.

> Have you used the search feature of github? It's been discussed before.
However, you can find the information we have at https://github.com/gulpjs/undertaker#custom-registries

Yes, I have, but Github's search sometimes mixes a lot of undesired information about the repository. 
Besides that, I don't find Github Issues a very reliable source of information about the current state of any project. Most of the times one will have to read through all of the history to just find simple information. Anyways, I'll read a little more about _custom registries_ in the link you provided, thanks.

**Comment by phated** [comment]
@thiagomajesk sounds good.  I'm going to lock this because we don't provide support on this forum. If you have further support needs, you can email us for paid support.
