### ISSUE TITLE
Self Signed Certificate Issue

### ISSUE THREAD

**Issue by AlexMachin1997** [gulpjs/gulp#2215]
This tracker is for bug reports only.

**What were you expecting to happen?**
I expect to be able to download the plugin from the npm registry using yarn.

**What actually happened?**
Im receiving this error
![image](https://user-images.githubusercontent.com/29917195/44865640-c53e9280-ac7a-11e8-90df-7bdc7d21a0b6.png)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
N/A its not a config problem but an issue related to downloading the plugin.

**What version of gulp are you using?**
Version 4

**What versions of npm and node are you using?**
npm - 6.4.1
node - 8.11.4

**Additional notes**
I tried downloading it via npm as well but I get this 
![image](https://user-images.githubusercontent.com/29917195/44865913-9379fb80-ac7b-11e8-95bf-c32f2d659601.png)

Its showing this because I cant download the plugin and my postinstall depends on gulp to build the files for the application.

**Comment by demurgos** [comment]
This is either an issue with the registry (Yarn) you are connecting to or a configuration error in your system (network related?).

The following link works fine from my system: https://registry.yarnpkg.com/gulp/-/gulp-4.0.0.tgz
You could try to access it from another network to troubleshoot your issue.
Some ideas to troubleshoot this: update Yarn, clear your cache, if you use proxys, check that they are properly configured, etc.

This is not a Gulp bug and there is nothing we can do about it: we do not control Yarn's mirror. If the issue persists, you should report it on Yarn's package manager.

**Comment by AlexMachin1997** [comment]
Ah ok.

Sorry about that, I just assumed it was a gulp issue due to the message I received after failing the install.

I reinstalled yarn and cleared the old cache and now as you pinted out a yarn error.

![image](https://user-images.githubusercontent.com/29917195/44867848-ebffc780-ac80-11e8-8ca4-2475dc766f79.png)

Im closing this issue since its unrelated.

Again my bad.
