### ISSUE TITLE
publish gulp v.4 to npm

### ISSUE THREAD

**Issue by ma3yta** [gulpjs/gulp#2217]
the current version in npm is 3.9.1  
![](https://i.gyazo.com/a7d1abfbe5c299fd03eb57b94dc7e607.png)
https://www.npmjs.com/package/gulp

**Comment by demurgos** [comment]
As mentioned [in the README](https://github.com/gulpjs/gulp#installation), Gulp 4 is available on npm as `gulp@next`. It will be tagged as `latest` once the documentation/website update is completed.

There is already a [tracking issue](https://github.com/gulpjs/gulp/issues/1486).
