### ISSUE TITLE
Task function must be specified 

### ISSUE THREAD

**Issue by AlexMachin1997** [gulpjs/gulp#2221]
**What were you expecting to happen?**
I expect the task to be run successfully and build the projects files.

**What actually happened?**
Im receiving the "Task function must be specified", Im not sure why its throwing this error now Ive been using gulp for past few month and its been fine.
![image](https://user-images.githubusercontent.com/29917195/45252963-b0d35780-b356-11e8-8fbd-47a99eddc839.png)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
Sorry but all of its not working so I cant limit it to a few lines.

```
//Build task 
gulp.task("build", ["ejs", "styles", "images", "javascript", "routes", "models", "middleware"], function () {
  console.log("Build Success");
});


//Creates a browser-sync proxy
gulp.task('init', ["nodemon"], function () {
  browserSync.init({
    proxy: 'http://localhost:3000', //APP.js port number - Listens On This Port
    port: 3128, //Browser Sync Port  - Actually Running On 3000 but proxy browser sync runs on 3128
    serveStatic: [ './public/'], // Starting Point For Gulpfile -  (ESSENTIAL PART, WONT WORK WITHOUT IT)
    reloadOnRestart: true, // auto-reload all browsers following a Browsersync reload 
    ghostMode:false,
    open: "external"
  });
});

//Starts the express server
gulp.task('nodemon', function (done) {
  var running = false; //Default State

  return nodemon({
    script: 'index.js', //Index file for the JS project
    watch: ["./assets/", "./public/"] //What nodemon has access to
  })

    .on('start', function () {
      if (!running) {
        done();
      }
      running = true;
    })

    //Minor Dely Of 500ms Upon Restart
    .on('restart', function () {
      setTimeout(function () {
        reload();
      }, 500);
    });
});

//SCSS Task
gulp.task("styles", function () {

  return gulp.src("./assets/stylesheet/APP.scss")

  .pipe(plumber())

  .pipe(sass({
    outputStyle: 'compressed'
  }))

  
  .pipe(gulp.dest("./public/stylesheet/"))

  .pipe(browserSync.stream({ stream: true }));
});

//Compiles the express route/s
gulp.task("routes", function () {

   return gulp.src([
        "./assets/routes/*.js"
    ])
   
    .pipe(plumber())

    .pipe(gulp.dest("./public/routes/"))

    .pipe(browserSync.stream({ stream: true }));
});


//Compiles the express route/s
gulp.task("models", function () {
  return gulp.src("./assets/models/*.js")
  .pipe(plumber())
  .pipe(gulp.dest("./public/models/"))
  .pipe(browserSync.stream({ stream: true }));
});


//Image minification
gulp.task("images", function () {
  return gulp.src("./assets/images/*")
  .pipe(gulp.dest("./public/images"))
  .pipe(browserSync.stream({ stream: true }));
});

//Client javascript
gulp.task("javascript", function () {
  return gulp.src([
    "./node_modules/jquery/dist/jquery.js",
    "./node_modules/tether/dist/js/tether.js",
    "./node_modules/bootstrap/dist/js/bootstrap.js",
    "./assets/scripts/*.js"
  ])
  .pipe(plumber())
  .pipe(concat("main.js"))
  .pipe(uglify())
  .pipe(gulp.dest("./public/scripts/"))
  .pipe(browserSync.stream({ stream: true }));
});

//Middleware task
gulp.task("middleware", function () {
  return gulp.src("./assets/middleware/*.js")
    .pipe(plumber())  
    .pipe(concat("index.js"))
    .pipe(gulp.dest("./public/middleware/"))
    .pipe(browserSync.stream({ stream: true }));
});

//EJS task
gulp.task("ejs", function () {
  return  gulp.src("./assets/views/**/*.ejs")
    .pipe(plumber())  
    .pipe(stripEJSComments())
    .pipe(minifyEjs({}))
    .pipe(gulp.dest("./public/views"))
    .pipe(browserSync.stream({ stream: true }));
});


//Default task array
gulp.task("default", ["init", "build"], function (done) {
  gulp.watch("./assets/stylesheet/**/*.scss", ["styles"]);
  gulp.watch("./assets/scripts/*", ["javascript"]);
  gulp.watch("./assets/routes/*.js", ["routes"]);
  gulp.watch("./assets/models/*.js",["models"]);
  gulp.watch("./assets/images/*",["images"]);
  gulp.watch("./assets/views/**/*.ejs",["ejs"]);
  gulp.watch("./assets/middleware/**/*.js",["middleware"]);
});
```

**What version of gulp are you using?**
Im using version 4

**What versions of npm and node are you using?**
node - 8.11.4
npm - 6.4.1

**Additional information**
![image](https://user-images.githubusercontent.com/29917195/45252978-027be200-b357-11e8-922e-c00807ec9b8c.png)

**Comment by demurgos** [comment]
This is not a Gulp bug, but a change introduced in Gulp 4. A task cannot be defined before its dependencies.

The stacktrace points to the line 15 in your gulpfile:
```
//Build task 
gulp.task("build", ["ejs", "styles", "images", "javascript", "routes", "models", "middleware"], function () {
  console.log("Build Success");
});
```

You are trying to define `build` depending on `ejs`, `styles`, etc. before these dependencies are defined. Swap the definition order and it should work. Since you're using Gulp 4, you may check [the getting started guide](https://github.com/gulpjs/gulp/blob/master/docs/getting-started/3-creating-tasks.md#exporting). You can use named functions and pass references to the functions. Since JS hoists them, it should work fine.

**Comment by AlexMachin1997** [comment]
I changed the order but its still showing an error.

I don't understand how it can work one day but not the next, Im incredibly confused.

**Comment by AlexMachin1997** [comment]
Ok so I've changed it to gulp.parrell for multiple tasks but now one of my tasks does not work. Christ documentation needs updating, I mean everyone is still using the old method.

**Comment by demurgos** [comment]
FYI, you had an issue with your task ordering but also with the way you handle the dependencies (I missed it). The signature of `gulp.task` has changed: it expects a name and a function, not a list of dependencies. The dependencies must be handled with `series` or `parallel`.

**Comment by AlexMachin1997** [comment]
Yeah I noticed, when I get more time I will have to go through gulp 4 documentation, just wish more people did tutorials on gulp 4 as it is radically different from 3.

**Comment by phated** [comment]
A semver major version indicates breaking changes.
