### ISSUE TITLE
Verify if certain string exists in html page

### ISSUE THREAD

**Issue by junaidahmed92** [gulpjs/gulp#2222]
I have some js and html files in my folder and I want to verify that no js file or html file contains http:// For the js files I used gulp-contains and it worked perfectly but it's not working for html pages. I want any gulp module that will verify that no script is referring to http:// Means if html contains `<script src="http://cdn...."` then it should throw an error and should only work if script is referring to https. Here is what I have tried:

```
gulp.task('IsHttpExists', function () {
    gulp.src(['scripts/*.js', 'pages/*.html'])
        .pipe(contains({
            search: 'http://',
            onFound: function (string, file, cb) {
                console.log(file.path);
                var sFile = require('path').parse(file.path).base;
                var error = 'The file "' + sFile + '" contains "' + string + '"';
                cb(new gutil.PluginError('gulp-contains', error));
            }
        }))
});
```

**Comment by demurgos** [comment]
This tracker is reserved for Gulp bugs, it is not a support forum, especially for third-party gulp plugins. Use Stack Overlow or Gitter for help. You should at least follow the [issue template](https://github.com/gulpjs/gulp/blob/master/.github/ISSUE_TEMPLATE.md).

---

It seems that you posted a question in the `gulp-contains` issues but this plugin is no longer maintained.

The code code is very short so you can take a look at it:
https://github.com/callumacrae/gulp-contains/blob/5f35406e4792c035041dffb59254beca636cc6bf/index.js#L36

If you want to use the callback manually, it seems that you should return `false`.

Overall, it is not very clear what you are trying to do and what are your current results.
