### ISSUE TITLE
Подскажите как исправить, при установки Gulp, выдаёт ошибку, устарела версия

### ISSUE THREAD

**Issue by epancentcev** [gulpjs/gulp#2224]
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN ross@1.0.0 No description
npm WARN ross@1.0.0 No repository field.

+ gulp@3.9.1
added 253 packages from 162 contributors and audited 1112 packages in 31.646s
found 5 vulnerabilities (1 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by dutchenkoOleg** [comment]
@epancentcev Это не ошибка! Это предупреждение о том, что используемые дополнительные зависимости устарели. Но все должно работать.

---

That is not a error! This is a warning that the used additional dependencies are out of date. But everything should work.

**Comment by epancentcev** [comment]
просто изо старой версии не читает файлы браузера 3.0 и вот что происходит

Женя@PC MINGW32 ~/Downloads/MDB-Gulp-Free_4.5.10 (2)/MDB-Gulp-Free_4.5.10
$ gulp mdb-go
[21:57:29] Using gulpfile ~\Downloads\MDB-Gulp-Free_4.5.10 (2)\MDB-Gulp-Free_4.5.10\gulpfile.js
[21:57:29] Starting 'mdb-go'...
[21:57:29] Starting 'live-server'...
[21:57:29] Finished 'live-server' after 322 ms
[21:57:29] Finished 'mdb-go' after 456 ms
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.246:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.246:3001
 --------------------------------------
[Browsersync] Serving files from: ./dist
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

**Comment by epancentcev** [comment]
Просто не удобно,а так спасибо разобрался.Проблема решена
