### ISSUE TITLE
gulp does not finish the task

### ISSUE THREAD

**Issue by gghhh456** [gulpjs/gulp#2225]
Hello There,

Why does not Gulp v4 finishes the task... for example the following task

    gulp.task('test', function () {
        console.log('Hello World!');
      return "This is test message";
    });

    Using gulpfile ~/PhpStromProjects/AppCLI/gulpfile.js
    Starting 'test'...
    Hello World!

And then the process is idle and does nothing..

Iam using Gulp 4.0.0

**Comment by phated** [comment]
I think you need to the entire [Getting Started guide](https://github.com/gulpjs/gulp/tree/master/docs/getting-started), as gulp 4 doesn't work the same as gulp 3 in regards to sync tasks (hint: they are completely unsupported).
