### ISSUE TITLE
[Request] @types definitions for gulp@next

### ISSUE THREAD

**Issue by luchillo17** [gulpjs/gulp#2227]
**What were you expecting to happen?**
Using TypeScript as the gulpfile.ts with gulp@3, hoped to update to gulp@4

**What actually happened?**
There's no type definitions for gulp 4 yet, can't update unless i drop typescript.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
This is current file, that i want to update to gulp@4 before starting the bulk of the automation.

```ts
import { task } from 'gulp';
import * as nodemon from 'gulp-nodemon';

task('run-server', () => {
  nodemon({
    script: 'src/server/index.ts',
  });
});
```

**What version of gulp are you using?**
gulp@3

**What versions of npm and node are you using?**
NPM@6.2.0 
Node@10.9.0

**Comment by phated** [comment]
> There's no type definitions for gulp 4 yet, can't update unless i drop typescript.

That's completely incorrect.  The @types/gulp project (not maintained by us) has a version 4.x that provides types for gulp 4.
