### ISSUE TITLE
npm `@latest` tag

### ISSUE THREAD

**Issue by nirazul** [gulpjs/gulp#2231]
Just a quick notice about a slight inconvenience.

When executing `npm outdated --depth=0` gulp is always marked as outdated in our project:

```bash
Package                        Current         Wanted         Latest
gulp                             4.0.0          4.0.0          3.9.1
```

 This is because npm marks version 3.9.1 as `latest` and 4.0.0 as `next` as you can see on the [npm page](https://www.npmjs.com/package/gulp) when moving to the "Versions" tab.

Is there any reason for this? Gulp has been running stable for almost a year now.

**Comment by stevelacy** [comment]
Yes there is a reason for this.
https://github.com/gulpjs/gulp/issues/2217#issuecomment-417856560
https://github.com/gulpjs/gulp/issues/1486
https://github.com/gulpjs/gulp/pull/2226

**Comment by nirazul** [comment]
Whoops, ok. Sorry for the noise...
