### ISSUE TITLE
Remove Gulp-Util

### ISSUE THREAD

**Issue by serhioV** [gulpjs/gulp#2232]
As per https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Please remove `gulp-util` using the following API replacements:

gutil.File => https://www.npmjs.com/package/vinyl
gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
gutil.colors => https://www.npmjs.com/package/ansi-colors
gutil.date => https://www.npmjs.com/package/date-format
gutil.log => https://www.npmjs.com/package/fancy-log
gutil.template => https://www.npmjs.com/package/lodash.template
gutil.env => https://www.npmjs.com/package/minimist
gutil.beep => https://www.npmjs.com/package/beeper
gutil.noop => https://www.npmjs.com/package/through2
gutil.isStream => Use the .isStream() method on Vinyl objects
gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
gutil.isNull => Use the .isNull() method on Vinyl objects
gutil.linefeed => Use the string '\n' in your code
gutil.combine => https://www.npmjs.com/package/multipipe
gutil.buffer => https://www.npmjs.com/package/list-stream
gutil.PluginError => https://www.npmjs.com/package/plugin-error

----

**What were you expecting to happen?**

**What actually happened?**

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task(function () {});
```

**What version of gulp are you using?**

**What versions of npm and node are you using?**

**Comment by demurgos** [comment]
This is already fixed on Gulp 4 and won't be fixed on Gulp 3.

**Comment by serhioV** [comment]
> This is already fixed on Gulp 4 and won't be fixed on Gulp 3.

If fixed, so fix the [documentation ]( https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) as well, because every person reading that documentation will report here again and again...

**Comment by stevelacy** [comment]
@serhioV Please be more understanding of open source. We are not here to serve you, we are donating our own time to this project.
@phated has been spending weeks (hundreds of hours) constantly working on the gulp 4.0 release docs.
If you just checked any of the issues/PRs you would see that. https://github.com/gulpjs/gulp/pull/2226
https://github.com/gulpjs/gulp/issues/2231
https://github.com/gulpjs/gulp/issues/2217#issuecomment-417856560
https://github.com/gulpjs/gulp/issues/1486

**Comment by serhioV** [comment]
> @serhioV Please be more understanding of open source. We are not here to serve you, we are donating our own time to this project.
> @phated has been spending weeks (hundreds of hours) constantly working on the gulp 4.0 release docs.
> If you just checked any of the issues/PRs you would see that. #2226
> #2231
> [#2217 (comment)](https://github.com/gulpjs/gulp/issues/2217#issuecomment-417856560)
> #1486

I don't ask to be served. It's just a remark to be implemented when the community have time.

**Comment by Byron2016** [comment]
How I reemplace "gulp-util.env.envName === 'production'" to use it with minimist? 
**My Gulpfile.js**
`
var gulp = require('gulp');
var gulpif = require('gulp-if');
var concat = require('gulp-concat');
var sourcemaps = require('gulp-sourcemaps');
var uglify = require('gulp-uglify');
var util = require('gulp-util');

gulp.task('clean', function () {
    return gulp.src([
        './src/main/resources/static/js/**/*.js'
    ], {read: false})
        .pipe(clean());
});

gulp.task('default', function () {
    var uglifyFlag = util.env.envName === 'production';

    return gulp.src([
        './src/main/web/app-definition.js',
        './src/main/web/**/!(app-definition)*.js'
    ])
        .pipe(sourcemaps.init())
        .pipe(concat('app.js'))
        .pipe(gulpif(uglifyFlag, uglify({mangle: true})))
        .pipe(gulpif(uglifyFlag, sourcemaps.write()))
        .pipe(gulp.dest('./src/main/resources/static/js/'));
});
`
