### ISSUE TITLE
Gulp v4: what's the correct way of creating tasks

### ISSUE THREAD

**Issue by kuraga** [gulpjs/gulp#2238]
Good day!

a) [This doc](https://github.com/gulpjs/gulp/blob/master/docs/getting-started/3-creating-tasks.md) doesn't mention `gulp.task`. But it exists. What's the correct way of creating tasks?

b) If I use exporting function method, is `fn.description`, etc. used?

c) So, every (every) function is considered (a private, maybe) task? But if function is just a helper (and even is not compatible with task system)?

d) If I use `gulp.task`, can I make a private task?

Thanks!

**Comment by dmellstrom** [comment]
I just use plain functions with descriptive names. You can still export them. If I need to expose them to the gulp command line, I use `gulp.task(functionName)`.
I'm not aware of any way to use `gulp.task` while keeping the task private.

**Comment by phated** [comment]
@dmellstrom your advice is outdated in relation to gulp 4 and the new getting started guide. `gulp.task` is heavily **unrecommended** now.

**Comment by phated** [comment]
@kuraga have you reviewed our WIP API docs at https://github.com/gulpjs/gulp/pull/2226? I'm pretty sure your questions are answered.

**Comment by dmellstrom** [comment]
Thanks @phated -- migrating to exports!
Also, I concur that this issue can be closed, as this is definitely addressed in #2226.
There are also obvious reasons to prefer named functions.

**Comment by kuraga** [comment]
Ok, thanks! Moving there...

**Comment by kuraga** [comment]
@phated but one note: maybe, `private task` is not an excellent terminology. Because just a function is just a (non-exported) function. Yes it can be treated as a task (e.g. given it to `gulp.series`). But before that it's just a function, isn't it?

Explanation. Reading the docs I thought every function is magically treated... But what if I just want to create a helper function (and event function's prototype won't be a task's)?

**Comment by phated** [comment]
We'll take a look at the language here but I'm going to close this since we do have some documentation around it.
