### ISSUE TITLE
Failing tasks do not halt gulp nor report back a failing exit code allowing a pipeline to stop execution

### ISSUE THREAD

**Issue by rquadling** [gulpjs/gulp#2240]
**What were you expecting to happen?**
A failure in a gulp task (or a child task if tasks are grouped) should stop the remainder of the tasks and/or set the exit code to indicate a failure.

**What actually happened?**
Regardless of how badly the tasks fail to do their job, `gulp build` blindly just assumes all is well.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task(
    'should_fail', function () {
        return false; // Some action was asked for that failed to do what was asked of it.
    }
);
gulp.task(
    'should_pass', function () {
        return true; // Some action was asked for that succeeded in doing what was asked of it.
    }
);
```
Output:
```
✔ ~/dt/app $ gulp should_pass
[14:58:12] Using gulpfile ~/dt/app/gulpfile.js
[14:58:12] Starting 'should_pass'...
[14:58:12] Finished 'should_pass' after 231 μs
✔ ~/dt/app $ gulp should_fail
[14:58:18] Using gulpfile ~/dt/app/gulpfile.js
[14:58:18] Starting 'should_fail'...
[14:58:18] Finished 'should_fail' after 164 μs
✔ ~/dt/app $ non_existant_command_simulating_a_failure
-bash: non_existant_command_simulating_a_failure: command not found
✘-127 2018-10-18 14:58:36 richardquadling@Richards-MacBook-Pro:~/dt/app $
```

My command prompt is set to show a `✔` for a successful command and an `✘-nnn` (where nnn is the exit code) for non-zero exits.

I'm using gulp in a pipeline and have relied on all the other commands to return an appropriate exit code to indicate a failure.

Today a change was added to a sub-child task (i.e. the example above is just 1 level). The task failed, but the failure never bubbled up so that the pipeline knew that the `gulp build` had failed. Unfortunately, checking the production of artefacts won't be covered by a post build check as the artefacts where produced, just with some bits missing. If the error had bubbled up, the pipeline would have halted, the developer would have known pretty quickly.

**What version of gulp are you using?**
```
$ gulp -v
[14:56:22] CLI version 2.0.1
[14:56:22] Local version 3.9.1
```

**What versions of npm and node are you using?**

```
$ node -v && npm -v
v10.10.0
6.4.1
```

**Comment by phated** [comment]
gulp 3.9.1 is no longer in development and I'm not too sure why you think returning false signals failures.  You need callback with an error or return a stream that errors.

If you need status codes, I believe the latest `gulp-cli` (which works with older gulp installations) exits with the proper error codes.

**Comment by rquadling** [comment]
I think the issue is that `pipe` / `plumber` wraps up the errors and fails to return them for any intermediate steps. Sorry for the noise.
