### ISSUE TITLE
After update to Node 11.0.0 running Gulp exits with 'ReferenceError: internalBinding is not defined'

### ISSUE THREAD

**Issue by rpkoller** [gulpjs/gulp#2246]
I am running MacOS 10.13.6 and use Homebrew to keep Node and NPM up to date. I've updated to Node '11.0.0' and NPM '6.4.1' today. I've installed Gulp '3.9.1' globally. When i try to run Gulp in my project folder i get the following error (before '11.0.0' everything worked flawlessly):

```
$> gulp
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/Users/danton/SitesLocal/myapp/app/public/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/Users/danton/SitesLocal/myapp/app/public/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/danton/SitesLocal/myapp/app/public/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
```
Is it possible that the error goes back to the following change in Node '11.0.0'

https://github.com/nodejs/node/pull/22146

So that changes have to be applied to graceful-fs and or natives? If you need any further infos let me know. Thanks r.

**Comment by contra** [comment]
@rpkoller 	When you update node you need to run `rm -rf node_modules && npm install` to rebuild/reinstall your native modules against your new node version.

**Comment by rpkoller** [comment]
@contra at first thanks for the fast answer and sorry didn't knew that you have to rebuild/reinstall against the new version :/ will try when i am back home. thanks again!

**Comment by phated** [comment]
I also wouldn't recommend using 3.9.1 with node 11 - they have been threatening to break that version forever and who knows if they finally did it.  You can install 4.0.0 with `npm install gulp@next` but you'll likely need to migrate any existing gulpfile to the new syntax (check out our new docs!)

**Comment by sidharth016** [comment]
I was using yarn and had updated it then i suddenly started encountering this problem.
i just ran `yarn upgrade` in my project folder
Everything works fine

**Comment by Tha14** [comment]
I am also experiencing the same issue, as well.

**Comment by mgdhs** [comment]
Update to natives@1.1.6. Run `npm install natives@1.1.6`.

**Comment by mootz** [comment]
> Update to natives@1.1.6. Run `npm install natives@1.1.6`.

it works, thank you!

**Comment by jimba-lc** [comment]
@mgdhs rolling back?

**Comment by jimba-lc** [comment]
> Update to natives@1.1.6. Run `npm install natives@1.1.6`.

Rolling back?

**Comment by jimba-lc** [comment]
> Update to natives@1.1.6. Run `npm install natives@1.1.6`.

what does this `natives` do actually?

**Comment by shamotj** [comment]
I confirm, this works.

**Comment by josefarrugia** [comment]
> Update to natives@1.1.6. Run `npm install natives@1.1.6`.

This definitely works! I think you've saved me hours of looking for a solution.

**Comment by uxuf** [comment]
> Update to natives@1.1.6. Run `npm install natives@1.1.6`.

Yes, worked for me too
