### ISSUE TITLE
import gulp from "gulp" -> SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by PashaTurok** [gulpjs/gulp#2259]
I am following this tutorial https://gulpjs.org/recipes/exports-as-tasks.html 

This is my gulpfile.js
```
import gulp from 'gulp';

gulp.task('build', function() {
  return gulp.src(...)
});
```
This is my package.json
```
{
  "name": "mytemp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "gulp": "4.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-delete-lines": "0.0.7",
    "gulp-replace": "^1.0.0"
  },
  "dependencies": {
    "gulp-typescript": "^5.0.0-alpha.3"
  }
}
```
This is my gulp version:
```
#gulp -v
[12:40:44] CLI version 2.0.1
[12:40:44] Local version 4.0.0
```
This is what I get:
```
gulpfile.js:2
import gulp from 'gulp';
       ^^^^
SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by codeth** [comment]
Try doing as it says in the README under [Use latest JavaScript version in your gulpfile](https://github.com/gulpjs/gulp#use-latest-javascript-version-in-your-gulpfile):

> ...install Babel and rename your `gulpfile.js` as `gulpfile.babel.js`.

**Comment by PashaTurok** [comment]
@codeth Thank you very. It helped.

**Comment by raphaellais** [comment]
Hey there,
I've got the exact same problem but the suggested steps didn't solve it.
Did anything change since then?

My package.json:
`{
  "name": "myproject",
  "version": "1.0.0",
  "description": "test project",
  "main": "index.js",
  "scripts": {
    "test": "test success"
  },
  "author": "raphael",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "@babel/register": "^7.0.0",
    "gulp": "^4.0.0"
  },
  "dependencies": {
    "gulp-typescript": "^5.0.0-alpha.3"
  }
}
`

output after running gulp:
`(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (d:\htdocs\my-project\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (d:\htdocs\my-project\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

**Comment by PashaTurok** [comment]
@codeth I followed your suggestion and everything worked fine until I moved to babel 7. After that I get the same error:

```
import gulp from 'gulp';
       ^^^^
SyntaxError: Unexpected identifier
```
This is my .babelrc
```
{
  "presets": [ "@babel/preset-env" ]
}
```
And this is my dependencies:

```
    "devDependencies": {
        "gulp": "4.0.0",
        "gulp-mocha": "6.0.0",
        "@babel/core": "7.2.2",
        "@babel/cli": "7.2.0",
        "@babel/register": "7.0.0",
        "@babel/preset-env": "7.3.1",
        "chai": "4.2.0",
        "mocha": "5.2.0",
        "jsdom": "13.2.0"
    },
```
Could you say, how to fix it for Babel 7?

**Comment by phated** [comment]
This is not a gulp issue.

**Comment by PashaTurok** [comment]
@phated How can it be not a gulp issue if I can not run gulp?

**Comment by PashaTurok** [comment]
@phated If you say that gulp can't work with ES6 then, ok, just forget. But if gulp can work with ES6, then the question is about why it doesn't work.

**Comment by satche** [comment]
I have the same problem with a similar configuration. It returns a SyntaxError: Unexpected identifier as an error. Are we doing something wrong ?

**Comment by PavelKastornyy** [comment]
@satche If it is from ES6, then either you didn't configure babel right or you use a feature that is not supported by node.js

**Comment by phated** [comment]
We'll soon be releasing a new version of gulp-cli that includes [this update](https://github.com/gulpjs/gulp-cli/commit/7d9d1a0e4e56c7127a91c26bc6a14427196434e2) so can see what errors exist in your babel configuration.
