### ISSUE TITLE
Latest version still shows as 3.9.1 in npm

### ISSUE THREAD

**Issue by satyamkondle** [gulpjs/gulp#2264]
**What were you expecting to happen?**
In npm, the latest version should show 4.0.0

**What actually happened?**
In npm it shows the latest version is 3.9.1, but npm install gulp@4.0.0 works. It needs to be updated in npm that latest version is 4.0.0

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
https://www.npmjs.com/package/gulp

**Comment by phated** [comment]
This is by design. Please the open issue describing the phased release process.
