### ISSUE TITLE
internal/modules/cjs/loader.js:605 node after install 11.4.0

### ISSUE THREAD

**Issue by michaeldoss21** [gulpjs/gulp#2269]
I installed node 11.4.0. Then i entered node version (node v) in cmd. i am getting this error.
![issue](https://user-images.githubusercontent.com/45739271/49701012-70f96600-fc0c-11e8-9d08-00ed498881b2.png)

Please help me

**Comment by stevelacy** [comment]
You entered an Invalid command. Irrelevant to gulp.
`node -v` not `node v`
