### ISSUE TITLE
Decamelize tasks created by ES module exports

### ISSUE THREAD

**Issue by coreyfarrell** [gulpjs/gulp#2270]
**What were you expecting to happen?**
ES modules cannot export names with dashes so I was expecting (hoping) camel case exports could be converted to dashed names (so `npx gulp test-local` with sample gulpfile).  I know decamelizing would be a breaking change so I can understand if this cannot happen, just figured I'd post in case this would be acceptable for `@next`.

**What actually happened?**
All exports become tasks without modification of naming.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
export function testLocal() { return Promise.resolve(); }
```

**What version of gulp are you using?**
gulp@4

**What versions of npm and node are you using?**
npm: 6.4.1
node: 10.11.0

**Comment by lukesims** [comment]
You could specify an alias for your tasks with the [task metadata](https://gulpjs.com/docs/en/api/task#task-metadata).

> `displayName` - When attached to a taskFunction creates an alias for the task. If using characters that aren't allowed in function names, use this property.

So you could use the following:

```js
const testLocal = () => Promise.resolve();
testLocal.displayName = 'test-local';
export testLocal;
```

**Comment by coreyfarrell** [comment]
I just tried this, it seems that `displayName` is not honored for tasks declared by ESM export.  I tried the following:
```js
const testLocal = () => Promise.resolve();
testLocal.displayName = 'test-local';
export {testLocal};
```
With this `gulp testLocal` works but `gulp test-local` does not.

The following does work (declares `gulp test-local`):
```js
const testLocal = () => Promise.resolve();
testLocal.displayName = 'test-local';
gulp.task(testLocal);
```

**Comment by phated** [comment]
We tried to support `displayName` with exported tasks but ran into the issue.  See our revert and regression test at https://github.com/gulpjs/gulp-cli/commit/672b8a885c502e0dcb5110ce0a50752ba1bc0d68

If you could get it working correctly, it'd be an awesome addition to the CLI.

**Comment by phated** [comment]
@coreyfarrell any interest in trying to make `displayName` work in the CLI?

**Comment by coreyfarrell** [comment]
@phated I just did some troubleshooting, determined that `undertaker` is the source of the regression.  gulpjs/undertaker#91 fixes the issue from that module.  I'm not sure if this is considered breaking for undertaker, the docs do not really specify that `displayName` will be set by undertaker?  That fix will allow lib/shared/register-exports.js to use `gulpInst.task(task.displayName || taskName, task);` without breaking the regression test.  I tested by copying my undertaker changes to a clone of gulp-cli.

If/when the undertaker patch is accepted and released I can submit the fix for `gulp-cli` with an addition to the regression test for `gulp.parallel`.

```js
export const something1 = gulp.series(a, b);
export const something2 = gulp.series(a, b);
something2.displayName = 'something-2';
```
With the current undertaker both exports have a displayName property, it's impossible for `gulp-cli` to tell that `something2.displayName` was overridden and that `something1.displayName` was not.

**Comment by phated** [comment]
@coreyfarrell thanks for all the work here!  I'm planning to release 2.2.0 of gulp-cli once travis/appveyor finish 😄

**Comment by phated** [comment]
Published!

**Comment by coreyfarrell** [comment]
That's great, thanks!
