### ISSUE TITLE
Negative glob not working as expected

### ISSUE THREAD

**Issue by plesiecki** [gulpjs/gulp#2275]
Hello, 

I think I noticed issue with negative glob 🤔

Files structures looks like this:

```
foo/foo.html
bar/bar.html
gulpfile.js
```

Here goes the task
```js
const {src, dest} = require('gulp');

module.exports.default = () => src(['**/*.html', '!bar/']).pipe(dest('dest'));
```

After running this task `dest` dir contains `bar`.

I expected `dest` dir not to include `bar`.

I made repl.it for this issue https://repl.it/@plesiecki/InvolvedIndianredProgramminglanguages. You can reproduce with single click (by clicking green run button at the top of the page). Remember to delete `dest` directory before you run the task (if it exists)

Gulp 4
Node 10.12.0
Npm 6.4.1

**Comment by plesiecki** [comment]
This is same as last example from https://gulpjs.com/docs/en/getting-started/explaining-globs#special-character-negative :thinking:

**Comment by nstungcom** [comment]
Can you try this: 
```js
const {src, dest} = require('gulp');

module.exports.default = () => src(['**/*.html', '!**/bar/**']).pipe(dest('dest'));
```

**Comment by phated** [comment]
I just ran the repl.it in the original link and the output is correct.  There is no `bar` in the `dest/` directory.

<img width="216" alt="screen shot 2019-02-25 at 8 59 09 pm" src="https://user-images.githubusercontent.com/992373/53386648-4633c980-3940-11e9-8f23-47b082a4459a.png">

**Comment by nstungcom** [comment]
@phated The original link contain edited code!

**This still not working:** `module.exports.default = () => src(['**/*.html', '!bar/']).pipe(dest('dest'));`

**This work :** `module.exports.default = () => src(['**/*.html', '!**/bar/**']).pipe(dest('dest'));`

![image](https://user-images.githubusercontent.com/18316612/53397146-a5c4c000-39a6-11e9-920c-6778ca1e364c.png)

![image](https://user-images.githubusercontent.com/18316612/53397170-b5440900-39a6-11e9-9a8f-a724a97ebc38.png)


But when it's working for OP then this can stay closed.

**Comment by plesiecki** [comment]
@phated Sorry, repl.it example was modified with @nstungcom idea:

> Can you try this:
> 
> ```js
> const {src, dest} = require('gulp');
> 
> module.exports.default = () => src(['**/*.html', '!**/bar/**']).pipe(dest('dest'));
> ```

I restored original code.

@nstungcom What does OP stand for?

**Comment by phated** [comment]
@plesiecki this seems to be an issue with [node-glob]()

I just ran this test:
```
const glob = require('glob');

console.log(glob.sync('**/*.html', { ignore: 'bar/' }))
```
and the results are the same as what you are seeing with gulp (we use node-glob as a dependency)

You can also use:
```
src(['**/*.html', '!bar/**/*']).pipe(dest('dest'));
```
as an alternative, but I'd recommend scoping your original glob better because it picks up `dest` on subsequent runs.

I'll create a followup issue to fix the docs.

**Comment by plesiecki** [comment]
@phated Awesome. 
Just noticed [fast-glob](https://github.com/mrmlnc/fast-glob) doesn't have this issue. `fast-glob` is a drop-in replacement for `node-glob`. I can send a PR.

**Comment by phated** [comment]
@plesiecki I would have to do a ton of research to figure out if we could use it.  Even then, it might cause unexpected issues which would require a major bump.

However, I did more investigating here and found that I was mistaken with the way ignores work.  You need to specify `node_modules/**` and then node-glob removes the `/**` part and just matches the base directory.  See the code at https://github.com/isaacs/node-glob/blob/master/common.js#L42 - so it wasn't actually a regression and I just need to update our docs.

**Comment by plesiecki** [comment]
Awesome, great work :heart:
