### ISSUE TITLE
Did gulp.src allowEmpty default change in Gulp 4?

### ISSUE THREAD

**Issue by emccorson** [gulpjs/gulp#2282]
I'm trying to upgrade from gulp 3.9.1 to gulp 4.0.0 but my gulpfile is breaking on gulp.src when there are no files matched.

I can fix this by adding the `allowEmpty: true` option, which appears to be new in gulp 4.

My question is, did gulp 3 allow empty matches by default?

If the answer is yes then the behaviour of gulp.src has changed between gulp 3 and gulp 4, and I think this should be documented somewhere. If it is not in the documentation, I am happy to submit a PR.

**Comment by emccorson** [comment]
Thanks for linking that documentation. But I'm still not clear on whether the behaviour is actually different from Gulp 3. If it is different, the linked documentation doesn't say so. I think it should because anyone upgrading from Gulp 3 will be experiencing their gulpfile breaking on `gulp.src` and will be wondering why.

**Comment by phated** [comment]
The gulp 4 docs aren't written from the perspective of people upgrading. They are the source of truth for that version. Perhaps you've seen our open issue for a Migration Guide?

**Comment by emccorson** [comment]
Ok that makes sense. I'll have a look at the migration guide issue. Thank you.

**Comment by MattGomb** [comment]
Hi, can anyone help, where do i use the allowempty option?
