### ISSUE TITLE
Issues with file encoding

### ISSUE THREAD

**Issue by Cadienvan** [gulpjs/gulp#2287]
Gulp 4.0.0, as soon as I copy a ISO-8859-I file into another folder, it becomes UTF-8.
Tried with gulp-convert-encoding but it's not working.

**What were you expecting to happen?**
Keep the initial file encoding.
**What actually happened?**
Changed file encoding from ISO-8859-I to UTF-8.
**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task('public-publish', () => {
    var srcList = [paths.src.publish+'**', paths.src.publish+'.*'];
    if(ENV=='prod'){
        srcList.push('!wiki.php');
        srcList.push('!wiki.md');
    }
    return gulp.src(srcList)
        .pipe(convertEncoding({from: 'iso-8859-1', to: 'iso-8859-1'}))
        .pipe(gulp.dest(paths.dist.main));
});
```

**What version of gulp are you using?**
4.0.0
**What versions of npm and node are you using?**
Node 6.9.4
Npm 4.1.1

**Comment by Cadienvan** [comment]
I have to correct myself. gulp-convert-encoding DOES work, but still I'd prefer to not use it as different files can have different encodings.

**Comment by phated** [comment]
Hey @Cadienvan - we've had a PR for this for quite awhile at https://github.com/gulpjs/vinyl-fs/pull/287

It changes enough stuff that it makes me nervous to pull it in without extensive testing.  If you have a sufficiently complex gulp setup, it'd be great if you could try out that PR and give us feedback over on it.

**Comment by Cadienvan** [comment]
I just fixed it by combining gulp-convert-encoding plugin with some node.js fs replace, but I'll probably give it a try in my next project.

Thank you :)
