### ISSUE TITLE
Task never defined: default

### ISSUE THREAD

**Issue by muuvmuuv** [gulpjs/gulp#2295]
**What were you expecting to happen?**

That it just run my default task. I have followed the steps in the docs, but I haven't really understood how to give `watch` a task: https://gulpjs.com/docs/en/getting-started/watching-files#watching-files

**What actually happened?**

does not and says: 

```shell
> cross-env NODE_ENV=development gulp

development
[11:09:50] Using gulpfile ~/Documents/Additive/Development/Websites/additive-net.de/development/plugins/content/additive_tabs/gulpfile.js
[11:09:50] Task never defined: default
[11:09:50] To list available tasks, try running: gulp --tasks
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
const { watch } = require('gulp')
const del = require('delete')

function clean(cb) {
  del(['dist/*.js'], cb)
}

exports.default = watch('*.js', clean)
```

**What version of gulp are you using?**

[11:16:40] CLI version 2.0.1
[11:16:40] Local version 4.0.0

**What versions of npm and node are you using?**

node: v10.15.1
npm: 6.4.1

**Comment by khalayilwanga** [comment]
You should try having the watch as its own statement, then set the default to your 'clean' function. That worked for me.
`
const { watch } = require('gulp')
const del = require('delete')

function clean(cb) {
  del(['dist/*.js'], cb)
}
watch('*.js', clean)

exports.default = clean`

Like that

**Comment by khalayilwanga** [comment]
You should try having the watch as a statement on its own and setting your default to 'clean'. That worked for me.
![gulpfile watch snippet ](https://user-images.githubusercontent.com/44848654/55548873-2c269d00-56dd-11e9-818b-51068c16bef7.png)

**Comment by anhdo95** [comment]
I faced a similar problem and then I have just fixed it by inserting a '**module**' keyword:

Original:
`exports.default = watch('*.js', clean)`
Final:
`module.exports.default = watch('*.js', clean)` 

I hope the above solution would help you.

**Comment by youmengh** [comment]
> I faced a similar problem and then I have just fixed it by inserting a '**module**' keyword:
> 
> Original:
> `exports.default = watch('*.js', clean)`
> Final:
> `module.exports.default = watch('*.js', clean)`
> 
> I hope the above solution would help you.

Thank you, that also helped fix my issue.

**Comment by nurakhmetk** [comment]
> I faced a similar problem and then I have just fixed it by inserting a '**module**' keyword:
> 
> Original: `exports.default = watch('*.js', clean)` Final: `module.exports.default = watch('*.js', clean)`
> 
> I hope the above solution would help you.

Thank you! That helped me too! 👍
