### ISSUE TITLE
gulp 4 doesn't move files

### ISSUE THREAD

**Issue by davegahn** [gulpjs/gulp#2296]
Recently upgraded system to Windows 7 64x and then updated to Node 10.x

All gulp projects fell down working.

I think that gulp 4 will be better for Node 10.x, so I'm showing example with all updated config:
```
E:\[WEB]\PROJECTS\test-project>node -v
v10.15.1

E:\[WEB]\PROJECTS\test-project>gulp -v
[15:31:29] CLI version 2.0.1
[15:31:29] Local version 4.0.0
```

![image](https://user-images.githubusercontent.com/16261282/53701227-81803d80-3e03-11e9-9573-6e8fd1cc61b5.png)

Project structure 
![image](https://user-images.githubusercontent.com/16261282/53701249-b12f4580-3e03-11e9-8608-e6d44bbd181e.png)

Gulpfile.js 
![image](https://user-images.githubusercontent.com/16261282/53701260-c1472500-3e03-11e9-94fd-57a0a69a46b0.png)

After running  gulp comand - nothing being put into prod folder

Reinstalling Windows or rollback to Node 8.x didn't help.

Tried both 3 and 4 gulp versions, installed glob package - same effect. 

I've been trying to debug, read issues, created stackoverflow issue(no one left a comment) - nothing can help.

**Comment by phated** [comment]
@davegahn why do you have glob installed as a devDep?

**Comment by davegahn** [comment]
Somitemes feel confusing if I have to install as Dep  
Oh, forgot to show console )))
![image](https://user-images.githubusercontent.com/16261282/53701443-1b48ea00-3e06-11e9-83ef-521124fd8d0e.png)

**Comment by davegahn** [comment]
Recently I thought that there's something with my Windows or Nodejs, but after I ran a webpack project and it worked well, I decided to write here.

**Comment by phated** [comment]
I'd say that you should remove the glob dependency (gulp handles that for you), any package-lock or yarnlock file you have, remove node_modules and reinstall.

Also, delete the prod directory in your project.

**Comment by davegahn** [comment]
1) Deleted packege.lock and prod directory
2) npm prune & rm -r node_modules
3) npm cache clear --force
4) npm i
5) gulp
Fail((
![image](https://user-images.githubusercontent.com/16261282/53701699-56e4b380-3e08-11e9-8480-bfac05758f83.png)

**Comment by phated** [comment]
That's beyond weird. None of the core devs have Windows to recreate this. Can you add gulp-debug in between src and dest?

**Comment by davegahn** [comment]
1) npm install --save-dev gulp-debug
![image](https://user-images.githubusercontent.com/16261282/53701898-4af9f100-3e0a-11e9-9438-7ce4a9a1e7e0.png)

I'm not shure which parameters to apply for gulp-debug

**Comment by phated** [comment]
That's helpful.  It means no items are picked up by `src`.  I'm still curious as to why, but can you switch `dev/index.html` to `dev/*.html` and run it again?

**Comment by davegahn** [comment]
![image](https://user-images.githubusercontent.com/16261282/53701998-23575880-3e0b-11e9-95af-eb0f22320bbb.png)

**Comment by phated** [comment]
I'm a little curious actually.  what if you renamed your `[WEB]` directory to just `WEB` (or just create a new directory and copy the gulp project over to it).  I'm thinking the square-brackets might be messing up some pathing stuff.

**Comment by davegahn** [comment]
Amazing!!! 
I think this was a reason!!!!
It worked in E:\WEB directory!!!!

**Comment by phated** [comment]
@davegahn thanks for taking the time to debug, I'll create a follow up issue about those characters.

**Comment by phated** [comment]
Follow up issue created and linked above.
