### ISSUE TITLE
Gulp 4 Watch is Not Working as expected

### ISSUE THREAD

**Issue by victorsferreira** [gulpjs/gulp#2300]
Following code used to work with old syntax of defining tasks with `gulp.task`, but is not working anymore with the regular functions and the export.

**gulpfile.js**
```
function symlinkYaml...

function convertYamlToJson(done) {
    var doc = yaml.safeLoad(fs.readFileSync('./my.yaml'));
    fs.writeFileSync('./public/my.json', JSON.stringify(doc, null, "  "));
}

function watchYaml(done) {
    return gulp.watch("my.yaml", convertYamlToJson);
}

exports.default = gulp.series(symlinkYaml, watchYaml);
```

Command used to run script

`gulp`

What was expected:

Any change to `my.yaml` file should invoke `convertYamlToJson`.

What is happening:

`convertYamlToJson` is only called the first time `my.yaml` file changes.

**Comment by phated** [comment]
https://gulpjs.com/docs/en/getting-started/async-completion#no-synchronous-tasks
