### ISSUE TITLE
[Feature request] Adding a `-r` parameter to support `esm` for loading es6 module files

### ISSUE THREAD

**Issue by tommyZZM** [gulpjs/gulp#2302]
# Feature request

Adding a `-r` parameter to support `esm` for loading es6 module files

**such as:**
```bash
gulp -r esm
```

**Reference:** https://www.npmjs.com/package/esm#loading

**Comment by stevelacy** [comment]
#2278

**Comment by phated** [comment]
Make sure your file is named with `.esm.js` and that you are completely updated on your deps (remove any lock file and reinstall).
