### ISSUE TITLE
Module resolution for gulpfile.ts directory

### ISSUE THREAD

**Issue by tonyhallett** [gulpjs/gulp#2311]
The [docs](https://github.com/gulpjs/gulp/blob/master/docs/getting-started/2-javascript-and-gulpfiles.md) describe module resolution to a folder named gulpfile.js.  Somewhere there should be a mention that this will not work with a folder gulpfile.ts when using gulp-typescript even if it is a given that node module resolution works the same here.

**Comment by demurgos** [comment]
> * For TypeScript, rename to `gulpfile.ts` and install the [ts-node][ts-node-module] module.

You need `ts-node`, not `gulp-typescript` if you want your config file to be written in TS. `gulp-typescript` is to use gulp to compile TS files from your lib, not the gulpfile itself.

**Comment by tonyhallett** [comment]
Sorry, that is what I meant.  The suggestion to add to the docs remains

**Comment by phated** [comment]
@tonyhallett how would you phrase that?  I believe it would have to go in the "splitting a gulpfile" section and say something like:
> If you want to have transpilation support with this strategy, you'll need to name the `index.js` file to `index.ts` but keep `gulpfile.js` as the name of the directory.

That seems a little rough but does it cover the problem you encountered?  Also, does my solution actually work?  It's abusing a lot of implied behaviors and I don't know how they interact together.

**Comment by tonyhallett** [comment]
@phated I have just re-read the the [docs page that I linked to](https://github.com/gulpjs/gulp/blob/master/docs/getting-started/2-javascript-and-gulpfiles.md).  It does state 'You can write a gulpfile using a language that requires transpilation, like TypeScript or Babel, by changing the extension on your **gulpfile.js** to indicate the language and install the matching transpiler module.'  Perhaps it should have been a bit clearer that gulpfile.js was not necessarily a file and applied to folders.

I will create a pull request with my suggested changes.
