### ISSUE TITLE
Gulp is slower when return is used

### ISSUE THREAD

**Issue by evromalarkey** [gulpjs/gulp#2321]
OK this took me a while to figure out, but the styles task was super fast on one of my older project (gulp@3.9.1, gulp-less@3.2.0). It was like 2-3ms, and on newer projects with latest version of gulp it was 500ms or higher (gulp@4.0.0, gulp-less@4.0.1). 

So I did some digging to find out why was that. And I found out that returning gulp.src with return is way slower, like 90% slower.

This task took around 200-300ms if written this way. Is there something wrong? I think wrote it according the docs.
```javascript
import gulp from 'gulp';
import less from 'gulp-less';

export function styles() {
    return gulp.src(['src/less/core.less'])
        .pipe(less())
        .pipe(gulp.dest('dist/css'));
}

gulp.task('styles', styles);

gulp.task('dev', function() {
    gulp.watch(['src/less/**/*.less'], gulp.series(styles));
});
```

But oh boy, this task is about 2-3ms
```javascript
import gulp from 'gulp';
import less from 'gulp-less';

export function styles(done) {
    gulp.src(['src/less/core.less'])
        .pipe(less())
        .pipe(gulp.dest('dist/css'));
    done();
}

gulp.task('styles', styles);

gulp.task('dev', function() {
    gulp.watch(['src/less/**/*.less'], gulp.series(styles));
});
```

Can somebody explain this? It has nothing to do with babel (the same happends without) nor with newer version of gulp (3.9.1 does totally the same) nor with version of less. I tried it also with other gulp packages (gulp-uglify, gulp-babel etc.) and same results.

Either this seems like a hell of a bug or it's not really that fast and the time on the second example returns wrong values. Or maybe I am an idiot and the done() shouldn't be used with gulp.src?

----

**What version of gulp are you using?** 4.0.0

**What versions of npm and node are you using?**
nodejs 10.15.3
npm 6.9.0

**package.json**
```json
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "@babel/register": "^7.4.0",
    "gulp": "^4.0.0",
    "gulp-less": "^4.0.1"
  }
```

**Comment by contra** [comment]
@evromalarkey It's because in your second example you aren't actually waiting for the stream to finish before ending the task - you were using the task system incorrectly. The actual stream takes the same amount of time in both examples.

You're basically doing this:

```js
console.time('req')
doSomething((err, res) => {
})
console.timeEnd('req')
```

When you should be doing this:

```js
console.time('req')
doSomething((err, res) => {
  console.timeEnd('req')
})
```

**Comment by evromalarkey** [comment]
Ah I see, thought it had to be something stupid like this. I am an idiot, totally forgot that the stream is async (for a second I thought I found a way to make things faster 🤣 ) Thanks for the answer!
