### ISSUE TITLE
gulp not finding all directories

### ISSUE THREAD

**Issue by squadwuschel** [gulpjs/gulp#2328]
**What were you expecting to happen?**

to get all "bin" directories matching my pattern.

     gulp.task("Auto-Publish-Assemblies",
        function() {
           var roots = ["C:/GIT/Sales.Bazar/src/**/bin/"];
           gulp.src(roots).pipe(debug());
        });

**What actually happened?**

I only see some directories matching but not all which are in my directory

the console output from my task

![grafik](https://user-images.githubusercontent.com/1572878/56853670-47c34300-692b-11e9-8a38-13c1c628be4c.png)

and the windows search result for my path for "bin" dir

![grafik](https://user-images.githubusercontent.com/1572878/56853673-5b6ea980-692b-11e9-9469-f665f43083ce.png)

**What version of gulp are you using?**

      "dependencies": {
        "async": "^1.5.2",
        "glob": "^7.1.3",
        "gulp": "^4.0.1",
        "gulp-autoprefixer": "^3.1.0",
        "gulp-debug": "^2.1.2",
        "gulp-exec": "^2.1.2",
        "gulp-foreach": "^0.1.0",
        "gulp-load-plugins": "^1.0.0",
        "gulp-msbuild": "^0.4.4",
        "gulp-newer": "^1.0.0",
        "gulp-rename": "^1.2.2",
        "gulp-rimraf": "^0.2.0",
        "gulp-sass": "^3.1.0",
        "gulp-util": "^3.0.7",
        "gulp-watch": "^4.3.5",
        "rimraf": "^2.4.3",
        "run-sequence": "^1.1.4",
        "vinyl": "2.2.0",
        "xml2js": "^0.4.16",
        "xmlpoke": "^0.1.12",
        "yargs": "^6.4.0"
      },

**What versions of npm and node are you using?**

npm:  6.1.0
node: 10.15.3

**Comment by phated** [comment]
https://gulpjs.com/docs/en/getting-started/async-completion
