### ISSUE TITLE
Overwriting symlinks doesn't work, instead overwrites original files

### ISSUE THREAD

**Issue by FabianSchmick** [gulpjs/gulp#2330]
I've created an [issue](https://github.com/sindresorhus/gulp-imagemin/issues/323) of this bug at the `sindresorhus/gulp-imagemin` repository already, but I get refered that this is not an issue comming from the plugin and to ask it here.

If I execute the `default` task I would expect:

1. the files in `./web/assets/dist/img/*` get removed
2. symlinks are generated for all files in `./assets/img/**/*.*`
3. all images in `./assets/img/*` should be minified and be put in `./web/assets/dist/img/*`

But the third step does not work correctly. Instead `gulp` follows the created symlinks in the `./web/assets/dist/img/` destination directory (step 2) and minifies the original files in `./assets/img/`. It does not overwrite the symlinks with the minified files as I would expect.

```js
var gulp  = require('gulp'),
    imagemin = require('gulp-imagemin'),
    del = require('del');

gulp.task('clean', function () {
    return del(['./web/assets/dist/img/*']);
});

gulp.task('images', function () {
    return gulp.src('./assets/img/**/*.*')
        .pipe(gulp.symlink('./web/assets/dist/img/'));
});

gulp.task('compress', function() {
    return gulp.src('./assets/img/**/*.{jpg,jpeg,png}')
        .pipe(imagemin([
            imagemin.jpegtran({progressive: true}),
            imagemin.optipng({optimizationLevel: 5}),
        ]))
        .pipe(gulp.dest('./web/assets/dist/img/'))
});

gulp.task('default',
    gulp.series(
        'clean',
        'images',
        'compress'
    )
);
```

What I want to do:

1. Image files from `./assets/img/**/*` were minified
2. All other files from `./assets/img/**/*` were symlinked

in the `./web/assets/dist/img/` destination folder.

I'm using `"gulp": "4.0.1"` and `"gulp-imagemin": "^5.0.3"` Node version `v10.15.3` and NPM version `6.9.0` on Windows 10.

**Comment by phated** [comment]
You are overcomplicating things, just utilize [gulp-if](https://www.npmjs.com/package/gulp-if) to output the symlink vs hard file.
