### ISSUE TITLE
Manual setup gulp

### ISSUE THREAD

**Issue by vnikolay** [gulpjs/gulp#2331]
I use gulp as a part of a project. And I need to set up it manually, not in the file gulpfile.js.
My code is very simple:

gulp.task('js', 
	done => {
console.log('js start');
		gulp.src(paths)
		.pipe(concat('combined.js'))
		.pipe(uglify())
		.pipe(gulp.dest(path+'/compiled/'))
		
		.on('end', function() {
            console.log('js');
        })
        
		.on('error', function (err) { gutil.log(
        	gutil.colors.red('[Error]'), err.toString());
        	console.log(err)
        });
                                
	    done();
	}
);

gulp.task('default',
	gulp.series('js')
);

This code runs when GET-request is coming on server.js. 
So when I run it as gulpfile.js by "node node_modules/gulp/bin/gulp.js" it works, but when
I run it as "node gulpfile.js" (actually name is server.js) - it doesn't work . In gulp 3.x everything was ok, but not in gulp 4.

**Comment by phated** [comment]
Don't use gulp on the server with user input being passed to gulp.  It is not made for that and we don't address security concerns that would effect you from doing things like that.
