### ISSUE TITLE
can't find moudle "chokidar"

### ISSUE THREAD

**Issue by SilverLeaves** [gulpjs/gulp#2334]
here are two issue, one about gulp and the other one is about postcss

please have look the one about gulp, ` can't find moudle "chokidar"` 

**What were you expecting to happen?**
no error
**What actually happened?**
![图片](https://user-images.githubusercontent.com/31165554/57755491-a9edb780-7723-11e9-87f8-092da067e105.png)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
import * as  gulp from "gulp"
import * as rename from "gulp-rename"
import * as stylus from "gulp-stylus"
import * as plumber from "gulp-plumber"

import * as autoprefixer from "autoprefixer"
import * as postcss from "gulp-postcss"

import * as ts from "gulp-typescript"
import { FSWatcher } from "fs";

let tsProject = ts.createProject("tsconfig.json");

function acss(done) {
    gulp.src(`pages/**/*.styl`)
        .pipe(plumber())
        .pipe(stylus())
        .pipe(postcss([autoprefixer()]))
        .pipe(rename({
            extname: '.acss',
        }))
        .pipe(gulp.dest("./"));
    done();
}

function tsc(done) {
    gulp.src(`./**/*.ts`)
        .pipe(tsProject())
        .js
        .pipe(gulp.dest("./"));
    done();
}

console.log("starting gulp task...")
gulp.task("default", gulp.parallel(acss, tsc))

console.log("starting watching...")

let watcher = <FSWatcher[]>[]

watcher.push(gulp.watch(`./**/*.styl`, acss))
watcher.push(gulp.watch(`./**/*.ts`, tsc))

watcher.forEach((ele) => {
    ele.on("change", (fileName, eventType) => {
        console.log(`${fileName} changed...`)
    })
})

```

**What version of gulp are you using?**
4.0.2
**What versions of npm and node are you using?**
node 15.3 npm 6.4.1 yarn 1.5.2

**Comment by demurgos** [comment]
This looks like an issue in your `package.json` or `tsconfig.json` file. Make sure that you use `@types/gulp@4.0.4` or higher.

This is a Typescript error caused by the types defined in DefinitelyTyped. We don't control these types. [Report the issue on DefinitelyTyped] if it persists.

**Comment by SilverLeaves** [comment]
@demurgos yeah, I use @types/gulp@4.0.6 now. and it has some relation with `tsconfig.json` file, the issue come out wiht `target option` above `es5`.
