### ISSUE TITLE
Having the exact same problem.  Using: Gulp 4

### ISSUE THREAD

**Issue by Jonesdl-2785** [gulpjs/gulp#2335]
Having the exact same problem.  Using: Gulp 4
node: v12.2.0
npm: 6.9.0
gulp CLI version: 2.2.0
Local version: 4.0.2

`
[exec] foundation new --framework emails
[exec] fs.js:27
[exec] const { Math, Object } = primordials;
                         ^

[exec]ReferenceError: primordials is not defined
[exec]   at fs.js:27:26
[exec]    at req_ (/usr/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
[exec]   at Object.req [as require] (/usr/lib/node_modules/foundation-[cli/node_modules/natives/index.js:55:10)
[exec]    at Object.<anonymous> (/usr/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
[exec]    at Module._compile (internal/modules/cjs/loader.js:759:30)
[exec]    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
[exec]    at Module.load (internal/modules/cjs/loader.js:628:32)
[exec]    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
[exec]    at Module.require (internal/modules/cjs/loader.js:666:19)
[exec]    at require (internal/modules/cjs/helpers.js:16:16)`

node: v12.2.0
npm: 6.9.0
gulp CLI version: 2.2.0
gulp Local version: 4.0.1

`
     [exec] fs.js:27
     [exec] const { Math, Object, Reflect } = primordials;
     [exec]                                   ^
     [exec] 
     [exec] ReferenceError: primordials is not defined
     [exec]     at fs.js:27:35
     [exec]     at req_ (/Users/remillet/dev/src/nuxeo/addons/nuxeo-platform-spreadsheet/nuxeo-platform-spreadsheet-web/src/main/js/node_modules/natives/index.js:143:24)
     [exec]     at Object.req [as require] (/Users/remillet/dev/src/nuxeo/addons/nuxeo-platform-spreadsheet/nuxeo-platform-spreadsheet-web/src/main/js/node_modules/natives/index.js:55:10)
     [exec]     at Object.<anonymous> (/Users/remillet/dev/src/nuxeo/addons/nuxeo-platform-spreadsheet/nuxeo-platform-spreadsheet-web/src/main/js/node_modules/graceful-fs/fs.js:1:37)
     [exec]     at Module._compile (internal/modules/cjs/loader.js:759:30)
     [exec]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
     [exec]     at Module.load (internal/modules/cjs/loader.js:628:32)
     [exec]     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
     [exec]     at Module.require (internal/modules/cjs/loader.js:666:19)
     [exec]     at require (internal/modules/cjs/helpers.js:16:16)`

_Originally posted by @remillet in https://github.com/gulpjs/gulp/issues/2324#issuecomment-488356019_

**Comment by jonathan-nielsen** [comment]
Having the same issue

node: v12.1.0
npm: 6.9.0
gulp CLI version: 2.2.0
gulp Local version: 4.0.2

```
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (.../node_modules/natives/index.js:143:24)
    at Object.req [as require] (.../node_modules/natives/index.js:55:10)
    at Object.<anonymous> (.../node_modules/gulp-require-tasks/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module._compile (.../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```

**Comment by phated** [comment]
We don't ship the `graceful-fs` that includes the `natives` module with gulp 4 - that version of graceful-fs is extremely old and you shouldn't be using it.
