### ISSUE TITLE
gulp.src and gulp.watch glob patterns are inconsistent

### ISSUE THREAD

**Issue by oliversalzburg** [gulpjs/gulp#2340]
**What were you expecting to happen?**
The glob patterns that are passed to `gulp.src` should also work for `gulp.watch`.

**What actually happened?**
When passing paths with `\` to gulp.watch, your watchers don't run.

This is a [known issue](https://github.com/gulpjs/gulp/issues/2085), when using `path.join` to concatenate path parts on Windows. This is unfortunate, because the same paths will work just fine for `gulp.src`.

To work around this issue, one can use `path.posix.join` to always use forward slashes, which work just as well on Windows.

Maybe this should be noted in the documentation?

**What version of gulp are you using?**
4.0.2

**What versions of npm and node are you using?**
6.9.0 and v12.4.0

**Comment by contra** [comment]
This is tracked in https://github.com/paulmillr/chokidar/issues/777

Seems like an easy bug fix if you want to send a PR to that project.

**Comment by phated** [comment]
In gulp 4, that path separator won't work either.  It is documented https://gulpjs.com/docs/en/getting-started/explaining-globs#segments-and-separators

**Comment by oliversalzburg** [comment]
@phated You mean the POSIX path separator won't work either? That would contradict what the documentation says. At least the part you linked to.

And using the forward slash `/` works perfectly fine for me for both use cases  on Windows. What am I missing?

**Comment by phated** [comment]
As stated in the docs, only POSIX path separators are valid glob path separators. Your original question was about Windows path separators.

Also, your suggested changes to the docs are already present in the docs.
