### ISSUE TITLE
process.exit(0) doesn't seem to exit

### ISSUE THREAD

**Issue by sean256** [gulpjs/gulp#2341]
**What were you expecting to happen?**
`process.exit(0)` to exit the process without returning an error.

**What actually happened?**
`npm ERR! code ELIFECYCLE`

Why? I need a way to conditionally abort a series of tasks without throwing an error.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
const b = async () => {
	log('b');
};
const a = async () => {
	log('a');
	process.exit(0);
};
exports.a = series(a, b);
```

OUTPUT

```
[08:43:42] Starting 'a'...
[08:43:42] Starting 'a'...
[08:43:42] a
[08:43:42] The following tasks did not complete: a, a
[08:43:42] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! do-ps-ipt-panel-extension@0.0.2-0 foo: `gulp a`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the do-ps-ipt-panel-extension@0.0.2-0 foo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**What version of gulp are you using?**
4.0.2

**What versions of npm and node are you using?**
Node: 10.15.3
NPM: 6.4.1

**Comment by phated** [comment]
A task series must complete, otherwise we flag it as an error.  In the past, we didn't do this and it caused subtle bugs that were really hard to track down.  You can often achieve your same goal by composing tasks conditionally.
