### ISSUE TITLE
Autoprefixer browsers warning produced in Gulp 3.9.1 system 

### ISSUE THREAD

**Issue by reineydays** [gulpjs/gulp#2342]
This is the exact same warning that appears in this recently closed issue - 
[https://github.com/gatsbyjs/gatsby/issues/14530](url) 

, except a solution hasn't been found for the Gulp system.
My Gulp system runs but now shows this warning - 

````
Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
````

I started using a Gulp-SASS-Pug boilerplate on which to build my website in the repository: [https://github.com/reineydays/reineydays.github.io](url) and was able to run it and preview my website on localhost 3000 while editing the HTML and CSS.

I am now unable to preview my website on localhost 3000, but can push changes to my website. I have tried modifying my package.json file but to no avail. 

Node version - 10.16.0
Npm version - 6.9.0

**Comment by phated** [comment]
@reineydays unfortunately, none of that stuff is actually created or managed by us.  This isn't an issue with gulp itself.
