### ISSUE TITLE
Gulp watch - recursive glob pattern not working

### ISSUE THREAD

**Issue by bluebrown** [gulpjs/gulp#2345]
### What were you expecting to happen?
I was expecting this glob pattern to work in gulp.watch. **It should achieve to watch all files in react-app, and all subfolder recursively.**
```
'./react-app/[!styles]{,**/}**'
```

_It works with gulp.src!_

### What actually happened?
It did not work, It only watches files in react-app

```js
const gulp = require('gulp');

// It works with gulp.src. In fact the method with {,**/}
// seems the only way to make it work.
const transpileJSX = () => gulp.src('./react-app/[!styles]{,**/}**')
    .pipe(require('gulp-babel')())
    .pipe(require('gulp-uglify')())
    .pipe(gulp.dest('./preload/react.dist/'));

gulp.task('jsx', transpileJSX);


// With gulp.watch this glob pattern does not watch the
// folder and all subfolders recursively
const watchJSX = () =>
    gulp.watch('./react-app/[!styles]{,**/}**', transpileJSX);

gulp.task('jsx:watch', watchJSX);
```

**Meta**
-  gulp - 4.0.2
- node - 10.16.0
- npm - 6.9.0
- yarn - 1.16.0

**Comment by qinyuanbin** [comment]
+1, I have the same problem rightnow, I found it work by passing an ignore file
```js
gulp.src([‘css/**/*.less’, ’!css/module/_variable.less’])
```

it is weird, whithout the ignore parts, glob does’t work fine

**Comment by phated** [comment]
@bluebrown we rely on [chokidar](https://github.com/paulmillr/chokidar) for our globbing on `gulp.watch`. If something doesn't match `gulp.src`, you should bring it up with them.
