### ISSUE TITLE
Gulp compatibility with node version

### ISSUE THREAD

**Issue by jimblue** [gulpjs/gulp#2346]
Hi,

I wasn't able to found what are the require node engines for Gulp 3 and Gulp 4.
Is Gulp 3 compatible with Nodejs 10?
Is Gulp 4 compatible with Nodejs 6?

Thanks

**Comment by stevelacy** [comment]
https://github.com/gulpjs/gulp/blob/master/package.json#L13

**Comment by ssimontis** [comment]
Yes, but it doesn't work in Node 10+ even though it says it does. Can we have this reopened?

**Comment by stevelacy** [comment]
@ssimontis Gulp does work with node 10, 12, 13, etc. What is the issue you are finding?

**Comment by phated** [comment]
Gulp 3 probably doesn't work with new node but that version is unmaintained as we released v4 about 3 years ago now - and node breaks things all the time.

Gulp 4 works on everything in the test matrix, though we are currently triaging a breaking change node core introduced in 12.18.3 that might cause some weirdness - though it should be an edge case of closing watchers in a running process and shouldn't affect most people.
