### ISSUE TITLE
need ES6 gulpfile example

### ISSUE THREAD

**Issue by Spongman** [gulpjs/gulp#2359]
the docs here need an example that shows how to use ES6 features like `import`/`export` and `async` in a gulpfile.

there's too much obsolete information scattered about, and having an out-of-date example in this repo's README doesn't help. @

**Comment by stevelacy** [comment]
If you had spent just enough time to scroll down you would have noticed this in the readme.

https://github.com/gulpjs/gulp#use-latest-javascript-version-in-your-gulpfile

The readme is _not_ obsolete.

**Comment by Spongman** [comment]
yeah, the babel stuff doesn't support `async`, and the 'esm' comment is entirely unhelpful.

**Comment by phated** [comment]
Hey @Spongman! Sorry that you were encountering out-of-date information, but that's going to be a problem with any sufficiently-old technology you are working with. We strive to keep the official documentation on our website (https://gulpjs.com) up-to-date but we don't really have control over StackOverflow or old information in issues.

New versions of node support `async`/`await` syntax, so you should probably just upgrade your version of node. For `import`/`export` syntax, you should review this section of our docs: https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#transpilation
