### ISSUE TITLE
Did you forget to signal async completion?

### ISSUE THREAD

**Issue by NasKadir123** [gulpjs/gulp#2364]
Hello!
Sorry for this question, but I looked at every issue with such theme,
But didn't find solution.
I have an error in terminal: 

The following tasks did not complete: styles, images, copy
Did you forget to signal async completion?

Here is my code:
`export const serve = done => {
  server.init({
    proxy: "http://localhost:8888/wordpress"
  });
  done();
};

export const reload = done => {
  server.reload();
  done();
};

export const clean = () => del(["dist"]);

export const watch = () => {
  gulp.watch("src/assets/scss/**/*.scss", styles);
  gulp.watch(paths.images.src, gulp.series(images, reload));
  gulp.watch(paths.other.src, gulp.series(copy, reload));
};

export const copy = () => {
  return gulp.src(paths.other.src).pipe(gulp.dest(paths.other.dest));
};

export const styles = () => {
  return gulp
    .src(paths.styles.src)
    .pipe(gulpif(!PRODUCTION, sourcemaps.init()))
    .pipe(sass().on("error", sass.logError))
    .pipe(gulpif(PRODUCTION, cleanCSS({ compatibility: "ie8" })))
    .pipe(gulpif(!PRODUCTION, sourcemaps.write()))
    .pipe(gulp.dest(paths.styles.dest))
    .pipe(server.stream());
};

export const images = () => {
  return gulp
    .src(paths.images.src)
    .pipe(gulpif(PRODUCTION, imagemin()))
    .pipe(gulp.dest(paths.images.dest));
};

export const dev = gulp.series(
  clean,
  gulp.parallel(styles, images),
  serve,
  watch
);
`

Can you help me please? 
Thanks.
node -v
v10.16.2
npm -v
6.9.0
gulp -v
CLI version: 2.2.0
Local version: 4.0.2

**Comment by PLQin** [comment]
Take a look at this `https://github.com/gulpjs/gulp/issues/2366` . It may help you.
