### ISSUE TITLE
Does not find local gulp on Travis CI

### ISSUE THREAD

**Issue by DanielRuf** [gulpjs/gulp#2367]
**What were you expecting to happen?**
The locally installed gulp should be found.

**What actually happened?**
Gulp says that it can not find the local gulp install.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
Standard example from website.
See https://travis-ci.com/DanielRuf/gulp-snapshot-test/jobs/225987166#L541

**What version of gulp are you using?**
4

**What versions of npm and node are you using?**
yarn and node 10.16

**Comment by sttk** [comment]
@DanielRuf Gulp needs to place `gulpfile.js` and `package.json` (`node_modules/`) in same directory. So copy `gulpfile.js` in `gulp4/` directory before executing gulp, for example.

**Comment by DanielRuf** [comment]
Ah thanks for the hint. Seems I forgot to remove the mkdir + cd steps when I was testing =)

**Comment by DanielRuf** [comment]
But generally the error message is very confusing. Don't you think so?

**Comment by DanielRuf** [comment]
See https://github.com/gulpjs/gulp-cli/blob/master/index.js#L150-L160

Shouldn't it be https://github.com/gulpjs/gulp-cli/blob/master/index.js#L175?

I think there might be some regression / bug.
