### ISSUE TITLE
[feat] kebab-case the private task names

### ISSUE THREAD

**Issue by pronebird** [gulpjs/gulp#2371]
Hi,

I'd like to request a feature to add a capability to kebab-case the private task names. Right now I have to use `displayName` which pollutes the code and creates a lot of duplication for something that can easily be automated. Maybe the default registry can expose a flag to achieve that?

```js
function copyCss() {
  return src('*.css').pipe(dest('out'));
}
copyCss.displayName = 'copy-css';
```

**Comment by sttk** [comment]
@pronebird Does this gulpfile meet your request?

```js
const { series } = require('gulp')
const obj = {
  'copy-css': () => {}
}
exports.default = series(obj['copy-css'])
```

```
$ npx gulp -T
[00:50:52] Tasks for ~/proj/gulpfile.js
[00:50:52] └─┬ default
[00:50:52]   └─┬ <series>
[00:50:52]     └── copy-css
```

Or [this my little plugin](https://www.npmjs.com/package/gulp-fun-style) (gulp-fun-style) might helps you.😄

**Comment by pronebird** [comment]
@sttk not particularly elegant solution. I thought we could do better. I really enjoy the simplicity of gulp and thought to keep it that way. Certainly I could make a helper to craft the name but that just adds noise in the source code.

**Comment by phated** [comment]
Just use:
```
exports['copy-css'] = copyCss;
```

This won't work for ESM exports but that's just how they made the spec.
