### ISSUE TITLE
Unclear wording in docs on `src` option parameter `buffer`

### ISSUE THREAD

**Issue by craigphicks** [gulpjs/gulp#2373]
**What were you expecting to happen?**

Docs would make clear whether `buffer` parameter would automatically be over riden for large files.

**What actually happened?**

Not clear.

-----------------------

> When true, file contents are buffered into memory. If false, the Vinyl object's contents property will be a paused stream. *It may not be possible to buffer* the contents of large files.

https://gulpjs.com/docs/en/api/src

The wording half implies buffering will be abandoned and streaming used instead to avoid failure.  It might be helpful to make it clear which design choice was taken.

**Comment by phated** [comment]
That is just a note to say that the end user might not be able to buffer large files. What is your suggestion? Should we label it "Note" like the note below it?

**Comment by craigphicks** [comment]
So it doesn't switch to streaming - which would actually be pretty hard to do and streaming might not be supported anyway.  Got it.  Thanks for your reply.
