### ISSUE TITLE
gulp.watch() does not recognize Windows file paths

### ISSUE THREAD

**Issue by fishfin** [gulpjs/gulp#2374]
**What were you expecting to happen?**
Watch files for changes

**What actually happened?**
Gulp does not work with Globs on Windows style file paths e.g. 'c:\\test\\*.scss'. I get input from user, and use path.normalize to normalize it for the platform.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
```js
const watcher = gulp.watch('c:\\prod\\htdocs\\gulp\\*.scss', pkgGulp.series(test));
```

**What version of gulp are you using?**
Gulp v4.0.2 (the above worked well in v3.9.1, broken now)

**What versions of npm and node are you using?**
NodeJS 10.16.0, NPM 6.9.0

**Comment by phated** [comment]
Windows paths are not globs. We have this documented at https://gulpjs.com/docs/en/getting-started/explaining-globs
