### ISSUE TITLE
Gulp Task completes with no error but no file is saved to destination

### ISSUE THREAD

**Issue by ousszizou** [gulpjs/gulp#2378]
**What were you expecting to happen?**
copying file named index.html from 'src' folder to 'dist' folder. 

**What actually happened?**
when i run the task, it completes, but there's nothing at the 'dist' folder. (the file index.html not found in the 'dist' folder)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
const { src, dest } = require('gulp')

exports.default = function () {
    return src('src/index.html')
        .pipe(dest('dist'));
}
```
=> structure of my project :
--dist/
--src/
----index.html
--gulpfile.js

**What version of gulp are you using?**
I use gulp version 4

**What versions of npm and node are you using?**
node v8.16.1
npm 6.4.1

**Comment by ousszizou** [comment]
solved

**Comment by NicolaiSchmid** [comment]
How did you solve it?

**Comment by tylerdong** [comment]
How did you solve it?

**Comment by tylerdong** [comment]
How did you solve it?
