### ISSUE TITLE
gulp-cli should ignore arguments after first task

### ISSUE THREAD

**Issue by dawidgarus** [gulpjs/gulp#2379]
**What were you expecting to happen?**
`gulp task --version` and `gulp task --help` should execute `task`

**What actually happened?**
Gulp shows it's version/help page.

According to it's own help, options should come before tasks list:
```
Usage: gulp [options] tasks
```
Every additional options after tasks should be ignored by gulp and be assumed as the arguments for the tasks.
This will allow the task to use arguments that are currently restricted by gulp.
Also, adding new option to gulp won't break existing tasks because they might use it already for something else.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
N/A

**What version of gulp are you using?**
CLI version: 2.2.0
Local version: 4.0.2

**What versions of npm and node are you using?**
npm 6.2.0
node v10.9.0

**Comment by phated** [comment]
Flags are not positional. You can use `--` to separate trailing flags. e.g. `gulp task -- --version`

**Comment by dawidgarus** [comment]
@phated then gulp treats `--version` a task name:
```
>gulp --version
CLI version: 2.2.0
Local version: 4.0.2
>gulp default -- --version
[10:20:19] Using gulpfile [...]\gulpfile.js
[10:20:19] Task never defined: --version
[10:20:19] To list available tasks, try running: gulp --tasks
```

**Comment by phated** [comment]
You're right. I'm not sure which behavior I prefer because I've seen people that might want to prefix their tasks with a symbol (like a `-`).

If we change this, it would be a breaking change in the CLI.
