### ISSUE TITLE
Add 'dot' option to 'watch'

### ISSUE THREAD

**Issue by Ursi** [gulpjs/gulp#2385]
When listening to files, I can use the `dot` option for my `src` globs. However, if I want to watch those same globs, there's no option to do that and I have to list out all dot entries explicitly.

Edit: I'm sorry, I did this in haste. I should have at least gone to SO first. Unfortunately I can't delete this so I hope that there isn't an easy solution I missed. I apologize in advance if there is.

**Comment by revelt** [comment]
@Ursi you don't need to delete, actually issues are never deleted — you just need to close it, click the button to close this issue underneath

**Comment by Ursi** [comment]
@revelt well if I close it then I don't think I can reopen it, and I don't want to close it if Gulp actually *is* missing this functionality.

**Comment by phated** [comment]
Gulp uses Chokidar v2.x - so you get whatever globbing they support.
