### ISSUE TITLE
why deprecated gulp.start

### ISSUE THREAD

**Issue by fragno** [gulpjs/gulp#2391]
without gulp.start, how can we use gulp without gulpfile.js?

**Comment by spacu** [comment]
> why deprecated gulp.start

Because there is another way to do it (`gulp.run`, ` gulp.start`). They are `gulp.parallel` and` gulp.series`.

```javascript
gulp.parallel('task')();
gulp.series('task')();
```

**Comment by dawidgarus** [comment]
@spacu shouldn't it be documented in any way? Right now documentation for parallel and series says that they return an "operation". It's not obvious that it's function (might as well be some internal reference used by gulp) and what that operation function signature is. Should I pass a callback or does it return a promise?
