### ISSUE TITLE
Cannot find the module 'gulp-shell'...

### ISSUE THREAD

**Issue by kirangangireddy** [gulpjs/gulp#2398]
I have installed the gulp and i can even see the versions when running gulp -v
CLI version: 2.2.0
Local version: 4.0.2

But running the gulp command, it throws an error "cannot find the module gulp-shell" (it's throwing the error for all gulp even when commenting this gulp-shell). I dont know what went wrong as i can see the gulp installation is also perfect as it's showing the versions.

Could someone please help me on this.

Thanks in advance.

**Comment by github-paul** [comment]
have u tried run the command - ‘npm install --save gulp-shell’ in the current working directory?

**Comment by phated** [comment]
`gulp-shell` is not part of gulp.

**Comment by github-paul** [comment]
Thanks Phated!
