### ISSUE TITLE
Gulp.dest() does not close files after writing to them

### ISSUE THREAD

**Issue by petr-buchin** [gulpjs/gulp#2402]
**What were you expecting to happen?**
I'm running `gulp.watch()` locally to recompile static files in `public/dist` directory.
I also watch `public/dist` directory with `Skaffold` to propagate changes to containers in my Kubernetes cluster.
**What actually happened?**
File changes does not get propagated when files are changed by `gulp`, but they propagated when I change them by some text redactor.
I traced `gulp` process and looks like `gulp` does not close files when writes to them.
I searched for some option in `gulp.dest()` but did not find anything.
**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
This task is running from `.gulp.watch()` task
```js
gulp.task('myapp.js', () => {
  return gulp.src(SRC_PATH + '/myapp.app.js')
    .pipe(plumber())
    .pipe(bro({
      transform: [
        babelify,
        [browserifyCss, { global: true }]
      ]
    }))
    .pipe(rename('myapp.min.js'))
    .pipe(base64())
    .pipe(development(sourcemaps.init({ loadMaps: true })))
    .pipe(production(ngAnnotate()))
    .pipe(production(uglify()))
    .pipe(development(sourcemaps.write('.')))
    .pipe(production(rev()))
    .pipe(assetManifest({
      bundleName: 'myapp-scripts',
      log: development() && !isWatching,
      manifestFile: MANIFEST_FILE,
      pathPrepend: MANIFEST_PREPEND_PATH
    }))
    .pipe(gulp.dest(getTenantAssetsPath('myapp')))
});
```

**What version of gulp are you using?**
3.9.1

**What versions of npm and node are you using?**
NPM: 6.11.3
Node: v10.17.0

**Comment by contra** [comment]
What OS are you on, and are the files being modified on any non-standard drive?

**Comment by phated** [comment]
Gulp 3.9.1 is no longer supported. There were plenty of issues with the filesystem stuff.

**Comment by petr-buchin** [comment]
@phated please reopen this issue, since the same behavior applies to Gulp 4: files get synchronized without `gulp watch`, but when I run the same tasks from `watch`, files do not get synchronized, since they are not closed after piping to `dest()`.
@contra my OS is MacOS Catalina, and no, the drive is standard.
