### ISSUE TITLE
gulpfile.babel.coffee file support

### ISSUE THREAD

**Issue by MegaJSDeveloper** [gulpjs/gulp#2404]
## Bug Report

**Current Behavior**
`gulpfile.babel.coffee` must not using coffeescript transpilation, it use just babel transpilation

**Expected behavior**
`gulpfile.babel.coffee` must go through the transpilation chain `coffeescript` => `babel`

**Configuration**
`gulpfile.babel.coffee` : 
```coffee
import 'gulp' from 'gulp'
#fs = require('fs')

gulp.task 'default', => console.log('hello world')
```
`cmd` :
```cmd
gulp --gulpfile ./gulpfile.babel.coffee

#fs = require('fs')
^^^

SyntaxError: Unexpected identifier
```

**Gulp versions**
CLI version: 2.2.0
Local version: 4.0.2

**Comment by phated** [comment]
Babel support is enabled by .babel.js

**Comment by MegaJSDeveloper** [comment]
@phated but not supported in .babel.coffee that's why I created this bug report

![image](https://user-images.githubusercontent.com/58376230/71402077-fba4db80-263c-11ea-93d7-d8b7f7e10b28.png)

**Comment by phated** [comment]
Multi-extension support comes with Rechoir 0.7.0 - see https://github.com/gulpjs/rechoir/commit/9bb964eb1ef150fa10551f1d23fd5db41843ef8c

That can't be upstreamed yet due to breaking changes.
