### ISSUE TITLE
Provide possibility to create tasks with anonymous functions and metadata 

### ISSUE THREAD

**Issue by ThePlenkov** [gulpjs/gulp#2405]
Hi!

To make code more compact I prefer to work with arrow functions.

However in this case task declaration doesn't look compact. We need to register a variable and provide it as input parameter.

As a proposal I suggest to add metadata parameter for gulp task function.

Here is an example:
https://gitlab.com/theplenkov-npm/gulp-task

```
const { src, task, dest } = require("gulpty")(require("gulp"));

task("build", done => {
  src(`${DEST_DIR}/**/themes/bui/library.less`)
    .pipe(less())
    .pipe(dest(DEST_DIR));
  done();
}, {description:"build theme"});
```

it would be nice to have it just in gulp. What do you think about this? Thank you!

**Comment by callumacrae** [comment]
how are fat arrow functions more compact than the export syntax?

```
export function build() {
  return src(`${DEST_DIR}/**/themes/bui/library.less`)
    .pipe(less())
    .pipe(dest(DEST_DIR));
}
```

**Comment by ThePlenkov** [comment]
ok - in this example the attention was mostly made on the metadata part. 

Currently in the example it is proposed to use a dedicated variable:
https://gulpjs.com/docs/en/api/task#usage
like
```
function build(cb) {
  // body omitted
  cb();
}
build.description = 'Build the project';
build.flags = { '-e': 'An example flag' };

task(build);
```

so the idea is to have something like this:

```
task("build", function() {}, { description..., flags:...} )
```

so whether it is arrow function or not is not important

**Comment by phated** [comment]
String task names and the task function are no longer encouraged. They are a hold-over from previous versions of gulp. Use named functions and exports.

We aren't going to change the task method.
