### ISSUE TITLE
unlinkDir event doesn't trigger with * (asterisk) glob 

### ISSUE THREAD

**Issue by arpadpall21** [gulpjs/gulp#2407]
The 'unlinkDir' event doesn't trigger if I use the * (asterisk) glob 

Any other event works just fine with the * (asterisk) glob ('add' 'addDir' ect..) but the 'unlinkDir'

The 'all' event triggers for all activity (add, remove, modify file and add directory) but doesn't recognizes when I remove a directory either   

  
  

```js
const {watch} = require('gulp');
    
exports.default = function(cb){
    watch('*', {events:'addDir'}, function(cb){                     // event triggers when adding a new directory to the cwd 
        console.log( 'TEST' );
        cb();
    });
    
    watch('*', {events:'unlinkDir'}, function(cb){                  // event does not trigger when removing a directory from the cwd
        console.log( 'TEST' );
        cb();
    });
    
// using chokidar instance -----------------------------------------
    var myChokidar = watch('*');
    
    myChokidar.on('addDir', function(path, stats){                  // event triggers when adding a new directory to the cwd
        console.log( `${path} directory added!` );
    });
    
    myChokidar.on('unlinkDir', function(path, stats){               // event does not trigger when removing a directory from the cwd
        console.log( `${path} directory removed!` );
    });
    
    cb();
}

```

**What version of gulp are you using?**
4.0.2
**What versions of npm and node are you using?**
NPM:  v6.13.1
Node: v13.2.0
OS: Windows10 (PowherShell)

**Comment by phated** [comment]
Have you checked if this can be replicated directly with chokidar?

**Comment by arpadpall21** [comment]
Yes it does, I've recently tested almost all the Gulp (v4.0.2) methods, here's what I noticed:
- the src() does not recognizes symbolic-links 
- the watch() method and chokidar instances are inconsistent watching files and directories, especially when using wildcard characters (this is my biggest disappointment)   

Tested on Windows (PowerShell v5.1.16299.1146), maybe on Linux it's different

**Comment by phated** [comment]
@arpadpall21 I'm not talking about the gulp methods, I'm talking about the underlying module. Please create a reproduction with just the chokidar module.
