### ISSUE TITLE
gulp fails on node_contextify.cc:631 assertion args[1]->IsString()

### ISSUE THREAD

**Issue by hitschandlarism** [gulpjs/gulp#2414]
> ui@1.0.0 postinstall 
> gulp deploy

gulp[8764]: c:\ws\src\node_contextify.cc:635: 

**Assertion `args[1]->IsString()' failed.**

 1: 00007FF77101D1BA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF770FF7F96 node::MakeCallback+4534
 3: 00007FF770FF804F node::MakeCallback+4719
 4: 00007FF770FCC460 node::DecodeWrite+13120
 5: 00007FF771525212 std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+79442
 6: 00007FF771526379 std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+83897
 7: 00007FF7715256BC std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+80636
 8: 00007FF7715255DB std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+80411
 9: 000000558D2DC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ui@1.0.0 postinstall: `gulp deploy`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the ui@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

C:\Users\mypc>node -v
v10.16.2

C:\Users\myoc>npm gulp -v
6.9.0

If anyone could please help me in understanding this issue.

**Comment by phated** [comment]
When you run into an error that looks like this, you are having troubles with native modules, which means you are either using an old version of gulp that doesn't work on your current version of node or you need to rebuild your native modules for a new version of node (usually this happens if you wipe node_modules and reinstall).

**Comment by hitschandlarism** [comment]
Sure thanks @phated
