### ISSUE TITLE
 watch queue does not affect on xy listener

### ISSUE THREAD

**Issue by senyaak** [gulpjs/gulp#2415]
I have following code
```js
  const watchCss = gulp.watch([
    path.join(conf.paths.src, "/app/**/*.css"),
  ], {queue: true}); // queue is by default true - I just wanna show it explicit

  watchCss.on('change', (done) => {
    console.log('start'); // it fires every time I save file immediately 
    styles(done);
  ); // styles -> some event handler
  watchCss.on('add', inject); // inject -> some event handler

```

**What were you expecting to happen?**
When I save file - the event starts. When I save file once again before previous event ends - new event placed in queue
**What actually happened?**
Events fire at the time I hit save.

**What version of gulp are you using?**
4
**What versions of npm and node are you using?**
6.13.7/12.14.1

**Comment by phated** [comment]
Please read the API docs. Queueing is not supported when using a chokidar instance directly.

**Comment by senyaak** [comment]
@phated Thanks - found it! Could u also please tell me - how can I access event and have queue in same time?
