### ISSUE TITLE
TypeError: e.pipe is not a function

### ISSUE THREAD

**Issue by meness** [gulpjs/gulp#2416]
**What were you expecting to happen?**
`series()` should work properly.

**What actually happened?**
I get the following exception while using `series()`.

> C:\X\src\node_modules\stream-series\index.js:23
>     e.pipe(pauseStream);
>       ^
> 
> TypeError: e.pipe is not a function
>     at C:\X\src\node_modules\stream-series\index.js:23:7
>     at Array.forEach (<anonymous>)
>     at module.exports (C:\X\src\node_modules\stream-series\index.js:20:11)
>     at Object.<anonymous> (C:\X\src\gulpfile.js:222:17)
>     at Module._compile (internal/modules/cjs/loader.js:936:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
>     at Module.load (internal/modules/cjs/loader.js:790:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:703:12)
>     at Module.require (internal/modules/cjs/loader.js:830:19)
>     at require (internal/modules/cjs/helpers.js:68:18)

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

`parallel()` works fine.

```js
function buildVendorJs(cb) {
  browserify({
      entries: './browserify.js',
      debug: false
    })
    .bundle()
    .pipe(fs.createWriteStream('./public/js/vendor.js'));

  cb();
}

exports.build = series(buildVendorJs);
```

**What version of gulp are you using?**
Gulp 4.0.2

**What versions of npm and node are you using?**
NPM 6.13.7 and Node 12.10.0

**Comment by phated** [comment]
This has nothing to do with gulp. You are handling asynchronousity incorrectly and something seems to be happening in browserify.

**Comment by meness** [comment]
@phated It definitely relates to Gulp because this very simple snippet doesn't work too! and get the same exception while using `series()`, but everything is fine with `parallel()`. OPEN THE ISSUE

```js
function testA(cb) {
  console.log("Test A");

  cb();
}

function testB(cb) {
  console.log("Test B");

  cb();
}

exports.test = series(testA, testB);
```
