### ISSUE TITLE
 AssertionError [ERR_ASSERTION]: Invalid callback object specified

### ISSUE THREAD

**Issue by umerfarooqjamsa** [gulpjs/gulp#2418]
D:\inbox>node compile.js
assert.js:374
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Invalid callback object specified.
    at runWithCallbacks (D:\inbox\node_modules\[4msolc[24m\wrapper.js:97:7)
    at compileStandard (D:\inbox\node_modules\[4msolc[24m\wrapper.js:207:14)
    at Object.compileStandardWrapper [as compile] (D:\inbox\node_modules\[4msolc[24m\wrapper.js:214:14)
    at Object.<anonymous> (D:\inbox\compile.js:6:18)
[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:811:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  generatedMessage: [33mfalse[39m,
  code: [32m'ERR_ASSERTION'[39m,
  actual: [33mfalse[39m,
  expected: [33mtrue[39m,
  operator: [32m'=='[39m
}

**Comment by phated** [comment]
This doesn't include anything about gulp. Sorry.
