### ISSUE TITLE
gulpfile.ts, support ts-node flags like transpile-only

### ISSUE THREAD

**Issue by ayroblu** [gulpjs/gulp#2429]
Hi, wondering if it's possible to pass flags down for ts-node. An example of this is `--transpile-only`

**Comment by nicolashenry** [comment]
If it can help you, I found out a way to do it using environment variable `TS_NODE_TRANSPILE_ONLY`.

To automatise it, I installed `dotenv` package, added a `.env` file containing `TS_NODE_TRANSPILE_ONLY=true` and finally added `.gulp.json` file containing `{"flags":{"require": "dotenv/config"}}`.

It could be simpler if `.gulp.json` could support adding environment variables directly so `dotenv` would not be needed.

**Comment by phated** [comment]
@nicolashenry thanks for helping out! You can also just specify the flag at the command line `TS_NODE_TRANSPILE_ONLY=true gulp` because those will be available to the process.

> It could be simpler if .gulp.json could support adding environment variables directly so dotenv would not be needed.

Feel free to open a feature request for that feature on https://github.com/gulpjs/gulp-cli and we will consider it!
