### ISSUE TITLE
Outputting multiple files

### ISSUE THREAD

**Issue by twolfson** [gulpjs/gulp#243]
I am interested in creating a gulp plugin for spritesmith, an images to spritesheet/CSS variables library. From a glance, it looks like `gulp` does not have any documentation on streams that output different data formats.

To elaborate further, the grunt flavor outputs a generated image and a set of formatted CSS. I was wondering if there is a defacto/preferred way to handle this case.

I have been playing around with my options and have found a nice syntax

``` js
// Create muxed stream
var spriteData = gulp.src(path.images).pipe(gulpSpritesmith({
  cssFormat: 'css'
}));


// Output the image and CSS
// Under the hood, this would perform a demux + pipe
spriteData.pipe('image', gulp.dest('output.png'));
spriteData.pipe('css', gulp.dest('output.css'));
```

Alternatively, I can use a library like `mux-demux` or output a JSON stream which the end user would have to listen to keys on. I dislike those options since they require more knowledge on the end-user's part.

Reference links:

https://github.com/Ensighten/spritesmith

// Open issue to create gulp plugin
https://github.com/Ensighten/spritesmith/issues/32

https://github.com/dominictarr/mux-demux

https://github.com/Ensighten/grunt-spritesmith

**Comment by cecilemuller** [comment]
If someone else stumbles here looking for *how to make a gulp plugin output multiple files from a single file*, you can [use modules "through2" and "vinyl" to push multiple files](https://gist.github.com/cecilemuller/40880002c340edaa7e4a).

**Comment by twolfson** [comment]
Fwiw, `gulp.spritesmith` now supports outputting as both a single stream and multiple streams:

https://github.com/twolfson/gulp.spritesmith/tree/2.5.0#getting-started

**Comment by andykov** [comment]
Hello. How to generate multiple files sprites?
