### ISSUE TITLE
Fail to install gulp-cli on Windows 10

### ISSUE THREAD

**Issue by webmasterpf** [gulpjs/gulp#2431]
**What were you expecting to happen?** Install gulp-cli

**What actually happened?** 
npm ERR! ELOOP: too many symbolic links encountered, stat 

**What version of gulp are you using?** v 3.0.9

**What versions of npm and node are you using?**
$ node -v v8.17.0  $ npm -v 6.13.4
 idem with node 10 or 12.

Npm doesn't find the path to my W10 profile
What can I do to get this working ? The goal is to compile SCSS files with gulpfile.

Thanks

**Comment by phated** [comment]
This seems like an environment error. If you are having trouble installing things with npm, you should look into that.

**Comment by webmasterpf** [comment]
After editing the environment variable (PATH) it work better but I get multiple issues with npm modules. Sass compilation only works with VS Code actually.
