### ISSUE TITLE
 Gulp 4.0.2 has 2 new low security vulnerabilities

### ISSUE THREAD

**Issue by MassivDash** [gulpjs/gulp#2441]
Gulp 4.0.2 has 2 new low-security vulnerabilities

Low: Prototype pollution  
gulp > glob-watcher > chokidar > fsevents > node-pre-gyp >  mkdirp > minimist 

Low: Prototype pollution 
gulp > gulp-cli > yargs > yargs-parser

**Comment by phated** [comment]
We no longer accept reports like this.

**Comment by darvanen** [comment]
Time for me to find a replacement for Gulp 🧐
