### ISSUE TITLE
Use es 6 with gulp 4 when gulpfile.babel.js not in root folder

### ISSUE THREAD

**Issue by aboutjquery** [gulpjs/gulp#2446]
When i change gulpfile.js to gulpfile.babel.js its work great.

But when gulpfile.babel.js in subfolder, like

```
package.json
gulp/gulpfile.babel.js
src/
dist/
```

Then its not working anymore, how can i keep the folder structure and make it working? Thanks.

**Comment by phated** [comment]
Please follow our issue template.

**Comment by Slapbox** [comment]
Same issue: https://github.com/gulpjs/gulp/issues/2619
