### ISSUE TITLE
primordials not defined fs / node 12

### ISSUE THREAD

**Issue by Cyanic76** [gulpjs/gulp#2450]
### What were you expecting to happen?
Expecting `fs` to make something useful

### What actually happened?
An error appeared

### Please give us a sample of your gulpfile
The script not working is [here](https://cyanic-haste.glitch.me/aab6782f.txt).

### Terminal output / screenshots

```sh
fs.js:27
const { Math, Object, Reflect } = primordials;

                                  ^

ReferenceError: primordials is not defined
```
The entire error is [here](https://cyanic-haste.glitch.me/aab39ce2.txt).
This error prevents my Discord.js bot from starting.

### Please provide the following information:
* node version : 12
* npm version : 6.9.0
* gulp version : 4.0.2

### Additional information
None

**Comment by phated** [comment]
The linked script and error don't include gulp at all. I'm not sure how this issue relates to gulp at all.

**Comment by FELS-Malkiat** [comment]
Hi Check this repo 

https://github.com/FELS-Malkiat/gulp/tree/fix-oldIssue
