### ISSUE TITLE
Support gulpfile.mjs

### ISSUE THREAD

**Issue by ngdangtu-vn** [gulpjs/gulp#2480]
Before you open this issue, please complete the following tasks:   
None of those template tasks is for my case, so I cleared them all.

## Our thoughts on feature requests
> Lots of developers rely on gulp, so we don't make big changes very often. Not every feature request will be added to gulp, but hearing about what you want is important. Don't be afraid to submit a feature request!

Mime is not exactly feature request, it is more a like a small improvement.

### Describe your idea for a new feature
Cite from [JavaScript and Gulpfiles](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#transpilation)
> When only that syntax (import/export) is desired, rename to gulpfile.esm.js and install the esm module.

This is a great option indeed. But for anyone uses the latest version of Node, we can add one more option. It is `gulpfile.mjs`. Gulp only has to scan for name file and then we are ready to use. No additional dependency required.

(Currently, I still use `gulpfile.esm.js` with package option `"type": "module"`. It's good but a little bit improvement would be appreacited)

### Explain the problem your idea is trying to solve
None

### How will it benefit gulp and its users?
Keep the file name short, sweet.

### If this feature could exist outside of gulp (like as a plugin or a module), would you be interested in helping to create and maintain it?
It's not a feature, it is just a small improvement.

**Comment by phated** [comment]
@ngdangtu-vn This is already supported. You didn't use the search function, so please actually follow the tasks instead of deleting them. If you had, you would have found this: https://github.com/gulpjs/gulp/issues/2445#issuecomment-638528534
