### ISSUE TITLE
Translating the docs to Portuguese (PT-BR)

### ISSUE THREAD

**Issue by sidneifjr** [gulpjs/gulp#2481]
I'm from Brazil. A decent chunk of colleagues have a hard time reading the current docs because of the language barrier, so i want to help.

I'll work on it and make a pull request when it's done, however I'd like to have some feedback.

**Comment by entrywayaudibly** [comment]
Hey, @sidneifjr!

I am currently maintainer of Boostrap Brasil and I was wondering if there's anything I can help you with.

**Comment by stearruda** [comment]
Hi @sidneifjr !

How's the progress of this issue? Anything in need to be done?

**Comment by entrywayaudibly** [comment]
Soon, I'll be making some PRs. I hope you don't mind...

**Comment by stearruda** [comment]
Not at all, @sidneifjr !
I'll have a look.

**Comment by sidneifjr** [comment]
Hi, @entrywayaudibly and @stearruda! Apologies for the delay.

Yes, I'd like some support regarding mostly foolproofing; however, I wouldn't mind translating some sections that are not worked on yet.

**Comment by entrywayaudibly** [comment]
I'll be pushing commits on sidnei's fork.

**Comment by sidneifjr** [comment]
@entrywayaudibly and @stearruda,

Progress and changes are available in the **project board** tab.

**Comment by lancaluis** [comment]
Hey, @sidneifjr I'd like to help the community as well!

**Comment by phated** [comment]
Further work and discussion should happen based on #2692
