### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by aflinchb** [gulpjs/gulp#2500]
With gulp@4.0.2, there are the following npm warnings calling out dependencies of deprecated packages:

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

I understand that some of this is dependent on the other repos in the dependency tree to update their packages, but wanted to put this on your radar. 

Here are the dependency trees:
└─┬ gulp@4.0.2
  └─┬ glob-watcher@5.0.5
    └─┬ anymatch@2.0.0
      └─┬ micromatch@3.1.10
        └─┬ snapdragon@0.8.2
          └─┬ source-map-resolve@0.5.3
            └── resolve-url@0.2.1 

└─┬ gulp@4.0.2
  └─┬ glob-watcher@5.0.5
    └─┬ anymatch@2.0.0
      └─┬ micromatch@3.1.10
        └─┬ snapdragon@0.8.2
          └─┬ source-map-resolve@0.5.3
            └── urix@0.1.0 

fsevents:
├─┬ gulp@4.0.2
│ └─┬ glob-watcher@5.0.5
│   └─┬ chokidar@2.1.8

**Comment by phated** [comment]
Read the issue templates.
