### ISSUE TITLE
gulp --tasks-simple command never finishes

### ISSUE THREAD

**Issue by birgersp** [gulpjs/gulp#2522]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
`.\node_modules\.bin\gulp.cmd --tasks-simple` should finish.

### What actually happened?
The command never finishes

### Please give us a sample of your gulpfile
```js
// gulpfile.js
var gulp = require("gulp");
var htmlGlob = ["src/index.html", "./favicon.ico"];
gulp.watch(htmlGlob, () => {}) // <-- This line makes "Fetching build tasks" never complete
```

### Terminal output / screenshots
```
PS C:\Users\birger.pedersen\test\ts> .\node_modules\.bin\gulp.cmd --tasks-simple

```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: Windows 10
* node version (run `node -v`): v14.0.0
* npm version (run `npm -v`): 6.14.4
* gulp version (run `gulp -v`):  CLI version: 2.3.0, Local version: 4.0.2

### Additional information
How to reproduce:
1. Open powershell or cmd
2. `cd` to some folder
3. Run `npm i gulp`
4. Create this file
```js
// gulpfile.js
var gulp = require("gulp");
var htmlGlob = ["src/index.html", "./favicon.ico"];
gulp.watch(htmlGlob, () => {}) // <-- This line makes "Fetching build tasks" never complete
```
5. Run `.\node_modules\.bin\gulp.cmd --tasks-simple`

Because of this bug, VSCode never completes fetching build tasks in my project.

**Comment by phated** [comment]
Of course it doesn't complete, you have a watcher running and holding the process open. That's why watchers need to either be in conditionals or inside a task.

**Comment by birgersp** [comment]
Thanks for your help
