### ISSUE TITLE
When a gulp.task only has a single child gulp.task, the child is not logged when run.

### ISSUE THREAD

**Issue by mattpr** [gulpjs/gulp#2548]
Gulp version 4.0.2

`gulp.task('html', gulp.task('html:pug'));`

Running `gulp html` results in:

```
[14:37:39] Starting 'html'...
[14:37:40] Finished 'html' after 1.58 s
```

`gulp.task('html', gulp.series('html:pug'));`

Running `gulp html` results in:

```
[14:37:54] Starting 'html'...
[14:37:54] Starting 'html:pug'...
[14:37:56] Finished 'html:pug' after 1.57 s
[14:37:56] Finished 'html' after 1.57 s
```

This is especially confusing in live-reload development scenarios because a user may change a file (e.g. a pug file in this example) and not see the result they were expecting in the browser.  When looking at the terminal running their development server (for instance with a `watch:html` task that runs `gulp.task('html:pug')`... they will not see any console output and may think that gulp is not running the expected task (`html:pug`) and spend time tracking down a gulp build problem that doesn't exist.

| gulp config | result |
|-----|--------|
| `gulp.task('html', gulp.task('html:pug'));` | `html:pug` task NOT logged when `html` task is run |
| `gulp.watch([...], gulp.task('html:pug'));` | `html:pug` task NOT logged when run by watcher |
| `gulp.task('html', gulp.series('html:pug'));` | `html:pug` task IS logged when `html` task is run |
| `gulp.watch([...], gulp.series('html:pug'));` | `html:pug` task IS logged when run by watcher |

I can't imagine a good reason that this would be intended behaviour other than an assumption that logging is overly noisy if you log a task when it only has a single child task.  The problem comes up in particular with a watch task because you won't get any output even though a task is being run.  In a normal build you see html and okay...maybe you have to assume that all tasks under html are indeed being run...and if you don't see any sub-tasks there must only be one subtask.

I'd rather have a little more verbosity and less confusion than having confusion for the sake of brevity.

I wasted 30 minutes trying to figure out what was wrong with my gulpfile and googling "gulp task not being logged even though it is running" type things without finding any clear answer on this...but perhaps there is a really good reason for this I am missing.

**Comment by phated** [comment]
Pulling a file out of the task registry just returns the function. This pattern is an anti-pattern in gulp 4 where you should just be using `series`/`parallel` to compose tasks and named functions for your tasks (that are exported to expose them to the task system).

**Comment by mattpr** [comment]
> This pattern is an anti-pattern in gulp 4

Thanks for the reply.  I didn't pay attention to the changes in gulp 4 and some of this source was inherited.  I'll go re-read the api docs and make sure I am up to speed on the current api best practices.  Appreciate you taking the time to push me in the right direction about the underlying issue.
