### ISSUE TITLE
How do I prepend a stream to another?

### ISSUE THREAD

**Issue by wyuenho** [gulpjs/gulp#255]
Hi!

I'm still getting used to gulp's processing model and it's not entirely clear to me how to achieve something like this:

```
src1 | filter concat src2 | filter > output
```

The [recipe here](https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md) results in an unordered stream, but I'd like concat to be really concat and not just merge chucks arbitrarily.

Thanks!

**Comment by chrismarx** [comment]
+1 for objectMode, that's critical!
