### ISSUE TITLE
Update Custom Registries example code

### ISSUE THREAD

**Issue by jeanbmar** [gulpjs/gulp#2561]
Task functions medata are lost when using ``fn.bind`` as in:
```
ConfigRegistry.prototype.set = function set(name, fn) {
  // The `DefaultRegistry` uses `this._tasks` for storage.
  var task = this._tasks[name] = fn.bind(this.config);
  return task;
};
```

Updating the example with the following would preserve metadata:
```
ConfigRegistry.prototype.set = function set(name, fn) {
  // The `DefaultRegistry` uses `this._tasks` for storage.
  var task = this._tasks[name] = Object.assign(fn.bind(this.config), fn);
  return task;
};
```

It's not a big deal but it would definitely save some times to devs wondering why metadata aren't displaying suddenly :).

**Comment by phated** [comment]
Good catch! Would you like to send a PR for this, I can get it merged and released on the website.

**Comment by jeanbmar** [comment]
PR https://github.com/gulpjs/gulp/pull/2565 sent!

**Comment by phated** [comment]
Thanks again!
