### ISSUE TITLE
Task never defined: [object Object]

### ISSUE THREAD

**Issue by K4rakara** [gulpjs/gulp#2563]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?

Based on the screenshot used on Gulps website (under "Composable"), I would have assumed that parallel would let you pass in tasks, not just functions. That way, you could have multiple tasks run in parallel. Perhaps I'm not using Gulp as intended, but I feel like this would be a nice idiomatic feature.

### What actually happened?

This actually works, given my example gulpfile, but will fail if its all in a single gulp.task.

### Please give us a sample of your gulpfile

The following gulpfile **works** but it throws errors in the console, despite the build finishing just fine:

```js
const gulp = require("gulp");
const { dest, parallel, src } = gulp;

const rename = require("gulp-rename");
const terser = require("gulp-terser");
const ts = require("gulp-typescript");

gulp.task("build", () => {
  const _ = src("./src/**/*.ts")
    .pipe(ts({
      target: "es2020",
      declaration: false,
      moduleResolution: "node",
      rootDir: "./src/",
    }));
  return parallel(
    _.js.pipe(dest("bin")),
    _.js
      .pipe(terser({ compress: true, mangle: true, toplevel: true }))
      .pipe(rename({ extname: ".min.js" }))
      .pipe(dest("bin")),
  );
});

gulp.task("default", () => parallel("build")());
```

### Terminal output / screenshots

```sh
$ gulp
[11:57:46] Using gulpfile /tmp/gulp-repo/gulpfile.js
[11:57:46] Starting 'default'...
[11:57:46] Starting 'build'...
[11:57:46] 'build' errored after 10 ms
[11:57:46] AssertionError [ERR_ASSERTION]: Task never defined: [object Object]
    at getFunction (/tmp/gulp-repo/node_modules/undertaker/lib/helpers/normalizeArgs.js:21:9)
    at map (/tmp/gulp-repo/node_modules/arr-map/index.js:20:14)
    at normalizeArgs (/tmp/gulp-repo/node_modules/undertaker/lib/helpers/normalizeArgs.js:30:10)
    at Gulp.parallel (/tmp/gulp-repo/node_modules/undertaker/lib/parallel.js:13:14)
    at /tmp/gulp-repo/gulpfile.js:16:10
    at build (/tmp/gulp-repo/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:416:15)
    at runBound (node:domain:427:12)
    at asyncRunner (/tmp/gulp-repo/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
```

### Please provide the following information:
* OS & version: Arch Linux, Linux 5.11 
* node version (run `node -v`): v15.12.0
* npm version (run `npm -v`): v7.7.6
* gulp version (run `gulp -v`): v2.3.0

### Additional information

I took a look at where this error originated from in `node_modules`, and it looks to be coming from `undertaker/lib/helpers/normalizeArgs.js`, where on line 11, it checks if task is a function, and if it is, returns it, or attempts to get the task from the registry. However, because this is loosley typed, it gets cohersed to the string, `[object Object]`.

**Comment by phated** [comment]
@K4rakara I think your interpretation of "tasks" is incorrect. A "task" in gulp is just a function. In your example, you are creating a stream and then trying to pass that stream into the `parallel` method, which only operates on functions (or "tasks").

In the nodejs ecosystem, there are tons of utilities for orchestrating your streams, so that's not something we are going to support.
