### ISSUE TITLE
Assertion failed on coroutine.cc with node 16

### ISSUE THREAD

**Issue by GregOriol** [gulpjs/gulp#2570]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?

I'm trying to run gulp; it worked with node 15 but doesn't anymore after an update to node 16.

### What actually happened?

```
$ gulp
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
Abort trap: 6
```

### Please give us a sample of your gulpfile
The gulpfile has a few exports (watch, clean, prod, ...) and all of them produce this error.

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: Mac OS Catalina 10.15.7
* node version (run `node -v`): v16.0.0 (installed via homebrew)
* npm version (run `npm -v`): 7.10.0
* gulp version (run `gulp -v`): CLI version: 2.3.0 - Local version: 4.0.2

**Comment by contra** [comment]
@GregOriol You have a native module somewhere - you probably just need to run `npm rebuild`. Any time you update node your native extensions in all of your projects will be built against the wrong version, and you will need to rebuild them via that command.

**Comment by GregOriol** [comment]
@contra Thanks for your feedback, but sadly it didn't work to do an npm rebuild:
```
$ npm rebuild
rebuilt dependencies successfully
$ gulp clean
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
Abort trap: 6
```
