### ISSUE TITLE
Could not find a declaration file

### ISSUE THREAD

**Issue by hold-baby** [gulpjs/gulp#2580]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
gulp start with typescript
### What actually happened?
Could not find a declaration file in gulp process
### Please give us a sample of your gulpfile

package.json
```json
"devDependencies": {
  "@types/gulp": "^4.0.8",
  "@types/node": "^15.6.1",
  "gulp": "^4.0.2",
  "gulp-typescript": "^6.0.0-alpha.1",
  "lodash": "^4.17.21",
  "ts-node": "^10.0.0",
  "typescript": "^4.3.2"
}
```
tsconfig.json
```json
"paths": {
   "*": ["__types__/*"]
 }  
```
`__types__/index.d.ts`
```ts
declare module "lodash";
```
gulpfile.ts
```js
import { series } from "gulp"
import _ from "lodash"

const test = () => {
  console.log("test", _)
}

export const start = series(test)
```

### Terminal output / screenshots

```sh
$ gulp start

gulpfile.ts:2:15 - error TS7016: Could not find a declaration file for module 'lodash'. '/Users/hold-baby/personal/gulp-quick-start/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

2 import _ from "lodash"
                ~~~~~~~~

error Command failed with exit code 1.
```

### Please provide the following information:
* OS & version :MacOS Big sur 11.2.1
* node version : v12.22.0
* npm version : 6.14.11
* gulp version : CLI version: 2.3.0 Local version: 4.0.2

### Additional information

no `@types/lodash` just for example

**Comment by phated** [comment]
I'm pretty sure you aren't supposed to specify `paths` otherwise typescript doesn't know how to look up the `@types/*` packages in node modules.
