### ISSUE TITLE
Npm error in push commits

### ISSUE THREAD

**Issue by curious-33** [gulpjs/gulp#2585]
Before you open this issue, please complete the following tasks:

* [✓] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [✓] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).

### What were you expecting to happen?
![image](https://user-images.githubusercontent.com/71032772/121481875-ffb9ea00-c9e5-11eb-865f-01c2adcd5667.png)

npm error

### What actually happened?
When i push my commits with standard-version, i'm facing this npm error every time. 

### Please provide the following information:
* OS & version: Windows 10 Pro 20H2
* node version: v14.17.0
* npm version: 6.14.13
* gulp version: CLI version: 2.3.0; Local version: 4.0.2

**Comment by curious-33** [comment]
Why did you guys close this issue?

**Comment by phated** [comment]
This is not an issue. You are not a publisher on gulp.
