### ISSUE TITLE
Watch stops on errors (Figure out better error handling)

### ISSUE THREAD

**Issue by yocontra** [gulpjs/gulp#259]
This is spread around 10 issues on all sorts of projects. I'm consolidating them all here.

**Comment by lokeshjainRL** [comment]
I faced the same problem.

omitting return in the task solves my problem.

```javascript

//code works
gulp.task('asset:uglify',function(){
	gulp.src('js/*js')
		.pipe(uglify())
		.on('error',console.log.bind(console)) //Error handling and 
		.pipe(gulp.dest('public/'));
});

// code that doesn't works

gulp.task('asset:uglify',function(){
	return gulp.src('js/*js')
		.pipe(uglify())
		.on('error',console.log.bind(console)) //Error handling and 
		.pipe(gulp.dest('public/'));
});


```

**Comment by Karl-Gustav** [comment]
@lokeshjainRL the problem you'll have with the code that works is that that doesn't pass along the pipe, and you'll not be able to tell when the task is finished, so you'll not be able to depend on that task because tasks that depend on that task will start as soon as this task is started. And the fact that you're not passing along the pipe is probably the reason why it doesn't break the watch-task on error.

**Comment by lokeshjainRL** [comment]
@Karl-Gustav :+1:  that is a great info. thanks.

**Comment by jamiehutber** [comment]
Just to add to this I do still get errors and it blocks and finishes.

```javascript
***HandleErrors Feil**
var notify = require("gulp-notify");

module.exports = function() {

  var args = Array.prototype.slice.call(arguments);

  // Send error to notification center with gulp-notify
  notify.onError({
    title: "Compile Error",
    message: "<%= error.message %>"
  }).apply(this, args);

  // Keep gulp from hanging on this task
  this.emit('end');
};

***gulp task**
gulp.task('sass', function() {
  return gulp.src(amazon)
    .pipe(changed(DEST, { extension: '.css' }))
	.pipe(plumber({
		errorHandler: handleErrors
	}))
	.pipe(sourcemaps.init())
    .pipe(sass({}))
	.pipe(sourcemaps.write('./'))
	.on('error', handleErrors)
    .pipe(gulp.dest(DEST))
});

```

I've tried all fixes and also removed everything but the sass() with errors and dest but no luck.

**Comment by robfe** [comment]
I've been using this as a general solution. The advantage is that non-watch tasks which don't depend on this keep behaving normally.

```
// Watch tasks should depend on suppress-errors - it will force all stream pipes to print but not crash on error
gulp.task('suppress-errors', function(){
	function monkeyPatchPipe(o){
		while(!o.hasOwnProperty('pipe')){
			o = Object.getPrototypeOf(o);
			if(!o){
				return;
			}
		}
		var originalPipe = o.pipe;
		var newPipe = function(){
			var result = originalPipe.apply(this, arguments);

			if(!result.pipe['monkey patched for suppress-errors']){
				monkeyPatchPipe(result);
			}

			return result.on('error', function (err) {
				gutil.log(gutil.colors.yellow(err));
				gutil.beep();
				this.emit('end');
			});
		};
		newPipe['monkey patched for suppress-errors'] = true;
		o.pipe = newPipe;
	}
	monkeyPatchPipe(gulp.src(""));
});
```

**Comment by callmecavs** [comment]
@jamiehutber you ever find a solution to your problem? I'm running into the same problem - using plumber with an error handler i have defined/exported from a different file. played around with using `bind` in different places to see if it was a context issue, but couldn't get anything working

**Comment by yairEO** [comment]
@robfe - how do you use it? and how is passing `gulp.src("")` to the `monkeyPatchPipe` does anything at all

**Comment by TrySound** [comment]
@yairEO I'm just use
```
gulp.task('name', function (done) {
  return gulp.src('')
    .pipe(plugin())
    .on('error', done)
    .pipe(plugin()) // The last pipe will be catched by gulp.
});
```

**Comment by callumacrae** [comment]
Isn't @robfe's solution basically what [gulp-plumber](https://www.npmjs.com/package/gulp-plumber) does?

**Comment by TrySound** [comment]
@callmecavs Yup. And it has the same problem with CI

**Comment by just-boris** [comment]
I am using the simple snippet to deliver caught errors in stream but deliver them for gulp: https://gist.github.com/just-boris/89ee7c1829e87e2db04c

It allow to keep `watch` working on errors and report failures into CI

**Comment by westonganger** [comment]
+1 for installing gulp-plumber

**Comment by tomsun** [comment]
I'm using a variant of https://github.com/gulpjs/gulp/issues/259#issuecomment-63297076 as a workaround

before
```
gulp.task('watch', ['default'], function() {
  return gulp.watch(['src/**/*'], function() {
    return gulp.start('default');
  });
});
```

after
```
gulp.task('watch-runner', function() {
  return gulp.watch(['src/**/*'], function() {
    return gulp.start('default');
  });
});
gulp.task('watch', ['default'], function() {
  (function spawnWatch() {
    require('child_process').spawn('gulp', ['watch-runner'], {stdio: 'inherit'}).on('close', spawnWatch);
  })();
});
```

**Comment by TrySound** [comment]
@tomsun Too difficult

**Comment by tomsun** [comment]
@TrySound As an interface for gulp: "too difficult indeed" :-)

As a workaround if gulp doesn't behave right now (case: closed etc): "works for me"...
Should earn one simplicity point or two from the fact that you don't have to mess with the error handling of individual tasks. An external actor for the watcher is less fun, but even simpler - for example in `package.json`, implementing `npm run-script watch` as:
```
 "scripts": {
   "watch": "while true ; do gulp watch ; done"
}
```

**Comment by TrySound** [comment]
@tomsun Everything works fine
https://github.com/TrySound/case/blob/master/gulpfile.js#L88

**Comment by babbelnedd** [comment]
@TrySound not working for me

**Comment by TrySound** [comment]
@babbelnedd What error?

**Comment by phillip-haydon** [comment]
This was raised a year ago and it's still broken?

**Comment by TrySound** [comment]
@phillip-haydon gulp3 won't be fixed. Wait gulp4 release or use it from repo,

**Comment by joepie91** [comment]
For what it's worth, [this implementation](https://git.cryto.net/joepie91/node-gulp-partial-logger/src/18b90fcb629ba21d17885da5fc657f43f9ecd8a4/src/index.js#L16-L28) works well in my build pipeline. It works correctly with a `combined-stream2` Duplex stream, and doesn't break watchers either.

**Comment by yairEO** [comment]
Any new workaround? 
I am using Rollup (without gulp plugin) inside a gulp task and it's not a stream that I can simply do 
`.on('error', function(err){ ... });`
and be done with it, but the error stops gulp-watch completely..

**Comment by maxkoryukov** [comment]
still breaking without `this.emit('end');`

the @mrienstra's advice from this [comment](https://github.com/gulpjs/gulp/issues/259#issuecomment-40392451) helps me

[the original answer on **stackoverflow**](http://stackoverflow.com/a/21678601/1115187)

**Comment by niftylettuce** [comment]
thanks @mikestreety for the `this.emit('end')` bit!  worked for me.

**Comment by GuyMograbi** [comment]
I just followed this thread. 
Not sure if I am missing something. 

Do I have to choose between "stopping watch on error" and "never fail"

If I implement the 'handleError' - it never fails.. even when it should. 
If I don't it stops the process on error. 

Or is there a solution to enjoy both worlds?

**Comment by ErEllison** [comment]
if you some one uses sass fot gulp plugin ('gulp-sass') and faces with this issue what you need to do is just add an on error event listener to your sass task like this 
```
var sass = require('gulp-sass')

.
.
.

// Compile Sass Files
gulp.task('sass' , () => {
  gulp.src('src/sass/**/*.scss')
    .pipe(wait(250))
    .pipe(sass().on('error' , sass.logError)) // this line here
    .pipe(gulp.dest(BUILD_FOLDER + 'css'))
    .pipe(browserSync.stream())
})
```

this will prevent from killing server when ever you made a mistake on variables names or things like that ...
hope it helps some one
