### ISSUE TITLE
Use Dependabot to keep dependencies updated

### ISSUE THREAD

**Issue by stefanobartoletti** [gulpjs/gulp#2594]
I think it would be useful to add Dependabot to the repository, it helps to keep dependencies updated and it is really easy to setup.

**Comment by phated** [comment]
No

**Comment by stefanobartoletti** [comment]
Thank you for your reply. Is there a reason for not wanting to do it?

I'm available to help for the setup if needed

**Comment by phated** [comment]
It's a bad tool and doesn't take into account our nodejs support matrix.
