### ISSUE TITLE
Unresolvable problems in dependencies

### ISSUE THREAD

**Issue by Choppel** [gulpjs/gulp#2617]
The current version (4.0.2) throws dependency errors when installing and mutliple "npm audit fix --force" calls do not resolve them.

How to reproduce:
````
mkdir test
cd test
npm init
npm i --save-dev gulp
````
This installs gulp@4.0.2 and prints some dependency problems.

````
npm audit fix --force
````
will install gulp@3.9.1 and prints different dependency problems.

Another
````
npm audit fix --force
````
installs gulp@4.0.2 again and so on....

**Comment by phated** [comment]
https://overreacted.io/npm-audit-broken-by-design/
