### ISSUE TITLE
Make gulp workable into Yarn's PnP mode

### ISSUE THREAD

**Issue by bhanubais** [gulpjs/gulp#2621]
Now yarn reached at it's version 3.0.0 and gulp reached at 4.0.2
But gulp is still not working in yarn's default PnP (plug and play) mode.

To run gulp in yarn we have to change yarn's mode from `pnp` to `node-modules` as follow.

1. insert `nodeLinker: node-modules` into `.yarnrc.yml` file.
2. run `yarn install`
3. now you can run gulp.

But we lost plug and play feature of yarn and almost every package placed in two places one copy into `.yarn` folder and another one into `node_modules` folder.

There is no doubt that yarn did a great job to make dependencies neat and clean. It's also very fast compare to npm.
But an excited user can't just install latest NodeJs, Yarn, Gulp and hope gulp will run. Because by default Yarn run on PnP mode.

In the current scenario, we have to install package into `.yarn` as well as into `node_modules` to run gulp command. If `gulp` will agree upon to run on PnP mode we don't need to waste double storage.

**Comment by phated** [comment]
In https://github.com/yarnpkg/berry/pull/3318 - yarn seems to claim that pnp support exists for gulp 4, so I'm going to close this.
