### ISSUE TITLE
ReferenceError: primordials is not defined at fs.js:51:5 in Node v15.7.0

### ISSUE THREAD

**Issue by mohankumar91** [gulpjs/gulp#2625]
I have installed Node version v15.7.0. 

>gulp -v
CLI version: 2.3.0
Local version: 4.0.2
> 
> 
> 
> ReferenceError: primordials is not defined
>     at fs.js:51:5
>     at req_ (D:\mohan\node_modules\natives\index.js:143:24)
>     at Object.req [as require] (D:\mohan\node_modules\natives\index.js:55:10)
>     at Object.<anonymous> (D:\mohan\node_modules\node_modules\graceful-fs\fs.js:1:37)
>     at Module._compile (node:internal/modules/cjs/loader:1108:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
>     at Module.load (node:internal/modules/cjs/loader:973:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at Module.require (node:internal/modules/cjs/loader:997:19)
>     at require (node:internal/modules/cjs/helpers:92:18)

**Comment by phated** [comment]
We don't support node 15, it's an unstable release. I have no idea if graceful-fs works with 16

**Comment by starwed** [comment]
I hit exactly this error on node `14.7.6`
