### ISSUE TITLE
Package Update Request

### ISSUE THREAD

**Issue by theimo1221** [gulpjs/gulp#2631]
As my PR was locked immediately...

>https://overreacted.io/npm-audit-broken-by-design/

_Originally posted by @phated in https://github.com/gulpjs/gulp/issues/2630#issuecomment-922384988_

While I agree on npm audit beeing flawed, other tools like dependabot security alert report it too.

Additionally -unlesss bypassed by aliasing or specifically defining a version- this can prevent other dependencies of using a newer version.

So while gulp itself isn't used during production, it still prevents using a newer version of it's own or subsequent dependencies.

**Comment by phated** [comment]
This isn't a discussion.

**Comment by theimo1221** [comment]
Moved to discussion
