### ISSUE TITLE
`dest()` cannot accept function callback despite having an override showing it can

### ISSUE THREAD

**Issue by paul-uz** [gulpjs/gulp#2646]
Whilst I using the newer version of Gulp, which no longer uses `gulp.dest()` - I have seen people using `gulp.dest()` with a function to get the path so it can be modified.

However, it seems that is no longer possible, despite there being an override for it in the Vinyl FS package https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vinyl-fs/index.d.ts#L176

**Comment by phated** [comment]
The DefinitelyTyped definitions are not official, nor maintained by the gulp team. Our docs and javascript source code are the official implementation and they can take a function.

**Comment by paul-uz** [comment]
@phated funny, because I cannot find any information here, or on the gulp site, about `dest()` acepting a function.

How does it work exactly?

This code:

```javascript
function foo() {
  return src('/foo/*')
  .pipe(dest(function(a) {
    console.log(a);
    return 'bar';
  }));
}
```

Does nothing. No console log is output, no files are moved.

**Comment by paul-uz** [comment]
@phated How does it work exactly? Are you able to provide proper types in this library so people like me don't see those confusing messages?
