### ISSUE TITLE
Add note about node >14 in gulp.watch documentation

### ISSUE THREAD

**Issue by nicolashenry** [gulpjs/gulp#2654]
### Describe your idea for a new feature

Just add a small warning here https://gulpjs.com/docs/en/getting-started/watching-files about NodeJS version about Gulp not supporting NodeJS >= 14 for watching files. 

### Explain the problem your idea is trying to solve

I have multiple co-workers wanting to use this gulp feature and they are all missing the fact that this is not compatible with current LTS versions of NodeJS. So it could help to prevent users that this feature is not available for recent versions of NodeJS.

### How will it benefit gulp and its users?

I think it will help users to not have to search in closed issues or discussions to have this information. I think this is reasonable since Gulp seems not going to be updated soon.

**Comment by anubajaj23** [comment]
Hi @nicolashenry, 

We are planning to migrate from node 10 to node 16, Is this statement true that i gulp.watch is not supported in node > 14 ?

Actually my changing are not getting reflected in browser even with node 13, Can you please help me on this ?

**Comment by nicolashenry** [comment]
@anubajaj23 gulp.watch is using an old and deprecated version of chokidar but kept for compatibility with old node versions.
I chose to use directly [chokidar](https://www.npmjs.com/package/chokidar) with the latest version instead of using gulp.watch.

**Comment by Adstokoe19** [comment]
@phated Do you know when gulp 4 will use the latest version of chokidar?

**Comment by jpike88** [comment]
> gulp.watch is using an old and deprecated version of chokidar but kept for compatibility with old node versions

Seems like it's time to just push to a new major version, node 16 is considered stable so why not target it?

Also looks like last commit was 9 months ago... is this library maintained anymore?

**Comment by phated** [comment]
@jpike88 kindly buzz off if you don't understand how semver and dependencies work. We're actively working on the required changes for v5.

**Comment by Atulin** [comment]
> @phated Do you know when gulp 4 will use the latest version of chokidar?

Sometime around ¯\\\_(ツ)\_/¯ I believe. Take a look at how many of the closed issues are about some dependencies being outdated. And how many years ago they started appearing.

**Comment by Alexander-Taran** [comment]
With npm version 8+ one can add [overrides section](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to package.json 
```json
  "overrides":{
    "chokidar":"^3.0.0",
    "glob-stream":"^7.0.0",
    "glob-parent":"^6.0.0",
    "micromatch":"^4.0.0"
  },
```

Which resolves the issue for me.
Also one can fight vulnerable packages presence in package.lock.json

**Comment by prurigro** [comment]
I'm always using the latest version of node (currently 18.3.0) and haven't had issues with gulp watching files... I did find I needed to declare individually watched files in a weird way however, and maybe that's a result of the node 14+ issue? On the chance that this is the case, this is what I had to do:

* For a single file like `resources/js/app.js` the watch call looks like `gulp.watch("resources/js/**/app.js"` (the downside is that this will catch every file named `app.js` at that directory or deeper)
* For any files at a directory level or deeper, follow the same logic (this is how you'd want to declare that anyway): `app/**/*.php`

If you want to test and see it working without setting a project up you can check out my website bootstrap template here: https://github.com/prurigro/hypothetical

**Comment by prurigro** [comment]
@Alexander-Taran That's a good point as I do use linux. That said, I just checked with my coworker who uses macos and he says gulp watch is working correctly for him with my template.

**Comment by rossb89** [comment]
On a project (with multiple themes) i've been working on, i'm using node v14.19.0 (MacOS) and my gulp watch appears to be working fine 👀

We have an object of theme name + path, and have this inside of a loop looping over each theme to set the watch tasks (yes, it's a bit nasty).

```
themes.forEach(function(theme) {
  gulp.task(`watch:sass:${theme.name}`, gulp.series(`compile:sass:${theme.name}:watch`, function() {
    var watchList = [
      `${theme.path}/sass/**/*.scss`,
    ];
    return gulp.watch(watchList, gulp.series(`compile:sass:${theme.name}:watch`));
  }));
});
```

So it does appear to work in some use cases?

**Comment by prurigro** [comment]
I notice you're also using the `/**/*` syntax, I wonder if that's all there is to it?

**Comment by xtracoder** [comment]
It would be nice if gulp maintainers release newer version with just dependecies for chokidar push to compatible with modern versions of nodejs. 

Today I've lost few hours while trying to identify why `watch` is not working. The solution is simple - override dependencies, what is avabile since NPM v8.3.0 + (2021-12-09), but I would not need it and would not lose my precious time for fixing that dummy thing :(

Here is the overrides section for package.json:
 
  "overrides": {
    "gulp": {
      "glob-watcher": "^5.0.5"
    },
    "glob-watcher": {
      "anymatch": "^3.1.3",
      "async-done": "^2.0.0",
      "chokidar": "^3.5.3"
    }
  },

**Comment by jonathanafranio** [comment]
Do like me, use nvm.
Here's an article explaining how it works, in Portuguese (my native language): https://fabiojanio.medium.com/nvm-gerencie-m%C3%BAltiplas-instala%C3%A7%C3%B5es-do-node-js-6fcd0f13aaf7
in English: https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/
