### ISSUE TITLE
Update gulp-cli dependency to 2.3.0

### ISSUE THREAD

**Issue by jens-t** [gulpjs/gulp#2655]
In my project i have explicitly added gulp-cli 2.3.0 as a dependency. But when using `npx gulp` the gulp-cli package with the version 2.2.0 is used instead. As the gulp package comes with the gulp-cli 2.2.0 dependency.

I worked arround this problem with the npm-force-resolutions package. I would like to drop this workaround.

I thought this would be changed in a new minor version update soon, but almost a year later it's not.
Is there a good reason why the gulp-cli dependency isn't updated to version 2.3.0 yet, inside the gulp package? (for es module support)

Thanks for the info!

**Comment by phated** [comment]
This is a problem with your lockfile, not gulp.
