### ISSUE TITLE
is possible overwrite the same file

### ISSUE THREAD

**Issue by Mirodil** [gulpjs/gulp#267]
Hi,
Is possible overwrite the same file? for example

```
gulp.task('styles', function() {
  return gulp.src('content/**/*.css')
    .pipe(minifyCSS())
    .pipe(gulp.dest('content'));
});
```

**Comment by juliocanares** [comment]
yes it's possible just add a the base parameter and 
```javascript
  gulp.src('./app/**/*.js', {base: './'})
        .pipe(prettify())
        .pipe(gulp.dest('./'));
```

**Comment by erikwoods** [comment]
gold star for you @juliocanares - worked for me

**Comment by mathijspoc** [comment]
not working for me.. 

var revReplace = require("gulp-rev-replace");
gulp.task("revrep", function(){
    var manifest = gulp.src('./assets/js/rev-manifest.json');

    return gulp.src("./index.html", {base: "./"})
        .pipe(revReplace({manifest: manifest}))
        .pipe(gulp.dest("./index.html"));
});

**Comment by kover** [comment]
@mathijspoc 

try this

`return gulp.src("./index.html", {base: "./"})
    .pipe(revReplace({manifest: manifest}))
    .pipe(gulp.dest("./"));`

**Comment by jmsherry** [comment]
Sounds dumb, but always check your write permissions on the file. If files are owned by root user then you may need to change that or sudo in order to overwrite.

**Comment by contra** [comment]
Just to be clear - the original ticket was asking "is it possible to overwrite a file" and pasted code. Yes, it is possible to overwrite a file - and yes, the code you pasted will work fine. For anyone still stumbling on this ticket - you don't have to do anything special to overwrite files. The code in the original ticket works fine - so yes. You don't need the base parameter unless your output has specific requirements.
