### ISSUE TITLE
Wrong module syntax on gulpjs.com /  Named export 'dest' not found.

### ISSUE THREAD

**Issue by Sebi2020** [gulpjs/gulp#2686]
### What actually happened?
[gulpjs.com](https://gulpjs.com/) shows example, which do not work, cause gulp is a CommonJS module, but the examples use ES-Module Syntax:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1862664/174136404-e8372738-1619-4ef9-a6d8-d9d4b501462d.png">

Which causes the following error:
```
import {src, dest} from 'gulp';
             ^^^^
SyntaxError: Named export 'dest' not found. The requested module 'gulp' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by phated** [comment]
These examples are meant to be used in a `gulpfile.esm.js` and require the esm module to be installed.
