### ISSUE TITLE
gulp.src and gulp.watch glob patterns are not working the same.

### ISSUE THREAD

**Issue by ve3** [gulpjs/gulp#2687]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [ ] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
The glob pattern use in `gulp.watch` should work the same way with `gulp.src`.

### What actually happened?
The negative character (`!pattern`) should filtered out the path. They did in `gulp.src` but did not in `gulp.watch` even they both have the same options.

For example: I filtered out **tests** folder.
- If I run `gulp copy` then it works fine because it use `gulp.src()`.
- If I run `gulp watch` and make change to somewhere such as **tests/readme.txt**, it should be skipped but it just copy this file to target path.

Folder structure for **D:/wwwroot/_test/gulp-test**
- a.txt
- bbb/
  - bbb-text.txt
- tests/
  - readme.txt

### Please give us a sample of your gulpfile
``` js
'use strict';


const {series, parallel, src, dest, watch} = require('gulp');
const print = require('gulp-print').default;

const patterns = [
    './**',
    '!./node_modules',
    '!./node_modules/**',
    '!./tests',
    '!./tests/**',
];
const srcPath = 'D:/wwwroot/_test/gulp-test';
const destPath = 'D:/wwwroot/_test/gulp-dest';


function doCopy(cb) {
    return src(patterns, {
        allowEmpty: true,
        base: srcPath,
        cwd: srcPath
    })
    .pipe(print())
    .pipe(dest(destPath))
}


function doWatch(cb) {
    const watcher = watch(patterns, {
        base: srcPath,
        cwd: srcPath,
        events: 'all'
    }/*, series(
        // can't `copyPath` here because some functional required.
    )*/);
    watcher.on('all', (event, filepath) => {
        copyPath(event, filepath);
    });
    cb();
}


async function copyPath(event, filepath) {
    let command;
    if (event.toLowerCase().indexOf('unlink') !== -1) {
        // if matched unlink (file), unlinkDir (folder)
        command = 'delete';
    } else {
        // if matched add, addDir, change
        command = null;
    }

    if (command === 'delete') {
        const del = require('del');
        await del(filepath, {cwd: destPath});
    } else {
        return src(filepath, {
            allowEmpty: true,
            base: srcPath,
            cwd: srcPath
        })
        .pipe(print())
        .pipe(dest(destPath, {cwd: destPath}));
    }
}


// exports ==================================
exports.default = series(
    doCopy
);

exports.watch = series(doWatch);
```

### Terminal output / screenshots

```sh
$ gulp watch
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]:
  * Windows 11 x64
* node version (run `node -v`):
  *  v16.13.2
* npm version (run `npm -v`):
  *  8.12.2
* gulp version (run `gulp -v`):
  * CLI version: 2.3.0
    Local version: 4.0.2

### Additional information
Use dot prefix or without dot prefix (**!./tests**, **!tests**) as described [here](https://github.com/gulpjs/glob-parent) don't change anything.

This seems to be resolved in https://github.com/gulpjs/gulp/issues/2340 but it doesn't. Because from my **paths.json** file, the source path is using **/** as directory separator but still not working.

Packages required for testing: gulp, del, gulp-print.

**Comment by phated** [comment]
This example is too complex. Please provide a simplified test case that we can check. Ideally this will be a repository that can be cloned.

**Comment by ve3** [comment]
> This example is too complex. Please provide a simplified test case that we can check. Ideally this will be a repository that can be cloned.

I've updated the content.

**Comment by ve3** [comment]
It is `async` because I use with `await del()`. The problem is patterns in `src()` work diffently with `watch()` that's. The problem is not in `copyPath()`. 
Even if you use more simple like `series()` after `watch()` it is still not work the same with `src()` that is the main problem.

I think this is not discussion type, it is the problem that your `src()` and `watch()` work differently with the same patterns.
If you don't think that this is the problem it's okay to close the issue.
