### ISSUE TITLE
Rewrite Gulp code with typescript and ESM. I want to do this for you.

### ISSUE THREAD

**Issue by rafikalid** [gulpjs/gulp#2689]
### Describe your idea for a new feature
Rewriting Gulp code using new Typescript and ESM
- This will enhance tests, bug fixes and code redability

### How will it benefit gulp and its users?
- More stable and easy to read code

### If this feature could exist outside of gulp (like as a plugin or a module), would you be interested in helping to create and maintain it?
No, this is a code refactor. I'm ready to do this for you and send PR if you love to go with typescript
I love Gulp, so I want to maintain it with you and resolve bugs, add features with you.

**Comment by phated** [comment]
We're in the process of the gulp 5 updates, which don't include any JS syntax updates.

Once v5 is released, we'll be updating the code to use ESNext and ESM. We have no plans to change any code to typescript.

If you'd like to contribute to v5, we have a public project board at https://github.com/orgs/gulpjs/projects/4 - there is still a lot to do.
