### ISSUE TITLE
Gulp links to protestware - blocks pipelines

### ISSUE THREAD

**Issue by oteoe** [gulpjs/gulp#2704]
Gulp > Gulp CLI > Undertaker links to protestware

gulp-cli links to undertaker -  links to:

https://github.com/medikoo/es6-weak-map

links to

https://github.com/medikoo/es5-ext

both are from the same author

see:
https://github.com/medikoo/es5-ext/issues/186

It gets flagged as a virus and blocks a lot of projects/pipelines.

**Comment by phated** [comment]
We are aware and it'll be removed in the next major release.
