### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by noraj** [gulpjs/gulp#2737]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.

### Describe your idea for a new feature

Gulp seems to [support JavaScript](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles) generally but in reality it's more targeted on nodejs only. Actually gulp is not working with [bun](https://bun.sh/) JavaScript runtime.

```
➜ bun run ./node_modules/gulp-cli/bin/gulp.js
15 | 
16 | // Needed to add this because node 10 decided to start coloring log output randomly
17 | var console;
18 | if (nodeVersion.major >= 10) {
19 |   // Node 10 also changed the way this is constructed
20 |   console = new Console({
                ^
TypeError: undefined is not a constructor (evaluating 'new Console({
      stdout: process.stdout,
      stderr: process.stderr,
      colorMode: !1
    })')
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/fancy-log/index.js:20:12
      at globalThis (/home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/fancy-log/index.js:92:23)
      at require (:1:20)
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/lib/shared/log/to-console.js:3:4
      at globalThis (/home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/lib/shared/log/to-console.js:58:17)
      at require (:1:20)
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/index.js:20:4
      at globalThis (/home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/index.js:111:17)
```

Currently, bun don't have [support for Console](https://bun.sh/docs/runtime/nodejs-apis).

It would be nice to have support for bun.

**Comment by phated** [comment]
Gulp is a node project and relies on node APIs. No attempt will currently be made to support other runtimes.

**Comment by shaulgo** [comment]
Maybe you could have a better error messages for some of this APIs.
