### ISSUE TITLE
Request to provide a more beginner-friendly tutorial on gulp website.

### ISSUE THREAD

**Issue by viocha** [gulpjs/gulp#2743]
### Describe your idea for a new feature
I hope the gulp official website can provide more beginner-friendly tutorials, which can introduce the use of gulp in a simple and understandable way.

### Explain the problem your idea is trying to solve
The beginner’s tutorial on the gulp official website is not suitable for beginners. It basically consists of a brief introduction to the features, followed by a complex piece of code, without explaining the function of the statements inside. After reading it, I still can’t understand the effect of the code, let alone learn to use gulp. Compared to the tutorials of other js libraries, gulp’s is the most difficult to understand.

**Comment by phated** [comment]
Gulp is just JavaScript. If you don't know JavaScript, you should probably start by learning that somewhere else.
