### ISSUE TITLE
gulp-ssh and gulp 5: still no success

### ISSUE THREAD

**Issue by jcvignoli** [gulpjs/gulp#2765]
Congratulations for the new gulp!

I know that you do not support gulp-ssh, but since the plugin is abandonned, and it seems to me that uploading to another server is quite a basic task, I'm wondering if there is any plan for the new gulp to support a ssh copy in the future.

The latest and very old gulp ssh throws errors on some occasions and don't copy the updated file. The error message thrown is:

`Error: Missing error message
    at new PluginError (/node_modules/plugin-error/index.js:64:11)
    at Client.<anonymous> (/node_modules/gulp-ssh/index.js:57:27)
    at Client.emit (node:events:519:28)
    at Client.emit (node:domain:488:12)
    at Socket.<anonymous> (/node_modules/ssh2/lib/client.js:299:10)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

As far as I know, it's due to an incompatibility between latest NPM versions and gulp-ssh. Happened before updating to gulp 5, I had to stick to nodejs 16 until today... was expecting the new gulp 5 would take rid of the incapatibility.

Any idea of how to achieve ssh copy with gulp 5?

**Comment by phated** [comment]
Thanks for the kind words.

Unfortunately, we have no plans to support gulp-ssh because the core gulp project does not include any plugins.

**Comment by jcvignoli** [comment]
Hi @phated 
Thanks for your reply.
I take the opportunity to follow up, since I'm not much at ease with nodejs in general.
1/ With nodejs 19.9.0, I have no error message, the ssh copy works perfectly. If I update to > 19.9.0, the ssh copy fails.
2/ Is it be possible to use ssh with gulp 5? How can I expand functionalities with gulp core in the new version?
Thanks in advance.

**Comment by yocontra** [comment]
@jcvignoli The plugin seems pretty simple, you could fork it and update it so it works again and publish it to npm for others to use?

**Comment by jcvignoli** [comment]
@yocontra as I said, I unfortunately know nothing about nodejs in general. I tried to take a look at the plugin and got lost immediately.
