### ISSUE TITLE
v5 gulp.src processes array in alphabetical order instead of their index

### ISSUE THREAD

**Issue by prurigro** [gulpjs/gulp#2769]
First, thank you so much for getting v5 out the door! Secondly, I'm assuming this is a bug but it's possible that this falls into the same category as requiring ordered-read-stream? The release notes say that's for ordered globs though and this is an array of file paths with no globs... In any case, hopefully I'm not jumping the gun but apologies if I am.

### What were you expecting to happen?

Up until v5 I've been passing gulp.src() an array of files and they've been digested in the order they appear in the array. This means I can put files that other files are dependant on before those dependencies and everything works correctly.

### What actually happened?

What's happening now is that the files in the input array are appearing in the output file in what appears to be alphabetical order based on their complete file path (which for dependencies in node_modules means the name of the package)

### Please give us a sample of your gulpfile

This is a simplified version of my gulpfile that only includes the parts necessary to show the issue:

```
const gulp = require("gulp"),
    concat = require("gulp-concat");

const deps = [
    "node_modules/jquery/dist/jquery.js",
    "node_modules/detect_swipe/jquery.detect_swipe.js"
];

function processJavaScript() {
    return gulp.src(deps)
        .pipe(concat("deps.js"))
        .pipe(gulp.dest("public/js/"));
}

gulp.task("default", processJavaScript);
```

Previously, `jquery.js` would appear at the top of `deps.js`, followed by `jquery.detect_swipe.js`, but now the order is reversed because `d` comes before `j`. This means that the resulting script is broken because `jquery.detect_swipe.js` depends on `jquery.js`.

### Terminal output / screenshots

```
> gulp
[17:58:20] Using gulpfile ~/test/gulpfile.js
[17:58:20] Starting 'default'...
[17:58:20] Finished 'default' after 290 ms
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: Archlinux (up to date)
* node version (run `node -v`): v21.7.1
* npm version (run `npm -v`): 10.5.0
* gulp version (run `gulp -v`): CLI version: 3.0.0 - Local version: 5.0.0

**Comment by phated** [comment]
You are correct that this is the same issue as noted about ordered globs. "File paths" in gulp are singular globs (that match exactly one path). 

This breaking change was by design and you'll want to use ordered-read-streams.

**Comment by prurigro** [comment]
Hey, thanks for the response! When I try to pass gulp.src an ordered-read-stream it responds with

```

**Comment by phated** [comment]
src returns a stream, you don't need to do a wild dance like you are trying.

You might want to ask in our Discussions if you'd like help understanding streams.

**Comment by yocontra** [comment]
Because other people are going to end up on this ticket, to be more specific you can do something like this:

```js
const order = require("ordered-read-streams")

order([
    gulp.src("node_modules/jquery/dist/jquery.js"),
    gulp.src("node_modules/detect_swipe/jquery.detect_swipe.js")
])
  .pipe(whateverPlugin())
  .pipe(gulp.dest('wherever'))
```

**Comment by prurigro** [comment]
Thank you @phated for pointing me in the right direction, and thanks a ton @yocontra for the answer! I'd tried a few variations of that type of thing but was stuck thinking streamx had to be incorporated somehow. I was going to write up the problem in a discussion post tomorrow morning, but you saved me the trouble :)

It might be worth including this in the gulp src API documentation as well once the dust settles on that note? It seems like a common use case.

Thanks again, and congrats on the 5.0!
