### ISSUE TITLE
Gulp 5 corrupt images

### ISSUE THREAD

**Issue by deco1974** [gulpjs/gulp#2775]
I want to copy images to the dist folder:

    src(
        [
            './src/img/*.*',
        ]
    ).pipe(dest('./dist/img'));

The images get corrupted in Gulp 5. Downgrade to Gulp 4.0.0.2 everything is working fine as expected. 
Is there something i miss in the new version?

**Comment by simonhammes** [comment]
Check out https://github.com/gulpjs/gulp/issues/2766 :)

**Comment by aloayzab88** [comment]
Looks like using {encoding: false} will solve the issue, but {read: false} will to just to copy files. In my case I'm converting the images to webp, so {read:false} would be an option?

**Comment by phated** [comment]
@aloayzab88 if you are modifying the contents, you need to read the file so you'll turn encoding off
