### ISSUE TITLE
Gulp 5 - Copied images using .src and .dest are corrupt

### ISSUE THREAD

**Issue by rickdoesburg** [gulpjs/gulp#2777]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
I except files to be copied to my dist folder

### What actually happened?
The files are copied, but the images are corrupt and unreadable. Tried both .jpeg and .webp

### Please give us a sample of your gulpfile

```js
const gulp = require("gulp");

// Copy assets to dist
gulp.task("copy", () => {
    return gulp.src(["./assets/**/*"], { base: "./assets/" }).pipe(gulp.dest("./dist/"));
});

// Default task
gulp.task("default", gulp.parallel("copy"));

```

### Terminal output / screenshots

```sh
~/Projects/gulp-5-copy-demo » gulp copy 
[09:29:35] Using gulpfile ~/Projects/gulp-5-copy-demo/gulpfile.js
[09:29:35] Starting 'copy'...
[09:29:35] Finished 'copy' after 90 ms
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: 14.4.1 (23E224)
* node version (run `node -v`): v20.8.0
* npm version (run `npm -v`): 10.1.0
* gulp version (run `gulp -v`): 5.0.0 / CLI 3.0.0

### Additional information
Running this command on gulp4 causes no issues. After updating to gulp 5 the images are still copied but are corrupt.

**Comment by Patta** [comment]
Try to set `{ encoding: false }` option to `src`. See "Stream encoding" at https://medium.com/gulpjs/announcing-gulp-v5-c67d077dbdb7

**Comment by scotty2nd** [comment]
Hi @rickdoesburg,
i have the same problem and does not know how to set the encoding: false option can you show me an example how you have done it. Thanks

**Comment by yocontra** [comment]
Docs have been updated: https://github.com/gulpjs/gulp/blob/master/docs/api/src.md#options

You need to add `{ encoding: false }` for binary files.

**Comment by iamontheinet** [comment]
I have the same issue where the images (.png) are in the right location but they're corrupt in that they won't even open in Preview. And I've tried setting `encoding: false` as shown below but that didn't work.

```
gulp.task('build:images', () => {
  const srcs = [
    'app/images/**/*',
    'app/favicon.ico',
  ];

  return gulp.src(srcs, { base: 'app/', encoding: false })
    .pipe(gulp.dest('build'));
});

```

**Comment by khorwood** [comment]
Setting a safe default of `false` for encoding would have made this less impactful.

**Comment by jasonsocha** [comment]
Side issue - if you already ran into this problem and have fixed it by adding the encoding: false parameter, you'll need to temporarily remove the pipe through newer() if you're using it.  Gulp will assume the files haven't changed and will not attempt to re-copy them with the new parameter.  After you've done your gulp build once, you should be able to re-add the pipe through newer().

**Comment by hwinkler** [comment]
Would've been awesome for the Gulp team to have introduced new semantics by introducing a new function name instead of breaking existing Gulp programs that worked. You could have introduced `src2` or `srcEncode` as a new function with the new semantics, and kept old  programs working.

**Comment by AlexHiriavenko** [comment]
> Try to set `{ encoding: false }` option to `src`. See "Stream encoding" at https://medium.com/gulpjs/announcing-gulp-v5-c67d077dbdb7

Thank you, this helped.

just in case here is a simple example:
```
export const copy = () => {
  return app.gulp
    .src(app.path.src.files, { encoding: false })
    .pipe(app.gulp.dest(app.path.dist.files));
};

```
