### ISSUE TITLE
In gulp 4.0.2 fonts are displayed correctly, and in version 5.0.0 there are constant errors

### ISSUE THREAD

**Issue by dmitrytrofim** [gulpjs/gulp#2778]
I'm doing a new project now, I updated gulp, and the oddities started. In my task, fonts are simply copied from one folder to another. So in 5.0.0 it gives this OTS parsing error: Failed to convert WOFF 2.0 fonttoSFNT. Then I downgrade gulp to 4.0.2 and everything works fine. What is all this for? And I noticed that the new version works much slower. But fonts are most annoying, how can I fix this behavior? Since I have only 2 lines there, copy and paste.

**Comment by Patta** [comment]
https://github.com/gulpjs/gulp/issues/2777#issuecomment-2036776560

**Comment by yocontra** [comment]
Docs have been updated: https://github.com/gulpjs/gulp/blob/master/docs/api/src.md#options

You need to add `{ encoding: false }` for binary files.
