### ISSUE TITLE
Gulp v5.0.0 png and jpg images not opening after transferring via gulp

### ISSUE THREAD

**Issue by sharnirio-work** [gulpjs/gulp#2779]
### What actually happened?
The pictures jpg & png format are broken and don't work after copy from "src" to "dest"

### Please give us a sample of your gulpfile
Full example - [repo](https://github.com/sharnirio-work/test-gulp5-bug.git)

Gulp file code:

`const { src, dest } = require('gulp');

function defaultTask(cb) {
    return src("img/*.+(jpg|png|svg)")
        .pipe(dest('img-after/'));
    cb();
}

exports.default = defaultTask`

As you can see the pictures break and stop working. Original image [link](https://prnt.sc/OlVyVM24qs4W) and image after gulp transferring [link](https://prnt.sc/xMwZ8YaYVjoc)

### Please provide the following information:
Windows 11
node -v : v18.19.0
npm -v : 10.4.0
gulp -v:  CLI version: 3.0.0 Local version: 5.0.0

**Comment by Patta** [comment]
https://github.com/gulpjs/gulp/issues/2777#issuecomment-2036776560

**Comment by yocontra** [comment]
Docs have been updated: https://github.com/gulpjs/gulp/blob/master/docs/api/src.md#options

You need to add `{ encoding: false }` for binary files.
