### ISSUE TITLE
PNG files are corrupted after Gulp upgrade to 5.0

### ISSUE THREAD

**Issue by ArtemAvramenko** [gulpjs/gulp#2793]
PNG files are corrupted in the most basic scenario:
```js
gulp.src(['src/images/*.png'])
    .pipe(gulp.dest('dist/'));
```

Reverting to v4.0.2 solved the problem.

* OS & version: Windows 10 Home 22H2
* node version: 18.17.1
* npm version: 9.6.7
* gulp version: 5.0.0

**Comment by minerva-mscaroni** [comment]
Same error here: not only PNG files, but also JPG and WEBP are corrupted. I've noticed that output files are also bigger (in KB) than original ones.

**Comment by johantor** [comment]
Have same issue with font files.

Src on the left, dest on the right with a basic `gulp.src(PATHS.fonts.src).pipe(gulp.dest(PATHS.fonts.dest));`

![image](https://github.com/gulpjs/gulp/assets/4183481/6b4f1c18-ff02-470b-9f46-62c8b1602c5d)

**Comment by minerva-mscaroni** [comment]
You're right: I forgot to mention font files (woff/woff2 in my case)!

**Comment by MikeVL** [comment]
Same error with JPEG files

**Comment by madjacky** [comment]
add to src { encoding: false }

**Comment by BotKarma46** [comment]
I advise you to first look through the magazine with closed questions that already have answers. In order not to multiply the same type of questions every day :)

**Comment by ArtemAvramenko** [comment]
Duplicates https://github.com/gulpjs/gulp/issues/2777
