### ISSUE TITLE
Images not loading after build gulp, when version changed (4.0.2 -> 5.0.0)

### ISSUE THREAD

**Issue by tasnim2512** [gulpjs/gulp#2816]
I'm encountering an issue where images are not loading after running the Gulp build process. The images are copied to the dist/assets/images directory, but when I try to load the website in a browser, it shows a "image cannot load" error when inspect the image.Also on the dist folder i can see the image files but can not open them while it was working when i used gulp4.0.2. Js and css files are working fine.

Expected Behavior:
The images should load correctly in the browser, being served from the dist/assets/images directory.

Actual Behavior:
The browser shows no image.
    
### gulpfile.js

```js
const paths = {   
 dist: {
        img: {
            dir: './dist/assets/images',
        },
    },
 src: {
        img: {
            dir: './src/assets/images',
            files: './src/assets/images/**/*',
        },
    }
gulp.task('copy:images', function () {
    return gulp
        .src(paths.src.img.files)
        .pipe(gulp.dest(paths.dist.img.dir));
});

gulp.task('default', gulp.series(gulp.parallel('copy:images'), gulp.parallel('browsersync', 'watch')));

gulp.task('build', gulp.series('copy:images'));

```

### Os & versions
* OS & version-Ubuntu 22.04.4 LTS
* node version :18.20.2
* npm version: 10.5.0
* gulp version: CLI version: 3.0.0
                       Local version: 5.0.0

### Screenshots
![Screenshot from 2024-07-29 18-35-09](https://github.com/user-attachments/assets/bbad67e9-a559-4402-8da3-05ff382be4a6)
![Screenshot from 2024-07-29 18-26-06](https://github.com/user-attachments/assets/b295a603-b0a2-4471-9156-29ff24c02666)

**Comment by yocontra** [comment]
`.src(paths.src.img.files)` -> `.src(paths.src.img.files, { encoding: false })` - See release notes for v5 that document this change.

**Comment by tasnim2512** [comment]
Hello Yocontra
Thank you for the solution but it's still not working on my end.Am i missing something?

```js
gulp.task('copy:images', function () {
    return gulp
        .src(paths.src.img.files, { encoding: false })
        .pipe(gulp.dest(paths.dist.img.dir));
});
```

**Comment by tasnim2512** [comment]
I am sharing my whole gulpfile here.
https://drive.google.com/file/d/1F-PyOm-p3j8MHXznGE7IrIx-3Q4SO2ut/view?usp=sharing

**Comment by Daniil-333** [comment]
I join the issue. Adding a parameter does not solve the problem.

NodeJS: 22.13.1
CLI version: 3.0.0
Local version: 5.0.0
OS: macOS Big Sure 11.7.10

`import ttf2woff from 'gulp-ttf2woff';

export const ttfToWoff = async () => {
	const ttf2woff2 = await import('gulp-ttf2woff2');

	return app.gulp.src(`${app.path.srcFolder}/fonts/*.ttf`, {encoding: false})
		.pipe(app.plugins.plumber({
			errorHandler: function (err) {
				console.log(err)
				this.emit('end');
			}
		}))
		.pipe(ttf2woff())
		.pipe(app.gulp.dest(`${app.path.build.fonts}`))
		.pipe(app.gulp.src(`${app.path.srcFolder}/fonts/*.ttf`), {encoding: false})
		.pipe(ttf2woff2.default())
		.pipe(app.gulp.dest(`${app.path.build.fonts}`));
}
`
