### ISSUE TITLE
Gulp.src doesn't seem to work on windows shares

### ISSUE THREAD

**Issue by tcoopman** [gulpjs/gulp#283]
On windows I have a gulpfile like this:

```javascript
var gulp = require('gulp');
var size = require('gulp-size');
var fs = require('fs');

var loc = '//some/shared/file.txt';

console.log(fs.existsSync(loc));

gulp.task('default', function(){
  gulp.src(loc)
    .pipe(size({showFiles: true}))
});
```

If I run this, I get size is 0, while the file does exist. The console.log outputs true, so node detects the file correctly, but gulp doesn't. If I change the path to something on the c drive, everything works as expected.

**Comment by heikki** [comment]
Shortcut to node-glob PR -> https://github.com/isaacs/node-glob/pull/146

**Comment by phated** [comment]
Followed some references and found a possible workaround at https://github.com/sindresorhus/del/issues/35#issuecomment-184736366

It doesn't look like node-glob cares about this issue at all, so hopefully anyone running into this is able to use that workaround.  We pass all extra options to node-glob, I believe.
