### ISSUE TITLE
Add beep sound on task error

### ISSUE THREAD

**Issue by yairEO** [gulpjs/gulp#293]
is it something that should be handled in GULP? I have this in GRUNT and it's very helpful.

**Comment by biwin** [comment]
Make sure you have internal buzzer in your computer.

If on Ubuntu, install beep with `sudo apt-get install beep`, type in `beep`. if it doesn't beep, run `sudo modprobe pcspkr`

**Comment by qodesmith** [comment]
Do we have a standard way of emitting a beep for gulp errors? Still looking for a solution to this...

**Comment by AndrewSepic** [comment]
I'd love to have an audible notification if the build fails..+1

**Comment by phated** [comment]
@AndrewSepic this won't be part of gulp, but you can always add it to your tasks yourself. There are plenty of modules on npm that do it.
