### ISSUE TITLE
How to write text into a file? Not from a source file.

### ISSUE THREAD

**Issue by leftstick** [gulpjs/gulp#332]
I am wondering if it is possible to write something into a file? Instead of using `gulp.src('glob').pipe(gulp.dest('target/'))`?

The thing is i have some text generated while the task is running, and i'd like to write those thing into a file. For consistency purpose, i am asking if there is a `gulp` plugin to do this? Instead of `fs`?

**Comment by ayyash** [comment]
Question, where does the filename.txt get saved if at all?
