### ISSUE TITLE
Supported globbing patterns

### ISSUE THREAD

**Issue by demisx** [gulpjs/gulp#348]
I need a glob to filter out JPG/PNG images. Is there a way to write a one-liner glob that gulp would understand instead of listing each file extension match string separately? 

For example:

``` js
gulp.src( ['./app/**/*.jpg', './app/**/*.png']) // <- this works, but gets too long over time
gulp.src( ['./app/**/*.(jpg|png)']) // <- this is preferred, but doesn't work
```

**Comment by mmarczell-graphisoft** [comment]
Today it's `*.@(jpg,png)`
