### ISSUE TITLE
Logging mixed up with asynchronous tasks

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#361]
3rd party modules that log progressively/asynchronously will get stuff mixed in from other tasks

![sample](https://pbs.twimg.com/media/Bi8K_g2IQAEKy4N.png:large)

This will have to be fixed at the plugin level or we could do some trickery at the task level

**Comment by phated** [comment]
Note: this will only be handled when logging is done through gulp-util.log (soon to be gulplog)

**Comment by phated** [comment]
Ref #1208

**Comment by kahlil** [comment]
Since new logging is done, how does this issue need to be addressed?

**Comment by phated** [comment]
@kahlil I'm not sure how this would be tackled.  Any ideas?

**Comment by phated** [comment]
Deferring to gulp-cli 1.2.0

**Comment by phated** [comment]
Moved to https://github.com/gulpjs/gulp-cli/issues/72 - Closing.
