### ISSUE TITLE
Make a browserify recipe

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#369]
Watchify is not needed, you can use browserify just fine.

This is an example of me bundling a browserify project into a standalone file:

```js
var buffer = require('vinyl-buffer');
var source = require('vinyl-source-stream');
var browserify = require('browserify');
var uglify = require('gulp-uglify');

var bundler = browserify('./js/index.js');

gulp.task('compile', function(){
  return bundler.bundle({standalone: 'noscope'})
    .pipe(source('noscope.js'))
    .pipe(buffer())
    .pipe(uglify())
    .pipe(gulp.dest('./dist'));
});
```

I think this could be a perfectly fine plugin as well:

```js
var uglify = require('gulp-uglify');
var browserify = require('gulp-browserify');

gulp.task('compile', function(){
  return browserify('./js/index.js', {standalone: 'noscope'})
    .pipe(uglify())
    .pipe(gulp.dest('./dist'));
});
```

**Comment by jmm** [comment]
@sogko Your recipe using vinyl-transform is broken as of browserify 8.0.2 (see substack/node-browserify#1044), at least when using `browserify.transform()`. I think that wasn't a great match in the first place as vinyl-transform is designed to pipe to the return value of `transformFn` (`browserify.bundle()` in this case), isn't it? Which makes no sense with browserify. I think it only worked in a sort of accidental way. That being said, there may be a way to adapt the recipe to continue to work using vinyl-transform (see the browserify issue).

**Comment by jmm** [comment]
@contra It's confusing trying to reconcile a few of your comments:

> I think this could be a perfectly fine plugin as well:

 

> I agree it shouldn't be a plugin.



> I don't think there has ever been an argument about if there should be a plugin or not. I absolutely think there should be one...

Maybe this thread would more accurately express your opinion with edits to some of your comments clarifying what you mean by "plugin". From the example in your first post here and [your comment](https://github.com/gulpjs/plugins/issues/47#issuecomment-38360210) on a different issue it seems that here maybe you're using the term plugin in a different sense than the commonly understood meaning of it in the context of gulp.

**Comment by phated** [comment]
We are satisfied with our latest browserify recipe at https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md. Closing this
