### ISSUE TITLE
Plugins producing and consuming objects as side effects/parameters

### ISSUE THREAD

**Issue by laurelnaiad** [gulpjs/gulp#401]
I have some plugins in mind that need to do more than just file streaming.  That is, while **they have their basis in input files** (like gulp.src), **output files** (like gup.dest) or **both** (like most of the custom plugins), they also need to do "other things".

What are these other things?  Well, for the most part they would be to produce information that for the purposes of a gulp-plugin might be thought of as a side effect.  Perhaps a plugin would analyze the files and provide some analytical value through a Javascript object that might be consumed as an input (mechanism TBD) of some other plugin.

The point is that I want to produce and consume stuff that is dynamically created/modified during processing.

If the information weren't dynamic, I could just dangle it in object(s) within options parameters.   Since it is  dynamic, the method I've come up with so far is to use promises, since the point at which some object may be ready for consumption isn't generally the same as the point at which the intended consumer is receiving its first file and thus otherwise ready to begin its work.

Perhaps there's a gotcha I haven't considered, but at the point where I formed this idea (just now), it seems like it is a technically feasible option.

But that doesn't mean it feels good.  In fact, it feels kind of hokey.

Is there some other solution to this problem?  To me, it seems like gulp has really filled a gap with respect to connecting inputs and outputs of dev process steps, but only when the inputs and outputs are file artifacts.  Other intermediate information doesn't feel like it has a home/generally accepted method of handling communication/asynchronicity.

Any thoughts?  Is there, in fact, some infrastructure to do this that I don't know about? Once I have both a stream of files that is coming out of such a plugin, and a promise as well, the next plugin that happens to rely on the promises would obviously be set up to wait on their fullfilment before processing the stream of files that comes into it... so the whole thing feels a bit messy.  I feel like I might be overlooking the obvious way to do this.  I also can guess that some might say, "don't use a plugin for this"... to me, this is a plugin with normal files in, files out, and unlike many plugins whose side effects are console log entries, this one also has a side effect of delivering some other data that is used down the chain... but I'm open to all advice.

**Comment by phated** [comment]
I don't think there's anything further for us to do on this discussion.

I think the best example I know of for interdependent gulp plugins is https://www.npmjs.com/package/gulp-escomplex, https://www.npmjs.com/package/gulp-escomplex-reporter-html & https://www.npmjs.com/package/gulp-escomplex-reporter-json
