### ISSUE TITLE
Problem with watchify recipe

### ISSUE THREAD

**Issue by rikukissa** [gulpjs/gulp#407]
It seems that if you create a task similar to the "watch" task in [watchify recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md) **gulp.dest** is not emitting "end" event in some cases. This prevents you from continuing the pipeline for example with gulp-livereload.

Everything seems to be working fine when you run the task for the first time, or if you save a file that's required by the entry file. When you save the entry file watchify emits the "update" event, the rebundle function is called and bundle file is written, but the pipeline seems to get stuck to gulp.dest and everything after that is ignored.

Also everything seems to be working fine if you have no **require** calls on your entry file.

I was able to track it down to vinyl-fs library's writeStream method, where for some reason the "finish" listener is not triggered on line 15.

[Here's my task](https://gist.github.com/rikukissa/a29940840207ffc3213e)

**Comment by contra** [comment]
The watchify recipe was redone, let me know if this is still an issue and I will reopen
