### ISSUE TITLE
process does not exit

### ISSUE THREAD

**Issue by mihhail-lapushkin** [gulpjs/gulp#411]
Tried different node versions, but doesn't help.
Using latest 3.6.0 gulp.
Running on latest OSX Mavericks.

Strange that on another laptop with Mountain Lion everything works.
I would guess that with such inconsistency it's hard to do something, but maybe someone can give me some tips regarding possible debugging of my situation. Maybe some console.log's would help is some gulp or orchestrator sources?

This is a similar issue:
https://github.com/gulpjs/gulp/issues/18

but in my case I am running as usual

**Comment by Janatbek** [comment]
@blopker 
are you still using this fix?
gulp.task('default', ['build'], function() {
    process.exit(0);
});
it works for me on Jenkins build, but I want to be sure if I can push this code as solved.
do you think I can leave it this way or I there is fix for this?

**Comment by demurgos** [comment]
The fix is to return an `async-done` compatible value.

```
    b.bundle()
     .pipe(source('build.js'))
     .pipe(gulp.dest(__dirname + '/../public/js/'))
     .on('error', function (err) { console.error(err); });
```

should be returned: `return b.bundle(). <...>`;
