### ISSUE TITLE
What is gulp.start?

### ISSUE THREAD

**Issue by CWSpear** [gulpjs/gulp#426]
I see that `gulp.run` was [deprecated](https://github.com/gulpjs/gulp/issues/193), but I also see that there is a `gulp.start` command that seems to do the same thing as `gulp.run`, but just is more aptly named and doesn't come with the deprecation warning.

I couldn't find anything in the docs about `gulp.start`. Am I correct in thinking that `gulp.start` is a replacement for `gulp.run` (because of the better name), or is it some unreliable internal API that some people have stumbled upon and it's gonna disappear someday and people shouldn't rely on it?

If it's just missing from the docs, I'd be willing to do a PR as far as I understand how it works.

**Comment by vikas-bansal** [comment]
does gulp.start work asynchronously?

**Comment by isochronous** [comment]
It works exactly like calling "gulp <taskname>" from the command line

**Comment by lucastheisen** [comment]
@fesor , in this code:
```
gulp.task('server', function () {
    gulp.watch(['src/index.html', 'bower.json'], ['index']);
    gulp.watch(someGlob, ['index']).on('change', function (e) {
        skipIndex = e.type !== 'added' && e.type !== 'deleted';
    });
});
```
Is there any guarantee that the `change` event callback will complete before the task gets run?  I cant find any sort of definitive information on the subject...  I am trying to do something similar where the content injected into the index (_gulp-inject_) depends on which file was updated...
