### ISSUE TITLE
Panes (feature request)

### ISSUE THREAD

**Issue by lambdahands** [gulpjs/gulp#434]
I'm not sure how feasible this is, but It would be awesome to have the ability to separate different tasks into panes. I like to use gulp to spin up development server instances, compile front end resources and live-reload my browser. It's a lot of different stuff going on a once, and the output gets pretty jumbled between all of it.

I'm not a Rails dev, but as an example I imagine a setup like this might be useful:

```
|-------------------------------------|
|                   |                 |
|                   |                 |
|   Server Output   |                 |
|                   |                 |
|                   |                 |
|-------------------|   Rails Tests   |
|                   |                 |
|                   |                 |
|   Sass Compiler   |                 |
|                   |                 |
|                   |                 |
|-------------------------------------|
```

Thoughts?

**Comment by nerdyglasses** [comment]
or you can do that with iterm2 on mac if you have one.
