### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by dmp42** [gulpjs/gulp#436]
Hi,

Running Ubuntu 14.04 and nodejs 0.10.25~dfsg2-2ubuntu1

The node binary is called `nodejs` (and there is no `node` binary) which makes gulp fail https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L1

The following would fix it (unfortunately, there is no simpler hack AFAIK):

```

#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" -- "$0" "$@"
```

What do you think?

**Comment by rohanpande** [comment]
I has to face the same issue. This is how I solved it. 
sudo ln -s /usr/bin/nodejs /usr/bin/node

just in case someone came here looking for solution to this problem.

**Comment by gameslayer** [comment]
@rohanpande Weird, that fixed my issue I was having both using npm and getting the newest version of Electron, thanks!

**Comment by mtucker6784** [comment]
Sorry to bump, but thanks @rohanpande!

**Comment by nighinatt** [comment]
@rohanpande, that fixed my issue..Thank you

**Comment by cjfpainter** [comment]
Also my thanks to @rohanpande!

**Comment by callumacrae** [comment]
Emoji reactions only from this point forwards, please - no need to send everyone notifications 😃 

🎉 🎊 😄 👯
