### ISSUE TITLE
Watch is very slow to recognize file modifications

### ISSUE THREAD

**Issue by swvjeff** [gulpjs/gulp#448]
This seems to be a common problem for me, but I haven't been able to find any issues about posted about it. Maybe I'm just doing something wrong. 

When I'm developing, it frequently takes the watch task 5-15 seconds just to recognize that a file was modified. Once the task actually starts, everything execute quickly, but the problem is triggering the watch task so it notices my file modifications. This makes development much slower than manually calling a particular task.  Here's my very simple watch task:

```
gulp.task('less', function() {
    return gulp.src(paths.less)
        .pipe(gulpless())
        .pipe(gulp.dest('./public/css/tmp'));
});

gulp.task('watch', function() {
    gulp.watch(paths.less, ['less']);
});
```

Is this normal behavior? If so, is there anything I can do to speed up the file modification recognition? If not, how can I benchmark what's taking so long?

**Comment by alexshelkov** [comment]
@rpullinger you are wizard. It works MUCH better now!

**Comment by tanc** [comment]
@rpullinger thank you very much for that hint, it works really nicely. Anyone know if there is any increase in CPU or disk activity with this method? I haven't noticed anything significant.

**Comment by lukepolo** [comment]
Also some other options that help 
https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/

**Comment by Gerst20051** [comment]
:+1:

**Comment by nickescobedo** [comment]
:+1: actimeo=2 worked for me as well!

**Comment by RiFi2k** [comment]
You made my life so much better you have no idea.

Also I second the:
https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/

**Comment by Amakaruk** [comment]
I'm having this same issue, but I don't understand how to locate my vagrantfile. I'm using windows.

**Comment by Repox** [comment]
@Amakaruk, the Vagrantfile is located in the same folder where you ran "vagrant up" in the first place.

**Comment by alex-moreno** [comment]
nickescobedo solution worked like a charm for me :-) very happy with this

**Comment by devantoine** [comment]
Erf, I don't understand why this is not working for me :/

`172.28.128.1:/Users/antoinedes/Dev/Projects/foobar on /vagrant type nfs (rw,vers=3,udp,actimeo=2,addr=172.28.128.1)`
