### ISSUE TITLE
Remove gulp-clean and gulp-rimraf from all documentation

### ISSUE THREAD

**Issue by yocontra** [gulpjs/gulp#451]
No need for a gulp plugin when you can do this

``` js
var rimraf = require('rimraf');

gulp.task('clean', function(cb){
  rimraf('./public', cb);
});
```

**Comment by helzgate** [comment]
i had to concatenate multiple paths like this in order to use rimraf:
var paths = "src/stuff" + " " + "bld/junk";
rimraf(paths,cb);
