### ISSUE TITLE
Question: with Gulp how do you only SFTP files which have changed after minification?

### ISSUE THREAD

**Issue by u01jmg3** [gulpjs/gulp#465]
Using `gulp` and `gulp-sftp`, I can't seem to only upload the file that has changed after CSS minification.

The semi-working snippet below begins by compiling the CSS and then continues to watch for changes in the `src` dir. It follows on by watching for changes in the `dist` dir (where minified CSS is stored) in order to upload that file to a web server.

However, this does not work as `gulp` is uploading everything rather than only the file that has changed and been minified.

``` js
var gulp = require('gulp'),
    changed = require('gulp-changed'),
    minifycss = require('gulp-minify-css'),
    sftp = require('gulp-sftp')
;

var src = './src/',
    dist = './dist/';

var srcStyles = src + '**/*.css',
    distStyles = dist + '**/*.css';

var host = 'ftp.xxxx.xx.xx',
    auth = 'keyMain',
    remotePath = 'public_html';

gulp.task('compilecss', function(){
    gulp.src(srcStyles)
        .pipe(changed(dist))
        .pipe(minifycss({keepBreaks: true}))
        .pipe(gulp.dest(dist))
    ;
});

gulp.task('uploadcss', function(){
    gulp.src(distStyles)
        .pipe(changed(dist))
        .pipe(sftp({
            host: host,
            auth: auth,
            remotePath: remotePath
        }))
    ;
});

gulp.task('main', function(){
    gulp.start('compilecss');
});

gulp.task('watch', function(){
    gulp.watch(srcStyles, ['compilecss']);
    gulp.watch(distStyles, ['uploadcss']);
});

gulp.task('default', ['main', 'watch']);
```

**Comment by stevenmwade** [comment]
@contra Using rimraf doesn't work if you are trying to delete multiple files, which is contrary to trying to put all the cleans in one task. Either that or I can't figure out how it works since it can't take an array of file paths and can't be called twice.
