### ISSUE TITLE
Is there any GUI tool for Gulp?

### ISSUE THREAD

**Issue by fritx** [gulpjs/gulp#468]
Or other Build Systems (like Grunt)? Or IDE that already integrates those?

**Comment by CrashyBang** [comment]
Here is the beginning of something pretty cool:
Video: http://www.screenr.com/VrUN
Repo: https://github.com/Enome/gobble

**Comment by cuixiping** [comment]
https://github.com/keith3/GulpIDE

![GulpIDE](https://github.com/keith3/GulpIDE/raw/master/img/newProject.png)

![GulpIDE](https://github.com/keith3/GulpIDE/raw/master/img/idelook.png)

**Comment by avihaymenahem** [comment]
Hi Guys!
Ive jsut started to work on something cool, Gulp task runner
https://github.com/avihaymenahem/GTRunner

**Comment by fritx** [comment]
Hi guys!
I've forked sindresorhus' cool [gulp-app](https://github.com/fritx/gulp-app), and made it work on Windows as well as OSX. Also made some changes. Free free to try ;)

**Comment by doubleedesign** [comment]
Thank you @fritx  At work I don't get a choice and have to use Windows, it's so annoying when tools I want to try are only available on Mac! Looking forward to trying yours!

**Comment by avihaymenahem** [comment]
I built one not so long ago:
https://github.com/avihaymenahem/GTRunner

**Comment by nsteiner** [comment]
This is a WIP, intended to make local site work/viewing as easy as opening an included app. I'm thinking the use-case to be if you want to share your work with someone less-technical, but I haven't validated how realistic a scenario that will end up being.

![gulp-gui-a1](https://cloud.githubusercontent.com/assets/111835/12928867/f710e5e6-cf3d-11e5-8df2-bf1a951eaca5.gif)

**Comment by warent** [comment]
I've been working on one. It uses ES2015 and Gulp 4. Will be releasing 1.0 soon. Feedback, comments, questions, etc, all welcome :)

https://github.com/VYNYL/gulpnoir/tree/1.0

**Comment by avihaymenahem** [comment]
https://github.com/avihaymenahem/GTRunner Enjoy :)

**Comment by ameshkin** [comment]
I am actually thinking of also building a visual gulp type system, then found this! I may not have to.

**Comment by PolaEdward** [comment]
@warent 
Looks very promising, I hope you don't abandon it!
You can even update it more and make it more generic GUI for any flow system

**Comment by warent** [comment]
@PolaEdward I didn't create the flow system myself, it's an implementation of clientIO/joint.

Unfortunately, I did choose to abandon the project due to most developers migrating to Webpack, Rollup, etc. This, coupled with the super slow progress on Gulp 4 (Gulp 4 was "almost done" when I was working on GulpNoir two years ago yet is only just recently starting to roll out!), made it apparent that Gulp was basically becoming deprecated.

Feel free to fork GulpNoir and take over if you'd like :)

**Comment by demurgos** [comment]
I did not see it mentioned here but Gulp is really well integrated with Intellij IDEA, Webstorm and other Jetbrains products:
![image](https://user-images.githubusercontent.com/2262218/38089173-cadba682-335e-11e8-8220-f20c87b22710.png)

**Comment by contra** [comment]
@warent gulp isn't deprecated, sometimes things are just feature complete and don't need to be rewritten every 2 months with massive breaking API changes to show "progress". when we do make breaking changes to the API (gulp 4) we do it carefully to make sure we get it right and don't have to redo it 2 months later.

**Comment by TheComputerM** [comment]
There is quenchjs
