### ISSUE TITLE
Optional dependent tasks

### ISSUE THREAD

**Issue by georeith** [gulpjs/gulp#483]
Okay so `gulp.run()` is deprecated, and that's fine because it helps people to do bad things.

However I often have a lot of dependant tasks, I want to lint my code and clean the build directories before compiling it:

```
gulp.task('scripts', ['lint', 'clean'], function() { return ... });
gulp.task('css', ['clean'], function() { return ... });
gulp.task('html', ['clean'], function() { return ... });

gulp.task('build', ['scripts', 'css', 'html']);
```

Fantastic! Except if I am going to use `gulp.watch`, in which case I still want to lint but not clean the build directories.

```
gulp.task('build', ['scripts', 'css', 'html']);
gulp.task('watch', ['devScripts', 'devCSS', 'devHTML']);
```

Sure there are ways around it but they all require code repetition (duplicate tasks with separate dependancies, or pulling stuff out of tasks into functions that I'd rather keep available to the CLI and I still end up repeating myself by calling them across multiple tasks).

Here is what I propose, the **independant operator**!

```
gulp.task('build', ['scripts', 'css']);
gulp.task('watch', ['!clean', 'scripts', 'css']);
```

The presence of the `!` or `^` character before a dependancy would tell gulp to ignore those dependancies in any of the dependant tasks. I imagine behind the scenes it would set that task to completed without logging anything so that any following tasks assume it is already done and ignore the dependancy, the same way a task doesn't get called twice if two tasks depend on it.

This would really help in creating concise DRY tasks. You could take this a step further and add a `gulp.forget([])` for manually flicking the "pretend a task is completed" switch, then we could do this in functions and make use of command line arguments and other logic.

**Comment by alanrivetta** [comment]
I created this function.
They think it's valid?

```javascript
function optionalDependency(paramCondition, dependencies_optional, tasksDefault, series_parallel, append){
    series_parallel = typeof(series_parallel) == "undefined" || series_parallel == null ? 'series':'parallel';
    append = typeof(append) == "undefined"? false:true;
        if(this.process.argv.indexOf('--' + paramCondition) > -1){
            if(series_parallel == "parallel"){
                tasks = (append? gulp.parallel(tasksDefault, dependencies_optional): gulp.parallel(dependencies_optional, tasksDefault));
            }
            else if(series_parallel == "series"){
                tasks = (append? gulp.series(tasksDefault, dependencies_optional): gulp.series(dependencies_optional, tasksDefault));
            }
        }
        else{
            tasks = gulp.series(tasksDefault);
        }
    return tasks;
};
```

## Example 1:

```javascript
gulp.task('default', optionalDependency('paramTest', 'optionalDep', 'build', 'parallel'))
```

#### gulp --tasks --paramTest

* default
    * parallel
        * optionalDep
        * build (And depends tasks...)

## Example 2:
```javascript
gulp.task('default', optionalDependency('paramTest', 'optionalDepAfter', 'build', null, true))
```

#### gulp --tasks --paramTest

* default
    * series
        * build (And depends tasks...)
        * optionalDepAfter

## And default without parameters

#### gulp --tasks

* default
    * series
        * build (And depends tasks...)
