### ISSUE TITLE
Error handling for a watchify recepie

### ISSUE THREAD

**Issue by samvasko** [gulpjs/gulp#488]
I would like to see a working example for error handling for [fast-browserify-builds-with-watchify](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md). Now it just crashes for me on error.

Thanks!

**Comment by builtbylane** [comment]
Finding this no longer works with newest version of watchify/browserify.

**Comment by FlorentD** [comment]
:-1:  this no longer works :-(

**Comment by alferov** [comment]
@FlorentD, try to add `this.emit("end")`

```
.on('error', function (err) {
  gutil.log(err.toString());
  this.emit("end");
})
```

**Comment by TrySound** [comment]
@FlorentD @alferov Maybe just callback? For me it works well
```js
.pipe(...)
.on('error', done)
```

**Comment by ThePixelPro** [comment]
`this.emit('end')` was the key.  Thanks @alferov
