### ISSUE TITLE
Options to make the default gulp messages off

### ISSUE THREAD

**Issue by kud** [gulpjs/gulp#492]
```
[gulp] Using gulpfile ~/Gulpfile.js
[gulp] Starting 'help'...
[gulp] Finished 'help' after 490 μs
```

Sometimes I don't want to see that, an option on the task to silent it could be great.

**Comment by hzlzh** [comment]
@kud Which way did you use at last?

**Comment by kud** [comment]
Nothing for the moment.

**Comment by hzlzh** [comment]
@kud So, you just leave it there?
`[gulp] Starting 'help'...` :cry:

**Comment by kud** [comment]
I use Make :D

**Comment by hzlzh** [comment]
@kud :sunglasses:

**Comment by HarveyWilliams** [comment]
It seems that because gulp is called before it is created in the code by running `gulp`, adding the the `--silent` flag in the code does not work.

However, if you run `node gulpfile.js`, you can add the silent flag before you require in gulp.

```
// This will cause gulp to be silent as long as you call "node gulpfile.js" and not "gulp".
process.argv.push('--silent');

var gulp = require('gulp');

**Comment by contra** [comment]
@hzizh The solution was posted already - use `--silent`

**Comment by HarveyWilliams** [comment]
@contra It's not possible to run Gulp in silent mode without using the silent flag. I feel like after you run `gulp`, it should be possible to pass further configuration into Gulp.

**Comment by vitto** [comment]
Yeah, I would do this way too.

Something like:

```
gulp.silent(true);
```

**Comment by phated** [comment]
Please stop requesting custom APIs. This will be supported once gulprc files are supported by the CLI. Locking.
