### ISSUE TITLE
Can't seem to solve "Invalid output folder" error

### ISSUE THREAD

**Issue by uberspeck** [gulpjs/gulp#496]
This is my first attempt at using Gulp. Regardless of what I do, I seem to just get an `Invalid output folder` error. I'm not trying to do anything fancy...

**gulpfile.js**

``` javascript
var config = require('./gulpconfig.json'),
    gulp = require('gulp'),
    sass = require('gulp-sass'),
    concat = require('gulp-concat')
gulp.task('scss', function(){
    gulp.src(config.scss)
        .pipe(sass())
        .pipe(concat('application.css'))
        .pipe(gulp.dest(config.build)) // Invalid output folder !?!?
});
gulp.task('default',['scss'])
```

**gulpconfig.json**

``` javascript
{
  "scss": ["/src/**/*.scss"],
  "coffee": ["/src/**/*.coffee"],
  "build": ["./build"]
}
```

**Folder structure**

```
/build
/src
    /app
        app.coffee
        app.scss
    /common
    /styles
        all.scss
gulpfile.js
gulpconfig.json
```

**Comment by evil-empire** [comment]
This also helped me. Fwiw, I had an additional problem in that I added a preceeding slash to my destinations, which also threw the error.
So basically _"dest": ["/public/vendors/"]_ became _"dest": "public/vendors"_  and voila, it works. Thanks!
