### ISSUE TITLE
Command "gulp" not found Mavericks OS

### ISSUE THREAD

**Issue by tcelestino** [gulpjs/gulp#510]
I'm trying install gulp in my Mac with Mavericks, but always this message show me:
![screen shot 2014-06-07 at 17 10 19](https://cloud.githubusercontent.com/assets/190265/3209680/ca136898-ee7f-11e3-80e1-12b3ee403de5.png)

Searching "gulp" node package, it's installed. Look:
![screen shot 2014-06-07 at 17 09 57](https://cloud.githubusercontent.com/assets/190265/3209685/f49ddbde-ee7f-11e3-9aab-705a92ce036c.png)

Anybody had this problem?

**Comment by zodthepossum** [comment]
I'm also getting the "gulp command not found", could someone help and let me know how to put gulp in my $PATH as per @sindresorhus comment above
thanks in advance

**Comment by Romanx** [comment]
Try this? http://architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/
