### ISSUE TITLE
working directory before changed to gulpfile.js location

### ISSUE THREAD

**Issue by yapcheahshen** [gulpjs/gulp#523]
scenario:
~/folder/gulpfile.js
~/folder/childfolder1   // no gulpfile.js in this folder
~/folder/childfolder2    // no gulpfile.js in this folder

running gulp under one of the child folder will load ~/folder/gulpfile.js

according to GULP change log 1.2-2.4 (11/12/13)
- chdir to gulpfile directory before loading it

therefore when gulpfile.js is loaded, process.cwd() == "~/folder" 

I want to share same gulpfile.js for all child folders,
my question is , how could the gulpfile knows it originate childfolder ?

**Comment by robert-blankenship** [comment]
@yapcheahshen Figured it out! :) Here's how you get the initial directory from Node:
``` coffeescript
console.log process.env.INIT_CWD #the initial directory
# ~/project/child_folder
console.log process.cwd() #gulpfile.js location
# ~/project

**Comment by taji** [comment]
@robert-blankenship : Looking for this for over two hours.  You are a life saver.  Thanks!
