### ISSUE TITLE
Who uses gulp?

### ISSUE THREAD

**Issue by sindresorhus** [gulpjs/gulp#540]
We would like to gather a list of projects/companies using gulp, for the website.

Let us know if your project/company uses gulp and wouldn't mind being mentioned on the website. Include a logo with a link to the project if you have one. And a link to the gulpfile if it's Open Source. A short description on how you use gulp and how it has helped you is also welcome.

**Comment by ncapito** [comment]
![image](https://cloud.githubusercontent.com/assets/601055/5695543/364d0d14-9977-11e4-90f1-40edc7004344.png)  uses gulp for almost all of their projects.  We are a .NET / AngularJS / PhoneGap shop.  We love gulp bc its so simple and natural to use.

**Comment by silvenon** [comment]
We use Gulp heavily at [Unity](http://unity.hr).

![logo_02](https://cloud.githubusercontent.com/assets/471278/8208510/4703c708-1508-11e5-8024-0d3e45a6ff57.png)

**Comment by limdauto** [comment]
Earlier this year at memrise.com, we have moved our entire client-side build process from python to gulp with great success.

![facebook 2x](https://cloud.githubusercontent.com/assets/2032984/8209245/de97c452-1503-11e5-959e-8c495c5467d6.png)

**Comment by liuggio** [comment]
http://www.chupamobile.com/   The best marketplace for  mobile application :)

[![http://www.chupamobile.com/images/chupamobile-logo.png](http://www.chupamobile.com/images/chupamobile-logo.png)](http://www.chupamobile.com/?utm=github-gulp)

Our new world (ab testing now you might no see the gulp)

**Comment by adambuczynski** [comment]
[Meanie](npmjs.com/package/meanie) is using Gulp, logo coming soon.

**Comment by artem-malko** [comment]
Project: TARS

Logo: 
![logo](https://cloud.githubusercontent.com/assets/1823689/8842982/d59b3eaa-311a-11e5-9f40-b068b55e3146.png)

**Comment by miralize** [comment]
![Logo](http://lovindublin.com/assets/images/sites/lovindublin/logo-inverted.png)

We use it for all of our sites 

http://lovindublin.com
http://lovintrends.com
http://lovinberlin.com

**Comment by SpaceBeers** [comment]
[Virgin Holidays](http://www.virginholidays.co.uk/) in the UK and we've started using Gulp in all new projects.

![image](https://cloud.githubusercontent.com/assets/912954/8856207/3e3a539c-3161-11e5-886d-2255e938ca7f.png)

**Comment by matyax** [comment]
![Pizza Pixel](http://pizzapixel.com/logo.jpg)
We use Gulp for our personal projects at www.pizzapixel.com and also in my fulltime job.

We use it to automate deployment processes and to compile static assets.

**Comment by glennphilp** [comment]
![UT Southwestern Medical Center]
(http://www.utsouthwestern.edu/resources/images/brand/ut-southwestern.png)

We use Gulp, here at UT Southwestern, for our front-end development.

**Comment by chdhmphry** [comment]
@thecharles has been using Gulp for projects for over a year now.

![tc12_logo_fa_secondary](https://cloud.githubusercontent.com/assets/1139784/8856408/b0887402-3138-11e5-9c5d-e846601401bb.jpg)

**Comment by dg1202** [comment]
![slogan-transparent-440x113](https://cloud.githubusercontent.com/assets/2365581/8856410/51ec2a72-3130-11e5-9716-a0308f88764b.png)

[Element Blue](http://www.elementblue.com/) uses gulp with its [SensorInsight](http://sensorinsight.io/) project. A platform for IIOT (sensor data)

**Comment by brandonb927** [comment]
At [sendwithus](https://www.sendwithus.com), we use Gulp to run the build process and assets pipeline for our Jekyll static site (landing pages).

![](https://www.sendwithus.com/assets/img/swu_kit_logo_dark.png)

**Comment by grayghostvisuals** [comment]
![](https://dl.dropboxusercontent.com/u/41114960/github/ggv/logo.svg)
**GRAY GHOST VISUALS**
*Site* : [http://grayghostvisuals.com](http://grayghostvisuals.com)
*Gulpfile* : [https://github.com/grayghostvisuals/grayghostvisuals/blob/development/gulpfile.js](https://github.com/grayghostvisuals/grayghostvisuals/blob/development/gulpfile.js)

Gulp is used for business site along w/other Open Source projects such as [Transformicons](http://transformicons.com). The gulpfile for that project can be found here: [https://github.com/grayghostvisuals/transformicons/blob/master/gulpfile.js](https://github.com/grayghostvisuals/transformicons/blob/master/gulpfile.js)

Mostly used to start servers, compile code, create builds, clean directories, minify assets, version rev and many more wonderful tasks this tool takes care of.

**Comment by w0rm** [comment]
We use gulp to lint, test and bundle static assets for online fashion store [https://zalando.de](https://zalando.de). Particularly we use it to combine svg icons together and generate png fallback, you may check [the demo here](https://github.com/zalando/compare-sprite-methods).

![zalando](https://cloud.githubusercontent.com/assets/43472/8856193/8e50aab8-3169-11e5-94fa-73dc5ad1e5ab.jpg)

**Comment by mvolkmann** [comment]
Maritz uses gulp to run JSHint, JSCS, LESS, Traceur, watch, and more.

**Comment by tonyspiro** [comment]
We :heart: Gulp at [The Brand Hatchery](http://brandhatchery.com)!

**Comment by shrunyan** [comment]
![zesty-logo](https://cloud.githubusercontent.com/assets/208819/8857032/aa8c4bec-3123-11e5-9265-29df1b7ad401.png)


Currently using gulp at [zesty.io](https://zesty.io) to bundle our application styles and javascript. Planning to run our tests, linting, and transpiling.

**Comment by SamVerschueren** [comment]
Using gulp quite heavily at [pridiktiv](http://www.pridiktiv.com) to minify our build and automatically generate our cordova builds with [gulp-cordova](http://www.github.com/SamVerschueren/gulp-cordova).

**Comment by juxton** [comment]
We use Gulp extensively at [Gloto](https://www.gloto.com) to build our web projects. It's been a breath of fresh air after our previous efforts with Grunt.

![Gloto Logo](https://www.gloto.com/wp-content/uploads/2014/12/gloto_logo_trans.png)

**Comment by zslabs** [comment]
We use Gulp at [BoomTown](http://boomtownroi.com) on both our frontend consumer sites and our backend CRM.

![boomtown](https://cloud.githubusercontent.com/assets/1018402/8859075/213f9d14-3149-11e5-8444-445c4d166a56.png)

**Comment by Steffen185** [comment]
We use Gulp at [ComputerBase](http://www.computerbase.de/) for our website frontend and backend (CMS).

* CSS: Sass, Autoprefixer, Pixrem, CSSWring
* JS: Concatenate, UglifyJS
* SVG: svgmin, svg2png, optipng, directory-encoder
* Watch + Livereload

![computerbase-logo 1920x911](https://cloud.githubusercontent.com/assets/1138129/8860395/cb0ee0e0-3183-11e5-9e68-7b867eab1582.png)

**Comment by navjinder** [comment]
one of the side project http://formspree-generator.navjinder.com/ 

__Formspree Generator__

![](https://raw.githubusercontent.com/navjinder/builtwith.angularjs.org/4c8536c6fb35c6dbbc4fc1c676ae98ccaf0bfeb4/projects/formspreegenerator/thumb.png)

**Comment by hmig** [comment]
We use gulpjs at <a href="http://giftcards.com">GiftCards.com</a> to streamline our entire front end build process.  With a single command, anyone from the team can be off and running with the latest tools being used. 
![giftcards_800 2x](https://cloud.githubusercontent.com/assets/1441938/8862218/e773e694-315c-11e5-8672-91b42efc67b4.png)


We also use it for <a href="http://www.omnicard.com">OmniCard.com</a>
![logo-omnicard](https://cloud.githubusercontent.com/assets/1441938/8861945/41e2f95a-315b-11e5-9fe6-92bb8e6a632e.png)

Thank you for doing such a great job with it!

**Comment by kmariano** [comment]
![octoblu-logo](https://cloud.githubusercontent.com/assets/565178/8863972/065be4cc-3152-11e5-843d-c5fd56f93bef.png)


[Octoblu](http://www.octoblu.com) is an Internet of Things platform that allows you to connect people, devices and software systems.   We use gulp for  several projects namely our (Octoblu web application)[https://app.octoblu.com and [Gateblu](https://gateblu.octoblu.com) our Internet of Things gateway application 

[Gateblu gulp file](https://github.com/octoblu/gateblu-ui/blob/master/gulpfile.coffee)

We <3 using Gulp

**Comment by stojanovic** [comment]
At [Cloud Horizon](http://cloudhorizon.com), we are using gulp in many of the projects we are working on.
ie. on our website, on some warehouse web apps optimized for tablets and many other projects.
We love to automate things and gulp is perfect tool for that.

![logo-small](https://cloud.githubusercontent.com/assets/613478/8864123/b5dabb16-319e-11e5-86f5-d779ec2ffd68.png)

**Comment by iGitScor** [comment]
At [1001pharmacies](http://1001pharmacies.com), we are using Gulp in all our projects.
We have created a kickstarter project for many kind of project

![1001pharmacies-1001startups](https://cloud.githubusercontent.com/assets/2276944/8869922/ca679f04-31e9-11e5-91e3-877ac0cc6cc8.jpg)

**Comment by LM450N** [comment]
At [4PLanet](https://sites.google.com/a/4planet.eu/4planetsiteweb/home), we are using Gulp for a project to manage users, made with [Polymer](https://www.polymer-project.org/1.0/) and love.

![logo_4planet](https://cloud.githubusercontent.com/assets/2325091/8871836/a7b64230-31f8-11e5-9061-e940cd0bd94a.png)

**Comment by benoitf** [comment]
We're using gulp to build the User Dashboard and Admin dashboard at [Codenvy](http://www.codenvy.com) !

![Codenvy white logo ](https://codenvy.com/images/logo@3x.png)
![Codenvy](https://www.eclipsecon.org/france2015/sites/default/files/styles/width-950/public/BlueCodenvyLogo.jpg?itok=4tOY1Gal)

**Comment by febLey** [comment]
We use it for all of our **frontend-, webapp- and mobileapp-projects** for more than a year.

We're using it in development with browsersync and after development to make the final build for deployment. Our favourite plugins are:

* browser-sync
* gulp-coffeescript
* gulp-postcss (with autoprefixer)
* gulp-sass
* gulp-uglify
* gulp-useref
* gulp-wiredep
* ... and many others

http://www.werdewelt.info/

![werdewelt](https://cloud.githubusercontent.com/assets/1727958/8909261/cafffcd8-3480-11e5-992d-adb8cd66b902.png)

**Comment by js0n** [comment]
![logo](https://cloud.githubusercontent.com/assets/27934/8909665/99fae77c-3450-11e5-9d73-f8d03eebf759.png)

We're using gulp for our front end build script at [BobbyPin](http://bobbypin.co/ "Bobbypin")!

**Comment by gbark1204** [comment]
Using Gulp at [SaveYa](https://www.saveya.com) for:
* dev sandbox builds
* production builds, including uploading resources to a cloud service.  
* condensing and combining css and js resources, local and third party
* downloading third party plugins from bower.io
* building angular apps
* running karma tests and eventually protractor

![SaveYa.com](https://www.saveya.com/assets/images/2x/saveya-new@2x.png)

**Comment by prio101** [comment]
Hi , I am Mahabub Islam Prio. I use Gulp where ever when ever I can .

**Comment by rangana** [comment]
we use Gulpjs at our office for building production releases of our latest product,
done with MEAN stack.
This is a back office admin portal application , therefore we don't have any external link to share with you guys.
I wrote the build file from scratch using gulp, and i am in love with gulp.

gulp is used 

- to minimize angular files
- to minimize css files
- to minimize html templates
- images optimization
- injecting resources according to the client

and many more.  :+1: 

our gulp build in web storm
![capture](https://cloud.githubusercontent.com/assets/305418/9129081/5b1e05fe-3cf0-11e5-92b5-e44b6121c498.PNG)

**Comment by marhalpert** [comment]
We use gulp @ Keno http://keno.com.au
Thanks!
<img width="343" alt="screen shot 2015-08-18 at 1 22 09 pm" src="https://cloud.githubusercontent.com/assets/745640/9321616/345b23ba-45ac-11e5-8cb1-f5d46793d259.png">

**Comment by Davei234** [comment]
We're a bunch of gulp fanatics @ <a href="https://www.getcroissant.com">Croissant</a>

We've even got a list of all the gulp plugins we use:
https://medium.com/@Croissant/40-npm-modules-we-can-t-live-without-36e29e352e3a

**Comment by metalim** [comment]
We at [Foxium](http://foxium.com/) use GulpJS to build our games.
![Foxium]
(http://foxium.com/wp-content/uploads/2015/07/foxium_logo.png)

**Comment by xandorxicay** [comment]
![ISkyhook Wireless](http://info.skyhookwireless.com/hs-fs/hub/287521/file-368518179-png/header-logo.png) 
www.skyhookwireless.com

**Comment by juanfran** [comment]
We use it at [Taiga](https://github.com/taigaio/)

![6905422](https://cloud.githubusercontent.com/assets/905195/9897337/3389903c-5c47-11e5-9e78-8e594fe9eef7.png)

**Comment by Saturate** [comment]
We use Gulp for most client projects at [Pentia A/S](http://pentia.dk).

![pentia_logo](https://cloud.githubusercontent.com/assets/453018/10728921/293d0320-7be6-11e5-8b3c-66f4b6b924aa.png)

**Comment by johnnycopperstone** [comment]
We use gulp here too at *Social.com*

![](http://i.imgur.com/bHX0SFB.png)

**Comment by tonyspiro** [comment]
We use Gulp at [cosmicjs.com](https://cosmicjs.com)

![01](https://cloud.githubusercontent.com/assets/1950722/11213655/c03bd062-8d02-11e5-84b2-ceaed1327ff2.png)

**Comment by huphtur** [comment]
Gulp is used for several projects at [Network Ninja](https://networkninja.com/).

[![NNI](https://cloud.githubusercontent.com/assets/469438/12117620/461733bc-b3c2-11e5-8d7a-10e72ee7b47c.png)](https://networkninja.com/)

**Comment by iGitScor** [comment]
An article about our automation workflow with gulp at [1001pharmacies](http://www.1001pharmacies.com) could be found here :

http://1001pharmacies.github.io/technique/industrialisation/industrialisation-front/

**Comment by voidl** [comment]
We are starting to use Gulp at [Vaporwhite](http://www.vaporwhite.com) for our Shopify deployment.
Using the [Google Web Starter Kit](https://developers.google.com/web/tools/starter-kit/?hl=en) gulpfile.js as a starting point.

![Vaporwhite Logo](http://cdn.shopify.com/s/files/1/0475/9397/t/9/assets/logo.png?13473348494086273731)

**Comment by blakeyc** [comment]
We use gulp at Universal Music Group

![image](https://cloud.githubusercontent.com/assets/694876/13713676/254625d8-e7c2-11e5-9cd3-3934b81fe99f.png)

**Comment by tanmynguyen** [comment]
Thanks all Bro!!! <3

**Comment by Stephn-R** [comment]
We use gulp at Gartner Inc. !

![Gartner](http://www.ignitionone.com/wp-content/uploads/2015/10/gartner-logo-vector1.jpg)

Our new Gartner Events Calendar was built using Gulp!

http://www.gartner.com/events/

**Comment by gregrickaby** [comment]
We love Gulp at [WebDevStudios](https://webdevstudios.com) and use it in our starter theme, [wd_s](https://github.com/WebDevStudios/wd_s)!

![wds-logo-withslogan](https://cloud.githubusercontent.com/assets/200280/14641112/4f8712ec-060a-11e6-834a-18e8be0efe8f.png)

**Comment by phated** [comment]
Hey everyone that uses gulp at their company!  I just wanted to let you know that the gulp team has recently set up an Open Collective to help out with sponsorship.  You can find all the details at https://opencollective.com/gulpjs

When you become a sponsor or backer, you picture/logo shows up at the bottom of our README and will eventually be embedded on our website (once the redesign kicks off).

Please consider sponsoring us!

Thanks,
-Blaine

**Comment by malchata** [comment]
I use gulp in my own development outside of work, but if it makes any difference, I'm writing a chapter on using it to automate optimization/performance workflow in my upcoming book from Manning Publications on the topic of web performance.

**Comment by SalahAdDin** [comment]
Wow, awesome.

**Comment by AfterbuyAxel** [comment]
We at [Afterbuy](https://www.afterbuy.de) use it for internal microservices.
[![image](https://cloud.githubusercontent.com/assets/1918472/18950443/199b95fc-8640-11e6-958e-51f2349718cd.png)](https://www.afterbuy.de)

**Comment by jurca** [comment]
[IMA.js](https://imajs.io/) - platform for creating isomorphic JavaScript web applications by [Seznam.cz](https://www.seznam.cz/).

![](https://imajs.io/static/img/imajs-logo.png)

We use gulp as general task runner for running build- & development-related tasks.

A link to a gulpfile is actually multiple links, as we split the tasks into multiple files:
https://github.com/seznam/IMA.js-gulp-task-loader
https://github.com/seznam/IMA.js-gulp-tasks/tree/next/tasks

**Comment by hougasian** [comment]
[Ritter Insurance Marketing](https://ritterim.com) (RIM) is a Field Marketing Organization (FMO) in the Senior Life and Health Insurance markets. That means we promote and distribute insurance carriers’ products to licensed agents.

![ritterlogo](https://cloud.githubusercontent.com/assets/6231956/19973729/7001797e-a1bc-11e6-8559-e53c76aad2e2.jpg)

We use gulp as our task runner for [Medicareful.com](https://medicareful.com), our Medicare quote engine, [eBrokerSoftware's](https://ebrokersoftware.com) ACA quote and enroll engine, and several internal apps, production and in development.

**Comment by contra** [comment]
Anyone who is a CTO/CEO/Head of Product/etc. want to give a testimonial for our website? You'll be featured with a big quote attributed to you.

If so, post a response and I'll pick the best one.

@jessepollak @blakeyc @johnnycopperstone @kmariano @silvenon @DonutEspresso @epitaphmike @hswolff @timmywil @ryan-roemer @zertosh and others

**Comment by ddtth** [comment]
We use Gulp at [Different Diet Tips](http://different.diet).

I kind of feel like we've only scratched the surface of what we can get out of Gulp but right now we're using it to:

1) Compile SASS to CSS, combine, and minify
2) Combine and uglify JavaScript

Using these libs:

-gulp-sass
-gulp-clean-css
-gulp-concat
-gulp-uglify

**Comment by Mohammed9531** [comment]
We use gulp at https://www.cvs.com/

**Comment by CKGrafico** [comment]
We've used Gulp for some projects

- https://github.com/Microsoft/BikeSharing360_Websites/tree/master/PublicWeb
- https://github.com/CKGrafico/Cordova-Multiplatform-Template/tree/master/App
- https://github.com/CKGrafico/Frontend-Boilerplates
- https://github.com/CKGrafico/Why-TypeScript

**Comment by CodeMan99** [comment]
Using gulp at [ChartIQ](https://www.chartiq.com). With `gulp` we:

 * manage our build process
 * process our documentation
 * create customer specific releases

![ChartIQ Logo](https://www.chartiq.com/wp-content/plugins/ciq-assets-downloader/dist/img/svg/full_color.svg)

**Comment by xianghongai** [comment]
We use Gulp:
![national-culture-logo](https://user-images.githubusercontent.com/2075006/34237286-c5d401ae-e636-11e7-89f8-f503289325f4.png)

**Comment by SalahAdDin** [comment]
Very interesting.

**Comment by anselmbradford** [comment]
We use it https://github.com/cfpb/cfgov-refresh/tree/master/gulp

![CFPB logo](https://www.consumerfinance.gov/static/img/logo_237x50@2x.1a8febf782f9.png)

**Comment by ibc** [comment]
We use gulp in:

#### mediasoup

*Cutting Edge WebRTC Video Conferencing*

https://mediasoup.org

<img width="937" alt="mediasoup_banner" src="https://user-images.githubusercontent.com/16191/34939859-a8c97772-f9ed-11e7-9519-7b6c4c745136.png">

#### JsSIP

*The JavaScript SIP Library*

http://jssip.net

![jssip-banner-new](https://user-images.githubusercontent.com/16191/34939872-badaa3aa-f9ed-11e7-8dcb-2a49187373bb.png)

**Comment by getmuddii** [comment]
we use gulp at https://muddii.com

**Comment by cedric05** [comment]
vscode uses gulp https://github.com/microsoft/vscode

**Comment by luchillo17** [comment]
In progress Angular library with Gulp 4 and TypeScript `gulpfile.ts` https://github.com/luchillo17/rxjs-socket-service

No logo (yet?...).

**Comment by james-nash** [comment]
![buildit-logotype](https://user-images.githubusercontent.com/16718916/48703277-1c556300-ebeb-11e8-83d2-9c380b232a9e.png)

We frequently use Gulp for client work as well as our own internal projects at [Buildit](https://buildit.wiprodigital.com/). Most of our client stuff is under NDA (but does include some well-known brands). Notable internal projects using Gulp are:

* [Our website](https://github.com/buildit/buildit)
* Our design system's [UI components and pattern library](https://github.com/buildit/gravity-ui-sass)

Thanks for making Gulp! Keep up  the great work!

**Comment by Zardoz89** [comment]
We use Gulp 4 at [Digibís](http://www.digibis.com/) to process and compile our frontend files.

Some sites that we made are : 
- [The Norman Foster Foundation's Archive](http://archive.normanfosterfoundation.org/en/inicio/inicio.do)
- [Archivo Fundación Felipe Gonzalez](https://archivo.fundacionfelipegonzalez.org/es/inicio/inicio.do)
- [L'Arxiu Municipal de Castelló](http://arxiumunicipal.castello.es/castellonbib/ca/home/home.do)

**Comment by syagawa** [comment]
We use Gulp4 in the phonegap(cordova) project to compile mobile app.
Our app is https://www.team-manage.com/ .

And, when exporting JS and CSS, call webpack from gulp and use it.

**Comment by ataylorme** [comment]
[WP Rig](https://github.com/wprig/wprig) uses gulp 4

**Comment by cedx** [comment]
At [SAB International](http://www.sabcomputer.com), we use Gulp 4 on all our CLI and Front End projects. As a task launcher, we use it for any kind of operation: compile/generate the assets, lint the code, check the project dependencies, perform file system actions, run the unit tests, etc.

![SAB Logo](https://user-images.githubusercontent.com/1643950/71407606-ca77db80-263b-11ea-8cbb-401f08729020.png)

A sample Gulp file, as we have on our projects:
https://github.com/sab-international/rich-text-editor/blob/master/gulpfile.ts
