### ISSUE TITLE
Gulp throwing “pre-build test failed” errors at end of tasks execution

### ISSUE THREAD

**Issue by teabow** [gulpjs/gulp#553]
At the end of every Gulp task i'm having the same “pre-build test failed” error.
Here is a trace of this error :

<pre>
C:\dev\yo\backbone>gulp mytest
[12:34:41] Using gulpfile C:\dev\yo\backbone\gulpfile.js
[12:34:41] Starting 'mytest'...
mytest
[12:34:41] Finished 'mytest' after 370 µs
? pre-build test failed, compiling from source...
? pre-build test failed, compiling from source...
? pre-build test failed, compiling from source...
? pre-build test failed, compiling from source...
? Error: getaddrinfo ENOTFOUND
? Error: getaddrinfo ENOTFOUND
? pre-build test failed, compiling from source...
? Error: getaddrinfo ENOTFOUND
? Error: getaddrinfo ENOTFOUND
libpng-dev is installed

{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall:
 'getaddrinfo' }
</pre>

Here is the related task : 

<pre>
gulp.task('mytest', function () {
  console.log('mytest');
});
</pre>

It seems like some network operations are launched but I don't understand why since the task doesn't request anything and has finished when the errors are printing. 
I'm working behind a corporate proxy server that must block these network operations.

**Comment by DomDomDomDomDom** [comment]
Had a similar problem: 
```[16:37:57] Starting 'build'...
Bundle built in 2ms
[16:38:00] Finished 'build' after 3.49 s

... Uhoh. Got error getaddrinfo ENOTFOUND ...
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```
mine was caused by a malformed hosts file, missing :
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
fe80::1%lo0	localhost
```
