### ISSUE TITLE
Fails on non-standard path characters

### ISSUE THREAD

**Issue by dusbuss** [gulpjs/gulp#616]
I beat my head against a wall for HOURS on this issue.  I'm not sure if it's core to Gulp or just the way that the packages are handles, but hopefully this can help someone.

I had a path that contained bracket characters, like: "~/Desktop/[gulp]"

When I cd to the directory, it worked fine
    cd ~/Desktop/\[gulp\]/", it worked fine

When I ran "gulp scripts" it SEEMED to work fine
    Using gulpfile ~/Desktop/[gulp]/gulpfile.js
    Starting 'scripts'...
    Finished 'scripts' after 7.53 ms

But... nothing happened. No errors, no output... nothing.

I tried with many packages, and I couldn't get any of the "hello world" examples to work (jshint, gulp-concat, etc)

Finally, I moved the whole thing to a new directory without the characters, and it worked fine!

At any rate, the "[" and "]" characters seems to silently break the process.

**Comment by holographix** [comment]
I just lost the entire morning working out a problem with gulp, just to later discover that it was related to the fact the my path was containing a nice pair of square brackets. damn't!

*[ FYI ]*


The incriminated path was "/Users/aaron/Works/The new App/repo [GIT]/"
I'm using 

ionic 1.0.1
ionic-cli 1.6.4
gulp 3.9.0
sass 3.4.15
node 0.12.7
running on OSX Yosemite 

here is comes the gulp file

      var gulp = require('gulp');
      var gutil = require('gulp-util');
      var bower = require('bower');
      var concat = require('gulp-concat');
      var sass = require('gulp-sass');
      var minifyCss = require('gulp-minify-css');
      var rename = require('gulp-rename');
      var sh = require('shelljs');

      var paths = {
        sass: ['./scss/**/*.scss']
      };

      gulp.task('default', ['sass']);

      gulp.task('sass', function(done) {
        gulp.src('./scss/ionic.app.scss')
          .pipe(sass({
            errLogToConsole: true
          }))
          .pipe(gulp.dest('./www/css/'))
          .pipe(minifyCss({
            keepSpecialComments: 0
          }))
          .pipe(rename({ extname: '.min.css' }))
          .pipe(gulp.dest('./www/css/'))
          .on('end', done);
      });

      gulp.task('watch', function() {
        gulp.watch(paths.sass, ['sass']);
      });

      gulp.task('install', ['git-check'], function() {
        return bower.commands.install()
          .on('log', function(data) {
            gutil.log('bower', gutil.colors.cyan(data.id), data.message);
          });
      });

      gulp.task('git-check', function(done) {
        if (!sh.which('git')) {
          console.log(
            '  ' + gutil.colors.red('Git is not installed.'),
            '\n  Git, the version control system, is required to download Ionic.',
            '\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
            '\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.'
          );
          process.exit(1);
        }
        done();
      });


It would be really nice to see those kind of annoying bugs go away for good in the next iteration.

**Comment by phated** [comment]
@holographix posting here isn't helpful, you need to comment on the linked minimatch issue, as it doesn't get any responses from the library author.

**Comment by contra** [comment]
Again, if you are having trouble please post about it on the minimatch issue - this is not our bug to solve,.

**Comment by phated** [comment]
We've switched to micromatch in gulp 4.  Hoping this is fixed over there.  If not, an issue needs to be created for them.  /cc @es128 @jonschlinkert
