### ISSUE TITLE
Gulp dependency filepaths too long for Windows

### ISSUE THREAD

**Issue by brantleye** [gulpjs/gulp#626]
My Jenkins build server is a Windows machine, and jenkins can't clean the workspace on each build because the filepaths for some Gulp dependencies are over 255 characters- which makes Windows choke.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.findindex@3.0.0
└─┬ lodash._basecallback@3.2.0
  ├─┬ lodash._baseisequal@3.0.1
  │ ├── lodash.isarray@3.0.0
  │ └── lodash.istypedarray@3.0.0
  ├── lodash._bindcallback@3.0.0
  └─┬ lodash.keys@3.0.3
    ├── lodash.isarguments@3.0.0
    ├── lodash.isarray@3.0.0
    └── lodash.isnative@3.0.0
```
