### ISSUE TITLE
File path length

### ISSUE THREAD

**Issue by robertmain** [gulpjs/gulp#630]
When working with gulp on a Windows machine, the setup of gulp results in a file path that is too long for Windows to be able to delete. This makes it difficult to delete any folder containing gulp.

![Long directory tee](https://camo.githubusercontent.com/e45821a8a9be19854ddcfa6f9ac43296c6fa520e/687474703a2f2f696d6775722e636f6d2f456230567237582e6a7067)

![Do you want to delete](https://camo.githubusercontent.com/49945ae5d84fe83286dc8cdf4fb94d18675bd553/687474703a2f2f692e696d6775722e636f6d2f4635457253534c2e706e67)

Clicking "Yes" then results in an error message saying the file path is too long
![File path too long](https://camo.githubusercontent.com/e6cd4930c4f3caf80068c7ae9fbb4a89cfafb1fc/687474703a2f2f692e696d6775722e636f6d2f574c576e4a66732e706e67)

Obviously on a Linux machine or a Mac, this isn't an issue, but I'm part of a team that are considering using gulp for work and are therefore using Windows machines.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.findindex@3.0.0
└─┬ lodash._basecallback@3.2.0
  ├─┬ lodash._baseisequal@3.0.1
  │ ├── lodash.isarray@3.0.0
  │ └── lodash.istypedarray@3.0.0
  ├── lodash._bindcallback@3.0.0
  └─┬ lodash.keys@3.0.3
    ├── lodash.isarguments@3.0.0
    ├── lodash.isarray@3.0.0
    └── lodash.isnative@3.0.0
```
