### ISSUE TITLE
constant CPU usage on watch

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [gulpjs/gulp#634]
i see constant CPU usage around 12% on quite small number of files. ~230 *.php files.
no files changing at that time, no other watchers, no action at all.

CPU: i7 2.2
Mac OS X 10.9.4
node -v
v0.10.30
gulp -v
[02:08:51] CLI version 3.8.7
[02:08:51] Local version 3.8.7

watcher:

```
gulp.task('default', function (){
    gulp.watch('_lara/app/**/*.php', ['codecept']);
})
```

**Comment by unphased** [comment]
Hey guys, so... CPU usage should be 0% because polling is wrong. Does anybody agree?

I mean, I would use slightly less strong phrasing if this is actually a point of contention. But I mean... this is 2015. There are filesystem APIs.
