### ISSUE TITLE
gulp.options.silent = true

### ISSUE THREAD

**Issue by xpepermint** [gulpjs/gulp#641]
As I can see from the source the `silent` options is only available from the command-line. Any way to do it like:

```
var gulp = require('gulp');
gulp.options({ silent: true }); // or something
```

**Comment by erwinw** [comment]
Not a gulp specific option, but try `sandboxed-module` if you really want to silence a particular plugin. It allows you to monkeypatch requires from modules, thus also enabling you to add logic to only `gulp-rev-all` 's `gutil.log` statements.
