### ISSUE TITLE
Add recipe to integrate grunt tasks into gulp

### ISSUE THREAD

**Issue by geekflyer** [gulpjs/gulp#646]
Hi, I just found with the latest grunt version it's possible to run tasks without the grunt cli and without a gruntfile. That makes it possible to run grun tasks within gulp relatively seamlessly (and without a plugin) and I was able to remove `gulp-grunt` from our project, which caused some issues.

**I'm just wondering if you would accept a pull request for a recipe on that topic (before I invest my time).**

Here's some more info on this new grunt option:
https://github.com/gruntjs/grunt/commit/77155e3f61d213c529a16ea595fc486fdeca28c9

**Comment by phated** [comment]
@geekflyer this looks like it shipped with grunt 1.0 - did you want to resubmit?  If not, I will close this soon.

**Comment by phated** [comment]
Completed by #1592
