### ISSUE TITLE
Exclude expression must be same as match expression

### ISSUE THREAD

**Issue by teamrun** [gulpjs/gulp#652]
i found this issue ealier today: 

    var file2w = ['js/**/*.js', '!js/bundle.js'];
    gulp.watch(file2w, ['bundle']);
    gulp.watch(file2w, function(file){
        console.log(file.path);
    });

watch files under `js` folder and bundle out a `bundle.js` file. When exclude expression `!js/bundle.js` became `!./js/bundle.js`, although these two expression have the same meaning (all means relative path, 'js' folder), the exclude won't work, logs out `bundle.js` file path.

change `file2w` to this:

    var file2w = ['js/**/*.js', '!./js/bundle.js'];

re run gulp task, here is the log:

    [12:42:17] Starting 'bundle'...
    /Users/chenllos/Documents/dev/ReacFlux/Flux-Todo/js/app.js
    [12:42:17] Finished 'bundle' after 66 ms
    [12:42:17] Starting 'bundle'...
    /Users/chenllos/Documents/dev/ReacFlux/Flux-Todo/js/bundle.js
    [12:42:17] Finished 'bundle' after 76 ms

i think i am already an experienced gulp user. i made this mistake and had no idea until a few minutes ago. If you guys think it is a bug, i hope you fix it soon. If not, i think this worth well documented.

**Comment by heikki** [comment]
If this is a bug, the functionality needs to be changed for `gulp.src` too.

**Comment by contra** [comment]
merging into #651

**Comment by contra** [comment]
@heikki This is only an issue with watch I think src should work just fine

**Comment by heikki** [comment]
Yes, src seems to work fine.
