### ISSUE TITLE
Output is unreadable with Solarized theme

### ISSUE THREAD

**Issue by djensen47** [gulpjs/gulp#656]
I'm using iterm2 on Mac OSX with the official Solarized theme. Unfortunately there is an issue with the theme and certain dark colors. The following is the output from running `gulp`:

![screen shot 2014-09-02 at 12 29 41 pm](https://cloud.githubusercontent.com/assets/527865/4124351/b7a9d592-32d7-11e4-8f66-0c67af2b6258.png)

Note: this is related to altercation/solarized#220 but it seems highly unlikely that it will be fixed on the Solarized side.

**Comment by revolter** [comment]
So you linked an issue that links back to this issue?
