### ISSUE TITLE
How can I gulp with ES6/Harmony

### ISSUE THREAD

**Issue by hiddentao** [gulpjs/gulp#66]
My module uses ES6/Harmony features and as such I need to run node like this:

``` js
node --harmony <app.js>
```

(There's no way of enabling Harmony features at runtime - [see this](http://stackoverflow.com/questions/19437241/enable-harmony-es6-features-in-v8-at-runtime-in-a-module)).

So to get gulp working I'm doing this:

``` js
node --harmony `which gulp`
```

Not nice, but it works. Unfortunately even if the build fails the exit code for the run is 0. Is there any way of getting this working?

**Comment by mik01aj** [comment]
A better way would be to use harmonize. See: http://stackoverflow.com/a/28412779/115493

**Comment by ratbeard** [comment]
Note that using harmonize doesn't allow you to use es6 syntax in the gulpfile.js itself.
