### ISSUE TITLE
Error: EPERM

### ISSUE THREAD

**Issue by Gazzo100uk** [gulpjs/gulp#660]
I'm getting the following error when running gulp tasks: Error: EPERM, open 'filename....'

Any idea what is causing this or how do I investigate the issue and resolve it?

Regards,
Gary

**Comment by sacredobelisk** [comment]
Anyone else have any luck being able to reproduce this? Or found a solution that I haven't had luck finding?

**Comment by schleumer** [comment]
I got the same problem and possible sources. When I found the same problem the first first thing I did was check which files gulp was hanging on(lsof) and, bang, there was the file which del couldn't clean.

First possible source: Browserify keep files opened so del can't clean the directory;
Second possible source: Vinyl-source keep files opened so del can't clean the directory;
Third possible source: gulp.dest keep files opened after write so del can't clean the directory;

But i think it's  more Browserify or Vinyl problem than gulp itself.

My OS at moment is Windows 8.1, also tested in OS X Yosemite and ArchLinux. File permissions are ok and triple checked.

It's my gulpfile https://gist.github.com/schleumer/9e07d040d1a773511405 of course it's not complete, i just removed useless tasks which is not related.

**Comment by contra** [comment]
@schleumer It's browserify or gulp-watch, none of the other things actually touch the file system they just deal with the in-memory files.

**Comment by contra** [comment]
@sacredobelisk I downloaded your test repo and I am able to reproduce, but the bug is from browserify not from gulp. You installed the browserify module, created a bundle, and then the bundle throws an error. This has nothing to do with gulp, so the issue should be opened on browserify or you should check if there already is one. You should completely remove gulp from the equation when opening that issue so it is easier for them to reproduce and diagnose it.

**Comment by schleumer** [comment]
Thanks, @contra! I'll move my issue to Browserify and gulp-watch, because  gulp-watch already have some issues like mine and this don't happen only with Browserify, kinda weird. Thanks again, sorry for the mess.

**Comment by sacredobelisk** [comment]
Will do. Thanks, @contra!

**Comment by keberox** [comment]
Just for whatever is worth to mention, I was having the EPERM error, what rang a bell was what @contra mentioned about gulp using the same permissions from the input file to write the output file, in my case I am sadly stuck with Clear Case for source control, and it is a pain to work with, all files that are read in a "non-checked out" state will end up being written as read only and next time the build runs, it errors out, my solution: try to check out all files before running the build tasks.

This may be a totally different problem from what everybody else is having, but just wanted to confirm on the statement of how gulp handles file permissions.

**Comment by nover** [comment]
I'm writing this as it goes in thread with what @keberox is mentioning. I'm currently working for a client who is using Microsoft TFS 2013 (sigh). Sadly TFS is exhibiting the same behavior as "Clear Case". If files are not "checked out for editing" they will have a read-only flag set. Thus, the first `gulp` works fine, but subsequent runs fails with `EPERM, Open` errors. Bower and other tools are having similar issues. The only solution so far for me is to "check out" the entire project with gulp / bower dependencies, which kinda suck.

Is it possible to get gulp to NOT set the read-only flags on the output files, or is this overly complex? :)

**Comment by feiwaltan** [comment]
@nover 
Currently I am also using TFS 2013 but no longer encounter the issue with gulp EPERM error.

We resolved this by making the tfs workspace local, this also allows us to work offline if tfs goes down and we haven't had any issues with merging changes.

Reference to configure: https://msdn.microsoft.com/en-us/library/gg490753(v=vs.100).aspx

**Comment by KE-Cbu** [comment]
I got the same problem.. With TFS 2013. I change my workspace from server to local and it solves this point.

**Comment by mvarblow** [comment]
I have the same problem with TFS, but don't have the option to use a local workspace due to the size of our solution.  Is it possible to get gulp to NOT set the read-only flags on the output files?

**Comment by feiwaltan** [comment]
@mvarblow  There's a way to create a gulp task that would allow you to update the file permission from read to write, but that would be problematic when you check stuff back in, might have merge conflicts on each checkin.

Here is a library that will assist with that: https://www.npmjs.com/package/gulp-chmod

**Comment by EjaYF** [comment]
Thanks @feiwaltan for sharing this. I use gulp in VS2015 for copying from /js to /jsdest which is the folder from where I am referencing the scripts in my browser. I only edit the /js files, so no problems with local workspace or TFS issues for me :)

**Comment by 8raveStarr** [comment]
@EjaYF How did you include your /jsdest folder in the project so it would publish that content, but not include it in source control/TFS? I have tried to select the files and use the Files > Source Control > Advanced > Exclude File from Source Control, but that still sets a read-only property on the file. That then causes issues with Gulp.

**Comment by EjaYF** [comment]
@8raveStarr I think your solution is fine. Make sure the file is not readonly. And use
`        .pipe(chmod(755)) 
`
I guess from that moment you won't have read-only attributes anymore...

**Comment by EjaYF** [comment]
@8raveStarr I was facing the exact problem as you did now... This helped me: http://stackoverflow.com/questions/29483772/remove-windows-file-readonly-attribute-in-gulp-file

The solution is to remove the readonly attribute beforehand:

`
require("child_process").exec("attrib -r <dir-name>\*.* /s");
`

**Comment by yogeshnikam** [comment]
I have one problem related to setting the permission for js file, I am using gulp for combining multiple files into one. For that's what i am doing i am setting permission for the compiled file. Using  gulp-chmod package, so that  I can set the permission for the files, 
Suppose i set write:false and run gulp it will set the file read only, but at the time of again removing the permission I am going to set write:true but that time I am getting the error. EPERM:  Operation not permitted, this is because of that read-only property true for the compiled file. If i manually remove the read-only property and run gulp again it will resolve. But I want to remove that property using gulp if i set the option write: true still i am getting error, is there another way to resolve the issue.

**Comment by golddragon007** [comment]
Actually I have simmilar problem... Actually I start the watch task, once it compile from less to css, than when it's start the real watch, it's dies.
Console:
[23:03:47] Using gulpfile /mnt/d/phptest/[...]/gulpfile.js
[23:03:47] Starting 'less'...
[23:03:49] Finished 'less' after 1.83 s
[23:03:49] Starting 'default'...
[23:03:49] 'default' errored after 13 ms
[23:03:49] Error: watch /mnt/d/phptest/[...]/less/ EPERM
    at exports._errnoException (util.js:1012:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/mnt/d/phptest/[...]/node_modules/gaze/lib/gaze.js:289:30)
    at /mnt/d/phptest/[...]/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/mnt/d/phptest/[...]/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/mnt/d/phptest/[...]/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/mnt/d/phptest/[...]/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/mnt/d/phptest/[...]/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/mnt/d/phptest/[...]/node_modules/gaze/lib/gaze.js:74:10)

gulpfile.js
/*global -$ */
'use strict';
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var less = require('gulp-less');

// Error notifications
var reportError = function(error) {
  $.notify({
    title: 'Gulp Task Error',
    message: 'Check the console.'
  }).write(error);
  console.log(error.toString());
  this.emit('end');
}

// less processing
gulp.task('less', function() {
  return gulp.src('less/style.less')
    .pipe($.sourcemaps.init())
    // Convert less into css
    .pipe($.less({
      outputStyle: 'nested', // libless doesn't support expanded yet
      precision: 10
    }))
    // Show errors
    .on('error', reportError)
    // Autoprefix properties
    .pipe($.autoprefixer({
      browsers: ['last 2 versions']
    }))
    // Write sourcemaps
    .pipe($.sourcemaps.write())
    // Save css
    .pipe(gulp.dest('css'));
});

// process JS files and return the stream.
gulp.task('js', function () {
    return gulp.src('js/*.js')
        .pipe(gulp.dest('js'));
});

// Optimize Images
gulp.task('images', function() {
  return gulp.src('img/*')
    .pipe($.imagemin({
      progressive: true,
      interlaced: true,
      svgoPlugins: [{
        cleanupIDs: false
      }]
    }))
    .pipe(gulp.dest('img'));
});

// JS hint
gulp.task('jshint', function() {
  return gulp.src('js/*.js')
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish'))
    .pipe($.notify({
      title: "JS Hint",
      message: "JS Hint says all is good.",
      onLast: true
    }));
});

// Beautify JS
gulp.task('beautify', function() {
  gulp.src('js/*.js')
    .pipe($.beautify({indentSize: 2}))
    .pipe(gulp.dest('js'))
    .pipe($.notify({
      title: "JS Beautified",
      message: "JS files in the theme have been beautified.",
      onLast: true
    }));
});

// Compress JS
gulp.task('compress', function() {
  return gulp.src('js/*.js')
    .pipe($.sourcemaps.init())
    .pipe($.uglify())
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('js'))
    .pipe($.notify({
      title: "JS Minified",
      message: "JS files in the theme have been minified.",
      onLast: true
    }));
});

// Run drush to clear the theme registry
gulp.task('drush', function() {
  return gulp.src('', {
      read: false
    })
    .pipe($.shell([
      'drush cc css-js',
    ]))
    .pipe($.notify({
      title: "Caches cleared",
      message: "Drupal CSS/JS caches cleared.",
      onLast: true
    }));
});

// Default task to be run with `gulp`
gulp.task('default', ['less'], function() {
  gulp.watch("less/*.less", ['less']);
  gulp.watch("js/*.js", ['js']);
});

OS: windwos 10, script running from bash on windows console, also, it was installed the linux version of everything. All files are set to anybody can read/write/execute from linux console, and in window permission, the administrator, user, anybody roles has full (complette) permission (read/write/execute/etc). 

Anybody?

**Comment by Newtsrock** [comment]
I'm getting the same exact issue

**Comment by cocoademon** [comment]
Hello all, I had the same issue on Windows with Browserify/Babelify.

I resolved it by adding the buffer stage to the pipeline, ie changing:

````js
return bundler
        .bundle()
        .on('error', gutil.log.bind(gutil, 'Browserify Error'))
        .pipe(source('content/js/main.js'))
        .pipe(gulp.dest('build'));
````

to:
````js
var buffer = require('vinyl-buffer');

...

return bundler
        .bundle()
        .on('error', gutil.log.bind(gutil, 'Browserify Error'))
        .pipe(source('content/js/main.js'))
        .pipe(buffer())
        .pipe(gulp.dest('build'));
````

I haven't investigated *why* this is so important yet.

@schleumer Can you try changing your Gulpfile as follows:

````js
var buffer = require('vinyl-buffer'); // at top

b.bundle()
    .pipe(source('app.js'))
    .pipe(buffer())
    .pipe(gulp.dest('./dist/js'))
```

**Comment by Newtsrock** [comment]
I will definitely add that to mile gulpfile

**Comment by Newtsrock** [comment]
My**

**Comment by golddragon007** [comment]
I've put before every .pipe(gulp.dest(*)) the .pipe(buffer()) line, and still I get the same error. I think there's something error in the watch... because the stand alone less task works.

**Comment by edson-** [comment]
We resolved this by giving read/write permissions to the Node application directory/node_modules.  Node uses its own node_modules directory during gulp processing.  We found that some users had read only permissions for anything in the Program Files directory - based on the image used (we were on PCs, not sure Mac is same).  

Another way to avoid this might be to install Node elsewhere - the root drive, for example.

**Comment by tegmos** [comment]
After a couple hours of flailing about trying to fix this,  finally found @cocoademon solution and it worked for me. Same issue with Vinyl/Browserify.

**Comment by chantmich** [comment]
I've had that error while using gulp and realized that atom still had the old version of the file opened after I pulled from github. 

All I had to do was close Atom and run gulp again. 

Voila! no more error.

**Comment by pestbarn** [comment]
Also having issues with EPERM, but _only_ on my `watch` task. All tasks run fine except for this one.

**Simplified gulpfile:**
```javascript
var gulp             = require('gulp');
var postcss          = require('gulp-postcss');
var postcss_cssnext  = require('postcss-cssnext');
var precss           = require('precss');
var postcss_magician = require('postcss-font-magician');
var clean_css        = require('gulp-clean-css');
var concat_css       = require('gulp-concat-css');
var automath         = require('postcss-automath');
var vfs              = require('vinyl-fs');
var livereload       = require('gulp-livereload');
var pump             = require('pump');

var paths = {
    css: {
        base:       './src/postcss/**/*.postcss',
        normalize:  './node_modules/normalize.css/normalize.css'
    }
};

const css = Object.keys(paths.css).map(key => paths.css[key]);

var processors = [
    postcss_cssnext,
    precss,
    postcss_magician,
    automath
];

gulp.task('css', function(callback){
    pump([
        vfs.src([css[1],css[0]]),
        postcss(processors),
        concat_css('main.min.css'),
        clean_css(),
        vfs.dest('./bin/css/'),
        livereload()
    ], callback);
});

gulp.task('watch', function() {
    livereload.listen();
    gulp.watch(css[0], ['css']);
});
```

**Complete error message:**
```bash
root@PESTBARN-PC:/mnt/f/www/v2# gulp watch
[20:24:06] Using gulpfile /mnt/f/www/v2/gulpfile.js
[20:24:06] Starting 'watch'...
[20:24:06] 'watch' errored after 27 ms
[20:24:06] Error: watch /mnt/f/www/v2/src/postcss/ EPERM
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/mnt/f/www/v2/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
```

This error only occurs when running on Windows (Bash). On a Unix system, it works completely fine. Also, I've checked the permissions for every file and folder in the project, which are all `rwxrwxrwx`.

**Comment by ForsakenHarmony** [comment]
it's a bug with bash for windows fixed in build [14942](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes?f=255&MSPPError=-2147217396#build-14942)

**Comment by phated** [comment]
@ForsakenHarmony do you know if that has shipped in the official channel yet?

**Comment by ForsakenHarmony** [comment]
@phated going by my windows build version: No

**Comment by McQuinTrix** [comment]
This might be related to permissions. I just did my gulp task with sudo and it worked perfectly.

`sudo gulp`

**Comment by aaronamm** [comment]
Using `vinyl-buffer`  @cocoademon  mentioned, fix issue on my computer.
This is my gulp file.

```

const gulp = require("gulp");
const jasmine = require("gulp-jasmine");
const clean = require("gulp-clean");
const runSequence = require("run-sequence");
const source = require("vinyl-source-stream");
const buffer = require("vinyl-buffer");
const browserify = require("browserify");
const tsify = require("tsify");

let paths = {
    src: [
        "src/**/*.ts",
    ],
    content: [
        "src/**/*.json",
        "src/**/*.html",
        "src/**/*.css",
        "src/**/*.png",
    ],
    spec: "dist/spec/**/*.js",
    dest: "dist",
};

gulp.task("clean", () => {
    return gulp.src(paths.dest, {
            read: false
        })
        .pipe(clean());
});

gulp.task("copy", () => {
    return gulp.src(paths.content)
        .pipe(gulp.dest(paths.dest));
});

gulp.task("compile", () => {

    let b = browserify({
        debug: false, //turn on/off source map 
        entries: [
            "./src/extension/content.ts"
        ]
    });

    //http://maximilianschmitt.me/posts/prevent-gulp-js-from-crashing-on-error/
    return b.plugin(tsify)
        .bundle()
        .on("error", error => {
            console.log(error);
        })
        .pipe(source("content.js"))
        .pipe(buffer())
        .pipe(gulp.dest("./dist/extension/"));
});

//test task depends on clean and compile tasks 
gulp.task("test", done => {
    //start with clean, compile and test respectively 
    runSequence("clean", "compile", "copy", () => {
        gulp.src(paths.spec)
            .pipe(jasmine({
                verbose: true
            }));
        done();
    });
});

gulp.task("watch", ["test"], () => {
    gulp.watch(paths.src.concat(paths.content), ["test"]);
});
```
