### ISSUE TITLE
Ignoring dot-files doesn't work with dot option set to true

### ISSUE THREAD

**Issue by thasmo** [gulpjs/gulp#679]
I'm trying to use `gulp.src(['directory/**', '!**/.git/**'], {dot: true})` but it *always* matches the `.git` directory too. I've tried several variations like `['directory/**', '!.git']` or ``['directory/**', '!.git/**']` etc. but it won't exclude the .git directory - when setting the `dot` option to true.

Any ideas? Thanks!

**Comment by heikki** [comment]
After little testing I realized that **all negations** work this way.

If `['directory/**']`matches these:

```
directory
directory/bar
directory/foo.js
directory/bar/baz.js
```

then `['directory/**', '!directory/bar/**']` matches these:

```
directory
directory/bar
directory/foo.js
```

.. so I don't think this is a bug.

**Comment by stringparser** [comment]
Makes sense, I think the problem was a double negation. 

`['directory/**', '!**/.git/**']`, not `.git` submodules + `{dot: true}` => dot file/dirs

In fact, you pointed this out with a triple negation => negation

> heikki commented on Sep 12, 2014
> This seems to work for me:
>
> gulp.src(['directory/**', '!**/.git', '!**/.git/**'], { dot: true })

**Comment by heikki** [comment]
@stringparser I think this is more accurate:

- `'directory/**'` - include everything under `directory`
- `'!directory/bar/**'` - remove everything under `directory/bar` from included files
- `{ dot: true }` - make dot-files/dirs behave like normal ones

There's no double/triple negations, just negations.

**Comment by stringparser** [comment]
@heikki ok, so how would this work?

* `directory/**`
* `!directory/.git`
* `{dot: true}`

**Comment by heikki** [comment]
-> `gulp.src(['directory/**', '!directory/.git/**'], { dot: true })`

1. Includes everything from `directory`
2. Removes things under `directory/.git` from included stuff

So you will see `directory/.git` directory in matches.

**Comment by stringparser** [comment]
@heikki yep, you are right and the only way then to remove `**/.git` from matches will be to do what you proposed: 

`gulp.src(['dir/**', '!**/.git/**', '!**/.git'], {dot: true})`
 - Treat dot file/dir as normal ones
 - Include all under `dir` not matching `!**/.git/**` and `!**/.git`

if `!**/.git` is not included in the array will always match `dir/.git` since only its contents were excluded

I've tested this with
.
├── dir
│   ├── .dotfile
│   └── .git
└── index.js

and 
```js
gulp.src(['dir/**', '!**/.git/**', '!**/.git'], {dot: true})
  .on('data', function(file){
    console.log(file.path.replace(__dirname, ''));
  });
```
