### ISSUE TITLE
Expose current gulpfile path on gulp instancee

### ISSUE THREAD

**Issue by wesleytodd** [gulpjs/gulp#682]
I am working on a tool that would enable a configuration with multiple `gulpfile`'s.  The goal is to have each module contain it's own build information and be able to run both the module level gulpfile and a app level gulpfile.

It would be very helpful for this to know which gulpfile is the entry point.  This would enable that:

``` javascript
// /bin/gulp.js:116

require(env.configPath);
gutil.log('Using gulpfile', chalk.magenta(tildify(env.configPath)));

var gulpInst = require(env.modulePath);

//
// The new part
//
gulpInst.gulpfile = env.configPath;

logEvents(gulpInst);
```

If you guys like this I will submit a PR.

**Comment by justnorris** [comment]
> With gulp4 coming very soon, larger builds should be able to be abstracted through custom registries.
🤔
