### ISSUE TITLE
Chmod issues on Windows share

### ISSUE THREAD

**Issue by F21** [gulpjs/gulp#702]
I have a Ubuntu 14.04 64-bit guest running in VMWare Workstation on my Windows 8.1 host.

Gulp and node.js are both installed in my Ubuntu guest, but works on files that lives on a Windows share on my host.

I have a simple task to copy some files:

``` javascript
gulp.task('copy', function() {
    return gulp.src('src/**/*')
        .pipe(gulp.dest('dist/'));
});
```

Unfortunately, this results in an error as chmod does not exist on windows:

```
[16:19:04] 'copy' errored after 206 ms
[16:19:04] Error: EPERM, chmod '/project/dist/testfolder'
```

Version information:

```
Gulp
CLI version 3.8.8
Local version 3.8.8

Node
v0.10.32
```

**Comment by BlaM** [comment]
How do I fix this if I'm neither the owner nor administrator on the machine?
