### ISSUE TITLE
Symlinked directories cause EISDIR error from `gulp.src()`

### ISSUE THREAD

**Issue by pghalliday** [gulpjs/gulp#706]
I have just raised https://github.com/wearefractal/vinyl-fs/issues/39 on the `vinyl-fs` project. Currently this impacts gulp if you npm installed in the last few days (the problem is in `vinyl-fs` 0.3.8 but not 0.3.7, gulp depends on ^0.3.0)

To work around this I have manually rolled back the `vinyl-fs` version under the `node_modules/gulp/node_modules` directory. I'm fortunate that in the project this affects, I already commit the node_modules directory to git otherwise this solution wouldn't really work.

**Comment by bzuillsmith** [comment]
It might we worth nothing that the fix on the vinyl-fs side of things was merged into their 1.0.0 branch. I don't think it made it into 0.3.x so the problem persists in gulp despite the fix.

**Comment by contra** [comment]
@bzuillsmith Use gulp 4.0

**Comment by articice** [comment]
Gulp 4.0 didn't help :(

**Comment by articice** [comment]
Gulp 4.0 not released yet :(

**Comment by contra** [comment]
@articice `npm install gulpjs/gulp#4.0`
