### ISSUE TITLE
Should piped streams flow by default?

### ISSUE THREAD

**Issue by hurrymaplelad** [gulpjs/gulp#707]
Is there a convention around whether or not gulp plugins should return flowing streams when piped?

I've [seen both behaviors](http://stackoverflow.com/questions/26206538/why-do-some-gulp-streams-flow-by-default-while-others-do-not), which leads to flakey gulpfiles.

For example, 

```
gulp.task('dest', function(done) {
  gulp.src('docs/*')
    .pipe(gulp.dest('temp'))
    .on('end', function() {
      console.log('ending');
      done();
    });
});
```

Logs `ending`, but

```
gulp.task('logger', function(done) {
  gulp.src('docs/*')
    .pipe(logger())
    .on('end', function() {
      console.log('ending');
      done();
    });
});
```

does not.

It seems like [Streams3](https://github.com/joyent/node/issues/5860) will always return a flowing stream from a pipe.  Can we make that a [plugin guideline](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) to motivate pull requests on non-conforming plugins?

**Comment by janraasch** [comment]
@phated, we have node 0.12. Should people thus update their gulp plugins to use `through2@1`?

**Comment by contra** [comment]
Would def be good to revisit this now that 0.12 is out - we should evaluate all of our streams (vinyl-fs) and make sure that we are on streams3, then figure out what plugin authors need to do to get there too. Would appreciate anyones help on this!

**Comment by janraasch** [comment]
@contra, I noticed that @sindresorhus has already moved some of his plugins to `through2@^2.0.0`. See e.g. https://github.com/sindresorhus/gulp-rev/commit/445aeb3ca1268c2c067ebf78b56c11bcb305ffd8. Since his plugins are used by a lot of people, I assume the upgrade path for plugin authors is as easy as simply upgrading their `through2` dependency. Is that right?
