### ISSUE TITLE
Incremental rebuilding recipe: handling the deleted event

### ISSUE THREAD

**Issue by ghidello** [gulpjs/gulp#732]
Hi all,
let's say I've a gulp task like the 'scripts' task below where:
- the gulp.src glob is modified by the specified 'base' path
- the stream is saved to disk by gulp.desc with folder prefix

In the watcher I need to handle the 'deleted' event type deleting the corresponding file into the dest folder and I'm wondering if there exists a smarter way than the one i came up with.

Better said: can anyone translate my stuff to proper gulp? :)
Thanks in advance.

Oh, last question: in a case like this is it ok to not provide a callback to the del task?

```javascript
gulp.task('scripts', function() {
    return gulp.src('src/**/*.js', {base: 'src'})
		.pipe(indent({tabs: true, amount: 1}))
        .pipe(header('(function () {\r\n\t\'use strict\'\r\n'))
        .pipe(footer('\r\n})();'))
        .pipe(gulp.dest('build'));
});

gulp.task('watch', function () {
    gulp.watch('src/**/*.js', ['scripts'])
        .on('change', function (event) {
            if (event.type === 'deleted') {
			
				// Simulating the {base: 'src'} used with gulp.src in the scripts task
                var filePathFromSrc = path.relative(path.resolve('src'), event.path);
				
				//Concatenating the "build" absolute path used by gulp.dest in the scripts task
                var destFilePath = path.resolve('build', filePathFromSrc); 

                del(destFilePath);
            }
        });
});
```

**Comment by phated** [comment]
@ghidello or anyone else: would you be able to submit this as a recipe?

**Comment by phated** [comment]
I added this recipe at https://github.com/gulpjs/gulp/blob/master/docs/recipes/handling-the-delete-event-on-watch.md - Thanks @ghidello for writing it up.

**Comment by ghidello** [comment]
Ups, sorry for the delay but i totally lost track of this issue.

As per my last question, i guess it's ok to not give a callback to the inner "del" call, am I correct?

And thanks for promoting my stuff to something which is worth being seen!

**Comment by h0r0man** [comment]
What if the generated file for example is css from sass? It doesn’t correspond the file extension.
