### ISSUE TITLE
gulp.dest and file read-only attribute

### ISSUE THREAD

**Issue by maximtgs** [gulpjs/gulp#735]
hi All
following is very simple code:

``` js
    gulp.src(config.lib.src('**/*.*')).pipe(gulp.dest(config.lib.dest));
```

it just copy files from folder to folder. source files are read-only and gulp somehow keeps the same attributes for destination files.
i tried to override it with gulp-chmod, but it doesnt work (the files still read-only):

``` js
    gulp.src(config.lib.src('**/*.*'))
       .pipe(plug.chmod({
        owner: {
            read: true,
            write: true,
            execute: true
        },
        group: {
            read: true,
            write: true,
            execute: true
        },
        others: {
            read: true,
            write: true,
            execute: true
        }
    }))
       .pipe(gulp.dest(config.lib.dest));
```

i work on windows server 2008 R2 standard. "gulp-chmod": "^1.1.1", "gulp": "^3.8.8",
how can i make the dest files RW?
thanks.

**Comment by AlexKey** [comment]
@maximtgs what versions are you using to get this working? I'm having a similar problem.
