### ISSUE TITLE
gulp does not support sub projects

### ISSUE THREAD

**Issue by dodtsair** [gulpjs/gulp#736]
You cannot have a gulpfile.js call another gulpfile.js from another project in a subfolder of your project.  Consider this canned example:

```
$ git init
$ git submodule add --force https://github.com/google/web-starter-kit.git 
$ git submodule add https://github.com/driftyco/ionic.git
$ pushd ionic/; npm install; popd
$ pushd web-starter-kit/; npm install; popd
$ cat >> gulpfile.js << EOF
var gulp = require('gulp');
var osScaffold = require('./web-starter-kit/gulpfile');
var njsApp = require('./ionic/gulpfile');

gulp.task('default', function() {
  //what goes here
});
EOF
$ npm install gulp

$ gulp
[15:42:49] Using gulpfile ~/.tmp/gulpfile.js
[15:42:49] Starting 'default'...
[15:42:49] Finished 'default' after 35 μs
```

This of course does nothing, but how could it do any thing.  I would need to call the default task of each sub project, but they have been replaced by the root project's default task.

Other problems arise like the following code in a child project:

```
gulp.task('tarball', function() {
  return gulp.src(['**/*')
    .pipe(tar('subproject.tar'))
    .pipe(gzip())
    .pipe(gulp.dest('./dist'));
});
```

This code will output a tarball of not just the subproject where it lies, but also the root project and the other project.  Also it will put that tarball in the dist folder of the root project, not the dist folder of the subproject.  

Only way that I know of to do sub projects would be to synchronously fork and call gulp on each gulpfile.js of the sub projects.

**Comment by tobias-neubert** [comment]
I found [gulp-hub](https://github.com/frankwallis/gulp-hub) for that. Simply create a route gulpfile.js like this. 
```javascript    
var gulp = require('gulp');
var hub = require('gulp-hub');
hub(['bas-amqp/gulpfile.js']);
```
