### ISSUE TITLE
need marked-man before gulp install?

### ISSUE THREAD

**Issue by zhuangya** [gulpjs/gulp#740]
```
> npm install -g gulp                                              master [8b957e2]

> gulp@3.8.9 prepublish /usr/local/lib/node_modules/gulp
> marked-man --name gulp docs/CLI.md > gulp.1

sh: marked-man: command not found

npm ERR! addLocalDirectory Could not pack "/usr/local/lib/node_modules/gulp" to "/Users/nos/.npm/gulp/3.8.9/package.tgz"
npm ERR! addLocal Could not install /usr/local/lib/node_modules/gulp
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.4
npm ERR! code ELIFECYCLE
npm ERR! gulp@3.8.9 prepublish: `marked-man --name gulp docs/CLI.md > gulp.1`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the gulp@3.8.9 prepublish script.
npm ERR! This is most likely a problem with the gulp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     marked-man --name gulp docs/CLI.md > gulp.1
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
```

i have to install `marked-man` before i install `gulp`

any idea to solve this?

**Comment by roberto68** [comment]
so installed marked-man but that arises another even more odd problem [CODE] npm install gulp
 
> gulp@3.9.0 prepublish /home/robert/node_modules/gulp
> marked-man --name gulp docs/CLI.md > gulp.1

/home/robert/node_modules/marked-man/bin/marked-man:8
	if (err) throw err;
	               ^
Error: ENOENT, open 'docs/CLI.md'
    at Error (native)

npm ERR! addLocalDirectory Could not pack /home/robert/node_modules/gulp to /home/robert/.npm/gulp/3.9.0/package.tgz
npm ERR! addLocal Could not install /home/robert/node_modules/gulp
npm ERR! Linux 4.1.6-200.fc22.x86_64
npm ERR! argv "node" "/home/robert/nvm/versions/node/v0.12.7/bin/npm" "install" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE
npm ERR! gulp@3.9.0 prepublish: `marked-man --name gulp docs/CLI.md > gulp.1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gulp@3.9.0 prepublish script 'marked-man --name gulp docs/CLI.md > gulp.1'.
npm ERR! This is most likely a problem with the gulp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     marked-man --name gulp docs/CLI.md > gulp.1
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robert/node_modules/npm-debug.log
 [/CODE]
