### ISSUE TITLE
Continue gulp on error?

### ISSUE THREAD

**Issue by dashed** [gulpjs/gulp#75]
I have the following gulp js code using the gulp-coffee plugin:

``` javascript

gulp.src('./**/*.coffee')
  .pipe(coffee({bare: true}))
    .on('error', gutil.log)
    .on('error', gutil.beep)
  .pipe(gulp.dest(destDir));
```

Whenever gulp-coffee throws an error (e.g. invalid coffee syntax), it stops the rest of valid coffee files from 'piping' through; even though the error is caught.

To clarify this, here is a sample file queued via `gulp.src`:

```
A.coffee (processed)
B.coffee (error and stops the rest of the stream)
C.coffee (not processed)
```

Is there a way to 'continue' the stream?

**Comment by alsotang** [comment]
I meet this problem when I use `webpack-stream`, just remove all default `error` handler.

see: https://github.com/floatdrop/gulp-plumber , and use it.

**Comment by GuyPaddock** [comment]
I'm using `plumber` and just wanted more human-friendly errors. Here's what I came up with:
```JavaScript
  gulp.src(coffeeSrc)
    .pipe(plumber())
    .pipe(coffee({bare: true}).on('error', function (error) {
        console.error("Compilation error: " + error.stack);
      }))
    .pipe(gulp.dest('./css'))
```

**Comment by Mugane** [comment]
Isn't `--continue` supposed to do this? It doesn't, but isn't it supposed to?
