### ISSUE TITLE
Unhandled stream error in pipe (Windows 8)

### ISSUE THREAD

**Issue by krman009** [gulpjs/gulp#762]
```
G:\KAUSHALYA\Testing\Daily-Task>gulp
[gulp] [19:32:46] Using gulpfile G:\KAUSHALYA\Testing\Daily-Task\gulpfile.js
[gulp] [19:32:47] Starting 'connect'...
[19:32:47] Server started http://localhost:9090
[19:32:47] LiveReload started on port 35729
[gulp] [19:32:47] Finished 'connect' after 77 ms
[gulp] [19:32:47] Starting 'watch'...
[gulp] [19:32:47] Finished 'watch' after 680 ms
[gulp] [19:32:47] Starting 'default'...
[gulp] [19:32:47] Finished 'default' after 20 µs
[gulp] [19:35:22] Starting 'html'...
[gulp] [19:35:22] Finished 'html' after 8.21 ms

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EBUSY, open 'G:\KAUSHALYA\Testing\Daily-Task\index.html'
```

Here is [repository](https://github.com/krman009/Daily-Task) of the project. (You can see there `gulpfile.js` and `package.json`)
Can I get solution for this?

**Comment by hasokeric** [comment]
I have the same issue wierd... it works like for 10 changes and then for example the 11th one crashes with 
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: file to import not found or unreadable: scss/walkthrough
Current dir: C:/code/eatgr_mobile/scss/

**Comment by krman009** [comment]
@hasokeric This may help you http://rhumaric.com/2014/01/livereload-magic-gulp-style/
