### ISSUE TITLE
Invoking the Gulp tool programmatically

### ISSUE THREAD

**Issue by ghost** [gulpjs/gulp#770]
I am trying to invoke Gulp within another Node.js script. Is there any non-hackish way to do this? e.g. by not manually requiring `bin/gulp.js` or setting up a `new Liftoff({ ... })`, or running the command in the shell as is done at the moment in [this plugin](https://github.com/therealklanni/git-guppy/blob/master/scripts/hookfile) I'm currently working on?

To be more general I'm asking if there's an official way to run Gulp as a part of another tool, without the extra overhead of spawning a new child process. A meta-API, if you like.

I think this is somewhat related to issue #755, except that no `gulpfile` has been loaded yet.

**Comment by desandro** [comment]
Logs get suppressed when triggered with `gulp.start()`. How do you get them back?

**Comment by stringparser** [comment]
afaik, logging is added when you run gulp from the cli so if you are running it programmatically [you will have to add them](https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L173)

**Comment by dacodekid** [comment]
@contra Is there an equivalent functionality for ```gulp.tasks.test``` in 4.0 alpha 1? While the above code works in 3.8, 4.0 alpha 1 gives an error ```"Uncaught TypeError: Cannot read property 'test' of undefined"```.

I also couldn't able to invoke a task programmatically with ```gulp.series(test)```

**Comment by contra** [comment]
@dacodekid `gulp.task('test')` will return the function that is registered for a task named `test`

**Comment by lijunle** [comment]
@contra In the 3.9 version, `gulp.task('test')` returns the all gulp tasks information, not the single task. It your mentioned feature new in 4.0?

**Comment by rafis** [comment]
Here is solution for gulp 3.9:
https://github.com/gulpjs/gulp/issues/494#issuecomment-44716601

**Comment by ORESoftware** [comment]
Ok, but what if want to get the "return" values from Gulp tasks?

Maybe someone could help me with my SO question?

https://stackoverflow.com/questions/40496855/retrieving-result-of-gulp-4-task-programmatically


basically, I have a Gulp task like so:


```
const t = gulp.task('foo', function(){
        return 5;
});
```

how can I capture the result of the task?

```
t.on('done', function(val){
  
      // this doesn't work TMK
});
```

**Comment by contra** [comment]
@ORESoftware 

```js
var gulp = require('gulp')
require('./gulpfile') // import the gulp file

const result = gulp.task('foo')()
```

Nothing fancy

**Comment by ORESoftware** [comment]
oh shazam, but what about a curve ball like this Terminator sequence:

```js
const t1 = gulp.task('one',['two'], function(){
             return Promise.resolve(5)
});

const t2 = gulp.task('two', function(){
          return Promise.resolve(11);
}):
```

surely I can't just do

`const result1 = t1();`

I must have to listen to an event or something...?

?

apologies, because I have only used Gulp 3 and am planning on using Gulp 4 heavily but still new to it, please correct syntax if it's wrong.

**Comment by contra** [comment]
@ORESoftware Yeah, you need gulp 4 for that case

gulpfile.js:

```js
import gulp from 'gulp'

const two = () => Promise.resolve(11)
const one = gulp.series(two, () => Promise.resolve(5))

gulp.task('one', one)
gulp.task('two', two)
```

code.js:

```js
import gulp from 'gulp'
import './gulpfile'

const result = gulp.task('one')()
```

With 4, you can also export the tasks from your gulpfile if you're trying to test them. The CLI picks these up too.

Here's what that would look like -

gulpfile.js:

```js
import gulp from 'gulp'

export const two = () => Promise.resolve(11)
export const one = gulp.series(two, () => Promise.resolve(5))
```
code.js:

```js
import { one, two } from './gulpfile'

const result = one()
```

**Comment by ORESoftware** [comment]
thanks let me try that out

**Comment by ORESoftware** [comment]
another question I have, just for context => the main reason I am interested in using Gulp programmatically is that it may offer some sophisticated ways to only run tasks once and cache the result. In fact, that is the primary reason I am interested in using it programmatically - I can compose tasks and if two different tasks (2,3) both depend on task 1, I can configure it so that task 1 only runs once, and caches the result. I assume this is possible with Gulp 4, if not then I might not use it. Sorry for sidetrack.

**Comment by contra** [comment]
@ORESoftware Wrap your task functions with a module like http://npm.im/once

**Comment by ORESoftware** [comment]
ok, cool, I can do that, but I think it would be really cool if Gulp did that natively

**Comment by ORESoftware** [comment]
Tried this, I am getting undefined as a result

```
const util = require('util');
const gulp = module.exports = require('gulp');

const two = () => Promise.resolve(11);

const one = gulp.series(two, () => Promise.resolve(5));

gulp.task('one', one);
gulp.task('two', two);

const prelim = gulp.task('one');
const result = prelim();

console.log(util.inspect(prelim));
console.log(util.inspect(result));
```

very confused :/

**Comment by contra** [comment]
@ORESoftware Maybe series isn't returning the value - @phated would have more info on that since he built the task system

**Comment by phated** [comment]
`series` and `parallel` don't return results because they have nothing to return.  When invoking, you pass a callback function that passes the errors and results.

`prelim(function(err, results) { console.log(err, results); });`

**Comment by squidfunk** [comment]
Trying to do this with a babel-transpiled Gulpfile, `Gulpfile.babel.js` - doesn't work for me:

```
.../node_modules/DEPENDENCY/Gulpfile.babel.js:23
import gulp from "gulp"
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../node_modules/babel-watch/runner.js:63:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

```

Somebody experiencing the same issues?

**Comment by bradstech01** [comment]
For anyone bumping into this thread and still running into @squidfunk's issue, make sure you've installed gulp-babel and gone through the other Gulp-specific setup steps on Babel's site (including making the .babelrc config file). I just went through this and I had to setup a .babelrc config file using a babel preset to get mine to work.

Go here and click on "Gulp" under build systems for more info:
https://babeljs.io/docs/setup

**Comment by bluebrown** [comment]
> nah heres how you really do it
> 
> ```js
> var gulp = require('gulp');
> require('./gulpfile');
> 
> if (gulp.tasks.test) { 
>     console.log('gulpfile contains task!');
>     gulp.start('test');
> }
> ```
> 
> a gulpfile is just a node script, so you can require it in like any other.
> 
> As they said though, .start will be gone in 4.0 and replaced with series and parallel

This doesnt work for me. First of all start doesn't seem to be a function.  `TypeError: gulp.start is not a function`

Second, when I use your if statement. It doesn't pick up my task either.
![gulp](https://user-images.githubusercontent.com/39703898/59351587-a3e4f980-8d16-11e9-8d8d-5eae5edd2c77.PNG)

Do you know why its not working? 

(I can run the task with my defined` npm start` script which just runs ` gulp watch`

**Comment by bluebrown** [comment]
In case someone stumbles over this. It seems like the provided solution is deprecated.
I was able to achieve it via `gulp.task('watch')();`

`gulp.task('taskname')` will return the task itself. So we just need to invoke it with another pair if brackets `()`
