### ISSUE TITLE
Question: Gulp 4.0 Conventions For Tasks

### ISSUE THREAD

**Issue by dman777** [gulpjs/gulp#771]
With 4.0, is the intended code flow(gulp convention) no longer calling outside normal javascript functions(non task wrapped) inside a wrapped task? 

The reason why I ask is because I see:

`gulp.task('default', gulp.parallel('clean', 'all'));` where `clean` and `all` are also gulp tasks called within task `default`. 

In 3.0, this would be done with

```
function clean() {}
function all() {}
gulp.task('default', function () {
    Promise.all([clean(), all()]);
})
```

Reference:
https://github.com/gulpjs/gulp/issues/458#issuecomment-62057370
https://github.com/gulpjs/gulp/issues/755#issuecomment-61884019

**Comment by geirsagberg** [comment]
`gulp.task('default', 'build')` should be synonymous with `gulp.task('default', gulp.series('build'))` IMO. When I tried wrapping the `build` task in a function as suggested, gulp won't log anything from the nested tasks:

```
function build(){
  return gulp.parallel(buildScripts, buildLess);
}
gulp.task(build);
gulp.task('default', build);
```
