### ISSUE TITLE
Question: Gulp 4: pipelining between tasks

### ISSUE THREAD

**Issue by jasonkarns** [gulpjs/gulp#782]
I've been experimenting with gulp 4 and i'm struggling with a bit of the task pipelining.

Example:

```
function build() { ... }
function bump(){ // bumps package version
  return gulp.src('package.json').pipe(incVersion).dest('.');
}

function tag(){
  // how do i access the current stream?
  return <current_stream>.pipe(tag_version)
}

gulp.task('bump', bump)
gulp.task('release', gulp.series(gulp.parallel(build, bump), tag))
```

The `tag` function needs to be given a stream, which doesn't seem possible using the bach-provided apis? This example is clearly contrived, because it *could* be written as:

```
gulp.task('release', gulp.series('build', function(){
  bump().pipe(tag)
}))
```

But then the parallelization between build and bump is lost. Is there another way to accomplish this with 4.0?

**Comment by contra** [comment]
I think this has been answered
