### ISSUE TITLE
gulp is segfaulting

### ISSUE THREAD

**Issue by noahgrant** [gulpjs/gulp#785]
I've searched and searched and haven't come across anyone else who has experienced this issue, but my gulp tasks segfault fairly often.  The thing is, it's hard to pinpoint, because it happens with multiple tasks.  Most often, it happens while [gulp-modernizr](https://github.com/doctyper/gulp-modernizr) is building a custom modernizr file, causing all tasks, including my local server (with [gulp-webserver](https://github.com/schickling/gulp-webserver)) and [watcher](https://github.com/floatdrop/gulp-watch) to stop.  If I run `gulp modernizr` separately from my other default tasks, it caches the file, and then won't segfault—most of the time. But sometimes it still does.  And sometimes, when I remove the modernizr task completely from my list of tasks, it still segfaults (though much less often).  Even if I include the modernizr tool but don't launch the webserver or watcher.  In fact, I've gone through every combination of tasks trying to single the problem out, but it seems to happen more globally, which is why I'm posting here.  Here is a common output from the modernizr task when it fails:

```
...

>> Ready to build using these settings:
>> setClasses, addTest, html5printshiv, testProp, fnBind

Building your customized Modernizr
>> Local Npm module "grunt-contrib-connect" not found. Is it installed?
>> Local Npm module "grunt-saucelabs" not found. Is it installed?
>> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
>> Local Npm module "grunt-contrib-nodeunit" not found. Is it installed?
..Segmentation fault: 11
```

(it fails as it's doing the actual file-building. When it succeeds, the last line prints `...........OK`.)

I'm on OS X Yosemite, I'm using browserify/watchify for js, [gulp-sass](https://github.com/dlmanning/gulp-sass) with node-sass/libsass for sass, and I've had to [up the limit on the number of watchable files](https://github.com/gruntjs/grunt-contrib-watch#how-do-i-fix-the-error-emfile-too-many-opened-files), and here's my offending gulp task looks something like:

``` js
...

gulp.task('default', function(cb) {
  runSequence('clean', ['js', 'modernizr', 'sass', 'jade', 'svg', 'copy'], 'serve', 'watch', cb);
});
```

Any insight as to why this might be happening regularly with gulp or what can be done about it would be greatly, greatly appreciated.

Thank you!

**Comment by kamlekar** [comment]
Just informing here..

This happened to me when I was in middle of upgrading nodejs from 4.0.0 to 4.1.2

I actually forgot that I was upgrading and stumbling upon why segment error is showing up. When I realised and completed the installation, the issue fixed.
