### ISSUE TITLE
Other gulpfiles as dependencies - namespacing

### ISSUE THREAD

**Issue by melbourne2991** [gulpjs/gulp#786]
Hi guys.

I am using a framework with its own gulpfile which has a "build" task, originally I found the gulp chug plugin only to discover it has been blacklisted. 

In this issue a number of suggestions are provided
https://github.com/gulpjs/plugins/issues/93

eg: simply requiring the other gulpfile

However, as @robatron rightly points out, how do we deal with conflicts in terms of the task names. Ideally I would like to use the term build as my task, but won't be able to do so without overriding the framework's build task. I can see this problem growing as gulp uptake increases and frameworks start using it.

I guess one unlikely solution is to introduce namespacing as a standard for plugins and their tasks. "less.build" "concat.build" etc

**Comment by phated** [comment]
The proper module to use for these types of scenarios is [gulp-hub](https://github.com/frankwallis/gulp-hub).  They currently have to do a bunch of stuff to work around inefficiencies in gulp 3.x but the current implementation doesn't try to hook into the stream system.  Also gulp-hub is very far along on implementing itself as a [Custom Registry](https://github.com/phated/undertaker#custom-registries) for gulp 4, which is the proper way to handle these things in 4.0
