### ISSUE TITLE
EBUSY on Windows

### ISSUE THREAD

**Issue by jasonhansel** [gulpjs/gulp#788]
I am having an annoying issue with gulp.js on Windows. The problem occurs with the following very simple gulpfile:

```
var gulp = require('gulp');
gulp.task('test', function() {
    return gulp.src('src/*.css').pipe(gulp.dest('dest'));
});
gulp.task('default', function() {
    gulp.watch('src/*.css', ['test']);
});
```

When one of the watched files is modified, the task usually runs perfectly. However, about one in five times, I get the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EBUSY, open 'C:\<whatever>\src\test.css'
```

and gulp exits.

The issue seems to be that gulp is trying to read the modified file while my text editor is still using it. If I add `{read:false}` to the `gulp.src` call, the bug goes away (although the file, of course, is no longer copied properly). If it's relevant, I'm using Sublime Text 3 with the `atomic_save` setting set to `false`.

I've tried a few things to fix this, to no avail:
- Putting a try/catch around the contents of each task
- Using `gulp-plumber`
- Adding an `.on('error',...)` handler

Would it be possible either to fix this bug entirely or to make gulp retry the task a few times until the file is no longer busy? Thanks for any help you can provide!

**Edit:** I noticed while writing this issue that setting `atomic_save` to `true` seems to fix the bug. Still, it would be nice not to have to do this.

**Comment by MFFoX** [comment]
For anyone visiting this later hoping to find ideas, I was also having this problem, specifically

    Error: EBUSY, open 'path/to/file.ext'

 I found that it was because of a race condition within my tasks. I fixed it by making sure my tasks were done in the proper sequence and no tasks could be touching the same file(s) at the same time.

**Comment by CalebKester** [comment]
@MFFoX could you give an example of your fix? or show your gulp file?

Thanks,
