### ISSUE TITLE
Allow for optional (weak) dependencies in task declarations

### ISSUE THREAD

**Issue by neil-morrison44** [gulpjs/gulp#790]
Hi,

I have a problem whereby I need two tasks, one which runs a full scale cleanup&build and one which builds individual files.
The sub tasks within the full build task used to depend on the cleanup step, but since they were also called from the individual files task they would clean more than they needed to.

What I'm looking for is a method of assigning a flag to a dependency, such that it's only a dependency if it's going to be preformed in the task anyway.

For example if I had a default task called ["clean", "build"], then within build had ["buildFileA", "buildFileB"] as dependencies.
And a watcher that was watching the files that would go into FileA and the files that would go into FileB.

For the first example I would need "clean" as a dependency in buildFileA and buildFileB, but for the second I wouldn't want clean in there at all (unless to clean only files related to that task).

So, what I'm suggesting is adding a flag, similar to the "!" in front of excluded files which will cause a task to only be seen as a dependency if another task within the dependency tree has also requested it.

buildFileA and buildFileB could have dependencies of ["?clean", "step1", "step2"].

Not sure how useful this would be outside the scope of this particular problem, and I'm guessing it would add considerable overhead to the task dependency tree resolving logic - but it would be useful in situations like this and reduce task repetition.

**Comment by marcospgp** [comment]
It's a shame that this information is so hard to find!

Thanks to @arantir and @contra !
