### ISSUE TITLE
Gulp doesn't find existing file

### ISSUE THREAD

**Issue by codeofsumit** [gulpjs/gulp#801]
Me and my colleagues started to have problems with gulp today. `.src` seems not to find our files while `.watch` observes the files correctly.

Our task for the CSS is this:

```
gulp.task('styles', function() {
  return gulp.src('src/css/app.scss')
    .pipe(sass({ 
        style: 'expanded',
        "sourcemap=none": true,
        noCache: true
    }))
    .pipe(autoprefixer({
        browsers: ['> 5%', 'last 2 versions', 'ie 8'],
        cascade: false
    }))
    .pipe(gulp.dest('dist/styles'))
    .pipe(rename({ suffix: '.min' }))
    .pipe(minifycss())
    .pipe(gulp.dest('dist/css'))
    .pipe(notify({ message: 'Styles task complete' }));
});
```

cli output was just `Starting` and `Finished`.
After a while we found out that gulp isn't failing but that the file, specified in `.src` isn't found.
We used `gulp-expect-file` to check for the file.

```
gulp.task('styles', function() {
  return gulp.src('src/css/app.scss')
    .pipe(expect('src/css/app.scss'))
});
```

now the output is, that this file is missing.

The weird part is that `gulp watch` observes this file and recognizes changes! It fires the styles task which now tells us that the file is missing. 

This is the complete gulpfile we're using to debug this:

```
// Load plugins
var gulp = require('gulp');
var expect = require('gulp-expect-file');

// Styles
gulp.task('styles', function() {
  return gulp.src('src/css/app.scss')
    .pipe(expect('src/css/app.scss'))
});

// Default task
gulp.task('default', function() {
    gulp.start('styles');
});

// Watch
gulp.task('watch', function() {

  // Watch .scss files
  gulp.watch('src/css/app.scss', ['styles']);

});

```

This happens to all files, not only this one. JavaScript, CSS, doesn't matter. `.src` doesn't find any file, even if we use `src/css/**/*.scss` as path.

We're on version 3.8.10

Thanks in advance for any help, this gives us huge headaches today.

Edit: Our gulpfile worked in dozens of projects before - and they're still working. It just stopped for new projects.

**Comment by farshidshahmoradi1996** [comment]
I have same problem :/

**Comment by stevelacy** [comment]
Please do not comment on a issue from 2014...
