### ISSUE TITLE
[gulp 4] allow forward references to tasks

### ISSUE THREAD

**Issue by alvint** [gulpjs/gulp#802]
Currently, forward references to tasks do not work in gulp 4 (and gulp 3, but I don't care about that):

``` js
gulp.task('default', gulp.series('clean', 'build', 'watch', 'server'));

gulp.task('clean', function () {
    // do something
});
...
```

This results in `AssertionError: Task never defined: clean`.

From a stylistic standpoint, many people prefer to place the broadest tasks first and then define component tasks later, since this is how most people think and design code. Also the current 'bottom up', Forth-like restriction is no longer necessary considering how gulp 4 works.

From a design standpoint, since tasks are interchangeable with functions now, and since functions (like most stuff in Javascript) can be referenced from anywhere within the current scope regardless of where it was declared, to be consistent tasks should work the same way.

**Comment by jkarttunen** [comment]
One annoying thing (that teaches javascript) is that now function names collide easily with plugin names.
```
var mocha = require('gulp-mocha');
function mocha() {
    console.log('mocha')
}
gulp.task(mocha);
```
==> AssertionError: Task name must be specified

**Comment by phated** [comment]
Figured I would update this post.  It was easiest to implement forward references as a custom registry - see https://github.com/undertakerjs/undertaker-forward-reference

**Comment by mryellow** [comment]
This makes migration to v4 much more time-consuming than it needs to be.

> what's the point of a registry if everything needs to be defined in order?

I'm defining tasks here, with names as strings. I expect them to exist.

**Comment by joeyhub** [comment]
This might be a more significant problem in some cases than it appears. Sometimes tasks come from other systems and might consist of objects containing task name and function. Those aren't guaranteed to be in order in javascript.

This means having to do really weird things with the structure to get things to work.
