### ISSUE TITLE
Gulp 3.x CLI does not support both versions of gulp

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp#805]
If I use gulp branch 0.4 within my local project but then run `gulp` 0.3 (installed globally) then I get an error:

```
$ gulp
[12:24:51] Using gulpfile ~/src/xxxxx/gulpfile.js

/Users/ibc/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^
TypeError: Cannot call method 'apply' of undefined
    at /Users/ibc/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickDomainCallback (node.js:463:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

May I know why gulp does not provide a separate module `gulp-cli` (similar to [`grunt-cli`](https://github.com/gruntjs/grunt-cli/)) whose only purpose is to locate the local `gulp` executable path (or the global one if not present locally)?

The idea of `grunt-cli` is to avoid issues as the described above. I consider it extremely useful.

**Comment by phated** [comment]
Should be working in gulpjs/gulp-cli#4.0 and gulpjs/gulp#4.0 now.  Give it a shot and let me know if it works.

**Comment by ilanbiala** [comment]
Can this issue be closed now that the CLI compatibility is fixed?

**Comment by heikki** [comment]
@ilanbiala [gulpjs/gulp-cli#4.0](https://github.com/gulpjs/gulp-cli/tree/4.0) branch needs to be merged first and there's a blocker https://github.com/gulpjs/gulp-cli/issues/7

**Comment by Aetet** [comment]
Maybe just rename CLI call to: `gulp4 default ` or write tool like `nvm` do the trick?

**Comment by phated** [comment]
As of now, gulp-cli has a published 1.0.0 - https://www.npmjs.com/package/gulp-cli

Closing this as completed.

**Comment by tkellen** [comment]
Woohoo!!

**Comment by postor** [comment]
```
node ./node_modules/gulp/bin/gulp.js -v
[16:21:56] CLI version 1.2.2
[16:21:56] Local version 4.0.0-alpha.2
```
but this really works
```
node ./node_modules/gulp/bin/gulp.js

Loading engines...
...scanning for engines in the core...
...scanning for engines in the edition or test directory...
- mustache engine: good to go
...done loading engines.

```
