### ISSUE TITLE
gulp-inject Nothing to inject into index.html display

### ISSUE THREAD

**Issue by WhaleWatching** [gulpjs/gulp#806]
I wrote a [gulpfile.js](https://gist.github.com/WhaleWatching/bf96355179d95c5daf95) and improving it now, I got a problem.

In this case, I splited the pipe, build task will put the scripts to static/, and gulp-inject will inject them into html files, but first time of the task inject moudle said it inject nothing into html file, must run build task again to inject them, is this a bug?

Thanks!

**Comment by NinoSkopac** [comment]
@WhaleWatching Same problem here. Did you fix it?
