### ISSUE TITLE
Async task with multiple gulp.src

### ISSUE THREAD

**Issue by 6aKa** [gulpjs/gulp#82]
Example, with useing callback

<pre>
gulp.task('test', function(cb) {

  gulp.src('bootstrap/js/*.js')
    .pipe(gulp.dest('public/bootstrap'))
    .on('end', function() {cb()});

  gulp.src('jquery.cookie/jquery.cookie.js')
    .pipe(gulp.dest('public/jquery'))
    .on('end', function() {cb()});

});
</pre>

Please add method for event 'end'. Like this

<pre>
gulp.task('test', function(cb) {

  gulp.src('bootstrap/js/*.js')
    .pipe(gulp.dest('public/bootstrap'))
    .end(cb());

  gulp.src('jquery.cookie/jquery.cookie.js')
    .pipe(gulp.dest('public/jquery'))
    .end(cb());

});
</pre>

And for 'error' and 'data' events.

**Comment by PanYuntao** [comment]
I do it like this:
```javascript

gulp.task('publish', function(cb) {
    async.series([
        function (callback) {
            gulp.src('css/*.css')
                .pipe(minifyCss())
                .pipe(rev())
                .pipe(gulp.dest('public/css'))
                .pipe( rev.manifest() )
                .pipe( gulp.dest( 'rev/css' ) )
                .on('end', callback);
        },
        function (callback) {
            gulp.src('js/*.js')
                .pipe(jshint())
                .pipe(uglify())
                .pipe(rev())
                .pipe(gulp.dest('public/js'))
                .pipe( rev.manifest() )
                .pipe( gulp.dest( 'rev/js' ) )
                .on('end', callback);
        }
        ,
        function (callback) {
            gulp.src('images/*')
                .pipe(imagemin({
                    progressive: true,
                    svgoPlugins: [{removeViewBox: false}],
                    use: [pngquant()]
                }))
                .pipe(gulp.dest('public/img'))
                .on('end', callback);
        }
        ],
        function (err, values) {
            if (err) {
                cb('your error');
            }
            else
            {
                console.log('success');
                cb();
                //process.exit();
            }
        });
});

gulp.task('default', ['publish']);

```

**Comment by yairEO** [comment]
@PanYuntao  - what is `async.series` ? where does `async` comes from? 

seems like you are using a 3rd party script for this magic.

**Comment by yairEO** [comment]
I (used to) do it like this:

    gulp.task('myTask', ()=>{
        var p1, p2;

        p1 = new Promise((resolve, reject)=>{
            gulp.src('./**/*.html')
                .pipe(...)
                .pipe(...)
                .on('end', resolve);
        });

        p2 = new Promise((resolve, reject)=>{
            gulp.src('./**/*.js')
                .pipe(...)
                .pipe(...)
                .on('end', resolve);
        });

        return Promise.all([p1, p2]);
    });

**Comment by stevelacy** [comment]
Do not restart an issue thread from 3 years ago.

**Comment by yairEO** [comment]
it's better, IMHO, that the information regarding this question will be here than scattered around the internet, so others will easily access it and gain insights.

**Comment by robrich** [comment]
`const async = require('async');`

**Comment by yairEO** [comment]
@robrich - This `async` which you require, is it a 3rd-party script?

why would I want to load such enormous package for something so simple like I showed in my code comment above?

**Comment by robrich** [comment]
@yairEO: We're likely going to get this thread locked, but in short because the `async` package existed before promises were popular.  Now-a-days it's likely better to use the `await` keyword in JavaScript and declare the function with the JavaScript `async` keyword.  In fact one might argue that you could use this `async` / `await` strategy, a single function that `await`s everything, require either [`vinyl-fs`](http://npmjs.org/vinyl-fs) or [`glob`](https://www.npmjs.com/package/glob) and accomplish pretty much everything gulp did.  Others argue this technique is reinventing the wheel.  If you'd like, tag me on a new issue or hit me up on twitter or email and let's continue the discussion.

**Comment by phated** [comment]
@robrich you're right, it's getting locked because you are so misinformed about where gulp is now. We even have tight integration with async/await
