### ISSUE TITLE
npm link of Gulpfile (as a module) will not find tasks and error.

### ISSUE THREAD

**Issue by Industrial** [gulpjs/gulp#833]
Hi.

I've written a gulp setup (https://github.com/Industrial/id-project) for all my projects but as the number of projects using this setup grew it became more generic and instead of copying over behaviour from project to project I opted to make the setup (id-project) more generic and support configuration.

At first I used git to pull in changes from id-project into e.g. ProjectA and ProjectB. This turned out to be a messy thing and a lot of bookkeeping and working with git instead of coding.

Right now, I've implemented id-project as a NPM module so all I have to do is `npm install --save-dev id-project gulp coffee-script` and the gulpfile.coffee looks like `(require "id-project")()` and I'm done. I can make changes to id-project and just update with npm when I want those changes in another project.

The problem I'm having is that when I am developing new features or fixing bugs on id-project, I can't use `npm link` to test these changes in another project before releasing id-project. Gulp tells me `Task 'default' is not in your gulpfile`.

There seems to be a difference between using the `npm install id-project` version and `npm link` version.

Meanwhile I'm releasing a lot of unneeded versions on npm that I would like to do without.

Any help would be appreciated.

**Comment by jfbibeau** [comment]
@tkellen Any idea what happened to this issue? I'm running into the same problem, and I don't see a fix... Thanks!

**Comment by ngokevin** [comment]
We have a gulpfile requiring another gulpfile as part of a library. To reproduce:
 
    git clone git@github.com:mozilla/marketplace-gulp
    git clone git@github.com:mozilla/fireplace
    cd marketplace-gulp && npm link && cd ../
    cd fireplace && npm install && make install && npm link marketplace-gulp
    make serve

gulp will then fail to find tasks. When debugging the Gulp object in the local gulpfile, it seems the tasks are registered to the Gulp object. But it can't find the ```default``` task.

**Comment by jfbibeau** [comment]
For what it's worth, I solved it by doing this:

http://stackoverflow.com/questions/28972330/task-is-not-in-your-gulpfile-when-using-npm-link

**Comment by ngokevin** [comment]
That's worth a lot, thanks @jfbibeau!

**Comment by Industrial** [comment]
Thanks for the solution!

I've since built my own project automation module, though; https://github.com/Industrial/id-builder
