### ISSUE TITLE
gulp.src globbing: re-include files that were excluded by globs?

### ISSUE THREAD

**Issue by UltCombo** [gulpjs/gulp#837]
In `gulp.src`, is it at all possible to re-include files that were excluded by a previous glob? This is what I mean:

``` js
gulp.task('default', function() {
    rimraf.sync('dist');
    return gulp.src(['src/**', '!src/**/*.js', 'src/vendor/**/*.js'], { base: 'src' })
        .pipe(gulp.dest('dist'));
});
```

This results in an empty `dist/vendor` directory.

**Comment by caroso1222** [comment]
+1 for @UltCombo's `gulp-src-ordered-globs` package. It does the work just perfect.
