### ISSUE TITLE
Add sourcemaps into core

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#843]
cc @floridoo

Basically src/dest will have a sourcemap option. Now people don't need to use gulp-sourcemaps in their own files. This will DRY up a ton of stuff

**Comment by johnpapa** [comment]
:+1:

**Comment by boogerlad** [comment]
@nuisanceofcats Any luck fixing that? I'm trying to get the same thing working.

**Comment by nuisanceofcats** [comment]
Have been waiting for gulp v4 and experimenting with my own stuff. All node based asset pipelines have major flaws or restrictions, v4 will probably sort it all out.

**Comment by boogerlad** [comment]
Sadly I'm on v4 alpha. Many things still seem to be not perfect. If I am compiling a less file to a css file, the sourcemap will refer to the outputted css file. Oh well.

**Comment by phated** [comment]
@boogerlad sourcemaps have nothing to do with v4 alpha.  This was an issue to discuss implementing the boilerplate into gulp.src/dest.  That has pushed off until gulp 4.1 anyway.

**Comment by boogerlad** [comment]
Sorry for going off topic.

**Comment by pikeas** [comment]
Based on my reading of this thread, there's no way to merge sourcemaps in Gulp v3, and this won't be added until v4.1, which is months away?

**Comment by contra** [comment]
@boogerlad if there is an issue with gulp-sourcemaps then open an issue on gulp-sourcemaps, no point in reporting it on an unrelated issue

**Comment by ohjames** [comment]
@boogerlad @pikeas [sigh](https://github.com/sighjs/sigh) asset pipeline now supports this along with many gulp plugins.

**Comment by contra** [comment]
Moving this back to 4.0 since this is pretty easy to do

**Comment by contra** [comment]
@floridoo any thoughts RE merging streams of sourcemaps?

**Comment by floridoo** [comment]
@contra the source maps are per file, so merging streams should not affect them in theory. maybe the sourcemaps property is dropped by the `merge` plugin? i will have a look when i find the time.

**Comment by ohjames** [comment]
@floridoo Combining source maps needs special handling that currently isn't in gulp. Here's an implementation:

* https://github.com/sighjs/sigh-core/blob/master/src/sourceMap.js#L26

**Comment by floridoo** [comment]
@ohjames `merge` does not combine files or sourcemaps, that's what `gulp-concat` is for. `merge` just merges streams.

**Comment by ohjames** [comment]
Yep, unfortunately if you merge streams before passing them into concat (e.g. the input streams each use different transformations) then the source maps are incorrect.

**Comment by ohjames** [comment]
My previous comment is incorrect/misleading though, you're right gulp-concat does exactly that... I think.

**Comment by contra** [comment]
@ohjames before we bring this into core I want to make sure that any edge cases are handled. If you have any other concerns/oddities feel free to raise them here

**Comment by contra** [comment]
Added into src on vinyl-fs master, going to do dest later today then make it available for testing on 4.0 :+1: https://github.com/wearefractal/vinyl-fs/commit/60685eb89e57f61c4462855532f43d75f0a616db

**Comment by ohjames** [comment]
Cool, anyone else think the default setting for source maps should be true rather than false?

**Comment by ohjames** [comment]
@contra I tested the merge + concat again with the git master commit, the same test I ran back in my comment from December. It still fails but I found the issue, essentially it's because one of the sources is not transformed (the `bootstrap.js` which should just be appended raw) and hence has an empty source map attached by this line of code:

https://github.com/floridoo/gulp-sourcemaps/blob/master/index.js#L107

`gulp-concat` should detect empty source maps and replace them with identity source maps. Either this or that line there could be changed to attach an identity source map instead of an empty source map.

`sigh` takes the former approach as it's slightly more efficient and abstracts it behind the source map API. With that small change then `gulp-concat` will produce valid source maps :)

**Comment by contra** [comment]
@ohjames I thought about making it true by default, but I think it makes more sense to opt-in to having more files pop up in the output and more CPU usage

**Comment by phated** [comment]
Looks like this is 50% done (included in `gulp.src` but not `gulp.dest`).  Marking as "help wanted" incase anyone wants to send a PR to https://github.com/wearefractal/vinyl-fs that adds the `dest` support.

**Comment by contra** [comment]
@phated Just added it into .dest this morning, needs tests though

**Comment by joshribakoff** [comment]
Inlining the sourcemaps like this breaks lots of older browsers like IE. If we want to support IE, is there some way to disable this? The behavior I seem to be seeing is that its enabled by default now, which means after updating gulp, lots of older browsers suddenly broke with no obvious fix.

**Comment by contra** [comment]
@joshribakoff Not sure why you are saying it's on by default when that was never said and certainly isn't true

**Comment by contra** [comment]
Also FYI for any interested parties, the sourcemaps option is now available for src and dest on vinyl-fs master. Please test out the changes and I'll cut a release if everything looks good

**Comment by contra** [comment]
im going to close this since it has been implemented, but it still needs testing

**Comment by eddiemonge** [comment]
Whats the api for this?
