### ISSUE TITLE
Gulp 3 task breaking Gulp 4 composite task

### ISSUE THREAD

**Issue by ilanbiala** [gulpjs/gulp#849]
I have a Gulp 3 task that ran before my test tasks:
```
gulp.task('env:test', function testEnv() {
  process.env.NODE_ENV = 'test';
});
```

Now when I do `gulp.series(testEnv, gulp.parallel(testTask1, testTask2));` and alias that as `gulp test`, the parallel doesn't get run. How can I make this compatible with Gulp 4?

**Comment by heikki** [comment]
Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/gulp) and you get answer in no time. :)

**Comment by ilanbiala** [comment]
@heikki Gulp 4 hasn't been released yet, there will be 0 answers on SO. All questions on SO about Gulp 4.0 currently have 0 answers...

**Comment by heikki** [comment]
Just a hint. This is a javascript question.

**Comment by contra** [comment]
Synchronous tasks don't exist in gulp 4, you need to take a callback parameter and call the callback

**Comment by contra** [comment]
cc @phated this should be documented in the changelog
