### ISSUE TITLE
Please clarify in Guidelines: “Instead, you should emit it as an error event.”

### ISSUE THREAD

**Issue by simevidas** [gulpjs/gulp#850]
In your [Guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) at nr. 6, you say:

> “Instead, you should emit it as an error event.”

Could you clarify how this is performed (by linking this sentence to the relevant page/section in your docs)? I was unable to find any information on this.

**Comment by contra** [comment]
http://nodejs.org/api/events.html
http://nodejs.org/api/stream.html

**Comment by simevidas** [comment]
@contra May I suggest adding an entry “Emitting an error event” to the list of Gulp [recipes](https://github.com/gulpjs/gulp/tree/master/docs/recipes)? The Node API docs are not the optimal source of information for users who are getting started with Gulp and streams in general.

**Comment by contra** [comment]
@simevidas Basic node and javascript knowledge is a pre-requisite for writing plugins. I'm not going to make it our responsibility to teach that information, there are plenty of good resources out there for that

**Comment by sindresorhus** [comment]
Look at some existing plugins ;)

**Comment by simevidas** [comment]
@sindresorhus 

through => this.emit('error', err)
through2 => cb(err)

I stand by my remark that a clarification in the plugin guidelines is needed. Gulp plugins are mostly based on through2, so the advice “you should emit it as an error event” does not reflect the current state of plugins, and leads to confusion.

**Comment by sindresorhus** [comment]
@simevidas That has nothing to do with gulp specifically. It's just Node streams. The `cb(err)` is just an early callback shorthand for `this.emit('error', err)`. Nothing to do with `gulp`, `through`, or `through2`.
