### ISSUE TITLE
Gulp completion is very slow

### ISSUE THREAD

**Issue by fundon** [gulpjs/gulp#851]
I used gulp zsh completion, and it's very slow.
Please improve it.

**Comment by contra** [comment]
@tkellen

**Comment by tkellen** [comment]
@fundon Do you have any suggestions on improvements?

**Comment by fundon** [comment]
No good idea.
When runnng `gulp --tasks-simple` will load many third-modules, many seconds will be used, then list tasks.

**Comment by tkellen** [comment]
Hmm.  Seems we need to memoize the result of --tasks-simple (mtime caching against the gulpfile, perhaps).

**Comment by geekflyer** [comment]
@fundon It helps to lazily require modules, just before they are needed. So instead of writing:

```
var gulp = require('gulp');
var plugin1 = require('plugin1')
var plugin2 = require('plugin3')
var plugin3 = require('plugin3')

gulp.task('task1',function(){
return gulp.src('*')
          .pipe(plugin1)
          .pipe(plugin2)
          .pipe(plugin3)
          pipe(gulp.dest('.')
});
```

Better write:
```
var gulp = require('gulp');

gulp.task('task1',function(){
var plugin1 = require('plugin1')
var plugin2 = require('plugin3')
var plugin3 = require('plugin3')
return gulp.src('*')
          .pipe(plugin1)
          .pipe(plugin2)
          .pipe(plugin3)
          pipe(gulp.dest('.')
});
```

There are also some node modules and gulpfriendly plugins which help in lazy requiring modules.

**Comment by contra** [comment]
@tkellen caching the task names :+1:

**Comment by fundon** [comment]
@geekflyer Thanks.
But it is not elegance.

**Comment by heikki** [comment]
> Hmm. Seems we need to memoize the result of --tasks-simple (mtime caching against the gulpfile, perhaps).

That won't be enough if tasks are [split across multiple files](https://github.com/gulpjs/gulp/blob/master/docs/recipes/split-tasks-across-multiple-files.md).

**Comment by mnpenner** [comment]
I discovered this too. As a temporary solution if hashing gulpfile.js to check for changes and caching the results to a separate .json file. I didn't know about the "multiple file" thing though; that definitely poses a problem. All the more reason to have a built-in solution.

**Comment by phated** [comment]
Is anyone going to tackle this?  I don't think it's a big deal.

**Comment by callumacrae** [comment]
Would using gulp-load-plugins help with this issue? I've never experienced this issue (I didn't even know completion was a thing), but from what I've read below, the lazy-loading approach that gulp-load-plugins takes would help speed things up here.

**Comment by contra** [comment]
load lazily or use gulp-load-plugins

**Comment by leventebalogh** [comment]
I added a small Gist that gives you a dumb, but fast autocompletion for Gulp.js. 
For me, waiting 2 sec for an autocomplete was unusable. 
I don't say it is a perfect solution, however can be a good alternative, until it get's better, or anyone takes the time to fix it:
https://gist.github.com/leventebalogh/ba862a284d21c39a80ed03af7be128b5

**Comment by phated** [comment]
@leventebalogh your solution is very specific to your use case since it relies on directory structure and making each gulp task it's own module/file.  That's actually the reason why your completion is so slow due to the require time.  I'm glad you found a solution for your workflow but we can't include that solution in our CLI.

**Comment by mnpenner** [comment]
I just cached the task list to a json file based on the hash of the
gulpfile. But that gives the opposite problem - if my tasks are defined in
other files, the hash won't change. If we could traverse the requires like
browserify or webpack we could generate a proper hash... That'd make it
quick.

**Comment by leventebalogh** [comment]
@phated, yea, I know it cannot be included in the CLI and I don't even expect that :)
I have just posted it here as an alternative solution, so if anyone has the same issue they can find it. (I think it is might quite common for bigger projects to start separating the tasks to multiple files so make them easier to maintain)
