### ISSUE TITLE
Allow setting cwd and require root independently of each other

### ISSUE THREAD

**Issue by wheresrhys** [gulpjs/gulp#854]
I'm trying to write a shared build process module for a number of inter-related applications. This module will have gulp and a number of gulp plugins as dependencies. The applications themselves will have something like this in their gulpfile:

```javascript
require('shared-build/gulpfile');

//define additional tasks here if required
```
In order for this to work l need to keep the cwd as the project root, but the require root needs to be './node_modules/shared-build/'. Is it feasible to add the ability to configure them separately? Or are you tied by the internal implementations of Liftoff/node?

**Comment by contra** [comment]
If you have a folder called `node_modules/shared-build` it doesn't matter what your CWD is, it will get resolved with `require('shared-build')` or `require('shared-build/gulpfile')`

**Comment by wheresrhys** [comment]
I'll expand the example a bit as I realise I didn't explain the problem fully enough

```
// package.json
{
  "shared-build": "*",
  "gulp-thing": "*",
}

// ./gulpfile
require('shared-build/gulpfile');
var gulpThing = require('gulp-thing');
//define additional tasks here if required

// node_modules/shared-build/package.json
{
  "gulp-other-thing": "*",
}

// node_modules/shared-build/gulpfile
var gulpOtherThing = require('gulp-other-thing');
//define additional tasks here if required
```

`gulpOtherThing` cannot be required as the require root is `./` and `gulp-other-thing` is at `node_modules/shared-build/node_modules/gulp-other-thing`

The implication of this is that gulp cannot be used as a dependency of a build process, which I think is quite a limitation. Please can you reopen. 

@contra
