### ISSUE TITLE
Error installing glup.

### ISSUE THREAD

**Issue by FreakDroid** [gulpjs/gulp#856]
I got this error when I tried <code>npm -g install glup</code> How I could fix it? It's like the glup does not exits or is down.

**C:\Users\desarollovchi>npm -g install glup
npm ERR! 404 404 Not Found: glup
npm ERR! 404
npm ERR! 404 'glup' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "glup"
npm ERR! cwd C:\Users\desarollovchi
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\desarollovchi\npm-debug.log
npm ERR! not ok code 0**

**Comment by stringparser** [comment]
is g**ul**p not g**lu**p

**Comment by FreakDroid** [comment]
@stringparser Thank!!! my bad.

**Comment by stringparser** [comment]
:+1: :)
