### ISSUE TITLE
Register anonymous function by name, if it has a special property `displayName`

### ISSUE THREAD

**Issue by geekflyer** [gulpjs/gulp#858]
Hi,

I just encountered a simple problem with Gulp 4. I tried to use functions everywhere, mainly named functions but also some anonymous functions (see below why I need some anonymous functions too). 
I encountered the problem that anonymous functions cannot be given a name directly and because of that the log is not very useful. Instead I have to register all of them using gulp.task(name,fn) and then refer subsequently to them by name.

Since I like prefer to leave functions as they are, but still having some useful log, I would propose that Undertaker also considers a new property `taskName`. If an anonymous function contains this property, it will be registered using this name.

So I could do:

```js
var anonFunction = function (cb) {console.log('foo'); cb()}
anonFunction.taskName = 'bar';

gulp.task(anonFunction)   // gets public registered as 'bar'

gulp.task('blabla',gulp.series(namedFunction,anonFunction)); // just used inline, with useful log
```

So what do you think? To me this seems more DRY / refactorable (less strings) than using gulp.task(name,fn). See below the original use case I stumpled upon this (task factory function).

### Detailed Use Case when I stumpled upon this
I found that some of the tasks in my gulpfile are copying files from one location to the other and are very similar in that sense. So I created a factory function for suchlike tasks:

```js
function getSimpleCopyTask(fnName, pathConfig){
    var fn = function () {
       return gulp.src(pathConfig.src, {dot: true})
            .pipe(changed(pathConfig.dest))
            .pipe(gulp.dest(pathConfig.dest));
    };
    fn.name = fnName;
    return fn;
}
```

Now I wanted to use it like that:
```js
gulp.task('build:fdn',gulp.parallel(
    buildConfigServer,
    getSimpleCopyTask('buildCommon',config.paths.common),
    getSimpleCopyTask('buildConfigUi',config.paths.configUi)
));
```

Everything works as expected, however the logger logs the simplyCopyTasks as `<anonymous>` and not as `buildCommon` or `buildConfigUi` as desired. The reason for that is obvious --> I'm attempting to write to the property `fn.name` in the getSimpleCopyTask function, which is non-writable property. 

Node Undertaker reads this property in 5:8 to get a name from a function
```js 
if(typeof name === 'function'){
    fn = name;
    name = fn.name;
  } 
```

I would propose to add, which probably already fixes my problem:
```js
name = fn.taskName || fn.name
```

**Comment by phated** [comment]
I've considered using [Function.displayName](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName)

My suggestion for the current implementation would be to do gulp.task(taskName, anonFn) inside your factory function.  It doesn't hurt to register them.

Let's see if this is a popular request before we go implementing.

**Comment by geekflyer** [comment]
Just tried it out:
Change of L14 in Undertaker `buildTree.js` to:
`var name = task.taskName || task.name ||  || '<anonymous>';`
Change of L7 in Undertaker `task.js` to:
`name = fn.taskName || fn.name`

Already seems to work fine :-)

**Comment by geekflyer** [comment]
@phated Yeah **Function.displayName** would be fine too :+1: 

Registering the function inside the factory would work, however then I still have to refer to the function afterwards by name and it also pollutes my top level task list (--tasks-simple) and the shell completion, even though I never will want to execute those tasks directly :smile:  I just need their name for the log.

**Comment by heikki** [comment]
You probably knew this already:

```js
function simpleCopy(pathConfig) {
    return gulp.src(pathConfig.src, { dot: true })
        .pipe(changed(pathConfig.dest))
        .pipe(gulp.dest(pathConfig.dest));
}

function buildCommon() {
    return simpleCopy(config.paths.common);
}

function buildConfigUi() {
    return simpleCopy(config.paths.configUi);
}

gulp.task('build:fdn', gulp.parallel(
    buildConfigServer,
    buildCommon,
    buildConfigUi
));
```

**Comment by contra** [comment]
Why not just set the name attribute instead of the taskName attribute? `name` and `displayName` are standard attrs, I don't think we should come up with a new one. Our stuff already works with the name attr no matter how it was defined

**Comment by geekflyer** [comment]
@contra `displayName` would be fine for me (probably better than taskName) but the current gulp4 doesn't read that.  `name` is an non-writable property of functions (also anonymous functions).

just try this snippet in your browser:
```js
var anonFunc = function(){};
console.log(anonFunc.name);  // --> ""
anonFunc.name = "anonFunc"
console.log(anonFunc.name); // --> ""  (unchanged)
```

**Comment by contra** [comment]
@geekflyer Ah didn't know that it was non-writable. displayName would probably be best IMO

**Comment by geekflyer** [comment]
`displayName` ftw :+1: :-)

In the meantime for I will use @heikki 's suggestion, which is ok for my particular use case:

```js
function simpleCopy(pathConfig) {
    return gulp.src(pathConfig.src, {dot: true})
        .pipe(changed(pathConfig.dest))
        .pipe(gulp.dest(pathConfig.dest));
}

gulp.task('build:fdn', gulp.parallel(
    buildConfigServer,
    function buildCommon() {return simpleCopy(config.paths.common);},
    function buildConfigUi() {return simpleCopy(config.paths.configUi);}
));
```

**Comment by stringparser** [comment]
Just a question, why an anonymous function is advantageous here?
And what I really mean is: why not enforce named functions, they give more useful stacktraces. Or is the latter so somewhat rude?

**Comment by geekflyer** [comment]
@stringparser When using a factory for creating a commonly used gulp task (gulp task = function) the factory cannot yield named functions. As a workaround I'm wrapping at the moment the output of the factory into a named function, but I would like to avoid this / make it shorter.

Also when using `displayName` the stractrace has the same usefulness as with a named function, since displayName is considered special (at least by Mozilla).

Here a simplified example, which shows the difference between using only named functions vs. setting displayName in a factory.

```js
// example with named functions only
function factory(config) {
    return gulp.src(config.src)
        .pipe(changed(config.dest))
        .pipe(gulp.dest(config.dest));
}

gulp.task('buildComponents', gulp.parallel(
    doStuff1,
    function buildComponent1() {return factory(config.component1);},
    function buildComponent2() {return factory(config.component2);},
    function buildComponent3() {return factory(config.component2);})
);

// example with displayName instead
function factory(config){
    var fn = function () {
        return gulp.src(config.src)
            .pipe(changed(config.dest))
            .pipe(gulp.dest(config.dest));
    };
    fn.displayName = config.name;
    return fn;
}

gulp.task('buildComponents', gulp.parallel(
        doStuff1,
        factory(config.component1),
        factory(config.component2),
        factory(config.component2))
);
```

**Comment by stringparser** [comment]
@geekflyer I understand, to dry stuff is always nice. Still... I don't know :smile_cat:. What about have a reporter just like test runners do being one form of it what we have for logging now?

**Comment by stringparser** [comment]
Well, in fact you can do it already by replacing the listeners for `start`, `stop`, etc. though you will have to figure how to pass the metadata from your factory function to the listener.

**Comment by geekflyer** [comment]
@stringparser well that sounds a bit too hacky imho. The integrated logger would still then log things like `Starting '<anonymous>'... ` . I can hardly change that from outside.

**Comment by stringparser** [comment]
Yes, you would have to remove the log listeners and after add yours but it will work.
In any case, I agree with you @geekflyer, too hacky. `displayName` is much simpler.

**Comment by phated** [comment]
This has been added as of https://github.com/gulpjs/gulp/commit/eb2beaa640945d13bb8254a8be1173f89efccc1e

**Comment by rsferreira11** [comment]
If anyone still has this problem, I found a workaround to give any string name to an anonymous function:

```javascript
const fn = Object.values({
  ["testTask:watch"]: () => {}
})[0];
```
Example with dynamic strings:
https://jsfiddle.net/ao7buhnr/

PS: It cannot be extracted into a function.
