### ISSUE TITLE
TypeError: Cannot call method 'apply' of undefined

### ISSUE THREAD

**Issue by johnpapa** [gulpjs/gulp#863]
I'm getting this error running some simple hello-world gulp tasks after I install the gulp-cli globally and gulp locally, both from the 4.0 branches respectively. Is there a newer version or some different directions?

TypeError: Cannot call method 'apply' of undefined

**Comment by johnpapa** [comment]
Resolved.

I uninstall gulp-cli globally and  installed gulp globally and it works.

Not sure if this is a bug or "as intended"

**Comment by geekflyer** [comment]
@johnpapa maybe you still had a global legacy `gulp` installation which was conflicting with the global `gulp-cli` installation? In any case to do a clean install of both things I usually also do `npm cache clean gulp gulp-cli` after i've uninstalled them.

**Comment by johnpapa** [comment]
didnt work for me.

as i understand it, we can use either gulp or gulp-cli globally. so this may not be a big deal.

**Comment by phated** [comment]
The cross-version CLI is still being worked on at https://github.com/gulpjs/gulp-cli/tree/4.0 - It isn't currently published to npm and you need to install with `npm install -g gulpjs/gulp-cli#4.0`

As you discovered, you can just install gulp globally still and it will work.

I will leave this open for a while to keep visibility if anyone else runs into this.

**Comment by phated** [comment]
Closing, as I feel like this has had enough visibility.
