### ISSUE TITLE
Dependent tasks must be defined before they are used

### ISSUE THREAD

**Issue by johnpapa** [gulpjs/gulp#864]
This was not a requirement in gulp 3 but appears to be one in gulp 4. Is this intended?

I prefer not having a sequencing restriction as often I organize my tasks however it appears most readable, not by who depends on who.

For example, the following will not work. 

```javascript
gulp.task('test', gulp.parallel('vet', function(done) {
  console.log('running tests');
  done();
}));

gulp.task('vet', gulp.parallel(function(done) {
  console.log('running code analysis');
  done();
}));
```

However, this will work since `vet` now comes before `test`.

```javascript
gulp.task('vet', gulp.parallel(function(done) {
  console.log('running code analysis');
  done();
}));

gulp.task('test', gulp.parallel('vet', function(done) {
  console.log('running tests');
  done();
}));
```

**Comment by heikki** [comment]
Duplicate of #802

**Comment by johnpapa** [comment]
Yep, I see that now. Sounds like the suggestion for gulp4 is to use functions, list them how you like, then list tasks.

**Comment by phated** [comment]
using plain functions is the recommended way but https://github.com/undertakerjs/undertaker-forward-reference can be used as a custom registry if forward references are required for some reason.
