### ISSUE TITLE
Dependency graph watching

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp#869]
If we start using this across the board https://github.com/gulpjs/gulp/issues/357 we can start tracing dependencies of modules. This is really interesting because it makes something like watchify obsolete.

1. Run task
2. All files read (intercepted by us) are treated as dependencies
3. Keep a list of these files after each task run
4. If any of these files change, run the task again

This means we don't have to parse any of the files (big blocking CPU op) and build the graph ourselves like webpack or broccoli, we just let the tools do that for us.

Thoughts? @phated @sindresorhus @jlongster

This would probably be in a user-land module

**Comment by sindresorhus** [comment]
:+1: :+1:

**Comment by srcspider** [comment]
The task should run when new files are added too, and that's probably one of the most annoying cases. How does that fit in to all of this?

**Comment by phated** [comment]
@contra if this is going to be userland, is there any reason to keep it open?
