### ISSUE TITLE
deleted file regenerated

### ISSUE THREAD

**Issue by githubutilities** [gulpjs/gulp#870]
I minify the js file and then run clean process, but the deleted file got regenerated at the end.

**Comment by githubutilities** [comment]
here is [the gulpfile.js](https://github.com/githubutilities/web_presentation/blob/master/gulpfile.js).
`gulp clean` works file but `gulp` doesn't

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)
