### ISSUE TITLE
Grouped indent of parallel tasks

### ISSUE THREAD

**Issue by ilanbiala** [gulpjs/gulp#874]
It feels clearer to me that parallel tasks can be grouped and indented to symbolize parallelism. Is this something that makes sense, because I get confused pretty often when I see a task called parallel starting.

**Comment by ilanbiala** [comment]
@contra @phated what do you guys think?

**Comment by phated** [comment]
I've been thinking about this but don't have any ideas of better ways to show it.  Do we currently show when `<parallel>` has completed?  I think that is a useful metric for people to see in the output.  Also, `--tasks` CLI flag needs to group parallel and series in `<parallel>` and `<series>` to give good information in how the task tree is being executed.

**Comment by ilanbiala** [comment]
@phated Yes there is a printout for when `<parallel>` has completed. The CLI does print out groups, but it is also not that clear.

**Comment by phated** [comment]
I'm open to clearer ways to display the requirements I outlined.

**Comment by ilanbiala** [comment]
How about same indent level is series, new indent level is parallel?

**Comment by phated** [comment]
That doesn't solve the task tree layout or timing.

**Comment by phated** [comment]
Where does this stand?  Are we just going to ship with the current format?  It seems like no one cares enough to PR anything.  @contra @heikki

**Comment by phated** [comment]
Due to inactivity, I'm going to label this as a `wontfix` but I will accept a PR with a proposed alternative.
