### ISSUE TITLE
Question on loading files

### ISSUE THREAD

**Issue by tamtakoe** [gulpjs/gulp#880]
```javascript
gulp.src([file1path, file2path])
    .pipe(concat(fileName)) //file1content + file2content
```
gulp ensures that the files are processed in the order in which they are specified in src array?

**Comment by pkozlowski-opensource** [comment]
> Files will be concatenated in the order that they are specified in the gulp.src function. For example, to concat ./lib/file3.js, ./lib/file1.js and ./lib/file2.js in that order, the following code will create a task to do that:

```
var concat = require('gulp-concat');

gulp.task('scripts', function() {
  gulp.src(['./lib/file3.js', './lib/file1.js', './lib/file2.js'])
    .pipe(concat('all.js'))
    .pipe(gulp.dest('./dist/'))
});
```

https://github.com/wearefractal/gulp-concat#usage

Anyway, this is not the best place to ask support questions, especially when the answer is readily available in the docs or can be quickly verified :-)

**Comment by sindresorhus** [comment]
Yes, but plugins are not ordered. So if you put anything between gulp.src and the concat plugin it might lose the order. You really shouldn't structure your app like this. Use a module loader.
