### ISSUE TITLE
Multiple browserify tasks

### ISSUE THREAD

**Issue by tnguyen14** [gulpjs/gulp#883]
I follow this recipe for making browserify task https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md

I was wondering if there is a way to create a browserify/ watchify task to handle multiple streams/ src-dest pairs?

For eg., a project I am working on requires 2 different `js` files in different directories to be bundled into different destinations. What would be the best solution for this?

**Comment by blvz** [comment]
I think that the "best solution" is something that you'll find, according to each scenario. But I've put it up an example that should give you some insights:

[blvz/gulp-bundle-stack-example](https://github.com/blvz/gulp-bundle-stack-example)

**Comment by heikki** [comment]
Support questions http://stackoverflow.com/questions/tagged/gulp
