### ISSUE TITLE
Why aren't gulp tasks structured as promises?

### ISSUE THREAD

**Issue by olsonpm** [gulpjs/gulp#884]
I'm just not understanding the current architecture and briefly looking at gulp4 - it doesn't seem to change.

If a task is dependent on zero to many tasks and should execute as soon as they are all finished, then why aren't they simply promises?  I just don't see the need for orchestrator at all, nor any of the limitations brought in by using the current task architecture.

**Comment by blvz** [comment]
https://github.com/orchestrator/orchestrator/issues/26#issuecomment-35455254

**Comment by olsonpm** [comment]
haha

**Comment by heikki** [comment]
I'm not sure what limitations you're talking about. If you're into promises you can return one from your task: https://github.com/gulpjs/gulp/blob/master/docs/API.md#return-a-promise

**Comment by olsonpm** [comment]
@heikki 
1) Inability to return values from tasks
2) JSHint compile time errors (As opposed to string dependencies, you declare promise objects as dependencies
3) Flexibility in declaring dependencies (with promises you could declare any combination of promise logic if needbe as opposed to the current structure of declaring single tasks only)

If you want me to think of more, just let me know.

**Comment by heikki** [comment]
Gulp 4 will address 2 & 3. You declare functions and compose them with `series` / `parallel`.

**Comment by contra** [comment]
There is no orchestrator on v4, obviously you haven't really taken a look at how v4 works other than a short glance at the documentation.

**Comment by olsonpm** [comment]
@contra - hence 'brief'

**Comment by contra** [comment]
If you have any specific problems that the new task system doesn't address please open issues.
