### ISSUE TITLE
npm install failed due to old version of v8flags?

### ISSUE THREAD

**Issue by normington** [gulpjs/gulp#885]
I started trying to install [waax](https://github.com/hoch/WAAX/), which has gulp as a dependency. It failed during trying to install dependencies for gulp.

I then tried installing gulp on its own and got the same problem. The messages I get are:

```
X:\HDD (SSD Install)\Git\orientEar dev\waax>npm install gulp
\


> v8flags@1.0.8 install X:\HDD (SSD Install)\Git\orientEar dev\waax\node_modules
\gulp\node_modules\v8flags
> node fetch.js

npm ERR! v8flags@1.0.8 install: `node fetch.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the v8flags@1.0.8 install script.
npm ERR! This is most likely a problem with the v8flags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fetch.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8flags
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
npm ERR! cwd X:\HDD (SSD Install)\Git\orientEar dev\waax
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0
```

The problem seems to be with v8flags. I looked into the issues in v8flags, and my problem looks a bit like tkellen/node-v8flags#9, which said it's fixed as of v8flags v2.0.0.

gulp calls for v8flags@1.0.8. I have tried installing v8flags with latest version (2.0.2) and it installs fine. **Is there any way I can get gulp to install and use v8flags@2.0.2 as a dependency instead?** Would that even work?

Sorry if I'm missing something - I'm new to the node.js process!

I am running Windows 8.1.

Thanks!

**Comment by heikki** [comment]
It's fixed on master but not yet published. You can try `npm install "gulpjs/gulp"`.

**Comment by normington** [comment]
Fantastic - that's dealt with it. Thanks!

**Comment by contra** [comment]
@tkellen Do I need to cut a new 3.x version to npm?

**Comment by tkellen** [comment]
if we want to stop fielding these issues, yeah.  just needs to bump liftoff and v8flags to 2x and change
https://github.com/gulpjs/gulp/blob/v3.8.10/bin/gulp.js#L25
to `'v8flags: v8flags`

**Comment by phated** [comment]
it is kind of a hassle to stick that in before the gulp-cli changes

**Comment by danialothman** [comment]
thanks @heikki ! that helped me install gulp -g in system.
