### ISSUE TITLE
Gulp Install Error

### ISSUE THREAD

**Issue by renatokd** [gulpjs/gulp#887]
Hello,

I'm try install gulp and got this error in response.

sudo npm install -g gulp
[sudo] password for renato: 
npm http GET https://registry.npmjs.org/gulp
npm http 304 https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/archy
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/deprecated
npm http GET https://registry.npmjs.org/gulp-util
npm http GET https://registry.npmjs.org/interpret
npm http GET https://registry.npmjs.org/liftoff
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/orchestrator
npm http GET https://registry.npmjs.org/pretty-hrtime
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/tildify
npm http GET https://registry.npmjs.org/v8flags
npm http GET https://registry.npmjs.org/vinyl-fs
npm http 304 https://registry.npmjs.org/deprecated
npm http 304 https://registry.npmjs.org/gulp-util
npm http 304 https://registry.npmjs.org/archy
npm http 304 https://registry.npmjs.org/liftoff
npm http 304 https://registry.npmjs.org/interpret
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/pretty-hrtime
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/orchestrator
npm http 304 https://registry.npmjs.org/tildify
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/v8flags
npm http 304 https://registry.npmjs.org/vinyl-fs
npm http GET https://registry.npmjs.org/user-home
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/end-of-stream
npm http GET https://registry.npmjs.org/sequencify
npm http GET https://registry.npmjs.org/stream-consume
npm http GET https://registry.npmjs.org/array-differ
npm http GET https://registry.npmjs.org/array-uniq
npm http GET https://registry.npmjs.org/beeper
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/lodash.reevaluate
npm http GET https://registry.npmjs.org/lodash.reescape
npm http GET https://registry.npmjs.org/lodash.reinterpolate
npm http GET https://registry.npmjs.org/lodash.template
npm http GET https://registry.npmjs.org/multipipe
npm http GET https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/replace-ext/0.0.1
npm http GET https://registry.npmjs.org/glob-watcher
npm http GET https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/vinyl
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/strip-bom
npm http GET https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/vinyl
npm http GET https://registry.npmjs.org/defaults
npm http GET https://registry.npmjs.org/glob-stream
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/flagged-respawn

> v8flags@1.0.8 install /usr/local/lib/node_modules/gulp/node_modules/v8flags
> node fetch.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm http 304 https://registry.npmjs.org/user-home
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/end-of-stream
npm http 304 https://registry.npmjs.org/sequencify
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/stream-consume
npm http 304 https://registry.npmjs.org/array-differ
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/beeper
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/lodash.reevaluate
npm http 304 https://registry.npmjs.org/dateformat
npm http 304 https://registry.npmjs.org/lodash.reescape
npm http 304 https://registry.npmjs.org/lodash.reinterpolate
npm http 304 https://registry.npmjs.org/lodash.template
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/multipipe
npm http 304 https://registry.npmjs.org/replace-ext/0.0.1
npm http 304 https://registry.npmjs.org/glob-watcher
npm http 304 https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/array-uniq
npm http 304 https://registry.npmjs.org/vinyl
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/lodash._basevalues
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/lodash._basecopy
npm http GET https://registry.npmjs.org/lodash._basetostring
npm http GET https://registry.npmjs.org/lodash._isiterateecall
npm http GET https://registry.npmjs.org/lodash.iserror
npm http GET https://registry.npmjs.org/lodash.keys
npm http GET https://registry.npmjs.org/lodash.templatesettings
npm http 304 https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/duplexer2/0.0.2
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/clone-stats
npm http 304 https://registry.npmjs.org/vinyl
npm http GET https://registry.npmjs.org/meow
npm http GET https://registry.npmjs.org/get-stdin
npm http 304 https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/defaults
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/glob-stream
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/first-chunk-stream
npm http GET https://registry.npmjs.org/is-utf8
npm http GET https://registry.npmjs.org/ordered-read-streams
npm http GET https://registry.npmjs.org/glob2base
npm http 304 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/unique-stream
npm http GET https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/flagged-respawn
npm http GET https://registry.npmjs.org/gaze
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/lodash._basevalues
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/lodash._basecopy
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/lodash._isiterateecall
npm http 304 https://registry.npmjs.org/lodash.iserror
npm http 304 https://registry.npmjs.org/lodash.templatesettings
npm http 304 https://registry.npmjs.org/lodash.keys
npm http 304 https://registry.npmjs.org/duplexer2/0.0.2
npm http 304 https://registry.npmjs.org/clone-stats
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/meow
npm http 304 https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/camelcase-keys
npm http GET https://registry.npmjs.org/indent-string
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/lodash._basetostring
npm http 304 https://registry.npmjs.org/is-utf8
npm http GET https://registry.npmjs.org/lodash.escape
npm http GET https://registry.npmjs.org/lodash.isnative
npm http GET https://registry.npmjs.org/lodash.isarguments
npm http GET https://registry.npmjs.org/lodash.isarray
npm http 304 https://registry.npmjs.org/ordered-read-streams
npm http 304 https://registry.npmjs.org/unique-stream
npm http 304 https://registry.npmjs.org/glob2base
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/gaze
npm http GET https://registry.npmjs.org/globule
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/find-index
npm http 304 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/first-chunk-stream
npm http 304 https://registry.npmjs.org/indent-string
npm http 304 https://registry.npmjs.org/camelcase-keys
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/map-obj
npm http GET https://registry.npmjs.org/repeating
npm http 304 https://registry.npmjs.org/lodash.escape
npm http 304 https://registry.npmjs.org/lodash.isnative
npm http 304 https://registry.npmjs.org/lodash.isarguments
npm http 304 https://registry.npmjs.org/lodash.isarray
npm http 304 https://registry.npmjs.org/globule
npm http 304 https://registry.npmjs.org/find-index
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/repeating
npm http 304 https://registry.npmjs.org/map-obj
npm http GET https://registry.npmjs.org/is-finite
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/is-finite
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm ERR! not ok code 0

**Comment by kevva** [comment]
> npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by phated** [comment]
As @kevva quoted, the error tells you what is wrong.

**Comment by renatokd** [comment]
Already removed and installed again the node and the nodejs several times and always got the same error!

Already searched in all it's only forum and meeting solutions that have tried! But do not work!!!

**Comment by kevva** [comment]
http://stackoverflow.com/a/21171188

**Comment by renatokd** [comment]
Thank U

I will test this strategy!
