### ISSUE TITLE
Unit Testing Gulp Tasks

### ISSUE THREAD

**Issue by scottnath** [gulpjs/gulp#889]
Is there a way to unit test my gulp tasks?

thanks,
Scott

**Comment by KapuzenSohn** [comment]
I´m also very interesseted if this is possible.
As a little work around I wrote a Programm which generates Files and then calls the Tasks per COmmand Line and then checks if the Output Folder are Like I expected, but this is more a Integration than a Unit Test and not very good.

Greetz

**Comment by phated** [comment]
I would suggest making your "tasks" functions and testing them as functions.  You can then assign the tested function to `gulp.task` in some central location.
