### ISSUE TITLE
Upgrade Liftoff and Interpret

### ISSUE THREAD

**Issue by pspeter3** [gulpjs/gulp#896]
Liftoff and Interpret are out of date which is causing some file type registration plugins to be missed.

**Comment by phated** [comment]
This is a symptom of a lot of other things.  We are working on rolling back some changes and getting this updated

**Comment by pspeter3** [comment]
Ok, well I'm looking forward to it. I just sent pull requests to interpret and rechoir for typescript-register.

**Comment by phated** [comment]
@pspeter3 it seems that we aren't going to be able to update interpret to the newest version because liftoff doesn't support legacy modules yet.  Updating interpret would be a breaking change in the current state.  We are trying to use rechoir inside liftoff but are blocked by https://github.com/tkellen/node-rechoir/issues/17 - please let us know there if you have any thoughts.  /cc @tkellen

**Comment by tkellen** [comment]
@phated we're fine to bump to interpret 0.4.x, `require('interpret').jsVariants` isn't breaking.

**Comment by tkellen** [comment]
sorry for the slow reply ya'll, been hard at it on some other open source stuff recently.

**Comment by pspeter3** [comment]
So the new version of interpret will be used?

**Comment by tkellen** [comment]
Yup! It's using your changes now.

**Comment by tkellen** [comment]
@contra or @phated need to cut a release, or you need to install from git, tho.  Not sure what their plan is with this.

**Comment by pspeter3** [comment]
Thanks! I'm looking forward to the new release

**Comment by pspeter3** [comment]
Is there anyway there can be a patch release?

**Comment by phated** [comment]
No. Your typescript change will break people. We need to get legacy module support implemented in liftoff first

**Comment by pspeter3** [comment]
How will it break people? Both `typescript-register` and `typescript-require` are considered legitimate

**Comment by tkellen** [comment]
@phated I don't think it will break anyone, typescript-register works just fine. I honestly don't know why we even need the option to fail over to typescript-require.

**Comment by phated** [comment]
@tkellen @pspeter3 since you have install the package next to gulp, people will be happily using typescript-require and an upgrade will break them and require switching to typescript-register.  If we don't get legacy implemented in liftoff, I'm not bumping.

**Comment by tkellen** [comment]
Ah, of course. I see what you mean now.

**Comment by jiyinyiyong** [comment]
Weird... to me it doesn't look like updated. And I got this on both OS X and Ubuntu.
By writing `"interpret": "^0.5.0",` it should be `0.5.2` here:
https://github.com/gulpjs/gulp/blob/master/package.json#L32
https://github.com/tkellen/js-interpret/commits/master

```text
gulp@3.8.11 /usr/lib/node_modules/gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10 <----- not `0.5.2`
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.0.0 (user-home@1.1.1)
├── minimist@1.1.1
├── v8flags@2.0.3 (user-home@1.1.1)
├── semver@4.3.3
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, vinyl@0.4.6, chalk@1.0.0, through2@0.6.3, lodash.template@3.4.0, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.0.3 (extend@2.0.0, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.6, strip-bom@1.0.0, defaults@1.0.2,
```

```text
➤➤ uname -a
Linux tiye.me 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
➤➤ node -v
v0.10.26
```
```text
➤➤ uname -v
Darwin Kernel Version 14.3.0: Mon Mar 16 23:12:31 PDT 2015; root:xnu-2782.20.48~4/RELEASE_X86_64
➤➤ node -v
v0.10.33
```

**Comment by phated** [comment]
npm has horrible caching issues.  just run `rm -rf node_modules && npm cache clean`

**Comment by jiyinyiyong** [comment]
@phated I didn't read that "typescript-register" issue the first time I commented. Is that ok now?

I tried `npm cache clean` several times but still got this:

```text
➤➤ npm i
gulp@3.8.11 node_modules/gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── semver@4.3.3
├── tildify@1.0.0 (user-home@1.1.1)
├── v8flags@2.0.3 (user-home@1.1.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, chalk@1.0.0, vinyl@0.4.6, lodash.template@3.4.0, through2@0.6.3, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.0.3 (extend@2.0.0, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.6, mkdirp@0.5.0, defaults@1.0.2, vinyl@0.4.6, strip-bom@1.0.0, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)
```

**Comment by jiyinyiyong** [comment]
@phated I checked the file npm downloaded `/Users/chen/.npm/gulp/3.8.11/package.tgz` but to find it's `^0.3.2` inside `3.8.11`.

```js
  "dependencies": {
    "archy": "^1.0.0",
    "chalk": "^0.5.0",
    "deprecated": "^0.0.1",
    "gulp-util": "^3.0.0",
    "interpret": "^0.3.2",
    "liftoff": "^2.0.1",
    "minimist": "^1.1.0",
    "orchestrator": "^0.3.0",
    "pretty-hrtime": "^0.2.0",
    "semver": "^4.1.0",
    "tildify": "^1.0.0",
    "v8flags": "^2.0.2",
    "vinyl-fs": "^0.3.0"
  },
```

by looking into commits, `gulp@3.8.11` was released at **Feb 10** https://github.com/gulpjs/gulp/commit/84df40b0faabc2b61d576154fd1145e2146377ca and `interpret@0.5.0` bumped at *Feb 16* https://github.com/gulpjs/gulp/commit/f62e76d9b2e5df57bc5537cd760177496b7942f0, which explains why I keep getting `interpret@0.3.10`.

Request for an update please...

**Comment by alsotang** [comment]
Maintainer of gulp should update version of `gulp`, and publish new version to npm.

I see in this pr https://github.com/gulpjs/gulp/pull/906/files, someone just update `interpret` but forgot `gulp` version.

The same version of npm package cannot overwrite old version.

**Comment by jiyinyiyong** [comment]
@tkellen ping...

**Comment by phated** [comment]
Please review https://github.com/gulpjs/gulp/issues/896#issuecomment-76441560 - we are not going to release this until gulp 4, as it is a breaking change.  Locking.
