### ISSUE TITLE
Tasks added in sub modules are not working properly

### ISSUE THREAD

**Issue by totty90** [gulpjs/gulp#900]
I have project A

**gulpfile.js**

    require('mygulpfile-module')({})

**mygulpfile-module.js**

    require('gulp');gulp.task("default", ["webpack-dev-server"]);

But when I run `gulp`from project A says it doesn't have any task.

In order to work I have to pass the gulp instance/module required from the project A to mygulpfile-module.js, which is not optimal. 

Any way to don't have to pass the gulp module?

**Comment by blvz** [comment]
Are you sure? [gulp-task-loader](https://github.com/hontas/gulp-task-loader) does exactly this and it works as expected.

**Comment by totty90** [comment]
In mine it says that there are no tasks.. What it might be?

**Comment by blvz** [comment]
It works for me. Try this: https://github.com/blvz/gulp-task-module-test

**Comment by totty90** [comment]
Ok, I understand, Now I can't test it but I will come back.

**Comment by totty90** [comment]
Still doesn't work...

**Comment by blvz** [comment]
What's your `node`, global `gulp` and OS versions?

**Comment by heikki** [comment]
Support questions http://stackoverflow.com/questions/tagged/gulp

Open a new issue if the problem turns out to be a bug.
