### ISSUE TITLE
Dealing with non-stream errors

### ISSUE THREAD

**Issue by ivan-kleshnin** [gulpjs/gulp#901]
Most threads about error handling in Gulp, that I found, are concerned about errors in streams. 
This one is different. I'd like to use gulp as ultimate task runner. I want to spawn additional tasks as processes at build time to get faster response:
```javascript
let Gulp = require("gulp");
let ChildProcess = require("child_process");

Gulp.task("backend:nodemon", function() {
  if (process.env.NODE_ENV == "development") {
    let nodemon = ChildProcess.spawn("npm", ["run", "nodemon"]);
    nodemon.stdout.pipe(process.stdout);
    nodemon.stderr.pipe(process.stderr);
    process.on("exit", () => nodemon.kill());
    process.on("uncaughtException", () => nodemon.kill());
  }
});
```

This code is not ok.
That `process.on("uncaughtException", () => nodemon.kill());` stuff "does not work".
Uncaught exceptions does not raise `process:uncaughtException` event if occur async.
I kinda understand that it's not specific to gulp, but I'd like to get advices about how to correct this code. If it's possible at all. I'm interested only in exception handling here (SIGTERM etc. are omitted).

**Comment by contra** [comment]
Use the nodemon module instead of spawning a nodemon process

**Comment by ivan-kleshnin** [comment]
I've tried. Spawned processes is way more fast.
