### ISSUE TITLE
Documentation missing for gulp.watch (glob, ['task1', 'task2', 'task3', callback])

### ISSUE THREAD

**Issue by finalfantasia** [gulpjs/gulp#902]
The other day, I was looking up the [API for BrowserSync](http://www.browsersync.io/docs/gulp/#gulp-reload) and spotted an interesting function signature of `gulp.watch` for which I could not find any description on the official documentation page for gulp:
```javascript
    // add browserSync.reload to the tasks array to make
    // all browsers reload after tasks are complete.
    gulp.watch ("js/*.js", ['js', browserSync.reload]);
```
Even though the comment above states that the callback (`browserSync.reload`) is called after _all_ of the tasks are completed, I could not find any official gulp documentation for this particular function signature.

It turned out that that function signature is valid, of course, and [supported by Orchestrator](https://github.com/orchestrator/orchestrator/blob/993535b1ba6721e7d5824742df2b22f6492c6c71/index.js#L78) under the hood.

It would be nice for this particular function signature of `gulp.watch` to be documented on the official gulp documentation page so that everybody can take advantage of it or at least not be confused by this particular function signature when they see it being used somewhere else.

**Comment by heikki** [comment]
It's not valid. See https://github.com/gulpjs/gulp/issues/776

**Comment by finalfantasia** [comment]
Ah, I see. Thanks, @heikki .
