### ISSUE TITLE
Bring JSCS to Gulp?

### ISSUE THREAD

**Issue by mrjoelkemp** [gulpjs/gulp#904]
Open to a PR that integrates JSCS into the travis flow?

**Comment by phated** [comment]
That would help with a lot of PR comments about style.

**Comment by mrjoelkemp** [comment]
Cool @phated. Thanks for the reply. I'll put one together.

**Comment by mrjoelkemp** [comment]
@phated I'm looking around and don't see a styleguide for the Gulp codebase. Any reference with specific rules as to how you like the code written? Otherwise, I'll just whip up a JSCS config with rules that conform to the current style of the code.

**Comment by phated** [comment]
@mrjoelkemp It's mostly just @contra's preferences.  If you submit something that passes with the current code base, we can work from there.

**Comment by mrjoelkemp** [comment]
Cool. Thanks.

**Comment by contra** [comment]
The styleguide for all of the projects is felixge's node-style-guide https://github.com/felixge/node-style-guide not just my preferences :palm_tree:

**Comment by contra** [comment]
We should incorporate the jshintrc and eslintrc from that repo ^

This is a pretty big job considering how many repos we have now

**Comment by heikki** [comment]
Shortcut to node-jscs issue -> https://github.com/jscs-dev/node-jscs/issues/1071

**Comment by phated** [comment]
@mrjoelkemp since the jscs PR was merged, would you be able to submit a PR for this now?

**Comment by mrjoelkemp** [comment]
Hey @phated. I will put a PR together. Without a new release of jscs, I can't use the `node-style-guide` preset directly. However, I could just copy the guts of it into gulp's jscsrc and then do a follow up PR (once the new version of jscs hits) converting the big jscsrc into:

```js
{
  "preset": "node-style-guide"
}
```

I'll put that together.

**Comment by baer** [comment]
Is there a reason not to consider ESLint instead? It can serve the same purpose but it's based on the ESTree, is extendable and is almost fully supporting ES6 by now.

**Comment by mrjoelkemp** [comment]
I'll avoid the general argument of JSCS vs ESLint. In this case, gulp's source isn't in es6 (though JSCS also has support for that). Plus, JSCS is a better fit for the task of thoroughly enforcing a styleguide.

**Comment by mikesherov** [comment]
@baer :

> It is succinct extendable and based off of ESTree
As is esprima, who started the estree initiative to begin with, and is what espree is based off of.

> I can fill the role of JSHint + JSCS
Depends on what you think JSCS does.

> Allows you to warn OR fail error out for a less frustrating dev experience
This is true. JSCS doesn't have warnings because we have an autofix option.

> It is tracking ES6 and hopefully will support the full spec shortly
As is Esprima and JSCS.

**Comment by baer** [comment]
Cool thanks guys - just thought I'd float the idea. Consider it retracted :)

**Comment by mikesherov** [comment]
@baer, no worries. Just wanted to clarify some of the differences/similarities  between JSCS and ESLint.
