### ISSUE TITLE
Modify tasks' behaviour based on the context they're called in

### ISSUE THREAD

**Issue by gruppjo** [gulpjs/gulp#912]
Hi, at first, thank you for your great work on gulp. I love it!

Now, the reason why I'm creating this issue:

Often, when writing my gulp tasks, I find myself wanting to slightly modify the behaviour of some of my tasks depending on the context they're called in. Let me elaborate:
For instance, I usually have a `jshint` task:
```js
gulp.task('jshint', function () {
  return gulp.src(paths.jsFiles)
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish'))
    .pipe($.jshint.reporter('fail'));
});
```
I use this tasks to lint my code in my `watch` and `build` task which look something like this:
```js
gulp.task('watch', ['serve', 'jshint'], function () {
  $.livereload.listen();

  gulp.watch(paths.jsFiles,
    function (event) {
      $.livereload.reload();
      gulp.start('jshint');
  });
});

gulp.task('build', ['jshint', 'build-stuff', 'other-tasks']);
```
Now comes the part in question:

**When building, I want my `jshint` task to fail, to let the build fail. In my `watch` task, I don't want this.** With the implementation above, when my watch task starts and `jshint` throws an error it won't setup livereload and I have to fix the errors and restart my watch tasks. Which is obviously a little cumbersome. I just want to the jshint task to report the errors but not fail. I wasn't able to figure out a clean way to do this. I thought about:

- creating a **duplicate task** that just doesn't fail, e.g. `jshint-no-fail`, and call that one in my `watch` task. But that's just weak, results in code duplication and thus is just a pain to maintain, especially since some of the tasks I have are more complicated and extensive than this example
- passing in a **CLI option** and catch that with [minimist](https://github.com/substack/minimist) and react with [gulp-if](https://github.com/robrich/gulp-if) or do so with similar packages. But then I'd have to start my tasks with an extra option which just isn't as convenient. For instance: `gulp watch --no-fail`

It would be great to be able to do it somewhat like this:
```js
gulp.task('build', ['linting(fail)', 'build-stuff', 'other-tasks']);

gulp.task('jshint', function (cb, fail) {
  return gulp.src(paths.jsFiles)
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish'))
    .pipe($.if(fail, $.jshint.reporter('fail')));
});
```

What do you think? - How do you cope with problems like this, am I just missing the obvious here, or is this not possible with gulp right now?

**Comment by heikki** [comment]
https://github.com/spalger/gulp-jshint#fail-reporter ?

**Comment by heikki** [comment]
Move shared stuff into a function:

```js
function lint(fail) {
  return function(cb) {
    return gulp.src(paths.jsFiles)
      .pipe($.jshint())
      .pipe($.jshint.reporter('jshint-stylish'))
      .pipe($.if(fail, $.jshint.reporter('fail')));
  };
}
gulp.task('jshint-fail', lint(true));
gulp.task('jshint-nofail', lint(false));
```

In gulp 4 you can get rid of intermediary tasks by using functions in series / parallel. Tasks, as in `gulp.task('something', ..)`, will be used only for exposing things to cli.

**Comment by gruppjo** [comment]
That looks great! Thanks for the quick reply.
This will not be available until gulp 4, if I understood you correctly?

**Comment by heikki** [comment]
In gulp 4 you won't need these unless you plan on running them straight from the command line:

```
gulp.task('jshint-fail', lint(true));
gulp.task('jshint-nofail', lint(false));
```

**Comment by gruppjo** [comment]
Ok, that's good enough for now :)
What would you recommend to, if I want to get my hands dirty with gulp 4. Where's a good place to get more info on it and how to write tasks with it? Also, when do you think it will be released?

**Comment by heikki** [comment]
You can try it this way without messing global installs:

```sh
npm install "gulpjs/gulp#4.0" --save-dev # install 4.0 branch
./node_modules/.bin/gulp some-task       # run your gulp 4 task
```

https://github.com/gulpjs/gulp/tree/4.0#sample-gulpfilejs

Release will be when docs and blocking issues are done.

**Comment by gruppjo** [comment]
Wonderful, thank you!
