### ISSUE TITLE
How to watch symlinks with gulp?

### ISSUE THREAD

**Issue by lfender6445** [gulpjs/gulp#918]
I'd like to watch changes in vendor/bower to kick off a build process - I am also running `bower link` which will symlink a package to local source. 

However, when gulp attempts to watch this directory, it fails to walk the symlink created by `bower link`.

    var bowerAssets ='vendor/javascripts/my_symlinked_package/**/*.js';
    if(bowerAssets){
      gulp.watch(bowerAssets, ['buildAssets']);
    }

From the log, I receive the following

> 2015-02-19 13:16 gulp[81305] (FSEvents.framework) FSEventStreamStart:
> register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

How can I successfully watch symlinked directories for changes?

**Comment by heikki** [comment]
For workaround I'd try something like this:

```js
var bowerAssets = fs.realpathSync('vendor/javascripts/my_symlinked_package') + '/**/*.js';
```

**Comment by heikki** [comment]
http://stackoverflow.com/questions/28614076/how-to-watch-symlinks-with-gulp

**Comment by lfender6445** [comment]
yeah, posted that earlier - fantastic! this is exactly what I needed :+1:

**Comment by justincy** [comment]
`gulp.src` follows symlinks. I think `gulp.watch` should be consistent and also follow symlinks.

**Comment by phated** [comment]
@justincy 1. gulp 3.x development has halted and we were on a really old version of gaze 2. watching is done by chokidar in gulp 4 so that would be handled by them, not us.
