### ISSUE TITLE
Can node require really replace gulp-chug?

### ISSUE THREAD

**Issue by kosz** [gulpjs/gulp#919]
Hi all,

sorry for resurfacing stale conversations here, however, I have been dealing with a bunch of issues, due to gulp-chug being blacklisted as a gulp plugin, in the past few days. 

The reference issue for this blacklisting is here : https://github.com/gulpjs/plugins/issues/93

Investigating that issue, and with the help of people on gitter, I was able to produce the following isolated example of achieving what i needed with require and without gulp-chug : https://github.com/kosz/research-is-gulp-chug-needed 

A simplified, example works. How nice. 

The next step was trying to use this in a real world scenario. Such a scenario involves manipulating gulpfiles from several projects generated with various yeoman generators. Basically, I do not write the gulp files, they are generated for me, and I just want the ability to trigger their tasks from a master gulp file. 

All hell broke loose when trying to use the suggested node require, with the standard gulpfiles. 

I have created another project to illustrate this problem. Note that gulp-chug works with everything out of the box, meanwhile, node require causes most tasks to fail:  

https://github.com/kosz/research-can-require-replace-gulp-chug

I would love some insight into this. 

I hope we can all agree, that modifying the child gulp scripts, to accomodate the require approach, is not a reasonable work around, especially since these gulp files are being automatically generated, and gulp-chug has no problem achieving this behaviour, using code that, itself, has no problem running standalone.  

Anticipated thanks

**Edit:** while this is a question, I think we shouldn't really dismiss it as a simple question, and argue that it should be on stackoverflow, since I feel that it outlines a reasonable requirement, which apparently gulp internals may not be able to handle at this point in time. gulp-chug helps with that, but since it's been black listed for almost a full year, that was probably damaging to it's momentum, and currently is a lot less mature than you'd expect a one and a half year old piece of code to be. 

Keep in mind that with the web becoming more modular, and the multitude of SPAs appearing everywhere, I don't think it's uncommon, for a project to consist of multiple mini/modular projects, that would each have their own gulp file, and at times, would need to be built together, in some sort of, larger build process.

**Comment by robrich** [comment]
The suggestion I mentioned on gitter: `{cwd:__dirname+'/bla/de/bla'}` inside your gulp.src

**Comment by kosz** [comment]
there is no gulp.src usage in the master gulp file, when using the require approach. 

gulp.src is used in the children gulp files, and requiring those to be rewritten should not be an option, since they are generated. The whole point here is automation, not hand coding stuff right ?

**Comment by heikki** [comment]
> I just want the ability to manipulate their tasks from a master gulp file

By "manipulating" do you mean running them as is?

**Comment by kosz** [comment]
Yes @heikki, just like in my example, if I have 10 projects, with 10 gulp files, I need a master gulp file, that starts up tasks on all the 10 projects, with a single command.

**Comment by heikki** [comment]
Since you can run childproject gulp task by `gulp --cwd childproject`, running the same from "master" gulpfile can be done like this:

```js
var gulp = require('gulp');
var spawn = require('child_process').spawn;

gulp.task('foo', function(cb) {
  spawn('gulp', ['--cwd', 'childproject'], { stdio: 'inherit' }).on('close', cb);
});
```

**Comment by kosz** [comment]
@heikki thanks a lot that seems to be working. 

I'll refactor my real master gulp file with this new approach and see if I run into additional limitations of not using gulp-chug. 

Feel free to close this issue, as long as you think that [this](https://github.com/gulpjs/plugins/blob/14e78e65e7a3eb0269f7c74b81a8c08c291da5b5/src/blackList.json#L85) is accurate and won't confuse other people with similar needs

**Comment by heikki** [comment]
Gulp-chug issue was closed for a reason. Future may bring better approaches than is described as a blacklisting reason. My personal opinion leans towards plain node and away of useless abstractions.

Please prefer http://stackoverflow.com/questions/tagged/gulp for questions. Unnecessary noise here effectively takes that time from further development (gulp 4?). We don't want that.

**Comment by kosz** [comment]
Right, and I do not necessarily dispute the need for gulp-chug, as long as there could be node workarrounds, however, fact is, the suggested alternative to gulp-chug in the official docs, **does not work** so given that, I don't think it's fair to consider such a question unecessary noise, when in fact, you may encounter it again, from other people who may take your word for it that require can really replace gulp-chug ( which we've just proven it can't, basically uncovering a documentation bug, which should probably not be reported on stackoverflow ) 

Once again thanks for your help, and i'll keep my fingers crossed that the bash script like work-arround doesn't come with it's own set of hiden caveats. 

Good luck on 4.0 definietely looking forward to it.

**Comment by heikki** [comment]
When asking questions it is good to be more specific. Answer to the question "Can node require really replace gulp-chug?" depends entirely on what one is trying to achieve. As for spawn example being a workaround take a look at gulp-chug source. :wink: 

Ps. answering questions in http://stackoverflow.com/questions/tagged/gulp is a good way of contributing

**Comment by kosz** [comment]
i didn't mean it like that. they are all workarounds i guess, untill some file based namespacing for tasks can be in place, to really be able to simplify build processes of multi-module apps. i have no excuse for not reading the gulp-chug source thuogh. i'll keep an eye on http://stackoverflow.com/questions/tagged/gulp. thx

**Comment by kosz** [comment]
@heikki, is this approach supposed to work on Windows ? We are testing it on our windows computers and it seems to consistently fail.

**Comment by heikki** [comment]
There could be differences as usual. Try running normal node script with spawn first.

**Comment by heikki** [comment]
Alternative:
```js
var gulp = require('gulp');
var which = require('which').sync;
var spawn = require('child_process').spawn;

gulp.task('default', function(cb) {
  spawn(which('gulp'), ['--cwd', 'childproject'], { stdio: 'inherit' }).on('exit', cb);
});
```

**Comment by kosz** [comment]
thanks Heikki for helping me out with this one. I will try it out and post update as soon as i get access to a Windows machine again.

**Comment by kosz** [comment]
@heikki thanks again, works great. 

phew, i can actually relax tonight, been working on something for a month and this gulp-chug, which i thought would take 1 hour, ended up taking 2 days >: ...

Your quick and accurate answers however, kept me sane. Thanks

**Comment by heikki** [comment]
I don't mind aswering questions as long as they are well asked and in proper place.

http://stackoverflow.com/search?q=user:516256+[gulp]
