### ISSUE TITLE
Did not found any notes on daemonizing

### ISSUE THREAD

**Issue by olamedia** [gulpjs/gulp#921]
How to run with npm module "forever"
Or may be how to run gulp as a daemon (with restart on failover)
Grunt, for example have its own "grunt-forever" npm module
And without that, "watch" is useful only in development, with one console for each script opened constantly.

**Comment by heikki** [comment]
http://stackoverflow.com/questions/21598340/nodemon-restart-run-gulp-tasks

This waits for your answer once you figure out how to do it with forever:
http://stackoverflow.com/questions/28543171/run-gulp-script-with-forever

**Comment by olamedia** [comment]
forever runs native nodejs apps. to use it, i need to use something like gulp.run. but this is deprecated.

**Comment by olamedia** [comment]
well, ok. made this workaround
```
#!/usr/bin/env node
// CONTENTS
var run = require('gulp-cli');
run();
```

**Comment by olamedia** [comment]
From my side of view, this is CRITICAL miss in documentation. Not even an "enhancement".
Running services continuously is not a feature, but a requirement for production.

**Comment by heikki** [comment]
Gulp is a node program. How do you run a node program with forever?

You case, simplified: `forever ./node_modules/.bin/gulp some-task`

**Comment by olamedia** [comment]
syntax is following:
forever [action] [options] SCRIPT [script-options]
where action is start
and, well, i probably can use --workingDir of gulpscript.js as an option, gulp (global gulp-cli) as the script and task as a script option
but including gulp-cli seems more clean solution for me atm

**Comment by contra** [comment]
Why are you using a build system in production?

**Comment by olamedia** [comment]
javascript wasn't made to run on servers.your turn.

**Comment by olamedia** [comment]
And by the way do you really expect that people who like to use "watch" will run extra console for you, even in development? Development chains are mostly automatic for years.
