### ISSUE TITLE
Gulp4 watch exit if it has dependent tasks

### ISSUE THREAD

**Issue by Aetet** [gulpjs/gulp#922]
Hello.
There's some problem with watch in gulp 4.0 from master, if using dependencies for watch task. Example:
```js
var gulp = require('gulp');

var config = {
  src: {
    scripts: ['index.js', 'lib/**/*.js']
  },
  dest: {
    scripts: 'dist'
  }
};

gulp.task('build', function () {
  return gulp.src(config.src.scripts)
    .pipe(gulp.dest(config.dest.scripts));
});

gulp.task('watch', gulp.parallel('build'), function () {
  gulp.watch(config.src.scripts, 'build');
});
```
After execution 'build' task, 'watch' task will ended too. This relevant for both `.parallel` and `.series`.

But if we haven't dependencies like:
```js
gulp.task('watch', function () {
  gulp.watch(config.src.scripts, 'build');
});
```
everything works like charm. Is it bug or default behaviour?

**Comment by heikki** [comment]
Your watch task syntax is wrong. Try this instead:

```js
gulp.task('watch', gulp.parallel('build', function () {
  gulp.watch(config.src.scripts, 'build');
}));
```

ps. there is no dependencies, just functions that are being composed with series / parallel.

**Comment by Aetet** [comment]
Ok, thanks.
