### ISSUE TITLE
Document updated gulp.watch syntax for gulp 4.0

### ISSUE THREAD

**Issue by kincaidoneil** [gulpjs/gulp#925]
I recently updated to the 4.0 branch, however, I'm experiencing an issue in which using a function as a callback to `gulp.watch` results in nothing being based through to the `event` variable, as I particularly use `event.path`.

Here's my code:
```
gulp.watch('app/index.html', function(event) {
	console.log(event);
	console.log(event.path);
});
```

Here's what the console returns after the file is updated:
```
[Function: done]
undefined
```

Even if I pass through `gulp.series('name_of_task_here')`, it passes through the same thing to the first parameter.

Is there anything I'm doing wrong/was this method deprecated in gulp 4.0? If so, is there a better alternative?

Thanks!

**Comment by heikki** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/API.md#tasks

**Comment by phated** [comment]
The watch syntax is changing in 4.0. Since everything is based on function composition, the watch tasks receive an async `done` callback (and handles streams/promises/etc being returned).

If you need to access the event object, use:

```js
var watcher = gulp.watch('app/index.html');
watcher.on('change', function(event){

});
```

**Comment by phated** [comment]
Changing title to "Document updated watch syntax"

**Comment by contra** [comment]
Should be in the changelog on the 4.0 branch

**Comment by phated** [comment]
[Done!](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#gulpwatchglob-opts-tasks) - Thanks @dinoboff

**Comment by lkraav** [comment]
> watcher.on('change', function(event){

Is `watcher.on('add change', function(event){` also supposed to work? It's not firing for me, while `'change'` alone is.

**Comment by phated** [comment]
I doubt it, the emitter is just a node EventEmitter as far as I am aware. Please review `chokidar` docs for event support.
