### ISSUE TITLE
Trying to precompile html templates in to one js file

### ISSUE THREAD

**Issue by venkateshwar** [gulpjs/gulp#926]
Hi, 

In my project, I have many .html template files with lodash variables. I want this template strings to be gathered and added to a single template.js file using gulp.

For example:

header.html

    <header>Hello 
              <span><% user%></span>
    </header>

footer.html
  
     <footer>go to <%link%></footer>

###Result:  (_in template.js_)

     var templates = {
              "header" : "<header>Hello <span><% user%></span></header>",
              "footer" : "<footer>go to <%link%></footer>"
     }

How should I write in gulp to do like this?

I stucked here:  (gulpfile.js)

	var gulp = require("gulp");

	gulp.task("generateJsTemplate", function(){
		gulp.src('app/templates/*.html')
			.pipe(gulp.dest('demo.js'));
	});

**Comment by heikki** [comment]
Support questions http://stackoverflow.com/questions/tagged/gulp
