### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by examinedliving** [gulpjs/gulp#927]
First.  Gulp is the shit.  
Second, I created a new logo for Gulp.  If you want it, it's yours.  If not, just close this issue, and proceed as you were.

Here it is:
![gulpjs](https://cloud.githubusercontent.com/assets/3099093/6382542/91e79a90-bd17-11e4-88dc-13d95848785b.png)

(I'll make source files available upon request)

**Comment by heikki** [comment]
No thanks :)

Artwork lives here btw -> https://github.com/gulpjs/artwork

**Comment by RobertHerhold** [comment]
@examinedliving I really like it!
+1
