### ISSUE TITLE
Problem in static scripts output with gulp-rev and gulp-inject

### ISSUE THREAD

**Issue by WhaleWatching** [gulpjs/gulp#930]
The gulpfile.js I wrote is [Common gulpfile.js](https://gist.github.com/WhaleWatching/bf96355179d95c5daf95).

In a `build` task, `inject` should inject all static files into html outputs, but it inject nothing in the clean build , I must run same command(here is `gulp -p project build`) twice(`gulp -p project build && gulp -p project build`) to inject them successful.

I have tried use [run-sequence](https://github.com/OverZealous/run-sequence), it helps nothing.

Is this a bug?

Thanks :)

**Comment by heikki** [comment]
Support questions http://stackoverflow.com/questions/tagged/gulp
