### ISSUE TITLE
Deletes .gitkeep despite negate pattern?

### ISSUE THREAD

**Issue by kyotoprotokollet** [gulpjs/gulp#932]
I'm using the following code, after the documentation example:

    // Clean our dist folder before we generate new content into it
    gulp.task('clean', function (cb) {
      del([
        // here we use a globbing pattern to match everything inside the `dist` folder
        'dist/**',
        // we don't want to clean this file though so we negate the pattern
        '!dist/.gitkeep'
      ], cb);
    });

However despite using this negate pattern the entire dist folder get's deleted, including the .gitkeep file. Am I doing something wrong or is this not working as intended?

**Comment by sindresorhus** [comment]
Dotfiles aren't matched by globbing patterns by default. You can turn it on in the options.
