### ISSUE TITLE
Nondeterministic/inconsistent builds

### ISSUE THREAD

**Issue by zachahn** [gulpjs/gulp#933]
I have a fairly large project that isn't giving me a consistent number of built files. From what I can tell, this is true for both my Mac and Linux boxes.

Builds have been working fine previously, but I wanted to make some build changes to the project.

I apologize in advance for the super long issue.. but most of it is skimmable.

Any help/input would be appreciated!

### Expected output

On both Linux and Mac, I seem to get about one correct build per day.

The discrepancy between the correct Linux and Mac builds (780 total vs 784 total) comes from the fact that Linux was a fresh clone before I changed any of the configs. The config folder has 4 extra files under Mac.

#### Linux (correct)

```
$ for i in $(find build -maxdepth 1 -type d) ; do echo $i ; ( find $i -type f | wc -l ) ; done
build
780
build/models
57
build/views
265
build/libs
230
build/routes
56
build/config
7
build/utils
114
build/jobs
5
build/actions
5
build/controllers
40
```

#### Mac (correct)

```
$ for i in $(find build -maxdepth 1 -type d) ; do echo $i ; ( find $i -type f | wc -l ) ; done
build
     784
build/actions
       5
build/config
      11
build/controllers
      40
build/jobs
       5
build/libs
     230
build/models
      57
build/routes
      56
build/utils
     114
build/views
     265
```

### Inconsistent output (Mac)

Here is the result of four consecutive runs.

```
$ for i in $(find build -type d -maxdepth 1) ; do echo $i ; ( find $i -type f | wc -l ) ; done
build
     571
build/config
      11
build/controllers
      40
build/jobs
       1
build/libs
     146
build/models
      12
build/routes
       2
build/utils
      93
build/views
     265
```

With three more consecutive runs, the total number of built files are `555`, `572`, and `573`.

This is how I invoked the commands:

```
$ gulp clean; gulp build; echo $?
[18:29:13] Requiring external module coffee-script/register
[18:29:15] Using gulpfile ~/project/gulpfile.coffee
[18:29:15] Starting 'clean'...
[18:29:15] Finished 'clean' after 11 ms
[18:29:15] Requiring external module coffee-script/register
[18:29:16] Using gulpfile ~/project/gulpfile.coffee
[18:29:16] Starting 'build'...
[18:29:23] Finished 'build' after 6.58 s
0
```

### gulpfile

```coffee
coffee = require 'gulp-coffee'
tap = require 'gulp-tap'

src = [
  'app.coffee'
  'controllers/**/*'
  'libs/**/*'
  'models/**/*'
  'routes/**/*'
  'utils/**/*'
  'actions/**/*'
  'jobs/**/*'
  'config/**/*'
  'views/**/*'
]

BUILD_DIR = 'build'

gulp.task('build', (done) ->
  gulp.src(src, { base: __dirname })
    .pipe(tap (file, t) ->
      if (path.extname(file.path) == '.coffee')
        return t.through(coffee, [])
    )
    .on('error', _handleError)
    .pipe(gulp.dest(BUILD_DIR))
)

# sorry if there are typos, I'm not pasting directly
```

### package.json

```
    "gulp": "~3.8.8",
    "gulp-coffee": "~2.2.0",
    "gulp-tap": "~0.1.3",
```

**Comment by heikki** [comment]
A repo that reproduces the issue would be helpful.

**Comment by zachahn** [comment]
The project is actually a company product, so I can't provide access to that unfortunately.

I tried reproducing the error on a small repository of about three files, but I couldn't reproduce the error.

I'll see what I can do.

**Comment by heikki** [comment]
Lightweight alternative is to src stuff from node_modules. The simpler the repo, the easier it is to pinpoint the problem.

**Comment by phated** [comment]
Don't use gulp-tap, use gulp-if for your conditional.  You can't return a stream from the callback in another stream without a ton of hackery which gulp-if does for you.  I'm going to close this as it is a support question and should be on stackoverflow.

**Comment by zachahn** [comment]
My bad, thought it could have been a bug. Using `gulp-if` solved it, thanks for the help!
