### ISSUE TITLE
Plugin repository returning 404

### ISSUE THREAD

**Issue by rk** [gulpjs/gulp#935]
I hit an issue yesterday and figured it was temporary, but it looks like the [plugin page](http://gulpjs.com/plugins/) won't load packages.

> XMLHttpRequest cannot load http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,…odified,homepage,version&from=0&q=keywords:gulpplugin,gulpfriendly&size=20. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gulpjs.com' is therefore not allowed access. The response had HTTP status code 404.

When I access the link the response is a genuine 404 error unrelated to the CORS headers or AJAX request.

**Comment by heikki** [comment]
Closing in favor of https://github.com/gulpjs/plugins/issues/168
