### ISSUE TITLE
Somewhere [object Object] is printed

### ISSUE THREAD

**Issue by binarykitchen** [gulpjs/gulp#939]
I have a couple of gulp tasks running and upon completion, just when gulp is about to exit, `[object Object]` is printed to the console.

No idea where this comes from. No idea if this is a gulp issue or caused by a module.

Any suggestions how I can debug this best?

**Comment by contra** [comment]
overwrite console.log before your gulpfile runs to throw an error if the message is not a string and then check the stack

**Comment by binarykitchen** [comment]
Ah, thanks! I figured out, it was a Java child process I spawned throwing a NullPointerException.

But I had this line

```
leinProcess.stderr.pipe(process.stderr)
```

which should have printed a string instead of an object.

Or should I use a different code for that?

**Comment by contra** [comment]
stdio inherit, but thats unrelated to gulp

**Comment by binarykitchen** [comment]
Well, stdio inherit is nice but I need the stdout stream to interpret some data as well ... (for being off-topic here, just need a little help if you do not mind?)

**Comment by heikki** [comment]
Ask on http://stackoverflow.com and provide enough information.

**Comment by binarykitchen** [comment]
Okay, here http://stackoverflow.com/questions/28801250/somewhere-object-object-is-printed
