### ISSUE TITLE
Gulp can't generate new files on Windows 7

### ISSUE THREAD

**Issue by Clunt** [gulpjs/gulp#940]
nodejs v0.10.36
gulp v3.8.10
```
var gulp = require('gulp');
gulp.task('default', function() {
  return gulp.src('main.css').pipe(gulp.dest('style/'));
});
```
When I run `gulp`,Nothing can be found

**Comment by callumacrae** [comment]
Does main.css exist in the same directory as the gulpfile?

You can check whether a glob is matching using [gulp-debug](https://www.npmjs.com/package/gulp-debug).

**Comment by phated** [comment]
Either duplicate of #374 or a support question.  Support questions should be directed to http://stackoverflow.com/questions/tagged/gulp

**Comment by Clunt** [comment]
Thanks for you reply, I use mac now and it works.
