### ISSUE TITLE
Can't use task/src/dest/etc directly

### ISSUE THREAD

**Issue by pikeas** [gulpjs/gulp#942]
If I use:

    #coffeescript
    {task} = require 'gulp'

or

    #javascript
    task = require('gulp').task

and then:

    task('build', ...)

This throws an error:

    /Users/pikeas/Documents/code/consult/node_modules/gulp/node_modules/undertaker/lib/task.js:14
      this.set(name, fn);
          ^
    TypeError: Cannot read property 'set' of undefined
      at task     (/Users/pikeas/Documents/code/consult/node_modules/gulp/node_modules/undertaker/lib/task.js:14:7)

**Comment by phated** [comment]
@contra I'm not going to hard bind the functions of undertaker. Gulp is a singleton instance of it. Destructuring isn't going to work

**Comment by heikki** [comment]
I find it suprising that this fails:

```js
var gulp = require('gulp');
var task = gulp.task;

task('default', function() {
	console.log('Running default task');
});
```

**Comment by callumacrae** [comment]
Why is that surprising? That's how objects and functions work in JavaScript.

**Comment by heikki** [comment]
> That's how objects and functions work in JavaScript.

Well, you could say that about every error :smile:

*[Looking from the user perspective]*
Suprising because gulp.task is a function and it needs to be used in a certain way. Why do I need to know that gulp is a singleton or anything else about implementation?

**Comment by callumacrae** [comment]
It's a method, not a function.

```js
var log = console.log;
log('test'); //=> TypeError: Illegal invocation
```

The error is slightly more helpful, but it's the same thing!

**Comment by heikki** [comment]
```js
// gulp.js
var tasks = {};

module.exports = {
	task: function(name, fn) {
		tasks[name] = fn;
	},
	run: function(name) {
		tasks[name]();
	}
};
```

```js
// test.js
var gulp = require('./gulp');
var task = gulp.task;
var run = gulp.run;

task('foo', function() {
	console.log('foo called');
});

run('foo');
```

**testing..**

```sh
node test.js 
foo called
```

**Comment by callumacrae** [comment]
Sure, but then you're just using the object for storage, and not as an actual object, which somewhat defeats the point.

Also, `task` is defined in a different file to `run`. You'd have to have another separate object which basically does what the undertaker object does now in order to do what your example does: https://github.com/phated/undertaker/blob/master/lib/task.js

**Comment by phated** [comment]
The underlying libraries to gulp (orchestrator now and undertaker next) are and will continue to be classes.  This isn't a bug with gulp4 because the same crash happens if you try the same thing in orchestrator.  This also allows us to expose the constructor which lets devs use their own instance (or multiple), see https://github.com/gulpjs/gulp/blob/master/index.js#L43-L44

**Comment by pikeas** [comment]
So, two questions:

1) What's the right way to pull out task/src/dest? My JS isn't super strong because I'm more of a backend engineer, so I'm not clear on the mechanics of why this is tricky.
2) If this won't be changed to support `task = gulp.task` (ditto src/dest/etc), I suggest that a more helpful error message be thrown instead, like the Chrome example above.

**Comment by callumacrae** [comment]
> 1) What's the right way to pull out task/src/dest? My JS isn't super strong because I'm more of a backend engineer, so I'm not clear on the mechanics of why this is tricky.

Don't pull them out. Just call them on the gulp object like the README says:

```
gulp = require 'gulp'

gulp.task 'build', ...
```

If you really want to, you can do this, but it's not nice:

```
gulp = require 'gulp'
task = gulp.task.bind(gulp)
```

Why do you want to pull them out so bad, though?
