### ISSUE TITLE
gulp.src doesn't return files in order, very rarely

### ISSUE THREAD

**Issue by collinsethans** [gulpjs/gulp#946]
gulp: 3.8.11, node: v0.12.0, Debian squeeze

I am new to gulp, trying to move parts of our build process from bash scripts to gulp.

On very rare occasions (this is the 3rd time out of approx 100/150 runs), I am finding that gulp.src is not returning files in the order provided to it. It's difficult to reproduce it. Last time I had embedded debug messages in the gulp task and today when it re occurred, I got the log. The only thing common in these instances are that they are the first run of gulp after system restart and gulp takes much longer time to process.

The gulp task I am using is here: http://stackoverflow.com/a/28774788/235415. It's basically concatenating JS files, after processing and prepending licenses to them.

In the task, I had placed debug after gulp.src and before cache, like this:

    each(jsConfig.post_jq.srcList, function(val, key, array) {
        var is_run_lint   = isProduction ? false : val.run_lint;
        var _src = val.src.map(function(el) {return srcBaseDir + el;});
        console.log('_src order: ' + _src);

        var stream = gulp.src(_src)
          .pipe( debug({title: 'before cache:'}) )
          .pipe( cache('scripts') )
          ....

I find in the log that the debug print of _src is in the order expected, but the prints with 'before cache:' is in different order, where the last item in the jsConfig is first, followed by the first two in order. The resultant merged JS is thus not in the correct order, but as in 'before cache:'.

The log (tpm.js == ih-1.js in SO post and that src has only this js file):

    [20:45:52] Using gulpfile ~/gulpfile.js
    [20:45:52] Starting 'build:js'...
    _src order: /home/ethan/srv/tpm_ws/tpm/static/css_js/js/opensource/bootstrap.js
    _src order: /home/ethan/srv/tpm_ws/tpm/static/css_js/js/opensource/jquery.lazyload.js
    _src order: /home/ethan/srv/tpm_ws/tpm/static/css_js/js/tpm.js
    streams.length: 3
    [20:45:52] Finished 'build:js' after 245 ms

    [20:45:52] before cache: srv/tpm_ws/tpm/static/css_js/js/tpm.js
    [20:45:52] after cache: srv/tpm_ws/tpm/static/css_js/js/tpm.js
    [20:45:53] before remember: srv/tpm_ws/tpm/static/css_js/js/tpm.js
    [20:45:53] before cache: 1 items
    [20:45:53] after cache: 1 items
    [20:45:53] before cache: srv/tpm_ws/tpm/static/css_js/js/opensource/bootstrap.js
    [20:45:53] after cache: srv/tpm_ws/tpm/static/css_js/js/opensource/bootstrap.js
    [20:45:53] before remember: srv/tpm_ws/tpm/static/css_js/js/opensource/bootstrap.js
    [20:45:53] before cache: 1 items
    [20:45:53] after cache: 1 items
    [20:45:53] before cache: srv/tpm_ws/tpm/static/css_js/js/opensource/jquery.lazyload.js
    [20:45:53] after cache: srv/tpm_ws/tpm/static/css_js/js/opensource/jquery.lazyload.js
    [20:45:53] before remember: srv/tpm_ws/tpm/static/css_js/js/opensource/jquery.lazyload.js
    [20:45:53] before cache: 1 items
    [20:45:53] after cache: 1 items
    [20:45:53] before remember: 3 items
    [20:45:53] after remember: srv/tpm_ws/tpm/static/css_js/js/tpm.js
    [20:45:53] after remember: srv/tpm_ws/tpm/static/css_js/js/opensource/bootstrap.js
    [20:45:53] after remember: srv/tpm_ws/tpm/static/css_js/js/opensource/jquery.lazyload.js
    [20:45:53] after remember: 3 items

The output JS has tpm.js, bootstrap.js and jquery.lazyload.js concatenated in that order, instead of bootstrap,lazyload and tpm.

**Comment by contra** [comment]
Show the whole pipeline, probably a plugin before concat that is losing the order

**Comment by collinsethans** [comment]
Here's the JSON config object:

    var jsConfig = {
        post_jq: {
            output_file: 'core.js',
            srcList: [ {
                name: 'bootstrap',
                // The 'src' is kept offset from srcBaseDir (calculated below).
                src: ['js/opensource/bootstrap.js'],
                run_lint: false,
                run_uglify: true,
                drop_console: true,
                license: '/* <bootstrap license> */'
            }, {
                name: 'lazyload',
                src: ['js/opensource/jquery.lazyload.js'],
                run_lint: false,
                run_uglify: true,
                drop_console: true,
                license: '/* <lazyload license> */'
            }, {
                name: 'tpm',
                src: ['js/tpm.js'],
                run_lint: true,
                run_uglify: false,
                drop_console: false,
                license: ''
            } ]
        }
    }

And here's the complete task, as-is:

    gulp.task('build:js', function() {
        var streams = [];

        each(jsConfig.post_jq.srcList, function(val, key, array) {
            var is_run_lint   = isProduction ? false : val.run_lint;
            var _src = val.src.map(function(el) { return srcBaseDir + el; });
            console.log('_src order: ' + _src);

            var stream = gulp.src(_src)
              .pipe( debug({title: 'before cache:'}) )
              .pipe( cache('scripts') )
              .pipe( debug({title: 'after cache:'}) )

              .pipe( gulpif(is_run_lint, jshint('.jshintrc')) )
              .pipe( gulpif(is_run_lint, jshint.reporter('jshint-stylish')) )

              .pipe( gulpif(isProduction || (val.run_uglify && val.drop_console),
                                        uglify({compress:{drop_console:true}}),
                                            gulpif(val.run_uglify, uglify())
                            ) )

              // Notes on tap usage in docs/gulp/gulp_js_build_notes.txt.
              .pipe( tap(function(file) {
                      // file is provided here with full path. Hence.
                      var _cur_file_base = path.basename(file.path);
                      var _is_first_file = 
                           (path.basename(_src[0]) === _cur_file_base) ? true:false;
                      var _is_last_file = 
                           (path.basename(_src[_src.length-1]) === _cur_file_base) ?
                                true: false;

                      // If the license text is empty, don't add an extra newline.
                      var _license = (val.license.length > 0) ? val.license+'\n':'';

                      // In a bunch, first file gets license header, last file
                      // gets newline appended and middles ones are concatenated.
                      if (_is_first_file) {
                          file.contents = Buffer.concat([new Buffer(_license),
                                                        file.contents]);
                      }
                      if (_is_last_file) {
                          file.contents = Buffer.concat([file.contents,
                                                         new Buffer('\n')]);
                      }
                      return file.contents;
                    }) );

            streams.push(stream);
        });

        console.log('streams.length: ' + streams.length);
        es.merge.apply(this, streams)
          .pipe( debug({title: 'before remember:'}) )
          .pipe( remember('scripts'))       // add back all files to the stream
          .pipe( debug({title: 'after remember:'}) )
          .pipe( concat(jsConfig.post_jq.output_file, {sep: ''}) )
          .pipe( rename({suffix: outputFileSuffix}) )
          .pipe( gulp.dest(outputDir) );
    });

**Comment by contra** [comment]
What exactly is this task supposed to do? This seems so overly complex

**Comment by collinsethans** [comment]
This has been my first task. Thanks for the feedback on it's complexity, that helps.

I describe the objectives of the task below. Note that much of the pipeline was borrowed/inspired from a gulp sample using cache/remember/tap plugins.


Objectives:
- Concatenate the JS packages in order, as given by jsConfig (has other control options, and the 'name' field in jsConfig is not used). Using 'foreach' on jsConfig to process them in order.

- Ugligy/remove-console.log:
  - Development build: Per package config via jsConfig
  - Production build: Mandatorily run.

- jslint: Per pkg config via jsConfig (like not to run for unmodified opensource packages).

- License txt: We often modify downloaded opensource files, even split them as necessary. All files for a given pkg are in 1 src, in jsConfig. We prepend the license file to the first src only (using 'tap' plugin) and append a newline to the last src of that pkg.
  Our license text can be smaller than what is there on the opensource's un-minified version (generally, similar to their minified version). 

An observation with the logs:
Before the gulp.src, I am prepending actual path to each of the src's relative one in jsConfig. (Didn't use 'base' of gulp.src, faced some initial issues with 'watch').

In the captured log provided above, I found that the logs with '_src order' are in correct order, but the logs with 'before cache', which is immediately after gulp.src, is not correct. Does this point give any clue on the issue?

**Comment by eth0lo** [comment]
The problem in your task is ``event-stream`` the ``merge`` method [does not support ordering](https://github.com/dominictarr/event-stream#merge-stream1streamn-or-merge-streamarray) they are taken in the order of they are done, so smaller files will arrive first, most likely.

You should look at [serial joins](https://github.com/osscafe/gulp-cheetsheet/raw/master/dist/en-js-p2.pdf) in the cheat sheet for reference; or maybe try [gulp-order](https://github.com/sirlantis/gulp-order), personally I never used the later

**Comment by phated** [comment]
Seems like @eth0lo has answered this.  Closing.

**Comment by collinsethans** [comment]
I don't think merge is the real problem here, but in the initial pipeline with gulp.src. Look at the logs in 1st post, especially the ones with '_src order' and 'before cache', which are just above and below the 'gulp.src'. The '_src order' shows the correct ordering, while 'before cache' has it different.

@contra Do you have any feedback? I was waiting for your simplified version, as you had mentioned.

@phated Can you keep this open for a while.

**Comment by phated** [comment]
@collinsethans contra was telling you to simply your overly complex code. 99.9% of all issues opened on this tracker are due to badly behaving plugins, and as @eth0lo said, event-stream doesn't support ordering.

**Comment by collinsethans** [comment]
@phated Ok. Can you look at the structure of my code once again -- I first use 'foreach' (step 2 in below snippet) to process each of the files and push them to an array (5 below). _Only after that_, I use the es.merge with the array input (7). 'foreach' is widely used as I understand and I didn't yet figure any bug report there. The _reported problem manifests right at the top, if you refer to the logs from below step 3 and 4 in my 1st post_.

Below is the simplified structure for you to understand my code flow, with numbering to map with the logs in 1st post:

    gulp.task('build:js-post_jq', function() {
        var streams = [];    // 1

        each(jsConfig.post_jq.srcList, function(val, key, array) {  // 2
            var _src = val.src.map(function(el) {
                                       return srcBaseDir + el;
                                   });
            console.log('_src order: ' + _src);   // 3

            var stream = gulp.src(_src)
              .pipe( debug({title: 'before cache:'}) ) // 4
              .pipe( cache('scripts') )
               ....
              .pipe(...);

            streams.push(stream);   // 5
        });

        console.log('streams.length: ' + streams.length);   // 6
        es.merge.apply(this, streams)           // 7
            .pipe(...);
    });

Would appreciate if you can take some time in pointing out where I am going wrong in my observation before the es.merge.apply.

**Comment by eth0lo** [comment]
You are generating three pipe lines there that are getting merged together with ``es.merge`` and since each of those pipes can end at any time that's why you see the error.

If you don't want to sync them manually, I would feed the ``gulp.src`` with the array of files instead, that should also solve your problem

**Comment by collinsethans** [comment]
@eth0lo Thanks for your reply and pointer to streamqueue. With the above code, I actually have been under the assumption that `foreach() {}` will complete first with it's array population and then comes in the merge.apply. So that's not the case.

I had initially thought of feeding `gulp.src` with the array, but dind't know how to do it for our requirement.

I have switched over to `streamqueue`. The current version looks like this:

    gulp.task('build:js-post_jq', function() {
        var streams = streamqueue({ objectMode: true });       // new 1

        each(jsConfig.post_jq.srcList, function(val, key, array) {
            var _src = val.src.map(function(el) { return srcBaseDir + el; });
            console.log('_src order: ' + _src);

            var stream = gulp.src(_src)
              .pipe( debug({title: 'before cache:'}) )
              .pipe( cache('scripts') )
              ...
              .pipe(...);

            streams.queue(stream);          // new 2
        });

        return streams.done()               // new 3
          .pipe(...);
    });

I am testing this out. The earlier problem _was very difficult to reproduce_, which used to manifest only when it's run after reboots and consuming much of the system RAM with other apps. Will update after a few days on the findings.

**Comment by eth0lo** [comment]
You are were not feeding it with an array, that's the problem, you are feeding ``gulp.src`` with only one item of your array.

```
foreach(jsConfig.post_jq.srcList, function(val, key, array) {
        var _src = val.src.map(function(el) { return srcBaseDir + el; });

        var stream = gulp.src(_src)
```
Your ``_src`` is only one file

**Comment by collinsethans** [comment]
@eth0lo Thanks for your time and help. The reported problem is now fixed with streamqueue, there hasn't been any sighting since.

However, I am facing a new problem and this is very rare. When using `gulp watch`, if I update one of the js files (3 js files declared in jsConfig) `watch` is getting triggered but `gulp.src` is not returning it. This happens after a very long usage of gulp watch and is very rare.

My code is same as mentioned earlier. Copied here for convenience:

    gulp.task('build:js-post_jq', function() {
        var streams = streamqueue({ objectMode: true });       // new 1

        foreach(jsConfig.post_jq.srcList, function(val, key, array) {
            var _src = val.src.map(function(el) { return srcBaseDir + el; });
            console.log('_src order: ' + _src);

            var stream = gulp.src(_src)
              .pipe( debug({title: 'before cache:'}) )
              .pipe( cache('scripts') )
              ...
              .pipe(...);

            streams.queue(stream);          // new 2
        });

        return streams.done()               // new 3
          .pipe(...);
    });

When this happens, I see the log message `_src order:` reporting the file, but the debug msg `before cache` called after gulp.src (and subsequent dbgs in the chain) are not reporting it. Finally, the resultant js file doesn't hold it. I really don't know yet who is creating the issue here.
