### ISSUE TITLE
Search plugins on gulp's site doesn't work

### ISSUE THREAD

**Issue by devoll** [gulpjs/gulp#947]
Hi,
I try to search plugins on the main site (http://gulpjs.com/plugins/) and it is not work :(

```
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (plugins, line 7)
```

Safari 8.0.3
MacOS 10.10.2

**Comment by sweetolive** [comment]
Me too! It's possible that the server would be down.

**Comment by callumacrae** [comment]
Looks like registry.gulpjs.com is down

**Comment by contra** [comment]
Same as the other 100 complaints. Use NPM. I will fix it when I have a minute but I have been traveling extensively
