### ISSUE TITLE
Support returning multiple streams from gulp.task

### ISSUE THREAD

**Issue by marklagendijk** [gulpjs/gulp#95]
Currently when you are dealing with async streams, and want Gulp to know when the task is finished, you have 3 options:
1. Accept a callback
2. Return a stream
3. Return a promise

Could this be extended to include `Return an array of streams`, so the task is recognized as finished when all the streams are finished.

Currently I am using the following function as workaround:

``` js
function getStreamsFinishedPromise(streams){
    var deferred = Q.defer();
    var runningStreams = streams.length;

    streams.forEach(function(stream){
        stream.pipe(es.wait(function(){
            runningStreams--;
            if(runningStreams === 0){
                deferred.resolve();
            }
        }));
    });

    return deferred.promise;
}
```

**Comment by brianblocker** [comment]
:+1: for that recipe, fyi

**Comment by kevin-smets** [comment]
@mgcrea have you ever found a solution? Having the exact same issue with jade compilation..

**Comment by klick-barakgall** [comment]
Linked recipes just redirects to gulp main page...

**Comment by contra** [comment]
@klick-barakgall I just clicked the link, it works fine. Not sure what you're talking about.
