### ISSUE TITLE
Why does errLogToConsole suppress error?

### ISSUE THREAD

**Issue by cappslock** [gulpjs/gulp#952]
I'm trying to understand why passing `errLogToConsole: true` suppresses the error event from being emitted on the stream. I think it's useful for the stream to emit an error still so that the gulp process will fail and the process will have a non-zero exit code. If I want this to happen as it's built currently I have to do something like this:

```
        .pipe(sass({
            onError: function (error) {
                console.error('[gulp-sass] ' + error.message + ' on line ' + error.line + ' in ' + error.file);
                process.exit(1);
            }
        }))
```

Am I missing something?

**Comment by callumacrae** [comment]
That's a gulp-sass thing, not a gulp thing: https://github.com/dlmanning/gulp-sass#errlogtoconsole-true

I'm not sure I understand what you're saying anyway. You want the error to be thrown? Just don't set `errLogToConsole`.

**Comment by phated** [comment]
As @callumacrae said, this is not a gulp issue.

**Comment by cappslock** [comment]
Blargh, sorry, meant to open this on gulp-sass and had too many tabs open.

**Comment by cappslock** [comment]
As for what I'm saying, this issue is that you apparently have to choose
between useful human-readable output and useful machine-readable exit codes
which seems like a design flaw (in gulp-sass).
