### ISSUE TITLE
Does the browserify-uglify-sourcemap.md example work with AngularJS code?

### ISSUE THREAD

**Issue by binarykitchen** [gulpjs/gulp#954]
With my current AngularJS I fail to use this recipe
https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md

Not sure if the problem is on my side but I wonder if somebody else managed it to implement this recipe for an AngularJS app?

**Comment by phated** [comment]
Support questions http://stackoverflow.com/questions/tagged/gulp

**Comment by binarykitchen** [comment]
Ok, here http://stackoverflow.com/questions/29043701/does-the-browserify-uglify-sourcemap-md-example-work-with-angularjs-code
