### ISSUE TITLE
Gulp flags issue in node 0.12 (again)

### ISSUE THREAD

**Issue by grofit** [gulpjs/gulp#958]
I know there are a lot of issues on this already but they are all marked as closed as someone solved the issue. However I have tried all the solutions and none of them have worked so far.

```
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\gulp\node_modules\v8flags\cache\3.28.73.flags.json
```

I have just moved to node 0.12 and have uninstalled global and local gulp versions then re-installed them, have tried doing this in the specific order mentioned in the other threads, but it ultimately does not remove the error.

```
node -v
v0.12.0

npm -v
2.5.1

Windows 8.1 pro 64 bit
```

I am REALLY hoping it is something simple that I have overlooked but I have spent and hour googling and trying the solutions available but am still stuck :(

**Comment by contra** [comment]
@tkellen how often have these flags changed? can't we just hardcode a list in and manually update when new ones are added? that seems like less time used than managing all of the issues that keep coming in and also make gulp install at a normal speed

**Comment by grofit** [comment]
So given that you seem to know what this flags thing is about, what is the recommended way to solve the issue or work around it?

**Comment by tkellen** [comment]
@contra they can change quite frequently, eve between patch releases of
node. They also differ between io.js and node.

That said, I doubt if many people are using flags other than like,
`--harmony`. We could hardcode that into the liftoff config for gulp and
add more as requested.

With respect to installation speed, v8flags no longer runs during
installation--it caches flags async on the first run of gulp (or subsequent
runs where the flags have changed due to switching node versions).

**Comment by tkellen** [comment]
@grofit, have you cleared your npm cache? The errors you are seeing are not present in the most recent releases of Gulp.

**Comment by grofit** [comment]
oh have not done that, I assumed deleting was enough will try that and let you know if it fixes it.

**Comment by grofit** [comment]
Nope, tried removing local, global and cache clearning (`npm cache clear`) then reinstalling global and locally and still get same error.

**Comment by tkellen** [comment]
Somehow or another you aren't actually uninstalling gulp. The error you are
reporting references files that are not even a part of the current versions
of Gulp/v8flags.

**Comment by grofit** [comment]
ok will try to figure out why they are still stale and report back, if you have any ideas in the mean time let me know.

**Comment by phated** [comment]
The command is `npm cache clean` not clear

**Comment by grofit** [comment]
oh right, well uninstalled local gulp (project), global gulp (npm?) then ran cache clean and then installed global then local, still same thing.

I know on windows when you want to update npm you need to do some hoop jumping like executing `npm update npm" from within the npm folder or something, I will see if running the cache clean there will have any other effect.

**Comment by grofit** [comment]
FIXED!

So yes I had to go to:

`C:/Program Files/NodeJS` as an admin in the command line then do `npm cache clean` uninstall global, install global and it worked.

**Comment by phated** [comment]
Thanks for adding your steps to fix. Global installs and cleanup are really touchy on Windows.

**Comment by jkodroff** [comment]
I think `npm update npm` is also a necessary step in fixing the issue.
