### ISSUE TITLE
Support running task synchronously

### ISSUE THREAD

**Issue by marklagendijk** [gulpjs/gulp#96]
Currently tasks are run asynchronously both the dependencies specified in `gulp.task` and when running tasks via `gulp.run`.
However, sometimes you want to run multiple tasks synchronously. To achieve this, you have to write the following:

``` js
gulp.task('default', function(){
  var deferred = Q.defer();
  gulp.run('task1', function(){
    gulp.run('task2', function(){
      gulp.run('task3', deferred.resolve);
    });
  });

  return deferred.promise;
});
```

I tried cleaning this up myself, by using the following helper function.

``` js
function runSynchronized(tasks, deferred){
    // First call, create a deferred
    if(!deferred){
        deferred = Q.defer();
    }
    // Run the next task
    if(tasks.length){
        var task = tasks.shift();
        gulp.run(task, function(){
            // Recursive call with the remaining tasks
            runSynchronized(tasks, deferred);
        });
    }
    // All tasks are done, resolve the promise
    else{
        deferred.resolve();
    }

    // Return the promise
    return deferred.promise;
}
```

Which would be used as follows.

``` js
gulp.task('default', function(){
  return runSynchronized('task1', 'task2', 'task3');
});
```

However, for some strange reason, only the first task is run, because the callback function never gets executed. I have no idea why this isn't working.

I have 2 questions:
1. Why isn't my helper function working?
2. Would it be a good idea to add synchronous support to `gulp.run`?

**Comment by contra** [comment]
Update: gulp 4 is basically done and the new task system is in place. This problem is now solved very elegantly, async control flow in gulp is no longer a problem. Try out the 4.0 branch!
