### ISSUE TITLE
Document plugin API

### ISSUE THREAD

**Issue by nalbion** [gulpjs/gulp#962]
The [writing a plugin](https://github.com/gulpjs/gulp/tree/master/docs/writing-a-plugin) docs are very vague.  Could you please document the parameters and returns?

````
/**
 * Assumptions, strategy etc...
 * @param {*} paramsFromGulp (optional) any parameters or config that may be passed from a Gulp script to the plugin
 * @return {no idea} Promise? Vinly? Stream? ????
 */
module.exports = function(paramsFromGulp) {

    /**
     * Assumptions, strategy etc...
     * @param {Vinyl} file - but pretend I have little/no experience with Vinyl or Node
     * @param {string} enc - presumably "utf8" etc
     * @param {function(Error?, Vinyl);WhatDoesItReturn?}
     * @return Promise? Vinly? Stream? ????   Because a callback is passed in, do we need to return anything?
     */
    return through.obj(function(file, enc, cb) {
    }
};
````

**Comment by nalbion** [comment]
Can you provide any hints regarding the acceptance tests mentioned in "What happens if I don't follow them?"?

The "What does a good plugin look like?" section should explain why the example provided is a good looking plugin.

**Comment by phated** [comment]
All of this can be figured out by looking at the modules they reference. That being said, we are always open to documentation PRs.

**Comment by nalbion** [comment]
...or you could add a couple of lines of documentation and make it easier for everybody.
I've looked at some other gulp plugins, but they all seem to have been written by people who already know what they are doing.

Rather than expect people to do mental gymnastics, inferring how it is supposed to work by reading multiple other code bases, the "how to write a Gulp plugin" docs should at the very least document the contract between Gulp and the plugins.

----- Reply message -----

**Comment by nalbion** [comment]
If you can answer the questions, and/or correct any misinterpretations in my snippet then I'll happily submit it as a PR

----- Reply message -----

**Comment by phated** [comment]
Code is pretty impossible to critique as a comment in an issue. Please submit a PR with these docs so we can critique inline as per the contribution guidelines. Thanks for the time you've put into making gulp better for newcomers.
