### ISSUE TITLE
gulp4 release plan?

### ISSUE THREAD

**Issue by tcurdt** [gulpjs/gulp#968]
Seems like most open gulp4 issues are just enhancements.
The milestone date is one month back in the past.
What's the plan for a release of gulp4?

**Comment by phated** [comment]
I'm sick of these issues so I've removed any sort of date associated with the milestones.  We are trying to solve some major blocking issues that no one has really contributed to fixing.  We've also had a lack of people contributing doc updates but @dinoboff has done most of it as of last week.  We could still use help polishing all the docs.

**Comment by tcurdt** [comment]
@phated seems like only enhancements are tagged as gulp4 - or are these 3.x issues that also apply to 4? What issues are the blockers? What areas of the docs need polishing?

**Comment by phated** [comment]
Biggest blocker is https://github.com/gulpjs/gulp-cli/issues/7 which @heikki was working on but the solution is very hacky.
