### ISSUE TITLE
Using strings when registering with gulp.task

### ISSUE THREAD

**Issue by jmm** [gulpjs/gulp#969]
Re: this entry in the [changelog](https://github.com/gulpjs/gulp/blob/4502a9caead8de00d16765dc30c4e5f81e847d75/CHANGELOG.md):

> using strings when registering with `gulp.task` should only be done when you will call the task with the CLI

A) What is the point of this advice? Is it that you can omit the string (the `name` arg) to make a task *not* callable from the CLI?

There was a pretty confusing discussion about that [starting here](https://github.com/gulpjs/gulp/issues/355#issuecomment-49510427).

Will this be callable via the CLI (`gulp whatever`)?:

```js
gulp.task(function whatever () {});

// As opposed to
gulp.task('whatever', function () {});
```

B) The API documentation for `.task()` should discuss this, right?

C) It looks like it will be an error to do `gulp.task(function () { "I'm anonymous"; })`, but if so the documentation doesn't make that clear.

D) Is `displayName` meant to be part of the API or it's just for some internal use?

```js
var f = function () {};
f.displayName = 'whatever';
gulp.task(f);
```

**Comment by dinoboff** [comment]
You can use a string, the function name or its `displayName` to register a task. There no difference AFAIK. I think the change log should say operation only need to be registered with `gulp.task` if you need  it as CLI task (in gulp 3, you would need to register an operation if it was a dependency of a proper task).

You're welcome to send a PR for the documentation.

**Comment by jmm** [comment]
@dinoboff 
> But there no difference between the 3 way to set it AFAIK. I think the change log should say operation only need to be registered with `gulp.task` if you need it as CLI task (in gulp 3, you would need to register an operation if it was a dependency of a proper task).

Maybe that's what it is. To me there's no obvious reason for that instruction unless it has to do with visibility of the tasks to the CLI. The discussion I linked to on that subject was very confusing; maybe that carried over to this readme entry.

> You're welcome to send a PR for the documentation.

I should make sure I understand the API / intended behavior before I try to document it :)

**Comment by jmm** [comment]
I got more context on this issue from #802. I imagine the documentation for `.task()` will eventually be needing an update. I'm not sure how settled those issue are now though. For the time being the readme comment is very cryptic.

One straightforward case though:

```js
// No particular reason to use string
gulp.task(function build () {});

// Need to use string
gulp.task('build:clean' function () {});
gulp.task('build-clean' function () {});
```

**Comment by phated** [comment]
@jmm you are correct that the changelog is confusing.  We could definitely use a PR to clean that up and add more information for the 4.0 `task` API.  Strings should only be used as a hold over during migration.  Now that we support `Function.name` and `Function.displayName`, those 2 should be used over strings for task registration.  `Function.displayName` can (and should) be used for your `build:clean` or `build-clean` examples.  We still haven't decided whether strings will become deprecated in 4.0 or not, so it's best to just avoid them.

The phrasing should be closer to @dinoboff's suggestion: "gulp.task should only be done when you will call the task with the CLI" (removing the mention of strings).

@dinoboff would you be able to make changes to the changelog and docs to add the points I've outlined above?

**Comment by dinoboff** [comment]
Do you want to update the current README example to avoid task name string:
```js
var gulp = require('gulp');
var coffee = require('gulp-coffee');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var imagemin = require('gulp-imagemin');
var sourcemaps = require('gulp-sourcemaps');
var del = require('del');

var paths = {
  scripts: ['client/js/**/*.coffee', '!client/external/**/*.coffee'],
  images: 'client/img/**/*'
};

// Not all tasks need to use streams
// A gulpfile is just another node program and you can use all packages available on npm
gulp.task('clean', function(done) {
  // You can use multiple globbing patterns as you would with `gulp.src`
  del(['build'], done);
});

gulp.task('scripts', function() {
  // Minify and copy all JavaScript (except vendor scripts)
  // with sourcemaps all the way down
  return gulp.src(paths.scripts)
    .pipe(sourcemaps.init())
      .pipe(coffee())
      .pipe(uglify())
      .pipe(concat('all.min.js'))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('build/js'));
});

// Copy all static images
gulp.task('images', function() {
  return gulp.src(paths.images)
    // Pass in options to the task
    .pipe(imagemin({optimizationLevel: 5}))
    .pipe(gulp.dest('build/img'));
});

// Rerun the task when a file changes
gulp.task('watch', function() {
  gulp.watch(paths.scripts, 'scripts');
  gulp.watch(paths.images, 'images');
});

gulp.task('all', gulp.parallel('watch', 'scripts', 'images'));
// The default task (called when you run `gulp` from cli)
gulp.task('default', gulp.series('clean', 'all'));
```

**Comment by phated** [comment]
I'm satisfied with the documentation/changelog changes that @dinoboff made to clear this up.  Closing

**Comment by jmm** [comment]
@phated 
> Strings should only be used as a hold over during migration. Now that we support `Function.name` and `Function.displayName`, those 2 should be used over strings for task registration. `Function.displayName` can (and should) be used for your `build:clean` or `build-clean` examples. We still haven't decided whether strings will become deprecated in 4.0 or not, so it's best to just avoid them.

So that means you're going to have to do things like this?:

```js
buildClean.displayName = 'build:clean';
gulp.task(buildClean);
function buildClean () {}
```

It's obviously doable, and even straightforward, but I wouldn't call it elegant. What is the motivation for / why would it be important to deprecate strings (the `name` arg to `.task()`)? If it's a heavy-handed approach to pushing people to learn and use basic JS, then instead of everyone suffering, what about `throw`ing on `name` arguments that would be valid identifiers instead? Then you could just continue to do `gulp.task('build:clean', function () {})` when you need to.

**Comment by jmm** [comment]
My mistake, that example doesn't even currently work. At the moment you have to do something even less elegant like:

```js
var buildClean = function () {};
buildClean.displayName = 'build:clean';
gulp.task(buildClean);

// or

gulp.task(buildClean());
function buildClean () {
  var f = function () {
    // real function
  };
  f.displayName = 'build:clean';
  return f;
}
```

I see that @dinoboff has [suggested](dinoboff) giving `displayName` precedence over `name`.

**Comment by jmm** [comment]
Another argument against eliminating the `name` argument is a case like this from the [docs](https://github.com/gulpjs/gulp/blob/78751c834e1c7365f60dff7094c1d7e492b11997/docs/API.md#gulpseriestasks) where you just want to expose a series / parallel to the CLI:

```js
gulp.task('default', gulp.series('one', 'two', function(done) {
  // do more stuff
  done();
}));
```

Without `name` you'd have to (at best) do something clunky like:

```js
gulp.task(function () {
  var task = gulp.series('one', 'two', function (done) {
    // do more stuff
    done();
  });
  task.displayName = 'default';
  return task;
}());
```

But of course *that* doesn't even work currently because `gulp.series()` returns a function with a `name` prop.

**Comment by mischkl** [comment]
Maybe there could be something like a `seriesWithName()` function on offer which takes a string for the returned function name as the first argument?
