### ISSUE TITLE
Gulp 4 / browserify / foregoing a vinyl stream altogether

### ISSUE THREAD

**Issue by jmm** [gulpjs/gulp#970]
Can @phated or anyone elaborate on what [this comment](https://github.com/gulpjs/plugins/issues/47#issuecomment-47005358) was referring to?:

@phated
> Gulp 4 will make it even easier to use browserify + fs.createWriteStream in a task, forgoing a vinyl stream all together.

I don't see anything yet in the changelog that gives me a clue how browserify would integrate more easily with gulp 4 than previously.

**Comment by phated** [comment]
Currently, gulp doesn't work well with returning a `fs.createWriteStream`.  I forget the exact problem and it may have been solved upstream in orchestrator, but I'm not sure.

I highly recommend you use the [browserify recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md) in our docs, as it is, by far, the best way to use browserify with gulp and doesn't require blacklisted plugins.

**Comment by jmm** [comment]
@phated Yes, thank you, I'm aware of that technique and several others. I'm asking because I'm wondering if there will be some better native way to integrate them, or if an integration layer (a new "plugin" that avoids previous problems) makes sense (because I might write it).

That recipe unfortunately isn't so good.

1) It doesn't use vinyl-transform the way it's designed to work. Neither `browserify()` nor `browserify.bundle()` returns a transform stream, or a stream that is meant to be piped to or written to from outside of browserify.

2) So, it started breaking in recent versions of browserify. See for example:
* substack/node-browserify/issues/1044
* https://github.com/gulpjs/gulp/issues/369#issuecomment-69085871
* babel/babelify/issues/46
* https://github.com/hughsk/vinyl-transform/issues/5

3) Even if that were not an issue, I believe it only allows a single entry file.
