### ISSUE TITLE
Document `description` property of task functions

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#973]
This has landed in gulp-cli 4.0 branch but we should make sure to document it as part of the gulp docs.

**Comment by dinoboff** [comment]
I have an PR that conflict with that. Once it's merged, I can take care of that. 
- in docs/API.md: we could add a section to `gulp.src` to describe fn attributes Gulp uses (displayName and description)
-in docs/CLI.md: mention where the description is coming from.

**Comment by phated** [comment]
@dinoboff sounds good. I've merged the other 2 PRs

**Comment by dinoboff** [comment]
@phated I fixed my editor settings; it's trimming end of line in md files.

**Comment by phated** [comment]
The PR for these docs has been merged.  Thanks again @dinoboff
