### ISSUE TITLE
Source maps don't work for "Fast browserify builds with watchify" recipe

### ISSUE THREAD

**Issue by airandfingers** [gulpjs/gulp#981]
The [Fast browserify builds with watchify](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md) recipe uses gulp-sourcemaps to create a source map, but the generated source map is for bundle.js, not for the original src/index.js file.

I got source maps to work for me by following [christianalfoni's post](http://christianalfoni.github.io/javascript/2014/08/15/react-js-workflow.html); namely, the debug: true argument to the browserify call replaces gulp-sourcemaps.

**Comment by contra** [comment]
@airandfingers You can rename it to whatever you want for the sourcemaps, if you have a correction for the recipe send a PR

**Comment by contra** [comment]
This does raise the issue with debug: true not existing in the options passed to browserify though

**Comment by phated** [comment]
I've fixed this in https://github.com/gulpjs/gulp/commit/7176929f09905cc2e7a2bb93f53779b54c081536
