### ISSUE TITLE
error instalation glup

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [gulpjs/gulp#985]
hi, ihave archlinux and i install glup and i find this error !
npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.0
npm ERR! npm v2.7.1
npm ERR! file /root/.npm/minimatch/2.0.4/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /root/.npm/minimatch/2.0.4/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by contra** [comment]
nothing to do with gulp, but try again npm was probably down

**Comment by sidahmedbenkhaoua** [comment]
no it dos't work i try again many more

**Comment by phated** [comment]
Your package.json is malformed in your project.  This isn't a gulp problem.
