### ISSUE TITLE
gulp.watch() bad listen

### ISSUE THREAD

**Issue by HonzaBittner** [gulpjs/gulp#987]
Hi, I use gulp.watch() to watch changes in my Sass code.

It works, but in PhpStorm (which has an autosave) I have to press CTRL + S or I have open/click to my ruby console.

// I use WIN 7 - with console for ruby

```
var gulp = require('gulp'),
    rename = require('gulp-rename'),
    sass = require('gulp-ruby-sass'),
    autoprefixer = require('gulp-autoprefixer'),
    gutil = require('gulp-util');

// Compile Sass, autoprefix properties, generate CSS.
gulp.task('sass', function () {
    gutil.beep();
    return sass('src/sass/style.scss', {style: 'compressed'})
        .pipe(autoprefixer())
        .pipe(rename('main.css'))
        .pipe(gulp.dest('src/css/'));
        //.pipe(gutil.beep()); // beep when build is done
});

// Watch ['Sass'] change in files and run it at begin.
gulp.task('watch', ['sass'], function () {
    gulp.watch('src/sass/**/*.scss', ['sass']);
});
```

**Comment by callumacrae** [comment]
It doesn't save as you type, it saves when you defocus the window or manually save it.

**Comment by HonzaBittner** [comment]
@callumacrae so if I will chech the 3rd rule and set it to 1sec - it will work as well as I want to, right? :)

**Comment by callumacrae** [comment]
No, because you'll pause halfway through a statement, invalid SASS will be saved, and Gulp will quit.

Why would you want it to save as you type?

**Comment by HonzaBittner** [comment]
Well I do know in fact, maybe I am accustomed from PhpStorm SCSS watcher...

What benefits has building manual? :)

**Comment by callumacrae** [comment]
what?

**Comment by HonzaBittner** [comment]
@callumacrae Thank you for your help, you are right... :)
