### ISSUE TITLE
Browserify Recipe Fails Silently on Uglify

### ISSUE THREAD

**Issue by bhough** [gulpjs/gulp#990]
The Browserify recipe fails silently if gulp-uglify fails: https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md

Uglify should output information when it errors. Errors are logged in other recipes, so would like to add it for consistency as well.

**Comment by bhough** [comment]
I have submitted a PR to correct this: https://github.com/gulpjs/gulp/pull/991

**Comment by phated** [comment]
Merged and added a note about handling errors generically to the recipe.  Thanks for the PR!
