### ISSUE TITLE
Gulp.src fails for non existing files

### ISSUE THREAD

**Issue by marekmicek** [gulpjs/gulp#992]
Hi,

I am not sure if this is an expected behavior (as it worked previously without problems), simply

```
gulp.src(['./src/non-existing-file.json'])
        .pipe(gulp.dest('./dist/'));
```

is failing with a not very descriptive exception:

> Error: File not found with singular glob

**Comment by callumacrae** [comment]
Are you using 4.0? This error shouldn't be happening with gulp 3.

cc @contra

**Comment by marekmicek** [comment]
Yes I am using 4.0 branch.

**Comment by contra** [comment]
- if you give gulp a full path it will fail if it doesnt exist
- pass allowEmpty: true to disable this

https://github.com/wearefractal/glob-stream/pull/41

**Comment by marekmicek** [comment]
Thanks!
