### ISSUE TITLE
Error: Error: EACCES, open '/tmp/3.28.73.flags.json'

### ISSUE THREAD

**Issue by joshkel** [gulpjs/gulp#993]
Gulp 3.8.11 requires being able to access `/tmp/3.28.73.flags.json` (or similar). This can easily fail due to permissions issues on a multiuser system, as all users try to access the same file.

Observed in Node.js 0.10.38 (using NodeSource package on Ubuntu 14.10) and 0.12.0 (using NodeSource package on Ubuntu 14.04).

Gulp 3.8.10 did not have this issue.

**Comment by contra** [comment]
@tkellen

**Comment by tkellen** [comment]
This is being addressed in tkellen/js-v8flag#15

**Comment by tkellen** [comment]
who knew writing a temporary file was going to be such a nightmare.
