### ISSUE TITLE
why i failed to install gulp?

### ISSUE THREAD

**Issue by chapgaga** [gulpjs/gulp#995]
![](http://img.itc.cn/photo/jm19oaOS2kx)

npm ERR! Error: ENOENT, chmod 'D:\Tools\Dev\Now\npm_dir\node_modules\gulp\bin\gulp0.js'

but there is no such file there, what's wrong?

**Comment by phated** [comment]
Your node and npm install is insanely out of date.  Other than that, I don't know what the problem would be.  Installation problems should be reported to npm.
