### ISSUE TITLE
Cannot assign to read only property 'mark' of sass

### ISSUE THREAD

**Issue by ilianaza** [gulpjs/gulp#997]
I'm using ```gulpjs/gulp#4.0```. I've updated it this morning (after quite a while) and I started to get the following error while running my **watch-styles** task:

#### Error
```bash
[16:40:20] TypeError: Cannot assign to read only property 'mark' of sass
  at new Gaze (.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:41:13)
  at gaze (.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
  at Object.module.exports [as watch] (.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:24:17)
  at Gulp.watch (.../node_modules/gulp/index.js:26:14)
  at .../gulpfile.js:243:8
  at taskWrapper (.../node_modules/gulp/node_modules/undertaker/lib/set.js:17:15)
  at bound (domain.js:254:14)
  at runBound (domain.js:267:12)
  at asyncRunner (.../node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
  at process._tickDomainCallback (node.js:381:11)
```

#### gulpfile.js
```javascript
gulp.task('watch:styles', function () {
  gulp.watch(paths.sass, 'sass');
  ...
});

gulp.task('sass', function () {
  return gulp.src(paths.sass)
  .pipe(plumber())
  .pipe(using({ prefix: 'After changed:' }))
  .pipe(sourcemaps.init())
  .pipe(sass())
  .pipe(changed(paths.dirs.build))
  .pipe(sourcemaps.write('.', { sourceRoot: '/' }))
  .pipe(gulp.dest(paths.dirs.build))
  .pipe(grep('**/*.css', { read: false, dot: true }))
  .pipe(browserSync.reload({stream:true}));
});
```

Need some help with this one.

**Comment by phated** [comment]
We no longer support strings to the watch task. Please use gulp.parallel around your task name. There's a few issues, commits and the docs have been updated for this change. Sorry I can't link because I am answering from my phone.

**Comment by ilianaza** [comment]
Thank you. That worked!
```javascript
gulp.task('watch:styles', function () {
  gulp.watch(paths.sass, gulp.parallel('sass'));
  ...
});
```

**Comment by demisx** [comment]
@ilianaza  :+1: Just got hit myself with this after an `npm update`. Thank you for showing the solution!

**Comment by dschinkel** [comment]
gulp.parallel isn't recognized when I try to use it.  Is this supported still?

**Comment by sunilw** [comment]
@dschinkel if I gather correctly, gulp.parallel is only available from gulp 4.0.

**Comment by dschinkel** [comment]
thanks @sunilw

**Comment by sunilw** [comment]
@dschinkel I think my statement before might have been incorrect:

I don't actually know if 'gulp watch' is unusable on the latest stable version. From the version number (4.0) I should actually assume that this is a stable version.

However, afaict, 4.0 is not the version that 'npm install' will install by default. Nor is it the version that is contained in the master branch of gulp's github repo.

I'm currently trying to figure out how to install 4.0. If I manage to do it, and you haven't figured it out before me, then I'll let you know if I was able to get gulp.parallel() to work.

**Comment by sunilw** [comment]
This works to install gulp 4: npm install "gulpjs/gulp-cli#4.0" 

I'm not sure if this is ideam, because 'gulp --version' returns "Local version 4.0.0-alpha.1".
So now we are working with an alpha version of gulp.

**Comment by phated** [comment]
@sunilw no, you are using "edge" which is the latest and greatest.  There is a risk things will break, so we labelled it as version "4.0.0-alpha.1".  Please stop beating this old thread.
