### ISSUE TITLE
(gulp.watch): Issue with new opt-in symlink

### ISSUE THREAD

**Issue by vikrantpogula** [gulpjs/gulp#999]
I think the new opt-in symlink is not usable with gulp.watch. Other tasks seem fine after adding `{follow: true}`, but gulp watch doesn't trigger its task when I provide `{follow: true}`. I have illustrated my gulpfile below

Currently doesn't trigger the task 'refresh:scripts'
```
var watcher = gulp.watch([
  _settings.APP_PATH+'/**/*.js',
  _settings.APP_PATH+'/**/*.jsx',
], {follow:true}, 'refresh:scripts')
```

Raises Error now, but used to work fine (would watch and trigger 'refresh:scripts')
```
var watcher = gulp.watch([
  _settings.APP_PATH+'/**/*.js',
  _settings.APP_PATH+'/**/*.jsx',
], 'refresh:scripts')

TypeError: Arguments to path.resolve must be strings
```

This used to work fine with `4.0` before the `opt-in symlink following for blobs`.

**Comment by phated** [comment]
You are confused on the actual problem here. We no longer support strings as watch tasks. Please review the last few commits on the 4.0 branch to see the changes and new docs. Sorry I can't link things right now, I'm on my phone.

**Comment by vikrantpogula** [comment]
@phated No worries, Thank you !

**Comment by vikrantpogula** [comment]
I just thought so because the actual files I am watching in this particular case are actually symlinks !

**Comment by phated** [comment]
I'm going to close this and open a different issue to make that error more apparent.  Thanks.
